### ISSUE TITLE
THP on tcache avail array.

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#1000]
With opt.metadata_thp, enabling this should be beneficial as well.

**Comment by davidtgoldblatt** [comment]
Can we accomplish this just by allocating tcache contents out of the metadata allocator?

**Comment by interwq** [comment]
The only issue would be to reclaim tcache on thread death. Currently base allocator doesn't handle deallocation, so we would need to find a way to re-use these allocations or even purge them (they are 28k, so not exactly small).
