### ISSUE TITLE
output stats unavailable after process shutdown. 

### ISSUE THREAD

**Issue by sridharnsk** [jemalloc/jemalloc#1007]
We have a multi-threaded process using jemalloc version 4.5.0. Have enabled stats_print as below. The process is run under test for 24 hours and gracefully shutdown. But during shutdown we do not see any output stats. However when process is restarted and shutdown immediately stats are emitted.

sudo ln -s "narenas:24,stats_print:true" /etc/malloc.conf 

Kindly let me know if I am missing anything or any other information required.

**Comment by davidtgoldblatt** [comment]
The stats printing happens via an atexit call; we just delegate to the libc implementation. I'd look into why the atexit handler isn't getting invoked (perhaps you're terminating the process in an unusual way?).

> sudo ln -s "narenas:24,stats_print:true" /etc/malloc.conf

I assume this is just a typo in the question, but this isn't quite what you want (i.e. you want the symlink to be to a file with those contents, not a file with that name). If you copied and pasted, it's possible that there's some weird configuration thing going on.

**Comment by interwq** [comment]
Discussion happened on gitter (https://gitter.im/jemalloc/jemalloc?at=59a5f77666c1c7c477f587d5). Closing assuming no further questions.
