### ISSUE TITLE
Provide a realloc function that accepts the actually *used* size of the allocation as an additional parameter

### ISSUE THREAD

**Issue by stephan-tolksdorf** [jemalloc/jemalloc#101]
Sometimes you have to resize an allocation even though it is only partially filled. When jemalloc has to move this allocation in order to grow it, only the actually used bits need to be copied. For example, if you have an empty C++ vector whose capacity needs to be grown, then no data needs to be copied at all, even if the allocation has to be moved.

If there was a realloc function that had another size parameter specifying how much of the allocation is actually used (as a continuous segment starting at the front of the allocation), then you could avoid unnecessarily copying unused bits without having to do a cost-benefit analysis in the user code and falling back to a malloc-memcpy-free sequence when there's too much unused space.

**Comment by jasone** [comment]
It looks like this design conversation has wound down, so I'm going to close, without adding a sized reallocation API for the time being.  Thanks for hashing this out in detail!
