### ISSUE TITLE
virtual memory leakage

### ISSUE THREAD

**Issue by walter0722** [jemalloc/jemalloc#1014]
Hi,
We think jemalloc 4.4 happen some virtual memory leakage, specially at using setrlimt testcase or CTS 8.0_r1 pthread_leak#detach testcase.
Example:
the in-use heap amount of process is about 130KB, but the virtual memory heap of process is about 150MB.
we see the je_arenas[0].stats.mapped=0x400000 and je_arenas[1].stats.mapped=0x280000, so it should not use more big vma, but the process map show the [anon:libc_malloc] size is about 150MB.
Question:
1. Does the Jemalloc free chunk only to use madvise(dont_need) if it happened above the case?
2. Does the arenas record the vma to directly use them if need to allocate new chunk? so it is not to need call map() if allocate new chunk?

**Comment by davidtgoldblatt** [comment]
1. Yes, we'll madvise away memory that's not in use; a virtual memory leak shouldn't cause any increase in physical memory use.

2. Yes, we'll re-use virtual memory before allocating new memory, if we can.

That said, that sounds like a pretty large heap for such a small amount of RSS. Does your application go through phases in which it allocates and then releases a lot of memory quickly?

**Comment by interwq** [comment]
Closing for now. Feel free to let us know if any questions.
