### ISSUE TITLE
Force usage of extent hooks

### ISSUE THREAD

**Issue by dw09** [jemalloc/jemalloc#1016]
I would like to ensure that all future allocations on a thread come from extents created by custom extent hooks.

To this end, I first do some sanity checks:

- check jemalloc version via `mallctl("version", ...)` which gives `5.0.1-0....`
- check the number of default arenas with `mallctl("arenas.narenas", ...)`

Then I create a new arena and try to lock my thread to it:

- I do `mallctl("arenas.create", ...)` with extent hooks where I only set the `alloc` hook. The returned arena id is the next id after the default arenas, which seems sane.
- Assign thread: `mallctl("thread.arena", ...)` to that new arena.

When I now allocate a bigger chunk, it triggers my extent hook and everything works fine.

Problem:

When I allocate smaller chunks, say 8kB, then they will not come from memory allocated by my extent hook. I observe the same behavior even when using `mallocx(size, MALLOCX_ARENA(arena))` explicitly: Large chunks come from my custom extents, smaller ones not.

As a ugly workaround, I currently loop until the allocation comes from the expected range.

Is this expected behavior or a known issue?
Can I force allocation from extents created by my custom extent hook?

**Comment by interwq** [comment]
Hi, it sounds like you need to flush thread local cache (tcache). Likely the thread already had allocation activities and some items were still in tcache. Try the 'tcache.flush' API before setting the custom hooks.

**Comment by dw09** [comment]
Thank you for your answer!
Before, I've tried `thread.tcache.enabled` before and after arena creation to disable caching altogether and which should flush as well. That did not help, so I did not have much hope at first.

But then I realized that I have to flush each time when I want to switch between arenas because (I guess) the tcache is not a separate cache for each arena that a thread uses, but simply one tcache per thread, which makes sense of course. So now it works fine, Thank you!

**Comment by dw09** [comment]
I think that I have no permission to label this as a 'question' instead of a simple issue, so I'll just close this.

**Comment by interwq** [comment]
@dw09 : ```thread.tcache.enabled``` is a per thread switch. So you'll need to disable them for different threads separately. If you want to disable tcache globally, there is ```opt.tcache```, e.g. adding ```tcache:false``` to malloc_conf (however it may affect performance negatively by quite a bit).
