### ISSUE TITLE
Track and Reset "high water mark" of process memory?

### ISSUE THREAD

**Issue by felixendres** [jemalloc/jemalloc#1018]
Hi,

I would like to track the maximum memory usage of my (C++) application. If it has been beyond threshold before a checkpoint, the application should free up memory.
For this I would need something like the resident memory "high water mark" provided by linux, but resetable to the amount of memory used after freeing memory (the linux kernel provides resetting, but only from version 4.0, which I cannot use)

Is it possible to implement something like this with jemalloc's statistics? I saw there is high-watermark profile dumping (opt.prof_gdump), but couldn't track the functionality I need down in the code.

Thanks

**Comment by davidtgoldblatt** [comment]
This should be doable by tracking the "stats.active" mallctl -- see [the man page](http://jemalloc.net/jemalloc.3.html) for details.

**Comment by felixendres** [comment]
Sorry, but I don't get how to use that. I checked out the example for mallctl in the man page and tried to do a simple query for stats.active like this


```
#include <jemalloc/jemalloc.h>
#include <iostream>

int main()
{
  size_t s = 8;
  size_t u = 0;
  int retval = mallctl("arenas.page", &u, &s, 0, 0);
  std::cout << "retval: " << retval << "\noldp: " << u << "\noldlenp: " << s << "\n";
  for(int i = 0; i < 10; ++i)
  {
    size_t size = 50000000;
    int* dummy = static_cast<int*>(malloc(size*sizeof(int)));
    double* dummy2 = new double[size]();
    for(int j = 0; j < size; ++j){
      dummy[j] = 1;
      dummy2[j] = 1.0;
    }
    retval = mallctl("stats.active", &u, &s, 0, 0);
    std::cout << i << "\n";
    std::cout << "\tretval: " << retval << "\n\tstats.active value: " << u << "\n\toldlenp: " << s << "\n";
    retval = mallctl("stats.allocated", &u, &s, 0, 0);
    std::cout << "\tretval: " << retval << "\n\tstats.allocated value: " << u << "\n\toldlenp: " << s << "\n";
  }
}
```

Output

> retval: 0
> oldp: 4096
> oldlenp: 8
> 0
>         retval: 0
>         stats.active value: 0
>         oldlenp: 8
>         retval: 0
>         stats.allocated value: 0
>         oldlenp: 8
> ...

Through alot of trial and error I think I have found the correct usage of the parameters oldp and oldplen. Now the page size value (4096) makes sense, but the stats.active and stats.allocated values are both zero, which I don't understand. Could you please elaborate on how to use this, or what to expect? The man page is not very clear (at least to me).

**Comment by davidtgoldblatt** [comment]
You have to do an "epoch" mallctl to refresh statistics if you want them to be up-to-date. See e.g. the example [here](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Introspection-Via-mallctl%2A%28%29), which is a program similar to the one you posted.

**Comment by felixendres** [comment]
Thanks for your help. I got querying and purging (arena.<narenas>.purge) working. The example helped a lot.

The stats.active value is the currently active memory, right? Is there something like a maximum-ever-used or even better maximum-since-last-purge?

**Comment by davidtgoldblatt** [comment]
There's nothing like that (note that, because the stats are collected across arenas and aggregated only periodically, multithreaded environments mean that this sort of question need not even have a consistent answer). One thing you could do is periodically update max counters from a background thread (or just periodically in some other thread).

**Comment by interwq** [comment]
Closing for now. Feel free to let us know if any questions.
