### ISSUE TITLE
-fsanitize=undefined errors

### ISSUE THREAD

**Issue by marxin** [jemalloc/jemalloc#1019]
Hello. I've just run test-suite on x86_64-linux-gnu with -fsanitize=undefined and there are various errors:

[jemalloc.report.txt](https://github.com/jemalloc/jemalloc/files/1295668/jemalloc.report.txt)

**Comment by marxin** [comment]
Adding -Wextra -Wno-unused-arguments shows:

      3 : missing initializer for field ‘l2_cache’ of ‘rtree_ctx_t {aka struct rtree_ctx_s}’ [-Wmissing-field-initializers]
      3 : ‘static’ is not at beginning of declaration [-Wold-style-declaration]
     84 : this statement may fall through [-Wimplicit-fallthrough=]
    156 : left shift of negative value [-Wshift-negative-value]
[jemalloc.report.warnings.txt](https://github.com/jemalloc/jemalloc/files/1295690/jemalloc.report.warnings.txt)

**Comment by davidtgoldblatt** [comment]
Looks like most of these boil down to two missing casts to unsigned (defining delta_inverse_mask and in the mallocx flags arena computation). All in all, I'm surprised at how clean we end up, tbh.

Thanks for checking on this, our lack of sanitization-testing has been making me nervous for a while.

**Comment by marxin** [comment]
Thanks for taking a look, I was just curious whether these cannot lead to a real issue.

**Comment by interwq** [comment]
Thanks for reporting these @marxin! I'll fix these up soon.

**Comment by interwq** [comment]
The warnings reported should be fixed in dev. We may want to add the flags later. Closing.
