### ISSUE TITLE
Please version jemalloc API

### ISSUE THREAD

**Issue by marxin** [jemalloc/jemalloc#1021]
I would consider it a useful thing to do as similar libraries do the same:

```
readelf -sW /usr/lib64/libjpeg.so
...
   140: 00000000000157e0   560 FUNC    GLOBAL DEFAULT   13 jinit_downsampler@@LIBJPEG_6.2
   141: 0000000000014ba0   633 FUNC    GLOBAL DEFAULT   13 jinit_c_prep_controller@@LIBJPEG_6.2
   142: 0000000000021790   134 FUNC    GLOBAL DEFAULT   13 jpeg_new_colormap@@LIBJPEG_6.2
...
```

I guess a small change in extended API is possible for jemalloc library. Am I right?

**Comment by davidtgoldblatt** [comment]
It's not totally clear to me what we'd get? The core APIs never lose compatibility across versions, and the mallctl ones give even finer-grained flexibility (i.e. you can detect incompatibility at runtime instead of relying on linker/loader versioning). Is there an end-goal this blocks?

**Comment by marxin** [comment]
My motivation for versioning is that I'm afraid in ABI non-compatibility across versions that will be released in longer time frame. If you're not planning ABI incompatibility then please close this issue.

**Comment by davidtgoldblatt** [comment]
I think we're comfortable with mallctls as the official versioning mechanism going forward, and comitting to indefinite compatibility guarantees for the remaining APIs.

**Comment by marxin** [comment]
Works for me, thanks.
