### ISSUE TITLE
Unable to download jemalloc from canonware.com

### ISSUE THREAD

**Issue by nellshamrell** [jemalloc/jemalloc#1026]
Canonware.com appears to be down at the moment.

**Comment by davidtgoldblatt** [comment]
The releases page is where this lives now: https://github.com/jemalloc/jemalloc/releases/latest .

**Comment by interwq** [comment]
Also see Jason's comment on gitter regarding this:https://gitter.im/jemalloc/jemalloc?at=59b07988bc46472974040c91
