### ISSUE TITLE
Modify configure to determine if strerror_r returns char*

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#1028]
In addition to glibc, bionic also has a strerror_r that returns char* if gnu source is defined. Since this is different on different systems, modify configure to determine this dynamically.

I've included a patch that implements this which can be applied using git apply strerror_r.txt.

[strerror_r.txt](https://github.com/jemalloc/jemalloc/files/1325609/strerror_r.txt)

I don't have the ability to upload directly, since I don't have rights in this repo.

**Comment by davidtgoldblatt** [comment]
Thanks for the patch, I'll try it out in a day or two.

BTW, if relevant in the future, a github Pull Request is an easier way to submit a change -- it eases doing back and forth on changes. (Not a big deal for something this straightforward, but on something bigger it's nice).
