### ISSUE TITLE
malloc_stats_print function can not statistics memory 

### ISSUE THREAD

**Issue by XMAN-WOMBAT** [jemalloc/jemalloc#1036]
Hi:
        I have used jemalloc in my C++  project. I have linked jemalloc.a library and contained jemalloc/jemalloc.h. now , in my project i have used std::shared_ptr<int>  t_sptr = std::make_shared<int>(5555)  apply for memory.after that,i use malloc_stats_print function to check the number of requests.

`malloc_stats_print(nullptr,nullptr,nullptr) ;

    for(int i = 0 ; i < 1000; i ++)
    {
            std::shared_ptr<int> t_sptr = std::make_shared<int>(5555);
            //malloc(i * 100);
    }

    malloc_stats_print(nullptr,nullptr,nullptr) ;`

![image](https://user-images.githubusercontent.com/20120146/31041678-f924f51e-a5cb-11e7-9e98-8fead6e634d4.png)

**Comment by davidtgoldblatt** [comment]
Probably you need an "epoch" mallctl -- see the example at https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Introspection-Via-mallctl%2A%28%29 .
