### ISSUE TITLE
How to build on qnx6.6

### ISSUE THREAD

**Issue by YanShenChun** [jemalloc/jemalloc#1037]
Hi, jemalloc experts

As the subject said, I have tried below approaches but no work

1.  Use autogen
export CC=/opt/qnx660/host/linux/x86/usr/bin/qcc
export CFLAGS="-V4.7.3,gcc_ntoarmv7le -lang-c -Wl,--no-keep-memory -Wl,--no-undefined"
export LDFLAGS="-V4.7.3,gcc_ntoarmv7le -Wl,--no-keep-memory -Wl,--no-undefined"
./autogen.sh --host=ntoarmv7
Error says:
_checking host system type... Invalid configuration `ntoarmv7': machine `ntoarmv7' not recognizd_

2. Do it manually.
`cmake_minimum_required(VERSION 2.8)
project(jemalloc)
if (${OS} STREQUAL "qnx")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -V4.7.3,gcc_ntoarmv7le -lang-c++ -Wl,--no-keep-memory -Wl,--no-undefined")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -V4.7.3,gcc_ntoarmv7le -lang-c -Wl,--no-keep-memory -Wl,--no-undefined")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -V4.7.3,gcc_ntoarmv7le -Wl,--no-keep-memory -Wl,--no-undefined")
endif()
include_directories(${PROJECT_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/include)
set(jemalloc_src
    src/arena.c
    src/background_thread.c
    src/base.c
    src/bitmap.c
    src/ckh.c
    src/ctl.c
    src/extent.c
    src/extent_dss.c
    src/extent_mmap.c
    src/hash.c
    src/hooks.c
    src/jemalloc.c
    src/large.c
    src/log.c
    src/malloc_io.c
    src/mutex.c
    src/mutex_pool.c
    src/nstime.c
    src/pages.c
    src/prng.c
    src/prof.c
    src/rtree.c
    src/stats.c
    src/sz.c
    src/tcache.c
    src/ticker.c
    src/tsd.c
    src/witness.c
    src/zone.c)
add_library(jemalloc ${jemalloc_src})

`
run the cmake and I got 'include/jemalloc/internal/XX.h not found" error.
I just tried to use the original 'include/jemalloc/internal/XX.h.in' file but a bunch of errors popped out.

So I just want to know if the jemalloc works on QNX 6.6 platform?

Any help is highly appreciated.

**Comment by davidtgoldblatt** [comment]
We definitely don't build or test on QNX (or even have the ability to). We'd look at pull requests fixing build errors, but can't promise to do much more than that (and, we can't promise not to break the build in the future).

The cmake approach you tried in approach 2 definitely won't work -- we generate several internal headers in our configure script (which itself autodetects aspects of the host platform; another impediment to implementing this).

I think that the level of work involved here is such that it's probably not worth the payoff for you. Closing for now, but feel free to reopen if this is something you'd still like to pursue.
