### ISSUE TITLE
How Jemalloc interacts with the kernel?

### ISSUE THREAD

**Issue by suruonuo** [jemalloc/jemalloc#1051]
I hope the system which using the jemalloc in single-threaded and multi-threaded have same performance，In single-threaded，I refer the jemalloc lib and call the malloc() function , but the performance disappoints me（cpu intensive, not io intensive）。

**Comment by davidtgoldblatt** [comment]
We get our memory from the underlying OS allocation mechanism (mmap, sbrk, or VirtualAlloc, depending on platform and configuration).

Could you clarify a little what you're seeing that's different from what you expect?

**Comment by davidtgoldblatt** [comment]
Closing for now, feel free to reopen if you have further questions.
