### ISSUE TITLE
Checks fails with LLVM/clang-5.0.x 

### ISSUE THREAD

**Issue by tpgxyz** [jemalloc/jemalloc#1057]
Hi,

i'm trying to build jemalloc-5.0.1 and i got this error on make check stage:
more logs here
http://file-store.openmandriva.org/api/v1/file_stores/3cdce13ca7d46990d377d9acc3e895482fcc3eec.log?show=true
```
/usr/bin/clang -o test/unit/rtree test/unit/rtree.o src/jemalloc.jet.o src/arena.jet.o src/background_thread.jet.o src/base.jet.o src/bitmap.jet.o src/ckh.jet.o src/ctl.jet.o src/extent.jet.o src/extent_dss.jet.o src/extent_mmap.jet.o src/hash.jet.o src/hooks.jet.o src/large.jet.o src/malloc_io.jet.o src/mutex.jet.o src/mutex_pool.jet.o src/nstime.jet.o src/pages.jet.o src/prng.jet.o src/prof.jet.o src/rtree.jet.o src/stats.jet.o src/spin.jet.o src/sz.jet.o src/tcache.jet.o src/ticker.jet.o src/tsd.jet.o src/witness.jet.o test/src/btalloc.unit.o test/src/btalloc_0.unit.o test/src/btalloc_1.unit.o test/src/math.unit.o test/src/mtx.unit.o test/src/mq.unit.o test/src/SFMT.unit.o test/src/test.unit.o test/src/thd.unit.o test/src/timer.unit.o -Wl,-rpath,lib -Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -flto -Wl,-O2  -Wl,--no-undefined -flto  -lstdc++ -lpthread -ldl -lm 
'allocsize' number of elements argument is out of bounds
  %12 = tail call fastcc noalias i8* @jet_calloc(i64 %2) #17, !dbg !7869
LLVM ERROR: Broken function found, compilation aborted!
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:393: test/unit/rtree] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.86064 (%check)

```

**Comment by davidtgoldblatt** [comment]
How did some of these options get selected? I would not be surprised if we do things that are inconsistent with e.g. gcc stack protection.

**Comment by tpgxyz** [comment]
@davidtgoldblatt Which options ? Can you be more specific.

**Comment by davidtgoldblatt** [comment]
`-fstack-protector` and `-D_FORTIFY_SOURCE` were the ones I was thinking of. The "number of elements argument is out of bounds" thing feels screwy to me; do you have some way of figuring out what calloc call in particular it's unhappy about?

**Comment by tpgxyz** [comment]
@davidtgoldblatt  Well that's strange because build on aarch64 went fine, with same optflags
https://abf.openmandriva.org/build_lists/128990

Anyway building without any optflags on x86_64

**Comment by tpgxyz** [comment]
@davidtgoldblatt  Looks like issue here was -flto. Without LTO enabled jemalloc builds fine.

**Comment by davidtgoldblatt** [comment]
Huh, is the environment you were building with easy to reproduce? I'd still like to be able to dig into this at least some.

**Comment by tpgxyz** [comment]
@davidtgoldblatt You may take a look on completed build here https://abf.openmandriva.org/build_lists/129772
