### ISSUE TITLE
What is the excess size of `rallocx` 

### ISSUE THREAD

**Issue by gnzlbg** [jemalloc/jemalloc#1059]
The docs of `rallocx` say:

> The rallocx() function resizes the allocation at ptr to be at least size bytes, 

How can I know if it has resized the allocation to more than `size` bytes ?

The `nallocx` function does this for `mallocx`:

> The nallocx() function allocates no memory, but it performs the same size computation as the mallocx() function

but I cannot find an API to do that for `rallocx`.

**Comment by gnzlbg** [comment]
Should I just call `sallocx` on the pointer returned by `rallocx` ? 

> The sallocx() function returns the real size of the allocation at ptr.

What is the cost of that compared to `nallocx` ?

**Comment by gnzlbg** [comment]
Or `xallocx`?

> The xallocx() function returns the real size of the resulting resized allocation pointed to by ptr, which is a value less than size if the allocation could not be adequately grown in place.

**Comment by interwq** [comment]
nallocx works for rallocx as well. It finds the next large enough size class for the specified the size which would be the real size after the reallocation.

**Comment by gnzlbg** [comment]
Don't you think that this should be... documented ? For which other functions does `nallocx` work?

**Comment by davidtgoldblatt** [comment]
`nallocx` works for all the allocation functions (we should probably clarify the documentation). `sallocx` is used when you have a pointer to heap memory, but don't know what size it was allocated with.

**Comment by gnzlbg** [comment]
So i've implemented these optimizations in Rust `Alloc`ator to return the exact size of the allocations:

- in [`alloc_excess`](https://github.com/rust-lang/rust/pull/45514) which uses `mallocx`
  -  [perf using `nallocx`](http://perf.rust-lang.org/compare.html?start=2f5ae25a34077aad82a5dc41c2684cd21279df58&end=d413b1cd8acbab43114c512ea0fa9b3d495560d2&stat=instructions%3Au)
- [in `realloc_excess`](https://github.com/rust-lang/rust/pull/45514) which uses `rallocx`:
  - [perf using `sallocx`](http://perf.rust-lang.org/compare.html?start=f764eaf453162cd19ef484ece07cc21e14dfb2c1&end=4b59c8253d8080e5dbf71807b4d8fb6625760910&stat=instructions%3Au)
  - [perf using `nallocx`](http://perf.rust-lang.org/compare.html?start=56dc171a2f2dc2373b1930f71140a354fa84b982&end=9b02a2d18a4c02a7781ac9ad4e76c6c16cf5961b&stat=instructions%3Au)

Against my intuition in both cases I observe:

- a higher memory usage
- a lower cpu-clock type / executed cycles
- similar wall time

Also, against my intuition, using `sallocx` instead of `nallocx` to obtain the real allocation size of `rallocx`, produces a:

- a lower memory usage
- a lower cpu-clock type / executed cycles
- similar wall time

[Our microbenchmarks](https://github.com/rust-lang/rust/pull/45514#issuecomment-339397082) show, however, that `nallocx` is faster than `sallocx`, and if IIUC both should return the same results.

Any idea of what is going on, or some recommendation about what we should do?

**Comment by davidtgoldblatt** [comment]
Neither sallocx nor nallocx affect allocator state; perhaps you're passing different alignment flags or similar?

It looked like the numbers in your benchmarks are in the tenths-of-a-percent range; perhaps you're just seeing noise?

BTW, in general, if you're mallocx-ing with a flags argument that's statically 0, it's probably better to just malloc instead (we can shave off a few branches and whatnot down those pathways). Not sure if this matters outside the benchmarks.

**Comment by gnzlbg** [comment]
> Neither sallocx nor nallocx affect allocator state; perhaps you're passing different alignment flags or similar?

Same alignment flags, the result of these functions are used, for example, by Rust collections like `Vec`. So my hypothesis is that, for example, on the first allocation, now these collections get a larger capacity, but in these "benchmark applications", this capacity isn't enough, so when the vectors grow size, they end up consuming larger memory. At the same time, they need to grow up size less often, which explains the reduced CPU time.

The difference between `sallocx` and `nallocx` can be similarly explained. The cost of a `nallocx` call is 15ns (~45 cycles), and the cost of a `sallocx` call is of 19ns (~60 cycles). If for some reason `sallocx` is more accurate than `nallocx` and returns a larger size, that would maybe explain the results. That is, a `sallocx` call would return a larger size, resulting in less allocations necessary by these collections, and if that means in these benchmark applications less vector growth that would explain the reduced memory size and increased performance.

> , if you're mallocx-ing with a flags argument that's statically 0

We are always `mallocx`-ing with the required alignment. For Rust the smallest-possible alignment requirement is `1`.

**Comment by davidtgoldblatt** [comment]
> At the same time, they need to grow up size less often, which explains the reduced CPU time.

This shouldn't cause a difference between the two, though. Having re-read the nallocx vs sallocx pathways again, I'm pretty sure this boils down to measurement error or noise somehow. (Except for CPU where, as you note, nallocx should be faster).

> We are always mallocx-ing with the required alignment. For Rust the smallest-possible alignment requirement is 1.

I would not recommend this usage pattern; the alignment API is really best used for over-aligning. Allocating an int as `mallocx(sizeof(int), MALLOCX_LG_ALIGN(lg_alignof_int))` will be rather wasteful of cycles. Is this something rust always does, or do you just mean the benchmarks in question?

**Comment by gnzlbg** [comment]
@davidtgoldblatt

It seems that you are correct and we are dealing with measuring noise. Only for realizing this it was worth it, we'll have to improve this. 

I've distilled the infallible (as in, if it fails, produces an irrecoverable error) `alloc` operation for you: 

```rust
// on x86
const MIN_ALIGN: usize = 16;

fn mallocx_align(a: usize) -> c_int {
        a.trailing_zeros() as c_int
}

fn align_to_flags(align: usize) -> c_int {
    if align <= MIN_ALIGN {
        0
    } else {
        mallocx_align(align)
    }
}

pub unsafe extern fn _alloc(size: usize,
                                     align: usize,
                                     err: *mut u8) -> *mut u8 {
        let flags = align_to_flags(align);
        let ptr = mallocx(size as size_t, flags) as *mut u8;
        // .. error handling
}

// this is then called like:
__alloc(std::mem::size_of::<T>(), std::mem::align_of::<T>, err)
```

So as you see we obtain the required alignment of a type using `mem::align_of::<T>` (like C++ `alignof`), then if that is smaller than 16, we use `0`, otherwise, we compute the alignment flag. But in both cases we call `mallocx` with either 0 or the alignment flag.

I could change that to:

```rust
let ptr = if flags == 0 { malloc(...) } else { mallocx(..., flags) }
```

**Comment by davidtgoldblatt** [comment]
Yeah, I think that makes sense, especially if that logic can get inlined so that it turns into a plain malloc call.

**Comment by davidtgoldblatt** [comment]
Also, those numbers you're seeing for the cost of nallocx are way too high; it's something like 4-7ns on my machine.

**Comment by gnzlbg** [comment]
I am closing this as I think it has been properly answered. Thanks :)
