### ISSUE TITLE
Properly handle mutex stats output

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1063]
For convenience in the stats outputting code, we treat all mutex profiling statistics as 64-bit, which is not actually the case. This can cause uninitialized data to be output, since the ctls the stats boil down to will only write 4 bytes out for 4-byte fields. For the stuff I'm doing in #1058 I can get away with memsetting to 0, but this only happens to work because I'm on a little-endian machine. We should do it the "right" way, and properly size the fields.

**Comment by interwq** [comment]
We observed this in production: max_n_thds is reported 140243567116289 (0x7F8D00000001), so this is definitely worth fixing.
