### ISSUE TITLE
Size class 2 is incorrect?

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1073]
In the default configuration, we'll have size class two (i.e. the third size class) be three times the size of a word, even when alignof(max_align_t) is 2 words. The line of reasoning is, "the size of an object is a multiple of its alignment in the implementations we support. Since the allocation size is not a multiple of two words, we must need only word-alignment". This isn't correct in the presence of flexible array members though (assume 64-bit here):
```
struct S {
  int _Alignas(16) data;
  char flexible_str[0];
};

S *get_s(const char *str) {
  return malloc(sizeof(struct S) + strlen(str));
}

void foo() {
  /* Results in a malloc call of size 20; the returned pointer might only be 8-byte aligned. */
  S *my_s = get_s("dtg");
}
```

I don't have a great answer for what to do here; the 24-byte size class is very highly used, and bumping those allocations up to 32 bytes would be painful. This pattern isn't allowed in C++ I believe, so that we'd be penalizing C++ users for no benefit to them.

Possible strategies:
1. Do nothing; this is an edge case that AFAIK no one has hit.
2. Make this behavior opt-in instead of opt-out at compile-time.
3. Make this behavior opt-in instead of opt-out at runtime (the relevant sizes are always in the lookup table).
4. Always provide 4 word allocations for any size between 2 and 4 words.

I'm inclined towards option 3. This would have the potential to cause sudden unexpected regressions to users who (quite reasonably) aren't paying close attention to jemalloc releases though.

**Comment by djwatson** [comment]
I vote for 1.  This seems specialized enough that users can use one of the aligned allocation calls?

**Comment by djwatson** [comment]
Unless someone is complaining that their code is broken, then 3 :)

**Comment by davidtgoldblatt** [comment]
We could make it a mallctl option, but leave the default to allowing the 24-byte size class too.

**Comment by jasone** [comment]
Do we actually have a 24-byte size class on systems with 16-byte quantum?  That is not the intent.  See the [size class table](http://jemalloc.net/jemalloc.3.html#size_classes) in the manual.  Last I checked this table reflected reality.

**Comment by davidtgoldblatt** [comment]
Oh woops, I'm dumb. I must have configured with a manual --with-lg-quantum for #1072 and forgot about it when looking at size classes.
