### ISSUE TITLE
jemalloc-5.0.1 test/unit/SFMT failing on ppc64le

### ISSUE THREAD

**Issue by ingvarha** [jemalloc/jemalloc#1087]
On the fedora builders, jemalloc-5.0.1 test/unit/SFMT fails all tests on ppc64le

Example build log: https://kojipkgs.fedoraproject.org//work/tasks/7909/23677909/build.log

Ingvar

**Comment by ingvarha** [comment]
Building without altivec support hides this error. See issue #1088

**Comment by sharkcz** [comment]
It looks as a duplicate of issue #761

**Comment by davidtgoldblatt** [comment]
Yep, dupe of #761, fixed in #1043.

**Comment by davidtgoldblatt** [comment]
(The fix will be included in 5.1).
