### ISSUE TITLE
Allocating memory in a signal handler

### ISSUE THREAD

**Issue by madscientist** [jemalloc/jemalloc#1090]
I'm using the Google coredumper library to perform coredumping on my own terms.  What I'd like to be able to do is invoke some of my code that does specific things during the coredump.  If the coredump is invoked through an assert() or abort() call that's fine, but if the coredump is invoked from a signal handler (via SIGABRT or whatever) then obviously I can't do anything that allocates memory, and sometimes I want to do things that allocate memory (generate strings to write(2) for example).
I was wondering if there was some way to set the jemalloc configuration in my signal handler so that it used a completely different heap than the "normal" one; that heap would only be used during signal handling and so it should be OK to use.  Are arenas something that would be appropriate here (today I don't use any special jemalloc macros to select arenas)?  Something like, when my program starts I'd initialize a special arena for signal handler heap but not use it, then in a signal handler I'd use that arena only.
If such a thing is feasible, is it possible to change the default arena so that normal malloc() etc. calls use it (so that I can call my normal code, that just runs malloc(), from a signal handler, rather than having to write special malloc calls for anything that might be invoked from a signal handler)?

**Comment by davidtgoldblatt** [comment]
It's something we've talked about a couple of times. It might be possible in the distant future, but not for a while. Even if all the user code uses a custom signal-only arena, we still sometimes want to acquire internal mutexes for things like metadata allocations, profiling, etc.

You might be able to adapt https://github.com/abseil/abseil-cpp/blob/720c017e30339fd1786ce4aac68bc8559736e53f/absl/base/internal/low_level_alloc.h to accomplish some of what you want.

**Comment by madscientist** [comment]
Thanks @davidtgoldblatt that's good to know.  Unfortunately using a separate allocator is painful for me since it means I need to write my code specially to allow it to be used both inside and outside of the handler.  Maybe for now I'll just not bother to generate the difficult content if I'm dumping due to a signal.  Most of my coredumps come from asserts/abort calls; I don't see SEGV etc. very often in my code anyway.
I'll be interested to see whether this (admittedly very limited) use case gains any traction.
Cheers!
