### ISSUE TITLE
msvc project configuration defines JEMALLOC_NO_PRIVATE_NAMESPACE for x64 build only

### ISSUE THREAD

**Issue by Cytoo** [jemalloc/jemalloc#1099]
When building jemalloc for all windows targets using msvc I noticed that all x64 targets defined JEMALLOC_NO_PRIVATE_NAMESPACE but not x86 targets. 

This changed was added by commit ba29113e5a58caeb6b4a65b1db6d8efae79cae45

Why does x86 and x64 builds behave differently ?

**Comment by CyberTech** [comment]
This bit me as well; as the windows x86 build failed using --without-export and --with-jemalloc-prefix, since the private namespace headers aren't generated.

**Comment by davidtgoldblatt** [comment]
I'm sort of coming around to think that we should kill the windows workspace files, and only support building using the commandline tooling (as CI does, say). I don't think any of the core team really understands the toolchain there well enough to keep something in that we don't test -- this is something like the third time that they've broken that I don't really know what to do about.

@interwq, any thoughts?

**Comment by CyberTech** [comment]
My first thought is that lack of an MSVC build would pretty seriously dissuade a lot of folks from trying this.  Requiring cygwin/autoconf/autogen is only a minor annoyance, as it can be done once then committed, but if there were no core MSVC project file, then we'd need to compare makefiles between releases and copy those changes to our project files. At least right now we have a base project to compare.

I fixed the current problem by simply defining NO_PRIVATE_NAMESPACE for x86 as well, but i think the core problem here was the change to generating the custom headers wasn't propagated to the windows build for the 5.0 release.

**Comment by Cytoo** [comment]
We also updated the x86 solution as well, Then tried to compile the test suite which also did not compile without modifications. 

We had noticed a bug when using our own product with jemalloc 5 (Allocating ~32GB instead of 100MB, approx) so we wanted to see if it happened really in jemalloc, thats why we ran the tests and the behaviour also occured (allocating way too much memory). 

We tested this on a 64 bits Windows 10.

We jumped to the conclusion that jemalloc 5 doesn't fully support windows yet and we rolledback to version 4.3 of jemalloc that is currently used in our project. Unfortunately we did not investigate this bug further so there is not enough material to properly open a ticket, but I thought it would be worth to mention still @davidtgoldblatt

**Comment by davidtgoldblatt** [comment]
@CyberTech, would transitioning to CMake ease things for you? I know MSVC has some support there, but I'm not sure how much. It's something we've wanted to do for a while now; a "real" cross-platform build system would greatly simplify things on our end as well.

@Cytoo, it may be worth trying a more recent dev build (or 5.1, which we hope to release before long). 5.0 had some address space explosion issues (which shouldn't affect "true" resident memory in most cases) that are fixed in dev.

**Comment by rustyx** [comment]
The master branch is compiling fine for me in VS2015, in 64-bit as well as 32-bit mode. Adding JEMALLOC_NO_PRIVATE_NAMESPACE doesn't seem to make any difference for compilation.
Did you run autogen.sh from the VS2015 **x64 Native** command prompt?

I must add though that the 32-bit 5.0.1 build currently compiles but doesn't actually [work](https://github.com/jemalloc/jemalloc/issues/1116). Doesn't seem related to JEMALLOC_NO_PRIVATE_NAMESPACE though.
