### ISSUE TITLE
Need help, can you help me on this output of jeprof?

### ISSUE THREAD

**Issue by mahaoboy** [jemalloc/jemalloc#1113]
Hi Team,
I used the jemalloc to analyze memory leak.
But I can see the result is confusing:
_Welcome to jeprof!  For help, type 'help'.
(jeprof) top
Total: 76401659763 B
37610323968  49.2%  49.2% 37610323968  49.2% 0x00007fb2b7044f3e
29910630400  39.1%  88.4% 29910630400  39.1% 0x00007fb2b704056e
6627381529   8.7%  97.1% 6627381529   8.7% os::malloc@9138c0
976522636   1.3%  98.3% 976522636   1.3% void* newImpl
382619666   0.5%  98.8% 382619666   0.5% 0x00007fb2b708e7bc
346110342   0.5%  99.3% 346110342   0.5% 0x00007fb2b6fe1a20
167772160   0.2%  99.5% 167772160   0.2% init
142038471   0.2%  99.7% 142038471   0.2% readCEN
89327187   0.1%  99.8% 89327187   0.1% updatewindow
62968641   0.1%  99.9% 62968641   0.1% deflateInit2_

Could you please tell me how to identify the hex number "0x00007fb2b7044f3e"?
Is it a native lib? third native lib?

**Comment by interwq** [comment]
This means jeprof wasn't able to find the symbol, e.g. the library information is missing, or if it's JIT-generated code. You may want to search for information like "pprof no function name" (jeprof is based on pprof).

**Comment by mahaoboy** [comment]
Thanks. I will try it.

**Comment by interwq** [comment]
Closing assume resolved. Please reopen if otherwise.

**Comment by meiry** [comment]
Any news on this ? i also facing Hex function  when running jemalloc
