### ISSUE TITLE
Feature request : To be able to reset the value of "lg_prof_interval"

### ISSUE THREAD

**Issue by hbellam24** [jemalloc/jemalloc#1114]
I would like enable and disable heap profiling
dynamically. When I enabled profiling               
I would like to have multiple dumps based on the allocation activity.
So I am setting the value of "lg_prof_interval" in configuration.
Example: "prof:true,prof_active:false,prof_prefix:jeprof.out, lg_prof_interval:10"

The blocker I am having is once I enabled profiling
(Example: mallctl("prof.active", nullptr, nullptr, &enable_profiling, val_sz))
,with the above configuration, I am not able to disable profiling.

When my configuration doesn't contain "lg_prof_interval", I am able to enable
and disable profiling using mallctl. 
 
Currently Jemalloc can reset the value of
"lg_prof_sample" using "prof.reset" but not "lg_prof_interval".

My request is to be able to set the value of "lg_prof_interval" dynamically.
 
Thanks, 
haritha

**Comment by hbellam24** [comment]
Thanks for the reply @interwq. I am not interested in changing the value of prof_interval dynamically but I would like to  have an option to disable jemalloc when prof_interval has some value. 
As a user I expect prof_active to take precedence over prof_interval. When I set prof_active as "false" it should stop dumping irrespective of value at prof_interval.

**Comment by interwq** [comment]
Sounds reasonable. I'll guard idump and gdump under prof_active, unless there's objection from @davidtgoldblatt.

**Comment by davidtgoldblatt** [comment]
Seems reasonable to me.

**Comment by interwq** [comment]
Okay I'll add the guards for gdump and idump then.
