### ISSUE TITLE
distinguish memory leak type

### ISSUE THREAD

**Issue by fungo** [jemalloc/jemalloc#1120]
Sometimes we alloc some size of memory,  use it through the whole life of process, but don't free it explicitly, cause the OS will reclaim the memory automatically at program exit.

May be sometimes it is fine and desirable , and should not be treated as memory leak, as long as we have a point reference to the memory. i.e. the memory is still reachable by us, it's is not lost.

Valgrind's memcheck can give us "definitely lost" or "still reachable" tips in the output, it is very clear and useful, we can just ignore those **still reachable leak**.

Is it possible for jemalloc to distinguish still reachable memory and totally lost memory at exit?

**Comment by davidtgoldblatt** [comment]
I don't think this should live in jemalloc; I think we'd be better off providing an introspection API alone. Doing things like pausing all threads, walking stacks, finding global and thread-local data, and doing the traversal, all seem like they fall outside of core allocator responsibility.
