### ISSUE TITLE
Windows: unresolved external symbol bin_infos

### ISSUE THREAD

**Issue by hatvik** [jemalloc/jemalloc#1125]
Starting with commit 4bf4a1c4ea418ba490d35d23aee0f535e96ddd23

sh -c "CC=cl ./autogen.sh" 
11:50:19  autoconf
11:50:23  ./configure --enable-autogen 
11:50:31  checking for xsltproc... false
11:50:31  checking for gcc... cl
11:50:34  checking whether the C compiler works... yes
11:50:34  checking for C compiler default output file name... conftest.exe
11:50:34  checking for suffix of executables... .exe
11:50:35  checking whether we are cross compiling... no
11:50:36  checking for suffix of object files... obj
11:50:37  checking whether we are using the GNU C compiler... no
11:50:40  checking whether cl accepts -g... yes
11:50:41  checking for cl option to accept ISO C89... none needed
11:50:42  checking whether compiler is MSVC... yes
11:50:43  checking whether compiler is cray... no
11:50:43  checking whether compiler supports -Zi... yes
11:50:44  checking whether compiler supports -MT... yes
11:50:44  checking whether compiler supports -W3... yes
11:50:45  checking whether compiler supports -FS... yes
11:50:47  checking how to run the C preprocessor... cl -nologo -E
11:50:48  checking for g++... g++
11:50:52  checking whether we are using the GNU C++ compiler... no
11:50:57  checking whether g++ accepts -g... no
11:50:59  checking whether g++ supports C++14 features by default... no
11:51:00  checking whether g++ supports C++14 features with -std=c++14... no
11:51:02  checking whether g++ supports C++14 features with -std=c++0x... no
11:51:03  checking whether g++ supports C++14 features with +std=c++14... no
11:51:05  checking whether g++ supports C++14 features with -h std=c++14... no
11:51:05  configure: No compiler with C++14 support was found
11:51:05  checking for grep that handles long lines and -e... /usr/bin/grep
11:51:05  checking for egrep... /usr/bin/grep -E
11:51:08  checking for ANSI C header files... yes
11:51:08  checking for sys/types.h... yes
11:51:10  checking for sys/stat.h... yes
11:51:11  checking for stdlib.h... yes
11:51:12  checking for string.h... yes
11:51:13  checking for memory.h... yes
11:51:14  checking for strings.h... yes
11:51:15  checking for inttypes.h... yes
11:51:17  checking for stdint.h... yes
11:51:18  checking for unistd.h... no
11:51:21  checking whether byte ordering is bigendian... no
11:51:21  Using a predefined value for sizeof(void *): 4 for 32-bit, 8 for 64-bit
11:51:22  checking size of int... 4
11:51:24  checking size of long... 4
11:51:26  checking size of long long... 8
11:51:27  checking size of intmax_t... 8
11:51:30  checking build system type... i686-pc-mingw32
11:51:30  checking host system type... i686-pc-mingw32
11:51:31  checking whether pause instruction MSVC is compilable... yes
11:51:32  checking number of significant virtual address bits... (1U << (LG_SIZEOF_PTR_WIN+3))
11:51:32  checking for ar... ar
11:51:32  checking for nm... nm
11:51:32  checking for gawk... gawk
11:51:32  checking malloc.h usability... yes
11:51:33  checking malloc.h presence... yes
11:51:33  checking for malloc.h... yes
11:51:34  checking whether malloc_usable_size definition can use const argument... yes
11:51:35  checking for library containing log... none required
11:51:36  checking whether __attribute__ syntax is compilable... no
11:51:37  checking whether compiler supports -Werror... no
11:51:38  checking whether compiler supports -herror_on_warning... yes
11:51:39  checking whether tls_model attribute is compilable... no
11:51:40  checking whether compiler supports -Werror... no
11:51:42  checking whether compiler supports -herror_on_warning... yes
11:51:43  checking whether alloc_size attribute is compilable... no
11:51:44  checking whether compiler supports -Werror... no
11:51:45  checking whether compiler supports -herror_on_warning... yes
11:51:46  checking whether format(gnu_printf, ...) attribute is compilable... no
11:51:47  checking whether compiler supports -Werror... no
11:51:48  checking whether compiler supports -herror_on_warning... yes
11:51:49  checking whether format(printf, ...) attribute is compilable... no
11:51:50  checking for a BSD-compatible install... /usr/bin/install -c
11:51:50  checking for ranlib... ranlib
11:51:50  checking for ld... /mingw/bin/ld
11:51:50  checking for autoconf... /mingw/bin/autoconf
11:51:51  checking for memalign... no
11:51:53  checking for valloc... no
11:51:53  checking whether compiler supports -O2... yes
11:51:54  checking whether compiler supports -O2... yes
11:51:54  checking configured backtracing method... N/A
11:51:55  checking for sbrk... no
11:51:56  checking whether utrace(2) is compilable... no
11:51:58  checking whether a program using __builtin_unreachable is compilable... no
11:51:59  checking whether a program using __builtin_ffsl is compilable... no
11:52:01  checking whether a program using ffsl is compilable... yes
11:52:02  checking LG_PAGE... 12
11:52:07  checking for library containing clock_gettime... no
11:52:08  checking whether clock_gettime(CLOCK_MONOTONIC_COARSE, ...) is compilable... no
11:52:10  checking whether clock_gettime(CLOCK_MONOTONIC, ...) is compilable... no
11:52:11  checking whether mach_absolute_time() is compilable... no
11:52:11  checking whether compiler supports -Werror... no
11:52:12  checking whether syscall(2) is compilable... no
11:52:14  checking for secure_getenv... no
11:52:15  checking for sched_getcpu... no
11:52:16  checking for sched_setaffinity... no
11:52:17  checking for issetugid... no
11:52:19  checking for _malloc_thread_cleanup... no
11:52:20  checking for _pthread_mutex_init_calloc_cb... no
11:52:21  checking whether C11 atomics is compilable... no
11:52:22  checking whether GCC __atomic atomics is compilable... no
11:52:23  checking whether GCC __sync atomics is compilable... no
11:52:24  checking whether Darwin OSAtomic*() is compilable... no
11:52:25  checking whether madvise(2) is compilable... no
11:52:27  checking whether to force 32-bit __sync_{add,sub}_and_fetch()... no
11:52:28  checking whether to force 64-bit __sync_{add,sub}_and_fetch()... no
11:52:29  checking for __builtin_clz... no
11:52:30  checking whether Darwin os_unfair_lock_*() is compilable... no
11:52:31  checking whether Darwin OSSpin*() is compilable... no
11:52:33  checking whether glibc malloc hook is compilable... no
11:52:34  checking whether glibc memalign hook is compilable... no
11:52:35  checking whether pthreads adaptive mutexes is compilable... no
11:52:35  checking for stdbool.h that conforms to C99... yes
11:52:37  checking for _Bool... yes
11:52:38  configure: creating ./config.status
11:52:47  config.status: creating Makefile
11:52:48  config.status: creating jemalloc.pc
11:52:49  config.status: creating doc/html.xsl
11:52:50  config.status: creating doc/manpages.xsl
11:52:51  config.status: creating doc/jemalloc.xml
11:52:53  config.status: creating include/jemalloc/jemalloc_macros.h
11:52:54  config.status: creating include/jemalloc/jemalloc_protos.h
11:52:56  config.status: creating include/jemalloc/jemalloc_typedefs.h
11:52:57  config.status: creating include/jemalloc/internal/jemalloc_preamble.h
11:52:59  config.status: creating test/test.sh
11:53:00  config.status: creating test/include/test/jemalloc_test.h
11:53:02  config.status: creating config.stamp
11:53:03  config.status: creating bin/jemalloc-config
11:53:04  config.status: creating bin/jemalloc.sh
11:53:06  config.status: creating bin/jeprof
11:53:07  config.status: creating include/jemalloc/jemalloc_defs.h
11:53:08  config.status: creating include/jemalloc/internal/jemalloc_internal_defs.h
11:53:09  config.status: creating test/include/test/jemalloc_test_defs.h
11:53:11  config.status: executing include/jemalloc/internal/public_symbols.txt commands
11:53:12  config.status: executing include/jemalloc/internal/private_symbols.awk commands
11:53:15  config.status: executing include/jemalloc/internal/private_symbols_jet.awk commands
11:53:18  config.status: executing include/jemalloc/internal/public_namespace.h commands
11:53:24  config.status: executing include/jemalloc/internal/public_unnamespace.h commands
11:53:30  config.status: executing include/jemalloc/internal/size_classes.h commands
11:53:32  config.status: executing include/jemalloc/jemalloc_protos_jet.h commands
11:53:33  config.status: executing include/jemalloc/jemalloc_rename.h commands
11:53:46  config.status: executing include/jemalloc/jemalloc_mangle.h commands
11:53:58  config.status: executing include/jemalloc/jemalloc_mangle_jet.h commands
11:54:10  config.status: executing include/jemalloc/jemalloc.h commands
11:54:12  ===============================================================================
11:54:12  jemalloc version   : 5.0.1-80-g4bf4a1c4ea418ba490d35d23aee0f535e96ddd23
11:54:12  library revision   : 2
11:54:12  
11:54:12  CONFIG             : --enable-autogen CC=cl
11:54:12  CC                 : cl -nologo
11:54:12  CONFIGURE_CFLAGS   : -Zi -MT -W3 -FS -O2
11:54:12  SPECIFIED_CFLAGS   : 
11:54:12  EXTRA_CFLAGS       : 
11:54:12  CPPFLAGS           : -I./include/msvc_compat -D_REENTRANT
11:54:12  CXX                : g++
11:54:12  CONFIGURE_CXXFLAGS : -O2
11:54:12  SPECIFIED_CXXFLAGS : 
11:54:12  EXTRA_CXXFLAGS     : 
11:54:12  LDFLAGS            : 
11:54:12  EXTRA_LDFLAGS      : -link -DEBUG
11:54:12  DSO_LDFLAGS        : -LD
11:54:12  LIBS               : 
11:54:12  RPATH_EXTRA        : 
11:54:12  
11:54:12  XSLTPROC           : false
11:54:12  XSLROOT            : 
11:54:12  
11:54:12  PREFIX             : /usr/local
11:54:12  BINDIR             : /usr/local/bin
11:54:12  DATADIR            : /usr/local/share
11:54:12  INCLUDEDIR         : /usr/local/include
11:54:12  LIBDIR             : /usr/local/lib
11:54:12  MANDIR             : /usr/local/share/man
11:54:12  
11:54:12  srcroot            : 
11:54:12  abs_srcroot        : /e/ade/hudson/workspace/Lab.build-jemalloc/jemalloc/
11:54:12  objroot            : 
11:54:12  abs_objroot        : /e/ade/hudson/workspace/Lab.build-jemalloc/jemalloc/
11:54:12  
11:54:12  JEMALLOC_PREFIX    : je_
11:54:12  JEMALLOC_PRIVATE_NAMESPACE
11:54:12                     : je_
11:54:12  install_suffix     : 
11:54:12  malloc_conf        : 
11:54:12  autogen            : 1
11:54:12  debug              : 0
11:54:12  stats              : 1
11:54:12  prof               : 0
11:54:12  prof-libunwind     : 0
11:54:12  prof-libgcc        : 0
11:54:12  prof-gcc           : 0
11:54:12  thp                : 0
11:54:12  fill               : 1
11:54:12  utrace             : 0
11:54:12  xmalloc            : 0
11:54:12  log                : 0
11:54:12  lazy_lock          : 0
11:54:12  cache-oblivious    : 1
11:54:12  cxx                : 0
11:54:12  ===============================================================================
11:54:13  
11:54:13  E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc>cd msvc 
11:54:13  
11:54:13  E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc\msvc>devenv jemalloc_vc2015.sln /build "Debug" 
11:54:18  
11:54:18  Microsoft Visual Studio 2015 Version 14.0.25420.1.
11:54:18  Copyright (C) Microsoft Corp. All rights reserved.
11:54:18  1>------ Build started: Project: jemalloc, Configuration: Debug x64 ------
11:54:20  1>  witness.c
11:54:20  1>  tsd.c
11:54:21  1>  ticker.c
11:54:21  1>  tcache.c
11:54:21  1>  sz.c
11:54:22  1>  stats.c
11:54:22  1>  rtree.c
11:54:23  1>  prof.c
11:54:23  1>  prng.c
11:54:23  1>  pages.c
11:54:24  1>  nstime.c
11:54:24  1>  mutex_pool.c
11:54:25  1>  mutex.c
11:54:25  1>  malloc_io.c
11:54:25  1>  log.c
11:54:26  1>  large.c
11:54:26  1>  jemalloc.c
11:54:26  1>  hooks.c
11:54:27  1>  hash.c
11:54:27  1>  extent_mmap.c
11:54:28  1>  Generating Code...
11:54:28  1>  Compiling...
11:54:28  1>  extent_dss.c
11:54:29  1>  extent.c
11:54:29  1>  ctl.c
11:54:30  1>  ckh.c
11:54:30  1>  bitmap.c
11:54:30  1>  base.c
11:54:31  1>  background_thread.c
11:54:31  1>  arena.c
11:54:32  1>  Generating Code...
11:54:33  1>     Creating library E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc\msvc\x64\Debug\jemallocd.lib and object E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc\msvc\x64\Debug\jemallocd.exp
11:54:33  1>large.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>prof.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>tcache.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>arena.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>ckh.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>ctl.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>jemalloc.obj : error LNK2001: unresolved external symbol bin_infos
11:54:33  1>E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc\msvc\x64\Debug\jemallocd.dll : fatal error LNK1120: 1 unresolved externals
11:54:33  2>------ Build started: Project: test_threads, Configuration: Debug x64 ------
11:54:33  2>  test_threads_main.cpp
11:54:35  2>  test_threads.cpp
11:54:36  2>  Generating Code...
11:54:37  2>  test_threads.vcxproj -> E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc\msvc\x64\Debug\test_threads.exe
11:54:37  2>  test_threads.vcxproj -> E:\ade\hudson\workspace\Lab.build-jemalloc\jemalloc\msvc\x64\Debug\test_threads.pdb (Full PDB)
11:54:37  ========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by maksqwe** [comment]
Should be fixed by https://github.com/jemalloc/jemalloc/pull/1130

**Comment by davidtgoldblatt** [comment]
Should be fixed after #1130.
