### ISSUE TITLE
Faulty address always the end of mmapped area.

### ISSUE THREAD

**Issue by antirez** [jemalloc/jemalloc#1126]
Hello, this is not a proper bug report, probably there is nothing wrong in jemalloc 4.0.3, but maybe knowing the allocator internals somebody here could help me.

I'm seeing a recurring Redis crash in the radix tree implementation. The crash address is very puzzling (reported by Redis crash report, checking `info->si_addr` in the `siginfo_t` structure reported to the signal handler). The following are three addresses accessed during the crashes:

* 0x7fce9c400000
* 0x7f2959e00000
* 0x7f0e9b800000

At first I thought that it was some bug in the rax tree memmove/memcpy calls not copying a whole address or zeroing for error the final bytes. However because the Redis crash report always reports the maps in the process memory, I noticed that the addresses are always at the end of the map used by Jemalloc for the help.

For instance the crash at 0x7f0e9b800000 also outputs this:

    *** Preparing to test memory region 7f0e8c400000 (255852544 bytes)

And 0x7f0e8c400000+255852544 is exactly 0x7f0e9b800000

This is consistent among the crashes. AFAIK there is no code in my program which scans the memory to hit the memory page, it's a radix tree so it manages small allocations of nodes, there are many reallocations and memmoves and things like that. At some point, when there is to access a new node linked in previous node, the address I found inside appears to be the one of the broken page. No way to reproduce the bug, so I can only use the information reported by the three users that happened to have this problem.

Any hint will be appreciated. Thank in advance.

**Comment by antirez** [comment]
Apparently it is the reverse, AFAIK my bug only happens when I happen to release a node at the end of the mmapped region, so that the non mapped address works as a guard.

**Comment by davidtgoldblatt** [comment]
Just to clarify, by radix tree implementation, you mean the one in redis, and not the jemalloc rtree module, right? Could you describe a little the allocation strategy? (E.g. does everything live in one big malloc, or do you one malloc per level, etc.).

**Comment by davidtgoldblatt** [comment]
Closing for now, looks like this was resolved: http://antirez.com/news/117 . Feel free to reopen if I've mixed up issues.
