### ISSUE TITLE
jemalloc 5 and transparent hugepages

### ISSUE THREAD

**Issue by viveksjain** [jemalloc/jemalloc#1127]
What is the expected behavior/interactions with jemalloc 5 and transparent hugepages? I saw there were some changes made in #243 but from my cursory browsing of the code it seems like there are no actual calls to `pages_nohuge` in jemalloc 5. I see #932 is open but I wanted to understand what the expected behavior and motivation for **not** calling MADV_NOHUGEPAGE in jemalloc 5 is.

To give some additional context, we have an application with lots of threads (~1000 is typical) and with jemalloc 5 we've seen instances where the application's RSS is 50% higher than what jemalloc itself reports (based on malloc_stats_print's `mapped` stat). We've turned off THP for now, but of course we don't want to be forced to do so just because of jemalloc. Also, would you recommend switching to jemalloc 4 (we haven't tried this yet)?

**Comment by davidtgoldblatt** [comment]
To be honest, I don't think any of us ever really thought too hard about the case where the user wants hugepages for all but heap memory. Seems like a reasonable MALLOC_CONF option. It might be awhile before one of us gets to it, though.

Trying 4.5 wouldn't be crazy. An OK short-term fix would be to just modify the pages module to madvise after mapping.

**Comment by viveksjain** [comment]
Thanks for the response @davidtgoldblatt. It's more that we want hugepages for all other processes running on the system except the jemalloc one.

So out of curiosity, was there a reason v5 doesn't try to handle THP? Or was it just lost in the big rewrite from v4 to v5?

**Comment by davidtgoldblatt** [comment]
I think we just forgot about it to be honest. Or at least, I don't remember it being it on my radar, but I wasn't heavily involved in the de-chunkification. Maybe @interwq remembers for sure?

**Comment by interwq** [comment]
@viveksjain: we just discussed about adding a simple runtime option to turn on / off THP. Will let you know when that ships (in a week or two).

**Comment by viveksjain** [comment]
@interwq great, thank you! FYI we probably won't be able to test it properly for a few weeks, so no rush from our side.
