### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by urhue** [jemalloc/jemalloc#1135]
I want to build aria2c with jemalloc but it semmed listed errors.
My system is Debian test. glibc version is Debian GLIBC 2.26-6
Is there any advice for me?

>/opt/aria2/build_libs/lib/libjemalloc.a(jemalloc.o): In function `malloc_init_hard_a0_locked':
/jemalloc/src/jemalloc.c:1222: undefined reference to `pthread_self'
/opt/aria2/build_libs/lib/libjemalloc.a(jemalloc.o): In function `malloc_init_hard_needed':
/jemalloc/src/jemalloc.c:1196: undefined reference to `pthread_self'
/opt/aria2/build_libs/lib/libjemalloc.a(jemalloc.o): In function `malloc_ncpus':
/jemalloc/src/jemalloc.c:729: undefined reference to `pthread_getaffinity_np'
/opt/aria2/build_libs/lib/libjemalloc.a(jemalloc.o): In function `malloc_init_hard_recursible':
/jemalloc/src/jemalloc.c:1301: undefined reference to `pthread_atfork'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_thread_create_signals_masked':
/jemalloc/src/background_thread.c:360: undefined reference to `pthread_sigmask'
/jemalloc/src/background_thread.c:370: undefined reference to `pthread_sigmask'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_thread_entry':
/jemalloc/src/background_thread.c:503: undefined reference to `pthread_self'
/jemalloc/src/background_thread.c:503: undefined reference to `pthread_setname_np'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_thread_sleep':
/jemalloc/src/background_thread.c:254: undefined reference to `pthread_cond_timedwait'
/jemalloc/src/background_thread.c:231: undefined reference to `pthread_cond_wait'
/jemalloc/src/background_thread.c:254: undefined reference to `pthread_cond_timedwait'
/jemalloc/src/background_thread.c:231: undefined reference to `pthread_cond_wait'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_threads_disable_single':
/jemalloc/src/background_thread.c:326: undefined reference to `pthread_cond_signal'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_thread_create_signals_masked':
/jemalloc/src/background_thread.c:360: undefined reference to `pthread_sigmask'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `je_background_thread_create':
/jemalloc/src/background_thread.c:554: undefined reference to `pthread_cond_signal'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_thread_create_signals_masked':
/jemalloc/src/background_thread.c:370: undefined reference to `pthread_sigmask'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `background_threads_disable_single':
/jemalloc/src/background_thread.c:326: undefined reference to `pthread_cond_signal'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `je_background_thread_interval_check':
/jemalloc/src/background_thread.c:707: undefined reference to `pthread_cond_signal'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `je_background_thread_postfork_child':
/jemalloc/src/background_thread.c:756: undefined reference to `pthread_cond_init'
/opt/aria2/build_libs/lib/libjemalloc.a(background_thread.o): In function `je_background_thread_boot1':
/jemalloc/src/background_thread.c:869: undefined reference to `pthread_cond_init'
collect2: error: ld returned 1 exit status

**Comment by davidtgoldblatt** [comment]
Looks like you're not linking against pthreads; how did you configure the build?

**Comment by urhue** [comment]
The configure of aria2 is listed
(All lib installed properly)

## config ##
PREFIX=/usr
C_COMPILER="gcc"
CXX_COMPILER="g++"

## BUILD ##
PKG_CONFIG_PATH=/opt/aria2/build_libs/lib/pkgconfig/ \
LD_LIBRARY_PATH=/opt/aria2/build_libs/lib/ \
CC="$C_COMPILER" \
CXX="$CXX_COMPILER" \
./configure \
    --prefix=$PREFIX \
    --without-libxml2 \
    --without-libgcrypt \
    --with-openssl \
    --without-libnettle \
    --without-gnutls \
    --without-libgmp \
	--with-libz \
    --with-libssh2 \
    --with-sqlite3 \
    --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' \
    ARIA2_STATIC=yes \
	--with-jemalloc \
    --enable-shared=no
