### ISSUE TITLE
jemalloc can't work on iOS

### ISSUE THREAD

**Issue by thinkperson** [jemalloc/jemalloc#1138]
Hello, We intend to resolve memory fragment via jemalloc,but it seems that jemalloc can't work on iOS.
when I call je_malloc_stats_print(NULL, NULL, NULL), I get the following echo:

[jemalloc]: Unsupported system page size
[jemalloc]: Memory allocation failure in mallctl("epoch", ...)

Any suggestion to make it work on iOS? 

Thank you.

**Comment by interwq** [comment]
It looks the page size wasn't configured or detected properly. I have no experience with iOS, is the page size in your system not 4k?

**Comment by michaeleisel** [comment]
The page size can be 16KB for newer phones

**Comment by xionghengheng** [comment]
How do you compile a static library for iOS?

**Comment by xionghengheng** [comment]
@michaeleisel i got same error, when i configue as your code
```
Undefined symbols for architecture x86_64:
  "_je_free", referenced from:
      operator delete(void*) in jemalloc_cpp.pic.o
      operator delete[](void*) in jemalloc_cpp.pic.o
      operator delete(void*, std::nothrow_t const&) in jemalloc_cpp.pic.o
      operator delete[](void*, std::nothrow_t const&) in jemalloc_cpp.pic.o
  "_je_malloc", referenced from:
      operator new(unsigned long) in jemalloc_cpp.pic.o
      operator new[](unsigned long) in jemalloc_cpp.pic.o
      operator new(unsigned long, std::nothrow_t const&) in jemalloc_cpp.pic.o
      operator new[](unsigned long, std::nothrow_t const&) in jemalloc_cpp.pic.o
      handleOOM(unsigned long, bool) in jemalloc_cpp.pic.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libjemalloc.2.dylib] Error 1
```

**Comment by xionghengheng** [comment]
it works, set the page size =16KB
'''
#define LG_PAGE 14
'''
