### ISSUE TITLE
Type truncation warnings in Visual Studio 2017

### ISSUE THREAD

**Issue by madscientist** [jemalloc/jemalloc#1142]
I saw issue #341 which appeared to try to solve the last of these issues, but unless I'm confused it actually created new issues.  I'm getting these warnings compiling jemalloc 4.5.0 (but I see the code is the same in master HEAD):
```
src\prof.c(978): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
src\util.c(64): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
```
The issue is that on Windows, the `write()` call takes an `unsigned int` as the last argument not a `size_t` (see https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/write ).  Thus when you pass a `size_t` value to it you get this warning.  In the first instance it's because `prof_dump_buf_end` has type `size_t`.  In the second case it's because we pass the return from `strlen()` (which returns `size_t`) as the length.

**Comment by interwq** [comment]
Hi, can you please try if the issue remains in the dev branch? The most recent 5.0 release had a major rewrite.
