### ISSUE TITLE
Possible Deadlock

### ISSUE THREAD

**Issue by N1cotin** [jemalloc/jemalloc#1143]
Hello,

for my program, which constantly allocates and deallocates large chunks of memory, I was searching for a new allocator.

I've made the switch from TCMalloc and instantly noticed an increase in speed.
Sadly now my program keeps getting stuck randomly in multiple places.

Everytime it happens, an objects lifetime expires.

Here are some example stacktraces:

This happend when joining multiple threads.

    __lll_lock_wait 0x00007ffff723273c
    pthread_mutex_lock 0x00007ffff722ba55
    malloc_mutex_lock_final mutex.h:141
    je_malloc_mutex_lock_slow mutex.c:84
    malloc_mutex_lock mutex.h:205
    je_tcache_bin_flush_small tcache.c:134
    tcache_flush_cache tcache.c:463
    tcache_destroy tcache.c:493
    je_tcache_cleanup tcache.c:522
    tsd_do_data_cleanup tsd.c:209
    je_tsd_cleanup tsd.c:234
    __nptl_deallocate_tsd.part.5 0x00007ffff72281b8
    start_thread 0x00007ffff72291e5
    clone 0x00007ffff6f60e7f

Or when exiting the program (Only one thread running at this moment, all other threads already joined):

    __lll_lock_wait 0x00007ffff723273c
    pthread_mutex_lock 0x00007ffff722ba55
    malloc_mutex_lock_final mutex.h:141
    je_malloc_mutex_lock_slow mutex.c:84
    malloc_mutex_lock mutex.h:205
    je_tcache_bin_flush_small tcache.c:134
    tcache_dalloc_small tcache_inlines.h:178
    arena_dalloc arena_inlines_b.h:224
    idalloctm jemalloc_internal_inlines_c.h:118
    ifree jemalloc.c:2200
    free jemalloc.c:2371
    __gnu_cxx::new_allocator<std::__detail::_Hash_node<unsigned long, false> >::deallocate new_allocator.h:125
    std::allocator_traits<std::allocator<std::__detail::_Hash_node<unsigned long, false> > >::deallocate alloc_traits.h:462
    std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<unsigned long, false> > >::_M_deallocate_node hashtable_policy.h:2086
    std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<unsigned long, false> > >::_M_deallocate_nodes hashtable_policy.h:2097
    std::_Hashtable<unsigned long, unsigned long, std::allocator<unsigned long>, std::__detail::_Identity, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::clear hashtable.h:2029
    std::_Hashtable<unsigned long, unsigned long, std::allocator<unsigned long>, std::__detail::_Identity, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::~_Hashtable hashtable.h:1355
    std::unordered_set<unsigned long, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >::~unordered_set unordered_set.h:96
    CacheEntry::~CacheEntry CacheEntry.h:12
    std::default_delete<CacheEntry>::operator() unique_ptr.h:78
    std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> >::~unique_ptr unique_ptr.h:268
    std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > >::~pair stl_pair.h:198
    __gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > > new_allocator.h:140
    std::allocator_traits<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > > alloc_traits.h:487
    std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > >, true> > >::_M_deallocate_node hashtable_policy.h:2084
    std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > >, true> > >::_M_deallocate_nodes hashtable_policy.h:2097
    std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear hashtable.h:2029
    std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable hashtable.h:1355
    std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<CacheEntry, std::default_delete<CacheEntry> > > > >::~unordered_map unordered_map.h:101
    QueryCache::~QueryCache QueryCache.h:13
    std::default_delete<QueryCache>::operator() unique_ptr.h:78
    std::unique_ptr<QueryCache, std::default_delete<QueryCache> >::~unique_ptr unique_ptr.h:268
    JSONContainer::~JSONContainer JSONContainer.h:24
    std::default_delete<JSONContainer>::operator() unique_ptr.h:78
    std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> >::~unique_ptr unique_ptr.h:268
    std::_Destroy<std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> > > stl_construct.h:98
    std::_Destroy_aux<false>::__destroy<std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> >*> stl_construct.h:108
    std::_Destroy<std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> >*> stl_construct.h:137
    std::_Destroy<std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> >*, std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> > > stl_construct.h:206
    std::vector<std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> >, std::allocator<std::unique_ptr<JSONContainer, std::default_delete<JSONContainer> > > >::~vector stl_vector.h:434
    JSONStorage::~JSONStorage JSONStorage.cpp:276
    __gnu_cxx::new_allocator<JSONStorage>::destroy<JSONStorage> new_allocator.h:140
    std::allocator_traits<std::allocator<JSONStorage> >::destroy<JSONStorage> alloc_traits.h:487
    std::_Sp_counted_ptr_inplace<JSONStorage, std::allocator<JSONStorage>, (__gnu_cxx::_Lock_policy)2>::_M_dispose shared_ptr_base.h:535
    std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release shared_ptr_base.h:154
    std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count shared_ptr_base.h:684
    std::__shared_ptr<JSONStorage, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr shared_ptr_base.h:1123
    std::shared_ptr<JSONStorage>::~shared_ptr shared_ptr.h:93
    std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> >::~pair stl_pair.h:198
    __gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > > new_allocator.h:140
    std::allocator_traits<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > > alloc_traits.h:487
    std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> >, true> > >::_M_deallocate_node hashtable_policy.h:2084
    std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> >, true> > >::_M_deallocate_nodes hashtable_policy.h:2097
    std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear hashtable.h:2029
    std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable hashtable.h:1355
    std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<JSONStorage>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<JSONStorage> > > >::~unordered_map unordered_map.h:101
    StorageCollection::~StorageCollection StorageCollection.cpp:101
    __run_exit_handlers 0x00007ffff6ea2448
    exit 0x00007ffff6ea249a
    __libc_start_main 0x00007ffff6e8bf51
    _start 0x00005555555de2ba

I'm using Arch-Linux and have the same problem, no matter if using the packaged version of JeMalloc (5.0.1-4) or building my own version, with default compile-arguments from the dev-branch.

I also tested it on ubuntu with the package (3.6.0-9ubuntu1).
I'm not sure if I'm doing something wrong (or if I even can do something wrong, as it is supposed to be a drop-in replacement).

The code runs normal with TCMalloc and the default system allocators of arch and ubuntu.

Systems on which I tested it and could reproduce the problem:

    OS: Arch Linux
    JeMalloc: Package (5.0.1-4)
    GCC: 7.3.0

    OS: Arch Linux
    JeMalloc: dev-branch compiled with default arguments
    GCC: 7.3.0

The problem does not seem to exist when compiling on:

    OS: Debian
    JeMalloc: Package (3.6.0-9ubuntu1)
    GCC: 5.4.0-6ubuntu1

Any help would be appreciated, as I'd like to keep the performance-gains of JeMalloc

**Comment by interwq** [comment]
Can you please try building the dev branch with --enable-debug (it uses jemalloc debug mode which does lock order checking etc), and share the stack trace when it happens? It might be some initialization issue.

**Comment by N1cotin** [comment]
Thank you for the hint.

Of course the problem stemmed from UB in my program.

One old polymorphic class was missing the virtual deconstructor, which was caught by the size assert in ``je_sdallocx(void *ptr, size_t size, int flags)``.

I don't know how this did not make any trouble before.

Sorry for the trouble.
