### ISSUE TITLE
What will happen if mix use of jemalloc with glibc's malloc in a single application?

### ISSUE THREAD

**Issue by qunying** [jemalloc/jemalloc#1145]
Hi,

I have an application, due to some uncontrollable situation, some part of the app is using a dependent lib which is using jemalloc, while other part of it is using glibc's malloc. It has been made sure everything is properly allocate/free with the the corresponding functions, would this kind of usage bring any potential problem?

**Comment by davidtgoldblatt** [comment]
It should be fine, so long as no pointers intermingle. I would recommend using the --with-jemalloc-prefix=your_prefix configure option, so that the jemalloc versions are named (e.g.) your_prefix_malloc, your_prefix_free, etc.

**Comment by qunying** [comment]
Yes, all jemalloc funcitons are compiled with prefix with je_

**Comment by interwq** [comment]
Closing assume solved. Please reopen if otherwise.
