### ISSUE TITLE
It can not  configure  path for generate the jemalloc dump file 

### ISSUE THREAD

**Issue by charmingcow** [jemalloc/jemalloc#1164]
MALLOC_CONF="prof_leak:true,lg_prof_sample:0,prof_final:true" /usr/bin/ceph-osd -f --cluster ceph --id 25 --setuser ceph --setgroup ceph
<jemalloc>: creat("jeprof.23480.0.f.heap"), 0644) failed
 
I used jemalloc to check ceph-osd memory, but the dump file seems like to be written to root /,
but the setuid is ceph,not root. so it caused create faile.
 
 
did have any configure the path for the dump file ?

**Comment by interwq** [comment]
You can use prof_prefix to specify the path. http://jemalloc.net/jemalloc.3.html#opt.prof_prefix

**Comment by interwq** [comment]
Closing for now. Feel free to let us know if any questions.

**Comment by charmingcow** [comment]
tks. 
it works like below:
 MALLOC_CONF="prof_leak:true,lg_prof_sample:0,prof_final:true,prof_prefix:/home/jemalloc"

/home/jemalloc.26870.0.f.heap
