### ISSUE TITLE
Intermittent background thread failures

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1183]
Seems to be a timing issue; it's hard to reproduce unless the test is somewhat starved for CPU time. Commands that will repro at dev (on my laptop):

```
./configure --enable-debug --with-malloc-conf=tcache:false,background_thread:true
make -j tests
seq 1000 | parallel -P128 test/unit/pack
```

Some runs will fail with: `<jemalloc>: src/background_thread.c:401: Failed assertion: "info->state != background_thread_paused"`

**Comment by interwq** [comment]
This doesn’t look good. Just to make sure, it’s happening on the current dev?

**Comment by davidtgoldblatt** [comment]
Yep. I tried a commit back in October and couldn't repro, so the window to bisect through isn't super large.

**Comment by interwq** [comment]
I likely introduced something new when fixing other stuff. Feel free to send the task my way.

**Comment by davidtgoldblatt** [comment]
Bisects to 21eb0d15a6cfdaee3aa78f724838b503053d7f00 .
