### ISSUE TITLE
Crash libjemalloc.so.1

### ISSUE THREAD

**Issue by 4ippers** [jemalloc/jemalloc#1184]
Hi. Can you help me figure it out.
In kernel log i see this:
general protection ip:7f72573c2159 sp:7f71feffab90 error:0 in libjemalloc.so.1[7f72573b4000+34000]
In my program i see: segfault. 
How i can debug it ? 
Thank you for you help

**Comment by interwq** [comment]
This most likely indicates heap corruption caused by application. I'd look at the crash stack trace first, if that doesn't point you to something obvious, sanitizers such as ASAN are very helpful in cases like this.
