### ISSUE TITLE
Intermittent memory growth

### ISSUE THREAD

**Issue by memoryhog** [jemalloc/jemalloc#1189]
Same hardware using jemalloc 5.1 and 4, we see that sometimes jemalloc is super effective and the SAR(system activity report) is solid but sometimes the kbcommit grows rapidly causing the OOM killer to be triggered.
We have kept all variables constant across multiple systems, same type of operation.

Why is kbcommit growing sometimes? We have tried both LD_PRELOAD as well as linking in jemalloc. We are using libc 2.12. Kernel  2.6.32-358.

GOOD SAR output,

![image](https://user-images.githubusercontent.com/38598809/39091275-1c04bf4c-45ae-11e8-93ec-99b13e1515b2.png)

BAD sar output
![image](https://user-images.githubusercontent.com/38598809/39091281-2de650c2-45ae-11e8-8238-a428774fb96e.png)

**Comment by interwq** [comment]
@memoryhog: THP set to always definitely have a high impact on rss. I'd investigate that first. I'd also try the current dev branch (which is the 5.1 release candidate) instead of 5.0.1, since we fixed a few issues that could contribute to fragmentation, in case it's related.

**Comment by davidtgoldblatt** [comment]
The thread to arena mapping is done at startup, and can vary from run to run; whether or not a producer-consumer pair (for instance) get mapped to the same arena or not can affect memory consumption; trying out manual thread->arena bindings may be helpful. (Of course, producer-consumer pairs with no backpressure is arguably an application bug, too, but arena management can be an OK way around that).

**Comment by memoryhog** [comment]
@davidtgoldblatt we are at out wit's end, we have tried the thread to arena binding with the dev branch with no luck. Commit mem grows with a smaller slope, but grows. we have tried the diry and muzzy to 0 with no luck. Something just fell in place when we had the good run and we dont know what it is.

**Comment by memoryhog** [comment]
should we disable overcommit? we are currently using the default setting of zero.

**Comment by memoryhog** [comment]
This is the malloc stat output for our process that consumes the most memory.
I am posting the very first readout and the last one when the memory was high. Any help or pointer is much appreciated.

___ Begin jemalloc statistics ___
Version: 0.0.0-0-g0000000000000000000000000000000000000000
Assertions disabled
config.malloc_conf: ""
Run-time option settings:
  opt.abort: false
  opt.lg_chunk: 21
  opt.dss: "secondary"
  opt.narenas: 32
  opt.purge: "ratio"
  opt.lg_dirty_mult: 3 (arenas.lg_dirty_mult: 3)
  opt.junk: "false"
  opt.quarantine: 0
  opt.redzone: false
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.stats_print: false
Arenas: 32
Min active:dirty page ratio per arena: 8:1
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Allocated: 640085328, active: 641544192, metadata: 3022720, resident: 643928064, mapped: 677380096, retained: 0
Current active ceiling: 675282944

Merged arenas stats:
assigned threads: 19
dss allocation precedence: N/A
min active:dirty page ratio: N/A
purging: dirty: 43, sweeps: 11, madvises: 16, purged: 1031
                            allocated      nmalloc      ndalloc    nrequests
small:                       14740816       192072         4923       348256
large:                        2490368          152          106          168
huge:                       622854144           23            0           23
total:                      640085328       192247         5029       348447
active:                     641544192
mapped:                     675282944
retained:                           0
metadata: mapped: 1331200, allocated: 815616



Version: 0.0.0-0-g0000000000000000000000000000000000000000
Assertions disabled
config.malloc_conf: ""
Run-time option settings:
  opt.abort: false
  opt.lg_chunk: 21
  opt.dss: "secondary"
  opt.narenas: 32
  opt.purge: "ratio"
  opt.lg_dirty_mult: 3 (arenas.lg_dirty_mult: 3)
  opt.junk: "false"
  opt.quarantine: 0
  opt.redzone: false
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.stats_print: false
Arenas: 32
Min active:dirty page ratio per arena: 8:1
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Allocated: 1241193016, active: 1243561984, metadata: 3201472, resident: 1271967744, mapped: 1280311296, retained: 29360128
Current active ceiling: 1275068416

Merged arenas stats:
assigned threads: 19
dss allocation precedence: N/A
min active:dirty page ratio: N/A
purging: dirty: 6353, sweeps: 567, madvises: 2115, purged: 3914640
                            allocated      nmalloc      ndalloc    nrequests
small:                       19208760      8226650      7934867     14011194
large:                        2490368          165          119          181
huge:                      1219493888          897          852          897
total:                     1241193016      8227712      7935838     14012272
active:                    1243561984
mapped:                    1278214144
retained:                    29360128
metadata: mapped: 1490944, allocated: 818432

**Comment by memoryhog** [comment]
We are baffled since we had solid runs for 2 days with jemalloc stable 4 and we done get the same performance all the time. With everything else being constant.

**Comment by jasone** [comment]
These stats say that your process is consuming ~1.2 GiB of RAM, ~98% of which is huge allocations (>= 2 MiB), and external fragmentation is very low (~0.2%).  Do you expect your process to use 1.2 GiB of RAM?  If not, the heap profiling functionality in jemalloc should be able to help you figure out how the memory is being allocated.

**Comment by chittad** [comment]
We found some system shared memory leaks by our processes, so the used/commit memory grows occasionally. 
Thank you for the pointer.

**Comment by interwq** [comment]
You are welcome. Let us know if anything more.
