### ISSUE TITLE
leveldb load cause process cost high memory,jemalloc will not release memory until used it again?

### ISSUE THREAD

**Issue by charmingcow** [jemalloc/jemalloc#1190]
leveldb load cause process cost high memory,jemalloc will not release memory until  process used it again?

process init ,  memory high.

process used memory for some reason, memory reduce.

did that jemalloc cached some memory but that can be release ? and async gc or revoke some anons?

If I want to release a process which jemalloc cached memory,  has any tools? 
(such as java gc memory command, I used  linux c++)

Or any arguments configure can get the same aims.

tks all.

**Comment by interwq** [comment]
By default jemalloc keeps unused memory around for a bit, and purges them with a time-based decay algorithm. If you are thinking about purge unused memory manually, you can do so with the [purge mallctl](http://jemalloc.net/jemalloc.3.html#arena.i.purge).

**Comment by charmingcow** [comment]
@interwq,
tks.,I just like to gc a process memory from external command.
the time-based operation did must be enable background_thread?
I found that default background_thread is false.
Did the back-ground thread (bg_thd) will purge and revoke any memory not used currently?

do you have any detail more jemalloc gc releated docs or links 


ALLOC_CONF="prof:true,prof_gdump:true,background_thread:true" LD_PRELOAD=/lib64/libjemalloc.so.2 ./a.out

**Comment by interwq** [comment]
Purging can be controlled using runtime options, e.g. adding `dirty_decay_ms:0` will make freed pages purged eagerly. Alternatively, it can be done programmatically through mallctl, e.g. http://jemalloc.net/jemalloc.3.html#arena.i.purge

More details about tuning in this doc: https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md

If you want purging to be triggered externally, you will need to implement the mechanism in the application.

**Comment by interwq** [comment]
Feel free to let us know if more questions.
