### ISSUE TITLE
Fix VERSION

### ISSUE THREAD

**Issue by tpgxyz** [jemalloc/jemalloc#1213]
Hi,

in jemalloc-5.0.1 tarball you can find a file which contains this
`VERSION:5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb`

This VERSION is propagated to jemalloc.pc.in
`Version: @jemalloc_version@`

When you build a jemalloc with rpm then this error occurs:
`BUILDSTDERR: error: Invalid version (double separator '-'): 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb: pkgconfig(jemalloc) = 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb
`
Finally rpm strips pkgconfig(jemalloc) provides which is wrong. Please fix VERSION by removing that hash or push sanitized VERSION to jemalloc_version in jemalloc.pc.in

**Comment by jasone** [comment]
I don't think we should change the version string anywhere except possibly in `jemalloc.pc`.  As for which format is correct in `jemalloc.pc`, my rpm knowledge is too rusty to depend on, but I suspect the proper form is `<major>.<minor>.<bugfix>_<nrev>`.
