### ISSUE TITLE
specifying page size per arena

### ISSUE THREAD

**Issue by lionkov** [jemalloc/jemalloc#1219]
There are systems that support multiple huge page sizes. The page sizes can be controlled when the memory is allocated with mmap (MAP_HUGETLB | MAP_HUGE_SHIFT). With custom extent hooks, I can use these flags, but there is no way to force/inform jemalloc what is the size of the extent that is allocated. Is it acceptable to add a new per-arena setting (arena.<i>.pagesize) that specifies the granularity of the extent allocations? I can try to implement the functionality if it is likely to get merged.

**Comment by davidtgoldblatt** [comment]
I think an arena-level mallctl setting is probably the wrong place for this; expanding the extent hook API is probably better. This is one of the things we've talked about in #1009.

Unfortunately, a lot of these details leak all over the place, and would mean picking answers to some unresolved design questions. (For example: right now, page size determines minimum slab size; would we have multiple different slab sizes for the same size class in the same binary? Do we force slab sizes to be in the megabytes if we're using a hugepage as the slab size? Probably not, but those concepts need to be disentangled for this to be feasible.). We'd like movement in that direction, but I think it'd be pretty difficult for someone not deep in the guts of things to pull off.

Probably for your use case, you'll have an easier time maintaining a mini-allocator within your extent hooks, that you can keep track of the "true" state of the world in.

**Comment by interwq** [comment]
Adding to what David said, an example of using customized extent hooks managing 1G huge pages: [HHVM](https://github.com/facebook/hhvm/blob/master/hphp/util/alloc.cpp)

**Comment by lionkov** [comment]
Hmm, I didn't realize that slabs are basically extents. It definitely
doesn't make sense to force slabs to be the size of a huge page. I think
I'll go with a mini-allocator in my extent hooks -- implementing it in the
jemalloc won't be much simpler/more efficient.

Thanks!
On Thu, May 10, 2018 at 12:45 PM Qi Wang <notifications@github.com> wrote:

> Adding to what David said, an example of using customized extent hooks
managing 1G huge pages: HHVM

**Comment by interwq** [comment]
Feel free to let us know if anything!
