### ISSUE TITLE
Build 5.1.0 with Cygwin and vs2017 : file "private_namespace.h" is not auto generated

### ISSUE THREAD

**Issue by nneesshh** [jemalloc/jemalloc#1232]
the jemalloc.log says:
...jemalloc_preamble.h(43): fatal error C1083: Cannot open include file: 'jemalloc/internal/private_namespace.h': No such file or directory

Why this file is missing?

PS: After I add "JEMALLOC_NO_PRIVATE_NAMESPACE" flag to my vs2017 project manually, the build success.

**Comment by rustyx** [comment]
Could you post your jemalloc.log and the steps to reproduce the issue.

**Comment by tahsin352** [comment]
I am getting same error on mac. the files are in .gitignore, how to get those files?
