### ISSUE TITLE
jemalloc 5.0.1 TLS error: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by ldcsaa** [jemalloc/jemalloc#1237]
I hava a shared library .so, which compiled with static library jemalloc_pic.a.
Some application load my .so by dlopen().
When I use jemalloc 4.5.0 it works.
But when I upgrade to jemalloc 5.0.1, dlopen() fail: 'cannot allocate memory in static TLS block'.

**Comment by interwq** [comment]
For performance reasons jemalloc 5 uses more TLS space.  This causes isses for dlopen jemalloc where the pre allocated TLS may not be enough for jemalloc.  The option `--disable-initial-exec-tls` in [INSTALL.md](https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md) should solve it for you. For more details see the discussion in #937.
