### ISSUE TITLE
Crash when compiling palemoon under musl with jemalloc memory allocator

### ISSUE THREAD

**Issue by Sharrisii** [jemalloc/jemalloc#1238]
When building palemoon with jemmaloc (using musl), it crashes. Output:

(gdb) info stack
#0  0x08086f85 in je_arena_bitselm_get (pageind=167, chunk=0x8000000)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/include/jemalloc/internal/arena.h:467
#1  je_arena_mapbitsp_get (pageind=167, chunk=0x8000000)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/include/jemalloc/internal/arena.h:519
#2  je_arena_mapbits_get (pageind=167, chunk=0x8000000)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/include/jemalloc/internal/arena.h:533
#3  je_arena_mapbits_binind_get (pageind=167, chunk=0x8000000)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/include/jemalloc/internal/arena.h:574
#4  je_arena_salloc (demote=false, ptr=0x80a7e30)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/include/jemalloc/internal/arena.h:970
#5  je_isalloc (demote=false, ptr=0x80a7e30)
    at src/include/jemalloc/internal/jemalloc_internal.h:898
#6  ifree (tsd=<optimized out>, try_tcache=true, ptr=0x80a7e30)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/src/jemalloc.c:1643
#7  free (ptr=0x80a7e30)
    at /var/tmp/portage/www-client/palemoon-27.9.2/work/palemoon-27.9.2/memory/jemalloc/src/src/jemalloc.c:1738
#8  0xf1e52380 in g_free () from /usr/lib/libglib-2.0.so.0
#9  0xffffb804 in ?? ()

**Comment by interwq** [comment]
This stack trace mostly likely points to heap corruption by application. Consider using sanitizer like ASAN, or building jemalloc with --enable-debug to help further investigation.
