### ISSUE TITLE
memory still in control after madvise?

### ISSUE THREAD

**Issue by wenqicao** [jemalloc/jemalloc#1243]
I observed that jemalloc uses `madvise(dontneed)` to free memory to OS. But, AFAIK, `madvise` is only a hint for OS to show that currently I don't need this.
I wanna know after `madvise()`, is the memory still in control of jemalloc. will jemalloc immediately remove these memory regions from bins? or jemalloc can still manage these memory regions until OS actually recycle the backing page. Because, it is very possible in the near future someone asks memory from jemalloc, if these memory region are still in control, jemalloc can reuse them quickly. 

Thanks

**Comment by interwq** [comment]
`madvise(... MADV_DONTNEED)` does synchronous memory reclamation (only virtual memory is retained).

By default jemalloc uses time based decay (see [here](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms)) on unused free memory, which won't purge memory until it stays idle for a while (as frequent reuse is expected).

**Comment by wenqicao** [comment]
I guess synchronous memory reclamation happens only when 4KB page is used. If the backing page is 2MB (huge page), it is very possible that only several parts of one huge page is unmapped by using `madvise(.... MADV_DONTNEED)`. So, such huge page can't be return to OS. I wonder how jemalloc handles this situation.

**Comment by interwq** [comment]
By default jemalloc does not use huge pages for heap memory (there is opt.metadata_thp which uses THP for internal metadata though). It's possible to use custom [extent_hooks](http://jemalloc.net/jemalloc.3.html#arena.i.extent_hooks) to manage huge pages.
