### ISSUE TITLE
Investigate nmalloc > nrequests?

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#1245]
This should not happen, unless overflowed. Need to check it.

**Comment by interwq** [comment]
Found the pattern that causes this -- this usually happens on very unpopular small sizes (in our example bin size 448).

When tcache_fill, we batch allocate and fill the tcache with N items. However the thread may only needed a smaller number (say M items at most). When later on the bin is GCed, many items could be flushed because they stay unused. After this the N items allocated initially (which counted as nmalloc) only were used on M requests, where N > M is fine.

**Comment by jasone** [comment]
Aww crud, I saw you open this, and meant to comment on the probable cause, but apparently forgot.  I've investigated the issue at least twice. :wink:

**Comment by interwq** [comment]
lol, hope I can find this page next time the "issue" comes around!
