### ISSUE TITLE
How to check jemalloc version

### ISSUE THREAD

**Issue by zh623** [jemalloc/jemalloc#1246]
Hello everyone! I have a question about how to know jemalloc version.
When running the same benchamrks with two different libc.so files, I find different jemalloc functions are invoked based on VTune Amplifier, details data are in below table

libc.so-version1(ms) |  
-- | --
je_malloc | 56 |  
je_ticker_ticks | 31 |  
je_tcache_alloc_easy | 26 |  
je_arena_mapbits_binind_get | 24 |  
je_arena_salloc | 20 |  
je_arena_dalloc | 17 |  
je_tsd_fetch | 15 |  
je_tcache_dalloc_mall | 13 |  
je_tsd_wrapper_get | 10 |  
je_tcache_alloc_small | 9 |  
je_index2size_lookup | 8 |  
je_size2index | 6 |  
imalloc_body | 5 |  
je_arena_malloc | 4 |  
je_arena_mapbitsp_read | 3 |  
je_size2index_lookup | 3 |  
je_arena_malloc_hard | 2 |  
je_arena_ptr_small_binind_get | 2 |  
je_size2index_compute | 2 |  
je_arena_malloc_large | 1 |  
je_arena_miscelm_to_pageind | 1 |  
je_calloc | 1 |  
je_run_quantize_floor | 1 |  
je_tcache_get | 1 |  
je_tsd_tcache_get | 1 |  

libc.so-version2(ms) |  
-- | --
je_malloc | 244 |  
je_tcache_event_hard | 5 |  
je_arena_malloc_hard | 4 |  
je_nstime_update | 2 |  
je_nstime_compare | 1 |  
je_arena_dalloc_large | 1 |  
je_nstime_copy | 1 |  
je_nstime_divide | 1 |  

I guess the issue is caused by different jemalloc version. How could we know jemalloc version in libc.so? And could we speculate which version performance is better based on above VTune data?

**Comment by davidtgoldblatt** [comment]
Jemalloc is your libc allocator? That's fairly unusual for Linux; are you sure you're checking the right place?

Running `strings lib/libjemalloc.so | grep JEMALLOC_VERSION` will dump out some version info for me; it likely will get included in the libc in question as well.

**Comment by zh623** [comment]
thanks David for your reply.
Jemalloc is my libc allocator and the OS is Android.
there isn't libjemalloc.so in Android. I tried strings lib/libc.so | grep JEMALLOC_VERSION, but there isn't useful output.
Are there other methods or experiments I can try?

**Comment by davidtgoldblatt** [comment]
Ordinarily I'd suggest using the "version" mallctl to check; not sure if that works for your use case (or if the android folks expose that as well).

The first version seems like it's in the 4.X series. The second is probably 5.x (time-based purging exists in 4.4 and later, but was off by default until 5.0).

**Comment by zh623** [comment]
thanks David, I tried "version", but not work.
Do you know whether there is performance gap between 4.x and 5.x? or how can I check their performance impact?

**Comment by davidtgoldblatt** [comment]
In general, jemalloc versions only get better over time with respect to performance, but in a very peculiar sense that only includes those workloads we can test (which are heavily biased towards long-running server applications). We don't do performance testing on Android, so it's entirely possible that there are silly regressions there.

My guess is that things get better over time there too, but in a much bumpier way.
