### ISSUE TITLE
Unable to dlopen jemalloc dynamic library

### ISSUE THREAD

**Issue by EnzoMolion** [jemalloc/jemalloc#1249]
I am trying to `dlopen` memory allocators at runtime. 
I have no problem with `libc`, `tcmalloc` and `tbbmalloc`. But trying to `dlopen` `jemalloc` results in the following error (caught via `dlerror`) : 
`/path/to/lib/libjemalloc.so: cannot allocate memory in static TLS block` 

Do you have any idea of the reason for this error and hence how I could tackle this ?

----------
(I first wrote this on [stackoverflow](https://stackoverflow.com/questions/50839284/how-to-dlopen-jemalloc-dynamic-library) but I figured out this was a better place for this, thus the repost)

**Comment by interwq** [comment]
Please see #1237.
