### ISSUE TITLE
Application using jemalloc causes mmapped regions to grow beyond 65530 and result in an application to crash with std::bad_alloc

### ISSUE THREAD

**Issue by rudreshahk** [jemalloc/jemalloc#1256]
One of our application is using the jemalloc-5.0.1 with all default options crashes within few minutes of startup. But the same application runs for several days without any issue.
One of the difference found with and without jemalloc is with the number of mmapped regions the application creates. 
Without jemalloc, the number of mmapped regions for the application has not crossed 400. 
But with jemalloc, this reaches to 65K very quickly and that is when the application crashes.

The overcommit_memory is set to 2. Is this causing any issue in growing the number of mmapped regions?

OS Parameters:
vm.overcommit_memory = 2
vm.overcommit_ratio = 90
vm.max_map_count = 65530

OS Version:
kernel.osrelease = 2.6.32-696.30.1.el6.x86_64
kernel.version = #1 SMP Fri May 18 11:50:44 EDT 2018

**Comment by rudreshahk** [comment]
Setting the overcommit to default value has resolved this issue. After this setting the number of mmapped regions have not grown beyond 300 and application can stay up for long time taking queries.

Changed Values:
vm.overcommit_memory = 0
vm.overcommit_ratio = 50

**Comment by davidtgoldblatt** [comment]
Yeah; the combination of overcommit being disabled and the max map count being kept low means that it's very difficult to return unused memory to the OS (without hitting the map limit). I think disabling purging entirely may resolve the immediate issue (at the cost of increased memory use, of course).

**Comment by davidtgoldblatt** [comment]
(Or, increasing the maximum map count at the OS level).

**Comment by interwq** [comment]
Closing as #1328 has more context.
