### ISSUE TITLE
jemalloc `make tests` fail to link with musl

### ISSUE THREAD

**Issue by gnzlbg** [jemalloc/jemalloc#1269]
The library compiles just fine, `make` succeeds: https://travis-ci.org/gnzlbg/jemallocator/jobs/401201021#L974

but `make test` fails: https://travis-ci.org/gnzlbg/jemallocator/jobs/401201021#L1069

**Comment by gnzlbg** [comment]
Duh, one can't run `linux-musl` target  binaries on a `linux-gnu` host, sorry for the noise.

**Comment by davidtgoldblatt** [comment]
Although, if I remember correctly, we do have a bootstrapping issue of some sort there, where we'll deadlock if a library iteration function is called?
