### ISSUE TITLE
coredump in jemalloc

### ISSUE THREAD

**Issue by scottzzq** [jemalloc/jemalloc#1296]
#0  0x00000000014fac41 in je_tcache_arena_associate (tsdn=0x7fac1109fc60, tcache=0x7fac1109fe18, arena=0x7fadaebe98c0) at src/tcache.c:295
#1  0x00000000014fb9ec in arena_choose_impl (arena=0x0, internal=false, tsd=0x7fac1109fc60) at include/jemalloc/internal/jemalloc_internal_inlines_b.h:35
#2  arena_choose (arena=0x0, tsd=0x7fac1109fc60) at include/jemalloc/internal/jemalloc_internal_inlines_b.h:63
#3  je_tsd_tcache_data_init (tsd=tsd@entry=0x7fac1109fc60) at src/tcache.c:410
#4  0x00000000014fbac4 in je_tsd_tcache_enabled_data_init (tsd=tsd@entry=0x7fac1109fc60) at src/tcache.c:339
#5  0x00000000014fd279 in tsd_data_init (tsd=0x7fac1109fc60) at src/tsd.c:74
#6  je_tsd_fetch_slow (tsd=0x7fac1109fc60, internal=internal@entry=false) at src/tsd.c:126
#7  0x00000000014ab0f3 in tsd_fetch_impl (internal=false, init=true) at include/jemalloc/internal/tsd.h:260
#8  tsd_fetch () at include/jemalloc/internal/tsd.h:275
#9  imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:1940
#10 malloc (size=size@entry=384) at src/jemalloc.c:1977
#11 0x00000000014fd76c in newImpl<true> (size=384) at src/jemalloc_cpp.cpp:45
#12 0x00000000010058ff in bthread::TaskControl::create_group (this=this@entry=0x7fad0ede1700) at brpc/src/bthread/task_control.cpp:86
#13 0x0000000001005a31 in bthread::TaskControl::worker_thread (arg=0x7fad0ede1700) at brpc/src/bthread/task_control.cpp:62
#14 0x00007fadb0c34dc5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007fadb066021d in clone () from /lib64/libc.so.6

how to slove this problem?

**Comment by rustyx** [comment]
What OS, version, steps to reproduce please? Thanks.
