### ISSUE TITLE
why malloc_conf_init is called frequently ?

### ISSUE THREAD

**Issue by justmao945** [jemalloc/jemalloc#1299]
I'm not familiar with the code of jemalloc, but I don't think something called `init` should be called so frequently.
Here is the report from perf tool. The jemalloc version is 5.1.0
Please correct me if I'm wrong.
![image](https://user-images.githubusercontent.com/619331/43574941-0c863738-9678-11e8-86d6-af993402fbb9.png)

**Comment by davidtgoldblatt** [comment]
Huh, this is indeed very surprising. I can't think of anything that would cause this sort of behavior.

I don't think this is symbolizing correctly, though. Unless I'm very thoroughly confused, malloc_conf_init can't call stats_arena_bins_print. Perhaps some misattribution is going on?

**Comment by justmao945** [comment]
OK, thanks for you reply
