### ISSUE TITLE
Experiment with cache index randomization.

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#13]
Experiment with cache index randomization, for small and large objects.  Consider that with every large object aligned at a page boundary, hardware caches tend to get uneven use (set associativity only goes so far).  Perhaps the most critical performance issue here is that jemalloc puts *all* small run headers at page boundaries, so jemalloc metadata structures stress the cache very unevenly.  The fix is to put run headers in varied locations throughout runs, and to vary page offsets for large objects (perhaps even incur cost of one extra page of memory).  For more motivation, see e.g. [this message](http://lists.freebsd.org/pipermail/freebsd-questions/2013-September/253384.html).  For more information on the problem and a range of possible solutions, see ["Cache Index-Aware Memory Allocation"](http://www.researchgate.net/publication/221032970_Cache_index-aware_memory_allocation/file/9fcfd50e6f8f89524e.pdf), by Afek, Dice, and Morrison (ISSM 2011).

**Comment by jasone** [comment]
There remains no cache index randomization for huge allocations, but I think this will have to remain the case.  If huge allocations weren't chunk-aligned, then we would have to perform radix tree lookups for all reallocation/deallocation operations, but that could be optimized to be synchronization-free in the common case.  The more troubling problem is that it wouldn't be feasible to preserve the precisely spaced size classes; we would have to decrease all huge size classes by one page, and then applications which tend to ask for nice round sizes could end up with a lot of internal fragmentation.  The alternative of adding one pad page to huge allocations would cause unacceptable virtual memory fragmentation.

I don't think this is a terrible end point, because it's still possible to set a very large chunk size for applications which want cache index randomization even for their largest allocations.

**Comment by thestinger** [comment]
Huge allocations could be placed at a random offset inside the initial chunk only when they're not a multiple of the chunk size so there's some slack to work with. This would probably be unacceptable due to forcing a read from the chunk header and branch in the critical path for small allocations though. It would also leave out many common sizes of huge allocations (like powers of 2).

**Comment by jasone** [comment]
I was actually wrong about the need to do a radix tree read in the critical path, as long as the randomized huge object base pointer always falls within the first page of the containing chunk.  This is because arena chunks always have at least one full page reserved for metadata, so small/large objects cannot fall within the first page of the chunk.  I benchmarked the required change to ```arena_salloc()```, and it had no discernible impact.

@thestinger, the huge size classes that are not a multiple of the chunk size is pretty limited -- there are only five of them.  Otherwise I'd be game for implementing your suggestion.
