### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by dertin** [jemalloc/jemalloc#1327]
`/usr/local/php7/bin/php: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
`

https://github.com/dertin/lemp-stack-debian/blob/develop/install.sh#L721

After compiling jemalloc I only have the following file:
libjemalloc.so -> libjemalloc.so.2

should I create the link from libjemalloc.so.1 to ibjemalloc.so.2 ?

**Comment by vasanthchellappa** [comment]
Hi.,

Please install the following to fix the issue.

`apt-get install -y libjemalloc-dev`

**Comment by davidtgoldblatt** [comment]
Yeah, this is some sort of packaging / configuration issue more than a jemalloc one specifically. Perhaps the maintainers of the packages in question would know more.
