### ISSUE TITLE
How to have allocations fulfilled from a static fixed size mmaped file

### ISSUE THREAD

**Issue by pcmoritz** [jemalloc/jemalloc#1329]
Dear all,

I'm trying to achieve the following: At program startup, a fixed size memory mapped file is allocated and certain mallocs should be fulfilled from that file and malloc should return 0 if no more memory is available (in which case I will free some manually and try again).

Here is how I tried to achieve this:

```
void *pre_alloc;
void *pre_alloc_end;

static void *
AllocHook(extent_hooks_t *extent_hooks, void *new_addr, size_t size,
		size_t alignment, bool *zero, bool *commit, unsigned arena_index) {
  LOG(INFO) << "hook: " << size;
  char *ret = (char *) pre_alloc;
  if (ret + size >= pre_alloc_end) {
    LOG(INFO) << "returned null";
    return NULL;
  }
  pre_alloc = (char *)pre_alloc + size;
  return ret;
}
```
and then:
```
fd = CreateTempFile(directory, system_memory, &file_name);
pointer = mmap(NULL, system_memory, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
  pre_alloc = pointer;
  pre_alloc_end = (char *) pointer + system_memory;
  jemalloc_hooks = {AllocHook, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
  extent_hooks_t *new_hooks = &jemalloc_hooks;
  arena_index = -1;
  size_t index_size = sizeof(arena_index);
  size_t error = je_plasma_mallctl("arenas.create", (void *)&arena_index, &index_size, (void *)&new_hooks, sizeof(extent_hooks_t *));
```

However what I'm seeing is some strange behavior of allocations failing even after I have freed memory and jemalloc trying to request more memory via the AllocHook. I suspect it is trying to allocate some memory for internal data structures and failing. Is there an some "official" way to achieve what I'm trying? I also tried to limit the amount of memory jemalloc is requesting via arena.i.retain_grow_limit but it still seems to overallocate.

Best,
Philipp.

**Comment by pcmoritz** [comment]
If anybody has an idea on how to do this, help would be greatly appreciated! I'm currently still blocked by this.

**Comment by pbalcer** [comment]
Hi,
see libmemkind (it's based on jemalloc) solution to this problem: https://github.com/memkind/memkind/blob/master/src/memkind_pmem.c
Here's the manpage that describes how it's used: http://manpages.ubuntu.com/manpages/bionic/man3/memkind_pmem.3.html

Generally it's not as simple as it looks ;)

Piotr

**Comment by interwq** [comment]
Like in the approach @pbalcer shared, extent_hooks (http://jemalloc.net/jemalloc.3.html#arena.i.extent_hooks) is the way to do what you described. It provides a way to control how an arena gets its underlying memory. https://github.com/facebook/folly/blob/master/folly/experimental/JemallocNodumpAllocator.cpp is another simple example of using the hooks (to inject a nodump call).

**Comment by interwq** [comment]
Closing for now. Feel free to ask if anything.
