### ISSUE TITLE
Does opt.lg_prof_interval dump all or the part between two dump?

### ISSUE THREAD

**Issue by fairjm** [jemalloc/jemalloc#1332]
It's a question...I feel confused about dump behavior of the option.  
I asked it in stackoverflow(https://stackoverflow.com/questions/52466025/does-the-lg-prof-interval-in-jemalloc-mean-dump-the-heap-between-two-time-point) before but got no answer.  

I read some article using i150 as base to compare to i200.  
https://blog.inliniac.net/2014/12/23/profiling-suricata-with-jemalloc/  

But I try it myself find iN can be much smaller than i0.  
for example:
`export MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:17,prof_prefix:/root/jemallocdump/jeprof`  
```
Using local file /usr/lib/jvm/jdk1.8.0_122/bin/java.
Using local file /root/jemallocdump/jeprof.22137.0.i0.heap.
Total: 3013.0 MB
  2377.9  78.9%  78.9%   2377.9  78.9% updatewindow
   517.5  17.2%  96.1%    517.5  17.2% inflateInit2_
```
i0  

```
Using local file /usr/lib/jvm/jdk1.8.0_122/bin/java.
Using local file /root/jemallocdump/jeprof.22137.26.i26.heap.
Total: 250.2 MB
   170.9  68.3%  68.3%    170.9  68.3% os::malloc@8ca3b0
    34.1  13.6%  82.0%     34.1  13.6% _cmsMallocZeroDefaultFn
```  
i26  

It's not like i26 is the dump from very beginning but just the part from i25.  

I can't find more explanation.  
Thx for helping :)

**Comment by interwq** [comment]
Not sure if I understand the question, but prof_interval controls the gap between two dumps; while prof_sample indicates how often a sample is taken -- in your case every 128K an allocation is sampled (and will be included in the dump if alive). So not all allocations will be included.

**Comment by fairjm** [comment]
Yeah nearly.  
And my problem is I want to know for example the allocation in i50 dump file is from i49(last dump) or is from the application start.   

the dump is:
start <---allocation(sampled)---> i50
or
i49 <----allocation(sampled)---> i50 ?

**Comment by interwq** [comment]
The dump contains all sampled memory, so it's the first case (from the start). You can use prof.reset (http://jemalloc.net/jemalloc.3.html#prof.reset) if you want the other case effectively.

Closing for now. Feel free to ask if any questions.

**Comment by fairjm** [comment]
Thx a lot :)  
So In my example i26( 250.2 MB) much smaller than i0(3013.0MB) is it because some allocation is no longer alive?
