### ISSUE TITLE
Segmentation fault (SEGV_MAPERR) on Android 7.1.2 (x86_64)

### ISSUE THREAD

**Issue by arunrajshanmugam** [jemalloc/jemalloc#1333]
[tombstone_01.txt](https://github.com/jemalloc/jemalloc/files/2434404/tombstone_01.txt)
[tombstone_02.txt](https://github.com/jemalloc/jemalloc/files/2434415/tombstone_02.txt)
[tombstone_04.txt](https://github.com/jemalloc/jemalloc/files/2434428/tombstone_04.txt)
[stacklog4.txt](https://github.com/jemalloc/jemalloc/files/2434443/stacklog4.txt)
[stacklog2.txt](https://github.com/jemalloc/jemalloc/files/2434444/stacklog2.txt)
[stacklog1.txt](https://github.com/jemalloc/jemalloc/files/2434445/stacklog1.txt)

Getting SEGV_MAPERR error while creating and launching new user. Attached tombstone and stack trace files for reference. SEGV_MAPERR gets reported at different places each time. Bug is not consistent(50/50).

SEGV_MAPERR error lines.
external/jemalloc/src/huge.c:99 (je_huge_palloc) (refer stacklog1.txt)
external/jemalloc/include/jemalloc/internal/extent.h:100 (je_extent_node_arena_get) (refer stacklog4.txt)

jemalloc version in use - 4.1.0.
How to debug this issue?
Could you help to check?

Thanks

**Comment by interwq** [comment]
Closing for now. Feel free to reopen if needed.
