### ISSUE TITLE
rtree_extents_read should return NULL if elm is NULL

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#1336]
This code in include/jemalloc/internal/rtree.h on the current dev branch and in jemalloc 5.1.0:

```
JEMALLOC_ALWAYS_INLINE extent_t *
rtree_extent_read(tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx,
    uintptr_t key, bool dependent) {
        rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key,
            dependent);
        if (!dependent && elm == NULL) {
                return NULL;
        }
        return rtree_leaf_elm_extent_read(tsdn, rtree, elm, dependent);
}
```

The code:

```
        if (!dependent && elm == NULL) {
                return NULL;
        }
```

Should probably just be:

```
        if (elm == NULL) {
                return NULL;
        }
```

There is no path through rtree_leaf_elm_extent_read that does not try and dereference the elm pointer.

It's possible this should have been !dependent || elm == NULL, but I'm not familiar enough with the code to be sure, so I don't want to offer a patch.

I noticed that this file has a few other cases where the same pattern is present if (!dependent && elm == NULL). Most of them also look suspicious and like they should also be if (elm == NULL) and skip the dependent check.

It's also possible that elm being NULL should never happen, so maybe this doesn't matter in the grand scheme of things.

**Comment by jasone** [comment]
I haven't looked at this code in a while, but my recollection is that if a read is truly dependent (lookup is on behalf of memory known to be in use), it is impossible to read a `NULL`.  Therefore, we only have to check for `NULL` in the `!dependent` case.

**Comment by cferris1000** [comment]
That sounds reasonable. I only ran into this when trying to free a bogus pointer and I wasn't sure if this code was okay or not.

I assume in the case of freeing a bad pointer, you get what you get.

**Comment by davidtgoldblatt** [comment]
Yes -- in practice, `dependent` is always statically known by the optimizer, so that the common paths can avoid these branches altogether.

Closing for now, can reopen if it turns out there's a case where this isn't true.
