### ISSUE TITLE
retain:true broken on FreeBSD

### ISSUE THREAD

**Issue by trasz** [jemalloc/jemalloc#1350]
Setting retain:true on FreeBSD results in replacing every call to `mmap(2)` with two calls, the second  one being the same as with retain:false, and the first one looking like this:

`+mmap(0x0,2097152,PROT_NONE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34387001344 (0x801a00000)`

This happens, because with `os_overcommits == true`, `extent_grow_retained()` fails and jemalloc falls back to `extent_alloc_wrapper_hard()`.

The `sysctl()` to obtain the value of vm.overcommit works correctly, it's just that the value obtained (`0`) is somehow incompatible with what jemalloc expects.

**Comment by interwq** [comment]
@trasz : thanks for the info! I remember we discussed this on gitter the other day -- can you remind me why the first call (within `grow_retained()`) failed?

**Comment by trasz** [comment]
It fails, because pages_commit_impl() returns true, because of os_overcommits is true.

**Comment by trasz** [comment]
Whoa.  Not only this fixes retained:true, but also - with retained:true enabled - solves #1339!  Thank you!

**Comment by interwq** [comment]
Closed via #1362.
