### ISSUE TITLE
adding metadata for region

### ISSUE THREAD

**Issue by wenqicao** [jemalloc/jemalloc#1358]
I am working on jemalloc 4.5. My goal is to add one metadata for each region. I want to use this metadata to record some address information. anyone knows where is the best place to do that? thanks

**Comment by interwq** [comment]
By region do you mean each allocation or for each `chunk` in jemalloc 4.x? BTW jemalloc 4 is in maintenance mode, so any completely new feature is unlikely to get merged upstream. I'd encourage working on jemalloc 5 instead.

**Comment by interwq** [comment]
Feel free to ask if more questions.
