### ISSUE TITLE
a question about cache_bin

### ISSUE THREAD

**Issue by UncP** [jemalloc/jemalloc#1370]
`cache_bin_s->avail` works like this, `bin->avail[-nached, ..., -1]`, in order to use cacheline prefetch, what's wrong with `bin->avail[0, ncached)`， they seem make no difference, prefetch still works.

**Comment by interwq** [comment]
The strategy is to better utilize simply prefetching like adjacent cacheline prefetch, where the next cacheline is fetched along with the requested one. So the avail stack is designed to have consecutive allocations moving towards higher address.
