### ISSUE TITLE
How to initialize jemalloc to a certain pre-allocated state.

### ISSUE THREAD

**Issue by fadingsoul** [jemalloc/jemalloc#1375]
Background: I have a snapshot of memory range on persistent memory, allocated by jemalloc, and I want to reuse the data(address/size recorded  in a a separate log) and free space for faster init.
Is there a way to initialize jemalloc to a certain state instead of a "totally free/clean" state? For the memory address range in my case, I already know that addressX/sizeX, addressY/sizeY and ... contain some data that shouldn't be overwritten unless freed explicitly. How should I tell jemalloc to mark those memory ranges as occupied and mark the rest of the memory space as free?
I think I can calculate the size_class/run size/run bitmap and page/chunk properties based on the raw inputs listed above. But I don't know the right way/API to inform jemalloc about those information.

And further more, I want do it right(maintainable/portable/general) and i want to do it fast because I may have a huge memory space to manage and millions of used/free memory ranges. Any hint on the right direction or where I should start will be appreciated. Thank you.

I'm using jemalloc 4.0, so it'll be very helpful if the solution can be applied to 4.0 version.
//copy some input from David & Qi from Gitter
David Goldblatt :
People have asked for variants of this in the past
And it's tricky to get done, because we need a great deal of flexibility and control over how metadata is represented
I think it's unlikely that this would be supported except in an extremely limited capacity (something like "you can dump a whole arena to disk, and then reload all contents at the same address with the exact same jemalloc version")
Qi Wang :
like David mentioned what you described would be quite tricky to support / maintain. However here's what's possible today -- you can create manual arenas and control the address space they use with extent_hooks; with that there is arena.reset API which can batch destroy everything within a specific arena / address range with the managed address space. Feel free to create an issue on github to ask / discuss more.

**Comment by interwq** [comment]
Sorry about the delay -- like mentioned before, I don't think what you described exists in jemalloc right now. We have discussed the possibility to support similar things like rebuilt heap based on a snapshot; but it would be quite tricky to get right.

That being said, I do agree that in the context of persistent memory, this might be a more valid request. @fadingsoul what approaches did you end up using?

**Comment by fadingsoul** [comment]
@interwq Thanks for the reply. I take the following steps to do the rebuild
0. hookup the trunk allocate function to allocate memory from persistent memory range.
1. Record each addr/size allocated during runtime in a log.
2. During rebuild, first calculate the allocate size/run_size of all the allocated runs by scanning  the log.
3. allocate each allocate region in each run including the non-used entries. Because jemalloc behavior is predictable if we allocate from lowest address towards high address.
4. free the non-used entries.
There are still some limitations in this approach. For example when allocation size is larger than several hundreds of KBs, the allocation becomes somewhat unpredictable. So far the approach only works for allocation region sizes no more than 200KB.

**Comment by interwq** [comment]
Glad you found a way to make it work. For a custom build, the approach you took sound reasonable to me. At the moment we don't have plans to support this upstream in the short term; however feel free to propose / share you use cases. Better support on persistent memory will certainly be on my mind.
