### ISSUE TITLE
About Total MB in jeprof result

### ISSUE THREAD

**Issue by prehistoric-penguin** [jemalloc/jemalloc#1376]
I am profiling the program sourcetrail with command:

```bash
MALLOC_CONF=prof:true,lg_prof_interval:27,lg_prof_sample:0 LD_PRELOAD=/usr/local/lib/libjemalloc.so sourcetrail
```

Then 24 profiles generated:
 jeprof.862.0.i0.heap ~ jeprof.862.23.i23.heap

After calling jeprof with command:

```bash
jeprof  --web /opt/sourcetrail/Sourcetrail --base jeprof.862.0.i0.heap jeprof.862.22.i22.heap
```

The result web shows that Total MB is 68.3, it's so small and I can't understand the size. The process now consumed about 27 GB virt. If run the process without jemalloc, we can see that about 800 MB virt is used.

So the question: 
what's the meaning of Total MB? Is there something wrong here?

Jemalloc version:5.1.0
os version: ubuntu 16.04 64 bit
gcc version: 4.8.5

**Comment by interwq** [comment]
You have the `--base` option with jeprof, which means only profile the incremental changes (so all the identical alive obj in both files won't show up).
