### ISSUE TITLE
take advantage of MREMAP_RETAIN if and when it lands upstream

### ISSUE THREAD

**Issue by thestinger** [jemalloc/jemalloc#138]
I'm filing this to follow progress on landing it upstream. I'll link new versions of the patch here.

Linux kernel patch v4 (has jemalloc benchmarks):

http://www.spinics.net/lists/kernel/msg1838477.html

jemalloc commit:

https://github.com/thestinger/jemalloc/tree/mremap

**Comment by poige** [comment]
Hi @thestinger !

How about this: https://github.com/jemalloc/jemalloc/blob/dev/src/chunk_mmap.c#L168 ? ;)

**Comment by thestinger** [comment]
Using the address hint to *attempt* filling in the leftover gap is what I'm doing in the allocator that I'm working on. It can easily fail because no lock is being held to prevent another `mmap` call from using the gap. The hint is also completely ignored with PaX ASLR.

You can see where I work around this here:

https://github.com/thestinger/allocator/blob/e80d2d0c2863c490b650ecffeb33beaccfcfdc46/huge.c#L167-L180

It also results in this code to preserve the range-based reservations that I rely on for parallel chunk/huge allocation on 64-bit:

https://github.com/thestinger/allocator/blob/e80d2d0c2863c490b650ecffeb33beaccfcfdc46/huge.c#L67-L75

It's not possible for jemalloc to do this without adding more complexity to the public chunk allocation API.

**Comment by thestinger** [comment]
The latest iteration of the patch is actively being discussed on linux-mm so hope for it landing in some form is still alive:

http://thread.gmane.org/gmane.linux.kernel.api/9287

**Comment by poige** [comment]
:+1:

**Comment by jasone** [comment]
Is ```MREMAP_RETAIN```/```MREMAP_NOHOLE``` dead?  A quick online search doesn't turn up any activity for well over a year.

**Comment by thestinger** [comment]
Yeah, there was interest in it but it never landed. I think this might as well be closed for now.

**Comment by jasone** [comment]
Shucks.
