### ISSUE TITLE
Single header file

### ISSUE THREAD

**Issue by optomux** [jemalloc/jemalloc#1381]
Provide single header file or modify script so we can generate it.

**Comment by davidtgoldblatt** [comment]
This is already done -- configure generates include/jemalloc/jemalloc.h, and in fact this is the only header installed by `make install`.

**Comment by optomux** [comment]
So I need only a single file to compile jemalloc?

**Comment by davidtgoldblatt** [comment]
I don't totally follow; you still have to link against it, but there's only one header file you need to include. (Or, if you mean you'd like something akin to a C++-style header-only libraries, this is probably not a direction we're interested in taking the library or supporting).
