### ISSUE TITLE
Getting Lock rank order reversal: extent_mutex_pool messages

### ISSUE THREAD

**Issue by dyadav7** [jemalloc/jemalloc#1384]
Hi

I am getting these messages with debug build:

<jemalloc>: Lock rank order reversal: extent_mutex_pool(16) extent_avail(15)
<jemalloc>: Should own 0 locks of rank >= 1: extent_mutex_pool(16)
<jemalloc>: Should own 0 locks of rank >= 1: extent_mutex_pool(16)
<jemalloc>: Should own 0 locks of rank >= 1: extent_mutex_pool(16)
<jemalloc>: Should own 0 locks of rank >= 1: extent_mutex_pool(16)
<jemalloc>: Should own 0 locks of rank >= 1: extent_mutex_pool(16)
<jemalloc>: Should own 0 locks of rank >= 1: extent_mutex_pool(16)

The application is using setrlimit() to be quite low memory . The application goes out of memory and is restarted again. After some re-starts this error started coming.

Regards
Deepak

**Comment by interwq** [comment]
Closing for now. Please let us know if you have more info.

**Comment by dyadav7** [comment]
With jemalloc debug build - i got the traces that i report initially in this issue. There was no hang with debug build.

Lock rank order reversal: extent_mutex_pool(16) extent_avail(15)
: Should own 0 locks of rank >= 1: extent_mutex_pool(16)
: Should own 0 locks of rank >= 1: extent_mutex_pool(16)

**Comment by dyadav7** [comment]
This is fixed with jemalloc 5.2.1 version.
