### ISSUE TITLE
Do something on tcache flush to wrong size class.

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1385]
The overwhelmingly most common sized deallocation error passes a size that's too small, rather than too large. This is safe (though a waste of memory) so long as the allocation never leaves the tcache. (If it does leave the tcache, we have the potential for essentially unbounded badness).

Down the only path where it leaves the tcache, though, we're already in a slow path, and have taken the metadata-lookup hit for it; checking that the true size is what we believe it to be is barely any overhead in comparison. If there's a mismatch, we can either print a warning and redirect to the appropriate bin (or leak), or just abort. (Or maybe decide between warning / abort via malloc conf).

**Comment by interwq** [comment]
A config option was added in #1427. It does add a small cost on the tcache flush path (in some tests close to 0.1% CPU of the process), so we disabled it by default. Plan to enable it in production workload for a while though.
