### ISSUE TITLE
jeprof prints addresses instead of method names

### ISSUE THREAD

**Issue by toktarev** [jemalloc/jemalloc#1391]
Dear JeMalloc team,

`jeprof --show_bytes --add_lib=/repos/myliba.a --pdf  jeprof* > w.pdf`

I see addresses in the result pdf instead of method names 

+ I see about 295 dump files instead of 1

**Comment by interwq** [comment]
jemalloc relies on stack unwinding support to properly unwind stack. Please check your config which unwinder you are using, e.g. prof-libunwind, prof-libgcc, or prof-gcc in config. I recommend going with libunwind which we have had great experience with.

**Comment by jiangxiaoqiang** [comment]
> Dear JeMalloc team,
> 
> `jeprof --show_bytes --add_lib=/repos/myliba.a --pdf jeprof* > w.pdf`
> 
> I see addresses in the result pdf instead of method names
> 
> * I see about 295 dump files instead of 1

did you found the solution for this issue?
