### ISSUE TITLE
Help ：Can i use jemalloc in C++ application？

### ISSUE THREAD

**Issue by strongmanwj** [jemalloc/jemalloc#1393]
Are there C++ new/delete  interface in jcmalloc? 
I need a high performance C++ lib for memory management.  Any  recommend?
thanks.

**Comment by voltento** [comment]
The `new` and `delete` use standard c method for memory management under the hood. So, yes. You can. Pls, check the page https://github.com/jemalloc/jemalloc/wiki/Getting-Started . I'd recommend use first way, it's the easiest

**Comment by duchuanINO** [comment]
@voltento how to do on windows
