### ISSUE TITLE
How to use jemalloc as static library?

### ISSUE THREAD

**Issue by voltento** [jemalloc/jemalloc#1395]
When I link jemalloc as dyn library, all work fine. But, when I linked it as static library, it doesn't work. 
I was hoping, somebody could tell me, what I'm doing wrong.

My actions:
I've build jemalloc as it shown in INSTALL file
```
./configure
make
make install
```
after that I've got the next libraries
```
-rwxr-xr-x    1 vladimir.dumanovskiy  admin    458744 Dec 14 17:43 libjemalloc.2.dylib
-rwxr-xr-x    1 vladimir.dumanovskiy  admin   2706472 Dec 14 17:43 libjemalloc.a
lrwxr-xr-x    1 vladimir.dumanovskiy  admin        19 Dec 14 17:43 libjemalloc.dylib -> libjemalloc.2.dylib
-rwxr-xr-x    1 vladimir.dumanovskiy  admin   2706672 Dec 14 17:43 libjemalloc_pic.a 
```

Then, I linked the libjemalloc.a library into my cmake project and set the `MALLOC_CONF=metadata_thp:always,dirty_decay_ms:30000,muzzy_decay_ms:30000,percpu_arena:percpu `
And after that, It looks like my program uses standard malloc again :(

**Comment by interwq** [comment]
Hello, please see the instructions for `Link jemalloc into the application at build time` here https://github.com/jemalloc/jemalloc/wiki/Getting-Started

Please share the build command for you application if it's not working for you.

**Comment by sealpp** [comment]
Hi, sorry to bother you. I am facing the same issue when trying to use jemalloc as a static library. Could you please share if there was any solution found for this issue?
