### ISSUE TITLE
Option to periodically dump malloc_stats

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#1397]
malloc_stats is useful in many cases, e.g. help understanding fragmentation or purging. Although we have the "stats_print" option to dump at exit, in reality we have many applications simply don't exit.

We'd like to have an option similar to `lg_prof_interval` to give us easy access to malloc_stats.

**Comment by davidtgoldblatt** [comment]
It sort of seems like this belongs at a higher level of the stack; e.g. the user program sets something up to call malloc_stats_print once a minute or so. No?

**Comment by interwq** [comment]
Yeah it's possible for the user to do so. However in some cases it's not very convenient (e.g. python programs) and sometimes the `stats_print` option won't work as the binary never exits.

**Comment by frederik-h** [comment]
@interwq Sounds like a good idea. We have implemented this on our own and it is certainly very useful.  Would this feature require pthreads or, in other words, would it also work on Windows without further ado?

**Comment by interwq** [comment]
@frederik-h yes it should work fine for Windows as well. @yinan1048576 has been working on this feature and it should happen in a few weeks.
