### ISSUE TITLE
use stl map core dump happened

### ISSUE THREAD

**Issue by blood9009** [jemalloc/jemalloc#1403]
#0  atomic_load_p (mo=atomic_memory_order_relaxed, a=0x1b9060) at include/jemalloc/internal/atomic.h:55
#1  rtree_leaf_elm_bits_read (dependent=true, elm=0x1b9060, rtree=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/rtree.h:175
#2  rtree_szind_slab_read (r_slab=<synthetic pointer>, r_szind=<synthetic pointer>, dependent=true, key=140727675833712, rtree_ctx=<optimized out>, rtree=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/rtree.h:464
#3  ifree (slow_path=false, tcache=<optimized out>, ptr=0x7ffdb720cd70, tsd=0x7f9633664840) at src/jemalloc.c:2206
#4  free (ptr=0x7ffdb720cd70) at src/jemalloc.c:2393
#5  0x000000000046d883 in state_sub (ses=0x7f962b071600, mk=0x7f962b11cdd0) at state.cpp:318
#6  0x000000000045bc7e in onmethodstate_sub (ses=0x7f962b071600, id=22, info=0x7f962b0a84a0, params=0x7f962b02b750) at server.cpp:503
#7  0x000000000045e6c3 in on_message (ses=0x7f962b071600, remote=0x7f962b0a8468 , url=0x7f962b11ce18 "/", message=0x7f962b097008, size=4066) at server.cpp:971
#8  0x000000000048250b in on_recv_pkg (ses=0x7f962b071600, data=0x7f962b1629d8, size=4074) at wssvr.c:461
#9  0x000000000049a0a7 in on_can_read (ses=0x7f962b071600) at wsses.c:138
#10 0x000000000049aad8 in libev_on_read_write_evt (loop=0x7f962b068000, watcher=0x7f962b071600, events=1) at wsses.c:338
#11 0x00007f9632e3b435 in ev_invoke_pending (loop=0x7f962b068000) at ev.c:3288
#12 0x00007f9632e3e615 in ev_run (loop=0x7f962b068000, flags=<optimized out>) at ev.c:3688
#13 0x000000000049c9dc in nw_loop_run () at wsevt.c:49
#14 0x0000000000475e44 in main (argc=2, argv=0x7ffdb720d4f8) at main.cpp:237

the code like this:
struct test_val
{
    std::vector<void *> sessions; 
    char *last;
};
      static std::map<std::string, test_val> *maptest = nullptr;
      if(!maptest)
       maptest = new std::map<std::string, test_val>;
        test_val val;
        val.sessions.push_back(ses);
        val.last = nullptr;
        maptest->insert(std::make_pair(std::string(market), val));

this is why core dump when i use jemalloc ?

**Comment by interwq** [comment]
This is a typical memory corruption by the application. Please use sanitizer tools like ASAN, or the jemalloc debug build to further investigate.
