### ISSUE TITLE
Jemalloc5.1 large memory can not be recycled? New char[1024* 1024 * 1024]

### ISSUE THREAD

**Issue by jay602** [jemalloc/jemalloc#1415]
My test steps： 
main.cpp
```
#include <stdlib.h>
#include <stdio.h>
#include <jemalloc/jemalloc.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    getchar();

    printf("new\n");
    
    char *data = new char[1024* 1024 * 1024];
    if(data == NULL)
    {
        printf("new failed\n");
    }

    getchar();
    printf("free\n");

    if(data)
    {
        delete[] data;
        printf("free ok\n");
    }
        
    getchar();

  while(true){
       char *data = new char[1024];
       if(data) delete[] data;
       sleep(1);
    }
    return 0;   
}
```

```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10):
kk@ubuntu:~/kk/test$ g++  main.cpp -o test2 -I`jemalloc-config --includedir` -L`jemalloc-config --libdir` -Wl,-rpath,`jemalloc-config --libdir` -ljemalloc `jemalloc-config --libs`
```

Thre  program has ran for one night.
Program execution result:
    1. When the initial states of the program is 
        ![1](https://user-images.githubusercontent.com/5274872/51652318-1d7b8580-1fca-11e9-8710-9a25039d4987.png)

    2.when program printf "new"
 
![2](https://user-images.githubusercontent.com/5274872/51652387-67fd0200-1fca-11e9-969a-3fa28f93e95a.png)

    3.when program printf "free ok"
![3](https://user-images.githubusercontent.com/5274872/51652399-6e8b7980-1fca-11e9-9b86-fa40ea6dede4.png)

**Comment by interwq** [comment]
By default jemalloc uses [time-based decay](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms) to purge dirty memory, which means memory freed won't be returned to kernel immediately (instead it will happen gradually overtime). This is based on the observation that memory reuse is frequent and the high overhead from unmapping operations.

We are making an exception for this though -- the current dev branch will eagerly purge large buffers.

**Comment by jay602** [comment]
https://github.com/kbengine/kbengine/issues/1005
Even with the latest jamalloc,the temporary large memory allocated when loading the navmesh file on the Linux platform is not released,


The size of the navmesh file is 767 MB.
At the beginning, the memory of the cellapp is more than 20 MB.
![QQ截图20190415103448](https://user-images.githubusercontent.com/5274872/56105088-36625a00-5f6d-11e9-8b23-fedad09c5a22.png)

After loading the navmesh file, the memory of the cellapp is more than 900 MB.
![QQ截图20190415103541](https://user-images.githubusercontent.com/5274872/56105170-7e817c80-5f6d-11e9-97c3-ec032da24004.png)

**Comment by AndroidInternal** [comment]
Maybe the reason  is that dirty pages purging relies on 1000 times allocation/deallocation tick-tock events.

有一个原因是jemalloc的purge是tick-tock的，默认应该是1000次申请和释放内存的事件，才会触发purge，进而释放内存
