### ISSUE TITLE
jeprof maps bunch of function addresses to a bogus name

### ISSUE THREAD

**Issue by malahal** [jemalloc/jemalloc#1418]
Using 5.1.0 version built from git sources on centsos7.4, x86_64 arch. With --debug option, I see that the actual binary (gpfs.ganesha.nfsd) addresses are small compared to other libraries. Here is the first few lines of --debug stderr out followed by the actual output. Note that clientip is a data symbol in the program! Appreciate any help. Also, is there a way I can tell function address (PC) and symbol name map externally?

# /usr/local/bin/jeprof --debug /usr/bin/gpfs.ganesha.nfsd --address --text /tmp/jeprof.out.18946.7.i7.heap > /tmp/xx
Using local file /usr/bin/gpfs.ganesha.nfsd.
Using 'nm' for 'nm'.
Using 'c++filt' for 'c++filt'.
Using 'addr2line' for 'addr2line'.
Using 'objdump' for 'objdump'.
Using local file /tmp/jeprof.out.18946.7.i7.heap.
0000000000400000:00000000005d5000 (0000000000000000) /usr/bin/gpfs.ganesha.nfsd
00007f46d3bf7000:00007f46d3bff000 (0000000000000000) /usr/lib64/libnss_sss.so.2
00007f46ddbc3000:00007f46ddbe1000 (0000000000000000) /usr/lib64/libgssrpc.so.4.2
00007f46ddde3000:00007f46dddfe000 (0000000000000000) /usr/lib64/gssproxy/proxymech.so

# cat /tmp/xx | head
Total: 61.0 MB
    56.5  92.6%  92.6%     56.5  92.6% 00000000004ea034 clientip ??:0
     2.3   3.7%  96.3%      2.3   3.7% 00007f46e5626d70 svc_dg_ncreatef /usr/src/debug/nfs-ganesha-2.5.3-ibm030.02-0.1.1-Source/libntirpc/src/svc_dg.c:201
     1.1   1.9%  98.1%      1.1   1.9% 000000000045adab clientip ??:0
     1.1   1.9% 100.0%      1.1   1.9% 000000000053798a clientip ??:0
     0.0   0.0% 100.0%     61.0 100.0% 000000000041c818 clientip ??:0
     0.0   0.0% 100.0%      1.1   1.9% 000000000041d4d9 clientip ??:0
     0.0   0.0% 100.0%      1.1   1.9% 000000000041d629 clientip ??:0
     0.0   0.0% 100.0%     58.8  96.3% 000000000041d7e1 clientip ??:0
     0.0   0.0% 100.0%      2.3   3.7% 000000000044dafa clientip ??:0

**Comment by interwq** [comment]
Looks to be issues with the unwinder. I suggest trying build jemalloc with libunwind https://github.com/libunwind/libunwind which we have had great experience with.

**Comment by malahal** [comment]
Thank you interwq, but passing the debuginfo rpm's gpfs.ganesha.nfsd.debug as executable helped to decode those symbols. Not sure why, so you can close the issue but if there is a clear explanation why addr2line worked with the same stripped binary but jeprof didn't work would be great!
