### ISSUE TITLE
ppc64le heap profile shows leak in je_prof_backtrace(). 

### ISSUE THREAD

**Issue by malahal** [jemalloc/jemalloc#1419]
I have used the following options but the jeprof reported 100% use/leak by the je_prof_backtrace() itself and didn't list anything else. Version used 5.1.0-0-g61efbda7098de6fe64c362d309824864308c36d4

Options: MALLOC_CONF=prof:true,prof_prefix:/tmp/jeprof.out,lg_prof_interval:30,lg_prof_sample:20 LD_PRELOAD=/usr/local/lib/libjemalloc.so <binary> <args>

# jeprof /usr/lib/debug/usr/bin/gpfs.ganesha.nfsd.debug --address --text   /tmp/jeprof.out.4898.* 2>/dev/null
Total: 4577622.3 MB
4577622.3 100.0% 100.0% 4577622.3 100.0% 00003fff938f1d28 je_prof_backtrace /root/jemalloc/src/prof.c:367 (discriminator 2)

That shows **Total 4577 GB**, but the pmaps indicates that the program is using around 29GB 

# pmap $(pidof gpfs.ganesha.nfsd) | tail
00003fff93890000    640K r-x-- libjemalloc.so
00003fff93930000     64K r---- libjemalloc.so
00003fff93940000     64K rw--- libjemalloc.so
00003fff93950000    640K rw---   [ anon ]
00003fff939f0000    128K r-x--   [ anon ]
00003fff93a10000    192K r-x-- ld-2.17.so
00003fff93a40000     64K r---- ld-2.17.so
00003fff93a50000     64K rw--- ld-2.17.so
00003fffff130000    192K rw---   [ stack ]
 **total         29406336K**

**Comment by interwq** [comment]
This sounds to be an issue from the stack unwinder (which jemalloc relies on to grab stack traces). I suggest trying libunwind https://github.com/libunwind/libunwind with jemalloc
