### ISSUE TITLE
madivse MADV_DONTNEED causes bad performence in KVM virtual machine

### ISSUE THREAD

**Issue by pacepi** [jemalloc/jemalloc#1422]
madvise MADV_DONTNEED needs to send IPI broadcast to other CPUs to flush TLB or invalid the specific PTE (Ex, native_flush_tlb_single function).
and in KVM virtual machine, IPI costs more CPU cycles.
will jemalloc support a  config flag to disable this syscall in the future ?

**Comment by interwq** [comment]
You can disable decay by adding `dirty_decay_ms:0,muzzy_decay_ms:0` as the runtime option, [manual](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms), e.g. through the MALLOC_CONF env var. However freed memory won't be returned to OS in that case.

**Comment by xurui-xr** [comment]
I have disable decay by adding dirty_decay_ms:-1,muzzy_decay_ms:-1, but why are there still a lagre number of madvise system calls
