### ISSUE TITLE
memory suddenly increase 1GB

### ISSUE THREAD

**Issue by haolujun** [jemalloc/jemalloc#1424]
HI : 
    When I use jemalloc in my server program,   at the begining,  some request come in and the memory use increase slowly, and then I stop the request, the memory usage decrese and then no change,  but after several hours (no request come in during this period)  the memory sudenly increase 1G, why?

**Comment by interwq** [comment]
The issue sounds to be from the application itself or other parts / libraries. jemalloc won't cause this behavior. The profiling feature https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling can help to understand memory usage.
