### ISSUE TITLE
5.2 release

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#1429]
This issue is for tracking communication/progress related to the 5.2 release.

Current release candidate: 8e9a613

We have a few notable changes that warrant this release -- 
- the `max_background_threads` fix
- a series of fast path optimizations
- the `oversize_threshold` feature
- allow `void *p = ::operator new(0);  ::operator delete(p, 0);`

**Comment by interwq** [comment]
The current release [candidate](https://github.com/jemalloc/jemalloc/commit/8e9a613122251d4c519059f8e1e11f27f6572b4c) has been up in production for a while. We will give it a few more weeks before cutting the release. I'll prepare a draft of the changelog next week.

@jasone: could you help with testing the RC on FreeBSD-current? As far as I can think of, the only visible "behavior" change is that we will use a dedicated arena for >=8M allocations (the `oversize_threshold` feature which is to avoid mixing "huge" and smaller allocations).

**Comment by jasone** [comment]
I'll work on FreeBSD integration/testing during the next week.

**Comment by ingvarha** [comment]
8e9a613 does not run full test suite on s390x with gcc-9.0.1, see #1434.

Ingvar

**Comment by ldcsaa** [comment]
Would you tell us when will 5.2.0 be released ?

**Comment by antirez** [comment]
Are there critical issues (that can lead to instability of programs using Jemalloc) that 5.2 will fix and are present in 5.1.0? Thanks.

**Comment by davidtgoldblatt** [comment]
> Would you tell us when will 5.2.0 be released?

Probably order weeks, unless some undiscovered bug appears.

> Are there critical issues (that can lead to instability of programs using Jemalloc) that 5.2 will fix and are present in 5.1.0?

5.2 has better behavior w.r.t. fragmentation of virtual memory; in some pathological cases 5.1 can have a very high ratio of virtual address space consumed to pages actually in memory.

**Comment by interwq** [comment]
In addition to what David mentioned, 5.2 will have a few bug fixes for the  ‘background_thread’ feature (which is not enabled by default)

**Comment by jasone** [comment]
I think I may have run into a serious portability problem for the mips platform on FreeBSD.  Shortly after the 5.1.0 release, 982c10de3566f38628770e57c62d1a6cdc5a09f9 added 8-bit atomics, i.e. in `include/jemalloc/internal/atomic.h`:

```c
JEMALLOC_GENERATE_INT_ATOMICS(uint8_t, u8, 0)
```

It appears that gcc 4.2 lacks support for this; here is a linker error from an attempted buildworld when trying to link a binary with libc:

```
/usr/obj/usr/src/mips.mips/tmp/lib/libc.so.7: undefined reference to `__sync_bool_compare_and_swap_1'
```

Are atomic operations on 8-bit values deeply ingrained now?  My brief looks suggests the answer is yes.  If so, this may be the end of the road for FreeBSD updates until all its platforms switch to clang.  Incidentally, I've had the current dev version of jemalloc integrated with FreeBSD on my amd64 development system for several days, and have encountered no problems.

**Comment by interwq** [comment]
Looks to me that the 8bit atomic cannot be easily avoided. Maybe bump it to 16bit when the 8bit support is missing? @davidtgoldblatt

**Comment by davidtgoldblatt** [comment]
Yeah; I think bumping it for mips is reasonable. This will cost some amount of nice cache behavior, but my expectation is that those use cases are not highly performance sensitive.

**Comment by interwq** [comment]
I’ll put up a patch soon.

**Comment by jasone** [comment]
Out of curiosity, I just looked up how old the FreeBSD/mips gcc (4.2.1) is.  It was released on July 18, 2007!  Hobbling jemalloc development with such ancient compiler technology is increasingly frustrating, especially for you who actually like C++. :wink:

**Comment by jasone** [comment]
Once #1449 is committed, we should be good to go with regard to FreeBSD libc integration.

**Comment by interwq** [comment]
Thanks a lot Jason! I’ll have a draft changlog in a few days.

**Comment by ingvarha** [comment]
FYI, after #1434 was fixed in gcc9, both 8e9a613 and b804d0f (dev today) builds fine on all fedora rawhide and epel7 targets, that is armv7hl, i686, ppc64, ppc64le, s390x, x86_64, aarch64.

Ingvar

**Comment by ldcsaa** [comment]
@davidtgoldblatt 
I'm waiting for 5.2.0 for a long time, please tell me when will 5.2.0 be released?

**Comment by davidtgoldblatt** [comment]
Probably in the next couple of weeks; the improvement in fb56766ca9b398d07e2def5ead75a021fc08da03 was big enough that it was worth delaying the release for.

**Comment by interwq** [comment]
Update: the current final release RC is fb56766, which has been deployed widely in production for ~a week. Like David mentioned, one of the change was not trivial and deserved some extra validation. We plan to give it one more week to settle, before making the official release.

**Comment by interwq** [comment]
Two remaining PR #1469 and #1471 (both trivial), plus the changelog coming soon.

**Comment by davidtgoldblatt** [comment]
Note that https://github.com/jemalloc/jemalloc/pull/1460#issuecomment-477709960 points out a correctness bug; we should get in a fix for that as well.

**Comment by interwq** [comment]
ChangeLog PR #1473.

**Comment by interwq** [comment]
The release is out: https://github.com/jemalloc/jemalloc/releases/tag/5.2.0
