### ISSUE TITLE
Should the '#include <strings.h>' statement be removed from generated jemalloc.h ?

### ISSUE THREAD

**Issue by ldcsaa** [jemalloc/jemalloc#1435]
I use MSVC to complie jemalloc according to the guidelines of Readme.txt, and then the  generated jemalloc.h file includes <strings.h>, but Windows platform does not has this header file, thus the program which uses jemalloc.h report compile error.
Would you remove this include statement from jemalloc.h please ?

**Comment by interwq** [comment]
Unfortunately we'd need more information to figure out what went wrong, e.g. the configure script output along with platform information. We have MSVC builds in CI working, e.g. https://ci.appveyor.com/project/jasone/jemalloc/builds/23633476/job/fmlqhybcycbnvleq?fullLog=true
You can also compare against the setup there.

Closing for now but please share if any new findings.
