### ISSUE TITLE
Does jemalloc 5.1.0 support VC2010 ?

### ISSUE THREAD

**Issue by ldcsaa** [jemalloc/jemalloc#1436]
I want to compile jemalloc-5.1.0 with VC2010, but it report error while running autoconf, doesn't jemalloc not support VC2010 ?
error message: **_configure: error: cannot determine number of significant virtual address bits_**
![image](https://user-images.githubusercontent.com/5990337/52855961-fdb92680-315d-11e9-8adb-212ccd102301.png)

**Comment by interwq** [comment]
It's likely some environment issue, the logic to detect number of virtual address bits is here: https://github.com/jemalloc/jemalloc/blob/dev/configure.ac#L417

Or alternatively, if you know the value on the platform, you can config with `--with-lg-vaddr`
