### ISSUE TITLE
libgcc profiling initialization & fakechroot

### ISSUE THREAD

**Issue by paravoid** [jemalloc/jemalloc#1438]
OK, this is not really a jemalloc bug, but I'm wondering if you have any insight or workarounds to provide for this.

In Debian, I enabled (libgcc) `--enable-prof` for amd64/i386 builds. One of the bugs I encountered while enabling this was a deadlock in the [fakechroot](http://packages.debian.org/sid/fakechroot) package. fakechoot is a piece of software which does a bunch of nasty LD_PRELOAD hacks to give a chroot environment to unprivileged users in which they can do root-like operations like bootstrap Debian.

I tracked down the issue and it seems to be sourced in the fact that with profiling build-enabled (`--enable-prof`), jemalloc calls `_Unwind_Backtrace` to initialize the unwind code. This happens unconditionally, even if profiling is not runtime-enabled.

This in turn seems to call `dl_iterate_phdr`, which is one of the libc calls that fakechroot captures; fakechroot then calls `dlsym`/`dlerror`, which allocates memory, which then ends up in jemalloc territory again, and (naturally) locks up. I have a full backtrace over at the Debian BTS, at [#918742](https://bugs.debian.org/918742).

Obviously when one intercepts and replaces libc functions like `dl_iterate_phdr`... all bets are off. Still, I was wondering if there was any way that e.g. `_Unwind_Backtrace` could be initialized more lazily, to minimize the initialization code path avoid such a thing? Or any other advice you may have :)

(Note that this isn't triggered when using libunwind due to a different initialization path. @jasone had previously recommended using unwind in #338, but I wanted to avoid the additional dependency for now. This is something I can and may have to revisit, though.)

**Comment by interwq** [comment]
Will simply guarding the `_Unwind_Backtrace` init call with opt.prof work for you? https://github.com/jemalloc/jemalloc/pull/1441

**Comment by paravoid** [comment]
It would, but I assumed there was a reason this wasn't the case as it felt quite deliberate. Would be happy if my assumption proved to be wrong!

**Comment by interwq** [comment]
Thanks for reporting this @paravoid!
