### ISSUE TITLE
How to enable jemalloc at runtime?

### ISSUE THREAD

**Issue by ObiWahn** [jemalloc/jemalloc#1450]
We are looking for a way to enable jemalloc at runtime. As our project is statically linked against musl-libc the `LD_PRELOAD` approach is not valid for us. One possible solution could be to prefix the jemalloc functions (using `--with-jemalloc-prefix`) and use ld's `--wrap=symbol` to select between `jemalloc_prefix_symbol` and `__real_symbol`. Are there other more reasonable solutions? Could it become a configurable build-option for jemalloc to allow for falling back to the system's allocation functions?

**Comment by interwq** [comment]
As I understand a while ago, the musl-libc does not support malloc replacement. Unless the feature has been added, I don't think it will be easily compatible.
