### ISSUE TITLE
Segfault due to jemalloc --- MWE

### ISSUE THREAD

**Issue by rob-p** [jemalloc/jemalloc#1453]
Hi,

  My group develops [an application](https://github.com/COMBINE-lab/salmon) that makes use of jemalloc.  Recently, we ran into an issue where a specific build (made via bioconda) would segfault on a specific platform.  In order to test if the issue was elsewhere in our application, I attempted to reproduce a minimum working example.  I was able to do so with a relatively simple test. 
 The repository with the mwe is [here](https://github.com/rob-p/jemalloc_segfault_test).  The problem pops up under valgrind and the executable can be run in the appropriate way using the `run.sh` script in that repo.  This behavior is observed on linux (ubuntu 16.10).  It's worth noting that if jemalloc is not linked in while compiling, the program runs under valigrind with no issues.  Any idea what might be going on here?

Thanks,
Rob

cc @k3yavi

**Comment by interwq** [comment]
Hello, which jemalloc version did you use? Since jemalloc 5.0, valgrind is not supported anymore (#369).
