### ISSUE TITLE
The wiki leads one to believe valgrind is supported, while it isn't

### ISSUE THREAD

**Issue by epruesse** [jemalloc/jemalloc#1456]
According to [this](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Find-a-memory-corruption-bug) page in the wiki here, users of jemalloc should really use valgrind. However, using valgrind with jemalloc >=5 leads to errors caused by jemalloc and not the client application.

Could you warn users on that page that they need to downgrade to 4.5 or not use valgrind & friends?

**Comment by interwq** [comment]
Thanks for noticing. Just updated the wiki.

**Comment by epruesse** [comment]
Thanks

**Comment by epruesse** [comment]
(I might use `**Note:** *something*` to get **Note:** *you should be aware that* - can't edit though)
