### ISSUE TITLE
Fragmentation Estimate

### ISSUE THREAD

**Issue by bogta** [jemalloc/jemalloc#1457]
Hi!

The statistics that I get looks something like this:
Allocated: 501579296, active: 556576768, metadata: 10432064 (n_thp 0), resident: 565587968, mapped: 590159872, retained: 0

I am wondering if it is correct to estimate the fragmentation induced by the application by "resident / allocated * 100%" or should I use mapped instead?

Thanks,

**Comment by interwq** [comment]
Allocated / Active will be the fragmentation estimation. mapped also includes other caches, such as the dirty extents.
