### ISSUE TITLE
Is there any API to make jemalloc dump prof file manually?

### ISSUE THREAD

**Issue by prehistoric-penguin** [jemalloc/jemalloc#1462]
Is there any API to make jemalloc dump prof file manually? I'd like to analysis the memory usage of my process at a specific time point, so I think this kind of API maybe helpful.

Thanks!

**Comment by interwq** [comment]
Yes it's `mallctl("prof.dump", ...` check the details in https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling
