### ISSUE TITLE
Doubt about the total memory in profile

### ISSUE THREAD

**Issue by prehistoric-penguin** [jemalloc/jemalloc#1466]
Thanks for such great project, I am profiling a large project.

The configuration argument for build jamelloc: `./configure --enable-debug --enable-prof --enable-stats --enable-prof-libunwind`

Then I use LD_PRELOAD environment to inject jemalloc before process start.
The variable to start my process: `MALLOC_CONF=prof:true,lg_prof_sample:0 ./myserver`
The head part of the profile dump file, the dump is generated by calling `mallctl` manually:

> heap_v2/1
  t*: 2013483: 1274940608 [0: 0]
  t0: 1196145: 116409144 [0: 0]
  t1: 155836: 114995520 [0: 0]
  t2: 6: 21808 [0: 0]
  t3: 3: 1200 [0: 0]
  t5: 25: 84928 [0: 0]
  t6: 2: 96 [0: 0]
  t7: 3: 1200 [0: 0]
  t8: 1: 768 [0: 0]

The stats of the process, which is get just after dump file generated:

> 

> Arenas: 256
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Number of bin size classes: 36
Number of thread-cache bin size classes: 41
Number of large size classes: 196
Allocated: 34570179848, active: 42832146432, metadata: 1120699400 (n_thp 0), resident: 44946198528, mapped: 45516144640, retained: 10829611008
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
background_thread                 517               0               0             257               0               0           0
ctl                                 5               0               0               3               0               0           0
prof                         34098051          168803        13823343        21050231    298874639534      4870977832          37
Merged arenas stats:
assigned threads: 696
uptime: 350902403044
dss allocation precedence: "N/A"
decaying:  time       npages       sweeps     madvises       purged
   dirty:   N/A       266667         1778        11473      3003409
   muzzy:   N/A       143358          996         5836      1814370
                            allocated     nmalloc     ndalloc   nrequests
small:                      592499976    23865488    21254624    23865488
large:                    33977679872     3609991     1593404     3609991
total:                    34570179848    27475479    22848028    27475479
active:                   42832146432
mapped:                   45516144640
retained:                 10829611008
base:                       434040576

And during the process's life time, I have double checked that the process used about 50 GB virt.

With the env `lg_prof_sample:0`, I think all memory allocation is tracked, am I right here?

I am confused that why the dump file only catch about 1.2 GB memory cost (1274940608 ), it's far from the true memory cost printed from stats  42 GB (42832146432) or top command.

**Comment by interwq** [comment]
Profiling is sample based, and the profile shows sampled allocations. See http://jemalloc.net/jemalloc.3.html#opt.lg_prof_sample

You can adjust the setting to increase the number of samples, but possibly with increased CPU cost.

**Comment by prehistoric-penguin** [comment]
@interwq Thanks, What if lg_prof_sample=0, is every allocation tracked?

**Comment by interwq** [comment]
Yes however it will introduce significant CPU and memory overhead.

**Comment by prehistoric-penguin** [comment]
Thank you so much, I have seen that it's so slow to run server with this configuration, but it maybe useful to do some memory analysis offline.
