### ISSUE TITLE
Java Jemalloc / jeprof pdf report doesn't show function names in linux 

### ISSUE THREAD

**Issue by meiry** [jemalloc/jemalloc#1475]
i executed successfully the jemalloc on web app in tomcat in AWS default ec2 linux using jdk1.8.0_181 (downloaded from oracle ) 
but then when i try to output PDF report the function names are in some hex format and not
with some human readable format .
how to get the human readable format ?
this is the command i run to out put the report :
```
sudo perl ./jeprof  --show_byte --pdf /usr/java/jdk1.8.0_181/bin/java $HOME/log/*.heap > test1.pdf
```

![TcNk7](https://user-images.githubusercontent.com/1107316/55353335-b7c8df80-54cb-11e9-8981-b6197512008d.png)

can't find any answer , what do i miss here ?
Thanks

**Comment by interwq** [comment]
jemalloc / jeprof relies on the stack unwinder to interpret raw function address to names. Please check the unwinder built with jemalloc (we recommend libunwind).

**Comment by meiry** [comment]
can you please point me to more info about the subject , there is so little information .
how do i check what is the default unwinder lib ,using ldd or other method ?
And how to compile the right lib if it doesn't exist in the system  .
Thanks

**Comment by meiry** [comment]
@interwq 
i tried to compile with static libunwind 
```
./configure --enable-prof --enable-stats --enable-debug --enable-fill --with-static-libunwind=/home/jemalloc/libunwind/src/.libs/libunwind-x86_64.a
--
```

then i invoked the java web app with thos parameters :
```
export  LD_PRELOAD=/home/jemalloc_wind/lib/libjemalloc.so                                                                                                                                                                                                              export  MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:17,prof_final:true,prof_prefix:/home//log/jeprof1.out
--
```

and then the jeprof 
```
sudo perl ./jeprof  --show_byte --pdf /usr/java/jdk1.8.0_181/bin/java ../../log/*.heap > test1.pdf
--
```

and still the output not having function names only hex values 
what im missing here ?

**Comment by interwq** [comment]
Maybe try a dbg build of jdk. Also note that Java functions won’t be visible to libunwind or glibc unwind, only the ones inside JVM.

**Comment by meiry** [comment]
i don't need the java function i need the libc/ system calls the JVM is invoking 
i don't find any dbg version in oracle site

**Comment by meiry** [comment]
perf-map-agent is for Linux  perf tool 
which working great by the way , without using jemalloc .
what is the connection between jemalloc and perf-map-agent or any ? 
maybe i need to compile addr2line ?

**Comment by smuryginim** [comment]
Was there some resolution found? I face the same problem

**Comment by meiry** [comment]
No , please update if you found something

**Comment by sattishv** [comment]
Even i am facing the same issue, the jeprof report shows only memory address . We are running the whole exercise inside a container any insights would be appreciated

**Comment by jiangxiaoqiang** [comment]
> can you please point me to more info about the subject , there is so little information . how do i check what is the default unwinder lib ,using ldd or other method ? And how to compile the right lib if it doesn't exist in the system . Thanks

did you fixed this problem?
