### ISSUE TITLE
can't run any rails command with Jemalloc on OS X (10.14.4)

### ISSUE THREAD

**Issue by rpbaltazar** [jemalloc/jemalloc#1481]
# Steps to reproduce:

1. Install Jemalloc via homebrew: `brew install jemalloc`
1. Re-install ruby with rbenv passing the option for jemalloc: `RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 2.5.5`
1. Add jemalloc to the gem file: `gem "jemalloc"`
1. Re-hash rbenv: `rbenv rehash`
1. run bundler: `bundle install`
1. Start rails server: `rails server`

## Expected

Puma to start

## What is happening

malloc error and process hanging forever (or until i kill it).

this is the output:

```
~/code/project$ rails s
ruby(38168,0x10cdb85c0) malloc: *** malloc_zone_unregister() failed for 0x7fffa9946000
```
I tried to debug but can't figure out a way of seeing any more useful output that could lead me somewhere.

It also throws my CPU usage to the roof
<img width="1001" alt="Screenshot 2019-04-13 at 11 34 39 AM" src="https://user-images.githubusercontent.com/5548466/56074173-557fb100-5de0-11e9-945e-8ef8dd0204cc.png">

## Attempts to fix it:

List all the dependencies that have C extensions and update them (the ones possible) one by one, testing if any would solve the issue.

```
bcrypt-3.1.12
bootsnap-1.4.3
byebug-10.0.2
concurrent-ruby-1.1.5
ffi-1.10.0
jaro_winkler-1.5.2
jemalloc-1.0.1
levenshtein-ffi-1.1.0
libv8-6.7.288.46.1-x86_64-darwin-18
mini_racer-0.2.4
msgpack-1.2.9
nio4r-2.3.1
nokogiri-1.10.2
oj-2.18.5
pg-0.21.0
puma-3.12.1
rb-fsevent-0.10.3
redcarpet-3.4.0
ruby-prof-0.17.0
scout_apm-2.4.24
thread_safe-0.3.6
tunemygc-1.0.71
unf_ext-0.0.7.5
websocket-driver-0.7.0
```

Any hints?

**Comment by gaffneyc** [comment]
Remove the [jemalloc gem](https://rubygems.org/gems/jemalloc) and you should be fine. The gem hasn't been updated since 2015 and bundles a _really_ old version of jemalloc thats competes with the one installed via homebrew.

Someone ran into the same issue on [the jemalloc buildpack I maintain](https://github.com/gaffneyc/heroku-buildpack-jemalloc/issues/10) and removing the gem solved it for them.

**Comment by rpbaltazar** [comment]
Thanks for the help. Tested and it solves the issue!
