### ISSUE TITLE
Wrong version written to the VERSION file

### ISSUE THREAD

**Issue by KingDuckZ** [jemalloc/jemalloc#1484]
When I run configure with my settings for an out of source build I always end up with a VERSION file in my objroot that contains the bogus version 0.0.0.

I managed to get it working by removing the exclamation mark [here](https://github.com/jemalloc/jemalloc/blob/dev/configure.ac#L563) and the one a few lines down as well (on the git describe line). Is that the right fix? could you patch master branch please?

**Comment by interwq** [comment]
Try “git fetch --tags”. Closing but feel free to ask anything.

**Comment by interwq** [comment]
Oh I might misunderstood. So the in source build is fine?

**Comment by KingDuckZ** [comment]
No idea, I haven't tried it. I can try it tomorrow if it's useful, but really just removing the "!" fixes it.
I can also supply the full configure command I'm running if you want to try reproducing the problem.

Running git fetch --tags at every build seems a bit wasteful to me and I don't think it's going to make any difference. That's simply going to refresh the tags, but I'm already up-to-date.
