### ISSUE TITLE
Jemalloc5.2 large memory can not be recycled? New char[200* 1024 * 1024]

### ISSUE THREAD

**Issue by jay602** [jemalloc/jemalloc#1485]
My test steps：
main.cpp
```
#include <stdlib.h>
#include <stdio.h>
#include <jemalloc/jemalloc.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    getchar();

    printf("new\n");
    
    char *data = new char[200* 1024 * 1024];
    if(data == NULL)
    {
        printf("new failed\n");
    }

    getchar();
    printf("free\n");

    if(data)
    {
        delete[] data;
        printf("free ok\n");
    }
        
    getchar();

  while(true){
       char *data = new char[1024];
       if(data) delete[] data;
       sleep(1);
    }
    return 0;   
}
```

```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10):
kk@ubuntu:~/kk/test$ g++  main.cpp -o test2 -I`jemalloc-config --includedir` -L`jemalloc-config --libdir` -Wl,-rpath,`jemalloc-config --libdir` -ljemalloc `jemalloc-config --libs`
```

Thre program has ran for one night.
Program execution result:
1. When the initial states of the program is
![QQ截图20190417195231](https://user-images.githubusercontent.com/5274872/56331995-1cb95080-61c1-11e9-9faa-c3a179a5e625.png)
 

Look at the final result.
![QQ截图20190418094324](https://user-images.githubusercontent.com/5274872/56332141-ba148480-61c1-11e9-8be5-370b91bd1643.png)

**Comment by IRainman** [comment]
Isn't that the correct behavior? There is a lot of free memory in the system. Since we have already allocated the memory to the application anyway, why should we select it if nobody needs it? And this memory is definitely not needed by anyone because the system is free ~180 MB.

**Comment by interwq** [comment]
@jay602: can you check `malloc_stats` at the end? the specific pattern you had might fall into some corner case. Two things to try: 1) call `malloc_stats_print(NULL, NULL, NULL)`, e.g. after sleeping for 30 seconds at the end; and 2) change the size to 32k in `char *data = new char[1024];`.

**Comment by jay602** [comment]
@interwq  This is my test code.
```
#include <stdlib.h>
#include <stdio.h>
#include <jemalloc/jemalloc.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    getchar();

    printf("new\n");
    
    char *data = new char[200* 1024 * 1024];
    if(data == NULL)
    {
        printf("new failed\n");
    }

    getchar();
    printf("free\n");

    if(data)
    {
        delete[] data;
        printf("free ok\n");
    }
        
    getchar();

    sleep(30);
    printf("after sleep.\n");
    
    malloc_stats_print(NULL, NULL, NULL);
    data = new char[1024];
    getchar();

    return 0;   
}
```

**Comment by interwq** [comment]
@jay602 : the results and stats both look fine to me. Are you worried about the VIRT usage? It's virtual memory and do not consume physical memory.

**Comment by interwq** [comment]
Closing but feel free to ask questions.
