### ISSUE TITLE
Print jemalloc runtime configuration

### ISSUE THREAD

**Issue by bentzimor** [jemalloc/jemalloc#1491]
Hi

I am running jemalloc 4.5.0 and set the MALLOC_CONF=purge:decay
How can I at runtime that the variable took place and not running with the default (ratio based)?

Thanks.

**Comment by interwq** [comment]
You can check the runtime settings in malloc_stats, e.g. by invoking malloc_stats_print() http://jemalloc.net/jemalloc.3.html#malloc_stats_print_opts; or adding `stats_print:true` to malloc_conf to output the stats at exit. Alternatively, adding some invalid setting to the end of the conf string, and combine with "abort_conf:true" which will stop the program at boot with invalid options.

We are also considering adding a new option to always output the settings in #1492.
