### ISSUE TITLE
What is the cost of --enable-prof

### ISSUE THREAD

**Issue by wudeng** [jemalloc/jemalloc#1496]
I'm using jemalloc in an open source project called skynet,  I was worried enabling profiling would slow things down, So it was built without "--enable-prof". Recently I would like to add some dynamic profiling to the project through the prof.active option, which means build it with "--enable-prof". My question is: what is the cost? Is it safe to enable profiling by default in productive environment?

**Comment by interwq** [comment]
Building with `enable-prof` has minimal overhead, in our experience barely measurable. Adding `prof:true` will enable profiling at runtime, which does has a small CPU and memory overhead (should be <0.5%). We have many production tiers enable profiling by default, so it's certainly safe and practical.
