### ISSUE TITLE
Add atomic.h support for powerpc 32/64 architectures.

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#15]
Add atomic.h support for powerpc 32/64 architectures.  This is needed when building with old versions of gcc that lack the necessary intrinsics.

**Comment by jasone** [comment]
@davidtgoldblatt, your work in #532 is likely to obsolete this.

**Comment by davidtgoldblatt** [comment]
After #664, we should support power with gcc versions >= 4.1.0.
