### ISSUE TITLE
Verify which malloc is used

### ISSUE THREAD

**Issue by rkoornstra** [jemalloc/jemalloc#1500]
Hello Everyone,

Forgive my basic question, but since we include stdlib.h (which includes malloc) how do I know the malloc from jemalloc is used in not the standard one? Thanks!

**Comment by interwq** [comment]
running with env var `MALLOC_CONF="abort_conf:true,some_invalid_option"` will abort at init with the invalid runtime option. Alternatively, Yinan is adding a simple option to output config info at beginning in #1498.
