### ISSUE TITLE
mallctl("epoch") is very slow in some scenario

### ISSUE THREAD

**Issue by oranagra** [jemalloc/jemalloc#1502]
Hi, I'm trying to enable the background_thread in Redis to solve a problem i reported in #1398.
while testing for possible regression i found a problem which i'm not yet sure what it is related to.

I'm attaching a small tester that reproduces it, but the general scenario is this:
Application allocates some massive amount of allocations (about 100M allocations of 100 bytes, 100M allocations of 24 bytes, and another 8MB of big chunk).
It then proceeds to release that memory in a background thread, while the main thread starts working on a new data set (but in some cases the main thread may also go idle).
Since the main thread may go idle, i'm enabling the `background_thread`.
Another thing that the main thread is doing from time to time is collect some stats from jemalloc, for which it needs to set the `epoch` using `mallctl.

In some cases, i observed that triggering the `epoch` calculations takes over a second!!!
This doesn't seem to occur when the background_thread is disabled, and it also doesn't seem to occur if the old allocations are released at the same order in which they were allocated (this is why the attached tester uses Redis's dict.c, i.e. to scramble the order in which deallocations are make)

Please let me know if there's a way to mitigate this? or if this is maybe a bug / edge case that can be fixed in jemalloc.

Thanks.

[test_epoch_calc_time.tgz.txt](https://github.com/jemalloc/jemalloc/files/3171307/test_epoch_calc_time.tgz.txt)
 (sorry for the dirty coding)

**Comment by interwq** [comment]
Can you share the `malloc_stats` after the long epoch delay? It sounds like we are holding some lock which blocks the epoch operation. Generally we are less concerned with the background threads holding locks longer (since it's taking the hit for the app threads), however in this case it might matter.

**Comment by oranagra** [comment]
@interwq i updated the tester that's attached to the first post above to print malloc_stats when epoch calculation time exceeds 200ms, output attached below.
[testit.output.txt](https://github.com/jemalloc/jemalloc/files/3171308/testit.output.txt)

**Comment by interwq** [comment]
Reading through the stats, I don't see any crazy high lock waiting times (the `max_wait_ns ` counter). Maybe it's simply the thread gets preempted for a while? It doesn't explain why it only happens with bg thds enabled. Can you also try if it repros with 5.2 instead of 5.1?

**Comment by oranagra** [comment]
here's the output with jemalloc 5.2.
first run with background thread were we can see epoch calc time taking over 900ms.
second run without background thread, shows max epoch calc time of 22us.
using same tester code that is attached to the first post.
[testit2.txt](https://github.com/jemalloc/jemalloc/files/3180949/testit2.txt)

**Comment by interwq** [comment]
I can repro this on my dev machine. Will dig into it.

**Comment by interwq** [comment]
Fixed in #1510. Thanks a lot for the great report and repro @oranagra! Made the investigation much easier for me.

Another thing to consider is, right now the per bg thd lock stats is not reported, as we didn't expect them to be contented. If we had that in stats, it would be much easier to spot the source. Tracking in #1511.

**Comment by oranagra** [comment]
@interwq thank you for solving it...
happy to help.. (it did take me a while to narrow down the trigger for the issue)
