### ISSUE TITLE
high load average issue

### ISSUE THREAD

**Issue by suenway** [jemalloc/jemalloc#1512]
Hi, 
On our production, we observed that jemalloc(5.1.0) caused many server threads to stay in 'D' state for several seconds. As a result, the load average was very high (the cpu and memory utilization <=30%). After removing jemalloc and using the default glibc malloc, the 'D' state issue was gone.

I tried to turn on `background_thread:true` and increase `dirty_decay_ms`&`muzzy_decay_ms ` to 60000, these didn't help much. Please advise. Thanks.

**Comment by interwq** [comment]
No enough info here for us to make suggestions. Please share more info (e.g. malloc_stats) if you can.
