### ISSUE TITLE
Design of /etc/je_malloc.conf

### ISSUE THREAD

**Issue by Ignition** [jemalloc/jemalloc#1513]
For tuning you can put options into:
> the "name" of the file referenced by the symbolic link named /etc/malloc.conf

This is seriously strange design, I'm unaware of any other configuration system working this way. 
Is there a good design reason that it is this way?
Is there any motivation to changing this to be the content of that file instead?

**Comment by interwq** [comment]
The config is read the first thing on init; so we want to avoid syscalls such as `open()` which may rely on malloc (which causes circular dependency, and requires tricky reentrancy handling). Instead using `readlink()` avoids depending on `open()`.
