### ISSUE TITLE
jemalloc4.5 core with musl on arm

### ISSUE THREAD

**Issue by nkzxw** [jemalloc/jemalloc#1514]
(gdb) bt
#0  arena_dalloc_bin_locked_impl (bitselm=0xb6ee9908, junked=<optimized out>, ptr=<optimized out>, chunk=<optimized out>, arena=<optimized out>, tsdn=<optimized out>) at src/arena.c:2955
#1  je_arena_dalloc_bin_junked_locked (tsdn=tsdn@entry=0xb6ee9908, arena=arena@entry=0xb6c12700, chunk=0xb5600000, ptr=0xb560d098, bitselm=0xb5600040) at src/arena.c:2981
#2  0x005e224c in je_tcache_bin_flush_small (tsd=0xb6ee9908, tcache=<optimized out>, tbin=0xb6451020, binind=<optimized out>, rem=3) at src/tcache.c:137
#3  0x005e2718 in je_tcache_event_hard (tsd=tsd@entry=0xb6ee9908, tcache=tcache@entry=0xb6451000) at src/tcache.c:48
#4  0x005c2bc4 in je_tcache_event (tcache=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/tcache.h:252
#5  je_tcache_dalloc_large (slow_path=<optimized out>, size=<optimized out>, ptr=<optimized out>, tcache=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/tcache.h:456
#6  je_arena_sdalloc (slow_path=true, tcache=0x0, size=3043528960, ptr=0xb56ea360, tsdn=<optimized out>) at include/jemalloc/internal/arena.h:1513
#7  je_isdalloct (slow_path=true, tcache=0x0, size=3043528960, ptr=0xb56ea360, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1195
#8  je_isqalloc (slow_path=true, tcache=0x0, size=3043528960, ptr=0xb56ea360, tsd=0xb6ee9908) at include/jemalloc/internal/jemalloc_internal.h:1205
#9  je_arena_ralloc (tsd=tsd@entry=0xb6ee9908, arena=arena@entry=0x0, ptr=ptr@entry=0xb56ea360, oldsize=oldsize@entry=32, size=size@entry=64, alignment=alignment@entry=0, zero=zero@entry=false, tcache=tcache@entry=0xb6451000) at src/arena.c:3376
#10 0x005afa54 in je_iralloct (arena=0x0, tcache=<optimized out>, zero=false, alignment=0, size=64, oldsize=<optimized out>, ptr=0xb56ea360, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1259
#11 je_iralloc (zero=false, alignment=0, size=64, oldsize=<optimized out>, ptr=0xb56ea360, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1268
#12 realloc (ptr=0xb56ea360, size=64) at src/jemalloc.c:1972
#13 0x00552a7c in alloc_addbyter ()
#14 0x00553a94 in dprintf_formatf ()
#15 0x00a91804 in Curl_cstrdup ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by nkzxw** [comment]
did all jemalloc5.x bugfix merged to jemalloc4.5？

**Comment by interwq** [comment]
musl might not support replacing malloc, see https://bugs.alpinelinux.org/issues/5389 The support was added pretty recent. Check if the version you have is compatible.

We are not aware any related bugs on 4.5.
