### ISSUE TITLE
Windows proxy malloc/free etc

### ISSUE THREAD

**Issue by Ignition** [jemalloc/jemalloc#1519]
Other allocators like TBB provide out of the box proxy that will swap out the CRTs allocator functions with those of its own. See the following:
https://github.com/intel/tbb/blob/tbb_2019/include/tbb/tbbmalloc_proxy.h
https://github.com/intel/tbb/blob/tbb_2019/src/tbbmalloc/proxy.cpp
https://github.com/intel/tbb/blob/tbb_2019/src/tbbmalloc/tbb_function_replacement.cpp

Any chance jemalloc could provide such a proxy?

**Comment by davidtgoldblatt** [comment]
Honestly I'm not sure there's the Windows expertise on the dev team it would take to get this to work.

In general, I'm growing more skeptical of trying to do malloc replacement on libcs that don't support it; it seems like there's just a stream of bugs of the form "I upgraded my OS, it changed some internal representation detail, and now there's a deadlock", and I'm not sure that's fixable.
