### ISSUE TITLE
jemalloc core in bitmap_set()

### ISSUE THREAD

**Issue by rkks** [jemalloc/jemalloc#1529]
Need help with jemalloc core that we are seeing in bitmap_set().

ubuntu: 14.04
gcc/g++: 4.8.4
jemalloc: rel v3.4.1

We are seeing crashes with below backtraces. On google search, we came across couple of reported issues that look quite similar to our crash backtraces.

https://github.com/TrinityCore/TrinityCore/issues/14533
http://jemalloc.net/mailman/jemalloc-discuss/2015-August/001132.html 

Will be really helpful if someone can provide us some pointers on the likelihood and probable fixes that have gone in later releases to address such an issue. Thanks.

- Crash 1
(gdb) bt
#0  0x00007fb82d1c51fb in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
#1  <signal handler called>
#2  bitmap_set (bit=18446744073709551615, binfo=0xb276b28 <arena_bin_info+456>, bitmap=0x7fb3f305e010) at ../usr/lib/libjemalloc/include/jemalloc/internal/bitmap.h:105
#3  bitmap_sfu (binfo=0xb276b28 <arena_bin_info+456>, bitmap=0x7fb3f305e010) at ../usr/lib/libjemalloc/include/jemalloc/internal/bitmap.h:140
#4  arena_run_reg_alloc (bin_info=0xb276b00 <arena_bin_info+416>, run=0x7fb3f305e000) at ../usr/lib/libjemalloc/src/arena.c:325
#5  arena_malloc_small (arena=<optimized out>, size=size@entry=64, zero=zero@entry=false) at ../usr/lib/libjemalloc/src/arena.c:1457
#6  0x00000000015c45c7 in arena_malloc (try_tcache=true, zero=false, size=64, arena=0x0) at ../usr/lib/libjemalloc/include/jemalloc/internal/arena.h:934
#7  imallocx (try_tcache=true, arena=0x0, size=64) at ../usr/lib/libjemalloc/include/jemalloc/internal/jemalloc_internal.h:798
#8  imalloc (size=64) at ../usr/lib/libjemalloc/include/jemalloc/internal/jemalloc_internal.h:807
#9  malloc (size=size@entry=64) at ../usr/lib/libjemalloc/src/jemalloc.c:1150

- Crash 2
(gdb) where 
#0  0x00007f3b914ac1fb in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
#1  <signal handler called>
#2  bitmap_set (bit=18446744073709551615, binfo=0xb276b28 <arena_bin_info+456>, bitmap=0x7f3832764010) at ../usr/lib/libjemalloc/include/jemalloc/internal/bitmap.h:105
#3  bitmap_sfu (binfo=0xb276b28 <arena_bin_info+456>, bitmap=0x7f3832764010) at ../usr/lib/libjemalloc/include/jemalloc/internal/bitmap.h:140
#4  arena_run_reg_alloc (bin_info=0xb276b00 <arena_bin_info+416>, run=0x7f3832764000) at ../usr/lib/libjemalloc/src/arena.c:325
#5  arena_malloc_small (arena=<optimized out>, size=size@entry=64, zero=zero@entry=true) at ../usr/lib/libjemalloc/src/arena.c:1457
#6  0x00000000015c4aa2 in arena_malloc (try_tcache=true, zero=true, size=64, arena=0x0) at ../usr/lib/libjemalloc/include/jemalloc/internal/arena.h:934
#7  icallocx (try_tcache=true, arena=0x0, size=64) at ../usr/lib/libjemalloc/include/jemalloc/internal/jemalloc_internal.h:815
#8  icalloc (size=64) at ../usr/lib/libjemalloc/include/jemalloc/internal/jemalloc_internal.h:824
#9  calloc (num=num@entry=1, size=<optimized out>) at ../usr/lib/libjemalloc/src/jemalloc.c:1362

**Comment by rkks** [comment]
Adding few more details.

Thread-cache is disabled in jemalloc.

The boxes where crashes are seen have 8 core x86 CPUs and have 64GB RAM. The memory utilization at the time of crash was approx ~18GB. The application using jemalloc is a multi-threaded and was using approx ~12GB of memory at the time of crash.

**Comment by davidtgoldblatt** [comment]
These sorts of issues almost always point to some sort of application-induced memory corruption bug (e.g. double-free). I'd suggest running against jemalloc in debug mode, or something like address sanitizer, and seeing if that exposes the issue.

**Comment by rkks** [comment]
Thanks @davidtgoldblatt for insight. We didn't have much luck with address sanitizer as it might be a timing issue. We have enabled jemalloc asserts and running tests to see if it catches the issue.

**Comment by interwq** [comment]
Closing but feel free to ask if anything.
