### ISSUE TITLE
tcache interaction with user-created arenas

### ISSUE THREAD

**Issue by frederik-h** [jemalloc/jemalloc#1535]
I would like to use explicitly created arenas in conjunction with thread caches. One of the reasons for using the explicit arenas is that I need to be able dispose of large amounts of allocations quickly. That is, I need to be able to destroy the arenas. But, as far as I can see, this is not possible if I use the automatic thread caches since they seem to associate with my own arenas which obviously leads to trouble if the caches continue to be used after deleting the arena.

The arenas that I need to destroy are used from a single thread only and hence I would probably not need a thread cache for the allocations on these arenas. But I would like to use the thread caches when ```malloc``` is used without an explicit arena and, ideally, also for some specific arenas that I create but which never have to be destroyed.

Is it possible to keep the automatic thread cache management from associating thread caches with certain arenas?

**Comment by davidtgoldblatt** [comment]
No. This is bad and unfortunate, and it's on the roadmap of things we want to fix in the next year or two, but disentangling the thread cache for malloc from the others is fairly tricky and will take a while.

Sorry :(

**Comment by interwq** [comment]
Adding to what David mentioned, if you allocate from the manual arena with `mallocx`, you can pass in `MALLOCX_TCACHE_NONE` to bypass tcache for the specific mallocx call; however you also need to make sure the deallocation to have the same flag, so that it doesn't get cached into the auto tcache.
