### ISSUE TITLE
How to use jemalloc debug mode

### ISSUE THREAD

**Issue by ben741863140** [jemalloc/jemalloc#1536]
I have seen that there have a debug mode can detect double frees, misaligned pointers, etc. However, I don't know how to use it. Now I have a program name test.cpp, would you like to tell me how to compile my program or install the jemalloc to use the debug mode?

**Comment by davidtgoldblatt** [comment]
Debug mode is a build-time setting. To enable it, configure with `./configure --enable-debug`. Then, you can link against it normally.
