### ISSUE TITLE
opt.retain & ulimit

### ISSUE THREAD

**Issue by asl** [jemalloc/jemalloc#1538]
It seems that ```opt.retain``` has very bad interaction with ulimit on RSS being set. I'm monitoring large application which does lots of allocations and deallocations utilizing multiple threads. As a precaution agains excessive memory consumption, the resident set size is limited via ulimit.

When ```opt.retain``` is set to ```true``` I'm seeing that VSIZE constantly grows. And at some point either memory allocation fails, or mmap()'s done by application fails. When ```opt.retain``` is set to ```false``` everything works as expected – no memory allocation fails, all mmap()'s succeed, etc. 

However, I'm a bit worried about keeping ```opt.retain``` set to ```false``` since the application is run on Linux and we certainly do not want to fragment the address space.

Is this behavior expected? I don't see anything like this with jemalloc 3.1 (the previous version we used for ages), however there is certainly some problem with the latest jemalloc 5.2.

Setting things like dirty_decay_ms:0,muzzy_decay_ms:0 do not help, unfortunately.

**Comment by asl** [comment]
Here is typical information when it overshoot the limit:

Allocated: 13438838848, active: 16051761152, metadata: 208637808 (n_thp 0), resident: 16263876608, mapped: 16326230016, retained: 21066043392

The amount of retained memory looks very high...

**Comment by interwq** [comment]
The behavior is expected. Retain is about keeping virtual memory around and avoid unmapping them (which has negative side effects, e.g. reaching `vm.max_map_count` on Linux). 

See http://jemalloc.net/jemalloc.3.html#opt.retain  VSIZE is practically free (even with some extreme cases we tested); so I wouldn't worry much about the overhead there. If you are tracking memory usage, I suggest monitor RSS instead of VSIZE.

**Comment by asl** [comment]
Sure, do you know universal cross-platform way to monitor RSS? Note that jemalloc 3 does not exhibit this behavior. Looks like we'd need to fall back to old version.

**Comment by interwq** [comment]
Does `RLIMIT_RSS` with setrlimit work for you? opt.retain is added as an optimization in jemalloc 5.x. Again the VSIZE is not necessarily related to the actual RSS usage, so monitoring that won't help much.

**Comment by asl** [comment]
Currently we're using `RLIMIT_AS`. As for `RLIMIT_RSS` – it seems, it is totally useless. E.g. (https://www.freebsd.org/cgi/man.cgi?query=setrlimit):

```
		     Processes that exceed their set RLIMIT_RSS	are not	sig-
		     nalled or halted.	The limit is merely a hint to the VM
		     daemon to prefer to deactivate pages from processes that
		     have exceeded their set RLIMIT_RSS.
```
And on Linux:
```
       RLIMIT_RSS
              This is a limit (in bytes) on the process's resident set (the
              number of virtual pages resident in RAM).  This limit has
              effect only in Linux 2.4.x, x < 30, and there affects only
              calls to madvise(2) specifying MADV_WILLNEED.
```
I believe certainly there was something similar to retain in jemalloc 3. At least with the similar functionality (do not unmap too much).
