### ISSUE TITLE
Any config option to disable statically linked jemalloc?

### ISSUE THREAD

**Issue by anysql** [jemalloc/jemalloc#1540]
We are statically compiled mysql with jemalloc, we need to disable or bapass the jemalloc memory management temporary without redistribute the mysql binary for memory problem diagnose. 

Is it possible?

**Comment by davidtgoldblatt** [comment]
Hi, sorry, I'm not entirely sure what you're trying to do here. Could you explain a little bit more?

It seems like you can just not link against jemalloc?

**Comment by interwq** [comment]
If you are thinking of not running with statically linked jemalloc using runtime options, I don't think that's possible. Closing but feel free to ask.
