### ISSUE TITLE
How will the jemalloc (jemalloc-5.1.0) be transplanted onto the ARM?

### ISSUE THREAD

**Issue by shirenfeng** [jemalloc/jemalloc#1542]
I want to cross-complile jemalloc-5.1.0 for arm platform,my cross-compiler is arm-linux-gnueabihf-gcc,I change CC=arm-linux-gnueabihf-gcc in Makefile and make,  errors .How will the jemalloc (jemalloc-5.1.0) be transplanted onto the ARM?

**Comment by interwq** [comment]
You can check the configs in our ARM CI for examples, e.g. https://master.jemalloc.net/#/builders/8/builds/412

**Comment by shirenfeng** [comment]
> You can check the configs in our ARM CI for examples, e.g. https://master.jemalloc.net/#/builders/8/builds/412

my compiler is  arm-linux-gnueabihf-gcc ,can you use it to try?

**Comment by shirenfeng** [comment]
./configure CC=arm-linux-gnueabihf-gcc  --host=x86_64
make
............
.............
include/jemalloc/internal/jemalloc_internal_inlines_a.h:14:2: warning: implicit declaration of function ‘sched_getcpu’ [-Wimplicit-function-declaration]
In file included from include/jemalloc/internal/jemalloc_internal_includes.h:89:0,
                 from src/jemalloc.c:3:
include/jemalloc/internal/arena_inlines_b.h: In function ‘arena_sdalloc_no_tcache’:
include/jemalloc/internal/arena_inlines_b.h:284:1: error: unable to generate reloads for:
(insn 287 283 289 19 (set (reg:SI 1 r1 [271])
        (sign_extract:SI (reg:SI 0 r0)
            (const_int 57 [0x39])
            (const_int 0 [0]))) include/jemalloc/internal/rtree.h:193 140 {*extv_reg}
     (expr_list:REG_DEAD (reg:SI 0 r0)
        (nil)))
include/jemalloc/internal/arena_inlines_b.h:284:1: internal compiler error: in find_reloads, at reload.c:3812
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.launchpad.net/gcc-linaro> for instructions.
make: *** [src/jemalloc.sym.o] Error 1

**Comment by MashoujiangPlusAI** [comment]
Why is this question closed since it seems not be solved? @interwq
