### ISSUE TITLE
How can i use jemalloc for code coverage ?

### ISSUE THREAD

**Issue by emstudio** [jemalloc/jemalloc#1548]
Hello, i configured jemalloc with code coverage option but no clue on how to collect the coverage results. I could not find any documentation related to code coverage  using jemalloc too.
Can i really use jemalloc for code coverage? Is there any working example or documentation ?

**Comment by interwq** [comment]
Not sure I understand the question. jemalloc itself doesn't do anything about code coverage. Are you talking about the compiler features?

Closing but feel free to ask.

**Comment by emstudio** [comment]
Yes i am asking about the compiler feature. 
--enable-code-coverage
    Enable code coverage support

**Comment by interwq** [comment]
It's a compiler feature; you would want to check the doc of the specific build tools you use.
