### ISSUE TITLE
I encounter a coredump in 5.2.0 build with gcc8.3.0

### ISSUE THREAD

**Issue by carson-yang** [jemalloc/jemalloc#1555]
env:
linux version : 3.10.0
build with default configuration

Program terminated with signal 11, Segmentation fault.
#0  0x00007f81b4e5930c in je_extent_heap_remove (ph=ph@entry=0x7f7fe6408120, phn=phn@entry=0x7f7fe640a000) at src/extent.c:289
289	ph_gen(, extent_heap_, extent_heap_t, extent_t, ph_link, extent_snad_comp)
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.x86_64
(gdb) bt
#0  0x00007f81b4e5930c in je_extent_heap_remove (ph=ph@entry=0x7f7fe6408120, phn=phn@entry=0x7f7fe640a000) at src/extent.c:289
#1  0x00007f81b4e25eb3 in arena_bin_slabs_nonfull_remove (slab=0x7f7fe640a000, bin=0x7f7fe64080a8) at src/arena.c:1606
#2  arena_dissociate_bin_slab (bin=0x7f7fe64080a8, slab=0x7f7fe640a000, arena=0x7f7fe64008c0) at src/arena.c:1606
#3  arena_dalloc_bin_locked_impl (junked=true, ptr=<optimized out>, slab=0x7f7fe640a000, binind=0, bin=0x7f7fe64080a8, arena=0x7f7fe64008c0, tsdn=0x7f8105372e88,
    tsdn@entry=0x0) at src/arena.c:1666
#4  je_arena_dalloc_bin_junked_locked (tsdn=tsdn@entry=0x7f8105372e88, arena=arena@entry=0x7f7fe64008c0, bin=bin@entry=0x7f7fe64080a8, binind=binind@entry=16,
    extent=0x7f7fe640a000, ptr=<optimized out>) at src/arena.c:1682
#5  0x00007f81b4e7f4e9 in je_tcache_bin_flush_small (tsd=tsd@entry=0x7f8105372e88, tcache=tcache@entry=0x7f8105373078, tbin=0x7f8105373208, binind=<optimized out>,
    rem=<optimized out>) at include/jemalloc/internal/tsd.h:225
#6  0x00007f81b4e1d8ea in tcache_dalloc_small (slow_path=false, binind=<optimized out>, ptr=0x7f7fe6247400, tcache=0x7f8105373078, tsd=<optimized out>)
    at include/jemalloc/internal/tcache_inlines.h:179
#7  arena_dalloc (slow_path=false, alloc_ctx=<synthetic pointer>, tcache=0x7f8105373078, ptr=0x7f7fe6247400, tsdn=<optimized out>)
    at include/jemalloc/internal/arena_inlines_b.h:295
#8  idalloctm (slow_path=false, is_internal=false, alloc_ctx=<synthetic pointer>, tcache=0x7f8105373078, ptr=0x7f7fe6247400, tsdn=<optimized out>)
    at include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#9  ifree (slow_path=false, tcache=0x7f8105373078, ptr=0x7f7fe6247400, tsd=<optimized out>) at src/jemalloc.c:2506
#10 je_free_default (ptr=0x7f7fe6247400) at src/jemalloc.c:2710
#11 0x00007f81b4e1df4d in free (ptr=<optimized out>) at src/jemalloc.c:2787
#12 0x00007f81b4e83c15 in operator delete (ptr=<optimized out>) at src/jemalloc_cpp.cpp:107

**Comment by interwq** [comment]
This is typically caused by heap corruption from the application. Sanitizers like ASAN are usually very helpful; or if that doesn’t work, try building jemalloc debug mode (—enable-debug).
