### ISSUE TITLE
make jemalloc allocation functions fail with total object size larger than PTRDIFF_MAX

### ISSUE THREAD

**Issue by LifeIsStrange** [jemalloc/jemalloc#1581]
> Memory allocation functions malloc, calloc, realloc, reallocarray, valloc, pvalloc, memalign, and posix_memalign fail now with total object size larger than PTRDIFF_MAX. This is to avoid potential undefined behavior with pointer subtraction within the allocated object, where results might overflow the ptrdiff_t type.

From the glibc 2.30 (latest) update.
https://sourceware.org/ml/libc-announce/2019/msg00001.html
I guess you should update behavior too ?

context: https://trust-in-soft.com/objects-larger-than-ptrdiff_max-bytes/

**Comment by interwq** [comment]
This is already enforced, as mentioned in http://jemalloc.net/jemalloc.3.html :

> large size classes extend from four times the page size up to the largest size class that does not exceed PTRDIFF_MAX.

There are a few sanity checks around this in the tests, e.g. https://github.com/jemalloc/jemalloc/blob/dev/test/unit/size_classes.c#L152
