### ISSUE TITLE
hi JEMALLOC_VERSION

### ISSUE THREAD

**Issue by wangzhione** [jemalloc/jemalloc#1598]
Environmental :
window 10 
jemalloc 5.2.1
x64 Native Tools Command Prompt for VS 2019

Generate:
jemalloc-5.2.1\include\jemalloc\jemalloc.h

...
#  define je_smallocx_0000000000000000000000000000000000000000 je_smallocx_0000000000000000000000000000000000000000
...
#define JEMALLOC_VERSION "0.0.0-0-g0000000000000000000000000000000000000000"
#define JEMALLOC_VERSION_MAJOR 0
#define JEMALLOC_VERSION_MINOR 0
#define JEMALLOC_VERSION_BUGFIX 0
#define JEMALLOC_VERSION_NREV 0
#define JEMALLOC_VERSION_GID "0000000000000000000000000000000000000000"
#define JEMALLOC_VERSION_GID_IDENT 0000000000000000000000000000000000000000
...

Thanks:
Whether this version is normal or not, it can be used normally at present.

**Comment by interwq** [comment]
When building from sources, git tags are needed to generate version numbers. `git fetch --tags` should fix it for you.

**Comment by wangzhione** [comment]
Dear thank you

**Comment by wangzhione** [comment]
Thank you
