### ISSUE TITLE
run_test fails due to -Werror (stringop-overflow)

### ISSUE THREAD

**Issue by bpringlemeir** [jemalloc/jemalloc#1601]
The run_test has log.c with line 53, etc.

	log_var_t log_l1 = LOG_VAR_INIT("l1");
        ...
	strcpy(log_var_names, "l1");

I think the intent is to verify that jemalloc detects a buffer overwrite in this situation.  However, the code fails to compile with some newer GCC as the option 'stringop-overflow' detects the overwrite at compile time and the log.c fails to build aborting the test.

**Comment by bpringlemeir** [comment]
I added -Wno-error=stringop-overflow= to the python file (so remove that build warning as error if gccXX detected is a solutions).  Also, log.c could put some sort of __attribute__ on that routine to turn off this diagnostic.  Probably that is useful if the intent of log.c is to detect buffer over-writes as this could appear with many different compilers doing this static analysis.

**Comment by bpringlemeir** [comment]
Could also be a tool issue,

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87296

I didn't see this issue reported here.  So at least it is useful to confirm if/when others encounter it.

**Comment by bpringlemeir** [comment]
I tested my gcc for this bug and it doesn't seem to have it.  I looked at the configure and it has "log: 0", so I think that JEMALLOC_LOG_VAR_BUFSIZE is 1 and the strcpy is overwriting log_var_names.

This seems to be an exhaustive test.  I should probably just run 'make test'.  The script detects many compilers on my machine and it looks like it has 1150 tests.

**Comment by interwq** [comment]
@bpringlemeir : thanks for reporting this. Can you please share the full config of the failed test? The test should be skipped without `config_log`; https://github.com/jemalloc/jemalloc/blob/dev/test/include/test/test.h#L319

**Comment by bpringlemeir** [comment]
I saw that macro in test.h.  I believe the issue is that the compiler still see the `strcpy`.  The macro will correctly skip things and the `strcpy` will never be called during **run time**.  The issue is the **compile** fails if LOG is off as it still tries to compile the strcpy which would over write the buffer.  I stopped it at about build 'one hundred and fifty' after I added this option to not detect a string overflow.

The script gives the step,

> EXTRA_CFLAGS=-Werror EXTRA_CXXFLAGS=-Werror CC=gcc  CXX=g++  ../../configure 
[config.log](https://github.com/jemalloc/jemalloc/files/3517541/config.log)
[run_test.log](https://github.com/jemalloc/jemalloc/files/3517542/run_test.log)

--enable-debug

As the first to fail.  I tried to attach the config.log and run_test.log

**Comment by davidtgoldblatt** [comment]
Yeah; the issue is that the compiler can't see that
```
if (false) {
  do_undefined_behavior();
}
```
is a safe construct.

Given that this is sort of a frequent source of headaches, maybe it's worth pulling out that logic into some helper that (say) assigns to and from a volatile before doing the copy?

**Comment by bpringlemeir** [comment]
It look like many (50+%) are of the form,

> unit/zero.c-TEST_BEGIN(test_zero_small) {
> unit/zero.c:    test_skip_if(!config_fill);

Maybe you could change the macro to use 'TEST_BEGIN_COND(f,e)' and put these conditionals there.  You would need at TEST_END_COND as well (or lispish is to use p).  It is more like,

>   if(true) { goto out; }
>  do_undefined_behavior();
>  out: return;

I have this code and it is fine,

> 
> #include <string.h>
> #define test 0
> char str[1];
> int foo(void)
> {
> 	if(!test) { goto out; }
> 	strcpy(str,"ab");
>   out:
>     return 0;
> }
> int bar(void)
> {
> 	if(test) strcpy(str,"ab");
>     return 0;
> }
> 

If I replace `#define test` with `const int`, I have the warning.  I think part of the issue is with `const bool` which 'C' treats a little differently than C++ afair.
