### ISSUE TITLE
realloc-in-place API (or realloc with a move callback)

### ISSUE THREAD

**Issue by al45tair** [jemalloc/jemalloc#1618]
There should be an `mshrink` API, which is like `realloc`, but (a) only supports shrinking, and (b) guarantees that it will never move the memory block (but might not actually shrink it in some cases, as a result).

The reason this is desirable is that in order to allow shrinking of C++ containers, the container needs to be able to guarantee that the underlying memory allocator won't move data on its own (because in that case, copy constructors and destructors, or move constructors, would need to run; not running them will break things in some cases). Supporting shrink-in-place is, however, desirable.

It *might* also be desirable to support an `mgrow` API for in-place grow, though the chances of that actually working are obviously more limited.

Alternatively, perhaps there should be a variant of `realloc` with a callback that gets used to move data if required? That would also solve the problem.

**Comment by davidtgoldblatt** [comment]
Any reason why calling `xallocx` with a reduced capacity doesn't suffice?

**Comment by al45tair** [comment]
Hah, good point, I missed that! Maybe `xallocx` wasn't the best choice of name :-)
