### ISSUE TITLE
jemalloc .heap file not getting generated on linux

### ISSUE THREAD

**Issue by GauravAccGit** [jemalloc/jemalloc#1630]
Hi,
I have compiled jemalloc using --enable-prof option and installed the library in some path such that my application is linked to jemalloc 

$ jemalloc-config --config
--prefix=/jemalloc-5.2.1/usr/local --enable-prof

However, when I run the application and stop it, .heap file is not getting generated. 
Below is the MALLOC_CONF setting I am using: 
$ echo $MALLOC_CONF
prof:true,lg_prof_interval:24,lg_prof_sample:12,prof_final:true,prof_leak:true

Have tried by changing lg_prof_interval, lg_prof_sample to 30/17 respectively but still .heap file not generated. 
Any pointers would be really helpful
Thanks,
Gaurav

**Comment by interwq** [comment]
Can you share the output from “malloc_stats_print(null, null, null)”? It can tell if the options are set properly.

**Comment by GauravAccGit** [comment]
I have to use this malloc_stats_print(null, null, null) in application code OR as option in MALLOC_CONF?

**Comment by GauravAccGit** [comment]
I changed the MALLOC_CONF as follows: 

export MALLOC_CONF=prof:true,lg_prof_interval:22,lg_prof_sample:12,prof_final:true,prof_leak:true
Thereafter, getting below error while application coming up:

15:06:06.848 ·  0.000: <jemalloc>: creat("jeprof.13380.1.i1.heap"), 0644) failed
15:06:06.848 ·  0.000: <jemalloc>: creat("jeprof.13380.2.i2.heap"), 0644) failed
15:06:06.848 ·  0.000: <jemalloc>: creat("jeprof.13380.3.i3.heap"), 0644) failed
...
...
15:06:07.110 ·  0.262: <jemalloc>: creat("jeprof.13380.51.i51.heap"), 0644) failed

Also used malloc_stats_print in application and below is the output:

15:06:07.110 ·  0.262: ___ Begin jemalloc statistics ___
15:06:07.110 ·  0.262: Version: "0.0.0-0-g0000000000000000000000000000000000000000"
15:06:07.110 ·  0.262: Build-time option settings
15:06:07.110 ·  0.262:   config.cache_oblivious: true
15:06:07.110 ·  0.262:   config.debug: false
15:06:07.110 ·  0.262:   config.fill: true
15:06:07.110 ·  0.262:   config.lazy_lock: false
15:06:07.110 ·  0.262:   config.malloc_conf: ""
15:06:07.110 ·  0.262:   config.opt_safety_checks: false
15:06:07.110 ·  0.262:   config.prof: true
15:06:07.110 ·  0.262:   config.prof_libgcc: true
15:06:07.110 ·  0.262:   config.prof_libunwind: false
15:06:07.110 ·  0.262:   config.stats: true
15:06:07.110 ·  0.263:   config.utrace: false
15:06:07.110 ·  0.263:   config.xmalloc: false
15:06:07.110 ·  0.263: Run-time option settings
15:06:07.110 ·  0.263:   opt.abort: false
15:06:07.110 ·  0.263:   opt.abort_conf: false
15:06:07.110 ·  0.263:   opt.confirm_conf: false
15:06:07.110 ·  0.263:   opt.retain: true
15:06:07.110 ·  0.263:   opt.dss: "secondary"
15:06:07.111 ·  0.263:   opt.narenas: 16
15:06:07.111 ·  0.263:   opt.percpu_arena: "disabled"
15:06:07.111 ·  0.263:   opt.oversize_threshold: 8388608
15:06:07.111 ·  0.263:   opt.metadata_thp: "disabled"
15:06:07.111 ·  0.263:   opt.background_thread: false (background_thread: false)
15:06:07.111 ·  0.263:   opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
15:06:07.111 ·  0.263:   opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)
15:06:07.111 ·  0.263:   opt.lg_extent_max_active_fit: 6
15:06:07.111 ·  0.263:   opt.junk: "false"
15:06:07.111 ·  0.263:   opt.zero: false
15:06:07.111 ·  0.263:   opt.tcache: true
15:06:07.111 ·  0.263:   opt.lg_tcache_max: 15
15:06:07.111 ·  0.263:   opt.thp: "default"
15:06:07.111 ·  0.263:   opt.prof: true
15:06:07.111 ·  0.263:   opt.prof_prefix: "jeprof"
15:06:07.111 ·  0.263:   opt.prof_active: true (prof.active: true)
15:06:07.111 ·  0.263:   opt.prof_thread_active_init: true (prof.thread_active_init: true)
15:06:07.111 ·  0.263:   opt.lg_prof_sample: 12 (prof.lg_sample: 12)
15:06:07.111 ·  0.263:   opt.prof_accum: false
15:06:07.111 ·  0.263:   opt.lg_prof_interval: 22
15:06:07.111 ·  0.263:   opt.prof_gdump: false
15:06:07.111 ·  0.263:   opt.prof_final: true
15:06:07.111 ·  0.263:   opt.prof_leak: true
15:06:07.111 ·  0.263:   opt.stats_print: false
15:06:07.111 ·  0.263:   opt.stats_print_opts: ""
15:06:07.111 ·  0.263: Profiling settings
15:06:07.111 ·  0.263:   prof.thread_active_init: true
15:06:07.111 ·  0.263:   prof.active: true
15:06:07.111 ·  0.263:   prof.gdump: false
15:06:07.111 ·  0.263:   prof.interval: 4194304
15:06:07.111 ·  0.263:   prof.lg_sample: 12
15:06:07.111 ·  0.263: Arenas: 17
15:06:07.111 ·  0.263: Quantum size: 16
15:06:07.111 ·  0.263: Page size: 4096
15:06:07.111 ·  0.263: Maximum thread-cached size class: 32768
15:06:07.111 ·  0.263: Number of bin size classes: 36
15:06:07.111 ·  0.263: Number of thread-cache bin size classes: 41
15:06:07.111 ·  0.263: Number of large size classes: 196
...

Thanks,
Gaurav

**Comment by interwq** [comment]
Check if you have write permission to the dump path. Feel free to ask if more questions.

**Comment by GauravAccGit** [comment]
I am not sure how jemalloc knows what is the dump path. 
I tweaked the MALLOC_CONF as follows: 
export MALLOC_CONF=prof:true,lg_prof_interval:16,lg_prof_sample:8,prof_final:true,prof_leak:true

After that, I could see following files being generated: 

-rw-r--r--   1 ...   ... 26042 ... jeprof.15885.1.i1.heap
-rw-r--r--   1 24278  jeprof.15885.0.i0.heap
-rw-r--r--   1    26558  jeprof.15885.2.i2.heap
-rw-r--r--   1    27739  jeprof.15885.3.i3.heap
-rw-r--r--   1    28203  jeprof.15885.4.i4.heap
...
...
-rw-r--r--   1   34266  jeprof.15885.10.i10.heap
-rw-r--r--   1    36069  jeprof.15885.11.i11.heap
-rw-r--r--   1   31861  jeprof.15885.12.i12.heap
-rw-r--r--   1   32809  jeprof.15885.14.i14.heap
-rw-r--r--   1    31867  jeprof.15885.13.i13.heap
 
So, total 14 files are created. However, it started giving errors from 15th file (in application log file): 

10:05:18.433 ·  0.001: <jemalloc>: creat("jeprof.15885.15.i15.heap"), 0644) failed
10:05:18.434 ·  0.003: <jemalloc>: creat("jeprof.15885.16.i16.heap"), 0644) failed
10:05:18.435 ·  0.003: <jemalloc>: creat("jeprof.15885.17.i17.heap"), 0644) failed
10:05:18.435 ·  0.004: <jemalloc>: creat("jeprof.15885.18.i18.heap"), 0644) failed
10:05:18.436 ·  0.005: <jemalloc>: creat("jeprof.15885.19.i19.heap"), 0644) failed
10:05:18.437 ·  0.006: <jemalloc>: creat("jeprof.15885.20.i20.heap"), 0644) failed
...
...

So, it's not clear where exactly is the error. If it was a permission issue, then first 14 files should also not have been formed. 
Kindly help

Thanks,
Gaurav

**Comment by interwq** [comment]
The dump path can be controlled by the prefix. http://jemalloc.net/jemalloc.3.html#opt.prof_prefix

Maybe insufficient disk space?

**Comment by GauravAccGit** [comment]
Hi,
I have been able to find out the root cause: At some point, my application code was doing this: 
char* work_dir = "/";
if (chdir(work_dir) < 0)
...
As a result, .heap was not getting generated as the user starting the application does not have root permissions. After removing above code, final .heap file is now getting generated. Thanks for your help!
I have one more query: Till now, I was testing on development environment where-in I could kill the process using CTRL-C and so I could see the final .heap file getting generated (jeprof.23452.f.0.heap). However, now I want to test jemalloc changes in staging environment where-in process would be running on linux under cgroups and I won't be able to kill it using CTRL-C. So, how will final .heap file be generated? Also, would I be getting intermediate .heap files based on lg_prof_interval,lg_prof_sample settings?

**Comment by interwq** [comment]
The final dump will be triggered when the program exits (implemented with ‘atexit()’). Interval based dumping can still be used, if the programs never exits. Note that the profiles will need to be cleaned up, otherwise they may eat up disk space.

**Comment by GauravAccGit** [comment]
In staging setup, I set the MALLOC_CONF variable in /etc/environment file as follows:
MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:19,prof_final:true,prof_leak:true

However, .heap files are not getting formed. I restarted the process also (systemctl restart <application.service> but still same result.

**Comment by GauravAccGit** [comment]
Hi,
After using command:
ln -s 'prof_prefix:/tmp/jeprof,prof:true,lg_prof_interval:30,lg_prof_sample:19,prof_final:true, prof_leak:true' /etc/malloc.conf

can see the final .heap file in /tmp folder when process is stopped. Will now run with traffic and see if some actual memory leaks are visible from the .heap file. Will update for further issues
Thanks for the inputs!

**Comment by GauravAccGit** [comment]
Hi @interwq 
After running traffic, what can be seen is that my application rsize memory grows too much. The .heap file showed some memory leaks. After fixing all those leaks, still there is a gap of around 500MB. (gap is more if traffic is run for longer duration).

I tried by enabling background_thread option set to true:
ln -s 'prof_prefix:/tmp/jeprof,background_thread:true, prof:true, lg_prof_interval:30, lg_prof_sample:19,prof_final:true,prof_leak:true' /etc/malloc.conf
 
However, still rsize is not coming back to what it was before starting traffic (even after waiting for an hour of stopping traffic). 
Somehow, it seems that jemalloc is not releasing the memory to OS. Is there any other setting which I should configure? 
Below is the output of malloc_stats when application is finally stopped (output is truncated, pls let me know if you require full output):

Sep 25 07:46:23 : ___ Begin jemalloc statistics ___
Sep 25 07:46:23 : Version: "0.0.0-0-g0000000000000000000000000000000000000000"
Sep 25 07:46:23 : Build-time option settings
Sep 25 07:46:23 : config.cache_oblivious: true
Sep 25 07:46:23 : config.debug: false
Sep 25 07:46:23 : config.fill: true
Sep 25 07:46:23 : config.lazy_lock: false
Sep 25 07:46:23 : config.malloc_conf: ""
Sep 25 07:46:23 : config.opt_safety_checks: false
Sep 25 07:46:23 : config.prof: true
Sep 25 07:46:23 : config.prof_libgcc: true
Sep 25 07:46:23 : config.prof_libunwind: false
Sep 25 07:46:23 : config.stats: true
Sep 25 07:46:23 : config.utrace: false
Sep 25 07:46:23 : config.xmalloc: false
Sep 25 07:46:23 : Run-time option settings
Sep 25 07:46:23 : opt.abort: false
Sep 25 07:46:23 : opt.abort_conf: false
Sep 25 07:46:23 : opt.confirm_conf: false
Sep 25 07:46:23 : opt.retain: true
Sep 25 07:46:23 : opt.dss: "secondary"
Sep 25 07:46:23 : opt.narenas: 32
Sep 25 07:46:23 : opt.percpu_arena: "disabled"
Sep 25 07:46:23 : opt.oversize_threshold: 8388608
Sep 25 07:46:23 : opt.metadata_thp: "disabled"
Sep 25 07:46:23 : opt.background_thread: true (background_thread: true)
Sep 25 07:46:23 : opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
Sep 25 07:46:23 : opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)
Sep 25 07:46:23 : opt.lg_extent_max_active_fit: 6
Sep 25 07:46:23 : opt.junk: "false"
Sep 25 07:46:23 : opt.zero: false
Sep 25 07:46:23 : opt.tcache: true
Sep 25 07:46:23 : opt.lg_tcache_max: 15
Sep 25 07:46:23 : opt.thp: "default"
Sep 25 07:46:23 : opt.prof: true
Sep 25 07:46:23 : opt.prof_prefix: "/tmp/jeprof"
Sep 25 07:46:23 : opt.prof_active: true (prof.active: true)
Sep 25 07:46:23 : opt.prof_thread_active_init: true (prof.thread_active_init: true)
Sep 25 07:46:23 : opt.lg_prof_sample: 19 (prof.lg_sample: 19)
Sep 25 07:46:23 : opt.prof_accum: false
Sep 25 07:46:23 : opt.lg_prof_interval: 30
Sep 25 07:46:23 : opt.prof_gdump: false
Sep 25 07:46:23 : opt.prof_final: true
Sep 25 07:46:23 : opt.prof_leak: true
Sep 25 07:46:23 : opt.stats_print: false
Sep 25 07:46:23 : opt.stats_print_opts: ""
Sep 25 07:46:23 : Profiling settings
Sep 25 07:46:23 : prof.thread_active_init: true
Sep 25 07:46:23 : prof.active: true
Sep 25 07:46:23 : prof.gdump: false
Sep 25 07:46:23 : prof.interval: 1073741824
Sep 25 07:46:23 : prof.lg_sample: 19
Sep 25 07:46:23 : Arenas: 33
Sep 25 07:46:23 : Quantum size: 16
Sep 25 07:46:23 : Page size: 4096
Sep 25 07:46:23 : Maximum thread-cached size class: 32768
Sep 25 07:46:23 : Number of bin size classes: 36
Sep 25 07:46:23 : Number of thread-cache bin size classes: 41
Sep 25 07:46:23 : Number of large size classes: 196
Sep 25 07:46:23 : Allocated: 806296112, active: 847650816, metadata: 26376048 (n_thp 0), resident: 873525248, mapped: 929853440, retained: 501977088
Sep 25 07:46:23 : Background threads: 4, num_runs: 22858, run_interval: 11682168795 ns
Sep 25 07:46:23 : n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
Sep 25 07:46:23 : background_thread                  65       0               0       0               0       0              32       0               0         0               0           0
Sep 25 07:46:23 : ctl                                 2       0               0       0               0       0               1       0               0         0               0           0
Sep 25 07:46:23 : prof                            44837       0               0       0               1       0           13835       0               0         0               0           0
Sep 25 07:46:23 : Merged arenas stats:
Sep 25 07:46:23 : assigned threads: 30
Sep 25 07:46:23 : uptime: 66767330570713
Sep 25 07:46:23 : dss allocation precedence: "N/A"
Sep 25 07:46:23 : decaying:  time       npages       sweeps     madvises       purged
Sep 25 07:46:23 : dirty:   N/A          101        20067        57153       536531
Sep 25 07:46:23 : muzzy:   N/A            0            0            0            0
Sep 25 07:46:23 : allocated         nmalloc (#/sec)         ndalloc (#/sec)       nrequests   (#/sec)           nfill   (#/sec)          nflush   (#/sec)

**Comment by interwq** [comment]
@GauravAccGit please do not cross post in other threads, unless it’s relevant. In this case the issue is quite specific to your binary.

What you described (rss not returning to initial value after handling workload) isn’t very unusual. The stats you shared look fine; nothing really stands out. There are only 101 dirty pages, so those don’t contribute much. In other words there isn’t many free pages that can be released.

What caused the increase after the traffic is very application specific. The heap profiling tool should be able to help.

**Comment by GauravAccGit** [comment]
OK, I will keep that in mind about cross posting

Can you please share more details about heap profiling tool

**Comment by interwq** [comment]
It's the same heap profiling tool you use to catch leaks; in your case, if you want to understand the gap, you can explicitly dump before accepting any requests, and then again after handling all requests and going idle, make another dump so that you can use the diff mode on the two profiles. This should help understanding the usage after workload; however this only covers the memory managed by jemalloc. Other parts such as directly mmapped pages by other libs won't be included.

**Comment by GauravAccGit** [comment]
Thanks @interwq for inputs. One thing: When the malloc_stats_print is called, it prints lot of statistics. If you can share any link about details of what those stats represent, it will be of great help. In particular, I am interested in knowing heap size of my application at any point.

**Comment by interwq** [comment]
You can see the details of the counters in the manual, e.g. http://jemalloc.net/jemalloc.3.html#stats.resident

For the heap size managed by jemalloc, you can check the `resident` counter, grep for `resident:` in the output should work.
