### ISSUE TITLE
chunk_alloc_core shouldn't unconditionally call chunk_recycle for mmap

### ISSUE THREAD

**Issue by VerGreeneyes** [jemalloc/jemalloc#164]
chunk_alloc_core appears to call into chunk_recycle for mmap even when config_munmap == true [1]. This is somewhat wasteful as chunk_recycle will always take the chunk lock, only to realize that the chunk cache is empty. I suggest wrapping lines 163-169 in an if (!config_munmap) {} block, which would aesthetically match the dss block above.

[1] https://github.com/jemalloc/jemalloc/blob/dev/src/chunk.c#L163

**Comment by jasone** [comment]
The ```chunk_alloc_mmap()``` call on line 167 should still happen even in the ```!config_munmap``` case, but I did as you suggested for the ```chunk_recycle()``` call.  Thanks!

**Comment by VerGreeneyes** [comment]
You're right of course. Looks good, thanks!
