### ISSUE TITLE
when openat available, we may use it on some architecture, such as aarch64

### ISSUE THREAD

**Issue by RingsC** [jemalloc/jemalloc#1644]
at some architecture, for example ARM, syscall 'open' not available but 'openat', 
so that we use 'openat' rather than 'open'
so in 'init_thp_state' we also need to determine which one would be used.

#if defined(JEMALLOC_USE_SYSCALL) && defined(SYS_open)
	int fd = (int)syscall(SYS_open,
	    "/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY);
**#elif defined(JEMALLOC_USE_SYSCALL) && defined(SYS_openat)
	int fd = (int)syscall(SYS_openat,
		           AT_FDCWD, "/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY);**
#else
	int fd = open("/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY);
#endif

[openat.patch.txt](https://github.com/jemalloc/jemalloc/files/3719945/openat.patch.txt)

**Comment by interwq** [comment]
Resolved in https://github.com/jemalloc/jemalloc/pull/1645.
