### ISSUE TITLE
linux 'top' command shows memory increase by 5%, but jemalloc shows not

### ISSUE THREAD

**Issue by andyxmu** [jemalloc/jemalloc#1663]
As title shows, I'm using below parameters:
 prof_active:true,prof_leak:true,lg_prof_sample:17

we suspect thers is some slow memory leak,and linux 'top' command shows memory increase by 5%, but jeprof shows it always stay the same 'Total ' value.

Anyone can help on this?

thanks!

**Comment by interwq** [comment]
The information isn't enough for us to give useful suggestions. Sharing output from `malloc_stats_print` will be a good start. Also check out heap profiling https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling
