### ISSUE TITLE
Document that jemalloc is not compatible with ulimit

### ISSUE THREAD

**Issue by asl** [jemalloc/jemalloc#1668]
Per #1538 – jemalloc does not work well in case where are limits imposed by RSS. This is a real problem on e.g. clusters / job-shared systems that may use this feature to limit the users' memory (and there is no alternative way to control memory usage from inside an application in sane manner).

Since this is a real problem with jemalloc 5 (we started to see lots of complaints with jemalloc 5 in the cases when everything was clean with jemalloc 3) and this is something is not going to be changed, please clearly outline this limitation of jemalloc in the documentation.

**Comment by interwq** [comment]
I don't think there's any incompatibility here. VM size isn't really a reliable way to track / control RSS (e.g. `overcommit` is the norm nowadays on Linux). I suggest looking into `cgroups` for this.

If VM size has to be limited, `retain:false` will unmap unused VM space and bring behavior close to previous versions of jemalloc.
