### ISSUE TITLE
Jemalloc 4.4.0- calloc function crash in arena_run_size_get

### ISSUE THREAD

**Issue by gnanakumarbala** [jemalloc/jemalloc#1673]
Hi team,

 we are using jemalloc version 4.4.0 . While trying to allocate memory using calloc function , it crashed ( SIGNAL 11 (Segmentation fault) ) with below bt. We have passed valid data of 16 bytes to calloc but still function crash. whether it is a known issue?.

#3  <signal handler called>
No symbol table info available.
#4  0x00007f8c2b37dfc6 in arena_run_size_get (tsdn=<value optimized out>, arena=0x7f8c23e936c0, run=<value optimized out>, dirty=true, cleaned=false, decommitted=false) at src/arena.c:2113
No locals.
#5  arena_run_dalloc (tsdn=<value optimized out>, arena=0x7f8c23e936c0, run=<value optimized out>, dirty=true, cleaned=false, decommitted=false) at src/arena.c:2132
        size = <value optimized out>
        run_ind = 358
        run_pages = <value optimized out>
        flag_dirty = <value optimized out>
        flag_decommitted = <value optimized out>
#6  0x00007f8c2b39f57a in je_tcache_bin_flush_large (tsd=<value optimized out>, tbin=<value optimized out>, binind=<value optimized out>, rem=<value optimized out>, tcache=<value optimized out>)
    at src/tcache.c:216
        chunk = 0x167
        locked_arena = 0x7f8c23e936c0
        idump = false
        arena = 0x7f8c23e9ac40
        ptr = 0xffffffffffe00000
        i = 1
        nflush = 2
        ndeferred = 0
        merged_stats = false
#7  0x00007f8c2b39fc54 in je_tcache_event_hard (tsd=0xd, tcache=0x7f8c23d25000) at src/tcache.c:49
        binind = 359
        tbin = 0x7f8c2b5bdf60
#8  0x00007f8c2b376063 in je_tcache_event (num=<value optimized out>, size=<value optimized out>) at include/jemalloc/internal/tcache.h:249
No locals.
#9  je_tcache_alloc_large (num=<value optimized out>, size=<value optimized out>) at include/jemalloc/internal/tcache.h:397
No locals.
#10 je_arena_malloc (num=<value optimized out>, size=<value optimized out>) at include/jemalloc/internal/arena.h:1349
No locals.
#11 je_iallocztm (num=<value optimized out>, size=<value optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1061
No locals.
#12 je_ialloc (num=<value optimized out>, size=<value optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1073
No locals.
#13 ialloc_body (num=<value optimized out>, size=<value optimized out>) at src/jemalloc.c:1599
        ind = 1
#14 calloc (num=<value optimized out>, size=<value optimized out>) at src/jemalloc.c:1815
        ret = 0x7f8bfccb10f0
        tsdn = <value optimized out>
        num_size = <value optimized out>
        usize = 16

Thanks,
B.Gnanakumar.

**Comment by interwq** [comment]
> tsd=0xd
> chunk = 0x167

These typically indicate heap corruption. Most likely from the application and happened before the crashing calloc call. Sanitizers such as ASan should help catch these; alternatively you can try building jemalloc with “—enable-debug”.
