### ISSUE TITLE
jemalloc consuming high RSS during Thread creation when THP was set as "always"

### ISSUE THREAD

**Issue by abenbachir** [jemalloc/jemalloc#1674]
Issue happening either with jemalloc 4.5 or 3.6 using Ruby 2.5.1 or 2.6.3.
While creating 100 threads with Ruby you can see a big spike in memory usage and that is related to THP.

The "MALLOC_CONF=thp:never" introduced in #1134 (jemalloc 4.5) doesn't work, because I keep getting this:
`<jemalloc>: Invalid conf value: thp:never`

$> cat /sys/kernel/mm/transparent_hugepage/enabled 
[**always**] madvise never

**Malloc,              Ruby 2.5.1, 11 MB
Malloc,              Ruby 2.6.3, 42 MB**
Jemalloc 3.6.0, Ruby 2.5.1, 181 MB
Jemalloc 3.6.0, Ruby 2.6.3, 215 MB
Jemalloc 4.5.0, Ruby 2.5.1, 250 MB
Jemalloc 4.5.0, Ruby 2.6.3, 283 MB

$> cat /sys/kernel/mm/transparent_hugepage/enabled 
always madvise [**never**]

**Malloc,              Ruby 2.5.1, 11 MB
Malloc,              Ruby 2.6.3, 15 MB**
Jemalloc 3.6.0, Ruby 2.5.1, 12 MB
Jemalloc 3.6.0, Ruby 2.6.3, 16 MB
Jemalloc 4.5.0, Ruby 2.5.1, 12 MB
Jemalloc 4.5.0, Ruby 2.6.3, 17 MB

Script:
```
number=100
number.times { |i| Thread.new { sleep 10 } }
sleep 1
puts "Creating #{number} threads, LD_PRLOAD=#{ENV['LD_PRELOAD']}..."
puts `ps -o rss -p #{Process.pid}`
```
This is how I do my tests:
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so ruby simple-threads.rb`

We can't change /sys/kernel/mm/transparent_hugepage/enabled or /sys/kernel/mm/transparent_hugepage/defrag in customer prod env.

**Comment by abenbachir** [comment]
Any input @davidtgoldblatt @interwq @jasone @SamSaffron

**Comment by SamSaffron** [comment]
Yeah this is something I have seen many times before with jemalloc all the 1MB reserved thread stack is always in RSS. Not the case in tcmalloc or libcmalloc

**Comment by abenbachir** [comment]
Is there a way to force jemalloc to use 4K even if transparent_hugepage is "always" ?

**Comment by SamSaffron** [comment]
You can use thpoff https://github.com/discourse/discourse_docker/blob/master/image/base/thpoff.c

and just pipe through it without changing anything on the server

**Comment by abenbachir** [comment]
I just noticed that THP was disabled in v2.6.
Why jemalloc is behaving badly with Ruby2.6 event with THP disabled w/ PR_SET_THP_DISABLE ?
```
    /*
     * Disable THP early before mallocs happen because we want this to
     * affect as many future pages as possible for CoW-friendliness
     */
#if defined(__linux__) && defined(PR_SET_THP_DISABLE)
        prctl(PR_SET_THP_DISABLE, 1, 0, 0, 0);
#endif
```

**Comment by SamSaffron** [comment]
Maybe this is a timing thing, maybe it is getting disabled too late?
Perhaps try to see if it works as expected with thpoff that makes the
changes before an exec?

**Comment by abenbachir** [comment]
Will prctl(PR_SET_THP_DISABLE, 1, 0, 0, 0); take effect on the current process or on the child ?

**Comment by abenbachir** [comment]
I just notice that I was compiling Ruby on Centos5 and the linux/prctl.h header didn't have this flag PR_SET_THP_DISABLE. So Ruby 2.6 was not disabling the THP.

I also validated that and worked with thpoff program that you attached.

Thanks.
