### ISSUE TITLE
Performance regression with HUGE_THRESHOLD_DEFAULT

### ISSUE THREAD

**Issue by mrks** [jemalloc/jemalloc#1677]
We are developing the research in-memory database [Hyrise](http://github.com/hyrise/hyrise).

When upgrading jemalloc from 7a815c1 to ea6b3e97, we noticed a significant performance regression introduced by https://github.com/jemalloc/jemalloc/commit/350809.

In single-threaded mode, the TPC-H benchmark gave use the following results:

```diff
 +----------------+----------------+-------+----------------+-------+------------+----------------------+
 | Benchmark      | prev. iter/s   | runs  | new iter/s     | runs  | change [%] |              p-value |
 +----------------+----------------+-------+----------------+-------+------------+----------------------+
-| TPC-H 01       | 0.608611941338 | 183   | 0.560413479805 | 169   | -8%        |               0.0000 |
-| TPC-H 02       | 12.422123909   | 3727  | 10.6051855087  | 3182  | -15%       |               0.0000 |
-| TPC-H 03       | 7.18575429916  | 2156  | 5.67671632767  | 1704  | -21%       |               0.0000 |
-| TPC-H 04       | 6.98459434509  | 2096  | 5.7726316452   | 1732  | -17%       |               0.0000 |
-| TPC-H 05       | 4.22810459137  | 1269  | 3.34266614914  | 1003  | -21%       |               0.0000 |
 | TPC-H 06       | 196.88911438   | 10000 | 194.981430054  | 10000 | -1%        | (run time too short) |
-| TPC-H 07       | 8.40113544464  | 2521  | 6.77922534943  | 2034  | -19%       |               0.0000 |
-| TPC-H 08       | 5.54870796204  | 1665  | 5.19938087463  | 1560  | -6%        |               0.0000 |
-| TPC-H 09       | 1.53582537174  | 461   | 1.38464677334  | 416   | -10%       |               0.0000 |
-| TPC-H 10       | 2.85038995743  | 856   | 2.68989849091  | 807   | -6%        |               0.0000 |
-| TPC-H 11       | 27.8206329346  | 8347  | 23.3441677094  | 7004  | -16%       |               0.0000 |
-| TPC-H 12       | 8.77770996094  | 2634  | 8.16262626648  | 2449  | -7%        |               0.0000 |
-| TPC-H 13       | 2.20570468903  | 662   | 2.05547451973  | 617   | -7%        |               0.0000 |
 | TPC-H 14       | 46.376499176   | 10000 | 46.3342819214  | 10000 | -0%        |               0.0716 |
 | TPC-H 15       | 76.5124740601  | 10000 | 75.9002456665  | 10000 | -1%        |               0.0000 |
-| TPC-H 16       | 6.9105591774   | 2074  | 6.32378816605  | 1898  | -8%        |               0.0000 |
-| TPC-H 17       | 1.57227170467  | 472   | 1.41119325161  | 424   | -10%       |               0.0000 |
-| TPC-H 18       | 0.805106163025 | 242   | 0.714566886425 | 215   | -11%       |               0.0000 |
 | TPC-H 19       | 33.5129928589  | 10000 | 32.9955596924  | 9899  | -2%        |               0.0000 |
-| TPC-H 20       | 2.56930947304  | 771   | 2.41745615005  | 726   | -6%        |               0.0000 |
-| TPC-H 21       | 1.4367647171   | 432   | 1.26840102673  | 381   | -12%       |               0.0000 |
-| TPC-H 22       | 14.2887220383  | 4287  | 11.5997133255  | 3480  | -19%       |               0.0000 |
-| geometric mean |                |       |                |       | -10%       |                      |
 +----------------+----------------+-------+----------------+-------+------------+----------------------+
```

With 280 logical cores, results look like this:

```diff
 +----------------+---------------+-------+---------------+-------+------------+---------+
 | Benchmark      | prev. iter/s  | runs  | new iter/s    | runs  | change [%] | p-value |
 +----------------+---------------+-------+---------------+-------+------------+---------+
 | TPC-H 01       | 12.6731786728 | 3802  | 12.5596256256 | 3768  | -1%        |  0.4182 |
-| TPC-H 02       | 289.952026367 | 10000 | 203.637664795 | 10000 | -30%       |  0.0000 |
-| TPC-H 03       | 127.491577148 | 10000 | 99.5596389771 | 10000 | -22%       |  0.0000 |
 | TPC-H 04       | 35.2989349365 | 10000 | 37.0170822144 | 10001 | +5%        |  0.0067 |
-| TPC-H 05       | 75.3958282471 | 10000 | 57.3086395264 | 10000 | -24%       |  0.0000 |
+| TPC-H 06       | 3132.63354492 | 10047 | 4055.80493164 | 10032 | +29%       |  0.0000 |
-| TPC-H 07       | 168.403396606 | 10001 | 135.297393799 | 10000 | -20%       |  0.0000 |
-| TPC-H 08       | 152.803039551 | 10002 | 120.546676636 | 10001 | -21%       |  0.0000 |
 | TPC-H 09       | 34.3682365417 | 10000 | 33.1723518372 | 9952  | -3%        |  0.0033 |
 | TPC-H 10       | 71.4074249268 | 10001 | 73.029083252  | 10000 | +2%        |  0.0110 |
-| TPC-H 11       | 546.906188965 | 10010 | 389.971405029 | 10002 | -29%       |  0.0000 |
 | TPC-H 12       | 361.627380371 | 10002 | 347.847076416 | 10003 | -4%        |  0.0030 |
 | TPC-H 13       | 54.6611557007 | 10000 | 53.5943527222 | 10000 | -2%        |  0.0401 |
 | TPC-H 14       | 902.07598877  | 10007 | 921.917602539 | 10008 | +2%        |  0.0356 |
 | TPC-H 15       | 1788.06005859 | 10005 | 1800.75878906 | 10002 | +1%        |  0.2331 |
 | TPC-H 16       | 205.136199951 | 10000 | 197.928237915 | 10002 | -4%        |  0.0000 |
 | TPC-H 17       | 25.7696876526 | 7731  | 26.1797904968 | 7854  | +2%        |  0.1477 |
-| TPC-H 18       | 14.6665058136 | 4400  | 13.6465864182 | 4094  | -7%        |  0.0000 |
 | TPC-H 19       | 598.716186523 | 10011 | 626.675476074 | 10034 | +5%        |  0.0000 |
-| TPC-H 20       | 52.8880310059 | 10001 | 38.8735809326 | 10001 | -26%       |  0.0000 |
+| TPC-H 21       | 22.5130386353 | 6754  | 23.6795330048 | 7104  | +5%        |  0.0000 |
-| TPC-H 22       | 204.671264648 | 10000 | 175.602172852 | 10000 | -14%       |  0.0000 |
-| geometric mean |               |       |               |       | -8%        |         |
 +----------------+---------------+-------+---------------+-------+------------+---------+
```

Changes of almost 30% are quite a lot - especially given that there is more work done than just allocating memory. Different queries (TPC-H 1 through 22) place the load on different database operators.

I tracked down the commit that caused the regression by building all commits between 5.10 and 5.20:

![jemalloc](https://user-images.githubusercontent.com/575106/68529573-6229a080-0300-11ea-962e-eb1ccbc3ca0e.png)

It looks as if the huge_threshold of 8M as introduced in https://github.com/jemalloc/jemalloc/commit/350809 is quite bad for our workload. By setting the constant to 0 in the current release, we can fix the regression.

If, as stated in the comment, this is subject to future optimization, maybe our findings can help. We allocate a couple of GBs in total. I'm not sure what information exactly would help you in understanding this, but in case you want to look into this in detail, I'll be happy to help.

I fully understand that jemalloc has to find a middle ground and that what might be good for everyone is not perfect for some users with specific performance characteristics. As such, I consider "well too bad for your workload" to be a completely valid response. ;)

**Comment by davidtgoldblatt** [comment]
Wow, that's quite a bit. Would you be able to grab some malloc_stats right with and without the huge_threshold change? I've got some suspicions about the sources (lock contention on the huge arena), that those would confirm.

**Comment by mrks** [comment]
Absolutely. Hopefully, this is what you were looking for.
* I believe it is easiest to look at single-threaded execution and just a single-query.
* I picked TPC-H 3, which shows the most significant performance regression.
* Instead of running the benchmarks for 60 seconds, I made sure that both versions run the SQL query 1000 times, so the allocations should be close to equal.
* Results for d31450 (6.82127 iter/s), 350809 (5.6201 iter/s): [Archive.zip](https://github.com/jemalloc/jemalloc/files/3836086/Archive.zip)

System was Ubuntu 19.10 with Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz and 2 TB of RAM.

Steps to reproduce on a current Mac or Ubuntu system:
* Check out https://github.com/hyrise/hyrise.git
* Remove the custom_jemalloc line from src/lib/CMakeLists.txt
* Run install.sh (which only installs prerequisites) or install dependencies manually
* Build hyriseBenchmarkTPCH
* Run `LD_PRELOAD.../d31450.so MALLOC_CONF=stats_print:true ./hyriseBenchmarkTPCH -t 999 -r 1000 -q 3`
* The performance will be printed as `> Executed 1000 times in 146.6 seconds (6.82127 iter/s, 0.1466 s/iter)`

**Comment by interwq** [comment]
Thanks for sharing the detailed info @mrks!

Looked through the stats, a few thoughts:
- the lock contention on the huge arena (`arenas[896]`) is fine; no spin / blocking on the arena level locks.
- the difference in throughput is from `madvise`: with huge_threshold set to 8M, ~5K more madvise calls were made, purging ~104G more dirty pages, average ~20M per madvise.
- the difference in memory consumption is also shown: with huge_threshold, mapped+retained (~peak VM / RSS) is ~5.9G, vs ~6.6G w/o huge_threshold.

So there is certainly tradeoff between CPU and memory (avg and peak should be lower). It's probably fair to say the 8M threshold is too conservative for the benchmark workload (changing it to 40M will "fix" for the specific benchmark).

Another thing to consider, is that the ~5K huge allocations likely happened in a bursty way, which amplifies the madvise overhead. In production workload, our observation is that the huge allocations happen way less frequent, so a lot of them got freed w/o immediate reuse, and then after a while got purged anyway (in which case the eager purging from huge_threshold didn't add actual overhead). The eager purging hurts most, when the freed huge buffer got reused immediately, which is often the pattern in benchmarks.

In the production testing we had, we didn't observe high overhead with the 8M threshold. We have rocksDB workload but the pattern is likely quite different. Depending on the workload, please feel free to try a higher threshold. I'd suggest keeping a higher value instead of disable though, say for example a 1G buffer got deallocated and it likely deserves to be returned to kernel sooner than later.

**Comment by mrks** [comment]
Got it. I believe some other databases maintain an internal buffer for these large allocations and reuse those while we return them immediately. Your explanation on why this is mostly our problem sounds reasonable. We will play around with the threshold value and see what works best.

Thanks again!

**Comment by interwq** [comment]
You are welcome! Feel free to ask if anything.
