### ISSUE TITLE
a small error in makefile.in?

### ISSUE THREAD

**Issue by xsc351072127** [jemalloc/jemalloc#1678]
https://github.com/jemalloc/jemalloc/blob/d01b425e5d1e1ed3d7f7c5571002681469acf601/Makefile.in#L421

Maybe this line should be look like this？
@if ! `cmp -s $< $@` ; then echo "cp $< $@"; cp $< $@ ; fi

I am not an obsessive. Not at all.

**Comment by interwq** [comment]
Thanks! Fixed in #1679
