### ISSUE TITLE
how to change malloc to jemalloc which is just my own code

### ISSUE THREAD

**Issue by aieinsummer** [jemalloc/jemalloc#1681]
there are many funcs in libc which used malloc ,when i use them , i dont want to cover these malloc into jemalloc,just cover the malloc into jemalloc which coded by myself,
 can jemalloc server this option when compiling?

**Comment by davidtgoldblatt** [comment]
You can pass `--with-jemalloc-prefix=my_prefix_`, and the publicly exported functions will be named `my_prefix_malloc`, `my_prefix_free`, etc.
