### ISSUE TITLE
Option --with-jemalloc-prefix does not work as expected.

### ISSUE THREAD

**Issue by XieXiating** [jemalloc/jemalloc#1701]
Hi,
I have an application and I only want to use jemalloc in some parts of my application.
So I configure jemalloc with --with-jemalloc-prefix option and name jemalloc versions something like "use_jemalloc". It really works with jemalloc versions and glibc's malloc/free API. However, new/delete API still uses jemalloc versions and the same to standard containers e.g. vector. To make sure new API indeed uses jemalloc versions, I add print in source code: jemalloc.c, je_malloc(). It actually prints.
Could it be possible to not use jemalloc's new and free? Is there something I miss to set ?

**Comment by jasone** [comment]
Add `--disable-cxx` during configuration to disable the `new/delete` wrappers.

**Comment by XieXiating** [comment]
> Add `--disable-cxx` during configuration to disable the `new/delete` wrappers.

Thank you:)
