### ISSUE TITLE
Error Cross Compilation iOS

### ISSUE THREAD

**Issue by Wizermil** [jemalloc/jemalloc#171]
Hello,

I wrote a small bash script ( [link gist](https://gist.github.com/Wizermil/1b8144e4f67511c1f7d6) ) to compile the static library for iOS but it failed for armv7, armv7s and arm64 with this error message ( [config.log](https://dl.dropboxusercontent.com/u/23130263/config.log) ):
```
configure:6384: result: no
configure:6474: checking STATIC_PAGE_SHIFT
configure:6480: error: in `/Users/wizermil/Desktop/build/jemalloc/output/armv7':
configure:6482: error: cannot run test program while cross compiling
See `config.log' for more details
```
Do you know the reason and how I could fix it?

Thanks

**Comment by jasone** [comment]
When cross compiling, you need to provide a configure cache for the values such as ```STATIC_PAGE_SHIFT``` which need to match the target.  Here is an [old mailing list email](http://www.canonware.com/pipermail/jemalloc-discuss/2011-April/000018.html) that incidentally shows how someone cross-compiled for SH4.

**Comment by myseemylife** [comment]
The link is broken~Plz help me~i came across the same issue

**Comment by jasone** [comment]
Link updated.  See also the more general documentation that was recently added in 9b94c015af7fe7f86b19c71059be8758afd06fe3.
