### ISSUE TITLE
Infinite (?) loops in je_extent_heap_remove_first

### ISSUE THREAD

**Issue by jsonn** [jemalloc/jemalloc#1721]
When using 5.1 or the last release of jemalloc in libc in NetBSD, cmake has a certain chance to trigger infinite loops in je_extent_heap_remove_first. Test case is a "make clean; make" loop e.g. in pkgsrc/archivers/karchive, it typically triggers within a few hours.

**Comment by davidtgoldblatt** [comment]
An infinite loop there is a strong indicator of a double free (or some other UB-bugs that can manifest similarly). I think running against a debug build or under an address sanitizer would be the best first step.

**Comment by interwq** [comment]
Closing but feel free to ask if anything.
