### ISSUE TITLE
Support C++17's aligned operator new

### ISSUE THREAD

**Issue by jsteemann** [jemalloc/jemalloc#1735]
C++17 introduced aligned versions of `operator new` and `operator delete`.

From https://en.cppreference.com/w/cpp/memory/new/operator_new:

> void* operator new  ( std::size_t count, std::align_val_t al); | (3) | (since C++17)
> void* operator new[]( std::size_t count, std::align_val_t al); | (4) | (since C++17)

plus their non-throwing and placement-new variants.

Similarly, alignment-aware overloads of `operator delete` are available.

From https://en.cppreference.com/w/cpp/memory/new/operator_delete:

> void operator delete  ( void* ptr, std::align_val_t al ) noexcept; | (3) | (since C++17)
> void operator delete[]( void* ptr, std::align_val_t al ) noexcept; | (4) | (since C++17)
> void operator delete  ( void* ptr, std::size_t sz,                         std::align_val_t al ) noexcept; | (7) | (since C++17)
> void operator delete[]( void* ptr, std::size_t sz,                         std::align_val_t al ) noexcept; | (8) | (since C++17)

plus their placement-delete variants.

Is there any support for handling these new operators planned in jemalloc, as there is also support for C++14's sized deallocation?
If yes, what target jemalloc release do you expect to contain it?

**Comment by davidtgoldblatt** [comment]
We have them in current `dev`, so the next release will pick them up (although, we hadn't planned on cutting a release for a while). We haven't seen very many cycles in these overloads in the workloads we look at, so it didn't seem super pressing.

**Comment by jsteemann** [comment]
From my personal point of view it is also not pressing. It only affects C++17-aware projects that make use of over-aligned types, which probably isn't too many right now :smile:

**Comment by jsteemann** [comment]
Thanks for the clarification. Will close this issue now, as the feature has already been added and will eventually be shipped.
