### ISSUE TITLE
mallctl prof.dump fails

### ISSUE THREAD

**Issue by shishirng** [jemalloc/jemalloc#175]
I have tried to use the following to dump the mem-profile for a demo program: export MALLOC_CONF="prof:true,prof_prefix:jeprof.out"

int main()
{
     int i;

```
 for (i = 0; i < 1000; i++) {
    malloc(i * 100);
 }

 const char *fileName = "heap_info.out";

 mallctl("prof.dump", NULL, NULL, &fileName, sizeof(const char *));
```

}
This fails with the following errors(no o/p:

: Invalid conf pair: prof:true

: Malformed conf string

Can some on tell me if I am doing something wrong?

**Comment by 0x007004** [comment]
I have a problem. 
If I am using the --enable-prof ， and set MALLOC_CONF=prof:false， Is there a difference with  not used --enable-prof at compile-time.

Can you tell me know

thank you
