### ISSUE TITLE
Signal SIGSEGV happened in arena_run_reg_alloc, use jemalloc version 4.1.0 on arm linux

### ISSUE THREAD

**Issue by flashtt** [jemalloc/jemalloc#1754]
I import jemalloc version 4.1.0 to arm-linux-platform.
Sometimes my code may crash in different places when calling jemalloc()， the backtrace is like: 
`pc 00049720  /system/lib/libc.so (arena_run_reg_alloc+87)`
`pc 0004b495  /system/lib/libc.so (je_arena_tcache_fill_small+100)`
`pc 0005c68b  /system/lib/libc.so (je_tcache_alloc_small_hard+18)`
`pc 00056ab7  /system/lib/libc.so (je_malloc+574)`
I can not reproduce this problem because it is occasional. 
I saw someone met the same problem but not solved it.
Is it a known issue, an application problem?

**Comment by davidtgoldblatt** [comment]
This is almost always an application problem -- the first course of action for these sorts of bugs is to try running your program under valgrind, or compiling with an address sanitizer mode.
