### ISSUE TITLE
Storing object header for every allocation by jemalloc

### ISSUE THREAD

**Issue by madaari** [jemalloc/jemalloc#1775]
Hello,

For every dynamic allocation through jemalloc, I wanted to store the size of allocation in the object header(say, in the first 4 bytes). For example, if I have to allocate 20 bytes then I will actually allocate 24 bytes and in the first four bytes I'll store the size of the object i.e. 20. Can anyone please point me to the code location where I can make this change? Perhaps, in the [malloc_default](https://github.com/jemalloc/jemalloc/blob/dev/src/jemalloc.c#L2316) function?

Here are the sample definition of malloc and free functions I want:
`void *mymalloc(size_t Size )
{
  void * objHeader = malloc(Size+4);
  *((int *)objHeader) = Size;
  return (void*)(((char*)objHeader)+4);
}`
`void myfree(void *ptr)
{
  free( (void*)( ((char*)(ptr)) - 4 ) );
}` 

Thanks.

**Comment by jasone** [comment]
You don't need to do this, because jemalloc can efficiently tell you the allocation size via `sallocx()` or `malloc_usable_size()`.  You're almost certainly better off using these functions rather than bloating your data structures.

**Comment by madaari** [comment]
Thanks.
