### ISSUE TITLE
Promptly return commited memory to the OS when "idle"

### ISSUE THREAD

**Issue by LifeIsStrange** [jemalloc/jemalloc#1778]
Hi!
This url
https://news.ycombinator.com/item?id=22488531 made me think about the subject:

The Java default garbage collector promptly return memory to the operating system when on idle/low activity, since Java 12. I wonder if some of their optimizations to make this possible could be transposed to jemalloc.
https://openjdk.java.net/jeps/346

Tests with a prototype in Bruno et al., section 5.5, shows that based on the real-world utilization of a Tomcat server that serves HTTP requests during the day, and is mostly idle during the night, this solution can reduce the amount of memory committed by the Java VM by 85%.

**Comment by davidtgoldblatt** [comment]
This is already sort of the way we work -- decay-based purging means that memory will tend to get returned to the OS after around 10 seconds of inactivity (on a sliding curve). Turning on background threads can ensure that this happens even if the application threads become truly idle; the background thread will wake and madvise-away free memory.

**Comment by LifeIsStrange** [comment]
Thanks for the answer!
For clarity: does this happen only when the system is idle (all processes) or on a per process basis?

**Comment by davidtgoldblatt** [comment]
It's per process -- e.g. if one application is highly active and another is mostly inactive (from a heap usage POV), the highly active one will tend to keep around more memory in an inactive-but-not-returned state. The documentation of `opt.dirty_decay_ms` and friends in the man page gives some more details.
