### ISSUE TITLE
Update to the 2015 Jason Evans talk on Jemalloc ?

### ISSUE THREAD

**Issue by karanchahal** [jemalloc/jemalloc#1785]
Hello,

I am researching memory allocators and writing a survey on them. I would love to be directed a more recent talk that details the improvements made to jemalloc from 2015 on !

Thank you for this amazing piece of work !

Best,
Karan

**Comment by davidtgoldblatt** [comment]
Unfortunately, I don't think any such talk exists. The big change has been moving to a world without chunks, which happened in late 2016 / early 2017 I think? I've also got an "internals" document in the works, but it still probably won't give the historical view.

**Comment by karanchahal** [comment]
Oh, thank you. I would love to read the "internals" doc if it is possible !

**Comment by davidtgoldblatt** [comment]
Unfortunately, it's not done yet. The PR is in https://github.com/jemalloc/jemalloc/pull/1713/, with the most recent version currently visible at: https://github.com/jemalloc/jemalloc/pull/1713/files?short_path=3fc7c0a#diff-3fc7c0a13cddc8a91969a6c4da159e7d
