### ISSUE TITLE
Any tool to analyze core dump to figure out root cause of a memory leak

### ISSUE THREAD

**Issue by worldhello126** [jemalloc/jemalloc#1789]
Guys:

I am a user of JeMalloc, we have an application which run with memory leak and slowly increase to 4GB. 

I check the wiki and looks like the way wiki proposed need to rebuild the application and release a seperate version. which is not accpetable for our scenario.

Now we have core dump., so is there some easy way I can use to analyze the core dump and figure out the statistic inforamtion of JeMalloc heap. so I can know which object is the real bad guy bring the leaking.

**Comment by xzxxzx401** [comment]
Same needs, is there any tools(maybe gdb plug-in) to analyze an coredump file to figure memory usages?

**Comment by interwq** [comment]
Unfortunately the core dump itself won't be sufficient to meaningfully debug leak. In order to find the allocations responsible for memory leaks, stack traces must be recorded (which won't happen unless profiling is enabled).

**Comment by snowolfhawk** [comment]
> Unfortunately the core dump itself won't be sufficient to meaningfully debug leak. In order to find the allocations responsible for memory leaks, stack traces must be recorded (which won't happen unless profiling is enabled).

Instead of find out the detail memory leak path and dynamic process,  sometimes we just need the distribution of all memory block, can we get it from coredump file useing jemalloc tool?
