### ISSUE TITLE
Configure jemelloc not to return memory to OS

### ISSUE THREAD

**Issue by walkerlala** [jemalloc/jemalloc#1816]
Is there any configuration such that jemelloc will not return any memory back to the OS (even after user call free()/delete)

The ideal use case would be that jemalloc reserve a large chunk of memory (e.g, 100GB) and carry out malloc/free inside that, without acquiring/returning anything to the OS.

**Comment by davidtgoldblatt** [comment]
This can be done via malloc conf settings -- you can set `dirty_decay_ms:-1` and `muzzy_decay_ms:-1` and jemalloc won't ever try to purge memory back to the OS.

**Comment by walkerlala** [comment]
@davidtgoldblatt These "decay" configurations are only valid for large memory after commit 0f552ed673b26b733a290bcac4c4d8ff4d0344e1  .  But even with this commit, if we set those configurations to -1, then after several round of malloc/free, the process will be killed by the OS (i.e., OOM). I have made sure that this process does not have memory by using a address sanitizer. But memory still go up continously and eventually OOM

**Comment by walkerlala** [comment]
Seems like there are some fragmentation issue which prevent memory from reuse if we don't purge large memory.

**Comment by walkerlala** [comment]
Is there any tool that we can print the malloc/free pattern (i.e, malloc/free/purge order) for debugging?
