### ISSUE TITLE
Set PAGES_CAN_PURGE_FORCE to false

### ISSUE THREAD

**Issue by walkerlala** [jemalloc/jemalloc#1818]
What will happen if I hijack jemalloc and set PAGES_CAN_PURGE_FORCED to false. In my profiling it seems that the `madvise(..., MADV_DONTNEED)` inside `extent_purge_forced_default()` is very time consuming. IIRC, `madvise` will not impact the correctness of the program.

So is it safe to set that variable to false so that pages_purge_forced() can be more efficient?
(there are only a few long running process on a server, so it is ok to ignore the impact on other process)

**Comment by davidtgoldblatt** [comment]
I think probably better would be to tune it to not try to purge rather than confusing it about whether or not it's purging; see the comment on the other diff.
