### ISSUE TITLE
rallocx segfault

### ISSUE THREAD

**Issue by computerquip** [jemalloc/jemalloc#182]
Apologies for lack of information ahead of time. I compiled jemalloc on a 64-bit Arch Linux setup, passing the -m32 flag in both CCFLAGS and LDFLAGS. No matter what I call rallocx with, it segfaults. 

rallocx(0, 4, MALLOCX_ALIGN(4))

is an instant segfault. Is there something wrong with the way I'm compiling the library? Please note that because I'm compiling a 32-bit application with jemalloc, I need it to accept the minimum of a 4-byte alignment. 

Thanks for any feedback.

**Comment by computerquip** [comment]
It appears to be segfaulting on line 511 of arena.h. 
If anyone could tell me what that means, it would save me so much pain and anguish. 
Thanks for future terms...

**Comment by computerquip** [comment]
This seems to be caused by mixing the standard API with the non-standard API. Apologies.

**Comment by thestinger** [comment]
@computerquip: AFAIK, mixing the standard API with the non-standard API is generally permitted.

**Comment by computerquip** [comment]
I actually wouldnt doubt if this was still an issue on the application side, however. Ill make a test case see if I can reproduce it outside of the weird environment Im using jemalloc in.

**Comment by jasone** [comment]
```rallocx()``` does not support passing a ```NULL``` pointer like ```realloc()``` does; use ```mallocx()``` instead if you don't have an existing allocation to resize.
