### ISSUE TITLE
Default value of muzzy_decay_ms in jemalloc 5.2.1?

### ISSUE THREAD

**Issue by quailty2020** [jemalloc/jemalloc#1827]
Hello world!
I read from the document http://jemalloc.net/jemalloc.3.html#opt.muzzy_decay_ms that muzzy_decay_ms should be 10000 by default. But without exporting MALLOC_CONF and with the code (partial) below
```cpp
#include <jemalloc/jemalloc.h>
...
    ssize_t dirty_decay_ms, muzzy_decay_ms;
    size_t sz = sizeof(ssize_t); 
    mallctl("opt.dirty_decay_ms", reinterpret_cast<void*>(&dirty_decay_ms), &sz, NULL, 0);
    mallctl("opt.muzzy_decay_ms", reinterpret_cast<void*>(&muzzy_decay_ms), &sz, NULL, 0);
    ERROR("[jemalloc] dirty_decay_ms %lld muzzy_decay_ms %lld", 
            static_cast<long long>(dirty_decay_ms), static_cast<long long>(muzzy_decay_ms));
```
I get the log
`2020-04-22 23:32:02,964 ERROR 0x7f23a31ec100 [jemalloc] dirty_decay_ms 10000 muzzy_decay_ms 0`
with jemalloc 5.2.1 and the log
`2020-04-22 23:43:33,488 ERROR 0x7f18e90cf0c0 [jemalloc] dirty_decay_ms 10000 muzzy_decay_ms 10000`
with jemalloc 5.1.0.
It seems the result can be reproduced on several machines, and I wonder whether the result meets the expectation.
Thank you!

**Comment by quailty2020** [comment]
Well, I find this commit https://github.com/jemalloc/jemalloc/commit/8e9a613122251d4c519059f8e1e11f27f6572b4c#diff-8b2454020c4b9e5d639c17ae61ab4b76
But I wonder why setting muzzy_decay_ms to 0 by default, since I have an issue that the memory keep rising without slowing down when filling cache and fixed by setting muzzy_decay_ms to 10000.
![image](https://user-images.githubusercontent.com/59469343/80009098-2fb0e000-84fb-11ea-8472-3635bfc6c7b2.png)
![image](https://user-images.githubusercontent.com/59469343/80009157-41928300-84fb-11ea-9c5f-324512388bbc.png)
(Inc related info has been erased)

**Comment by davidtgoldblatt** [comment]
The documentation is out of date; we set muzzy decay to 0 by default starting in 5.2.1 (to match the production configurations we have the most experience with; where it tends to save memory). It's surprising to me that turning on muzzy decay would save memory; I can't think of any reason this might be the case. It seems as though it should be better both directly (we MADV_DONTNEED it instead of MADV_FREEing it when muzzy is off), and in terms of fragmentation avoidance.

**Comment by quailty2020** [comment]
> The documentation is out of date; we set muzzy decay to 0 by default starting in 5.2.1 (to match the production configurations we have the most experience with; where it tends to save memory). It's surprising to me that turning on muzzy decay would save memory; I can't think of any reason this might be the case. It seems as though it should be better both directly (we MADV_DONTNEED it instead of MADV_FREEing it when muzzy is off), and in terms of fragmentation avoidance.

Thank you for your reply.
Only a few machines of the whole cluster meet the issue mentioned above, and these machines are "similar" (i.e. with the same kernal version). Maybe MADV_DONTNEED does not work properly due to some potential kernal bugs on these machines.
I think it is hard to verify but if I get the result I will share it later.

**Comment by quailty2020** [comment]
Refer to https://github.com/jemalloc/jemalloc/issues/1674, I find the thp config (/sys/kernel/mm/transparent_hugepage) is "always" on the machine with the issue, and I switch it to "madvise" and also fix the issue.

**Comment by orlp** [comment]
Why was this issue closed without a PR to update the documentation to mention the new default?
