### ISSUE TITLE
32-bit compiling on a 64-bit system, Linux

### ISSUE THREAD

**Issue by computerquip** [jemalloc/jemalloc#183]
There wasn't anything in the docs so I added -m32 to both the CFLAGS and LDFLAGS at configure time. It seems to have compiled fine although I'm not sure of any possible side effects. Is this a viable way of compiling the library?

**Comment by jasone** [comment]
jemalloc supports 32-bit systems, so as long as the toolchain operates properly, there should be no unwanted side effects to compiling a 32-bit version of jemalloc for use in 32-bit applications running on 64-bit systems.  As for the details of whether ```-m32``` is sufficient, I don't know off the top of my head.
