### ISSUE TITLE
why sallocx need a flags parameter when calling?

### ISSUE THREAD

**Issue by dm0619** [jemalloc/jemalloc#1834]
actually, I have several related questions to ask.
1）the 'flags' parameter is not used in sallocx, but it is in the function declaration. is it plan to be used in future? 
2)  is there any difference between sallocx and malloc_usable_size, can I use malloc_usable_size instead of sallocx?
3)  I want to record some meta information at the end of each allocation, and then locate this meta information from the allocated pointer. this is not for debug purpose, means I need a fast and stable way to do it. let's say, the meta information occupy 64 bytes, can I located it by doing:
ptr = malloc(allocbytes + 64);
metaptr = malloc_usable_size(ptr) - 64;

or I must(or better) do like this:
ptr = malloc( nallocx(allocbytes + 64) )
metaptr = malloc_usable_size(ptr) - 64;

thanks for you helps

**Comment by davidtgoldblatt** [comment]
> 1）the 'flags' parameter is not used in sallocx, but it is in the function declaration. is it plan to be used in future?

We don't have any short-term plans to. You could imagine some sort of flags parameter that would allow it to start being useful, though.

> 2) is there any difference between sallocx and malloc_usable_size, can I use malloc_usable_size instead of sallocx?

There's no real difference. Philosophically, sallocx is part of jemalloc, while malloc_usable_size is part of our emulation of the system allocator.

> 3) I want to record some meta information at the end of each allocation, [...]

Either of those should be fine. `nallocx` is an API guarantee, so you can use it in place of malloc_usable_size and avoid the cost of an extra lookup if you know the size (i.e. `ptr = malloc(allocbytes + 64); metaptr = ptr + nallocx(allocbytes + 64) - 64`. (Of course, be careful about alignment of your metadata).
