### ISSUE TITLE
Is it possible to disable DSS and sbrk?

### ISSUE THREAD

**Issue by andronat** [jemalloc/jemalloc#1836]
Hello, I would like to initialize jemalloc completely with mmap and avoid any use of sbrk/brk. The only way I managed to make this work is by manually editing `configure.ac`. Is there a reason there is no runtime or compile time option to disable DSS? Is there a reason sbrk/brk are the preferred mechanism and thus I might shoot myself in the foot if I bypass it?

**Comment by davidtgoldblatt** [comment]
This is a runtime configuration option, too; setting "dss:disabled" will prevent using it.

> Is there a reason sbrk/brk are the preferred mechanism and thus I might shoot myself in the foot if I bypass it?

**Comment by andronat** [comment]
Thanks for the response! I actually build jemalloc with `--with-malloc-conf=dss:disabled` but when I run an `strace` I can actually see some `brk` calls. Through GDB I found the following:
```
#0  0x00007ffff76d74b9 in __brk (addr=addr@entry=0x0) at ../sysdeps/unix/sysv/linux/x86_64/brk.c:31
#1  0x00007ffff76d7548 in __GI___sbrk (increment=increment@entry=0) at sbrk.c:41
#2  0x00005555555ac69b in extent_dss_sbrk (increment=0) at src/extent_dss.c:44
#3  je_extent_dss_boot () at src/extent_dss.c:265
#4  0x00005555555abc0d in je_extent_boot () at src/extent.c:2330
#5  0x0000555555565340 in malloc_init_hard_a0_locked () at src/jemalloc.c:1524
#6  0x000055555556559b in malloc_init_hard () at src/jemalloc.c:1750
#7  0x00005555555dcfad in __libc_csu_init ()
#8  0x00007ffff75e2b28 in __libc_start_main (main=0x55555555aeca <main>, argc=3, argv=0x7fffffffe398, init=0x5555555dcf60 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe388) at ../csu/libc-start.c:266
#9  0x000055555555adea in _start ()
```

During configuring I can see that the options are passed properly:
```
...
CONFIG             : --prefix=/home/vagrant/project/build/jemalloc/install --disable-initial-exec-tls --with-malloc-conf=dss:disabled
...
malloc_conf        : dss:disabled
```

Is this normal behavior?

**Comment by davidtgoldblatt** [comment]
Yes -- note that increment is zero there (i.e. we're not actually allocating at all; just reading the data segment begin address). We grab this at boot since, even if dss is disabled by default, it might be turned on later via the mallctl interface.

**Comment by andronat** [comment]
Got it! Thanks for the explanation!
