### ISSUE TITLE
Infinite loop involving a0malloc

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#184]
When switching firefox to what essentially is current jemalloc dev, we hit a case where we got into an infinite loop on mac and windows with a call stack involving a0malloc.

The call stack looks like this:
je_a0malloc -> a0alloc -> je_arena_malloc -> je_arena_malloc_small -> arena_bin_malloc_hard -> arena_bin_nonfull_run_get -> arena_run_alloc_small -> arena_chunk_alloc -> arena_chunk_init_hard -> arena_chunk_alloc_internal -> je_chunk_alloc_arena -> je_chunk_alloc_default -> je_tsd_wrapper_get -> je_malloc_tsd_malloc -> je_a0malloc -> (repeat)

AIUI, this happens in the rare case where a0malloc is called at a moment when the arena cannot fulfill that allocation without allocating another chunk, which itself requires tsd allocation, which requires a0malloc.

This is a cousin of what was fixed in 9b75677e538836b284a0d26a593963187c24a153. That is, the reason that tsd_fetch was removed still exists, but in the arena_malloc code path, there is another tsd_fetch that can happen.

This may be related to issue #170.

**Comment by jasone** [comment]
I'll make sure this is fixed at the same time as #170.

**Comment by glandium** [comment]
I could reproduce with current jemalloc dev branch with the following source code, on linux x86-64 with --disable-tls:
```c
#include <malloc.h>
#include <pthread.h>

const char* malloc_conf = "tcache:false";

void* func(void* data) {
  malloc(128);
}

int main(void) {
  int i;
  pthread_t t;
  for (i = 0; i < 512; i++) {
    malloc(8);
  }
  malloc(272);
  for (i = 0; i < 31743; i++) {
    malloc(128);
  }
  pthread_create(&t, NULL, &func, NULL);
  pthread_join(t, NULL);
  return 0;
}
```

**Comment by glandium** [comment]
So, this all comes down to the fact that despite we have the arena_t*, when calling chunk_alloc_arena, we give it the arena index, which is the used with arena_get (which uses the tsd), to get back the arena_t* we already had. This, I guess, is necessary for chunk_alloc overrides not to have access to the arena_t. OTOH, can chunk_alloc overrides actually do anything useful with that arena index?

chunk_alloc_default uses it, but that's because it is internal and actually can use arena_get to make it useful. But, the only reason it needs the arena is to get to arena->dss_prec, in order to give it to chunk_alloc_core, which doesn't use it unless have_dss is set. Not getting the arena when have_dss is false would already fix the issue on Windows, which doesn't have sbrk, and mac, where it is disabled manually. That leaves Android, which I hadn't mentioned, but that theoretically has the same problem, since it doesn't have tls (although i think recent versions do have a limited support for it, but you can't support older versions if you use that).

So the following patch should work around it on some platforms:

```diff
diff --git a/src/chunk.c b/src/chunk.c
index 7926452..32e659c 100644
--- a/src/chunk.c
+++ b/src/chunk.c
@@ -252,17 +252,22 @@ void *
 chunk_alloc_default(void *new_addr, size_t size, size_t alignment, bool *zero,
     unsigned arena_ind)
 {
-       arena_t *arena;
+       dss_prec_t dss_prec = dss_prec_disabled;
 
-       arena = arena_get(tsd_fetch(), arena_ind, false, true);
-       /*
-        * The arena we're allocating on behalf of must have been initialized
-        * already.
-        */
-       assert(arena != NULL);
+       if (have_dss) {
+               arena_t *arena;
+
+               arena = arena_get(tsd_fetch(), arena_ind, false, true);
+               /*
+                * The arena we're allocating on behalf of must have been
+                * initialized already.
+                */
+               assert(arena != NULL);
+               dss_prec = arena->dss_prec;
+       }
 
        return (chunk_alloc_core(new_addr, size, alignment, false, zero,
-           arena->dss_prec));
+           dss_prec));
 }
 
 static void
```

**Comment by jasone** [comment]
How about this diff?  As an aside, unfortunately #170 looks like it's different (and harder to fix) than the issue here.

```diff
diff --git a/src/chunk.c b/src/chunk.c
index 7926452..b9a2441 100644
--- a/src/chunk.c
+++ b/src/chunk.c
@@ -254,7 +254,9 @@ chunk_alloc_default(void *new_addr, size_t size, size_t alignment, bool *zero,
 {
        arena_t *arena;

-       arena = arena_get(tsd_fetch(), arena_ind, false, true);
+       /* Dodge tsd for a0 in order to avoid bootstrapping issues. */
+       arena = (arena_ind == 0) ? a0get() : arena_get(tsd_fetch(), arena_ind,
+            false, true);
        /*
         * The arena we're allocating on behalf of must have been initialized
         * already.
```

**Comment by glandium** [comment]
That would work too, but I think we should do both (that is, just have the compiler remove that code entirely when dss is disabled)

**Comment by jasone** [comment]
If this were a hot code path I'd agree, but it's not very hot and optimizing the code adds a maintenance burden that doesn't seem worthwhile to me.

**Comment by jasone** [comment]
Thanks for diagnosing this bug!
