### ISSUE TITLE
Why would je_calloc not return zero-initialized memory?

### ISSUE THREAD

**Issue by goffioul** [jemalloc/jemalloc#1844]
I'm working on a ARM-to-x86 translation layer for android-x86 [1], and I'm facing a really odd behavior whereby je_calloc in the emulated layer returns memory that is not zero-initialized.

The code is based on AOSP/Android-Q, which uses jemalloc from here [2]. The emulation layer is based on QEMU, which operates in user mode, with a minimal ARM-compiled runtime environment and a set of interface libraries that bridge the emulated environment and the native Android OS.

Maybe of importance is that there are 2 versions of jemalloc operating at the same time:
- the regular Android native jemalloc (x86)
- the jemalloc version in the emulated runtime environment (arm)

I've been tracking a series of crashes that all point to the same root cause: at some point during the execution, the emulated code performs a `calloc` call, but the returned memory is not fully zero-initialized. I've patched libc.so (in the emulated environment) with the following snippet to verify it.

```
--- a/libc/bionic/malloc_common.cpp
+++ b/libc/bionic/malloc_common.cpp
@@ -67,10 +67,19 @@ extern "C" void* calloc(size_t n_elements, size_t elem_size) {
   if (__predict_false(result == nullptr)) {
     warning_log("calloc(%zu, %zu) failed: returning null pointer", n_elements, elem_size);
   }
+  for (size_t i = 0; i < (n_elements * elem_size); i++) {
+    if (((char*)result)[i] != 0) {
+      warning_log("calloc(%zu, %zu): %p byte %zu is not zero!!! [calloc=%p]", n_elements, elem_size, result, i, Malloc(calloc));
+      break;
+    }
+  }
   return result;
 }
```

I would appreciate if you could help me understand in what circumstances such behavior could ever happen?

[1] https://github.com/goffioul/ax86-nb-qemu
[2] https://android.googlesource.com/platform/external/jemalloc_new/+/refs/tags/android-10.0.0_r2

**Comment by davidtgoldblatt** [comment]
It's hard to say without a little bit more info. Could you print the sizes of the allocations that are failing? Small and large allocations get zeroed at different places.

My best guess right now is that something about the unusual environment might be making some of the configuration go a little screwy. We assume that certain system calls (e.g. madvise with the right flags) will zero memory. One way you could check this would be to instrument ehooks_zero (in ehooks.h) to do the zero-checking as well.

**Comment by goffioul** [comment]
This is the `calloc` call that is failing (print using the patch snippet posted previously):
```
calloc(20366, 4): 0xc19ab000 byte 836 is not zero!!! [calloc=0xc8710dd5]
```

**Comment by goffioul** [comment]
The jemalloc version used in AOSP doesn't have ehooks_zero. However, youre reference to madvise made me look at the syscall implementation in QEMU usermode:

https://github.com/qemu/qemu/blob/master/linux-user/syscall.c#L11325

It doesn't look like it's actually implemented. Is there a way to make jemalloc not make use of madvise for zeroing memory? Could the lack of madvise implementation have other side effects in jemalloc?

**Comment by davidtgoldblatt** [comment]
Ah, yep, that'd do it. If we detect that we're running on an OS where madviseing-away zeroes memory, but the actual hooks that get invoked don't do it, we'll incorrectly track zero state. I think this is a qemu bug if it's trying to emulate linux; MADV_DONTNEED demand-zeroes anonymous mappings after a successful MADV_DONTNEED as an API guarantee.

> Is there a way to make jemalloc not make use of madvise for zeroing memory?

Changing the implementation of pages_purge_forced to do a memset will work I think.

> Could the lack of madvise implementation have other side effects in jemalloc?

We won't end up returning memory to the OS if madvise is a no-op, under our default linux configurations. My guess is that it's not a big deal for simulation stuff, but I wouldn't want to run workloads I really cared about under these circumstances.

**Comment by goffioul** [comment]
For reference, I asked the question to QEMU devs and here's the answer:
https://lists.nongnu.org/archive/html/qemu-devel/2020-05/msg03119.html
