### ISSUE TITLE
Tracking the peak memory used by individual threads ?

### ISSUE THREAD

**Issue by fwyzard** [jemalloc/jemalloc#1850]
Hi,
I would be interested in resurrecting the idea discussed in #1176, that is, implement the possibility of measuring the peak memory usage within a section of code that is running on a single task.

From #1176:

> In the context of profiling a modular application, I am interested in the peak memory used by each thread, within each module. Here "module" could be a function call, a TBB task, _etc._ that is going to run within a given thread.
> 
> Something like
>   - at the begin of each module, check the memory usage and reset the peak value;
>   - while the module is running, track each memory allocation and deallocation and update the peak memory usage accordingly;
>   - at the end of the module, read the peak memory usage.
> 
> `jemalloc` can already track each allocation and deallocation; if we define the "memory usage" as "allocated memory - deallocated memory" (and let the client code take care of the offset) a possible solution is to add one more field to the `tsd` and track the peak "allocated - deallocated memory".

On the other hand, I see that the relevant code has seen quite some changes after jemalloc `5.2.1`.

Answering to #1176 
  - @interwq [mentioned](https://github.com/jemalloc/jemalloc/pull/1176#issuecomment-381698379) allocation hooks as a coming experimental feature. Did that happen ? Is it something I can try to use for this ?
  - @jasone [mentioned](https://github.com/jemalloc/jemalloc/pull/1176#issuecomment-382070521) the possibility of implementing a different approach based on thread heap profiling. Is that still a viable option ?  If yes, could you share some pointers of where to start looking for trying to implement it ?

Thanks,
.Andrea

**Comment by davidtgoldblatt** [comment]
I think https://github.com/jemalloc/jemalloc/pull/1853 should solve this issue accurately enough for most reasonable use cases without forcing the allocation fast path to maintain extra tracking state.

**Comment by fwyzard** [comment]
Thanks @davidtgoldblatt , that looks pretty interesting, and should cover our use case.
