### ISSUE TITLE
Why stats.active grows a lot than stats.allocated when reading large file?

### ISSUE THREAD

**Issue by xuefei199288** [jemalloc/jemalloc#1870]
I'm running jemalloc 5.2.1 on Linux with default configure. My program will load large files to memory's lru data structure. But i found my program's memfree will descend quickly and rise a little later, i print stats parameter over a period of time and found stats.allocated/stats.metadata/stats.metadata_thp always remain unchanged but stats.active/stats.resident/stats.mapped/stats.retained grows a lot. 
I cannot figure out why this happen. I have tried some MALLOC_CONF like backgroup_thread:true/dirty_decay_ms:0/muzzy_decay_ms:0/thread.tcache.flush, but it does not work.

I0622 17:01:35.801857 69326 stats.allocated:156084777552 stats.active:157145034752 stats.metadata:3906964512 stats.metadata_thp:0 stats.resident:161025740800ned:18725597184
I0622 17:06:49.900040 69326 stats.allocated:128970215296 stats.active:153585889280 stats.metadata:4220104320 stats.metadata_thp:0 stats.resident:157856608256ned:53346291712
I0622 17:08:25.742754 69326 stats.allocated:131039768920 stats.active:156026490880 stats.metadata:4229887616 stats.metadata_thp:0 stats.resident:160313528320ned:54388813824
I0622 17:09:25.750432 69326 stats.allocated:132276164312 stats.active:157334544384 stats.metadata:4234438560 stats.metadata_thp:0 stats.resident:161641312256ned:55213035520
I0622 17:10:25.759804 69326 stats.allocated:133537333448 stats.active:158607663104 stats.metadata:4238864160 stats.metadata_thp:0 stats.resident:162919481344ned:53939294208
I0622 17:11:25.770347 69326 stats.allocated:134710062832 stats.active:159611854848 stats.metadata:4247615008 stats.metadata_thp:0 stats.resident:163895066624ned:56730554368
I0622 17:12:25.786738 69326 stats.allocated:135376164424 stats.active:160316366848 stats.metadata:4248041760 stats.metadata_thp:0 stats.resident:165261426688ned:55364624384
I0622 17:13:25.796519 69326 stats.allocated:135317446512 stats.active:160275845120 stats.metadata:4252536992 stats.metadata_thp:0 stats.resident:164628389888ned:56002154496
I0622 17:14:25.804558 69326 stats.allocated:135325174592 stats.active:160289476608 stats.metadata:4252709024 stats.metadata_thp:0 stats.resident:164675764224ned:55954952192
I0622 17:18:19.400718 69326 stats.allocated:191747075808 stats.active:227507175424 stats.metadata:6140827344 stats.metadata_thp:0 stats.resident:233817993216ned:59836014592
I0622 17:19:19.406584 69326 stats.allocated:189481553760 stats.active:225247088640 stats.metadata:6150340176 stats.metadata_thp:0 stats.resident:231514816512ned:66980769792
I0622 17:20:19.413375 69326 stats.allocated:189571935040 stats.active:225320570880 stats.metadata:6152652240 stats.metadata_thp:0 stats.resident:231567732736ned:66930163712
I0622 17:21:19.418936 69326 stats.allocated:189596443312 stats.active:225185615872 stats.metadata:6154095696 stats.metadata_thp:0 stats.resident:231422136320ned:67077201920
I0622 17:24:42.956148 69326 stats.allocated:134912042992 stats.active:192590483456 stats.metadata:6160469328 stats.metadata_thp:0 stats.resident:198876786688ned:101776408576
I0622 17:25:42.962345 69326 stats.allocated:135016386600 stats.active:192665059328 stats.metadata:6160469328 stats.metadata_thp:0 stats.resident:198899408896ned:101753786368
I0622 17:27:12.748889 69326 stats.allocated:135124450400 stats.active:190965923840 stats.metadata:6162566480 stats.metadata_thp:0 stats.resident:197228699648ned:106110947328
I0622 17:28:12.756047 69326 stats.allocated:135134445128 stats.active:190976196608 stats.metadata:6162566480 stats.metadata_thp:0 stats.resident:197266755584ned:106072891392
I0622 17:29:12.766342 69326 stats.allocated:134189509992 stats.active:188884099072 stats.metadata:6162566480 stats.metadata_thp:0 stats.resident:195200720896ned:108138926080
I0622 17:30:42.993269 69326 stats.allocated:135297526080 stats.active:190237822976 stats.metadata:6162566480 stats.metadata_thp:0 stats.resident:196507987968ned:106831659008
I0622 17:31:43.001663 69326 stats.allocated:135284695104 stats.active:190083932160 stats.metadata:6162566480 stats.metadata_thp:0 stats.resident:196346429440ned:106993217536
I0622 17:32:43.007750 69326 stats.allocated:135310274512 stats.active:190111465472 stats.metadata:6162566480 stats.metadata_thp:0 stats.resident:196368240640ned:106971406336
I0622 17:33:43.015722 69326 stats.allocated:135291520992 stats.active:190095785984 stats.metadata:6164663632 stats.metadata_thp:0 stats.resident:196373897216ned:106967846912
I0622 17:35:16.610370 69326 stats.allocated:135387625712 stats.active:188931133440 stats.metadata:6164663632 stats.metadata_thp:0 stats.resident:196832845824ned:106508898304

Anyone has meet this problem?

**Comment by davidtgoldblatt** [comment]
One possible explanation is simply fragmentation -- it looks like resident memory and metadata do indeed stabilize over time, so it's possible that the peak memory just exceeds non-peak memory, but is hanging onto pages with memory active in them.

One way to check this theory would be to look at bin utilization over time in the malloc stats.

**Comment by davidtgoldblatt** [comment]
Closing for now, but feel free to reopen if there are more questions.
