### ISSUE TITLE
[Question] build jemalloc v5.2.1

### ISSUE THREAD

**Issue by wpc062** [jemalloc/jemalloc#1871]
I'm trying to compile jemalloc v5.2.1. But I find it's compiled with option "-g3". E.g.
```
gcc -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -fPIC -DPIC -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/jemalloc.sym.o src/jemalloc.c
```
I ran the configure command as below:
```
$ ./configure --enable-prof --enable-munmap --enable-tls --with-jemalloc-prefix=je_   CFLAGS='-std=gnu99 -Wall -pipe -O3 -funroll-loops'

$ grep CFLAGS Makefile
CONFIGURE_CFLAGS := -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops
SPECIFIED_CFLAGS := -std=gnu99 -Wall -pipe -O3 -funroll-loops
EXTRA_CFLAGS := 
CFLAGS := $(strip $(CONFIGURE_CFLAGS) $(SPECIFIED_CFLAGS) $(EXTRA_CFLAGS))
PIC_CFLAGS = -fPIC -DPIC
ifdef PIC_CFLAGS
$(C_PIC_OBJS): CFLAGS += $(PIC_CFLAGS)
$(CPP_PIC_OBJS): CXXFLAGS += $(PIC_CFLAGS)
	$(CC) $(CFLAGS) -c $(CPPFLAGS) $(CTARGET) $<
$(objroot)lib/$(LIBJEMALLOC).$(SOREV) : $(if $(PIC_CFLAGS),$(C_PIC_OBJS),$(C_OBJS)) $(if $(PIC_CFLAGS),$(CPP_PIC_OBJS),$(CPP_OBJS))

```
How can I get rid of it?

Thanks,

**Comment by davidtgoldblatt** [comment]
Putting -g0 in cflags should have the same affect as not specifying -g3 (following the usual rule that later flags overwrite settings of earlier ones).

Why do you want to? Ordinarily you'd strip at link time I would think.

**Comment by wpc062** [comment]
@davidtgoldblatt ,
Thanks for your response. putting -g0 in CFLAGS works. But I'm still wondering why -g3 is set by default.
To me, it's a little unreasonable since I didn't enable debugging.
PS: I never met this problem when using old release of jemalloc such as v3.6.0.

**Comment by davidtgoldblatt** [comment]
I'm not sure -- setting `-g3` has been there since b7924f50c02be555a445771e7bd51209250a5d52, 11 years (and two days) ago; the difference is that we went to adding in the user CFLAGS rather than replacing them (around 4 years ago).

I don't know the historical reason why, but including that sort of information can be invaluable in figuring out crashes in optimized binaries; it gives a little bit of a sense of what operation the misbehaving binary was doing.

**Comment by wpc062** [comment]
Thanks for your answer.
