### ISSUE TITLE
used by LD_PRELOAD ,and errno change to EBUSY 

### ISSUE THREAD

**Issue by aieinsummer** [jemalloc/jemalloc#1873]
i used jemalloc.so by LD_PRELOAD,when process stared the errno must changed to 16(EBUSY) ，is it unusual?

**Comment by davidtgoldblatt** [comment]
I don't totally follow -- in general I would only expect errnos out of failed malloc attempts (rare on modern systems given reasonable allocation sizes) or invalid mallctl parameters. We shouldn't in general change the errors reported outside of malloc.

**Comment by aieinsummer** [comment]
> I don't totally follow -- in general I would only expect errnos out of failed malloc attempts (rare on modern systems given reasonable allocation sizes) or invalid mallctl parameters. We shouldn't in general change the errors reported outside of malloc.

will stable3/stable branch provide more stable servise? 
is there any difierrent on function between 4.5 and 5.2 ?

**Comment by davidtgoldblatt** [comment]
Right -- 5.2.1 is the maintained branch of jemalloc.
