### ISSUE TITLE
is 5.21 a stable branch ?

### ISSUE THREAD

**Issue by aieinsummer** [jemalloc/jemalloc#1877]
i saw the stable branch is 4.5 from 3years ago ,is 5.2.1 stable ？I use 5.2.1 and sometimes found some malloc core

**Comment by davidtgoldblatt** [comment]
Yes, 5.2.1 is the current stable branch. We don't have any known open correctness bugs in it; the usual cause of cores within malloc is some sort of application-induced heap corruption. Things like valgrind or address sanitizer will often do a good job of tracking down such issues.

Closing for now, but feel free to reopen if something starts pointing to a jemalloc bug.
