### ISSUE TITLE
extent_split_impl do not set lead extent slab bit.

### ISSUE THREAD

**Issue by xsc351072127** [jemalloc/jemalloc#1880]
https://github.com/jemalloc/jemalloc/blob/ea6b3e973b477b8061e0076bb257dbd7f3faa756/src/extent.c#L2154
Why do not call extent_slab_get to set lead extetnt slab bit in the function extent_split_impl?
I review the code but something confuse me for function extent_split_impl. Where call extent_rtree_write_acquired to set lead extent szind and slab in rtree but do not set  slab bit in extent_t. Someting wrong with my comprehension?

**Comment by xsc351072127** [comment]
https://github.com/jemalloc/jemalloc/blob/ea6b3e973b477b8061e0076bb257dbd7f3faa756/src/extent.c#L1038
By the way.in the function extent_split_interior not only cause szind

**Comment by davidtgoldblatt** [comment]
> Why do not call extent_slab_get to set lead extetnt slab bit in the function extent_split_impl?

extent_split_impl is only called when we're trying to reuse a currently inactive extent, and inactive extents are never slabs. (Slab extents are extents that have been broken up to serve small user allocations on them, and always hold at least one user allocation).

> Where call extent_rtree_write_acquired to set lead extent szind and slab in rtree but do not set slab bit in extent_t. Someting wrong with my comprehension?

>1.In the function extent_split_interior not only cause szind to be set as side effect. When leadsize!=0 the return extent slab flag was set also.

Sorry, I don't completely understand. In general, we'll pick the lead extent to return for an extent we have to split, and so only bother setting its data. The trail extent remains inactive, and so doesn't need the active-only pieces of metadata to be initialized.

> 2.If a recycle call to change a slab extent extern_record in extents to a large extent. In extent_record only do extent_slab_set and extent_interior_deregister. The 'if' condition 'slab &&' leave the wrong slab flag and szind flag in the laster rtree elm of a large extent.

This is true, but mostly fine; we don't care about the values of those items while the associated extents are inactive. It's only while we're resetting them that we need to be careful.

**Comment by xsc351072127** [comment]
> > 1.In the function extent_split_interior not only cause szind to be set as side effect. When leadsize!=0 the return extent slab flag was set also.
> 
> Sorry, I don't completely understand. In general, we'll pick the lead extent to return for an extent we have to split, and so only bother setting its data. The trail extent remains inactive, and so doesn't need the active-only pieces of metadata to be initialized.
> May be I still think this can be a issue. But let's talk about it later. I agree with you this won't be a problem right now.
> > 2.If a recycle call to change a slab extent extern_record in extents to a large extent. In extent_record only do extent_slab_set and extent_interior_deregister. The 'if' condition 'slab &&' leave the wrong slab flag and szind flag in the laster rtree elm of a large extent.
> 
> This is true, but mostly fine; we don't care about the values of those items while the associated extents are inactive. It's only while we're resetting them that we need to be careful.
> This may occur memory fragmentation. 
https://github.com/jemalloc/jemalloc/blob/ea6b3e973b477b8061e0076bb257dbd7f3faa756/src/extent.c#L1722
https://github.com/jemalloc/jemalloc/blob/ea6b3e973b477b8061e0076bb257dbd7f3faa756/src/extent.c#L1680
https://github.com/jemalloc/jemalloc/blob/ea6b3e973b477b8061e0076bb257dbd7f3faa756/src/extent.c#L1644

**Comment by xsc351072127** [comment]
> > Why do not call extent_slab_get to set lead extetnt slab bit in the function extent_split_impl?
> 
> extent_split_impl is only called when we're trying to reuse a currently inactive extent, and inactive extents are never slabs. (Slab extents are extents that have been broken up to serve small user allocations on them, and always hold at least one user allocation).
> 
> > Where call extent_rtree_write_acquired to set lead extent szind and slab in rtree but do not set slab bit in extent_t. Someting wrong with my comprehension?
> 
> > 1.In the function extent_split_interior not only cause szind to be set as side effect. When leadsize!=0 the return extent slab flag was set also.
> 
> Sorry, I don't completely understand. In general, we'll pick the lead extent to return for an extent we have to split, and so only bother setting its data. The trail extent remains inactive, and so doesn't need the active-only pieces of metadata to be initialized.
> 

Although I think this is still an issue,  but let's talk about it later.  I agree with you, It's not going to be a problem right now.

> > 2.If a recycle call to change a slab extent extern_record in extents to a large extent. In extent_record only do extent_slab_set and extent_interior_deregister. The 'if' condition 'slab &&' leave the wrong slab flag and szind flag in the laster rtree elm of a large extent.
> 
> This is true, but mostly fine; we don't care about the values of those items while the associated extents are inactive. It's only while we're resetting them that we need to be careful.

This may cause memory fragmentation.  In the extent_try_coalesce_large only check neighbouring extent which it's rtree elm slab flag not be set. May be a extent can not got coalesce beacuse it's "prev" extent have a wrong  slab flag.
