### ISSUE TITLE
the difference between stats.mapped and stats.resident

### ISSUE THREAD

**Issue by zct** [jemalloc/jemalloc#1882]
I'm reading the  jemalloc man page at http://jemalloc.net/jemalloc.3.html. In the print stat information,  stats.resident may be he pages that we act as if are backed by physical pages. But what the stats.mapped meaning?  From the follow document, I can't understand the meanings

> Total number of bytes in active extents mapped by the allocator. This is larger than stats.active. This does not include inactive extents, even those that contain unused dirty pages, which means that there is no strict ordering between this and stats.resident.

In my test program, I found the stats.mapped is greater than stats.resident:

active:                      61476864
mapped:                      74059776
retained:                     4583424
base:                        11739600
internal:                       28680
metadata_thp:                       0
tcache_bytes:                       0
resident:                    73220096
abandoned_vm:                       0
extent_avail:                       0

**Comment by davidtgoldblatt** [comment]
Mapped is the sum of regions of virtual address space currently dedicated (internally) to serving some live allocation. Some of those regions have pages we are reasonably confident have not been demand-paged in yet; these count towards mapped, but not resident. Some pages have been touched by user code and then freed, but not yet returned to the OS (we're keeping them around under the hope that we'll be able to serve another allocation out of them soon). These pages don't hold any allocations on them, so they don't count towards mapped; they do however count towards resident.

Does that make sense? Sorry; I know the relationship between these is not terribly well documented.

**Comment by zct** [comment]
I got it. thanks for your nice reply.
