### ISSUE TITLE
default thread and valgrind memleak

### ISSUE THREAD

**Issue by robambalu** [jemalloc/jemalloc#1884]
We recently upgraded our pyarrow version, the newer version pulls in jemalloc libraries and we noticed the following issues.
1) a "jemalloc_bg_thd" thread is spawned on dlinit before we ever hit main
2) all our apps are now hitting valgrind leak warnings due to a (potential) leak in jemalloc code:
==33515== 656 bytes in 1 blocks are possibly lost in loss record 1 of 1
==33515== at 0x402E9EA: calloc (vg_replace_malloc.c:752)
==33515== by 0x4011F44: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==33515== by 0x5DFF9C0: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==33515== by 0x589186B: je_arrow_private_je_pthread_create_wrapper (background_thread.c:48)
==33515== by 0x589186B: background_thread_create_signals_masked (background_thread.c:365)
==33515== by 0x589186B: background_thread_create_locked (background_thread.c:573)
==33515== by 0x5891A47: je_arrow_private_je_background_thread_create (background_thread.c:598)
==33515== by 0x400F502: _dl_init (in /usr/lib64/ld-2.17.so)
==33515== by 0x40011A9: ??? (in /usr/lib64/ld-2.17.so)

valgrind is an FYI we can always suppress that in our valgrind runs, but you may want to clean it up.
The default thread is a bit of a nuisance.  We link in pyarrow into one of our core libraries which is linked into pretty much all of our applications.  Now every application that we run automatically has a jemalloc-bg_thd in it even if arrow isnt used in the process at all.  
It would be appreciated if this thread can be changed to spawn on first use.  Note i originally posted this to the arrow project but they deferred my to post into jemalloc directly.

Thanks
- Rob

**Comment by davidtgoldblatt** [comment]
Background threads are off by default in the standard configuration; probably either arrow or something in the runtime environment is configured to turn them on by default. You can probably track down where this config option is getting set and flip it back.

**Comment by robambalu** [comment]
I did find the config option being set in arrow code, and I can’t control that. I assume they have good reason for using jemalloc and for enabling the background thread, my issue is that the thread is created on dl init. is it possible to spawn it on first use instead?

**Comment by wkvolkman** [comment]
The background thread does not seem to be very "back ground" when idle.
 47377      - E   3% jemalloc_bg_thd
 47399      - E   3% jemalloc_bg_thd
 47332      - E   3% jemalloc_bg_thd
 47354      - E   3% jemalloc_bg_thd
 47374      - E   2% jemalloc_bg_thd
 47396      - E   2% jemalloc_bg_thd
 47330      - E   2% jemalloc_bg_thd
 47352      - E   2% jemalloc_bg_thd
