### ISSUE TITLE
Improve scalability of huge allocation.

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#189]
Huge allocation is currently bottlenecked on a single mutex which protects a red-black tree of extant huge allocations.  For sufficiently large chunk size settings, this tends to work okay because huge allocations rarely happen.  However, it creates artificial upward pressure on the default chunk size, which is currently 4 MiB, but might otherwise be as low as ~256 KiB without issue.  In principle smaller chunks should reduce chunk metadata overhead because chunks would be more likely to completely drain.  Also, the current chunk size can cause some unfortunate interactions with Linux's transparent huge pages, and smaller chunks may mitigate this.

Addressing this issue will require some major changes:
- The global data structure for looking up huge allocations will have to scale better than the current global red-black tree.  Two potential solutions include hashing (similar to https://github.com/jemalloc/jemalloc/pull/142) and a lock-free radix tree, which I currently favor.
- Any chunk caching, e.g. ```chunk_record()``` and ```chunk_recycle()``` will have to become decentralized, i.e. per arena.  This has the disadvantage that chunk coalescing will become less effective, so in the case of ```!config_munmap``` it may be necessary to mitigate this by bulk mapping chunks so that each arena manages large contiguous ranges of virtual memory.
- As chunk size decreases, rapid huge allocation/deallocation cycles become more common, and the cost of ```mmap()``` and ```munmap()``` becomes intolerable in the fast path, which means chunk caching becomes critical to performance.  This additional cache needs to be integrated with the dirty page purging management logic.

**Comment by thestinger** [comment]
Clean spans of virtual memory marked as `PROT_NONE` don't consume commit charge, so mapping in huge spans of memory wouldn't be a problem on 64-bit even without overcommit. OpenJDK handles memory allocation like this now.

In glibc, purging is only done with `madvise` when overcommit is enabled. If it's disabled, it will drop the commit charge completely by using `mmap(addr, size, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS)` which is a lot like `MEM_DECOMMIT`/`MEM_COMMIT` on Windows rather than the usual `MEM_RESET` equivalent.

I think the option of using `PROT_NONE` like this for purging would mostly eliminate the current use case for `munmap`, along with making it sane to reserve huge ranges of memory in advance.

**Comment by jasone** [comment]
Lock-free radix trees: 8d0e04d42f4750970ac3052a6c76379b60aba5dc.  I initially started working on this because it appeared to also be useful for #145, but it turned out that only f500a10b2e94852b867334703ad77467dcfd2ddd was needed for that feature.  In any case, the radix tree work is done now, but I'm going to work on some other features before coming back to huge allocation scalability.

**Comment by jasone** [comment]
The critical parts of this are done now that chunk management is per arena (cbf3a6d70371d2390b8b0e76814e04cc6088002c), but I still want to investigate the following before calling it done:
- Don't immediately purge chunks when they are deallocated (and integrate unpurged chunks with the purging machinery), in order to add hysteresis for rapid chunk allocation/deallocation.
- Experiment with "superchunk" allocation and ```PROT_NONE``` as suggested by @thestinger.  If this proves workable, get rid of ```munmap()``` support entirely.

**Comment by thestinger** [comment]
@jasone: Here's the code I've been playing with:

```c
// use MAP_NORESERVE to get either proper memory accounting or full overcommit
static const int map_flags = MAP_ANONYMOUS|MAP_PRIVATE|MAP_NORESERVE;
static bool reduce_commit_charge = true;

void memory_init(void) {
    int overcommit = open("/proc/sys/vm/overcommit_memory", O_RDONLY|O_CLOEXEC);
    if (overcommit != -1) {
        char digit;
        int rc = read(overcommit, &digit, 1);
        if (rc == 1 && digit != '2') {
            reduce_commit_charge = false;
        }
        close(overcommit);
    }
}

void memory_decommit(void *addr, size_t size) {
    if (reduce_commit_charge) {
        mmap(addr, size, PROT_NONE, map_flags|MAP_FIXED, -1, 0);
    } else {
        madvise(addr, size, MADV_DONTNEED);
    }
}

bool memory_commit(UNUSED void *addr, UNUSED size_t size) {
    if (reduce_commit_charge) {
        return mprotect(addr, size, PROT_READ|PROT_WRITE);
    }
    return false;
}

void *memory_map(void *hint, size_t size) {
    void *addr = mmap(hint, size, PROT_READ|PROT_WRITE, map_flags, -1, 0);
    if (addr == MAP_FAILED) {
        return NULL;
    }
    return addr;
}

void *memory_reserve(void *hint, size_t size) {
    int prot = reduce_commit_charge ? PROT_NONE : PROT_READ|PROT_WRITE;
    void *addr = mmap(hint, size, prot, map_flags, -1, 0);
    if (addr == MAP_FAILED) {
        return NULL;
    }
    return addr;
}
```

It's possible to allocate enormous spans of memory with or without overcommit enabled like this, and it maps well to `MEM_DECOMMIT` / `MEM_COMMIT` on Windows (and a runtime option can be there for `MEM_RESET`). The `MAP_NORESERVE` workaround is needed to deal with the silly default heuristics, but those don't work well anyway... they tend to make `fork()` fail when it doesn't need to. I explained covered the reasoning behind it in #193.

**Comment by thestinger** [comment]
`MADV_FREE` may make it worth doing `madvise` + `mprotect` rather than using `MAP_FIXED though. I also have no idea if `PROT_NONE` works this way on other operating systems like FreeBSD and OS X.

**Comment by jasone** [comment]
A few days ago I realized that using ```PROT_NONE``` to decommit on Linux will fragment the VM map into distinct mappings.  The main reason jemalloc doesn't use ```munmap()``` on Linux by default is that the kernel performs linear VM map scans for some common operations.  ```PROT_NONE``` decommitting would be incrementally better than ```munmap()``` because at least we wouldn't suffer from the kernel's poor heuristic virtual memory recycling, but the linear scan overhead would remain an incrementally lesser problem for large applications.

Regarding poor interaction with heuristic overcommit (#193), one possibility would be to decommit via a ```pthread_atfork()```-registered function.  This still introduces VM map fragmentation, but at least it only happens when there's a compelling reason to decrease the commit charge.  Multi-threaded applications that really care about ```fork()``` performance already need to jump through some hoops and maintain one or more "light process" children that are forked early during program initialization for use as fork proxies, and decommit prior to ```fork()``` would have little impact (neither positive nor negative) on such applications.

**Comment by jasone** [comment]
ee41ad409a43d12900a5a3108f6c14f84e4eb0eb integrates chunks into the unused dirty page purging machinery.  Basic experiments indicate that this change can have a major positive impact on the minor page fault rate.  Although this change tends to increase the "dirty pages purged" statistic, that's because chunk purging is now being explicitly counted, whereas before it was an implicit side effect of chunk deallocation.

**Comment by jasone** [comment]
Huge allocation scalability looks to be in a good state now that numerous bugfixes are in place.  I'm going to punt on superchunk allocation because it solves an issue that may not be of practical significance,  as well as ```PROT_NONE```-based decommit because of the VM map fragmentation issues mentioned above.  I may do some space optimization on ```extent_node_t``` to reduce the bloat caused by the embedded ```arena_run_t```, but otherwise I'm done with this project for now.
