### ISSUE TITLE
Use dlopen to dynamically load jemalloc.so in the thread, and then use dlclose to destroy it, the program will crash when the thread is jion

### ISSUE THREAD

**Issue by pengmhm** [jemalloc/jemalloc#1890]
code segment：
void test()
{
    void *handle = NULL;
    handle = dlopen("jemalloc.so", 0x2);
    std::cout << "fd : "<< handle << "\n";
    dlclose(handle);
    return ;
}
int main()
{
    sed::thread thd(test);
    thd.join(); 
    std::cout << "finish!" << "\n";
    return 0;
}
make to run : ./test
#0  0x00007ffff61a4da0 in ?? ()
#1  0x00007ffff71a3c63 in __nptl_deallocate_tsd () from /lib64/libpthread.so.0
#2 0x00007ffff71a3e73 in start_thread () from /lib64/libpthread.so.0
#3 0x00007ffff6ecc88d in clone () from /lib64/libc.so.6

use version 4.5.0 to 5.2.1 are the same

**Comment by davidtgoldblatt** [comment]
Jemalloc can't really be dlclose'd. This is kinda-sorta tracked here: https://github.com/jemalloc/jemalloc/issues/730, but realistically I think this is low-enough priority that it probably won't ever happen.

**Comment by pengmhm** [comment]
Thank tou very much for your reply:
can I use the experimental API on the 4.5 version has solved my product problem.
