### ISSUE TITLE
Adding MAP_UNINITIALIZED option

### ISSUE THREAD

**Issue by Pusnow** [jemalloc/jemalloc#1893]
Linux has `MAP_UNINITIALIZED` option for allocating uninitialized pages. [link](https://man7.org/linux/man-pages/man2/mmap.2.html)
It is usually used for performance on embedded devices.

I've tested JEMalloc with `MAP_UNINITIALIZED` option, and it does not works.
It seems that JEMalloc (at least rtree) assumes all mmaped pages are zero-filled. 

So, it would be nice if JEMalloc has an option for `MAP_UNINITIALIZED`.
Facebook internal JEMalloc seems to already have this option. [link](https://twitter.com/RichFelker/status/786294948865806336)

**Comment by davidtgoldblatt** [comment]
This is achievable with the extent hooks API without requiring built-in support; the alloc hook can look at the `zero` argument it gets to decide if MAP_UNINITIALIZED memory is acceptable or not.

> Facebook internal JEMalloc seems to already have this option. link

The Facebook-internal jemalloc doesn't have any interesting differences from the public one. (Historically there were some, but any more).

**Comment by davidtgoldblatt** [comment]
Closing for now, but feel free to reopen if the extent hook approach wouldn't work for you for some reason.
