### ISSUE TITLE
LetsEncrypt certificate on https://master.jemalloc.net is expired

### ISSUE THREAD

**Issue by umanwizard** [jemalloc/jemalloc#1920]

**Comment by umanwizard** [comment]
![image](https://user-images.githubusercontent.com/1893159/91083711-bcd68380-e618-11ea-99f8-64ee253e75c5.png)

**Comment by davidtgoldblatt** [comment]
I rebooted the CI machine to install the newer LetsEncrypt cert program, but it seems they never came back up.

@jasone, I think you're running the ubuntu CI machines these days; any chance you could check the control panel and see how come they're not booting? (At some point it might be a good idea to figure out how to do some sort of subdomain management behind a group setup, just so we don't have to bug you every time something goes down).

**Comment by jasone** [comment]
The console was blank, unresponsive, so I power-cycled the droplet and it came back up without apparent issue. @davidtgoldblatt, there is a jemalloc project on digitalocean that I must have set up back in ~2016, and you appear to have access to it.

**Comment by davidtgoldblatt** [comment]
Cool, thanks.

I restarted CI, updated certs, and now have cert renewal on a cron job, so this should be the last time we have to manually refresh.
