### ISSUE TITLE
how to calucate the memory fragmentation? 

### ISSUE THREAD

**Issue by lnparker** [jemalloc/jemalloc#1929]
hi all , i want to count the real memory to calulate memory fragmentation rate when using jemalloc. i have seen stats.allocated : total number of bytes allocated by the application. But "allocated" stands for the "size class" jemalloc alloced. For example, i use " malloc(3);" , i want to get "3", but "allocated" returns "8" because the smallest size class is 8.
is there any good idea ? thank u !

**Comment by lnparker** [comment]
when calling jemalloc free, a " void *ptr " is passed as the parameter  . it seems that we cannot get the type of the object to be freed. is there any better ideas to get size of the object ? thanks guys

**Comment by duanyangjing** [comment]
Upon entry of `je_malloc` function, there is `LOG("core.malloc.entry", "size: %zu", size)` which gives you the size of the requested allocation. This will be printed when you configure jemalloc with `--enable-log`, and set environment variable `MALLOC_CONF="log:core.malloc"` when running your application.

**Comment by davidtgoldblatt** [comment]
There's no way to get requested object size after allocation (once we round it up internally, we treat that as the "true" size, and treat that as an API guarantee). I don't think there's anything we reasonably could do; tracking this sort of data would probably impose unacceptable cost.
