### ISSUE TITLE
License Check Compliance?

### ISSUE THREAD

**Issue by breeswish** [jemalloc/jemalloc#1932]
According to some license scanning services like fossa.com, these two files are reported as GPL:

https://github.com/jemalloc/jemalloc/blob/dev/build-aux/config.guess
https://github.com/jemalloc/jemalloc/blob/dev/build-aux/config.sub

![image](https://user-images.githubusercontent.com/1916485/92744969-8472cb80-f3b4-11ea-8c2e-38eb5a687adf.png)

I'm not an expert in license compliance and I would like to know whether these two GPL licensed files are conflict with the jemalloc's license (since GPL is "infectious"). Could I safely mark the GPL check result as false positive, or this need to be resolved?

Thanks a lot!

**Comment by davidtgoldblatt** [comment]
I couldn't really comment on which licenses are allowable for your purposes, but one thing I'll note is that the license isn't GPL-3, it's GPL-3 with the GCC exception:

```
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that contains a
# configuration script generated by Autoconf, you may include it under
# the same distribution terms that you use for the rest of that
# program.  This Exception is an additional permission under section 7
# of the GNU General Public License, version 3 ("GPLv3").
```

This is indeed how we use the scripts.
