### ISSUE TITLE
Jeprof generate many heapfiles in few minutes

### ISSUE THREAD

**Issue by UKeeySDis** [jemalloc/jemalloc#1936]
### info
- conf: MALLOC_CONF:prof:true,lg_prof_interval:39
- version: jemalloc-5.1
- server info:
    1. mem: 250G
    2. kernel version: Linux 3.10.107-1-tlinux2-0052
    3. architecture: x86-64
### problem
I want to detect memory leak for online service, so I choose libjemalloc.a and  lg_prof_interval is 512G.At first, heap file generated every hour, but after running for a period of time, every hour, a large number of files will be generated in a few minutes.
![image](https://user-images.githubusercontent.com/26181669/93220440-1efd5100-f79f-11ea-8bbc-89318a1f62c3.png)
It can't be malloc 512G in such a short time.

**Comment by interwq** [comment]
I'm not aware of any issues that may cause this behavior. Can you please check the summary section in the profiles, to see if anything stands out?

Another thought is, to check if there's any failed malloc calls, potentially with underflowed input size. That may cause the described behavior.

CC: @yinan1048576 in case it rings any bell.

**Comment by yinan1048576** [comment]
I can't think of any better explanations. Another way to investigate is to get the malloc stats and check the total allocated memory.

**Comment by UKeeySDis** [comment]
> I can't think of any better explanations. Another way to investigate is to get the malloc stats and check the total allocated memory.

How to check the total allocated memory?by `prof_accum` option?

**Comment by UKeeySDis** [comment]
I run `jeprof --pdf bin --base=heap1.file heap2.file > res.pdf` command to compare the two files with a short time interval(one minute), and result :
![image](https://user-images.githubusercontent.com/26181669/93296623-2b76bd80-f822-11ea-90cd-641d450677ce.png).
So those heap files are normal.

**Comment by antbob** [comment]
Bump. Experiencing a similar issue. With 'prof:true,lg_prof_interval:30,lg_prof_sample:20' it generates thousands of files like:

...
-rw-r--r--. 1 dirsrv dirsrv  66K Feb 11 11:31 jeprof.15964.0.i0.heap
-rw-r--r--. 1 dirsrv dirsrv  64K Feb 11 12:31 jeprof.15964.1000.i1000.heap
-rw-r--r--. 1 dirsrv dirsrv  62K Feb 11 12:31 jeprof.15964.1001.i1001.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:31 jeprof.15964.1002.i1002.heap
-rw-r--r--. 1 dirsrv dirsrv  64K Feb 11 12:31 jeprof.15964.1003.i1003.heap
-rw-r--r--. 1 dirsrv dirsrv  65K Feb 11 12:31 jeprof.15964.1004.i1004.heap
-rw-r--r--. 1 dirsrv dirsrv  64K Feb 11 12:31 jeprof.15964.1005.i1005.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:31 jeprof.15964.1006.i1006.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:31 jeprof.15964.1007.i1007.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:31 jeprof.15964.1008.i1008.heap
-rw-r--r--. 1 dirsrv dirsrv  64K Feb 11 12:31 jeprof.15964.1009.i1009.heap
-rw-r--r--. 1 dirsrv dirsrv  68K Feb 11 11:33 jeprof.15964.100.i100.heap
-rw-r--r--. 1 dirsrv dirsrv  64K Feb 11 12:31 jeprof.15964.1010.i1010.heap
-rw-r--r--. 1 dirsrv dirsrv  62K Feb 11 12:31 jeprof.15964.1011.i1011.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:31 jeprof.15964.1012.i1012.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:31 jeprof.15964.1013.i1013.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:32 jeprof.15964.1014.i1014.heap
-rw-r--r--. 1 dirsrv dirsrv  63K Feb 11 12:32 jeprof.15964.1015.i1015.heap
-rw-r--r--. 1 dirsrv dirsrv  62K Feb 11 12:32 jeprof.15964.1016.i1016.heap
-rw-r--r--. 1 dirsrv dirsrv  62K Feb 11 12:32 jeprof.15964.1017.i1017.heap
-rw-r--r--. 1 dirsrv dirsrv  65K Feb 11 12:32 jeprof.15964.1018.i1018.heap
-rw-r--r--. 1 dirsrv dirsrv  64K Feb 11 12:32 jeprof.15964.1019.i1019.heap
-rw-r--r--. 1 dirsrv dirsrv  68K Feb 11 11:33 jeprof.15964.101.i101.heap
...

8379 files in total. I can actually generate a report with (take quite a while)

jeprof --show_bytes --pdf "/usr/sbin/ns-slapd" jeprof.*.heap > /tmp/slapd.pdf

but I'm not sure if it can be trusted or not. This is also with a multi-threaded app. jemalloc is LD_PRELOAD'ed and no other malloc conf settings are set and no jemalloc specific APIs are invoked.

**Comment by Lapenkov** [comment]
@antbob does your app have very short thread lifetime by any chance?
What jemalloc are you using?
Could you please run your app with upstream jemalloc and check if the issue persists?

**Comment by antbob** [comment]
@Lapenkov no, the threads are created when the app starts and they terminate when the process exits. Total of 16 worker threads in this case and majority of allocations are driven by them. There are some other service threads that are less active but they are long lived (til process exit) as well.

This is with 5.2.1 which is the latest I believe. Which branch I should try with ? Is 'dev' branch relatively stable/usable right now ? I can give it a try tomorrow and report back.

**Comment by Lapenkov** [comment]
You can try 5.3 release candidate: https://github.com/jemalloc/jemalloc/issues/2213#issuecomment-1026119508

**Comment by antbob** [comment]
@Lapenkov The 5.3rc does not produce any heap files at all on exact same test with exact same malloc conf settings (prof:true,lg_prof_interval:30,lg_prof_sample:20). I did verify with pmap that it got preloaded. Nada with process RSS size over 2,5Gb and VSZ over 3Gb so it clearly went thru enough allocations to produce at least 1-2 heap dumps. Perhaps I did not build it correctly ? I simply followed INSTALL instructions and did configure && make && make install. What gives ?

**Comment by antbob** [comment]
on another run 5.2.1 created 0-100 seq heap dumps in a short burst so my theory above is likely a total bs. 5.3rc does not produce any heap dumps in my case. if anyone here is interested i can do a write up on how to setup a reproducer, its a bit of an effort but should be easy to reproduce.

**Comment by Lapenkov** [comment]
> @Lapenkov The 5.3rc does not produce any heap files at all on exact same test with exact same malloc conf settings (prof:true,lg_prof_interval:30,lg_prof_sample:20). I did verify with pmap that it got preloaded. Nada with process RSS size over 2,5Gb and VSZ over 3Gb so it clearly went thru enough allocations to produce at least 1-2 heap dumps. Perhaps I did not build it correctly ? I simply followed INSTALL instructions and did configure && make && make install. What gives ?

Yes, the problem is with the configuration. You need to configure with `--enable-prof`.

**Comment by Lapenkov** [comment]
> I think those _might_ actually be legit. jemalloc docs are mum on this but i _think_ whats happening is that the default number of arenas is 4*ncpus(cores) which in my case is 16. so it would dump a heap file for each each arena eg with 5.2.1 the 1st dump event dumps 16 heap files sequentially (0.i0 to 15.i15). it also seems that in order for the dump event to occur lg_prof_interval has to be crossed by all arenas. this is just a speculation of course since i dont have spare cycles right now to read the code to understand how it actually works but here you go next person finding this issue, hope this helps.

No, `lg_prof_interval` is a global entity and has to be crossed only once by all allocations combined.

**Comment by Lapenkov** [comment]
> on another run 5.2.1 created 0-100 seq heap dumps in a short burst so my theory above is likely a total bs. 5.3rc does not produce any heap dumps in my case. if anyone here is interested i can do a write up on how to setup a reproducer, its a bit of an effort but should be easy to reproduce.

It's really hard to say what's going on without a debugging session. So a way to reproduce would definitely help here.

**Comment by antbob** [comment]
@Lapenkov Thanx for trying to help out! So on Sunday I had a minute to look into it in more detail. I found https://github.com/jemalloc/jemalloc/blob/12cd13cd418512d9e7596921ccdb62e25a103f87/include/jemalloc/internal/lockedint.h#L93 is what essentially triggers the dump and did a couple of things:

- undefined JEMALLOC_ATOMIC_U64 to use mutexes instead just in case there is some monkey business with atomics that isnt apparent.
- augmented it with some logging for initial values and on overflow.

and did some tests and it appears that everything works as expected ie before/after and https://github.com/jemalloc/jemalloc/blob/8c59c44ffa83bab0f73d5cc8f7d0bbc8d649220b/src/prof.c#L41 gets updated and everything seem to be in order eg there are no weird values or sudden swings/jumps or anything like that.

so, i'm thinking i was just probably underestimating how much those threads allocate and how much alloc churn there is ie based on application load it is kinda in realm of possibility it goes thru 1Gb of allocs that quickly tho i'm a bit surprised. also have tried printing jemalloc stats on overflow but i think only 'prof_idump_accumulated' tracks the accumulated allocations so stats allocated figures didnt help much to clear the picture as i think they just represent whats currently allocated.

anyway, here is how to reproduce, just in case you have time to have a look at it:

i'm doing this on Red Hat Enterprise Linux 8.5 but it should be the same on the latest Fedora release. you gonna need either 2 small 4 core machines with 8Gb RAM or 1 equivalent bigger one eg 8 core / 16Gb.

1) install 389ds on both machines (lets call one machine the server and the other the client):

yum install 389-ds-base

2) on the server machine configure 389ds:

dscreate interactive

Install Directory Server (interactive mode)
===========================================

Enter system's hostname [your.server.fqdn.hostname.com]: 

Enter the instance name []: server

Enter port number [389]: 

Create self-signed certificate database [yes]: 

Enter secure port number [636]: 

Enter Directory Manager DN [cn=Directory Manager]: 

Enter the Directory Manager password: password
Confirm the Directory Manager Password: password

Enter the database suffix (or enter "none" to skip) [dc=example,dc=com]: dc=example,dc=com

Create sample entries in the suffix [no]: yes

Do you want to start the instance after the installation? [yes]: no

Are you ready to install? [no]: yes

3) change MALLOC_CONF settings:

add to '/usr/lib/systemd/system/dirsrv@.service.d/custom.conf' file:

Environment=MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:20

then do

systemctl daemon-reload

4) start the 389ds server:

systemctl start dirsrv@server

5) on the client machine run:

ldclt -h your.server.fqdn.hostname.com -p 389 -b "ou=people,dc=example,dc=com" -D "cn=Directory Manager" -w password -e esearch -f "(objectClass=*)" -e attrlist=cn -I 32 > /tmp/ldclt.search &

ldclt -h your.server.fqdn.hostname.com -p 389 -b "ou=people,dc=example,dc=com" -D "cn=Directory Manager" -w password -f cn=MrXXXXXXXXX -b "ou=people,dc=example,dc=com" -e add,person,incr,noloop,commoncounter -r0 -R999999999 -I 32 > /tmp/ldclt.add &

Once these clients run for a while you should start seeing heap profile dumps on the server machine under '/var/log/dirsrv/slapd-server'. In a few hours there should be thousands of those heap files.

**Comment by antbob** [comment]
@Lapenkov and also on 'get your xmas list in early' note, i reckon it would be great to have an option similar to 'opt.prof_gdump' but as interval for resident size. so it would track kinda similar to 'prof_idump_accumulated' and dump when resident size grows by specified value. i realize it probably wont be a priority for you guys to implement but if you are open to this idea please let me know, i might be able to hack a patch to do that at some point if i have time (since i already invested a bit looking at the code).

**Comment by Lapenkov** [comment]
Frankly, the repro is more demanding than I had expected, I won't be able to allocate the time immediately to follow it. If you're not sure how much memory is actually allocated between dumps, I think you can see that with BPF and uprobes.
For instance, if your binary's name is `a.out`, you can do the following (don't forget to specify the correct path to `libjemalloc.so`):
```
sudo bpftrace -e 'uprobe:<path_to_libjemalloc.so>:malloc /comm == "a.out"/ { @sum += arg0; }
uprobe:<path_to_libjemalloc.so>:je_prof_idump /comm == "a.out"/ { printf("Allocated %d bytes between dumps\n", @sum);  @sum = 0; }'
```
This can reveal if your app indeed allocates too much and jemalloc is doing the correct thing (or not :) ). If so, you can expand my example to detect where the allocations are coming from.

**Comment by antbob** [comment]
@Lapenkov Thats a good idea! I did that just now and here its fairly close (dunno what really makes up the difference)

Attaching 2 probes...
Allocated 754079753 bytes between dumps
Allocated 852972597 bytes between dumps
Allocated 865721840 bytes between dumps
Allocated 867412868 bytes between dumps
Allocated 855381223 bytes between dumps
Allocated 866402851 bytes between dumps
Allocated 872154935 bytes between dumps
Allocated 855955131 bytes between dumps
Allocated 865380441 bytes between dumps
Allocated 866988035 bytes between dumps
^C

**Comment by Lapenkov** [comment]
Well, log2 of these numbers is pretty close to 30, therefore malloc does the right thing here. You need to figure out why the app allocates that much. This can be done via BPF as well - aggregate arg0 by `ustack()` and print top 10 upon `je_prof_idump`. This will give you the top 10 stacks by bytes allocated.

**Comment by antbob** [comment]
@Lapenkov Thank you very much for your help with this!

**Comment by Lapenkov** [comment]
You're welcome!
I assume, you have found the root cause in your case? Also, so far I haven't seen evidence that something is wrong with jemalloc, therefore I'll close.
But feel free to reopen if you have additional questions or something needs to be fixed.

**Comment by antbob** [comment]
@Lapenkov the root cause is that the test done against the server basically hammers it with thousands of requests and even tho I expected allocation churn I just didn't expect that much.
