### ISSUE TITLE
Abnormal memory increase after I use jemalloc and a lot of memory has been released

### ISSUE THREAD

**Issue by lan1120** [jemalloc/jemalloc#1940]
My application processes flow with a maximum memory consumption of 800m. After stopping the flow:
(1) When I use ptmalloc, 800m memory cannot be released
(2) When I used jemalloc, I released 450m, good. But program memory began to increase, increased 400m, and then remained stable. No message was processed.

**Comment by davidtgoldblatt** [comment]
By default, memory gets returned based on how long it's gone unused, and is checked based on activity; it's possible that the allocator isn't getting used enough to return the memory. You could try turning on background threads, or explicitly purging arenas during low-activity periods.

(Another possibility is plain old fragmentation induced by sparse small allocations, but that's harder to deal with).
