### ISSUE TITLE
crash at function arena_chunk_stash_dirty in jemalloc 

### ISSUE THREAD

**Issue by knull-cn** [jemalloc/jemalloc#195]
Our game programs were run by zlib and jemalloc and other libs;
when game program run locals,There is no problem;
Today, we run in internet;One process-program was crash when use zlib function deflateEnd;
my Environment:
Centos 6.2 ; GCC 4.47 ;  zlib version is 1.2.5;
jemalloc version is 3.6(Compile on Centos 6.3); 

Here is the core dump information:
(gdb) where
#0  0xf779ea6a in arena_chunk_stash_dirty (arena=0xf6c27040, all=false) at src/arena.c:876
#1  arena_chunk_purge (arena=0xf6c27040, all=false) at src/arena.c:994
#2  arena_purge (arena=0xf6c27040, all=false) at src/arena.c:1075
#3  0xf77a1ecd in je_arena_dalloc_large_locked (arena=0xf6c27040, chunk=0xf1c00000, ptr=0xf1c5e000) at src/arena.c:1971
#4  je_arena_dalloc_large (arena=0xf6c27040, chunk=0xf1c00000, ptr=0xf1c5e000) at src/arena.c:1979
#5  0xf77973db in je_arena_dalloc (ptr=0xf1c5e000) at include/jemalloc/internal/arena.h:1056
#6  je_idalloct (ptr=0xf1c5e000) at include/jemalloc/internal/jemalloc_internal.h:898
#7  je_iqalloct (ptr=0xf1c5e000) at include/jemalloc/internal/jemalloc_internal.h:917
#8  je_iqalloc (ptr=0xf1c5e000) at include/jemalloc/internal/jemalloc_internal.h:924
#9  ifree (ptr=0xf1c5e000) at src/jemalloc.c:1233
#10 free (ptr=0xf1c5e000) at src/jemalloc.c:1308
#11 0x080e7084 in deflateEnd ()
#12 0x080dfcd1 in compresszlib 

arena_chunk_stash_dirty  crash at arena.c:876
binbind is to large out arena_bin_info.
mybe run->bin point wrong memory:

(gdb) p arena
$6 = (arena_t *) 0xf6c27040
(gdb) p &arena->bins
$7 = (arena_bin_t (*)[28]) 0xf6c270f4
(gdb) p run->bin
$8 = (arena_bin_t *) 0xf6003030

**Comment by jasone** [comment]
I'm not sure what's going on here, but I suspect earlier metadata corruption, possibly due to a double free.  Are you able to reproduce this with a debug build of jemalloc?

**Comment by jasone** [comment]
Closing because this is not actionable.  Please reopen if you gather additional data.
