### ISSUE TITLE
partial purging of THP

### ISSUE THREAD

**Issue by jty2** [jemalloc/jemalloc#1950]
On Linux, when memory mapped by THP (using malloc_conf="thp:always") is purged using madvise(MADV_DONTNEED), jemalloc (5.2.1 and dev) uses region lengths that are smaller than the size of a THP.  The kernel handles MADV_DONTNEED by splitting the THP into PTE mappings.  As a result, remaining data that was not part of the purge is mapped using base pages on access, thereby losing the performance benefit of being mapped by large TLB support.  

For 2MB THP page size, there's not much performance loss because usually there are enough TLBs for mapping such a small amount of memory.  But when the THP page size is 512MB or larger, there can be much more collateral damage, to the effect that the performance is the same as not using THP at all.  

Should jemalloc purge a THP only in its entirety, and not partially?

**Comment by davidtgoldblatt** [comment]
Probably yes. The tricky is that THPs are sort of another axis to consider when it comes to purging, and we don't yet have THP-aware logic; extents of the same size are (more or less) equivalent to the purging logic, which of course stops being true when the kernel is mapping some of those into hugepages behind the scenes. This is in the works, though.

In the meantime, I think our best recommendation is to turn off purging entirely if you want thp:always on (and treat it as a "burn memory to save CPU" option).

**Comment by jty2** [comment]
Thanks, can confirm, "MALLOC_CONF=thp:always,retain:true,dirty_decay_ms:-1,muzzy_decay_ms:-1" seems to do what I want.
