### ISSUE TITLE
How does jemalloc determine slab size?

### ISSUE THREAD

**Issue by lriuui0x0** [jemalloc/jemalloc#1959]
I didn't find reference on how jemalloc determines the default slab size when a new slab needs to be allocated for a particular small size class. May I ask how does this work, and how to optimize this? For example, if I know a particular type of object will have at most 100 instances, I may try to control the slab size to be enough for just holding 100 regions.

**Comment by davidtgoldblatt** [comment]
By default, we pick slab sizes to be the smallest number of pages that don't result in any wasted space due to not dividing evenly into the object size (e.g. 48 byte slabs get 3 pages, while 32 and 64 byte slabs only get 1 page).

We have some experimental controls (search for the "slab_sizes" MALLOC_CONF option in the codebase), but no guarantees as to whether or not we'll continue to respect them over time; they're mostly for our benefit as we run various tuning experiments.

**Comment by davidtgoldblatt** [comment]
Closing for now, but feel free to reopen if there are more questions.

**Comment by lriuui0x0** [comment]
@davidtgoldblatt Does that mean if I allocate a 4KB object, the slab will have be able to hold one object, assuming page size if 4KB?

What happens if we want to allocate even larger object? The jemalloc documentation is quite opaque on this. It only says ' large objects each have their own extents backing them', but lacks details.

Also where is slab header stored? Is it stored together with the slab? Then does that mean if we want to allocate 2KB object, we get a 4KB slab which should hold two objects. But due to the slab header, it can actually only hold one object?

**Comment by davidtgoldblatt** [comment]
> Does that mean if I allocate a 4KB object, the slab will have be able to hold one object, assuming page size if 4KB?

Right. It's really only nominally a "slab" in this case.

> What happens if we want to allocate even larger object? The jemalloc documentation is quite opaque on this. It only says ' large objects each have their own extents backing them', but lacks details.

These requests will go to the page-level allocator directly. A similar sort of size-class binning happens there; we pick an extent that can satisfy the allocation.

> Also where is slab header stored? Is it stored together with the slab? Then does that mean if we want to allocate 2KB object, we get a 4KB slab which should hold two objects. But due to the slab header, it can actually only hold one object?

The metadata for the extent (where the used/unused bitmap is stored) is out of band; the slabs for the 2kb size class are 1-page in length by default, which results in 2 2kb objects per slab on systems with 4kb pages.
