### ISSUE TITLE
Question about decreasing memory consumed obviously

### ISSUE THREAD

**Issue by firejq** [jemalloc/jemalloc#1989]
I have used jemalloc to replace ptmalloc of glibc in a machine learning multi-threads training scene, of which the result produced a significant effect, the memory consumed by the program was reduced by 50%. But while surprised, it made a little confused for me. I read some related articles, such as the following links. They also produced obvious memory reduction, but the specific reason is not clear in the article.

Therefore, I raised this issue.
1. Why can using jemalloc reduce so much memory consumption, is the reduced part memory fragments?
1. Is there any tool or method for verification?

I am looking forward to any suggestions. Thanks!

Ref:
- [Decreasing RAM Usage by 40% Using jemalloc with Python & Celery](https://zapier.com/engineering/celery-python-jemalloc/)
- [REDUCING SIDEKIQ MEMORY USAGE 4x WITH JEMALLOC](https://brandonhilkert.com/blog/reducing-sidekiq-memory-usage-with-jemalloc/)

**Comment by davidtgoldblatt** [comment]
> Why can using jemalloc reduce so much memory consumption, is the reduced part memory fragments?

I think that this may one source, but my recollection is that the glibc malloc's heuristics about when to return memory to the OS are less developed as well.

> Is there any tool or method for verification?

I suppose the gold-standard for memory consumption is OS-level RSS counters (in, say, `top`).
