### ISSUE TITLE
Alternate ARM CI strategy

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1993]
We had been using a buildbot-powered ARM host for CI, but the VPS provider stopped supporting it. We could move to Travis (which has since added ARM support), but then we wouldn't be able to ssh in and debug things, which is a nice facility to have.

I think Travis is probably the easiest way forwards for now, but it would be nice to have some sort of systematic strategy for testing architectures where we don't have machines sitting on our desks[1].

[1] Or we could all just buy the new Mac minis.

**Comment by xhochy** [comment]
At conda-forge we are using `drone.io` for ARM builds and it works fine but is a bit resource constraint but still it's fine. We have a fallback that we cross-compile on x86 CI instances and then run the tests with docker/qemu. The tests then have a ~10x slowdown but at least show 99% of the failures you would see on an ARM machine.

**Comment by egaudry** [comment]
@davidtgoldblatt I'm not sure this is relevant to your use-case, but I read that Ampere contributed to Debian and other opensource project porting effort on aarch64 (src: https://www.debian.org/News/2020/20200616). Have you considered getting in touch with them ?

**Comment by davidtgoldblatt** [comment]
I hadn't thought of it, but it's a good thing to keep in mind. Although, in the meantime we got got paid Travis, which does let us SSH in with a little more ease, so I think most of the pain we felt in the Travis-only world is gone these days. Closing for now, although @Lapenkov might want to reopen if he's got thoughts here.
