### ISSUE TITLE
Set arena chunk alloc/dalloc before first call.

### ISSUE THREAD

**Issue by ldalessa** [jemalloc/jemalloc#200]
As it stands, we use arena.*.chunk.alloc/.dalloc in order to replace the chunk allocator in our arenas. Unfortunately, we need to abandon the "vestigial" chunk that has been allocated in jemalloc_constructor(). It would be helpful if there was a way to set a default chunk allocator so we could actually trap all chunks, perhaps through a malloc_conf setting, or through a global pointer that we could set with our allocator statically.

This isn't a problem as much as it is a feature request.

**Comment by jasone** [comment]
Does the base allocator also cause problems for your use case?

**Comment by ldalessa** [comment]
I'm not sure what the base allocator does. I'm trying to register chunks with the network, and if I miss one and it winds up being used later, we can get a network driver failure during rdma.

I could  potentially special-case register the chunk-size/cunk-aligned region after my first call, but I'm trying to use huge pages (2M-16M depending on what the hugetlbfs tells me) for chunks—they're getting pre-faulted during network registration anyway so there's not a benefit to smaller pages. On some of our platforms (e.g., Cray's Gemini network)  we need to use huge pages anyway to register enough memory anyway.

I can mostly avoid using the vestigial chunk, so it's okay, but it just feels wrong to waste the initial page and arena—if I could guarantee that the vestigial chunk wouldn't satisfy and future allocations after I reset the allocator (assuming I promise not to free anything from it) then I could at least stay with the default set of arenas.

Again, we have a workaround—replace the default arena with one with my custom allocation and don't free anything from the old arena—so this is mostly forward-looking.

**Comment by ldalessa** [comment]
I still think that this would be useful in some contexts, but the explicit tcache capability has entirely solved our current need. We used to have three different instances of jemalloc loaded into the address space and we'd need to burn all the initial chunks in two of them. Now we can get by with just one, and we *do* occasionally have the need to perform an allocation through the default chunk, so we're not wasting anything.

We do create two extra arenas per system thread, but as the documentation says we replace their alloc/dalloc/purge calls before ever using them in `mallocx()` so we shouldn't get default arenas allocated there.

**Comment by jasone** [comment]
I'm going to close this without implementation, because I can't think of a way to do it without introducing library-level symbols, and those would impose a binary compatibility burden I want to avoid unless there's a compelling need.

**Comment by ldalessa** [comment]
Thanks Jason. This is less of an issue for us now that we're only using one instance of the library. It can be wasteful with hugetlb allocation for some of our applications, but we can live with that.

**Comment by neon12345** [comment]
Perhaps it would be enough to set the a0 alloc funcs before any alloc will happen. 

int
ctl_byname(const char *name, void *oldp, size_t *oldlenp, void *newp,
    size_t newlen)
{
	int ret;
	size_t depth;
	ctl_node_t const *nodes[CTL_MAX_DEPTH];
	size_t mib[CTL_MAX_DEPTH];
	const ctl_named_node_t *node;

	depth = CTL_MAX_DEPTH;
	ret = ctl_lookup(name, nodes, mib, &depth);
	if (ret != 0)
		goto label_return;

	node = ctl_named_node(nodes[depth-1]);
	if (node != NULL && node->ctl) {
		if (!ctl_initialized) {
			unsigned i = 0;
			unsigned arena_ind = mib[1];
			if((arena_ind == 0) &&
			   (node == &chunk_node[i] ||
			   node == &chunk_node[++i] ||
			   node == &chunk_node[++i])) {
				arena_t* a0 = a0get();
				switch(i)
				{
				case 0:
					READ(a0->chunk_alloc, chunk_alloc_t *);
					WRITE(a0->chunk_alloc, chunk_alloc_t *);
					break;
				case 1:
					READ(a0->chunk_dalloc, chunk_dalloc_t *);
					WRITE(a0->chunk_dalloc, chunk_dalloc_t *);
					break;
				case 2:
					READ(a0->chunk_purge, chunk_purge_t *);
					WRITE(a0->chunk_purge, chunk_purge_t *);
					break;
				}
				goto label_return;
			}
			else
			{
				if(ctl_init()) {
					ret = EAGAIN;
					goto label_return;
				}
			}
		}

		ret = node->ctl(mib, depth, oldp, oldlenp, newp, newlen);
	} else {
		/* The name refers to a partial path through the ctl tree. */
		ret = ENOENT;
	}

label_return:
	return(ret);
}

**Comment by neon12345** [comment]
Perhaps it is possible to change the arena0 alloc funcs before the first alloc:

https://github.com/neon12345/jemalloc/commit/63622ebe95e02f3e12dc388a8c63ef76d1cc5557
