### ISSUE TITLE
question: (formal) thread safety guarantee of jemalloc APIs

### ISSUE THREAD

**Issue by ryuxin** [jemalloc/jemalloc#2002]
Is there any docs/model/specification talking about the concurrency semantics of jemalloc APIs (`calloc`, `free`, `realloc`...)?
Are they undefined? linearizable? or other types of guarantee?

For example, if two cores call `realloc` on the same pointer concurrently, what are their possible results?
Similarly for concurrent `realloc` and `free` on the same pointer.

Thanks

**Comment by davidtgoldblatt** [comment]
We meet the C API guarantees: basically, don't do that. If the user can't prove (for example) that a realloc happens-before a free, then it's undefined behavior, and we may behave arbitrarily badly, erase your boot sector, etc.

**Comment by ryuxin** [comment]
Thanks for your reply.

What happens for two concurrent `realloc` on the same pointer？

**Comment by davidtgoldblatt** [comment]
It's undefined behavior; we can and will break in arbitrarily bad ways.

**Comment by ryuxin** [comment]
I have another related question.
Do you know any tools or methods to detect such problematic concurrent calls?

Thanks

**Comment by LifeIsStrange** [comment]
@ryuxin maybe https://clang.llvm.org/docs/ThreadSanitizer.html?
