### ISSUE TITLE
why meta data not derease after purging

### ISSUE THREAD

**Issue by freecw** [jemalloc/jemalloc#2007]
before purge:

Allocated: 1932737808, active: 1934479360, metadata: **14665832** (n_thp 0), resident: 1948798976, mapped: 1963847680, retained: 190189568

after purge:

Allocated: 24319992, active: 26599424, metadata: **14665832** (n_thp 0), resident: 40972288, mapped: 56020992, retained: 2098016256

**Comment by interwq** [comment]
Purge only deals with the user-facing unused pages; the internal metadata won't be removed and will remain cached (and there's no plan to change that in the short term).
