### ISSUE TITLE
issue during analysis 

### ISSUE THREAD

**Issue by zulqarnain1985** [jemalloc/jemalloc#2008]
<jemalloc>: Error in malloc(): out of memory
 Requested: 2065019520

== Error ==  system call for: "['/home/qaisar/SPAdes-3.14.1-Linux/bin/spades-hammer', '/home/qaisar/SPAdes-3.14.1-Linux/bin/spades_test/corrected/configs/config.info']" finished abnormally, OS return value: -6

**Comment by davidtgoldblatt** [comment]
I'm not sure that there's much we can do with this without more context / a repro. Feel free to reopen if there's something more specific we can look into.
