### ISSUE TITLE
Re-release 5.2.1 with updated config.guess/config.sub

### ISSUE THREAD

**Issue by xhochy** [jemalloc/jemalloc#2010]
The current `config.guess/config.sub` files don't support (cross-)compiling to the Apple M1 process. The build fails with 

```
Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
configure: error: /bin/sh build-aux/config.sub arm64-apple-darwin20.0.0 failed
```

This is easily fixed by updating the `config.guess/config.sub` files. Manually doing this and running the tests shows that `jemalloc` runs fine on Apple Silicon

But in Apache Arrow we built `jemalloc` during Arrow C++'s build from the latest release tarball. We would neither like to have a `autoconf` dependency nor can we ship those files with the Arrow source tarball due to licensing restrictions inside the Apache Software Foundation. Working with a jemalloc release tarball that contains them is though ok for us/the ASF. Happy to do volunteer some work into getting this minor release, not sure if I can add valuable things here for such a minor release.

cc @pitrou @nealrichardson @kou

**Comment by davidtgoldblatt** [comment]
Makes sense to me, if you're OK putting up a PR to update them, I'm happy to merge (or, I can as well, although for silly dev-box reasons it'll take me a while).
