### ISSUE TITLE
Optionally override C++ new/delete operators.

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#202]
C++14 adds sized deallocation for `delete()`:

```
void operator delete (void *, std::size_t) noexcept;
void operator delete[] (void *, std::size_t) noexcept;
```

Prior to this change, the default suite of new/delete operators was sufficient for full integration with jemalloc in that the operators called directly into `malloc()` and `free()`.  With the addition of sized deallocation, the default sized delete implementation will just call `free()`, even though `sdallocx()` would be the ideal.  Thus jemalloc needs to start replacing the default new/delete operators.  This should probably default to being enabled, but with a `--disable-new-delete` configure option.

**Comment by bmaurer** [comment]
If you're customizing for C++, one thing that would be helpful is to force GLIBCXX_FORCE_NEW=1. See:
http://gperftools.googlecode.com/svn/trunk/src/malloc_extension.cc

(we should double check this is actually still necessary -- it looks like libstdc++ may have switched to a non-caching allocator as the default. If this is the case, there's a bunch of uses of GLIBCXX_FORCE_NEW=1 we can fix up at fb :-)

**Comment by jasone** [comment]
LLVM developers are finding it difficult to seamlessly add sized deallocation support as envisioned by C++14: http://reviews.llvm.org/rL232788

**Comment by jasone** [comment]
gcc-specific C++14 feature info: https://gcc.gnu.org/projects/cxx1y.html

**Comment by tomjakubowski** [comment]
I can see why replacing the default sized `operator delete` and `operator delete[]` overloads is desirable, but I don't understand the implication in the OP that the default STL `operator new` family should be replaced too.

**Comment by tomjakubowski** [comment]
Oh, I suppose it's necessary in the case that `--with-jemalloc-prefix` is passed at configure time but *not* (say) `--disable-new-delete`.

**Comment by djwatson** [comment]
new is useful to ensure both use jemalloc as with prefixes.  It can also be useful to avoid an extra plt thunk, since je_malloc() is a public symbol, and you may get two thunks currently: one to libstdc++'s new operator, and another to je_malloc().  Overriding new could remove the second thunk.

**Comment by alexreg** [comment]
Any update on this? It seems it would be particularly useful when linking C++ libraries to Rust libraries.

**Comment by jasone** [comment]
@alexreg, @djwatson already implemented a patch, so it will probably get integrated as soon as I can shift focus from 4.3.0 to 5.0.0.

**Comment by alexreg** [comment]
Okay, sounds good. So then, just linking with `libjemalloc` should sort out this issue, with no extra work?

**Comment by jasone** [comment]
Yes, that's the idea.  We're bound to have to work out some kinks on some platform or another, but AFAIK it's workable.

**Comment by alexreg** [comment]
Thanks for the update. I’ll wait for things to settle then.
