### ISSUE TITLE
jemalloc lead to crash in numa

### ISSUE THREAD

**Issue by maliangzhu** [jemalloc/jemalloc#2053]
I use jemalloc in my program ( a database like clickhouse ), and  complie with "percpu_arena:percpu,muzzy_decay_ms:10000"
When I run my program with "numactrl --cpunodebind=0 my_program", my program my be crash within 10 minutes.
The crash stack looks like shared_ptr address is double freeed.
When I compile jemalloc with default option(without percpu_arena:percpu,muzzy_decay_ms:10000), my program works well.

Also, I found the follow commit seemed fix the problem, but I don't know why

```
commit 20140629b44f9a76241749b9c47e3905202d034c (HEAD)
Author: David Goldblatt <davidgoldblatt@fb.com>
Date:   Mon Feb 1 12:03:11 2021 -0800

    Bin: Move stats closer to the mutex.
```

**Comment by interwq** [comment]
This still sounds like heap corruption; the specific config with NUMA / arena / decay settings likely just happens to trigger the issue often.

The commit 20140629b44f9a76241749b9c47e3905202d034c was a simple reordering to optimize locality, and won't really affect behavior correctness-wise. I'd suggest trying out sanitizers like ASAN first, and if that doesn't workout, try the running the debug build (i.e. configure with `--enable-debug).

**Comment by maliangzhu** [comment]
With debug version, I found the bug:

 
```
lscpu
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
```

```c
a.c
int main()
{
    ....
     malloc(100);
     ...
}
```
Compile a.c with "percpu_arena:percpu,muzzy_decay_ms:10000" ...

run with
```
numactrl --cpunodebind=0 ./a.out
assert(ind <= narenas_total_get());  //e.g. 40 <= 32
````

'ind' is the current thread's cpu which calculated by `sched_getcpu`
narenas_total_get is the total available cpu which calculated by
```c
malloc_ncpus
{
     result = CPU_COUNT(&set);   //32
}
 
(gdb) p/x set
$3 = {
  __bits = {0x5555555555555555,	0x0 <repeats 15 times>}
}

```




BTW, in the latest version(include ), the bug still exists
