### ISSUE TITLE
crash in numa

### ISSUE THREAD

**Issue by maliangzhu** [jemalloc/jemalloc#2054]
With debug version, I found the bug:

 
```
lscpu
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
```

```c
a.c
int main()
{
    ....
     malloc(100);
     ...
}
```
Compile a.c with "percpu_arena:percpu,muzzy_decay_ms:10000" ...

run with
```
numactrl --cpunodebind=0 ./a.out
assert(ind <= narenas_total_get());  //e.g. 40 <= 32
````

'ind' is the current thread's cpu which calculated by `sched_getcpu`
narenas_total_get is the total available cpu which calculated by
```c
malloc_ncpus
{
     result = CPU_COUNT(&set);   //32
}
 
(gdb) p/x set
$3 = {
  __bits = {0x5555555555555555,	0x0 <repeats 15 times>}
}

```

BTW, in the latest version(include 20140629b4 ), the bug still exists

_Originally posted by @maliangzhu in https://github.com/jemalloc/jemalloc/issues/2053#issuecomment-816491118_

**Comment by interwq** [comment]
Forgot about this case: the current percpu_arena implementation doesn't work nicely with explicit CPU affinity. There is a quick workaround, by specifying narenas as well, see https://github.com/jemalloc/jemalloc/blob/dev/src/jemalloc.c#L1900-L1913

For example, if you know the system has 64 cores, you can add `narenas:64` to MALLOC_CONF which will make it work with percpu arena.

**Comment by interwq** [comment]
Closing but feel free to ask anything. No need to create new thread.

**Comment by Bouncner** [comment]
As far as I can tell, the behavior is still the same with the latest release of jemalloc. Are there any plans to address this issue?

We are frequently binding our software to single NUMA nodes and would like to use `percpu_arena`. The workaround above (setting `narenas` to cores) apparently works, but we were surprised to see that you recommend setting it to the number of cores (which also automatically happens) while the documentation states that it defaults to `cores * 4`.

Can you explain that? Are we misinterpreting the documentation?
