### ISSUE TITLE
[Request] Take advantage of MAP_FIXED_NOREPLACE

### ISSUE THREAD

**Issue by Sonicadvance1** [jemalloc/jemalloc#2055]
Similar to #1251 but for Linux.
Should be relatively straightforward to support. Just needs someone that knows the code well enough to take advantage of it.
Also means that you would need kernel 4.17 and greater to use this path once compiled in.

**Comment by interwq** [comment]
Currently there's not enough benefits from this (mmap with addr != NULL is rarely used); more details in #2189.
