### ISSUE TITLE
Where to find the map between Threads and Arenas

### ISSUE THREAD

**Issue by zegang** [jemalloc/jemalloc#2057]
I am using Freebsd and got a core. Not found which records the map/assignment between Threads and Arenas. Checked following points.
1. Global TSDs list: not record thread-ID.
` (gdb) p tsd_nominal_tsds.qlh_first;`
2. Arenas: last_thd = 0x0
```
(gdb) p __je_arenas
$3 = {{repr = 0x802c00980}, {repr = 0x8034008c0}, ...
(gdb) p *((arena_t*)__je_arenas[0].repr)
$4 = {nthreads = {{repr = 1}, {repr = 1}}, binshard_next = {repr = 47}, last_thd = 0x0, ...
```
3. Thread Local Storage TSD: unable to access
```
(gdb) p __je_tsd_tls
Cannot find thread-local variables on this target
```
BTY, I also tried project '[shadow](https://github.com/CENSUS/shadow)'. It does not work for Freebsd.

**Comment by interwq** [comment]
To get the information programmatically, there is the [thread.arena mallctl](http://jemalloc.net/jemalloc.3.html#thread.arena).

jemalloc stores the associated arena for each thread in their TSD (e.g. through `tsd_arena_get`). However not sure if you can easily access it from a core. Maybe try a debug build will help?

**Comment by zegang** [comment]
> To get the information programmatically, there is the [thread.arena mallctl](http://jemalloc.net/jemalloc.3.html#thread.arena).
> 
> jemalloc stores the associated arena for each thread in their TSD (e.g. through `tsd_arena_get`). However not sure if you can easily access it from a core. Maybe try a debug build will help?
1. 'tsd_nominal_tsds' records a list of TSD pointers. Not sure whether it records the real/latest status.
2. Even we can access a TSD from 'tsd_nominal_tsds'. Not found any reference to the thread which associated with it. Can we get the thread from TSD ?
3. Just expected to check whether existing memory leak or not and where from a core dump file.

**Comment by interwq** [comment]
The tsd list isn't intended for data-accessing across threads, but rather a way of delivering internal notifications. I don't think we record the thread_t in the tsd.

If your intention is to debug memory leak through thread to arena internals, it's not an effective way. There are some raw counters within the arenas, but they are far away from telling you where the memory leak comes from. You will need to the profiling feature, which will sample stack traces.

Closing but feel free to ask.
