### ISSUE TITLE
Why does jemalloc take more time to allocate 4096 bytes of memory than other SMALL memory?

### ISSUE THREAD

**Issue by hsueh-yh** [jemalloc/jemalloc#2058]
jemalloc-5.2.0
# Test results:
Use [google benchmark](https://github.com/google/benchmark) with multithreaded test (24threads).

```(c)
Run on (32 X 3400 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 256 KiB (x16)
  L3 Unified 20480 KiB (x2)
Load Average: 15.72, 14.21, 14.26
-----------------------------------------------------------------------------------------
Benchmark                                               Time             CPU   Iterations
-----------------------------------------------------------------------------------------
BM_SomeFunction/1792/iterations:500/threads:24      0.095 ms         2.12 ms        12000
BM_SomeFunction/1856/iterations:500/threads:24      0.175 ms         4.10 ms        12000
BM_SomeFunction/1920/iterations:500/threads:24      0.178 ms         4.13 ms        12000
BM_SomeFunction/1984/iterations:500/threads:24      0.177 ms         4.14 ms        12000
BM_SomeFunction/2048/iterations:500/threads:24      0.181 ms         4.18 ms        12000
BM_SomeFunction/2048/iterations:500/threads:24      0.177 ms         4.16 ms        12000
BM_SomeFunction/2176/iterations:500/threads:24      0.116 ms         2.67 ms        12000
BM_SomeFunction/2304/iterations:500/threads:24      0.113 ms         2.64 ms        12000
BM_SomeFunction/2432/iterations:500/threads:24      0.118 ms         2.75 ms        12000
BM_SomeFunction/2560/iterations:500/threads:24      0.113 ms         2.65 ms        12000
BM_SomeFunction/2560/iterations:500/threads:24      0.114 ms         2.68 ms        12000
BM_SomeFunction/2688/iterations:500/threads:24      0.133 ms         3.13 ms        12000
BM_SomeFunction/2816/iterations:500/threads:24      0.132 ms         3.08 ms        12000
BM_SomeFunction/2944/iterations:500/threads:24      0.131 ms         3.09 ms        12000
BM_SomeFunction/3072/iterations:500/threads:24      0.132 ms         3.10 ms        12000
BM_SomeFunction/3072/iterations:500/threads:24      0.132 ms         3.11 ms        12000
BM_SomeFunction/3200/iterations:500/threads:24      0.117 ms         2.72 ms        12000
BM_SomeFunction/3328/iterations:500/threads:24      0.113 ms         2.66 ms        12000
BM_SomeFunction/3456/iterations:500/threads:24      0.111 ms         2.61 ms        12000
BM_SomeFunction/3584/iterations:500/threads:24      0.112 ms         2.63 ms        12000
BM_SomeFunction/3584/iterations:500/threads:24      0.112 ms         2.63 ms        12000
BM_SomeFunction/3712/iterations:500/threads:24      0.271 ms         6.35 ms        12000
BM_SomeFunction/3840/iterations:500/threads:24      0.270 ms         6.35 ms        12000
BM_SomeFunction/3968/iterations:500/threads:24      0.274 ms         6.42 ms        12000
BM_SomeFunction/4096/iterations:500/threads:24      0.276 ms         6.49 ms        12000
BM_SomeFunction/4096/iterations:500/threads:24      0.273 ms         6.41 ms        12000
BM_SomeFunction/4352/iterations:500/threads:24      0.151 ms         3.53 ms        12000
BM_SomeFunction/4608/iterations:500/threads:24      0.146 ms         3.45 ms        12000
BM_SomeFunction/4864/iterations:500/threads:24      0.142 ms         3.36 ms        12000
BM_SomeFunction/5120/iterations:500/threads:24      0.144 ms         3.40 ms        12000
BM_SomeFunction/5120/iterations:500/threads:24      0.146 ms         3.40 ms        12000
BM_SomeFunction/5376/iterations:500/threads:24      0.196 ms         4.57 ms        12000
BM_SomeFunction/5632/iterations:500/threads:24      0.187 ms         4.39 ms        12000
BM_SomeFunction/5888/iterations:500/threads:24      0.191 ms         4.47 ms        12000
BM_SomeFunction/6144/iterations:500/threads:24      0.188 ms         4.39 ms        12000
```

test report:

```(c)
BM_SomeFunction/1792/iterations:500/threads:24      0.095 ms         2.12 ms        12000
```

means allocating 1792 byte of memory consumes 2.12 ms CPU time.

Test memory size refs [size classes](http://jemalloc.net/jemalloc.3.html#size_classes)

# Test code
```(c++)
#include "benchmark/benchmark.h"
#include "jemalloc/jemalloc.h"

static size_t kBatchSize = 10000;

static void alloc_mem_n(size_t size) {
    std::vector<char*> kVec(kBatchSize, 0);
    for (int i = 0; i < kBatchSize; ++i) {
        auto p = new char[size];
        p[0] = i;
        benchmark::ClobberMemory();
        kVec[i] = p;
    }
    for (auto &p : kVec) {
        delete p;
        p = nullptr;
    }
}

static void BM_SomeFunction(benchmark::State& state) {
    for (auto _ : state) {
        alloc_mem_n(state.range(0));
    }
}


BENCHMARK(BM_SomeFunction)
    ->Unit(benchmark::kMillisecond)
    ->Iterations(500)
    ->Threads(24)
    ->DenseRange(1792, 2048, 64)
    ->DenseRange(2048, 2560, 128)
    ->DenseRange(2560, 3072, 128)
    ->DenseRange(3072, 3584, 128)
    ->DenseRange(3584, 4096, 128)
    ->DenseRange(4096, 5120, 256)
    ->DenseRange(5120, 6144, 256);

BENCHMARK_MAIN();
```

**Comment by romiguan** [comment]
@jasone @davidtgoldblatt  would you plz help to see this issue?

**Comment by interwq** [comment]
Among the sizes benchmarked, the special thing about the 4K size class, is that each 4K allocation is a slab on its own, i.e. the slab contains only 1 [region](http://jemalloc.net/jemalloc.3.html#arenas.bin.i.nregs). The malloc flow tries allocating from the `bin` first, and if there's no partially used slabs in the bin, try the next level which is the page cache. For the 4K size class, there will never be any partially used slabs, meaning it always has to go down to the page cache level, which likely explains the higher cost here. On the other hand, the benefit of this is, the 4k size class will have no fragmentation / always 100% utilized.

I wouldn't really consider this an issue, but rather an implementation artifact. I also want to mention that, tight loop benchmarks like this one, although they have their merits, do tend to exaggerate the difference. In a production workload (especially with thread cache), the difference between the 4K and other sizes should be minimal.

**Comment by romiguan** [comment]
@interwq thanks a lot for the explanation. It is really an issue in our production env, allocating 4KB memory w/ multi-threads is slower than other size class. 
Would you like to point out the source code? We'd like to dive into the code.

**Comment by interwq** [comment]
Do you have thread cache enabled (which is the case by default)? With the local cache, the extra overhead really should be amortized and not a concern anymore. If you can share the output of `malloc_stats_print()`, I can take a look to see if anything strange is going on.

Also, you may want to try `perf record` which is very helpful doing performance investigations. microbenchmarks can certainly be misleading.

**Comment by interwq** [comment]
re: the code path -- this is the function refilling thread cache https://github.com/jemalloc/jemalloc/blob/12cd13cd418512d9e7596921ccdb62e25a103f87/src/arena.c#L817

All small size classes share the path. The special part about the 4K class, is that it always goes down to the `arena_bin_refill_slabcur_with_fresh_slab` part.

Although I still suggest looking at the stats, config, or the `perf record` method first.

**Comment by romiguan** [comment]
> Do you have thread cache enabled (which is the case by default)? With the local cache, the extra overhead really should be amortized and not a concern anymore. If you can share the output of `malloc_stats_print()`, I can take a look to see if anything strange is going on.
> 
> Also, you may want to try `perf record` which is very helpful doing performance investigations. microbenchmarks can certainly be misleading.

Our prodction system is a  search system w/ high traffic, the issue is when adding members to  a core data structure(containing members for feature calculation), when exceeding 35xx bytes(would be round to 4K-Byte) , the performance downgrade is about 6-8%.

**Comment by romiguan** [comment]
> re: the code path -- this is the function refilling thread cache
> 
> https://github.com/jemalloc/jemalloc/blob/12cd13cd418512d9e7596921ccdb62e25a103f87/src/arena.c#L817
> 
> All small size classes share the path. The special part about the 4K class, is that it always goes down to the `arena_bin_refill_slabcur_with_fresh_slab` part.
> 
> Although I still suggest looking at the stats, config, or the `perf record` method first.

Thanks a lot for the reply. The perf record shows page fault is high, the detail output will be provided later.
