### ISSUE TITLE
jeprof svg report doesn't show function names 

### ISSUE THREAD

**Issue by wenlongkang** [jemalloc/jemalloc#2061]
Hello,I'm trying to debug a memory leak in some vendor-provided JNI/native code for my java application and run  command to generate the .svg

/data1/xxx/jemalloc-5.2.1/bin/jeprof --show_bytes --svg /usr/jdk1.8.0_121/bin/java jeprof.12.999.i999.heap > ./app-profiling333.svg  

![vvv](https://user-images.githubusercontent.com/8955753/116025731-c4f13200-a683-11eb-9b8a-b823c7733f1c.png)

Why is the function address displayed instead of the function name？

**Comment by wenlongkang** [comment]
export MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:17,prof_prefix:/data1/xxx/logs/jeprof.out
export LD_PRELOAD=/data1/xxx/logs/jemalloc-5.2.1/lib/libjemalloc.so

[root@13-112-125-bx-core logs]# java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

and I use jemalloc/jeprof in the docker container

**Comment by benet96** [comment]
Jeprof uses addr2line and nm to resolve symbol. Maybe your binutils' version is too old for binary. I update binutils to jeprof and it works.
