### ISSUE TITLE
Access violation reading location on Windows

### ISSUE THREAD

**Issue by sangshuduo** [jemalloc/jemalloc#2063]
Hello,

I am working on replace standard memory allocator with jemalloc on a Windows project.

I built the dll and lib with Visual Studio 2019 according to official document. BTW, the visual studio project's configuration type is Dynamic Library (.dll). I got both jemallocd.dll and jemalloc.lib. I have changed the configuration type to Static library. But the build failed. Now I link the static library and put the dll file to the folder where program is.

I use following macros to keep original source code unchanged as less as possible.

```
// define to jemalloc
#define malloc(size) je_malloc(size)
#define calloc(nmemb, size) je_calloc(nmemb, size)
#define realloc(ptr, size) je_realloc(ptr, size)
#define free(ptr) je_free(ptr) 
```

Now the build seems smooth. But when I execute the execution file, a command line program. It be terminated unexpectedly.

I run Visual Studio debugger to debug it. I see the error happen when it call free(). The error message is:

```
Unhandled exception at 0x00007FF8E68CF9ED (jemallocd.dll) in myprog.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

any idea?

Thanks,

**Comment by sangshuduo** [comment]
found out that happened because it tries to free a pointer allocated by getline().

**Comment by constructor-igor** [comment]
> found out that happened because it tries to free a pointer allocated by getline().

Hi, please, could you help?
Probably, we have same issue.
I don't understand answer.

```
version: 5.3.0

call stack:
             jemalloc.dll!tcache_bin_flush_edatas_lookup(tsd_s * tsd, cache_bin_ptr_array_s * arr, unsigned int binind, unsigned __int64 nflush, emap_batch_lookup_result_u * edatas) Line 288             C
             [Inline Frame] jemalloc.dll!tcache_bin_flush_impl(tsd_s * nflush, tcache_s *) Line 331       C
             [Inline Frame] jemalloc.dll!tcache_bin_flush_bottom(tsd_s *) Line 519        C
             jemalloc.dll!tcache_bin_flush_small(tsd_s * tsd, tcache_s * tcache, cache_bin_s * cache_bin, unsigned int binind, unsigned int rem) Line 529              C
             jemalloc.dll!tcache_gc_small(tsd_s * tsd, tcache_slow_s * tcache_slow, tcache_s * tcache, unsigned int szind) Line 148       C
             jemalloc.dll!tcache_event(tsd_s * tsd) Line 194  C
             jemalloc.dll!te_event_trigger(tsd_s * tsd, te_ctx_s * ctx) Line 299              C
             jemalloc.dll!free_default(void * ptr) Line 2978    C

line: 
              je_free(p)
              
error:
              Exception thrown at 0x00007FFDCE415060 (jemalloc.dll) in ConsoleTestRunner.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

```

**Comment by guangli-dai** [comment]
@constructor-igor This error trace is most possibly caused by freeing an invalid pointer. This means 2 potential cases:
1. The pointer freed is not allocated by jemalloc. Another memory allocator is the one allocating this pointer and should be freed within that memory allocator's scope;
2. The pointer freed was already freed before this free (a double-free error).
