### ISSUE TITLE
any plan to provide "make uninstall"?

### ISSUE THREAD

**Issue by sangshuduo** [jemalloc/jemalloc#2074]
It makes life easy.

**Comment by davidtgoldblatt** [comment]
I'm insufficiently knowledgeable of the packaging systems we use to write such a PR, but I'm happy to review one.

**Comment by sangshuduo** [comment]
I found a closed PR #296 that was submitted in 2016. I am working to include jemalloc in a time-series database (https://github.com/taosdata/TDengine) and need often to remove installed files manually. I guess other developers have to do that too.

I can submit another PR soon if it's welcomed now.

BTW, thanks for all's contributions to the jemalloc. It's really cool and helps other memory-intensive software greater.

**Comment by sangshuduo** [comment]
here you go #2075

**Comment by sleepreading** [comment]
I think it will be very helpful to have this feature.

**Comment by Lapenkov** [comment]
https://github.com/jemalloc/jemalloc/commit/640c3c72e661ec0b3f20865ee4fd4363644c017a implements the uninstall
