### ISSUE TITLE
epoch mallctl overhead

### ISSUE THREAD

**Issue by czpmango** [jemalloc/jemalloc#2077]
I want to limit the process's memory usage to avoid OOM risk, so I collect memory usage information at run time and compare it with the preset memory thresholds.

I got these stats using mallctl API. But `epoch mallctl` brings overhead than I expected,:
```
mallctl("epoch", 0, 0, &epoch, sz);
mallctl("stats.allocated", &(process_memory_info_->allocated), &sz, NULL, 0);
mallctl("stats.resident", &(process_memory_info_->resident), &sz, NULL, 0);
...
if (process_memory_info_->resident > memory_limit_by_user) {
  // do some things
}
...
```
Am I correct? Or are there better alternatives to do it?

**Comment by davidtgoldblatt** [comment]
You're right; `epoch` calls are fairly heavyweight. The intent is that they happen intermittently (e.g. with updates only occuring at some periodic interval), with processes using the cached values in between.

(These semantics aren't ideal, but it's not necessarily easy to make it unconditionally fast).

**Comment by czpmango** [comment]
Thank you for reply. That helps a lot! 

I also built jemalloc with the `--disable-stats` and `--enable-stats`(by default) options for performance testing, and found that the latter had more overhead. Does this mean it(--enable-stats) should never be used at run time in production?
Do you have a more accurate and comprehensive assessment of the overhead caused by this compilation option in more scenarios? And what is the specific difference when I compile with `--enable-stats`?

Intermittent access to statistics is also acceptable and useful to me if `--enable-stats` does not bring too much performance degradation to my system.
Also, is there some more fine-grained interface to get memory statistics(beacuse I may only care about one or two memory metrics)?

**Comment by interwq** [comment]
In our production setup, `--enable-stats` don't add too much overhead. It's certainly measurable in micro-benchmarks, but the difference is usually amplified in these cases. We do enable stats in our production settings.

Making frequent `epoch` calls, like David mentioned, can cause noticeable slowdowns in real world applications (since it refreshes stats globally). Our suggestion would be to rate-limit the stats reading (e.g. 10 times / sec should be fine).

Closing but feel free to ask anything.

**Comment by czpmango** [comment]
@interwq How to rate-limit the stats reading? I did not find relevant documents.

**Comment by davidtgoldblatt** [comment]
I.e. just calling (say) `clock_gettime()`, and only doing the `epoch` mallctl if more than some fixed number of milliseconds have elapsed; otherwise, return the cached stats value *without* an `epoch` call.

**Comment by czpmango** [comment]
> the cached stats value _without_ an `epoch` call.

That's a good idea :)
