### ISSUE TITLE
RSS 6GB，jemalloc resident only 2GB

### ISSUE THREAD

**Issue by amjy** [jemalloc/jemalloc#2080]
**proc pid status**
VmPeak: 26714096 kB
VmSize: 14663924 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:   7004388 kB
VmRSS:   6708500 kB
VmData:  8493240 kB
VmStk:       272 kB
VmExe:     32332 kB
VmLib:     26736 kB
VmPTE:     16172 kB

**malloc_stats_print**
Allocated: 1917463712, active: 1958727680, metadata: 146305824 (n_thp 0), resident: 2116513792, mapped: 2123427840, retained: 6504779776
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
background_thread                   4       0               0       0               0       0               1       0               0         0               0           0
ctl                                 2       0               0       0               0       0               1       0               0         0               0           0
prof                          1781236      12               0       0               0       0               1       0               0         0               0           0
Merged arenas stats:
assigned threads: 1
uptime: 143912233762692
dss allocation precedence: "N/A"
decaying:  time       npages       sweeps     madvises       purged
   dirty:   N/A         2834       210113     88774320    262385159
   muzzy:   N/A            0            0            0            0
                            allocated         nmalloc (#/sec)         ndalloc (#/sec)       nrequests   (#/sec)           nfill   (#/sec)          nflush   (#/sec)
small:                     1433099424      1779487179   12365      1766475378   12274      2290945811     15919       179229645      1245       148711722      1033
large:                      484364288        11103902      77        11097733      77        18216044       126        11103902        77               0         0
total:                     1917463712      1790591081   12442      1777573111   12351      2309161855     16045       190333547      1322       148711722      1033

active:                    1958727680
mapped:                    2123427840
retained:                  6504779776
base:                       146173344
internal:                      132480
metadata_thp:                       0
tcache_bytes:                  210168
resident:                  2116513792
abandoned_vm:                       0
extent_avail:                  625663

**malloc_stats**
Arena 0:
system bytes     = 0
in use bytes     =  0
Total (incl. mmap):
system bytes     = 0
in use bytes     =  0
max mmap regions = 0
max mmap bytes   = 0

**Comment by interwq** [comment]
The `VmSize` is ~14G, which is much higher than jemalloc managed virtual memory (mapped + retained ~8.5G). Please check if there are directly mapped regions / not allocated through jemalloc in the binary.

**Comment by amjy** [comment]
Shared memory mmap() without jemalloc, ~6G `VmSize` but only ~100M `Rss`

jemalloc managed virtual memory (mapped + retained ~8.5G)  == total vm (14.6G) - SHM (6G)

``cat smap | grep ^Size| awk '{sum += $2};END {print sum " KB"}'``
14663928 KB

``cat smap | grep ^Rss| awk '{sum += $2};END {print sum " KB"}'``
6687908 KB

``grep "/dev/zero" smap -A15| grep ^Size| awk '{sum += $2};END {print sum " KB"}'``
6068696 KB

``grep "/dev/zero" smap -A15| grep ^Rss| awk '{sum += $2};END {print sum " KB"}'``
95156 KB

``grep "/dev/zero" smap -A15| grep VmFlags| sort| uniq``
VmFlags: rd wr **sh** mr mw me ms

**Comment by amjy** [comment]
jemalloc version 5.2.1

**Comment by interwq** [comment]
Nothing in the malloc stats jumps out. If you want to double check that the purged pages (i.e. retained) are not accessed by the application, you can add `retain:false` to MALLOC_CONF in which case the purged virtual address space will be unmapped.

You may also want to check if the huge pages are used somehow.
