### ISSUE TITLE
use docker cpu count 

### ISSUE THREAD

**Issue by 0x007004** [jemalloc/jemalloc#2085]
the server run at docker,  the physical machine has 64 cores, and I use only 8 cores,  can I replace the cpu count by the docker env cpu count in my project , the code at here  https://github.com/jemalloc/jemalloc/blob/5.1.0/src/jemalloc.c#L731 , I want replace the variable "result",  will this have a problem.

**Comment by davidtgoldblatt** [comment]
Seems reasonable to me, so long as the cpu counts returned by malloc_getcpu and your modified version correspond.

**Comment by 0x007004** [comment]
Thanks
