### ISSUE TITLE
adding jemalloc to a production business webapp.

### ISSUE THREAD

**Issue by rhtaylor** [jemalloc/jemalloc#2090]
The company is growing and having scaling issues with memory on Heroku. Jemalloc is the obvious solution to this issue. 

**Question:** Will there be any side effects from switching to jemalloc such as a dump of the database?  

Memory allocation is just a fundamental and low level part of the application an I do not see much on this issue.

**Comment by davidtgoldblatt** [comment]
In general, absent things like heap corruption bugs or the like, jemalloc should be a drop-in replacement for (e.g.) glibc malloc. There shouldn't be noticeable changes outside of things like operation timing, memory effects, etc.

**Comment by davidtgoldblatt** [comment]
Closing, but feel free to ask if there are any followup questions.
