### ISSUE TITLE
it takes up a lot of memory when QT application  use -ljemalloc build  in servers with large memory

### ISSUE THREAD

**Issue by panchenbo** [jemalloc/jemalloc#2093]
demo src:
[testJemalloc.zip](https://github.com/jemalloc/jemalloc/files/6845345/testJemalloc.zip)

whitout -ljemalloc:
![image](https://user-images.githubusercontent.com/75836904/126259910-8a398673-753e-4a90-9991-57f44fec5776.png)
with -ljemalloc:
![image](https://user-images.githubusercontent.com/75836904/126260006-0ff161b5-cd3e-4695-bb3a-48569c0cb9d4.png)

**Comment by davidtgoldblatt** [comment]
Not a ton to go on here; one guess is that time-based decay isn't being triggered because the application isn't doing any work. Retrying with background threads on or decay settings changed may help.

If you post the malloc stats we could take a look as well.

**Comment by GongHeng2017** [comment]
hi,
    My question is similar to the above, my have Cmake project demo and detailed data.
cmake project demo:
[project_cmake.zip](https://github.com/jemalloc/jemalloc/files/6859872/project_cmake.zip)

data:

$ uname -r
4.19.90-2009.3.0.0045.up1.uel20.aarch64
$ getconf PAGESIZE
65536
$ grep Hugepagesize /proc/meminfo
Hugepagesize:     524288 kB
$ grep CONFIG_ARM64_64K_PAGES /boot/config-$(uname -r)
CONFIG_ARM64_64K_PAGES=y

top result:
without jemalloc:
    VIRT        RES     SHR     S       %CPU        %MEM
    521280      61248   1472    S       0.0         0.1

top result:
without jemalloc:
    VIRT        RES     SHR     S       %CPU        %MEM
    521280      61248   1472    S       0.0         0.1

use jemalloc:
    VIRT        RES     SHR     S       %CPU        %MEM
    1710848     1.0g    2432    S       0.0         1.6

malloc_stats_print:
___ Begin jemalloc statistics ___
Version: "5.1.0-0-g61efbda7098de6fe64c362d309824864308c36d4"
Build-time option settings
  config.cache_oblivious: true
  config.debug: false
  config.fill: true
  config.lazy_lock: false
  config.malloc_conf: ""
  config.prof: false
  config.prof_libgcc: false
  config.prof_libunwind: false
  config.stats: true
  config.utrace: false
  config.xmalloc: false
Run-time option settings
  opt.abort: false
  opt.abort_conf: false
  opt.retain: true
  opt.dss: "secondary"
  opt.narenas: 384
  opt.percpu_arena: "disabled"
  opt.metadata_thp: "disabled"
  opt.background_thread: false (background_thread: false)
  opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
  opt.muzzy_decay_ms: 10000 (arenas.muzzy_decay_ms: 10000)
  opt.junk: "false"
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.thp: "default"
  opt.stats_print: false
  opt.stats_print_opts: ""
Arenas: 384
Quantum size: 16
Page size: 65536
Maximum thread-cached size class: 229376
Number of bin size classes: 52
Number of thread-cache bin size classes: 52
Number of large size classes: 180
Allocated: 564126504, active: 615841792, metadata: 9253440 (n_thp 0), resident: 625082368, mapped: 1152712704, retained: 592117760
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
background_thread                   4               0               0               1               0               0           0
ctl                                 2               0               0               1               0               0           0
prof                                0               0               0               0               0               0           0
arenas[0]:
assigned threads: 1
uptime: 127530046486
dss allocation precedence: "secondary"
decaying:  time       npages       sweeps     madvises       purged
   dirty: 10000            0            0            0            0
   muzzy: 10000            0            0            0            0
                            allocated     nmalloc     ndalloc   nrequests
small:                       38265640         830           0         132
large:                      525860864         775           0         775
total:                      564126504        1605           0         907
                                     
active:                     615841792
mapped:                    1152712704
retained:                   592117760
base:                         9196088
internal:                       57352
metadata_thp:                       0
tcache_bytes:                10161944
resident:                   625082368
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
large                               2               0               0               1               0               0           0
extent_avail                      941               0               0               3               0               0           0
extents_dirty                     939               0               0               3               0               0           0
extents_muzzy                     939               0               0               3               0               0           0
extents_retained                 1876               0               0               3               0               0           0
decay_dirty                         2               0               0               1               0               0           0
decay_muzzy                         2               0               0               1               0               0           0
base                             1335               0               0               3               0               0           0
tcache_list                         3               0               0               1               0               0           0
bins:           size ind    allocated      nmalloc      ndalloc    nrequests      curregs     curslabs regs pgs   util       nfills     nflushes       nslabs     nreslabs      n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
                   8   0          808          101            0            1          101            1 8192   1  0.012            1            0            1            0               5               0               0               1               0               0           0
                  16   1            0            0            0            0            0            0 4096   1      1            0            0            0            0               2               0               0               1               0               0           0
                  32   2            0            0            0            0            0            0 2048   1      1            0            0            0            0               2               0               0               1               0               0           0
                  48   3            0            0            0            0            0            0 4096   3      1            0            0            0            0               2               0               0               1               0               0           0
                  64   4            0            0            0            0            0            0 1024   1      1            0            0            0            0               2               0               0               1               0               0           0
                  80   5            0            0            0            0            0            0 4096   5      1            0            0            0            0               2               0               0               1               0               0           0
                  96   6            0            0            0            0            0            0 2048   3      1            0            0            0            0               2               0               0               1               0               0           0
                 112   7            0            0            0            0            0            0 4096   7      1            0            0            0            0               2               0               0               1               0               0           0
                 128   8            0            0            0            0            0            0  512   1      1            0            0            0            0               2               0               0               1               0               0           0
                 160   9            0            0            0            0            0            0 2048   5      1            0            0            0            0               2               0               0               1               0               0           0
                 192  10            0            0            0            0            0            0 1024   3      1            0            0            0            0               2               0               0               1               0               0           0
                 224  11            0            0            0            0            0            0 2048   7      1            0            0            0            0               2               0               0               1               0               0           0
                 256  12            0            0            0            0            0            0  256   1      1            0            0            0            0               2               0               0               1               0               0           0
                 320  13            0            0            0            0            0            0 1024   5      1            0            0            0            0               2               0               0               1               0               0           0
                 384  14            0            0            0            0            0            0  512   3      1            0            0            0            0               2               0               0               1               0               0           0
                 448  15            0            0            0            0            0            0 1024   7      1            0            0            0            0               2               0               0               1               0               0           0
                 512  16            0            0            0            0            0            0  128   1      1            0            0            0            0               2               0               0               1               0               0           0
                 640  17            0            0            0            0            0            0  512   5      1            0            0            0            0               2               0               0               1               0               0           0
                 768  18            0            0            0            0            0            0  256   3      1            0            0            0            0               2               0               0               1               0               0           0
                 896  19            0            0            0            0            0            0  512   7      1            0            0            0            0               2               0               0               1               0               0           0
                     ---
                1024  20        65536           64            0            0           64            1   64   1      1            1            0            1            0               4               0               0               1               0               0           0
                1280  21            0            0            0            0            0            0  256   5      1            0            0            0            0               2               0               0               1               0               0           0
                1536  22            0            0            0            0            0            0  128   3      1            0            0            0            0               2               0               0               1               0               0           0
                1792  23            0            0            0            0            0            0  256   7      1            0            0            0            0               2               0               0               1               0               0           0
                     ---
                2048  24        65536           32            0            0           32            1   32   1      1            1            0            1            0               4               0               0               1               0               0           0
                2560  25            0            0            0            0            0            0  128   5      1            0            0            0            0               2               0               0               1               0               0           0
                     ---
                3072  26       196608           64            0            0           64            1   64   3      1            1            0            1            0               4               0               0               1               0               0           0
                3584  27            0            0            0            0            0            0  128   7      1            0            0            0            0               2               0               0               1               0               0           0
                     ---
                4096  28        65536           16            0            0           16            1   16   1      1            1            0            1            0               4               0               0               1               0               0           0
                5120  29       327680           64            0            0           64            1   64   5      1            1            0            1            0               4               0               0               1               0               0           0
                6144  30       196608           32            0            0           32            1   32   3      1            1            0            1            0               4               0               0               1               0               0           0
                7168  31       458752           64            0            0           64            1   64   7      1            1            0            1            0               4               0               0               1               0               0           0
                8192  32        81920           10            0            0           10            2    8   1  0.625            1            0            2            0               5               0               0               1               0               0           0
               10240  33       327680           32            0            0           32            1   32   5      1            1            0            1            0               4               0               0               1               0               0           0
               12288  34       196608           16            0            0           16            1   16   3      1            1            0            1            0               4               0               0               1               0               0           0
               14336  35       458752           32            0            0           32            1   32   7      1            1            0            1            0               4               0               0               1               0               0           0
               16384  36       163840           10            0            0           10            3    4   1  0.833            1            0            3            0               6               0               0               1               0               0           0
               20480  37       327680           16            0            0           16            1   16   5      1            1            0            1            0               4               0               0               1               0               0           0
               24576  38       245760           10            0            0           10            2    8   3  0.625            1            0            2            0               5               0               0               1               0               0           0
               28672  39       458752           16            0            0           16            1   16   7      1            1            0            1            0               4               0               0               1               0               0           0
               32768  40       327680           10            0            0           10            5    2   1      1            1            0            5            0               8               0               0               1               0               0           0
               40960  41       409600           10            0            0           10            2    8   5  0.625            1            0            2            0               5               0               0               1               0               0           0
               49152  42       491520           10            0            0           10            3    4   3  0.833            1            0            3            0               6               0               0               1               0               0           0
               57344  43       630784           11            0            1           11            2    8   7  0.687            1            0            2            0               6               0               0               1               0               0           0
               65536  44       655360           10            0            0           10           10    1   1      1            1            0           10            0              13               0               0               1               0               0           0
               81920  45      1638400           20            0           10           20            5    4   5      1            2            0            5            0               9               0               0               1               0               0           0
               98304  46      1966080           20            0           10           20           10    2   3      1            2            0           10            0              14               0               0               1               0               0           0
              114688  47      2293760           20            0           10           20            5    4   7      1            2            0            5            0               9               0               0               1               0               0           0
              131072  48      2621440           20            0           10           20           20    1   2      1            2            0           20            0              24               0               0               1               0               0           0
              163840  49      6553600           40            0           30           40           20    2   5      1            4            0           20            0              26               0               0               1               0               0           0
              196608  50      7864320           40            0           30           40           40    1   3      1            4            0           40            0              46               0               0               1               0               0           0
              229376  51      9175040           40            0           30           40           20    2   7      1            4            0           20            0              26               0               0               1               0               0           0
large:          size ind    allocated      nmalloc      ndalloc    nrequests  curlextents
              262144  52      8650752           33            0           33           33
              327680  53     20971520           64            0           64           64
              393216  54     25165824           64            0           64           64
              458752  55     29360128           64            0           64           64
              524288  56     34078720           65            0           65           65
              655360  57     83886080          128            0          128          128
              786432  58    101449728          129            0          129          129
              917504  59    117440512          128            0          128          128
             1048576  60    104857600          100            0          100          100
                     ---
--- End jemalloc statistics ---

**Comment by GongHeng2017** [comment]
@davidtgoldblatt

**Comment by Lapenkov** [comment]
Hello @GongHeng2017
Your demo project only allocates memory and doesn't touch it, so if your system implements demand paging, RSS of your process should not significantly change after these allocations.

If you change the amount of memory your demo program allocates, does it affect the RSS?

**Comment by Lapenkov** [comment]
Reopen if you still have the question.
