### ISSUE TITLE
Why a process allocated many non-huge-page memory using library jemalloc when the transparent huge page has been enabled?

### ISSUE THREAD

**Issue by elftech** [jemalloc/jemalloc#2099]
I've enable transparent huge page in a process who uses jemalloc for memory allocation, by following steps:

1. setting transparent huge page state to "madvice" :
```
echo madvise > /sys/kernel/mm/transparent_hugepage/enabled;
echo madvise > /sys/kernel/mm/transparent_hugepage/defrag;
```

2.setting jemalloc to always use thp
```
export MALLOC_CONF="thp:always,metadata_thp:always,dirty_decay_ms:-1";
```

Since the program only use jemalloc to allocate memory, the expected result should be that the size of memory used totally (RSS) is equal to the size of huge pages alloced. But it differs a lot, as items "AnonHugePages" and  "Rss" show below :
```
# cat /proc/<pid>/smaps |awk 'NF==3 {dict[$1]+=$2} END{for(key in dict) print key" "dict[key]}' 
Locked: 4
Shared_Clean: 18732
MMUPageSize: 8776
KernelPageSize: 8776
Pss: 150242778
Swap: 0
ShmemPmdMapped: 0
Shared_Dirty: 0
Size: 258068324
Private_Hugetlb: 0
Private_Dirty: 150234008
LazyFree: 0
Private_Clean: 124
Referenced: 147993656
VmFlags: 0
AnonHugePages: 76193792
Rss: 150252864
SwapPss: 0
Shared_Hugetlb: 0
Anonymous: 150232456
```

I know normal memory allocation (4k page) will occur if there is no enough huge page available in the operating system, adding one count to the item "thp_fault_fallback" in "/proc/vmstat". But the value is small as below snippet shows, meaning no so much non-huge-page-allocation happens:
```
# grep thp_fault_fallback /proc/vmstat 
thp_fault_fallback 2982
```

So, Why the gap between the size of RSS and THP?  Looking forward to some clues and advices.

**Comment by Lapenkov** [comment]
Disclaimer: I'm not a huge page expert, but I'll still try to help you.

1. The memory regions that we pass to `madvice` are not hugepage-aligned. In this case, the documentation says the following: "The kernel will regularly scan the areas marked as huge page candidates to replace them with huge pages". Meaning that it's up to the kernel when your allocations are backed by hugepages.
2. It would be nice if you could run `strace` and check if everything works correctly on your system and `madvice` is called after each `mmap`. It could be some bug in jemalloc that prevents `madvice` from being called, although I highly doubt it.

**Comment by Lapenkov** [comment]
To verify 1, you can try doing only hugepage-aligned allocations in your application, which should cause jemalloc to map hugepage-aligned regions, and kernel should back it by hugepages immediately according to the documentation.

**Comment by elftech** [comment]
@Lapenkov ， thank you for you replies. I've found the reason:  many small-sized objects are reclaimed by jemalloc in already allocated huge pages, resulting in splitting those pages into normal 4k pages.

There are two ways to solve this problem:
1) disable or delay jemalloc memory reclaim

**Comment by interwq** [comment]
Like you observed, the default jemalloc page allocator is not hugepage aware, and likely will cause huge page fragmentation if THP is set to always enabled. Longer decay time can alleviate the issue, but at a memory cost. We have an internal / experimental huge page allocator inside jemalloc in the work, but it may take a while for it to be officially announced.

Closing but feel free to ask if anything.

**Comment by elftech** [comment]
@interwq , ok. Looking forward to the offcially-announced day!

**Comment by elftech** [comment]
@interwq , How is the process of your experimental huge page allocator??  What's the benefits can be expected from it?

The new version 5.3.0 of jemalloc has been released recently.  But no news about improvement about thp allocation.

**Comment by aalbersk** [comment]
Hi @interwq, do you plan to release support to huge pages allocator in jemalloc in nearest future?
