### ISSUE TITLE
A lot of tests failed

### ISSUE THREAD

**Issue by Mingli-Yu** [jemalloc/jemalloc#2109]
\# rpm -qa|grep jemalloc
jemalloc-5.2.1-r0.corei7_64

\# ./tests/unit/binshard
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:136: Failed assertion: (nshards) == (16) --> 1 != 16: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:138: Failed assertion: (nshards) == (8) --> 1 != 8: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard:../git/test/unit/binshard.c:140: Failed assertion: (nshards) == (4) --> 1 != 4: Unexpected nshards
test_bin_shard (non-reentrant): fail
test_bin_shard_mt:../git/test/unit/binshard.c:101: Failed assertion: (sharded) == (true) --> false != true: Did not find s
test_bin_shard_mt (non-reentrant): fail
test_producer_consumer (non-reentrant): pass
--- pass: 1/3, skip: 0/3, fail: 2/3 ---

\# ./tests/unit/decay
test_decay_ticks:../git/test/unit/decay.c:228: Failed assertion: (tick1) != (tick0) --> 999 == 999: Expected ticker to ti)
test_decay_ticks:../git/test/unit/decay.c:235: Failed assertion: (tick1) != (tick0) --> 999 == 999: Expected ticker to ti)
test_decay_ticks:../git/test/unit/decay.c:262: Failed assertion: (tick1) != (tick0) --> 997 == 997: Expected ticker to ti)
test_decay_ticks:../git/test/unit/decay.c:273: Failed assertion: (tick1) != (tick0) --> 996 == 996: Expected ticker to ti)
test_decay_ticks (non-reentrant): fail
test_decay_ticks:../git/test/unit/decay.c:223: Failed assertion: (tick1) != (tick0) --> 1000 == 1000: Expected ticker to )
test_decay_ticks:../git/test/unit/decay.c:228: Failed assertion: (tick1) != (tick0) --> 1000 == 1000: Expected ticker to )
test_decay_ticks:../git/test/unit/decay.c:235: Failed assertion: (tick1) != (tick0) --> 1000 == 1000: Expected ticker to )
test_decay_ticks:../git/test/unit/decay.c:262: Failed assertion: (tick1) != (tick0) --> 998 == 998: Expected ticker to ti)
test_decay_ticks:../git/test/unit/decay.c:273: Failed assertion: (tick1) != (tick0) --> 997 == 997: Expected ticker to ti)
test_decay_ticks (libc-reentrant): fail
test_decay_ticks:../git/test/unit/decay.c:223: Failed assertion: (tick1) != (tick0) --> 1000 == 1000: Expected ticker to )
test_decay_ticks:../git/test/unit/decay.c:228: Failed assertion: (tick1) != (tick0) --> 1000 == 1000: Expected ticker to )
test_decay_ticks:../git/test/unit/decay.c:235: Failed assertion: (tick1) != (tick0) --> 1000 == 1000: Expected ticker to )
test_decay_ticks:../git/test/unit/decay.c:262: Failed assertion: (tick1) != (tick0) --> 998 == 998: Expected ticker to ti)
test_decay_ticks:../git/test/unit/decay.c:273: Failed assertion: (tick1) != (tick0) --> 997 == 997: Expected ticker to ti)
test_decay_ticks (arena_new-reentrant): fail
test_decay_ticker (non-reentrant): pass
test_decay_ticker (libc-reentrant): pass
test_decay_ticker (arena_new-reentrant): pass
test_decay_nonmonotonic (non-reentrant): pass
test_decay_nonmonotonic (libc-reentrant): pass
test_decay_nonmonotonic (arena_new-reentrant): pass
test_decay_now (non-reentrant): pass
test_decay_now (libc-reentrant): pass
test_decay_now (arena_new-reentrant): pass
test_decay_never (non-reentrant): pass
test_decay_never (libc-reentrant): pass
test_decay_never (arena_new-reentrant): pass
--- pass: 12/15, skip: 0/15, fail: 3/15 ---

**Comment by interwq** [comment]
If you want to manual run a test, do `sh test/test.sh test/unit/binshard` for example. Don't invoke the test binary direct which will miss the env var setup.

We suggest use `make check` which will run all tests (and will give repro commands if any failed).
