### ISSUE TITLE
mallctl dump seems failure

### ISSUE THREAD

**Issue by pengpengge** [jemalloc/jemalloc#2117]
My project introduced Jemalloc as a third-party library and enable prof, like this:
```
genrule(
    name = "jemalloc-build",
    srcs = glob(["**/*"], exclude=["bazel-*"]),
    outs = [
        "jemalloc-out/lib/libjemalloc.a",
        "jemalloc-out/lib/libjemalloc_pic.a",
        "jemalloc-out/bin/jemalloc.sh",
        "jemalloc-out/bin/jeprof",
        "jemalloc-out/include/jemalloc/jemalloc.h",
    ],
    cmd = "\n".join([
        "export INSTALL_DIR=$$(pwd)/$(@D)/jemalloc-out",
        "export TMP_DIR=$$(mktemp -d -t jemalloc.XXXXXX)",
        "mkdir -p $$TMP_DIR",
        "cp -R $$(pwd)/external/jemalloc/* $$TMP_DIR",
        "cd $$TMP_DIR",
        "./configure --prefix=$$INSTALL_DIR --enable-prof",
        "make install",
        "rm -rf $$TMP_DIR",
    ]),
)
```
Then I add environment variable"
```
export MALLOC_CONF="prof:true,prof_active:false,prof_prefix:jeprof.out,lg_prof_sample:0"
```
But When I get the dumped file, It seems not correct, like this picture. 
![image](https://user-images.githubusercontent.com/33371640/130591966-1b8d6388-1c19-4442-94b7-5d44292e7ad1.png)
And I use jeprof to get the parsed result, it can't get any thing but only two line.
![image](https://user-images.githubusercontent.com/33371640/130592374-bbdfde20-2ed5-46c1-a312-61cfcd238f0c.png)

I hope to get your help, Thanks!

My code to trigger the dump is like  this
```
  ::mallctl("prof.active", NULL, NULL, &active, sizeof(active));
  absl::SleepFor(duration);
  const char* fileName = prof_file_path.c_str();
  ::mallctl("prof.dump", NULL, NULL, &fileName, sizeof(const char*));
  active = false;
  ::mallctl("prof.active", NULL, NULL, &active, sizeof(active));
```

**Comment by Lapenkov** [comment]
It seems that your screenshot only shows the `MAPPED_LIBRARIES` part of your heap profile. There should be a part with stack traces above it. Does that part look correct? Does the file start with `heap_v2/1`?

What your screenshot shows is simply being read from `/proc/<PID>/task/<PID>/maps` (or `/proc/curproc/map` depending on the OS). Can you check the mappings of the process and confirm they're different from what is on your screenshot?

**Comment by Lapenkov** [comment]
Feel free to reopen if you still have the issue and are willing to provide additional information.
