### ISSUE TITLE
Compile failure when trying ported it to qnx 7.0

### ISSUE THREAD

**Issue by hbwang15** [jemalloc/jemalloc#2122]
jemalloc version: master
QNX version: 7.0
Platform: ARM64(aarch64)
Build Tools: QNX Software Development Platform (SDP 7.0, ntoaarch64-g++, ntoaarch64-gcc)

configure command: 
`QNX_BINS="/workspaces/mfrnode/cdc_mfr_node/.build/saic/_deps/cc_toolchain/qnx700/host/linux/x86_64/usr/bin"

./configure CC="${QNX_BINS}/qcc" CXX="${QNX_BINS}/QCC" CFLAGS="-fpic -Vgcc_ntoaarch64le" CXXFLAGS="-fpic -Vgcc_ntoaarch64le -Y_cxx" OS=qnx7 --target=aarch64-qnx-qnx --host=x86_64-linux-gnu RANLIB="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ranlib" AR="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ar" LD="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ld" LDCXX="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ld"`

error:
![企业微信截图_16305914353537](https://user-images.githubusercontent.com/65098776/131941672-5485405e-d0a6-479f-9c57-2ea949bfe03a.png)

It seems qnx don't have the syscall() api. so how can i do for fix this error.

**Comment by hbwang15** [comment]
i add an platfrom option for not including syscall header file. the compiler complain above disappeared, but then it comes to another compiler error as show below.
![企业微信截图_16305914353537](https://user-images.githubusercontent.com/65098776/131945116-dc150a86-84ed-40b6-b111-231a4ee9eccb.png)

**Comment by Howe2015** [comment]
can u build it for qnx? I failed too, pls help.

**Comment by Illidan-Stromrage** [comment]
sys/syscall.h failed +1

**Comment by tangzhiqiang3** [comment]
@hbwang15   Have you solved your problem? I also encountered the same problem
