### ISSUE TITLE
How to enable background_thread after fork

### ISSUE THREAD

**Issue by hwCloudRDS** [jemalloc/jemalloc#2125]
I notice that [this commit](https://github.com/jemalloc/jemalloc/commit/b83b5ad) disabled background_thread after fork. How can I re-enable it after fork?

**Comment by Lapenkov** [comment]
You can call `mallctl` in your child process to enable background thread there.
See [this example](https://github.com/jemalloc/jemalloc/blob/dev/test/unit/background_thread.c#L11)

**Comment by hwCloudRDS** [comment]
Thanks.
