### ISSUE TITLE
Features like Memory Pool and uma_init/uma_fini (FreeBSD UMA) in Jemalloc

### ISSUE THREAD

**Issue by zegang** [jemalloc/jemalloc#2126]
UMA Zone and configurable init/destroy functions are really useful features. We can book a Zone (memory pool) for identical structures/items.

Does Jemalloc have features like this ?

FYR: https://www.freebsd.org/cgi/man.cgi?query=uma&sektion=9

**Comment by Lapenkov** [comment]
Hello. Thank you for the question.

No, jemalloc doesn't support such functionality. It's only capable of allocating chunks of memory of requested size using internal size classes, without any knowledge of the objects and callbacks to initialize them.
