### ISSUE TITLE
prof: sample at every new highwater of memory usage?

### ISSUE THREAD

**Issue by luphye** [jemalloc/jemalloc#2127]
Hi,  as in jemalloc's documention,   "prof.gdump" dumps the sampled profiling data  "every time the total virtual memory exceeds the previous maximum". According to my understanding,  it only do the dumping job. Is there a way to  sample at every new highwater of memory usage,  and dump the "highwater-based sampling" data by mallctl interface?  
Like the '*GetHeapGrowthStacks()*' interface  in tcmalloc?  
I have searched for similar issues in this git, but found none;  Forgive for this question if any similar questions issused before.
thanks!

**Comment by Lapenkov** [comment]
Hello. Currently there is no way to sample only at highwater.

**Comment by luphye** [comment]
ok,  thanks for answer. Will support this feature in the future?

**Comment by Lapenkov** [comment]
There are currently no plans to implement this feature. Can you please provide your use case?

**Comment by luphye** [comment]
The use case is simple, while the 512k based sampling (or bigger sample rate but less accuracy ) may come with some overhead,  the "highwater-based sampling"  can provide a profile with little overhead because it will not be triggered frequently, thus makes it more suitable for long time running.  With the benefit of "prof_active",  one can get both high-resolution but temporal profiling data with "512k based sampling", and also low-resolution data with "highwater-based sampling".

**Comment by Lapenkov** [comment]
I see. Currently the only approach I can suggest is to play with `opt.lg_prof_sample` to find suitable overhead. Unless `opt.prof_accum` is enabled, all sampling data will be released once the sampled allocations are `free`d. So if your program doesn't keep most of `malloc`ed memory forever, you'll be able to achieve very low overhead with defined upper bound.
