### ISSUE TITLE
Failed assertion: "tbin->ncached < tbin_info->ncached_max"

### ISSUE THREAD

**Issue by dcci** [jemalloc/jemalloc#214]
% uname -a
FreeBSD foo 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r277486: Wed Jan 21 16:31:48 UTC 2015     root@grind.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

% clang++ vector.cpp -o vector -std=c++11 -lpthread

This is the one I hit more often:

% ./vector
<jemalloc>: /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/tcache.h:405: Failed assertion: "tbin->ncached < tb
in_info->ncached_max"
Abort (core dumped)

I also hit this (but happens less frequently)

% ./vector
<jemalloc>: jemalloc_arena.c:353: Failed assertion: "p[i] == 0"
Abort (core dumped)

The issue is intermittent so you might want to run multiple times. I don't exclude there's a bug in the code but that shouldn't trigger assertion(s) internals to jemalloc anyway.

Code:
https://gist.github.com/dcci/96027c3d92c42fb03bec

**Comment by jasone** [comment]
I compiled your program with clang 3.4 and with gcc 4.9.2 (had to ```#include <algorithm>```).  In both cases the program crashes in ```ConcurrentVector<int>::insert(int)``` even without linking in jemalloc.  I'm closing this under the assumption that the test program is flawed.

**Comment by dcci** [comment]
Yes, I don't disagree that the program is not quite right but jemalloc could help with something a little bit more explicative.
This is what glibc says, which seems a little bit more helpful. 
$ ./blah
*** Error in `./blah': free(): invalid next size (fast): 0x0000000001632010 *** 

So, maybe this can be moved to a enhancement request?
