### ISSUE TITLE
Using another allocator in conjunction with jemalloc

### ISSUE THREAD

**Issue by stan-1199** [jemalloc/jemalloc#2147]
I am writing an application that uses standard malloc with jemalloc. I used "with-jemalloc-prefix" for this. Though there is existing code files that use normal malloc and I want those existing normal malloc calls to fall to jemalloc.
If I use the "with-jemalloc-prefix" option then pre_malloc would be used for jemalloc and those existing calls would not fall to jemalloc. Is there a way to do this?

**Comment by Lapenkov** [comment]
I don't think there's a way to do this. You can either redirect all `malloc` calls to `jemalloc` in your application, or use `je_malloc` alongside other malloc implementation called with `malloc`.
I can think of a dirty way: `#define malloc je_malloc` for those existing files that you want to redirect to jemalloc.
