### ISSUE TITLE
Incorrect path to 'arena.<N>.lg_dirty_mult'

### ISSUE THREAD

**Issue by daverigby** [jemalloc/jemalloc#215]
Commit 8d6a3e8321a7767c incorrectly references the per-arena lg_dirty_mult setting as `stats.arenas.0.lg_dirty_mult`, when it should be `arena.0.lg_dirty_mult`.

Additionally, index MIB position for this differs from all others (index is at position 1 not 2) and hence `CTL_I_GET()` macro is incorrect.

**Comment by daverigby** [comment]
See https://github.com/jemalloc/jemalloc/pull/216 for a hacky fix to demonstrate the problem - I don't know how you want to handle using a variable index position when looking up MIBs...

**Comment by jasone** [comment]
Thanks!
