### ISSUE TITLE
Any suggestions for tuning cgo + rocksdb + jemalloc-5.2.1 combo?

### ISSUE THREAD

**Issue by dmpetroff** [jemalloc/jemalloc#2153]
Hello!

We experience RSS growing over time with Go application which uses RocksDB and jemalloc-5.2.1.
![2021-11-03_23-35](https://user-images.githubusercontent.com/25196930/140190366-4a3b77f8-4551-4c3f-81c8-53c0bf95d0c5.png)
Shown plots are `stats.resident` and `stats.allocated` from jemalloc and slope of RSS graph resembles `stats.resident` very closely.
What could such huge gap between resident and allocated stats mean?

From my experience cgo uses a lot of threads to perform native calls. This was a huge problem for glibc default allocator: gigabytes of memory got "abandoned" in per thread arenas over time.
Could it be the same issue: a lot of unused memory in per-thread arenas? But shouldn't it be taken care by background thread (btw is it enabled by default)?

Thanks in advance!

**Comment by interwq** [comment]
Can you share the full output from malloc_stats_print()? That would help us pinpoint the issue.

For compatibility reasons, background thread isn't enabled by default. Enabling it could help here.

On a related note -- In our RockDB workload, the high thread count resulted in GBs of memory consumed by the thread cache. If you can try the jemalloc dev branch, there's an option to improve the situation -- by setting `tcache_max:4096` in MALLOC_CONF, we had a ~20% reduction in memory usage. That won't explain the gap here between allocated and rss though; malloc_stats should tell what's going on.

**Comment by dmpetroff** [comment]
Unfortunately I didn't added malloc_stats_print into the service and will be able to do so only next week. We're running service on 64-core machine so there should be a lot of arenas.
Meanwhile resident has grown a bit over past day.
![2021-11-04_23-11](https://user-images.githubusercontent.com/25196930/140412819-39a7feca-f0e3-4607-8861-3ffd029715c3.png)

**Comment by dmpetroff** [comment]
Enabling background thread solved the problem. It seems memory was "forgotten" across 128 arenas (with 1-2 threads per arena).
