### ISSUE TITLE
Failed test with specific configuration

### ISSUE THREAD

**Issue by Lapenkov** [jemalloc/jemalloc#2156]
**test_batch_alloc** fails an assertion when configured with `./configure --enable-debug --enable-autogen --enable-prof=yes --enable-prof-libgcc --with-malloc-conf="prof:true,prof_active:false"`:

`<jemalloc>: ../src/jemalloc.c:4116: Failed assertion: "prof_sampled(tsd, p)"`

**Comment by davidtgoldblatt** [comment]
Should probably just be a test_skip_if(!opt_prof_active) in there somewhere; presumably it's the profiling test that isn't passing.

**Comment by interwq** [comment]
It looks the prof_active check was missed during batch_alloc. Fix in #2157
