### ISSUE TITLE
free() silently leaks memory on custom pointers. How to know a pointer able to free?

### ISSUE THREAD

**Issue by wmwsagara** [jemalloc/jemalloc#2158]
Hi 

The free() silently ignors pointers that do not exactly match to pointers returned by allocation functions (eg. malloc()).

My question here is, in jemalloc, how to know a given pointer is able to free by free() before passing it to free()?

Or in other words, how to know if a given pointer exactly matches to a pointer returned by allocation functions (eg. malloc())?

Detail:
There are use cases for custom pointers (still allocated by malloc()).

Therefore, custom pointers should not be passed to free(), but require a custom free().

But in large programs, it is possible to pass custom pointers to free() accidently and leak memory.

Eg.
```
void *customMalloc(size_t size)
{
 void *p = malloc(size + N);

 ... first N bytes reserved and do some process ...

 return p + N;
}

void customFree(void *ptr)
{
 ptr -= N;

 ... do some process ...

 free(ptr);
}

main()
{
 void *p = customMalloc(somesize);

 ... do some process ...

 free(p); // free() silently leaks memory. Should call customFree().

 if (validPointer(p))
    free(p);
 else
    printf("p cannot free.")

}
```
Best regards
Sagara

**Comment by Lapenkov** [comment]
Hello Sagara,
No, there's no way to check if your pointer is valid. Perhaps, you should store that information along with your custom pointer.
