### ISSUE TITLE
fatal error C1189: #error:  Generate the headers using x64 vcargs

### ISSUE THREAD

**Issue by ULis3h** [jemalloc/jemalloc#2163]
how to fix this error, my ide is vs2019

**Comment by Lapenkov** [comment]
We haven't tested our VS projects on vs2019. You can try using vs2017 or building through MSYS2 like we do in our CI tests:
https://ci.appveyor.com/project/jasone/jemalloc/builds/41795095/job/pelmonxrvma8mrnu
