### ISSUE TITLE
[jemalloc][dll] Across a layer of dynamic libraries, jemalloc crashes

### ISSUE THREAD

**Issue by duchuan34** [jemalloc/jemalloc#2165]
OS：windows
ARCH：X64
when i use dynamic library use jemallloc 
XXX.Dll

#include "jemalloc/jemalloc.h"
#define malloc(size)        je_malloc(size)
#define calloc(count,size)  je_calloc(count,size)
#define realloc(ptr,size)   je_realloc(ptr,size)
#define free(ptr)           je_free(ptr)

### test modelA:
Test.exe dep myJE.dll
myJE.dll dep jemalloc
when i run Test.exe ,jemalloc crush.

Running INFO:
Spawning 4 threads...
<jemalloc>: E:\sourceCodeTest\3rdparty\jemalloc\src\tcache.c:592: Failed assertion: "tcache_small_bin_get(tcache, 0)->avail != NULL"
malloc span time = 15676, new span time = 9927, jemalloc span time = 23749
press any key exit......
malloc span time = 16882, new span time = 28731, jemalloc span time = 7837
press any key exit......
malloc span time = 25609, new span time = 20693, jemalloc span time = 23658
press any key exit......

### test modelB:
Test.exe dep jemalloc
keep runnig
Running INFO:
Spawning 4 threads...
malloc span time = 16723, new span time = 12001, jemalloc span time = 6617
malloc span time = 17146, new span time = 10825, jemalloc span time = 7369
press any key exit......
press any key exit......
malloc span time = 17551, new span time = 10941, jemalloc span time = 7461
press any key exit......
malloc span time = 18338, new span time = 10630, jemalloc span time = 9713
press any key exit......

**Comment by duchuanLX** [comment]
@jasone  
I want to get your guidance, thank you!

**Comment by duchuanLX** [comment]
@davidtgoldblatt 
maybe its configure config  not support dynamic LIIB
