### ISSUE TITLE
heap file can not use in ARM_V7

### ISSUE THREAD

**Issue by KingWang569** [jemalloc/jemalloc#2192]
We write a test demo cpp file and compile it in **X86** with:
sudo g++ test_jemalloc1.cpp -g -o test_jemalloc1 -L/usr/local/jemalloc-5.2.1/lib -pthread -ljemalloc
then we run the demo use:
export MALLOC_CONF="prof:true" && LD_PRELOAD=/usr/local/jemalloc-5.2.1/lib/libjemalloc.so.2  ./test_jemalloc1
a lot of heap file generate, and we run the command: /
usr/local/jemalloc-5.2.1/bin/jeprof test_jemalloc1 jeprof.21673.175.m175.heap
run the command : top , it show that 3.5M

but the same demo cpp file and the same meathod to compile it in **ARM-V7**, also a lot of heap file generate
but we choose a heap file and run the command: usr/local/jemalloc-5.2.1/bin/jeprof test_jemalloc1 jeprof.21673.175.m175.heap
it show that 0M
when we try to convert to pdf file, it said that: no nodes to print

also we try the ARMV8, it show that 3.5M

so why heap file can not use in ARM_V7

thank you very much if you can tell me!

**Comment by Lapenkov** [comment]
Hello. Jemalloc can use different stack unwinders, maybe the issue is that the unwinder you're trying to use is unavailable on the system that runs on ARM-V7.

First, compare the options your libjemalloc.so were built with. Please, attach 3 links to pastes that contain the output of your example launched as follows:
`LD_PRELOAD=/usr/local/jemalloc-5.2.1/lib/libjemalloc.so.2 MALLOC_CONF="prof:true,stats_print:true"  ./test_jemalloc1`

I added `stats_print:true` to `MALLOC_CONF` to make your example prints the stats at exit. These stats are what I need for each architecture you listed.

**Comment by Lapenkov** [comment]
Reopen if you still have the issue and the requested data.

**Comment by Lapenkov** [comment]
Can you make it readable though?

**Comment by cvidkal** [comment]
Hey Lapenkov:
Here is the stats print:



`___ Begin jemalloc statistics ___
Version: "0.0.0-0-g0000000000000000000000000000000000000000"
Build-time option settings
  config.cache_oblivious: true
  config.debug: false
  config.fill: true
  config.lazy_lock: false
  config.malloc_conf: ""
  config.opt_safety_checks: false
  config.prof: true
  config.prof_libgcc: true
  config.prof_libunwind: false
  config.stats: true
  config.utrace: false
  config.xmalloc: false
Run-time option settings
  opt.abort: false
  opt.abort_conf: false
  opt.confirm_conf: false
  opt.retain: false
  opt.dss: "secondary"
  opt.narenas: 16
  opt.percpu_arena: "disabled"
  opt.oversize_threshold: 8388608
  opt.metadata_thp: "disabled"
  opt.background_thread: false (background_thread: false)
  opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
  opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)
  opt.lg_extent_max_active_fit: 6
  opt.junk: "false"
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.thp: "not supported"
  opt.prof: true
  opt.prof_prefix: "jeprof"
  opt.prof_active: true (prof.active: true)
  opt.prof_thread_active_init: true (prof.thread_active_init: true)
  opt.lg_prof_sample: 19 (prof.lg_sample: 19)
  opt.prof_accum: false
  opt.lg_prof_interval: -1
  opt.prof_gdump: false
  opt.prof_final: false
  opt.prof_leak: false
  opt.stats_print: true
  opt.stats_print_opts: ""
Profiling settings
  prof.thread_active_init: true
  prof.active: true
  prof.gdump: false
  prof.interval: 0
  prof.lg_sample: 19
Arenas: 17
Quantum size: 8
Page size: 4096
Maximum thread-cached size class: 32768
Number of bin size classes: 39
Number of thread-cache bin size classes: 44
Number of large size classes: 68
Allocated: 121480, active: 159744, metadata: 482080 (n_thp 0), resident: 622592, mapped: 2256896, retained: 0
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
background_thread                   4       4               0       0               0       0               1       1               0         0               0           0
ctl                                 2       2               0       0               0       0               1       1               0         0               0           0
prof                                2       2               0       0               0       0               1       1               0         0               0           0
arenas[0]:
assigned threads: 1
uptime: 9999837
dss allocation precedence: "secondary"
decaying:  time       npages       sweeps     madvises       purged
   dirty: 10000            0            0            0            0
   muzzy:     0            0            0            0            0
                            allocated         nmalloc (#/sec)         ndalloc (#/sec)       nrequests   (#/sec)           nfill   (#/sec)          nflush   (#/sec)
small:                          43656              48      48               0       0               8         8               2         2               0         0
large:                          77824               3       3               0       0               3         3               3         3               5         5
total:                         121480              51      51               0       0              11        11               5         5               5         5
                                     
active:                        159744
mapped:                       2256896
retained:                           0
base:                          460952
internal:                       21128
metadata_thp:                       0
tcache_bytes:                   36992
resident:                      622592
abandoned_vm:                       0
extent_avail:                       0
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
large                               2       2               0       0               0       0               1       1               0         0               0           0
extent_avail                       12      12               0       0               0       0               3       3               0         0               0           0
extents_dirty                      12      12               0       0               0       0               3       3               0         0               0           0
extents_muzzy                       2       2               0       0               0       0               1       1               0         0               0           0
extents_retained                   12      12               0       0               0       0               3       3               0         0               0           0
decay_dirty                         2       2               0       0               0       0               1       1               0         0               0           0
decay_muzzy                         2       2               0       0               0       0               1       1               0         0               0           0
base                               42      42               0       0               0       0               3       3               0         0               0           0
tcache_list                         4       4               0       0               0       0               1       1               0         0               0           0
bins:           size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests   (#/sec)  nshards      curregs     curslabs  nonfull_slabs regs pgs   util       nfills (#/sec)     nflushes (#/sec)       nslabs     nreslabs (#/sec)      n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
                   8   013181380495440609288            1       1            0       0            1         1        1            1            1              0  512   1  0.001            0       0            0       0            1            0       0               5       5               0       0               0       0               1       1               0         0               0           0
                  16   113181380495440609280            0       0            0       0            0         0        1            0            0              0  256   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  24   213181380495440609280            0       0            0       0            0         0        1            0            0              0  512   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  32   313181380495440609280            0       0            0       0            0         0        1            0            0              0  128   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  40   413181380495440609280            0       0            0       0            0         0        1            0            0              0  512   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  48   513181380495440609280            0       0            0       0            0         0        1            0            0              0  256   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  56   613181380495440609280            0       0            0       0            0         0        1            0            0              0  512   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  64   713181380495440609280            0       0            0       0            0         0        1            0            0              0   64   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  80   813181380495440609280            0       0            0       0            0         0        1            0            0              0  256   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                  96   913181380495440609280            0       0            0       0            0         0        1            0            0              0  128   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 112  1013181380495440609280            0       0            0       0            0         0        1            0            0              0  256   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 128  1113181380495440609280            0       0            0       0            0         0        1            0            0              0   32   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 160  1213181380495440609280            0       0            0       0            0         0        1            0            0              0  128   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 192  1313181380495440609280            0       0            0       0            0         0        1            0            0              0   64   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 224  1413181380495440609280            0       0            0       0            0         0        1            0            0              0  128   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 256  1513181380495440609280            0       0            0       0            0         0        1            0            0              0   16   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 320  1613181380495440609280            0       0            0       0            0         0        1            0            0              0   64   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 384  1713181380495440609280            0       0            0       0            0         0        1            0            0              0   32   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 448  1813181380495440609280            0       0            0       0            0         0        1            0            0              0   64   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                 512  1913181380495440609280            0       0            0       0            0         0        1            0            0              0    8   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                     ---
                 640  2013181380495440609920            1       1            0       0            1         1        1            1            1              0   32   5  0.031            0       0            0       0            1            0       0               5       5               0       0               0       0               1       1               0         0               0           0
                 768  2113181380495440609280            0       0            0       0            0         0        1            0            0              0   16   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                     ---
                 896  2213181380495440637952           32      32            0       0            1         1        1           32            1              0   32   7      1            1       1            0       0            1            0       0               5       5               0       0               0       0               1       1               0         0               0           0
                1024  2313181380495440623616           14      14            0       0            5         5        1           14            4              0    4   1  0.875            1       1            0       0            4            0       0              12      12               0       0               0       0               1       1               0         0               0           0
                1280  2413181380495440609280            0       0            0       0            0         0        1            0            0              0   16   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                1536  2513181380495440609280            0       0            0       0            0         0        1            0            0              0    8   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                1792  2613181380495440609280            0       0            0       0            0         0        1            0            0              0   16   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                2048  2713181380495440609280            0       0            0       0            0         0        1            0            0              0    2   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                2560  2813181380495440609280            0       0            0       0            0         0        1            0            0              0    8   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                3072  2913181380495440609280            0       0            0       0            0         0        1            0            0              0    4   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                3584  3013181380495440609280            0       0            0       0            0         0        1            0            0              0    8   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                4096  3113181380495440609280            0       0            0       0            0         0        1            0            0              0    1   1      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                5120  3213181380495440609280            0       0            0       0            0         0        1            0            0              0    4   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                6144  3313181380495440609280            0       0            0       0            0         0        1            0            0              0    2   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                7168  3413181380495440609280            0       0            0       0            0         0        1            0            0              0    4   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                8192  3513181380495440609280            0       0            0       0            0         0        1            0            0              0    1   2      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
               10240  3613181380495440609280            0       0            0       0            0         0        1            0            0              0    2   5      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
               12288  3713181380495440609280            0       0            0       0            0         0        1            0            0              0    1   3      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
               14336  3813181380495440609280            0       0            0       0            0         0        1            0            0              0    2   7      1            0       0            0       0            0            0       0               3       3               0       0               0       0               1       1               0         0               0           0
                     ---
large:          size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests (#/sec)  curlextents
               16384  39        16384            1       1            0       0            1       1            1
               20480  40        20480            1       1            0       0            1       1            1
                     ---
               40960  44        40960            1       1            0       0            1       1            1
                     ---
extents:        size ind       ndirty        dirty       nmuzzy        muzzy    nretained     retained       ntotal        total
                     ---
--- End jemalloc statistics ---`

**Comment by Lapenkov** [comment]
Is this output from x86, ARMv8 or ARMv7 that you have issues with?

Either way, in the meantime, try configuring and building with `--enable-prof --enable-prof-libunwind`. Let me know if that makes the output non-empty.

**Comment by cvidkal** [comment]
This is from ARMv7, I had configuring and building with libunwind, and the log is in the following. And when I use jeprof to show heap file, shows 0.0 mb.

Dump heap file, current mem useage 1 M2
2
Dump heap file, current mem useage 2 M___ Begin jemalloc statistics ___
Version: "0.0.0-0-g0000000000000000000000000000000000000000"
Build-time option settings
  config.cache_oblivious: true
  config.debug: true
  config.fill: true
  config.lazy_lock: false
  config.malloc_conf: ""
  config.opt_safety_checks: true
  config.prof: true
  config.prof_libgcc: false
  config.prof_libunwind: true
  config.stats: true
  config.utrace: false
  config.xmalloc: false
Run-time option settings
  opt.abort: true
  opt.abort_conf: true
  opt.confirm_conf: false
  opt.retain: false
  opt.dss: "secondary"
  opt.narenas: 16
  opt.percpu_arena: "disabled"
  opt.oversize_threshold: 8388608
  opt.metadata_thp: "disabled"
  opt.background_thread: false (background_thread: false)
  opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
  opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)
  opt.lg_extent_max_active_fit: 6
  opt.junk: "true"
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.thp: "not supported"
  opt.prof: true
  opt.prof_prefix: "jeprof"
  opt.prof_active: true (prof.active: true)
  opt.prof_thread_active_init: true (prof.thread_active_init: true)
  opt.lg_prof_sample: 19 (prof.lg_sample: 19)
  opt.prof_accum: false
  opt.lg_prof_interval: -1
  opt.prof_gdump: false
  opt.prof_final: false
  opt.prof_leak: false
  opt.stats_print: true
  opt.stats_print_opts: ""
Profiling settings
  prof.thread_active_init: true
  prof.active: true
  prof.gdump: false
  prof.interval: 0
  prof.lg_sample: 19
Arenas: 17
Quantum size: 8
Page size: 4096
Maximum thread-cached size class: 32768
Number of bin size classes: 39
Number of thread-cache bin size classes: 44
Number of large size classes: 68
Allocated: 121480, active: 159744, metadata: 525440 (n_thp 0), resident: 667648, mapped: 2256896, retained: 0
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
background_thread                   4       0               0       0               0       0               1       0               0         0               0           0
ctl                                 2       0               0       0               0       0               1       0               0         0               0           0
prof                                4       0               0       0               0       0               1       0               0         0               0           0
arenas[0]:
assigned threads: 1
uptime: 0
dss allocation precedence: "secondary"
decaying:  time       npages       sweeps     madvises       purged
   dirty: 10000            0            0            0            0
   muzzy:     0            0            0            0            0
                            allocated         nmalloc (#/sec)         ndalloc (#/sec)       nrequests   (#/sec)           nfill   (#/sec)          nflush   (#/sec)
small:                          43656              48       0               0       0               8         0               2         0               0         0
large:                          77824               3       0               0       0               3         0               3         0               5         0
total:                         121480              51       0               0       0              11         0               5         0               5         0
                                     
active:                        159744
mapped:                       2256896
retained:                           0
base:                          504312
internal:                       21128
metadata_thp:                       0
tcache_bytes:                   36992
resident:                      667648
abandoned_vm:                       0
extent_avail:                       0
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
large                               2       0               0       0               0       0               1       0               0         0               0           0
extent_avail                       12       0               0       0               0       0               3       0               0         0               0           0
extents_dirty                      12       0               0       0               0       0               3       0               0         0               0           0
extents_muzzy                       2       0               0       0               0       0               1       0               0         0               0           0
extents_retained                   12       0               0       0               0       0               3       0               0         0               0           0
decay_dirty                         2       0               0       0               0       0               1       0               0         0               0           0
decay_muzzy                         2       0               0       0               0       0               1       0               0         0               0           0
base                               42       0               0       0               0       0               3       0               0         0               0           0
tcache_list                         4       0               0       0               0       0               1       0               0         0               0           0
bins:           size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests   (#/sec)  nshards      curregs     curslabs  nonfull_slabs regs pgs   util       nfills (#/sec)     nflushes (#/sec)       nslabs     nreslabs (#/sec)      n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
                   8   0            8            1       0            0       0            1         0        1            1            1              0  512   1  0.001            0       0            0       0            1            0       0               5       0               0       0               0       0               1       0               0         0               0           0
                  16   1            0            0       0            0       0            0         0        1            0            0              0  256   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  24   2            0            0       0            0       0            0         0        1            0            0              0  512   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  32   3            0            0       0            0       0            0         0        1            0            0              0  128   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  40   4            0            0       0            0       0            0         0        1            0            0              0  512   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  48   5            0            0       0            0       0            0         0        1            0            0              0  256   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  56   6            0            0       0            0       0            0         0        1            0            0              0  512   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  64   7            0            0       0            0       0            0         0        1            0            0              0   64   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  80   8            0            0       0            0       0            0         0        1            0            0              0  256   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                  96   9            0            0       0            0       0            0         0        1            0            0              0  128   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 112  10            0            0       0            0       0            0         0        1            0            0              0  256   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 128  11            0            0       0            0       0            0         0        1            0            0              0   32   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 160  12            0            0       0            0       0            0         0        1            0            0              0  128   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 192  13            0            0       0            0       0            0         0        1            0            0              0   64   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 224  14            0            0       0            0       0            0         0        1            0            0              0  128   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 256  15            0            0       0            0       0            0         0        1            0            0              0   16   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 320  16            0            0       0            0       0            0         0        1            0            0              0   64   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 384  17            0            0       0            0       0            0         0        1            0            0              0   32   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 448  18            0            0       0            0       0            0         0        1            0            0              0   64   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                 512  19            0            0       0            0       0            0         0        1            0            0              0    8   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                     ---
                 640  20          640            1       0            0       0            1         0        1            1            1              0   32   5  0.031            0       0            0       0            1            0       0               5       0               0       0               0       0               1       0               0         0               0           0
                 768  21            0            0       0            0       0            0         0        1            0            0              0   16   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                     ---
                 896  22        28672           32       0            0       0            1         0        1           32            1              0   32   7      1            1       0            0       0            1            0       0               5       0               0       0               0       0               1       0               0         0               0           0
                1024  23        14336           14       0            0       0            5         0        1           14            4              0    4   1  0.875            1       0            0       0            4            0       0              12       0               0       0               0       0               1       0               0         0               0           0
                1280  24            0            0       0            0       0            0         0        1            0            0              0   16   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                1536  25            0            0       0            0       0            0         0        1            0            0              0    8   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                1792  26            0            0       0            0       0            0         0        1            0            0              0   16   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                2048  27            0            0       0            0       0            0         0        1            0            0              0    2   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                2560  28            0            0       0            0       0            0         0        1            0            0              0    8   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                3072  29            0            0       0            0       0            0         0        1            0            0              0    4   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                3584  30            0            0       0            0       0            0         0        1            0            0              0    8   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                4096  31            0            0       0            0       0            0         0        1            0            0              0    1   1      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                5120  32            0            0       0            0       0            0         0        1            0            0              0    4   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                6144  33            0            0       0            0       0            0         0        1            0            0              0    2   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                7168  34            0            0       0            0       0            0         0        1            0            0              0    4   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                8192  35            0            0       0            0       0            0         0        1            0            0              0    1   2      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
               10240  36            0            0       0            0       0            0         0        1            0            0              0    2   5      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
               12288  37            0            0       0            0       0            0         0        1            0            0              0    1   3      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
               14336  38            0            0       0            0       0            0         0        1            0            0              0    2   7      1            0       0            0       0            0            0       0               3       0               0       0               0       0               1       0               0         0               0           0
                     ---
large:          size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests (#/sec)  curlextents
               16384  39        16384            1       0            0       0            1       0            1
               20480  40        20480            1       0            0       0            1       0            1
                     ---
               40960  44        40960            1       0            0       0            1       0            1
                     ---
extents:        size ind       ndirty        dirty       nmuzzy        muzzy    nretained     retained       ntotal        total
                     ---
--- End jemalloc statistics ---

**Comment by Lapenkov** [comment]
I don't see why it would be empty. Can you share the jeprof command you're running?
