### ISSUE TITLE
make install error when configure has --with-install-suffix

### ISSUE THREAD

**Issue by lawmurray** [jemalloc/jemalloc#2197]
On branch `dev` latest (`eabe889`), when setting `--with-install-suffix`:

    ./configure --with-install-suffix=_test
    make

succeeds, then:

    make install

gives (snipped):

    make: *** No rule to make target 'doc/jemalloc_test.html', needed by 'build_doc_html'.  Stop.

It seems that the suffix is not applied to the files in `doc/`, which are still e.g. `doc/jemalloc.html` and not `doc/jemalloc_test.html`.

Otherwise this is working, and other files are successfully installing with the given suffix. I've tried adding `--disable-documentation` to the configure line as a workaround, but this does not seem to work---same error (should it not be trying to install docs in this case?). Easy to fix this with manual intervention, but thought I'd report.

I'm on openSUSE Tumbleweed, autoconf 2.69, automake 1.16.5, libtool 2.4.6.

Finally, thanks for jemalloc, love it!

**Comment by interwq** [comment]
Thanks for reporting this. The fix is in #2209.

re: `--disable-documentation` it should be `--disable-doc`; sorry about the confusion. Fixed in the PR above as well.
