### ISSUE TITLE
5.3 Release Candidate

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#2213]
This issue is for tracking progress and communication related to the upcoming 5.3 release.

Current release candidate: ed5fc14 which is going through our production testing pipeline.

A [previous commit](c9ebff0fd6ab90d5eed0d11f48dfedcc21222ab0
) was production deployed in November and no issues were observed.

CC: @jasone

**Comment by zct** [comment]
Is any description or docs about HPA , I want to test this feature in our workloads

**Comment by interwq** [comment]
@zct: thanks for offering help testing. jemalloc's internal huge page allocator (HPA) is still in an early stage and will not be officially introduced in the 5.3 release. We have several binaries using it and showing great results, but also have been tuning and fixing things around. When it reaches a semi-stable state we will share more details in a separate thread (I'll make sure to tag you).

**Comment by josh-m-sharpe** [comment]
Hi - sorry if this is the wrong place.  Where are releases pushed these days?  Latest I see is 5.2.1 from a few years back: https://github.com/jemalloc/jemalloc/releases - thank you!

**Comment by Lapenkov** [comment]
@josh-m-sharpe You're looking at the right place - it's been a while since the previous release.

**Comment by interwq** [comment]
Update: the current [5.3 release candidate](https://github.com/jemalloc/jemalloc/commit/20f9802e4f25922884448d9581c66d76cc905c0c). CC folks who might be interested in testing it before the official release: @gnzlbg, @rkmisra, @hatvik, @rustyx,  @davidlt, @paravoid, @marxin, @strejda, @sharkcz, @ingvarha, @cferris1000, @maksqwe, @trasz, @tamird, @xhochy, @rlibby, @zonyitoo, @AWSjswinney, @yunxuo, @leres, @georgthegreat, @devnexen, @azat, @mweisgut, @wangjl-uos, @pbalcer, @Mingli-Yu, @sangshuduo, @vineetgarc, @DeannaGelbart, @everschen, @AndroidInternal, @jqian-aurora, @ezeeyahoo, @hliu202, @brooksdavis, @tyroguru, @krytarowski, @zoulasc, @ethercflow, @lwhsu, @nickdesaulniers, @santagada, @RingsC, @Ignition, @giridharprasath, @j0t, @ffontaine, @mgrice, @daverigby

**Comment by marxin** [comment]
Thank you for working on the project. I would like to test the release candidate, but can you please pack a tarball and upload it somewhere, so that one doesn't have to run `autogen.sh` and stuff like that. Thanks.

**Comment by georgthegreat** [comment]
+1. We are using NixOS to build jemalloc.
While it is possible to override version, I have failed to make it run ./autogen.sh -> ./configure and so on in proper order.

**Comment by sangshuduo** [comment]
Thanks for your effort. I have verified that `make uninstall` works as expected. I would suggest adding a sentence in the  INSTALL.md to let the users know they can uninstall now.

**Comment by interwq** [comment]
@marxin @georgthegreat : Of course. Please see the attached zip file (github doesn't seem to allow tar files) for the 5.3RC. Note that the `VERSION` file included says `5.2.1-855-g20f9802e4f25922884448d9581c66d76cc905c0c`

[jemalloc-5.3rc.zip](https://github.com/jemalloc/jemalloc/files/7973504/jemalloc-5.3rc.zip)

**Comment by marxin** [comment]
Thanks for the zip file. I can confirm it works on all targets we've got in `openSUSE:Factory`.

**Comment by georgthegreat** [comment]
Unfortunately, I was unable to import 5.3-rc, as it requires to fix some of our local patches which were not upstreamed yet.

I am fine with proceeding with the release, as my fix is quite simple.
I will return to patching upon final 5.3 release.

**Comment by devnexen** [comment]
nothing bad to say about using this RC since 4 days with long running multithreaded processes, quite glad with the performances.

**Comment by eilandert** [comment]
Thanks!  I'm running in production on my nginx webservers (and dockers), so far so good.

I'm building debian/ubuntu packages from git here: http://edge.deb.myguard.nl:8888/pool/main/j/jemalloc/
(the final will be on https://deb.myguard.nl)
By the way, it might be easier to create a git rc/prerelease-tag for people with buildsystems.

**Comment by jeremiahpslewis** [comment]
Cross-compiling the latest commit of jemalloc from x86-linux to x86-apple-darwin fails with the following error:

```bash
[19:09:48] src/background_thread.c:87:2: error: unknown type name 'cpuset_t'; did you mean 'psset_t'?
[19:09:48]         cpuset_t cpuset;
[19:09:48]         ^~~~~~~~
[19:09:48]         psset_t
[19:09:48] include/jemalloc/internal/psset.h:63:24: note: 'psset_t' declared here
[19:09:48] typedef struct psset_s psset_t;
[19:09:48]                        ^
[19:09:48] src/background_thread.c:94:2: warning: implicit declaration of function 'CPU_ZERO' is invalid in C99 [-Wimplicit-function-declaration]
[19:09:48]         CPU_ZERO(&cpuset);
[19:09:48]         ^
[19:09:48] src/background_thread.c:95:2: warning: implicit declaration of function 'CPU_SET' is invalid in C99 [-Wimplicit-function-declaration]
[19:09:48]         CPU_SET(cpu, &cpuset);
[19:09:48]         ^
[19:09:48] src/background_thread.c:104:12: warning: implicit declaration of function 'pthread_setaffinity_np' is invalid in C99 [-Wimplicit-function-declaration]
[19:09:48]         int ret = pthread_setaffinity_np(pthread_self(), sizeof(cpuset_t),
[19:09:48]                   ^
[19:09:48] src/background_thread.c:104:58: error: use of undeclared identifier 'cpuset_t'
[19:09:48]         int ret = pthread_setaffinity_np(pthread_self(), sizeof(cpuset_t),
[19:09:48]                                                                 ^
[19:09:48] 3 warnings and 2 errors generated.
```

Can this be fixed via a build argument or is this a known issue?

Full output: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=16933&view=logs&jobId=43702cf5-850f-5c8b-4d19-2aa0bc8b2ab2&j=43702cf5-850f-5c8b-4d19-2aa0bc8b2ab2&t=dab34717-1508-5d74-f415-7bf57211487e

**Comment by azat** [comment]
One assertion fails - #2222

**Comment by ingvarha** [comment]
Did test build on Fedora rawhide, epel8 and epel9. Builds fine and runs the test suite on all targets, that is armvh7l, i686, x86_64, aarch64, ppc64le, s390x. Also builds fine and runs the test suite on Debian/ppc (32 bit).

**Comment by interwq** [comment]
@jeremiahpslewis : thanks for reporting the issue. Indeed the background thread configure detection wasn't correct when cross-compile -- the fix is in #2225.

**Comment by jeremiahpslewis** [comment]
@interwq Thanks for the PR, I updated my build files and all platforms pass with your fix! (See [here](https://github.com/JuliaPackaging/Yggdrasil/pull/4381/checks?check_run_id=5201637375)).

**Comment by jeremiahpslewis** [comment]
There is a known build issue for Apple silicon which is discussed in detail in this blog post (https://uwekorn.com/2021/01/11/apache-arrow-on-the-apple-m1.html). Would you be interested in fixing this upstream before the 5.3 release?


Here's how we 'patch' it at the moment: https://github.com/JuliaPackaging/Yggdrasil/blob/9feaf16a7e33dfe049041b45e9ef11662d411bd7/J/jemalloc/build_tarballs.jl#L38:L40

```bash
     # Use correct 'system page size' per https://uwekorn.com/2021/01/11/apache-arrow-on-the-apple-m1.html
     FLAGS+=(--with-lg-page=14)
```

**Comment by interwq** [comment]
@jeremiahpslewis I'm not sure that's an issue though. When cross-compile the page size auto detected is based on the build host, and if the target has different page sizes, you'd need to explicitly set `lg-page` like in your config.

Unless MacOS on M1 has a fixed 16K page size, or it has to be at least 16K? In that case we can add a default (or a minimal) page size if the target is M1 Mac.

**Comment by marxin** [comment]
Any update about the `5.3` release?

**Comment by interwq** [comment]
We ran into a configuration issue but resolved it recently. a4e8122 has been running in our entire fleet for a few weeks. Since then there were some new commits added; I'm trying another quicker round of testing with ed5fc14. Assuming no surprise, I should be able to finalize it next week.

**Comment by azat** [comment]
FWIW ClickHouse now uses jemalloc 5.3 rc (78b58379c854a639df79beb3289351129d863d4b), and the latest ClickHouse stable release (v22.3.2.2-lts) includes this change, no issues so far.

Plus ClickHouse has extensive CI (with stressing/fuzzing/...), and no issues so far there too.

**Comment by interwq** [comment]
5.3 released -- https://github.com/jemalloc/jemalloc/releases/tag/5.3.0

Thanks again everyone!
