### ISSUE TITLE
mallctl failed with return value: 14

### ISSUE THREAD

**Issue by guoxiangCN** [jemalloc/jemalloc#2215]
here are my code: 
```
void jeprof_dump() {
#ifdef USE_JEMALLOC
  static std::once_flag flag;
  std::call_once(flag, []() {
    std::string env = "MALLOC_CONF=prof:true,prof_prefix:jeprof.out";
    putenv(const_cast<char *>(env.c_str()));
  });

  // dump a file named as '<prefix>.<pid>.<seq>.m<mseq>.heap'
  int ret = mallctl("prof.dump", NULL, NULL, NULL, 0);
  LOG(INFO) << "prof.dump result: " << ret;
#endif
}
```

the log outputs:

I0124 11:39:59.599191 84131840 jeprof.cc:25] prof.dump result: 14
I0124 11:40:00.631527 84131840 jeprof.cc:25] prof.dump result: 14
I0124 11:40:01.669327 84131840 jeprof.cc:25] prof.dump result: 14

there are no any dump files created, could you help me, thanks!

**Comment by interwq** [comment]
Likely the jemalloc used wasn’t configured with the ‘—enable-prof’ option. Let us know if it still doesn’t work.
