### ISSUE TITLE
memory profiling link error

### ISSUE THREAD

**Issue by sifangli** [jemalloc/jemalloc#2216]
Trying to use the memory profiler. cloned the latest from master branch, i.e. b798fabdf7c86288f303b1e0bcf877c9ded67c18

built jemalloc with following flags:
```
$ ./autogen.sh --prefix=/tmp/jemalloc --disable-libdl --with-jemalloc-prefix=je_ --enable-prof
$ make
$ make install
```

Below is the gist link about my CppTest project:
https://gist.github.com/sifangli/64b4df7af2bbc4247ddf249d4b3df9f3

I tried both STATIC and SHARED link to jemalloc lib, but all got this link error:
```
[100%] Linking CXX executable MyCppTest
Undefined symbols for architecture x86_64:
  "_je_mallctl", referenced from:
      _main in Main.cpp.o
```
it complains about _je_mallctl, not je_mallctl. It may be something inside jemalloc code? I'm able to see this symbol though:

```
$ nm /tmp/jemalloc/lib/libjemalloc.dylib | grep ' T ' | grep mallctl
000000000001d590 T _je_mallctl
000000000001e1e0 T _je_mallctlbymib
000000000001dbc0 T _je_mallctlnametomib
$
```

**Comment by sifangli** [comment]
This is the link to my test files:
https://gist.github.com/sifangli/64b4df7af2bbc4247ddf249d4b3df9f3

**Comment by Lapenkov** [comment]
You have `add_library` in your CMake file, while you need `target_link_libraries` instead.

**Comment by sifangli** [comment]
@Lapenkov you are right! I made a dump mistake. `target_link_libraries` fixed the build issue.
