### ISSUE TITLE
Failed assertion: "bin->low_bits_full > bin->low_bits_empty" in 5.3RC

### ISSUE THREAD

**Issue by azat** [jemalloc/jemalloc#2222]
While upgrading [jemalloc for ClickHouse](https://github.com/ClickHouse/ClickHouse/pull/33057) CI founds one failed assertion:

```
Failed assertion: "bin->low_bits_full > bin->low_bits_empty"
```

You can find full report [here](https://s3.amazonaws.com/clickhouse-test-reports/33057/c43709a12fcca4452331464d31ace4df804e8796/fuzzer_astfuzzerdebug,actions//report.html), it includes:
- full stacktrace for the assertion (and all other threads)
- and also [core](https://s3.amazonaws.com/clickhouse-test-reports/33057/c43709a12fcca4452331464d31ace4df804e8796/fuzzer_astfuzzerdebug,actions//core.gz) file (**739MiB**)
- and from [here](https://s3.amazonaws.com/clickhouse-builds/33057/c43709a12fcca4452331464d31ace4df804e8796/package_debug/clickhouse) you can download appropriate binary (**2.8GiB**)

Here are my thoughts about it, it looks like it is some kind of a race (by they way I don't see any locks for `cache_bin_t`):

```
(lldb) p *bin
(cache_bin_t) $24 = {
  stack_head = 0x00007f28f5ece788
  tstats = (nrequests = 309)
  low_bits_low_water = 59336
  low_bits_full = 57800
  low_bits_empty = 59400
}

(lldb) p (uint16_t)(uintptr_t)low_bound
(uint16_t) $41 = 57808
                          ^^^^^^ beyond low_bits_full

# here I've recalculated low_bound and it is equal to low_bits_full
(lldb) p (uint16_t)(uintptr_t)((void**)((uintptr_t)bin->stack_head + bin->low_bits_empty-(uint16_t)(uintptr_t)bin->stack_head) - info->ncached_max)
(uint16_t) $43 = 57800
```

Refs: #1784 (cc @davidtgoldblatt)

**Comment by Lapenkov** [comment]
I agree that this is most probably a race.

Let me elaborate - for the allocation purposes we don't need to use any synchronization within cache bins, as they reside in thread local storage and are only modified by a single thread that owns the storage. But when we gather stats, a different stat collecting thread iterates over the bins and reads some data with a race. We don't lock to avoid slowdowns on the fast path.

The race condition again surfaced for the stat reading thread in some new cache bin functionality. It's pretty innocent, though.

I'll put up a fix for it and propose a new RC once it's merged.

Thank you for testing!
