### ISSUE TITLE
Refactor the remote / cross thread cache bin stats reading

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#2227]
Now that bin->stack_head and bin->low_bits_full can both be modified, we have the `bool racy` propagated quite extensively in `cache_bin.h`. Since the only `racy == true` case is for stats reading only, i.e. in `cache_bin_nitems_get_remote`, and unlikely to have new use cases, we might as well specialize that single function, i.e. to contain all the complexity in a single place, instead of having to ask "is this helper function safe to use for remote access". For example, `cache_bin_empty_position_get` isn't safe for the racy case, as pointed out in #2226.

We should be able to have only `cache_bin_nitems_get_remote` worry about the racy case, and simply say that all other utility functions are only for thread local usage.

**Comment by Lapenkov** [comment]
Isn't that going to be somewhat a copy-paste of the other helper functions, but without assertions and `racy` checks?  The concurrent code will be more localized, that's for sure, but it seems that it will come at a cost of duplication.

**Comment by interwq** [comment]
Yes there will be a bit of logic duplication, where we would make it thread safe specifically. In turn we'll be able to make all other utility functions single threaded only. Right now some of the helpers can and some cannot be used in the racy case, and it's not clearly so, like right now, a race can be introduced easily if `cache_bin_empty_position_get` gets called indirectly through one of the utilities used by `cache_bin_nitems_get_remote`.

The other direction is to make all the cache bin utilities multi thread safe. But that's quite an overkill and not really necessary given the very specific stats use case.
