### ISSUE TITLE
No nodes on the jemalloc heap dump/profile

### ISSUE THREAD

**Issue by asuwend1** [jemalloc/jemalloc#2229]
Hi,

OS: CentOS 7

I can use jemalloc (recently pulled from github repo, v5.2.1-857) to profile for memory leaks with C/C++ standalone programs without any problem. However I cannot seem to make it work with Java-App-Calling-C-Via-JNI settings (although it prints a probably-empty stats right after I stopped the service - attached).

Here's the jemalloc heap dump that I got (approx 42kb in size) after making a request that should trigger C/native malloc:
----------------- (also tried with OpenJDK 11)
Using local file /usr/java/amazon-corretto-11.0.14.9.1-linux-x64/bin/java.
Using local file jeprof.out.4809.0.f.heap.
Welcome to jeprof!  For help, type 'help'.
(jeprof) top
Total: 0 B
(jeprof) gv
Total: 0 B
No nodes to print
(jeprof) quit
---------------- (this same library works fine with jemalloc when called from a standalone C++ program, generating jemalloc heap with nodes)
ldd -d libsomething.so
...
	libjemalloc.so.2 => /usr/local/lib/libjemalloc.so.2 (0x00007efcb4d58000)
	libunwind.so.8 => /usr/local/lib/libunwind.so.8 (0x00007efcb4b41000)
	libm.so.6 => /lib64/libm.so.6 (0x00007efcb483f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007efcb463b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efca59a8000)
...
--------------

my jemalloc install configuration (tried using libunwind too):
 ./configure --disable-initial-exec-tls --enable-prof --enable-prof-libunwind --disable-prof-libgcc --disable-prof-gcc  --enable-debug --enable-fill

setting:
/etc/malloc.conf -> prof_leak:true,lg_prof_sample:0,prof_final:true,prof_prefix:jeprof.out,stats_print:true

I also set LD_PRELOAD=/usr/local/lib/libjemalloc.so.2  and followed the Getting Started article.
Java startup command:
java <VARIOUS-VM-OPTIONS> - jar app-exec.jar -DLD_PRELOAD=/usr/local/lib/libjemalloc.so.2

I have read and tried many things but they couldn't solve this issue. I'm assuming that I should be able to use jemalloc for a Java app with JNI too since I see web articles where people managed to do that. Any inputs on what else I can try would be very appreciated. Thank you!

[jemalloc_stats.txt](https://github.com/jemalloc/jemalloc/files/8092814/jemalloc_stats.txt)

**Comment by Lapenkov** [comment]
It looks like your shared library isn't calling jemalloc, but rather libc malloc. I suggest you run java with `LD_DEBUG=all` and check the output of the dynamic linker. Look for the line `object=libsomething.so` and check the lookup scope in the following lines. Below that, find `symbol=malloc;  lookup in file ...` to see where it tries to find malloc.

**Comment by asuwend1** [comment]
Hi @Lapenkov , Thank you for the feedback. While trying out the new env var LD_DEBUG, it made me realized that I have not set the LD_PRELOAD env var properly with Java. Once I fixed it, it works as expected now. Thank you!!

**Comment by Lapenkov** [comment]
You're welcome!
