### ISSUE TITLE
Can prof:false totally disable profiling overhead when library prof enabled compiled ?

### ISSUE THREAD

**Issue by benet96** [jemalloc/jemalloc#2230]
Jemalloc: 5.2.1
OS: Linux on server

I found a history mail with question about Jemalloc profiling overhead and replied with a conclusion that disable prof with MALLOC_CONF can vanish the overhead.

But when I look through source code, there are many if(config_prof) in main source code. Why config_prof is not always with opt_prof ?

![image](https://user-images.githubusercontent.com/18164356/155110630-ae13781d-d5d0-456d-9173-442f3435d2cd.png)

So I run a benchmark program for google-benchmark, check the difference between program linked with disable-prof jemalloc and enable-prof with prof:false startup. The result show prof:false version takes over 10% CPU overhead.

![image](https://user-images.githubusercontent.com/18164356/155110961-2c23e40a-9cb6-44aa-97b1-728decb1944b.png)

I think that is far from low overhead ? Is there any thing I can do  or newer version already merged to reduce them?

**Comment by Lapenkov** [comment]
If you check all these `if (config_prof)`, you'll see that they either boot prof, collect stats, or call a function that is a no-op if `opt_prof` is false. I highly doubt about 10% CPU overhead, how did you measure that?

**Comment by benet96** [comment]
> If you check all these `if (config_prof)`, you'll see that they either boot prof, collect stats, or call a function that is a no-op if `opt_prof` is false. I highly doubt about 10% CPU overhead, how did you measure that?

I'm back. Here is the summary of my code reading. Some of the cases may not have huge performance influence but worth fixed for code clean, others did has performance negative effect. 

Here are the typical cases, I didn't track the latest dev code, if any case has beed fixed, just ignore me~

1. arena_dalloc_promoted function is not always inlined, so there's extra cost for the function entrance.
```c
 arena_dalloc_large_no_tcache(tsdn_t *tsdn, void *ptr, szind_t szind) {
-       if (config_prof && unlikely(szind < SC_NBINS)) {
+       if (config_prof && opt_prof && unlikely(szind < SC_NBINS)) {
                arena_dalloc_promoted(tsdn, ptr, NULL, true);
        } else {
                extent_t *extent = iealloc(tsdn, ptr);
```
if bumped size == usize, the function will just entered, and return.

2. even it is inlined, it does atomic operation with CPU cost

```c
-       if (config_prof) {
+       if (config_prof && opt_prof) {
                extent_prof_tctx_set(extent, NULL);
        }
...

static inline void
extent_prof_tctx_set(extent_t *extent, prof_tctx_t *tctx) {
       atomic_store_p(&extent->e_prof_tctx, tctx, ATOMIC_RELEASE);
}

```

3. size counter never used.
-       if (config_prof) {
+       if (config_prof && opt_prof) {
                tcache->prof_accumbytes += usize;
        }

Our cloud services have really heavy loads on CPU, after I fixed those cases, our services linked with --enable-prof but opt.prof:false have the same performance as version LD_PRELOAD with --disable-prof.

**Comment by benet96** [comment]
Program must have heavy enough loads in performance and it show difference between Jemalloc versions with the above cases fixed or not. Firstly I use google official protobuf benchmark, I missed some corner cases and it still have performance diff for the services online.

**Comment by Lapenkov** [comment]
All these cases have been fixed, in dev it's different now.

**Comment by benet96** [comment]
Awesome, I think we can close the issue.
