### ISSUE TITLE
mallctl("prof.active"...) can't work in tag 5.2.1

### ISSUE THREAD

**Issue by No-limits** [jemalloc/jemalloc#2231]
I meet a problem when use jemalloc(tag:5.2.1). But it can work in jemalloc(tag:5.1.0).

- Linux gcc-4.9.2
- `MALLOC_CONF="prof:true,lg_prof_interval:20,prof_active:false,prof_prefix:jeprof.out" `
-  enable prof sampling by `mallctl("prof.active", NULL, NULL, &active, sizeof(active));` during execution，and it won't generate any heap profiling.

compile jemalloc
```
#!/bin/bash
wget https://github.com/jemalloc/jemalloc/archive/5.2.1.zip 
unzip 5.2.1.zip

workdir=`pwd`
cd jemalloc-5.2.1/
./autogen.sh 
./configure --prefix=${workdir} --enable-prof
make -j32
make install
```

test code
```
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <chrono>
#include <unistd.h>
#include <thread>
#include "jemalloc/jemalloc.h"


int main() {
    sleep(10);
    std::thread t([]() {
        std::vector<int> vec;
        std::map<int, int> mp;
        std::string s;
        for (;;) {
            for (int i = 0; i < 1000; ++i) {
                vec.push_back(i);
                mp[rand()] = i;
                s += "xxxx";
                new char[4];
            }
            std::this_thread::sleep_for(std::chrono::microseconds(100));
        }

    });
    
    t.detach();

    mallctl("prof.active", NULL, NULL, &active, sizeof(active));
    sleep(100);

    return 0;
}
```

compile
```
g++ test.cc -o test -std=c++11 -I./third_party/jemalloc/include/ -L./third_party/jemalloc/lib -lpthread -ljemalloc
```

run
```
MALLOC_CONF="prof:true,lg_prof_interval:20,prof_active:false,prof_prefix:jeprof.out" LD_PRELOAD=./third_party/jemalloc/lib/libjemalloc.so ./test
```

**Comment by benet96** [comment]
Please check the  return value of mallctl("prof.active", ...), 0  is succes, and the old value of prof.active. Perhaps your program does not dump enough memory for profiling with the lg_prof_sample value specified. Smaller lg_prof_sample value or more memory malloc-ed may help, default value is 512K (2^19).

**Comment by interwq** [comment]
@No-limits I believe this should have been fixed in the [dev branch](https://github.com/jemalloc/jemalloc/commits/dev). We are releasing 5.3 soon which will also include the fix.
