### ISSUE TITLE
Performance Tuning via enabling custom small bin size

### ISSUE THREAD

**Issue by sathish249** [jemalloc/jemalloc#2237]
I am trying to optimize my application to improve performance. My application has various small size allocations
24 bytes, 40 bytes, 56 bytes, 208 bytes, 144bytes, 4 bytes etc which are high frequency. Out of which size like 24,40,56 i am able to tune via "--with-lg-quantum=3" and get the BIN size. Request for the help(I am new to jemalloc source) or a pointer on how to enable BIN size for the non standard size's like 208,144,176.

**Comment by Lapenkov** [comment]
Hi. There's no way to achieve that by configuring jemalloc just yet. We've had plans to potentially add this feature in the future, though.
