### ISSUE TITLE
__memset_sse2 carsh 

### ISSUE THREAD

**Issue by ooknn** [jemalloc/jemalloc#2241]
The commit hash for the jemalloc I use is d9bbf53

The compilation process is as follows:
git clone https://hub.fastgit.org/jemalloc/jemalloc.git
cd jemalloc
./autogen.sh
./configure --enable-prof --enable-stats --enable-debug --enable-fill

I run the program with MALLOC_CONF=prof:true,prof_active:false

Thread 12 (Thread 0x7f02d7ffa700 (LWP 233)):
#0  0x00007f02f641281d in __memset_sse2 () from /lib64/libc.so.6
#1  0x00007f02f77b918a in default_junk_alloc (ptr=0x7f02cd8cefc0, usize=80) at src/jemalloc.c:133
#2  0x00007f02f77c2a51 in imalloc_body (sopts=0x7f02d7ff3150, dopts=0x7f02d7ff3110, tsd=0x7f02d7ff42a8)
    at src/jemalloc.c:2478                                                                            
#3  0x00007f02f77c2d16 in imalloc (sopts=0x7f02d7ff3150, dopts=0x7f02d7ff3110) at src/jemalloc.c:2578
#4  0x00007f02f77c2d83 in je_malloc_default (size=65) at src/jemalloc.c:2606
#5  0x00007f02f77b821e in imalloc_fastpath (size=65, fallback_alloc=0x7f02f77c2d18 <je_malloc_default>)
    at include/jemalloc/internal/jemalloc_internal_inlines_c.h:310                                 
#6  0x00007f02f77c2ea7 in malloc (size=65) at src/jemalloc.c:2630
#7  0x00007f02f6cc31bd in operator new(unsigned long) () from /lib64/libstdc++.so.6                 
#8  0x000000000063341e in boost::asio::detail::thread_info_base::allocate (this_thread=0x7f02d7ff3790,
    size=64) at boost_1_62_0/include/boost/asio/detail/thread_info_base.hpp:60
#9  0x000000000063352a in boost::asio::asio_handler_allocate (size=64)
    at boost_1_62_0/include/boost/asio/impl/handler_alloc_hook.ipp:50

When doing memset to 0x7f02cd8cefc0, the program crashed, I printed the data in the memory of 0x7f02cd8cefc0, as follows

(gdb) x/80bx 0x7f02cd8cefc0                                                                                                                            
0x7f02cd8cefc0: 0xa5    0xa5    0xa5    0xa5    0xa5    0xa5    0xa5    0xa5
0x7f02cd8cefc8: 0xa5    0xa5    0xa5    0xa5    0xa5    0xa5    0xa5    0xa5
0x7f02cd8cefd0: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8cefd8: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8cefe0: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8cefe8: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8ceff0: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8ceff8: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8cf000: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a
0x7f02cd8cf008: 0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a    0x5a

The data at 0x7f02cd8cefc0 to 0x7f02cd8cefc8 is 0xa5. At this point, I don't know what to do, how can I continue to investigate?

The OS I am using is
Linux vms-oss-0-65f67856d8-tktxm 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

the compiler is
gcc version 4.8.5 20150623

**Comment by Lapenkov** [comment]
@ooknn Did you find what the problem was?

**Comment by ooknn** [comment]
I haven't found the problem yet, but I ran the program with valgrind and found some warnings, I'm fixing them now, and if the same problem occurs again, I'll open the issue again
