### ISSUE TITLE
jemalloc does not implement pvalloc, what happens if je_free(pvalloc() @libc) 

### ISSUE THREAD

**Issue by zylthinking** [jemalloc/jemalloc#2246]
all pvalloc will call to libc; but free will call je_free, is that a problem?

**Comment by Lapenkov** [comment]
Yes, that's a problem. I think this function was overlooked either because it's a GNU extension, or because it's obsolete. But I'll add the support in the near future. Meanwhile, you can also submit a PR that adds it, if you wish.

**Comment by Lapenkov** [comment]
https://github.com/jemalloc/jemalloc/pull/2257

**Comment by interwq** [comment]
Fixed in the dev branch.
