### ISSUE TITLE
request support for bazel build system

### ISSUE THREAD

**Issue by xiedeacc** [jemalloc/jemalloc#2249]
as title

**Comment by Lapenkov** [comment]
Hello.

Thank you for the request :)

We haven't had plans to switch to Bazel, therefore I can neither satisfy the request, nor even propose to submit a PR that migrates jemalloc to Bazel.
We could conceivably switch to CMake, and it takes pretty extensive effort to do so, therefore it hasn't been done yet.

**Comment by Mr-whoz** [comment]
our system is builded by bazel,we want to use jemalloc, but we can't switch our build tool to cmake.if jemalloc support bazel,lots of bazel reposity can use jemalloc conviniently
