### ISSUE TITLE
How do you feel about putting the official release tarball on GitHub?

### ISSUE THREAD

**Issue by jszakmeister** [jemalloc/jemalloc#225]
I'm helping with the Neovim project, and we currently download a tarball from the release tag on GitHub.  We know your site has the official release tarball, but we worry about driving too much download traffic to your site.  How would you feel about hosting the tarball on GitHub?  You can do that by using the "Draft a New Release" button on the Releases page, and uploading the source tarball there.  Thoughts?

**Comment by jszakmeister** [comment]
Here's a handy url for the releases feature: https://github.com/blog/1547-release-your-software

**Comment by jasone** [comment]
I didn't know about this github feature, but it's great.  I've added the tarball for 3.6.0, and will do so for previous tagged releases as well.

**Comment by jszakmeister** [comment]
Beautiful!  Thank you!
