### ISSUE TITLE
How to accurately judge whether this memory is allocated by jemalloc?

### ISSUE THREAD

**Issue by ximu8922** [jemalloc/jemalloc#2252]
I need to accurately distinguish whether the current memory block is allocated by jemalloc. I realize windows memory replacement through hook technology.

**Comment by Lapenkov** [comment]
If I understood your question correctly, given a pointer you'd like to know if it points to a memory allocation managed by jemalloc. That is discouraged and not officially supported. So make sure that's really what you want.

Disclaimers aside, if you compile jemalloc with [this defined](https://github.com/jemalloc/jemalloc/blob/dev/include/jemalloc/internal/jemalloc_preamble.h.in#L234), you'll be able to answer your question by calling `sallocx(ptr)`. If it returns any size >0, then the allocation is managed by jemalloc.
