### ISSUE TITLE
jemalloc with --enable-prof-libunwind， run with MALLOC=prof:true , caused sigsegv

### ISSUE THREAD

**Issue by cvidkal** [jemalloc/jemalloc#2259]
I run a simple test, jemalloc with libunwind ,that'ok , when i use jemalloc to my application with jemalloc with libunwind andn prof:true,
caused segv.   When jemalloc with libgcc, it's ok.

And I get the stacktrace, it is crashed in qt.

#0  0xb637ec54 in ?? () from /home/chenguojun/robotCC/bin/../libs/libunwind.so.8
#1  0xb637f8c4 in ?? () from /home/chenguojun/robotCC/bin/../libs/libunwind.so.8
#2  0xb637fc88 in ?? () from /home/chenguojun/robotCC/bin/../libs/libunwind.so.8
#3  0xb637d6a2 in _ULarm_step () from /home/chenguojun/robotCC/bin/../libs/libunwind.so.8
#4  0xb637c600 in unw_backtrace () from /home/chenguojun/robotCC/bin/../libs/libunwind.so.8
#5  0xb6f601f8 in je_prof_backtrace (bt=bt@entry=0xbeefac54) at src/prof.c:595
#6  0xb6f269b2 in prof_alloc_prep (update=true, je_prof_active=<optimized out>, usize=4194304, tsd=0xb6ff24c8) at include/jemalloc/internal/prof_inlines_b.h:158
#7  imalloc_body (tsd=0xb6ff24c8, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2116
#8  imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2258
#9  je_malloc_default (size=<optimized out>) at src/jemalloc.c:2289
#10 0xb6709f00 in QArrayData::allocate(unsigned int, unsigned int, unsigned int, QFlags<QArrayData::AllocationOption>) () from /opt/cross-compile/qt-5.8-arm7/lib/libQt5Core.so.5
#11 0xb670ba1e in QByteArray::resize(int) () from /opt/cross-compile/qt-5.8-arm7/lib/libQt5Core.so.5
#12 0xb67bb314 in QIODevice::readAll() () from /opt/cross-compile/qt-5.8-arm7/lib/libQt5Core.so.5
#13 0xb4e583d2 in FileOperate::CheackFileMd5(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /home/chenguojun/robotCC/bin/../libs/./libmap-manager.so.1
#14 0xb4e58dc8 in BuildMap::BuildMapEvent::ProcessMap(PngToMap&, int) () from /home/chenguojun/robotCC/bin/../libs/./libmap-manager.so.1
#15 0xb4e35000 in YoGoMap::MapMgrImpl::ProcessMap() () from /home/chenguojun/robotCC/bin/../libs/./libmap-manager.so.1
#16 0xb4e3ac62 in YoGoMap::MapMgrImpl::LoadCfg(char const*, char const*) () from /home/chenguojun/robotCC/bin/../libs/./libmap-manager.so.1
#17 0x0002db56 in App::Init(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#18 0x00026b12 in main ()

**Comment by Lapenkov** [comment]
It crashes in libunwind, and by this stack trace I can't relate it to jemalloc. I suggest building libunwind locally without optimizations and with symbols, see where it fails, maybe the context will be enough to understand why it fails.

**Comment by Lapenkov** [comment]
Also, check whether your libunwind has the fix mentioned here or not:
https://github.com/libunwind/libunwind/issues/68
