### ISSUE TITLE
jemalloc rss usage  is much larger than tcmalloc

### ISSUE THREAD

**Issue by emmettwu** [jemalloc/jemalloc#2268]
Hi developers,
I tried to switch to jemalloc from tcmalloc in my application. Jemalloc performance is much better tcmalloc in my application, but rss is also much larger than tcmalloc.

When linked with jemalloc 5.1, rss is increasing for 1-2 days from 150GB to 220GB, then rss remains stable.
Same application linked with tcmalloc, rss is only 100-120GB and is very stable.
I  have set MALLOC_CONF=background_thread:true, this problem still exists.
I have tried latest dev branch, this problem still exists.
Is there any way to reduce rss usage？

**Comment by interwq** [comment]
It's hard to suggest based on the limited info. You can take a look at the tuning doc which has options to balance CPU vs memory: https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md

Or if you can share`malloc_stats` (from either the dev branch, or the 5.3 release), either from `malloc_stats_print()` or the MALLOC_CONF=stats_print:true option, we can take a look too.

Closing but feel free to ask.
