### ISSUE TITLE
test/unit/background_thread_enable reliably fails on high core-count systems

### ISSUE THREAD

**Issue by xen0n** [jemalloc/jemalloc#2272]
On testing the 5.3 RC commit ed5fc14b28ca as described in the testing issue #2213, I came across this failure with 32-bit x86.

On looking at the test code it's clear `ncpus * 10` threads are being spawned for the test:

https://github.com/jemalloc/jemalloc/blob/ed5fc14b28ca62a6ba57b65adf557e1ef09037f0/test/unit/background_thread_enable.c#L53-L56

Probably because I'm using a Threadripper 3990X with 128 threads, and 1280 threads are a bit too much for x86_32? I reduced the 10 to 5 and it passed. (8 will break too, but I didn't investigate deeper.) Maybe we should clamp the thread count to some maximum on 32-bit.

`configure` args: `../configure --disable-debug --disable-lazy-lock --disable-prof --disable-stats --disable-xmalloc --host=i686-pc-linux-gnu CC='gcc -m32' CXX='g++ -m32'`

Test log:

```
=== test/unit/background_thread_enable ===
test_deferred (non-reentrant): pass
test_max_background_threads:../test/unit/background_thread_enable.c:54: Failed assertion: (jet_mallctl("arenas.create", &id, &sz_u, ((void *)0), 0)) == (0) --> 11 != 0: Failed to create arena
 ... 536 same lines ...
<jemalloc>: background thread creation failed (11)
 ... 40 same lines ...
test_max_background_threads (non-reentrant): fail
--- pass: 1/2, skip: 0/2, fail: 1/2 ---
```

This is found during work on gentoo/gentoo#25315 (main purpose would be for the LoongArch port, but it's general toolchain work too).

**Comment by interwq** [comment]
Thanks for reporting this! Yes the test config is too aggressive. I'll put up a fix soon.
