### ISSUE TITLE
Adding hooks for mmap and munmap

### ISSUE THREAD

**Issue by Sonicadvance1** [jemalloc/jemalloc#2276]
I have hooks in my fork of JEMalloc for hooking mmap and munmap.
This is required since jemalloc can't use the OS/glibc provided mmap/munmap functions to get memory.
JEMalloc in my fork is living in a constrained environment where virtual address space is at a premium.

To support this case I've added hooks that default to OS provided mmap/munmap but are visible symbols that can be overridden.
This is definitely in a way that can't be upstreamed, but I don't know which way it should be changed to support upstreaming.

Here's my small downstream commit that adds the hooks: https://github.com/FEX-Emu/jemalloc/commit/2c7c069c8ffe224caaee9b878ef9272173a0c409

What could be done to achieve the same results that are viable to be taken upstream?

**Comment by zylthinking** [comment]
why jemalloc can't use the OS/glibc provided mmap/munmap?
I do provided a mmap/munmap/remap with jemalloc simply using syscall, does it have problems?

In my option,  my mmap is same with glibc mmap,  if jemalloc can't use glibc's mmap, it can't use my mmap;
But I don't meet any problem yet

```c

extern "C" void* mmap(void* addr, size_t length, int prot, int flags, int fd, off_t offset)
{
    refuge_init();
    size_t page = refuge.page - 1;
    length = (length + page) & (~page);

    addr = (void*) syscall(__NR_mmap, addr, length, prot, flags, fd, offset);
    if (addr != (void*) -1) {
        mmap_item_t* item = mmap_item_alloc();
        item->stacks = trace_back_mmap(item->pc, sizeof(item->pc) / sizeof(item->pc[0]));
        item->range[0] = (intptr_t) addr;
        item->range[1] = (intptr_t) addr + length;
        item->type = 0;
        __atomic_add_fetch(&refuge.mmap_bytes, length, __ATOMIC_RELAXED);

        lkf_node_put(&refuge.list, &item->node);
    }
    return addr;
}


```

**Comment by Sonicadvance1** [comment]
In my environment a raw `syscall(__NR_mmap` will return ENOMEM. It will need to call in to a different mmap implementation to ensure virtual address space can be allocated.

**Comment by Lapenkov** [comment]
The capability to set such hooks already exists - https://jemalloc.net/jemalloc.3.html#arena.i.extent_hooks

See `extent_alloc_t` hook.
