### ISSUE TITLE
Change library 'name' to full path for OSX

### ISSUE THREAD

**Issue by jonthn** [jemalloc/jemalloc#228]
Would it be possible to change library name (```install_name_tool -id ..``` equivalent) to the full path for the shared library ?

For instance I made this change to solve my problem
```
-       DSO_LDFLAGS='-shared -Wl,-dylib_install_name,$(@F)'
+       DSO_LDFLAGS='-shared -Wl,-install_name,$(LIBDIR)/$(@F)'
```

Maybe for other use it would even be better to be able to deactivate this and return to the old behavior. But I don't know how *jemalloc* is used by projects.

**Comment by jasone** [comment]
Your suggestion appears to follow standard practice.  I'll make the change momentarily.

**Comment by jonthn** [comment]
Thanks.
