### ISSUE TITLE
Rename 'bin/pprof' to an executable with a je prefix

### ISSUE THREAD

**Issue by jonthn** [jemalloc/jemalloc#229]
If you install Google Perftools ( https://code.google.com/p/gperftools/ ) in the same prefix as jemalloc, one overwrite the other 'bin/pprof'.

Maybe it would be appropriate to rename the *jemalloc* version ?

**Comment by jasone** [comment]
```jemalloc_pprof``` is an obvious candidate, but it's rather verbose.  ```jeprof``` is also justifiable, since that's the default file suffix.
