### ISSUE TITLE
[question] Is jemalloc-cmake dead?

### ISSUE THREAD

**Issue by JackBoosY** [jemalloc/jemalloc#2295]
The last commit in jemalloc-cmake is https://github.com/jemalloc/jemalloc-cmake/commit/abeb19f8493feb67a2a8f121ea9bab1829f8d3fb 5 years ago.
After that, the contents of this repo are not synced there anymore.

Does this indicate that jemalloc has officially deprecated jemalloc-cmake?
If yes, then we should deprecate https://github.com/microsoft/vcpkg/pull/25227 in favor of this repo.

**Comment by Lapenkov** [comment]
I'm not empowered to make official statements, but according to my knowledge, that repo with CMake support has not been maintained by jemalloc developers (other than some commits by jasone a while ago). Looks like there was an active maintainer 5 years ago, you might ask that person.

**Comment by JackBoosY** [comment]
cc @yuslepukhin

**Comment by davidtgoldblatt** [comment]
Yeah, jemalloc-cmake is more or less dead; I've tried a couple of times to get a CMake build up and running, but it's fairly nontrivial to migrate the thousands of lines of autotools scripts we've got.

**Comment by JackBoosY** [comment]
@davidtgoldblatt I wish you guys notice this in the jemalloc-cmake readme. But I'm going to close this issue now.

**Comment by yuslepukhin** [comment]
I have not been working on it for a while. Except some projects that rely on jemalloc pools management, we migrated to another memory allocator.
