### ISSUE TITLE
opt.retain make program run out of memory in a restricted virtual memory environment.

### ISSUE THREAD

**Issue by akamit91** [jemalloc/jemalloc#2297]
I have a application running in FreeBSD that sets limits on "The maximum amount of virtual memory the process is allowed to map." via https://www.freebsd.org/cgi/man.cgi?setrlimit RLIMIT_AS.
With opt.retain=true it crosses the VM limit pretty fast. If opt.retain = false the program never breaches the limit. Can someone suggest me if using   opt.retain = true is a good idea for this kind of environment, or if there is a way to set a default limit on retain_grow_limit without using mallctl maybe by making changes to arena_new() ?  

To further demonstrate the issue , I have written a small code
OS FreeBSD 14.0-CURRENT

```
int main() {
        void *ret;
        struct rlimit limit = {0};
        limit.rlim_cur = limit.rlim_max = 1024*1024*16;
        setrlimit(RLIMIT_AS, &limit);
        for(int i=0;i<INT_MAX;i++){
            printf("i = %d \n", i);
            ret=malloc(4096*1024);
            if(!ret)
                abort();

            free(ret);
        }
}
```

MALLOC_CONF=retain:true ./a.out
i = 0
[1]    6143 abort (core dumped)  MALLOC_CONF=retain:true ./a.out

But

MALLOC_CONF=retain:false ./a.out
i = 0
i = 1
i = 2
i = 3
......Will keep running

**Comment by Lapenkov** [comment]
For that kind of environment, `opt.retain=true` is a bad choice. This option is designed for environments that have divergence in the availability of physical and virtual memory. If your virtual memory is limited, and you want its usage to be as close to your actual allocations as possible, disable `opt.retain`. You might also want to tune other options to preserve memory, but that's out of the scope of this question.
