### ISSUE TITLE
Error while trying to dump heap stats

### ISSUE THREAD

**Issue by tgurram9** [jemalloc/jemalloc#2308]
### **info**

Built jemalloc with the following configuration
`./configure --with-malloc-conf=narenas:48,tcache_nslots_small_max:2000,tcache_nslots_large:512,tcache_gc_delay_bytes:4096,background_thread:true,metadata_thp:auto,mutex_max_spin:1000,dirty_decay_ms:5000,muzzy_decay_ms:0 --enable-prof --disable-prof-libgcc --disable-fill --enable-stats`

Exported the MALLOC_CONF as follows, before running the below mentioned code.
`export MALLOC_CONF="prof:true,prof_prefix:jeprof.out"`

### **problem**

Getting no such file or directory error, while trying to dump heap stats with the help of the following code.

```
const char fileName = "heap_info.out";
int rc = mallctl("prof.dump", NULL, NULL,&fileName, sizeof(const char ));
if (rc != 0) {
html_page.AddText(StringPrintf("Failed to dump with error %d", rc));
} else {
html_page.AddText(StringPrintf("Heap stats dumped to %s", fileName));
}
```

**Comment by interwq** [comment]
Nothing jumps out to me. Does the process have write access to its location? Maybe try `prof_prefix:/tmp/jeprof` to verify.

**Comment by interwq** [comment]
Closing but feel free to ask.
