### ISSUE TITLE
install: cannot stat ‘doc/jemalloc.html’: No such file or directory

### ISSUE THREAD

**Issue by zzak** [jemalloc/jemalloc#231]
Recently, jemalloc stopped compiling for me:

```
# from both master and release
#git clone git://github.com/jemalloc/jemalloc.git
wget https://github.com/jemalloc/jemalloc/archive/3.6.0.tar.gz
tar -xvzf 3.6.0.tar.gz -C jemalloc
cd jemalloc
./autogen.sh
./configure --enable-autogen --prefix="$BUILD_DIR/vendor"
make && make install
```

Maybe because autogen and then configure are causing issues.
How can I pass prefix to autogen? That may solve this issue.

**Comment by ldalessa** [comment]
Not sure about 3.6.0, but I've always had to run `make dist` before `make install` with the dev branch.

http://www.canonware.com/pipermail/jemalloc-discuss/2013-May/000593.html

**Comment by jasone** [comment]
Yes, you need to ```make dist``` in order to build the docs unless you grab a release tarball, e.g. the one for [3.6.0](https://github.com/jemalloc/jemalloc/releases/download/3.6.0/jemalloc-3.6.0.tar.bz2).

**Comment by dmitri-shubin** [comment]
Hi!

I have the same error for release 4.0.3 tarball --  https://github.com/jemalloc/jemalloc/releases/download/4.0.3/jemalloc-4.0.3.tar.bz2

**Comment by chaoran** [comment]
`make dist` gave me an error:
```
/usr/bin/xsltproc -o doc/jemalloc.html doc/html.xsl doc/jemalloc.xml
warning: failed to load external entity "/html/docbook.xsl"
compilation error: file doc/html.xsl line 2 element import
xsl:import : unable to load /html/docbook.xsl
make: *** [doc/jemalloc.html] Error 5
```

I'm building release 4.0.4. I tried both out-of-tree build and in-place build.

**Comment by jasone** [comment]
@chaoran, you didn't configure XSL, or it's missing from your system.  Make sure you have the appropriate software installed, and if so, make sure it's found during configuration.  The following configure parameter settings are commonly required:

```
  --with-xslroot=/usr/local/share/xsl/docbook # FreeBSD
  --with-xslroot=/opt/local/share/xsl/docbook-xsl # OS X
```

**Comment by chaoran** [comment]
@jasone Is there a way to avoid building docs? I don't have XSL on my system, which I do not have administrator privilege. And I don't need the docs at all.

**Comment by jasone** [comment]
Yes: ```make && make install_bin install_include install_lib```

**Comment by marxin** [comment]
Hi.

I see same error. On Linux, I have installed package docbook-xsl-stylesheets, but I can't find ```doc/html.xsl``` provided by the package:

```
$ rpm -ql docbook-xsl-stylesheets | grep 'html.xsl'
/usr/share/xml/docbook/stylesheet/nwalsh/1.79.2/html/html.xsl
/usr/share/xml/docbook/stylesheet/nwalsh/1.79.2/xhtml-1_1/html.xsl
/usr/share/xml/docbook/stylesheet/nwalsh/1.79.2/xhtml/html.xsl
```

Can you please explain me what kind of template is requested?

**Comment by marxin** [comment]
Thanks, using a bit different template works for me:
```
./configure --with-xslroot=/usr/share/xml/docbook/stylesheet/nwalsh/1.79.2/
```
