### ISSUE TITLE
Cross compile for ARM

### ISSUE THREAD

**Issue by daniel6651** [jemalloc/jemalloc#233]
Hi

COuld not find any instructions for cross compiling jemalloc for ARM.
Tried the following, but there is an error. What is the proper way to run configure here? On Linux x86 and compiling for ARM.
3.6.1 seems to missing configure as well, so tried an older version 3.4.1 because of that.

=> ./configure --host=arm-wrs-linux-gnueabi  --with-sysroot=$DISTRO/arm-wr6
configure: WARNING: unrecognized options: --with-sysroot
checking for xsltproc... /usr/bin/xsltproc
checking for arm-wrs-linux-gnueabi-gcc... arm-wrs-linux-gnueabi-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-wrs-linux-gnueabi-gcc accepts -g... yes
checking for arm-wrs-linux-gnueabi-gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /lib/cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 4
checking size of int... 4
checking size of long... 4
checking size of intmax_t... 8
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-wrs-linux-gnueabi
checking for arm-wrs-linux-gnueabi-ar... arm-wrs-linux-gnueabi-ar
checking whether __attribute__ syntax is compilable... yes
checking whether compiler supports -fvisibility=hidden... yes
checking whether compiler supports -Werror... yes
checking whether tls_model attribute is compilable... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for arm-wrs-linux-gnueabi-ranlib... arm-wrs-linux-gnueabi-ranlib
checking for ld... /xyz/Linux/i386/bin/ld
checking for autoconf... /usr/bin/autoconf
checking for memalign... yes
checking for valloc... yes
checking configured backtracing method... N/A
checking for sbrk... yes
checking whether utrace(2) is compilable... no
checking whether valgrind is compilable... no
checking STATIC_PAGE_SHIFT... configure: error: in `/home/xyz/jemalloc-3.4.1':
configure: error: cannot run test program while cross compiling
See `config.log' for more details

**Comment by jasone** [comment]
Use a newer version of jemalloc, and see the sh4.cache file attached to http://www.canonware.com/pipermail/jemalloc-discuss/2011-April/000018.html for an example of how to specify configure information when cross compiling.

**Comment by AbdulmalikAlyousfi** [comment]
Hi Jasone,

I am running into the same issue and the link you have provided above is down.
is there an alternative link/fix.

thanks
