### ISSUE TITLE
Add chunk_dealloc_dss to reduce a process's Vm Size when using jemalloc + DSS Primary

### ISSUE THREAD

**Issue by khannasusa** [jemalloc/jemalloc#234]
All the details are in this post - http://www.canonware.com/pipermail/jemalloc-discuss/2015-May/001110.html

thanks
--sk

**Comment by jasone** [comment]
```sbrk()``` is racy, and there is no way to reliably avoid discarding memory that was directly allocated via ```sbrk()``` by the application.  This could in principle be supported for single-threaded applications, but reliably detecting whether the application is multi-threaded is too much of a portability burden to make this feature an acceptable maintenance cost.
