### ISSUE TITLE
Heap profiling does not work when`--with-jemalloc-prefix=xxx` is set

### ISSUE THREAD

**Issue by spaces-X** [jemalloc/jemalloc#2366]
I found that the heap profiling does not work when `with-jemalloc-prefix` is set using jemalloc.
The steps of my  demo case are as follows.

1. build the jemalloc with version 5.3.0
` ./configure --prefix="/opt/jemalloc" --with-jemalloc-prefix=je --enable-prof --disable-cxx --disable-libdl --disable-shared`
`make -j 8 && make install`

2. build my demo test program with gcc
`gcc -I/opt/jemalloc/include test.c -L/opt/jemalloc/lib -Wl,-Bstatic -ljemalloc -DJEMALLOC_NO_DEMANGLE -Wl,-Bdynamic -lm -Wl,-Bdynamic -lpthread -Wl,-Bdynamic -ldl  -o test`

```test.c
// test.c
#include <stdio.h>
#include <stdlib.h>
#include <jemalloc/jemalloc.h>


void do_something(size_t i)
{
  // Leak some memory.
  je_malloc(i * 1024);
}


int main(int argc, char **argv)
{
  size_t i, sz;
  printf("call do something 80 times\n");
  for (i = 0; i < 80; i++)
  {
    do_something(i);
  }
  printf("call do something 40 times\n");

  for (i = 0; i < 40; i++)
  {
    do_something(i);
  }

  return (0);
}

```

3. enable heap profile in  malloc_conf and start to run my test program
```export MALLOC_CONF="prof:true,lg_prof_interval:20,prof_leak:true,lg_prof_sample:0,prof_final:true"```
```./test```

The test program can terminate normally but no profile file is generated.
If i drop the `with-jemalloc-prefix=xxx` in step 1, heap profiling can work normally.

Is there any problem with my usage?

**Comment by interwq** [comment]
You need to prefix the `MALLOC_CONF` as well. See details in https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md

To verify that the conf setting is recognized, you can try adding `abort_conf:true,abc:123` to the setting string, and it should abort immediately and report its not valid.

**Comment by spaces-X** [comment]
> You need to prefix the `MALLOC_CONF` as well. See details in https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md
> 
> To verify that the conf setting is recognized, you can try adding `abort_conf:true,abc:123` to the setting string, and it should abort immediately and report its not valid.


For this case, i change the `export MALLOC_CONF ` to `export JEMALLOC_CONF ` and it works.
Thanks a lot.
