### ISSUE TITLE
Page size problem on ARM

### ISSUE THREAD

**Issue by dmn22-3ds** [jemalloc/jemalloc#2377]
Unlike X86, not all ARM systems use the same page size.

We build our ARM build on a Linux system with 64 KB page size and tests pass there. But we found that malloc(64) is frequently returning a pointer to unmapped memory when run on a Linux system with 4 KB page size, specifically Amazon AWS c6g Ubuntu "20.04.5 LTS (Focal Fossa)". In the specific failure I studied carefully, the value returned from malloc was 0xffff889ff000, the beginning of the last 4 KB page of a 64 KB block but I don't know whether that is relevant.

Is this a bug in jemalloc 5.3.0-0-g54eaed1d8b56b1aa528be3bdd1877e59c56fa90c or do we need to configure it differently to make it run correctly with different page sizes at compile time and at run time?

**Comment by interwq** [comment]
No known issue around this part. The configured page size needs to be >= the runtime page size, e.g. if you build jemalloc with `--with-lg-page=16` it will use 64K pages at the jemalloc level, which is compatible with lower page sizes (but not the other way around).

See https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md for more details.

Closing but feel free to ask if anything.

**Comment by dmn22-3ds** [comment]
I don't think it is true that a runtime page size less than the configured page size will work. That's not what we observe. Has this feature been tested on ARMv8?

Our config.log says
#define LG_PAGE 16
#define LG_HUGEPAGE 29
so the configured page size is 64K. The shell pagesize command says 4096 on the AWS instance where jemalloc is not working correctly.

Is it relevant that we recently started using "arena." STRINGIFY(MALLCTL_ARENAS_ALL) ".purge" when memory becomes too full? I don't think so, because I don't think this code had been executed before the SEGV occurred, although that's difficult to prove. I could add a counter of the number of times it has been done.

Is there anything I can do to get more information about what is happening?

Do you want me to try to construct a standalone reproducible test case? The problem is I don't have personal access to the AWS instances we use, so there would be a delay while I get that permission.

Can you reopen this please?

**Comment by dmn22-3ds** [comment]
I have not been able to reproduce the problem with a simple test program so maybe I am wrong that it is caused by the page size. Maybe the problem is something else, possibly related to Red Hat vs. Ubuntu.

QUESTION: Is there a way to exfiltrate jemalloc's internal data structures from a core file?

**Comment by dmn22-3ds** [comment]
The cause turned out to be something else, so you can leave this closed.
