### ISSUE TITLE
How to maximize jemalloc performance

### ISSUE THREAD

**Issue by xinyiZzz** [jemalloc/jemalloc#2378]
Assuming sufficient memory, we test that Jemalloc performance is lower than Tcmalloc.
Can Jemalloc MALLOC_CONF be optimized again? or other optimization ideas

I can provide more debug info if needed,
Similar issue: https://github.com/jemalloc/jemalloc/issues/279, in 2015, whether the conclusion is still correct.

test:
Apache Doris tests ssb-flat. Jemalloc is about 10% slower

Jemalloc conf: (version: 5.2.1)
```
MALLOC_CONF="percpu_arena:percpu,background_thread:true,metadata_thp:auto,muzzy_decay_ms:-1,dirty_decay_ms:-1,oversize_threshold:0,lg_tcache_max:24,thp:always,retain:true"
```

tcmalloc-conf:  (version: gperftools-2.10 tcmalloc)
```
tcmalloc.aggressive_memory_decommit=false
tc_max_total_thread_cache_bytes=1073741824
```

**Comment by breisig** [comment]
Always looking for MALLOC_CONF optimizations but if your saying jemalloc is about 10% slower, this is a problem.

**Comment by interwq** [comment]
Not really actionable based on the info here. I'd also suggest not over optimize for a benchmark but rather focus on the real workload instead.

If you really want to figure out why the benchmark runs slower, try running with `perf record` and `perf report` which helps quantify cost distribution.

**Comment by xinyiZzz** [comment]
> Not really actionable based on the info here. I'd also suggest not over optimize for a benchmark but rather focus on the real workload instead.
> 
> If you really want to figure out why the benchmark runs slower, try running with `perf record` and `perf report` which helps quantify cost distribution.

Thanks for your advice, I will try to analyze `perf record`.
