### ISSUE TITLE
random coredump  with jemalloc (unknown version)

### ISSUE THREAD

**Issue by EricccYang** [jemalloc/jemalloc#2390]
version: unknown ( don't know who build it )
how to use jemalloc : LD_PRELOAD
kernel : 4.9.151   x86_64 GNU/Linux
what happens: 
After about 30 hours from starting our application using jemalloc, here comes  some coredumps,  those coredumps have different stack, one of those is showing later.    
The probability of causing coredump looks not high, but it is more unstable than using malloc in libc, we don't get coredumps with libc malloc for years.
really want to know the reason about this.

here are some guesses :
1. the jemalloc we are using is incompatible with some libs already in our applicaiton
2. using a unstable version of jemalloc

here is one of the coredump stack:

#0  0x00007f878d0d4caf in __exchange_and_add (__val=-1, __mem=0xa0fa4630) at /usr/include/c++/4.9.2/ext/atomicity.h:49
#1  __exchange_and_add_dispatch (__val=-1, __mem=0xa0fa4630) at /usr/include/c++/4.9.2/ext/atomicity.h:82
#2  std::string::_Rep::_M_dispose (this=0xa0fa4620, __a=...) at /usr/include/c++/4.9.2/bits/basic_string.h:246
#3  0x00007f878d0d619a in _M_dispose (__a=..., this=0xa0fa4620) at /usr/include/c++/4.9.2/bits/basic_string.h:240
#4  ~basic_string (this=0x7f6ced81bb38, __in_chrg=<optimized out>) at /usr/include/c++/4.9.2/bits/basic_string.h:547
#5  ~pair (this=0x7f6ced81bb30, __in_chrg=<optimized out>) at /usr/include/c++/4.9.2/bits/stl_pair.h:96
#6  _Destroy<std::pair<std::basic_string<char>, std::basic_string<char> > > (__pointer=0x7f6ced81bb30) at /usr/include/c++/4.9.2/bits/stl_construct.h:93
#7  __destroy<std::pair<std::basic_string<char>, std::basic_string<char> >*> (__last=<optimized out>, __first=0x7f6ced81bb30) at /usr/include/c++/4.9.2/bits/stl_construct.h:103
#8  _Destroy<std::pair<std::basic_string<char>, std::basic_string<char> >*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/4.9.2/bits/stl_construct.h:126
#9  _Destroy<std::pair<std::basic_string<char>, std::basic_string<char> >*, std::pair<std::basic_string<char>, std::basic_string<char> > > (__last=0x7f6ced81bb40, __first=<optimized out>)
    at /usr/include/c++/4.9.2/bits/stl_construct.h:151
#10 ~vector (this=0x7f866d69f000, __in_chrg=<optimized out>) at /usr/include/c++/4.9.2/bits/stl_vector.h:424
#11 wings_worker::OrAnalyzerProcessor::doProcess (this=0x7f6b644de770, context=...) at build/release64/qr_app/basic_analysis/processor/basic_algorithm/OrAnalyzerProcessor.cpp:339
#12 0x00007f878c21b83f in amap_qr::processor::AProcessor::process (this=0x7f6b644de770, context=...) at build/release64/qr_app/frame/processor/AProcessor.cpp:22
#13 0x00007f87a2672208 in wings_worker::worker::NormalProcessorExecutor::execute (this=<optimized out>, context=...) at build/release64/wings_worker/worker/NormalProcessorExecutor.cpp:58
#14 0x00007f87a2671081 in wings_worker::worker::PhaseExecutor::execute (this=0x7f869d2999a0, context=...) at build/release64/wings_worker/worker/PhaseExecutor.cpp:39
#15 0x00007f87a267066e in wings_worker::worker::ChainExecutor::execute (this=0x7f869d2cbc80, context=...) at build/release64/wings_worker/worker/ChainExecutor.cpp:56
#16 0x00007f87a266fd50 in wings_worker::worker::ParallelExecuteItem::process (this=0x7f68d1831cc0) at build/release64/wings_worker/worker/ParallelExecuteItem.cpp:39
#17 0x00007f87a187fe17 in autil::ThreadPool::workerLoop (this=0x7f869d0505c0) at build/release64/autil/ThreadPool.cpp:175
#18 0x00007f87a187f673 in operator() (this=0x7f869d199e30) at /usr/include/c++/4.9.2/tr1/functional:2146
#19 autil::Thread::threadWrapperFunction (arg=0x7f869d199e30) at build/release64/autil/Thread.cpp:19
#20 0x00007f87a11b0e25 in start_thread () from /usr/lib64/libpthread.so.0
#21 0x00007f87a04b4f1d in clone () from /usr/lib64/libc.so.6

**Comment by interwq** [comment]
Hard to say given the info here. My best guess is there's some heap corruption that is often silent, but with the different allocators the memory layout / pattern becomes different so it may become more noticeable under some allocators.

I'd recommend try a sanitizer run first, e.g. with ASAN etc and see if they catch anything. Closing but feel free to ask questions.
