### ISSUE TITLE
Experiment with better "clocks".

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#24]
jemalloc has no true sense of time, but it effectively measures time in units of allocation events.  In particular, the tcache code uses an event counter to drive its incremental garbage collection, but unfortunately this is only a weak proxy for what tcache really wants to know -- wall time elapsed since a previous event.  Furthermore, the unused dirty page purging code is in dire need of time sense so that hysteresis can be incorporated into the purge rate.

Experiment with clocks that actually track wall time (one second granularity is likely good enough for intended purposes), determine how expensive they are to use, and develop strategies for using them where needed to the fullest extent possible.  Data points: time(2) is a vsyscall on Linux 3.2, and gettimeofday() is a vsyscall on Linux 2.6.32.  Assuming that clock overhead is manageably low across all operating systems of interest, use clocks to:
- Introduce hysteresis into unused dirty page purging.  This will require logic changes and will impact application-visible tuning parametrization, but internal data structures will need little modification beyond changes necessary to support a global limit on aggregate tcache size.
- Introduce hysteresis into tcache flushing based on time rather than event count, and experiment with dynamically growing tcaches to match demand.  (tcache is currently effective at amortizing mutex overhead, but falls far short in terms of handling large short-term swings in memory usage.)

**Comment by thestinger** [comment]
MADV_FREE is now in linux-next so it's only a matter of time before it lands in mainline.
