### ISSUE TITLE
Using explicit huge pages (2MB and 1GB) with custom extent hooks

### ISSUE THREAD

**Issue by rezafmk** [jemalloc/jemalloc#2403]
I have created a pool allocator that is implemented with jemalloc's extent hooks. I have experimented with THP and explicit huge pages separately and found that explicit ones give my application a much better boost, so I'm going to stick with those.

The way I have used explicit huge pages (starting with 2MB ones on x86), is that I initially allocate a large mapping with `mmap(... MAP_HUGETLB ...)` (i.e., my fixed size pool), and then also compiled jemalloc with `--with-lg-page=21` so that my alloc hook is always asked to allocate `>=2MB` pages, which I supply from pages of that mapping. As a side note, I understand there might be more fragmentation issues with such large pages, but that doesn't really hurt my application.

Now that I'd like to do the same with 1GB explicit huge pages, I hit a few issues. I compile jemalloc with `--with-lg-page=30` (and make sure either my system default's HP size is that large or at least I have `--with-lg-hugepage=30` as well). It seems like such a large page size causes a bunch of variable overflows in jemalloc, as evident by some compile warnings as well (and at runtime jemalloc hangs). Here's just an example, but I've seen more issues beyond this:
```
src/emap.c:209:31: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  assert(edata_size_get(edata) > (2 << LG_PAGE));
```

So I'm wondering

1. if my approach of using explicit huge pages (via extent hooks + customized `--with-lg-page`) is the right one, when trying to use explicit huge pages.
2. if there's no other way to make extent hooks work with explicit huge pages, should this issue be considered a bug when `--with-lg-page=30`?

Please note that it is possible for me to still have a `--with-lg-page` smaller than 30 despite having 1GB explicit huge pages, but that adds another layer of _partial_-page management to my pool allocator, and I thought maybe I'm missing a more straightforward way to do this. @interwq sorry for pinging you, but I see you're an expert on using hooks, hence maybe you have the answer at the back of your head. Much appreciated.

**Comment by interwq** [comment]
@rezafmk The best example I'd suggest to look, is hhvm which uses customized hooks to manage huge pages (both 2MB and 1G), e.g. https://github.com/facebook/hhvm/blob/master/hphp/util/alloc.cpp#L491

[edit] also the --with-lg-hugepage is more designed for transparent huge pages, not for the 1G explicit case.

**Comment by interwq** [comment]
Closing but feel free to ask if anything.

**Comment by subhajit-cdot** [comment]
Hi @interwq ,
I have a question regarding this . I am using an dpdk application inside virtual machine. I have memory backed the virtual machine (from host to guest ) with 1GB hugepages , but inside VM I have both 1GB and 2MB hugepages. For allocating memory I am using zmalloc_aligned() which internally calls posix_memalign() with RTE_CACHE_LINE_SIZE alignment. I have preloaded Jemalloc library for my application and it uses jemalloc. However it is not taking memory from 1GB hugepages but using 2MB hugepages (same things happens without Jemalloc as well) which leads to lots of TLB miss and introducing memory latency etc. what are the alternate option to configure Jemalloc to use memory from 1GB hugepages ? (using rte_malloc could be an option to 1GB hugepages but I want to use Jemalloc for better performance.)

Thanks 
Subhajit
