### ISSUE TITLE
[Question] SIGSEGV when dallocx() in a dlopened shared library, which is statically linked to jemalloc 

### ISSUE THREAD

**Issue by binmahone** [jemalloc/jemalloc#2404]
Hi, 

I have reproduced my problem in a minimal project https://github.com/binmahone/test1/tree/b_dlopen_fail, where:

- main() dlopens a shared library(called liblibb.so) and calls its func()
- liblibb.so is statically linked to `/tmp/je/lib/libjemalloc_pic.a`
- in func(), malloc and dallocx are called respectively

and I'm seeing the following two error stacktrace randomly:

stacktrace 1:

> __GI_raise 0x00007f5388c5900b
__GI_abort 0x00007f5388c38859
rtree_child_leaf_tryread rtree.c:146
je_rtree_leaf_elm_lookup_hard rtree.c:233
rtree_leaf_elm_lookup rtree.h:411
rtree_metadata_read rtree.h:443
emap_alloc_ctx_lookup emap.h:238
ifree jemalloc.c:2877
dallocx jemalloc.c:3890
func() libb_bar.cpp:25
main main.cpp:44
__libc_start_main 0x00007f5388c3a083
_start 0x0000561be66a3d6e

stacktrace 2:

> edata_szind_get_maybe_invalid edata.h:267
edata_szind_get edata.h:275
arena_dalloc arena_inlines_b.h:324
idalloctm jemalloc_internal_inlines_c.h:120
ifree jemalloc.c:2893
dallocx jemalloc.c:3890
func() libb_bar.cpp:25
main main.cpp:44
__libc_start_main 0x00007f6b10d93083
_start 0x000055f580fe0d6e

However,

- If I choose not to use dlopen and link liblibb.so directly to main, or
- If I replace the dallocx() call with free()

then no such errors are observed.

I'm wondering why this happens, is it because of the way I'm using jemalloc, or is it a bug or something?
BTW, I'm building libjemalloc_pic.a from jemalloc v5.3.0 with `./configure --prefix=/tmp/je --enable-debug --disable-initial-exec-tls`

Any insights would be really appreciated, thanks!

**Comment by guangli-dai** [comment]
Not sure why but it seems the stack trace given does not match the latest source codes: [jemalloc.c:2893](https://github.com/jemalloc/jemalloc/blob/dev/src/jemalloc.c#L2893) is not in `ifree`. Maybe it's an older version instead of an upstream one? Can you try the latest upstream version?

**Comment by binmahone** [comment]
hi @guangli-dai , I'm using jemalloc v5.3.0 , which seems to be the latest release version (https://github.com/jemalloc/jemalloc/tree/5.3.0). Do you believe it's a bug already fixed in dev branch?

**Comment by guangli-dai** [comment]
I see. The stack trace indicates that the pointer to be deleted is not registered in jemalloc. In this case, it's possible that the `malloc` in `func` has not actually been linked to jemalloc. When using other standard deallocation function, i.e., `free`, jemalloc will not be used as well and thus causes no errors. Can confirm this through `gdb` to see whether `malloc` goes into jemalloc. If the guess is correct, configure `LD_PRELOAD` when running your main like [this](https://github.com/jemalloc/jemalloc/wiki/Getting-Started) should work. Made the guess above assuming you are running on Linux.

**Comment by binmahone** [comment]
hi @guangli-dai ,  I have tried your advises are prove you're right.

thanks!
