### ISSUE TITLE
Question about assertions in hpa_from_pai

### ISSUE THREAD

**Issue by ericm1024** [jemalloc/jemalloc#2412]
I've been trying to read and understand the HPA code, and I noticed these assertions in `hpa_from_pai`
```
static hpa_shard_t *
hpa_from_pai(pai_t *self) {
	assert(self->alloc = &hpa_alloc);
	assert(self->expand = &hpa_expand);
	assert(self->shrink = &hpa_shrink);
	assert(self->dalloc = &hpa_dalloc);
	return (hpa_shard_t *)self;
}
```
It looks like those assertions are re-assigning the fields every time? Is this a typo, i.e. should these be `==` instead of `=`?

Let me know if I've misunderstood something.

**Comment by interwq** [comment]
It does look like a bug to me. Thanks for catching it! Please feel free to submit a PR, or let me know if you'd prefer us to do that.
