### ISSUE TITLE
php-fpm: free(): invalid pointer when used with jemalloc

### ISSUE THREAD

**Issue by makhomed** [jemalloc/jemalloc#2419]
When I install jemalloc package jemalloc-5.2.1-2.el9.x86_64 from the [EPEL repo](https://docs.fedoraproject.org/en-US/epel/) on the [Rocky Linux 9.1](https://rockylinux.org/) and enable using /usr/lib64/libjemalloc.so.2 by all processes on the system by the /etc/ld.so.preload - I got php-fpm process crashed on the start.

PHP developers say, what this is not a PHP bug: https://github.com/php/php-src/issues/11133 because this is current state, what "any application that uses RTLD_DEEPBIND to load its libraries can break". 

This is means, what it is not possible to use jemalloc be all processes by just placing /usr/lib64/libjemalloc.so.2 library filename in the system-wide configuration file /etc/ld.so.preload

So, this is means what such way of preloading /usr/lib64/libjemalloc.so.2 via /etc/ld.so.preload config on the modern Linux operating systems is very dangerous, because it lead to unexpected crashes of many Linux processes.

So, this is means what preloading /usr/lib64/libjemalloc.so.2 via /etc/ld.so.preload config on the modern Linux operating systems can't be used it the production and should not be used at all.

Does this fact is described it the jemalloc documentation?

I look at the https://jemalloc.net/ site and jemalloc wiki https://github.com/jemalloc/jemalloc/wiki but I can't find such warnings for jemalloc users.

Or everyone already know, what jemalloc mainly for testing and memory statistics and should not be used in the production, at least as system-wide replacement of the standard glibc malloc/free/etc functions?

At least, I did not know about this, and got php-fpm crashes on the production server.

As I understand, standard glibc memory allocator is slower but more safe and robust and should be used in the production. And jemalloc, at least in the dynamical linking via /etc/ld.so.preload should not be used on the production systems because this is unstable and unpredictably. 

And using jemalloc with LD_PRELOAD for concrete programs should be with very great care and understanding of all possible consequences. Better for devops an system administrators of production Linux servers don't touch jemalloc with dynamically linking library and replacing via LD_PRELOAD glibc malloc/free/etc at all, I right?

**Comment by interwq** [comment]
>  I right?

No. You need to understand the problem first. Plenty of materials online, e.g. https://twitter.com/ParkyMatthew/status/1630500641708683268
