### ISSUE TITLE
Improve interaction with transparent huge pages

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#243]
The unused dirty page purging functionality wreaks havoc on [Linux transparent huge pages](https://www.kernel.org/doc/Documentation/vm/transhuge.txt).  There are multiple phases to this problem:
1. Chunk allocation results in huge pages if chunks are at least 2 MiB because chunks are naturally aligned.
2. Unused dirty page purging tells the kernel to discard individual 4 KiB pages within what started out as a huge page.
3. jemalloc recycles the discarded virtual memory ranges during page run allocation, but even if the entire chunk becomes in-use again, unless the kernel picks just the right physical 4 KiB pages, it later has to shuffle physical memory to re-create the huge page.

Following are some possibilities for how to better interact with transparent huge pages:
- Reduce unused dirty page purging activity, e.g. as outlined in #149.  This might reduce the churn enough that the kernel could keep up.
- Explicitly use (and track per chunk) the `MADV_HUGEPAGE` and `MADV_NOHUGEPAGE` `madvise(2)` options.  Huge allocations could be uniformly set to `MADV_HUGEPAGE`, and each arena chunk could be marked `MADV_NOHUGEPAGE` during the first applicable dirty page purge.  This would also improve behavior if the kernel were set to the `madvise` mode rather than `always` (`/sys/kernel/mm/transparent_hugepage/enabled`).
- Expose huge page functionality to the application via some API that allows for better allocation placement decisions.  Unfortunately, with the exception of huge allocations this devolves to the allocation lifetime problem -- if we knew in advance the lifetimes of all allocations we could achieve optimal placement, but the application rarely understands its own behavior well enough to provide high fidelity lifetime information.

**Comment by glandium** [comment]
Note that rust uses jemalloc and knows a lot about lifetimes. This is something you could discuss specifically with/for them.

**Comment by thestinger** [comment]
@glandium: Rust's lifetimes aren't relevant to this. That's a type-checking feature for preventing dangling lightweight references. The feature doesn't provide *any* additional information about the lifetimes of dynamic allocations. It has no runtime impact at all.

**Comment by thestinger** [comment]
Lifetimes of dynamic allocations are determined by destructors / move semantics in Rust, which works the same way in Rust as it does in C++. The only significant difference is that Rust prevents use-after-move, but that's not relevant to this. A compiler optimization pass heavily tied to an allocator API could potentially pass along some information from analysis of object lifetimes. It wouldn't be able to distinguish the very long-lived allocations from nearly everything else though. It would be able to identify cases where allocations don't live past a scope, but that's not a clear indication that they're short-lived outside of trivial cases. It also wouldn't get more information from Rust than it could from C++.

**Comment by thestinger** [comment]
An application can already use jemalloc's extended arenas if it wants to compartmentalize the allocations. I don't really think there's anything else an application / compiler *should* try to pass along to jemalloc. It *might* be useful to have the application and any libraries it's using mark anything that's not going to be freed until exit, but trying to deal with any other lifetime tier is seems way out-of-scope of what a general purpose allocator can do.

It would be useful to have a compiler optimization pass merging all dynamic allocations with the same lifetime, but that's allocation-agnostic.

**Comment by glandium** [comment]
My point is, rust is already using jemalloc specific APIs, not the generic malloc API, and it knows a lot more *at compile time* than C++ does, and there might be room for cooperation in that space.

**Comment by thestinger** [comment]
It doesn't know any more at compile-time about dynamic allocation lifetimes. Overall, the only extra knowledge it has is that some allocations are always local to a thread and I'm not sure there's any way for jemalloc to take advantage of that (very high external fragmentation costs rule out doing something like thread-specific arenas with no locking).

**Comment by jasone** [comment]
#325 typically reduces purging activity, but there remains work to do here.

**Comment by jasone** [comment]
See #473 for additional context.

**Comment by jasone** [comment]
I'm planning to give this a shot for both 4.4.0 and 5.0.0 despite the implementation requirements being somewhat different.  If the coding gets too harry to justify the duplicate effort I may punt it back to 5.0.0.

**Comment by madscientist** [comment]
Just to note about this issue: we have a patch we apply locally which simply always sets MADV_NOHUGEPAGE.  No doubt this is sub-optimal for some people but it works pretty well for us, in our environment.  We also require our users to always set transparent/hugepage to either "madvise" or "never", if it's set to "always" we won't start.  Without this we have big problems with not being able to release memory and getting OOM.  I'm sure you can't use it as-is, this is more just a note about some real-world uses.

[pages.diff](https://github.com/jemalloc/jemalloc/files/593204/pages.diff.txt)

**Comment by jasone** [comment]
See #524 for an example of bad THP interactions.

**Comment by gnzlbg** [comment]
Is this still a problem in jemalloc 5? https://bugs.ruby-lang.org/issues/14718#note-89

**Comment by davidtgoldblatt** [comment]
I think it certainly matters less, now that we don't have the pathology discussed.

We also have the option of MALLOC_CONF="thp:never". I'm not sure I think it's our place to disable functionality that the user has set at an OS-level, unless they opt-in explicitly.
