### ISSUE TITLE
High page faults in jemalloc compared to tcmalloc when replacing JVM allocator

### ISSUE THREAD

**Issue by islamismailov** [jemalloc/jemalloc#2438]
After we saw an incredibly high resident memory usage with the default allocator on our busy Java application I started experimenting with different custom allocators for JVM. We use Azul JDK-17 with `-XX:+AlwaysPreTouch` and `-XX:+UseTransparentHugePages` enabled. We set -Xmx and -Xms to 80% of containers RAM right at the start of the application.

Without the `-XX:+UseTransparentHugePages` option, page fault rate is even higher.

I have noticed much higher minor page fault rate in jemalloc compared to tcmalloc (think yellow):

<img width="1501" alt="Page Faults" src="https://github.com/jemalloc/jemalloc/assets/573719/354d765e-734a-4258-be28-c70785a12b4c">

Memory usage seems to fluctuate compared to host with tcmalloc (yellow):

<img width="1505" alt="Memory Usage" src="https://github.com/jemalloc/jemalloc/assets/573719/13d3e07f-c9e0-43e6-a20b-dad6082e9bfe">

I was wondering about your experience changing allocator on JVM apps, and if there are any knobs I could use to reduce page fault rate.

I can capture and attach `malloc_stats` if necessary.

**Comment by islamismailov** [comment]
Here are the stats from one of the worker nodes with jemalloc:

[jemalloc_stats.txt](https://github.com/jemalloc/jemalloc/files/11467052/jemalloc_stats.txt)

**Comment by islamismailov** [comment]
@Svetlitski @interwq could you provide some insight here?

**Comment by interwq** [comment]
@islamismailov there are a lot of `madvise` happening (see the `decaying` section in stats), which directly correlates to soft page faults. You can tune the `dirty_decay_ms` to make it less aggressive at returning pages back to kernel. See http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms

**Comment by interwq** [comment]
Closing but feel free to ask if any questions.
