### ISSUE TITLE
What assets to copy from a docker multi-stage build?

### ISSUE THREAD

**Issue by deostroll** [jemalloc/jemalloc#2444]
Trying to get the jemalloc libraries into a docker image - which is minimal. It doesn't have necessary tools to build jemalloc. 

There is another image which has the necessary build tools. So we plan to use this image as base to build jemalloc from source, and, copy necessary assets from there to the target image.

Q1. Will this work?
Q2. Is it ok to only copy /usr/local/lib/libjemalloc.so from the multi-stage build to the target image? Or are there any other assets/artifacts required for proper functioning?

**Comment by interwq** [comment]
If you need and enable the heap profiling feature, you may need to include your choice of the stack unwinder (e.g. we recommend `libunwind`). But if it's not required, then usually jemalloc itself would be sufficient (assuming the common deps like pthreads are available).
