### ISSUE TITLE
Profiling latency spikes when using 5.3.0

### ISSUE THREAD

**Issue by bottiger1** [jemalloc/jemalloc#2458]
When running with "prof:true,prof_active:false" in /etc/malloc.conf and jemalloc 5.3.0, not even turning profiling on with mallctl, there will be lag spikes every 15-30 seconds lasting about half a second. The application does a soft reset with mass allocation/deallocation every 30 minutes, and this takes longer and longer as the day goes by, until it triggers a crash in uvloop+curl code where there is null pointer that should never occur (it never did in the past 10 years with jemalloc 3.4.1 with no profiling compiled).

I cannot figure out the cause with perf. I am thinking it is some kind of deadlock because I don't see 100% cpu usage when the spikes occur but that might be because it is too fast.

This issue goes away when I downgrade to 4.5.0.

**Runtime environment**
Ubuntu 22.04 64bit, running in 32 bit mode.
./configure CC="gcc -m32" CXX="g++ -m32" --enable-prof --enable-prof-libunwind --with-static-libunwind=/usr/lib/i386-linux-gnu/libunwind.a

**Application**
srcds_linux, Team Fortress 2 server.

**Comment by interwq** [comment]
If you can share some malloc_stats after the issue happened, either by calling malloc_stats_print explicitly or using the [stats_interval option](http://jemalloc.net/jemalloc.3.html#opt.stats_interval) , I can take a look.

**Comment by Thordin** [comment]
I'm assuming you'd like one before and after the lag burst happened?

Unfortunately this issue causes users to leave and rebooting to change version of jemalloc will also cause a mass drop in users so I will probably not attempt to try this again, at least not anytime soon.

**Comment by bottiger1** [comment]
Ok I will keep that in mind if I decide to attempt it again, but I am not sure sure I will do it as it is hard on our users to have this problem active and rebooting the server to change jemalloc versions.
