### ISSUE TITLE
Missing function prototype in test hooks

### ISSUE THREAD

**Issue by rillig** [jemalloc/jemalloc#2468]
https://github.com/jemalloc/jemalloc/blob/d1313313101f9df127bba08bf8fd90a849bf3b87/include/jemalloc/internal/test_hooks.h#L4

This line and the line below define a function pointer with a missing prototype. In these lines, `()` should be replaced with `(void)`.

There may be other places in the code with the same problem. NetBSD compiles the code using GCC's `-Wstrict-prototypes` option to detect these.

**Comment by interwq** [comment]
Thanks @rillig. #2473 will fix this.
