### ISSUE TITLE
High memory consumption in a networking application doing a lot of memory allocations when `dirty_decay_ms` > `0` (jemalloc does not seem to return memory back to the OS on fast enough rate)

### ISSUE THREAD

**Issue by arbv** [jemalloc/jemalloc#2483]
(Initially posted on the [project's Gitter](https://matrix.to/#/!KPsXPiasJyvHrZLabl:gitter.im/$M8HqQXdMtf9iGAaQJRB-nNHJViHXPkERKC5DJrKWXaI?via=gitter.im&via=matrix.freyachat.eu), but we have been asked to create an issue)

Hi!

I think that we need some recommendations from jemalloc developers.

We have experienced high memory consumption in an application. It is a networking application which, during testing, needs to process many small messages (think of 300 000) in a very short time. The application allocates a buffer for each message, and the messages are small (think of 50 bytes). We allocate a large buffer (64K) and then resize the buffer according to the message size.

It is worth noting that we are using jemalloc with the default configuration: we do not try to tune jemalloc in runtime.

The application could consume multiple gigabytes of memory in 10 iterations of the test in a loop on a system with enough memory. An interesting thing happens when containers are involved: when the physical memory limit is not specified, the application could get killed (OOMed) due to high memory usage (as it can run alongside other containers, which also require memory). With the memory limit specified for a container (e.g. `systemd-run -p MemoryMax=1073741824 ...`) application runs fine. That is, as if when jemalloc "knows" its limits, it behaves better. The buffer resizing step has been added recently, but it was not sufficient to mitigate the problem described. It improved things from the jemalloc (jeprof) perspective, though. But memory is not being given back to the OS quickly enough, it seems.

To better understand what is going on, we tried to tune jemalloc to see if any parameter can help with this and to pinpoint the problem. It turned out that when we set `dirty_decay_ms` to `0` (effectively disabling dirty page purging and trying to return memory back to the kernel ASAP), the application did not crash and did not consume a lot of memory. Also, we have experimented with setting `dirty_decay_ms` to smaller values (up to 1ms) + enabling background threads, but memory usage was higher then with `dirty_decay_ms` set to `0`. For example, when set `0`, the application's memory consumption would peak at around 512MB, while with `dirty_decay_ms` set to `1`, it could be over 1GB.

Of course, we are aware that disabling dirty page management can have hard-to-predict performance implications. Also, we would like to keep jemalloc configurable by our users (by means of `MALLOC_CONF`) and not change the memory manager configuration in runtime unnecessarily. At the same time, considering that the application, when run within the container, can coexist with other containers, the current behaviour could have security implications - the application could allocate too much memory and get OOMed.

Do you have any recommendations on how to approach the problem?

**Comment by interwq** [comment]
> With the memory limit specified for a container (e.g. systemd-run -p MemoryMax=1073741824 ...) application runs fine

That sounds strange. Any chance the container also limits the # of cores available along with the memory? If so, that would affect the default # of arenas that jemalloc will use (4x available # of cores), which affects CPU / memory usage.

In order to verify which part is contributing to the OOM, getting `malloc_stats` (e.g. by calling `malloc_stats_print()`, or through [MALLOC_CONF stats_interval](http://jemalloc.net/jemalloc.3.html#opt.stats_interval) under high memory usage should help.

Based on the info, here's what I think the most reasonable approach:
1) if you know the large 64K allocations are the main contributor here, when initializing your lib, [creating a manual arena](http://jemalloc.net/jemalloc.3.html#arenas.create), and route the allocations explicitly to that arena using `mallocx` should help improve purging behavior (limit the peak, plus improved reuse rate among threads). I suspect this change alone should make the dirty page usage alright. If not, try next --
2) you can also change the purge setting for the manually created arena: http://jemalloc.net/jemalloc.3.html#arena.i.dirty_decay_ms
This won't affect other parts of the binary, since the manual arenas will only be used by your workload.
Maybe try a lowered dirty decay first, and if you strongly prefer memory usage over CPU / latency etc, set it to 0 for that specific arena.
3) One other change you can try (which is complimentary to the above), is if / when your threads know that they will go be sleeping for a while and don't expect memory reuse in the near future, an explicit mallctl to purge will help make sure the cached pages don't stay around: https://jemalloc.net/jemalloc.3.html#arena.i.purge

**Comment by arbv** [comment]
@interwq Thank you for the provided information! Your suggestion regarding providing a separate memory arena specifically for these large buffer allocations looks reasonable.

Regarding limiting the number of cores - no, I do not think that we are doing anything like that. Besides, the problem of high memory consumption is very well pronounced in the cases when the containers are not at play, too (e.g. when I run the test locally on my machine). When multiple parallel container jobs without memory limits are involved, the application can get OOMed.

I am attaching an excerpt from the application log with jemalloc statistic logging enabled (`MALLOC_CONF="stats_print:true,stats_interval:536870912"`). The excerpt is towards the end of the test when memory consumption should be around its peak. Maybe it will give you a bit more clues about what could be going on.

[jemalloc-statistics.txt](https://github.com/jemalloc/jemalloc/files/12080055/jemalloc-statistics.txt)

**Comment by everschen** [comment]
opt.narenas: 32, it could be that the too much arena numer cause much more memory, you can have a try to control arena number use http://jemalloc.net/jemalloc.3.html#opt.narenas

however your cpu number is 8, it is not that big, not sure if it's the root cause of your case or not.

**Comment by arbv** [comment]
Thank you for your suggestions, and sorry for not getting back to you sooner.

I have experimented using your suggestions.

Firstly, the [suggestion of using a dedicated arena specifically for allocating message buffers](https://github.com/jemalloc/jemalloc/issues/2483#issuecomment-1639019699) works and does not seem to require from us additional tuning of the arena parameters. Just like @interwq said.

Secondly, [the suggestion by @everschen](https://github.com/jemalloc/jemalloc/issues/2483#issuecomment-1652801818) to test the application with different (= smaller) numbers of generic arenas has shown that, indeed, the number of arenas is definitely at play here. The more arenas there are, the higher the chance for the application to exhibit high memory consumption behaviour. In particular, on my 8-core machine, as soon as I set the number of automatic arenas (opt.narenas) to 6 and more, the application starts consuming memory in amounts similar to these when the number of arenas is not altered.

I have also tried to allocate an arena for the message buffers on a per-worker thread basis (with the number of workers being equal to the number of CPUs). I got results very similar to not using any dedicated arenas at all: the consumption was lower than with no changes, but still higher than I would expect and definitely higher compared to the case when there is only one explicitly dedicated arena. That is, it is absolutely clear that the number of arenas is at play in this case, too. Setting the dirty_decay_ms to 0 on these arenas does solve the problem.

So, I am happy to see that using only one arena for the buffers works well, but I am getting a bit concerned if using only one arena will not significantly impact performance negatively when multiple worker threads are involved on large multicore systems, as I am not sure how access to memory arenas is synchronised. Would it not be better to use per-worker explicit arenas (e. g. with dirty_decay_ms set to 0) rather than use only one arena? Could you tell, please, how locking on arenas is done?

I would be very interested to hear your thoughts on the above. Also, if possible, I would really appreciate it if you could give us some insights/hypotheses explaining (on a very high level) what is going on. I seems that knowing the inner details of jemalloc is necessary to understand the origins of the problem.

Thank you for the help! We appreciate that a lot.

**Comment by everschen** [comment]
the issue I was met before is, the machine has 96 cpus, and there's many thread were created, just as you said per-wroker thread, what was observed is, for each thread if the arena numner is not reach 96*4, new arena would be created, it will cost about 2.8M memorey for each new arena, for some other machine with less cpu, it don't need to create new arena, the memory cost is about 200K, and since the default freebsd memory threshold is 1G, it will cause the machine with 96 cpus OOM for my case.

so come to your case, since your cpus number is 8, not big, if you don't care for the memory very much, maybe suggestion from @interwq dedicated arena is best solution for you. only if you care for the memory space very much, maybe you can consider about the arena number.

**Comment by arbv** [comment]
@everschen It should be noted that this 8-core machine is nothing more than my development machine - it is not the target for this software. Manycore systems with tens of CPUs and good networking hardware is exactly the target for our software deployment.

**Comment by arbv** [comment]
@everschen Oh, and thank you for the provided information, that puts things into perspective, as we seem to have very similar needs.

**Comment by everschen** [comment]
ok, got it. if your target machine is very strong, as you know usually the machine with more cpus also have more physical memory, then another option could be why not increase the memory limitation? I don't know your threshould now, is it 1G also?

**Comment by arbv** [comment]
@everschen I do not think that we have hard limitations (the application is a cross-platform one). I would say that it is up to our users to configure the OS properly in accordance with their hardware.

**Comment by arbv** [comment]
@everschen Our main problem that the application can consume too much memory on smaller systems, too, and our users expect it to scale properly in accordance to their hardware.

**Comment by everschen** [comment]
yes, it make sences especially on small system, we need care for the memory space much more than big one, and good luck.

**Comment by arbv** [comment]
@interwq Regarding [this my message](https://github.com/jemalloc/jemalloc/issues/2483#issuecomment-1677580569): should I create a new issue for asking this question or, perhaps, it could be answered in this thread? I would be appreciated for your thoughts on this one.

**Comment by interwq** [comment]
@arbv: sorry for the delay. Using only 1 arena can indeed cause contention at the arena level -- regarding the locking, it's fine grained and organized this way in the arena:
bins (contain partially used pages / slabs): each size class of bin is under its own lock
dirty page cache (when bins run out of local slabs, they reach here): the page cache is under a single lock

In case I didn't mention, always do `MALLOCX_TCACHE_NONE` to bypass tcache, when alloc or free into a specific arena is required.

`malloc_stats` has information about locking, https://jemalloc.net/jemalloc.3.html#stats.mutexes.ctl

In general the above two lock types are the most contended.

Creating 1 arena per worker thread is a good way to reduce contention. We have many workloads doing that. Keep in mind though, it does not completely avoid locking if there's any producer-consumer pattern, i.e. alloc on one thread but free on another.

Higher arena count can increase fragmentation though; you can balance contention and fragmentation with the arena count, e.g. every N thread assigning to 1 dedicated arena.

**Comment by arbv** [comment]
@interwq Thank you for the provided information! Considering that we are going to use it mostly for allocating 64Kb chunks of data and there is a lock per each size class, with only one arena we will have scalability issues as too many threads are going to use one lock. Thanks for mentioning `MALLOCX_TCACHE_NONE` as using this flag is not obvious at all to me.

> Keep in mind though, it does not completely avoid locking if there's any producer-consumer pattern, i.e. alloc on one thread but free on another.

In our case it is not going to be the case as the arenas will be bound to specific threads.

So, considering what you have written, it seems that a dedicated arena per worker thread with a disable dirty page caching is a good way to go forward.

**Comment by arbv** [comment]
Oh, I did not close the issue despite it being resolved. Closing it now. Thank you all for the help!
