### ISSUE TITLE
[5.2.0] jemalloc_bg_thd received SIGSEGV in function background_thread_sleep, errno = 6

### ISSUE THREAD

**Issue by LoTmLumian** [jemalloc/jemalloc#2491]
Jemalloc VERSION: 5.2.0
My MALLOC_CONF: `--with-malloc-conf=background_thread:true`
Running in VM,
Arch: x86 (64bits)
CPU: 1U
Memory: 1G
_OS: EulerOS 2.9_ 

GDB information:
![image](https://github.com/jemalloc/jemalloc/assets/130299336/8f36bee8-27d0-416c-b03f-337a5dcefbaa)

File Line:
https://github.com/jemalloc/jemalloc/blob/5.2.0/src/background_thread.c#L261
```
if (config_stats) {
=>	gettimeofday(&tv, NULL);
```

GDB disassembly:
![image](https://github.com/jemalloc/jemalloc/assets/130299336/33a24ff9-1681-4e54-a718-639e16bdc893)
BTW, context of rax is 0.

I disassembled background_thread_sleep() and gettimeofday() in other machine with greater memory (16G), I never saw `add %al, (%rax)`. Besides, this segfault never occurs in other machine.

dmesg info:
![image](https://github.com/jemalloc/jemalloc/assets/130299336/67afee6d-b9bc-45b6-a478-81f8d4ec7a4c)

Probability: Very high on virtual machines _with small memory, in EulerOS 2.9._
If there are segfaults, they always occur at the beginning of process running.

**Comment by interwq** [comment]
The assembly looks to be the result of some heap or stack corruption. Does it happen w/o bg thds? Try building jemalloc with `--enable-debug` which should help you catching issues earlier.

**Comment by LoTmLumian** [comment]
> 

Thx. When the crash occurs, the main thread is always running after just mremap() or unmap() LOAD segment. (it is remapping all shared libs' text and data sections) I think it may corrupt some libs' text section.
At last, I enabled jemalloc bg_thd after doing all remap jobs. Never crash then.
