### ISSUE TITLE
System requirements for jemalloc

### ISSUE THREAD

**Issue by lgacnik** [jemalloc/jemalloc#2498]
The following question is of informative nature.

I'm looking for an effective, preferably faster, and less time-deterministic alternative to `malloc()` memory allocator. I'm targetting use in C++ where code runs on a _freestanding_ (no underlying operating system) implementation on a memory constrained device (microcontroller device with up to 1Mbyte of RAM/FLASH and sub-gigahertz frequency of CPU operation speed).  Additionally I would be using such a memory allocation mechanism in combination with a pre-allocated (statically, at compile time, fixed-size container) memory and not dynamic (on heap) memory.

Therefore I'm asking whether `jemalloc` is a suitable component for integration in such a system?

**Comment by interwq** [comment]
> microcontroller device with up to 1Mbyte of RAM

This might not be the best use case, considering the text size (which can be a deal breaker alone) and metadata usage like thread-locals are often on the less-conservative side.

You can certainly experiment, but perhaps staring with a memory-saving setting, e.g. set `char *malloc_conf = narenas:1,tcache:false`.

Closing but feel free to ask questions.
