### ISSUE TITLE
Print malloc conf strings when they can't be parsed

### ISSUE THREAD

**Issue by mdcallag** [jemalloc/jemalloc#2502]
The existing code can print key:value pairs when it doesn't recognize a key. But it doesn't print the full string when it is unable to even parse a key.

When I [reach here](https://github.com/jemalloc/jemalloc/blob/b01d49664651f239fdf76774cb6de05ed7e63f4a/src/jemalloc.c#L907) all I get is ...
```
<jemalloc>: Malformed conf string
<jemalloc>: Abort (abort_conf:true) on invalid conf value (see above).
```

The problem in this case is that it was trying to parse "narenas:1" rather than narenas:1 -- yes for some reason I don't understand those quotes made it into the string that malloc_conf_init_helper and malloc_conf_next were parsing.

I was using /bin/bash. I am not asking you to debug this for me, just give me the value of the full malloc conf string when this error occurs.

This failed for me and gets the error message above.
MALLOC_CONF=“narenas:1” bin/mysqld

This was fine:
MALLOC_CONF=narenas:1 bin/mysqld

**Comment by interwq** [comment]
Will submit a PR soon.
