### ISSUE TITLE
`--enable-prof-libunwind` not work

### ISSUE THREAD

**Issue by xinyiZzz** [jemalloc/jemalloc#2504]
I compiled `jemalloc` `5.3.0` and `5.2.1` in the following way, `--enable-prof-libunwind` didn't work.
```
cflags='-O3 -fPIC -g'
CFLAGS="${cflags}" ../configure --prefix="${TP_INSTALL_DIR}" --with-jemalloc-prefix=je --enable-prof --enable-prof-libunwind --disable-prof-libgcc --disable-prof-gcc
```
![image](https://github.com/jemalloc/jemalloc/assets/13197424/1b38a85f-b68a-4ba8-9b22-8cc0f590100c)

As expected, run `export JEMALLOC_CONF="prof:true"`, report error `<jemalloc>: Invalid conf pair: prof:true`.

Has anyone encountered it, thanks

**Comment by xinyiZzz** [comment]
Specifying `--with-static-libunwind` also does not work, `libunwind` is `gnu libunwind-1.7.2`, `gnu libunwind-1.6.2` also not
![image](https://github.com/jemalloc/jemalloc/assets/13197424/c6326054-b5e1-41d3-90ae-e3b2527c32a8)

**Comment by xinyiZzz** [comment]
```
* `--enable-prof`

    Enable heap profiling and leak detection functionality.  See the "opt.prof"
    option documentation for usage details.  When enabled, there are several
    approaches to backtracing, and the configure script chooses the first one
    in the following list that appears to function correctly:
```

It seems that libunwind is not runnable at compile time? how can i confirm

**Comment by Svetlitski** [comment]
Do you have the _development_ version of `libunwind` installed with the headers and everything (via `sudo apt-get install libunwind-dev` on Ubutnu-likes or `sudo dnf install libunwind-devel` on CentOS/RHEL/Fedora)?

**Comment by xinyiZzz** [comment]
Thanks for reporting this @Svetlitski , `libunwind` is compiled by myself (from: https://github.com/libunwind/libunwind/releases)
Can Jemalloc prof link `libunwind` compiled separately?

**Comment by guangli-dai** [comment]
You can link `libunwind` statically with `--with-static-libunwind=<libunwind.a>` when configuring.
