### ISSUE TITLE
Compile error on the Mac, "./autogen.sh:line 5: autoconf: command not found".

### ISSUE THREAD

**Issue by shenwei888** [jemalloc/jemalloc#2512]
**Introduction：**
An error is reported when jemalloc is compiled in the Mac environment. The error is "./autogen.sh:line 5: autoconf: command not found".

**Compilation environment：**
MacOS CPU x86

**Compiling Commands：**
1. ./autogen.sh
2. make
3. make install

**Error Details：**
![image](https://github.com/jemalloc/jemalloc/assets/49518850/ffc966ae-d4c6-4dac-a8c0-f45009d3e726)

**Question：**
1. How do you solve this compilation problem?（Can I run the **"brew install autoconf automake libtool"** command to solve the problem?）
2. Is the same compilation method for both Linux and Mac environments?

**Comment by Svetlitski** [comment]
> How do you solve this compilation problem?（Can I run the "brew install autoconf automake libtool" command to solve the problem?

Yes, something of this nature should solve your issue (not sure what the actual package names are).
