### ISSUE TITLE
which jemalloc-version use libc.so  less than 2.27?

### ISSUE THREAD

**Issue by xuandu** [jemalloc/jemalloc#2513]
hello:
I recently encountered a problem where the memory did not decrease after deconstruction on ARM64 Ubuntu18；so i want to use jemalloc ,may be the memory is Memory Fragmentation；so i download it from arclinux  jemalloc-1 5.3.0-2-aarch64.pkg.tar.xz,
but when i  compile the jemalloc to my exe ,it break error ,need glibc 2.35;but my computer is arm ubuntu 18.the latest libc.so6 is2.27，so the master code can use by arc64?and which version use glibc less than 2.27?

**Comment by interwq** [comment]
We don't maintain the packages. This isn't a question for jemalloc devs.
