### ISSUE TITLE
windows configure --enable-cxx is't effective

### ISSUE THREAD

**Issue by SinoGao** [jemalloc/jemalloc#2515]
![企业微信截图_16916519886627](https://github.com/jemalloc/jemalloc/assets/10723413/81512326-2821-45ff-a64b-791e02a9203a)

**Comment by everschen** [comment]
it works for me, maybe your env cxx has not been installed.

CONFIG             : --enable-autogen --enable-cxx
CC                 : gcc
CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -Wimplicit-fallthrough -Wdeprecated-declarations -O3 -funroll-loops
SPECIFIED_CFLAGS   :
EXTRA_CFLAGS       :
CPPFLAGS           : -D_REENTRANT
CXX                : g++ -std=c++17
CONFIGURE_CXXFLAGS : -Wall -Wextra -g3 -Wimplicit-fallthrough -Wdeprecated-declarations -O3

**Comment by everschen** [comment]
from below code, it looks it is checking je_cv_libstdcxx even if you enable-cxx explictly.

`if ac_fn_c_try_link "$LINENO"
then :
  je_cv_libstdcxx=yes
else $as_nop
  je_cv_libstdcxx=no
fi
rm -f core conftest.err conftest.$ac_objext conftest.beam \
    conftest$ac_exeext conftest.$ac_ext
fi
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $je_cv_libstdcxx" >&5
printf "%s\n" "$je_cv_libstdcxx" >&6; }

    if test "x${je_cv_libstdcxx}" = "xno" ; then
      LIBS="${SAVED_LIBS}"
    fi
  else
    enable_cxx="0"
  fi
fi
if test "x$enable_cxx" = "x1"; then

printf "%s\n" "#define JEMALLOC_ENABLE_CXX  " >>confdefs.h

fi`
