### ISSUE TITLE
Error linking jemalloc.so to binary

### ISSUE THREAD

**Issue by shenwei888** [jemalloc/jemalloc#2518]
**Introduction：**
I fixed the error "cannot allocate memory in static TLS block" by adding "--disable-initial-exec-tls". But when I finally ran, I encountered this problem again, and I don't know how to solve it.
I compiled a jemalloc.so using the following compilation command. But when I used target_link_libraries to link "jemalloc.so" to "_c_dataengine", the following error occurred during import.
![image](https://github.com/jemalloc/jemalloc/assets/49518850/192e9dd1-d345-4763-b6ed-ac94e62f0915)

**Compilation environment：**
Linux x86

**Compiling Commands：**

./autogen.sh
./configure --disable-initial-exec-tls
make
make install

**Question：**

- How can we solve this problem?
- Note that I do not want to use the **export LD_PRELOAD** mode, but want to integrate it into the project through CMake.

**Comment by interwq** [comment]
The `free(): invalid pointer` msg isn't from jemalloc. You might be passing a pointer from one allocator to another allocator.

See this thread for debugging an example https://github.com/jemalloc/jemalloc/issues/2500#issuecomment-1663806512
