### ISSUE TITLE
any idea why run_test_0 failed to run? and any method to debug on this error? thanks

### ISSUE THREAD

**Issue by everschen** [jemalloc/jemalloc#2521]
gcc  -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -Wdeprecated-declarations -O3 -funroll-loops -Werror -fno-builtin -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -I../../include -DJEMALLOC_UNIT_TEST -I../../test/include -Itest/include -o test/unit/size_classes.o ../../test/unit/size_classes.c
In file included from ../../include/jemalloc/internal/cache_bin.h:8,
                 from ../../include/jemalloc/internal/tcache_structs.h:5,
                 from ../../include/jemalloc/internal/tsd_internals.h:16,
                 from ../../include/jemalloc/internal/tsd_tls.h:7,
                 from ../../include/jemalloc/internal/tsd.h:13,
                 from ../../include/jemalloc/internal/ckh.h:5,
                 from ../../include/jemalloc/internal/prof_structs.h:5,
                 from ../../include/jemalloc/internal/jemalloc_internal_includes.h:51,
                 from ../../test/include/test/jemalloc_test.h:47,
                 from ../../test/unit/size_classes.c:1:
In function ‘sz_index2size_lookup_impl’,
    inlined from ‘sz_index2size_lookup’ at ../../include/jemalloc/internal/sz.h:244:15,
    inlined from ‘sz_index2size’ at ../../include/jemalloc/internal/sz.h:252:9,
    inlined from ‘test_size_classes’ at ../../test/unit/size_classes.c:42:3:
../../include/jemalloc/internal/sz.h:239:33: error: array subscript 232 is above array bounds of ‘size_t[232]’ {aka ‘long unsigned int[232]’} [-Werror=array-bounds]
  239 |         return sz_index2size_tab[index];
In file included from ../../test/include/test/jemalloc_test.h:46:
../../include/jemalloc/internal/sz.h: In function ‘test_size_classes’:
include/jemalloc/internal/jemalloc_preamble.h:20:25: note: while referencing ‘jet_sz_index2size_tab’
   20 | #  define JEMALLOC_N(n) jet_##n
      |                         ^~~~
include/jemalloc/internal/private_namespace_jet.h:639:27: note: in expansion of macro ‘JEMALLOC_N’
  639 | #define sz_index2size_tab JEMALLOC_N(sz_index2size_tab)
      |                           ^~~~~~~~~~
../../include/jemalloc/internal/sz.h:41:15: note: in expansion of macro ‘sz_index2size_tab’
   41 | extern size_t sz_index2size_tab[SC_NSIZES];
      |               ^~~~~~~~~~~~~~~~~
In function ‘sz_index2size_lookup_impl’,
    inlined from ‘sz_index2size_lookup’ at ../../include/jemalloc/internal/sz.h:244:15,
    inlined from ‘sz_index2size’ at ../../include/jemalloc/internal/sz.h:252:9,
    inlined from ‘test_size_classes’ at ../../test/unit/size_classes.c:47:3:
../../include/jemalloc/internal/sz.h:239:33: error: array subscript 232 is above array bounds of ‘size_t[232]’ {aka ‘long unsigned int[232]’} [-Werror=array-bounds]
  239 |         return sz_index2size_tab[index];
../../include/jemalloc/internal/sz.h: In function ‘test_size_classes’:
include/jemalloc/internal/jemalloc_preamble.h:20:25: note: while referencing ‘jet_sz_index2size_tab’
   20 | #  define JEMALLOC_N(n) jet_##n
      |                         ^~~~
include/jemalloc/internal/private_namespace_jet.h:639:27: note: in expansion of macro ‘JEMALLOC_N’
  639 | #define sz_index2size_tab JEMALLOC_N(sz_index2size_tab)
      |                           ^~~~~~~~~~
../../include/jemalloc/internal/sz.h:41:15: note: in expansion of macro ‘sz_index2size_tab’
   41 | extern size_t sz_index2size_tab[SC_NSIZES];
      |               ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

**Comment by interwq** [comment]
> ../../include/jemalloc/internal/sz.h:239:33: error: array subscript 232 is above array bounds of ‘size_t[232]’ {aka ‘long unsigned int[232]’} [-Werror=array-bounds]

This looks the configure was incorrect. What's the output from autogen / configure?

**Comment by everschen** [comment]
below is configure output:

===============================================================================
jemalloc version   : 5.3.0-124-gda66aa391f853ccf2300845b3873cc8f1cf48f2d
library revision   : 2

CONFIG             :
CC                 : gcc
CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -Wdeprecated-declarations -O3 -funroll-loops
SPECIFIED_CFLAGS   :
EXTRA_CFLAGS       :
CPPFLAGS           : -D_GNU_SOURCE -D_REENTRANT
CXX                : g++ -std=c++17
CONFIGURE_CXXFLAGS : -Wall -Wextra -g3 -fvisibility=hidden -Wimplicit-fallthrough -Wdeprecated-declarations -O3
SPECIFIED_CXXFLAGS :
EXTRA_CXXFLAGS     :
LDFLAGS            :
EXTRA_LDFLAGS      :
DSO_LDFLAGS        : -shared -Wl,-soname,$(@F)
LIBS               : -lm -lstdc++ -pthread
RPATH_EXTRA        :

XSLTPROC           : false
XSLROOT            :

PREFIX             : /usr/local
BINDIR             : /usr/local/bin
DATADIR            : /usr/local/share
INCLUDEDIR         : /usr/local/include
LIBDIR             : /usr/local/lib
MANDIR             : /usr/local/share/man

srcroot            :
abs_srcroot        : /home/evers/jemalloc/
objroot            :
abs_objroot        : /home/evers/jemalloc/

JEMALLOC_PREFIX    :
JEMALLOC_PRIVATE_NAMESPACE
                   : je_
install_suffix     :
malloc_conf        :
documentation      : 1
shared libs        : 1
static libs        : 1
autogen            : 0
debug              : 0
stats              : 1
experimental_smallocx : 0
prof               : 0
prof-libunwind     : 0
prof-libgcc        : 0
prof-gcc           : 0
fill               : 1
utrace             : 0
xmalloc            : 0
log                : 0
lazy_lock          : 0
cache-oblivious    : 1
pageid             : 0
cxx                : 1
dss                : 1
===============================================================================

**Comment by everschen** [comment]
my env:

evers@xiaomi:~/jemalloc$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
evers@xiaomi:~/jemalloc$ uname -a
Linux xiaomi 6.2.0-27-generic #28-Ubuntu SMP PREEMPT_DYNAMIC Wed Jul 12 22:39:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
evers@xiaomi:~/jemalloc$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 12.3.0-1ubuntu1~23.04' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-12-DAPbBt/gcc-12-12.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-12-DAPbBt/gcc-12-12.3.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~23.04)
evers@xiaomi:~/jemalloc$

**Comment by everschen** [comment]
whole test log for trouble shooting.
[run_test.log](https://github.com/jemalloc/jemalloc/files/12378629/run_test.log)

**Comment by everschen** [comment]
it can pass on gcc 7.5.0

evers@MiWiFi-R3600-srv:~/MyGithub/jemalloc$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
evers@MiWiFi-R3600-srv:~/MyGithub/jemalloc$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
evers@MiWiFi-R3600-srv:~/MyGithub/jemalloc$ uname -a
Linux MiWiFi-R3600-srv 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
evers@MiWiFi-R3600-srv:~/MyGithub/jemalloc$

**Comment by everschen** [comment]
so could it be that for gcc 12.3.0 it is more restrict lead to this error?

**Comment by everschen** [comment]
After test related code, it looks more like false warning from gcc 12.3.0, and I also try to use temp variable to save sz_size2index(size_class) inside of for loop, it will avoid this false warning, I will try to provide PR for your reference later.

PR: https://github.com/jemalloc/jemalloc/pull/2524
