### ISSUE TITLE
Wrong core id with RDTSCP

### ISSUE THREAD

**Issue by tobias-fire** [jemalloc/jemalloc#2527]
`jemalloc` has a configuration option `JEMALLOC_HAVE_RDTSCP`. When it is enabled, it uses the `rdtscp` x86 instruction to get the core that a thread is currently running on. 

## Expected behavior:
Using the `rdtscp` instruction should give the same core id as `sched_getcpu()` (excluding unlucky core migrations between evaluating both).

## Actual behavior:
On my machine, the way this instruction is used gives different results than `sched_getcpu()`. 

Here is the relevant code: https://github.com/jemalloc/jemalloc/blob/dev/include/jemalloc/internal/jemalloc_internal_inlines_a.h#L22-L24

## Potential fix:
According to https://hjlebbink.github.io/x86doc/html/RDTSCP.html, `dx` should be replaced by `cx` in `(malloc_cpuid_t)(dx & 0xfff);`. If I change it to `(malloc_cpuid_t)(cx & 0xfff);`, I get the same core ids as with `sched_getcpu()`. 

## Environment:
Intel(R) Core(TM)  i7 10700 CPU, Ubuntu 22.04.3 LTS, Linux Kernel 6.2.0-26-generic

**Comment by interwq** [comment]
Thanks for reporting this @tobias-fire . Fix is in #2529.
