### ISSUE TITLE
[Needhelp] suddently core by pthread using jemalloc

### ISSUE THREAD

**Issue by yiguolei** [jemalloc/jemalloc#2535]
Apache Doris is using jemalloc as default allocator, but sometimes we meet some errors like 

0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/doris/be/src/common/signal_handler.h:420
1# os::Linux::chained_handler(int, siginfo*, void*) in /opt/jdk-11.0.14/lib/server/libjvm.so
2# JVM_handle_linux_signal in /opt/jdk-11.0.14/lib/server/libjvm.so
3# signalHandler(int, siginfo*, void*) in /opt/jdk-11.0.14/lib/server/libjvm.so
4# 0x00007FD5E217A400 in /lib64/libc.so.6
5# je_arena_dalloc_promoted at ../src/arena.c:1604
6# __GI__dl_deallocate_tls in /lib64/ld-linux-x86-64.so.2
7# __free_stacks in /lib64/libpthread.so.0
8# __deallocate_stack in /lib64/libpthread.so.0
9# pthread_join in /lib64/libpthread.so.0
10# std:🧵:join() at ../../../../../libstdc++-v3/src/c++11/thread.cc:114
11# rocksdb::VersionBuilder::Rep::LoadTableHandlers(rocksdb::InternalStats*, int, bool) in /data/doris/doris-be//lib/doris_be
12# rocksdb::VersionSet::Recover(std::vector<rocksdb::ColumnFamilyDescriptor, std::allocatorrocksdb::ColumnFamilyDescriptor > const&, bool) in /data/doris/doris-be//lib/doris_be

OR 

![img_v2_2a523d6c-21a5-4206-8981-5ffc0d0180fg](https://github.com/jemalloc/jemalloc/assets/9208457/8618278d-aa63-4b53-9549-2f5d4438b928)

https://github.com/apache/doris/issues/22816

I find it always happens in pthread_create or pthread_join.
 Does anybody have any ideas about it? Thanks a lot.

**Comment by everschen** [comment]
from the stack, it looks during dalloc:  je_arena_dalloc_promoted 
maybe you can enable debug of jemalloc, and it can usually catch the issue in very early stage.

**Comment by interwq** [comment]
No known issue on jemalloc should cause this. Check for heap corruption at the application level.
