### ISSUE TITLE
Deadlock when two threads are doing realloc and malloc

### ISSUE THREAD

**Issue by LZxiao** [jemalloc/jemalloc#2539]
"Binder:16773_2" sysTid=16838

    #00 pc 0000000000089ccc  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #01 pc 000000000008d968  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #02 pc 00000000000f50b4  /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+216) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #03 pc 0000000000078890  /apex/com.android.runtime/lib64/bionic/libc.so (je_malloc_mutex_lock_slow+188) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #04 pc 0000000000082a5c  /apex/com.android.runtime/lib64/bionic/libc.so (je_tcache_bin_flush_small+1432) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #05 pc 000000000008242c  /apex/com.android.runtime/lib64/bionic/libc.so (je_tcache_event_hard+92) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #06 pc 000000000005ab48  /apex/com.android.runtime/lib64/bionic/libc.so (je_arena_ralloc+1136) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #07 pc 0000000000050c28  /apex/com.android.runtime/lib64/bionic/libc.so (je_realloc+576) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #08 pc 00000000000487a0  /apex/com.android.runtime/lib64/bionic/libc.so (LimitRealloc(void*, unsigned long)+120) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #09 pc 0000000000045f9c  /apex/com.android.runtime/lib64/bionic/libc.so (realloc+160) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #10 pc 000000000005c620  /system/lib64/libbinder.so (android::Parcel::continueWrite(unsigned long)+956) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #11 pc 000000000005dbac  /system/lib64/libbinder.so (android::Parcel::writeInplace(unsigned long)+148) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #12 pc 0000000000060f9c  /system/lib64/libbinder.so (android::Parcel::writeBlob(unsigned long, bool, android::Parcel::WritableBlob*)+528) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #13 pc 0000000000031cc8  /system/lib64/libstagefright_foundation.so (android::MetaDataBase::writeToParcel(android::Parcel&)+492) (BuildId: 83b8142db99cfbce5dead8591d05e78a)
    #14 pc 000000000006af1c  /system/lib64/libmedia.so (android::BnMediaSource::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+872) (BuildId: 645066abe352fb92cb0eb414b803e835)
    #15 pc 0000000000048834  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+232) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #16 pc 0000000000051c10  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1040) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #17 pc 0000000000051750  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #18 pc 0000000000051f90  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+108) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #19 pc 0000000000078f58  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #20 pc 000000000001553c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+320) (BuildId: 6b453123259887cd16e522119154597b)
    #21 pc 0000000000014db0  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+408) (BuildId: 6b453123259887cd16e522119154597b)
    #22 pc 00000000000f42e4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #23 pc 000000000008ec64  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)

"Binder:16773_E" sysTid=12031

    #00 pc 0000000000089ccc  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #01 pc 000000000008d968  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #02 pc 00000000000f50b4  /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+216) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #03 pc 0000000000078890  /apex/com.android.runtime/lib64/bionic/libc.so (je_malloc_mutex_lock_slow+188) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #04 pc 0000000000082a5c  /apex/com.android.runtime/lib64/bionic/libc.so (je_tcache_bin_flush_small+1432) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #05 pc 000000000008242c  /apex/com.android.runtime/lib64/bionic/libc.so (je_tcache_event_hard+92) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #06 pc 000000000004df34  /apex/com.android.runtime/lib64/bionic/libc.so (je_malloc+724) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #07 pc 0000000000048434  /apex/com.android.runtime/lib64/bionic/libc.so (LimitMalloc(unsigned long)+72) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #08 pc 0000000000045ca4  /apex/com.android.runtime/lib64/bionic/libc.so (malloc+76) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #09 pc 000000000004ef54  /system/lib64/libc++.so (operator new(unsigned long)+24) (BuildId: 4eccf98481702c54f932a523b3616bf0)
    #10 pc 0000000000010dec  /system/lib64/libutils.so (android::RefBase::RefBase()+36) (BuildId: 6b453123259887cd16e522119154597b)
    #11 pc 000000000001f8e8  /system/lib64/libstagefright_foundation.so (android::AMessage::AMessage()+16) (BuildId: 83b8142db99cfbce5dead8591d05e78a)
    #12 pc 000000000017141c  /system/lib64/libstagefright.so (android::MediaTrackCUnwrapper::getFormat(android::MetaDataBase&)+56) (BuildId: 77d73d08f9792ca4335e3ab4cf37ddca)
    #13 pc 0000000000180c0c  /system/lib64/libstagefright.so (android::RemoteMediaSource::getFormat()+216) (BuildId: 77d73d08f9792ca4335e3ab4cf37ddca)
    #14 pc 000000000004db34  /system/lib64/libmedia.so (android::registerMediaSource(android::sp<android::IMediaExtractor> const&, android::sp<android::IMediaSource> const&) (.cfi)+820) (BuildId: 645066abe352fb92cb0eb414b803e835)
    #15 pc 000000000004d178  /system/lib64/libmedia.so (android::BnMediaExtractor::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+792) (BuildId: 645066abe352fb92cb0eb414b803e835)
    #16 pc 0000000000048834  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+232) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #17 pc 0000000000051c10  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1040) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #18 pc 0000000000051750  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #19 pc 0000000000051f90  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+108) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #20 pc 0000000000078f58  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24) (BuildId: 758271a8d2f75c6927f097f485f10c72)
    #21 pc 000000000001553c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+320) (BuildId: 6b453123259887cd16e522119154597b)
    #22 pc 0000000000014db0  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+408) (BuildId: 6b453123259887cd16e522119154597b)
    #23 pc 00000000000f42e4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
    #24 pc 000000000008ec64  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)

**Comment by interwq** [comment]
No known issue around these parts. Best guess is heap corruption from the application leading to corrupted allocator internals.
