### ISSUE TITLE
Memory usage can increase during low traffic periods.

### ISSUE THREAD

**Issue by 0x007004** [jemalloc/jemalloc#2541]
My program uses jemalloc, and I have noticed that it increases memory usage during low traffic periods. I have used the parameter “background_thread:true,metadata_thp:auto,dirty_decay_ms:30000,muzzy_decay_ms:30000” , and I can confirm that there is no memory leak in the program.I'm unsure how to troubleshoot this issue. 
![20230917114657048](https://github.com/jemalloc/jemalloc/assets/13299372/21b335c6-49e2-4434-8adc-256a6c4557ef)

**Comment by interwq** [comment]
Try heap profiling during the high memory usage, and compare against the low usage profiles. 
https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling

Doesn't look like the allocator is causing the behavior.
