### ISSUE TITLE
incorrect memory usage

### ISSUE THREAD

**Issue by season27** [jemalloc/jemalloc#2542]
version:
jemalloc-5.2.1
C++11

code:
class Buffer {
public:
  explicit Buffer(uint64_t key);
  ~Buffer();
  Buffer(const Buffer&) = delete;
  Buffer& operator=(const Buffer&) = delete;
  char* page() { return page_; }
  uint64_t key() const { return key_; }
  void set_key(uint64_t key) { key_ = key; }

private:
  uint64_t key_;
  char* page_;
};

Buffer::Buffer(uint64_t key)
{
  int ret = posix_memalign((void **) &page_, 4096, 4096);
  if (ret) {
      assert(0);
  }

  key_ = key;
}

int main()
{
    std::list<std::shared_ptr<Buffer>> buffers;

    for (uint32_t i = 0; i < 4; ++i) {
        for (uint32_t j = 0; j < 8192; ++j) {
            std::shared_ptr<Buffer> bp = std::make_shared<Buffer>(0);
            buffers.push_back(bp);
      }
    }
}

Linux：
the VIRT increase 550MB

jemalloc：
(jeprof) top
Total: 534.3 MB
   494.1  92.5%  92.5%    494.1  92.5% Buffer::Buffer
    16.0   3.0%  95.5%     16.0   3.0% xx::xx
    15.6   2.9%  98.4%     15.6   2.9% __gnu_cxx::new_allocator::allocate (inline)
     5.4   1.0%  99.4%      5.4   1.0% fbuf_aligned_malloc
     2.1   0.4%  99.8%      2.1   0.4% xx::xx
     0.5   0.1%  99.9%      0.5   0.1% std::string::_Rep::_S_create
     0.5   0.1% 100.0%      0.5   0.1% CreateInternal (inline)
     0.0   0.0% 100.0%      4.9   0.9% CacheUtils (inline)

it should be 4 * 8192 * 4KB=128MB. why 500MB?
posix_memalign((void **) &page_, 4096, 4096):jeprof is 494MB, the VIRT is 550MB;
posix_memalign((void **) &page_, 512, 4096):jeprof is 128MB, the VIRT decrease 550MB;
posix_memalign((void **) &page_, 4096, 16384):jeprof is 525MB, the VIRT is 550MB;

**Comment by interwq** [comment]
Try jemalloc 5.3 which has a [profiling biasing fix](https://github.com/jemalloc/jemalloc/pull/1897). It's effect is most noticeable for single size tests like this.
