### ISSUE TITLE
[Needhelp] suddently core by pthread using jemalloc  and Failed assertion: "force_ivsalloc || ret != 0"

### ISSUE THREAD

**Issue by yiguolei** [jemalloc/jemalloc#2559]
related with  issue https://github.com/jemalloc/jemalloc/issues/2535

I add --enable-debug option and it print a more detail info.

start time: Thu Oct 19 17:03:31 CST 2023
INFO: java_cmd /mnt/disk0/env/jdk1.8.0_231//bin/java
INFO: jdk_version 8
<jemalloc>: ../src/jemalloc.c:4086: Failed assertion: "force_ivsalloc || ret != 0"
*** Query id: d88328fafa944966-82c684e265278b16 ***
*** tablet id: 0 ***
*** Aborted at 1697752805 (unix time) try "date -d @1697752805" if you are using GNU date ***
*** Current BE git commitID: 051c020997 ***
*** SIGABRT unknown detail explain (@0x3ec00049d5b) received by PID 302427 (TID 205302 OR 0x7f029992b700) from PID 302427; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /mnt/disk2/liyifan/doris/core/be/src/common/signal_handler.h:417
 1# 0x00007F8020A7F400 in /lib64/libc.so.6
 2# __GI_raise in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# jemalloc_usable_size at /mnt/disk2/liyifan/doris/core/thirdparty/src/jemalloc-5.3.0/doris_build/../src/jemalloc.c:4100
 5# free at /mnt/disk2/liyifan/doris/core/be/src/runtime/memory/jemalloc_hook.cpp:53
 6# __GI__dl_deallocate_tls in /lib64/ld-linux-x86-64.so.2
 7# __free_stacks in /lib64/libpthread.so.0
 8# __deallocate_stack in /lib64/libpthread.so.0
 9# start_thread in /lib64/libpthread.so.0
10# __clone in /lib64/libc.so.6

and I check jemalloc's source code, it is a assert.
![image](https://github.com/jemalloc/jemalloc/assets/9208457/dae47267-4689-4e2c-a8fa-9aed50598926)

@everschen @interwq  Do you know some more details about this assert??

**Comment by interwq** [comment]
As mentioned in the previous thread, this assert is saying "the pointer is not recognized / managed by jemalloc". It's either a corrupted pointer, or the memory being freed was not obtained by jemalloc (e.g. trying to free a stack address).

You will want to follow the pointer being freed, and see where it came from or is it valid at all. If you haven't tried, ASAN is very effective there.
