### ISSUE TITLE
Add -lrt for clock_gettime() if necessary

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#257]
On older Linux systems, ```clock_gettime()``` is in librt rather than libc.  Add a configure test to determine whether explicitly linking against librt is necessary.

**Comment by thestinger** [comment]
It could also just link unconditionally to librt to keep things simple. They moved clock_gettime out of it but it still exists. Using `-Wl,--as-needed` would automatically avoid linking when it's unnecessary but it's only the tests so it doesn't really matter.
