### ISSUE TITLE
Unsupported page size on Apple Silicon

### ISSUE THREAD

**Issue by RossComputerGuy** [jemalloc/jemalloc#2572]
Apple Silicon uses 16k page sizes, when running Telegram from the Flatpak on NixOS with Asahi config + packages I get this error:
```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```
Jemalloc should get the page size info from the kernel and use that.

**Comment by interwq** [comment]
Apple silicon already defaults to 16K page size:
https://github.com/jemalloc/jemalloc/blob/dev/configure.ac#L1807-L1813

It's either an older package before 5.3, or configured with wrong page size explicitly.

jemalloc's page size is a compile time option as some internal optimizations rely on const page size. Higher configured page size is compatible with lower OS page sizes, but not the other way around. Currently there's no plan to switch to runtime detected page sizes.
