### ISSUE TITLE
Huge memory allocation leads to an infinite loop

### ISSUE THREAD

**Issue by kaushalgoa** [jemalloc/jemalloc#2575]
Jemalloc version - 5.3.0
Due to an error condition my program tries to allocate HUGE memory of size = 4294967273 bytes.

The thread is stuck in an infinite loop with below BT. I attached GDB and found some data which might be useful.

(gdb) f 1
#1  phn_merge_siblings (cmp=<optimized out>, offset=40, phn=<optimized out>) at include/jemalloc/internal/ph.h:180
180     in include/jemalloc/internal/ph.h
(gdb) p phn0
$7 = (void *) 0x14ac8e416780
(gdb) p offset
$8 = 40

#1  phn_merge_siblings (cmp=<optimized out>, offset=40, phn=<optimized out>) at include/jemalloc/internal/ph.h:180
180     in include/jemalloc/internal/ph.h
(gdb) p phn0
$12 = (void *) 0x14ac8e416780
(gdb) p ((phn_link_t*)(phn0 + 40))->next
$13 = (void *) 0x14ac8e416780
(gdb) p phn1
$14 = (void *) 0x14ac8e416780

#0  0x0000559748caad60 in phn_prev_set (offset=<optimized out>, prev=<optimized out>, phn=<optimized out>) at include/jemalloc/internal/ph.h:114
#1  phn_merge_siblings (cmp=<optimized out>, offset=40, phn=<optimized out>) at include/jemalloc/internal/ph.h:188
#2  ph_merge_children (cmp=<optimized out>, offset=40, phn=<optimized out>) at include/jemalloc/internal/ph.h:244
#3  ph_remove (cmp=<optimized out>, offset=40, Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
phn=phn@entry=0x14a872200000, ph=0x14ac8e40dc18, ph@entry=0x0) at include/jemalloc/internal/ph.h:389
#4  je_edata_heap_remove (ph=ph@entry=0x14ac8e40dc18, phn=phn@entry=0x14ac8e416780) at src/edata.c:6
#5  0x0000559748cae479 in je_eset_remove (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
eset=0x14ac8e40d278, edata=edata@entry=0x14ac8e416780) at src/eset.c:126
#6  0x0000559748cb1d06 in extent_activate_locked (edata=0x14ac8e416780, eset=<optimized out>, ecache=0x14ac8e40d208, pac=0x14ac8e4039f0, tsdn=0x14ac283aead8) at src/extent.c:280
#7  extent_recycle_extract (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
ehooks=0x14ac8e4000c0, guarded=<optimized out>, alignment=64, size=4294971392, expand_edata=0x100001000, ecache=0x14ac8e40d208, pac=0x14ac8e4039f0,
    tsdn=0x14ac283aead8) at src/extent.c:444
#8  extent_recycle (tsdn=tsdn@entry=0x14ac283aead8, pac=pac@entry=0x14ac8e4039f0, Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
ehooks=ehooks@entry=0x14ac8e4000c0, ecache=ecache@entry=0x14ac8e40d208,
    expand_edata=expand_edata@entry=0x0, size=size@entry=4294971392, alignment=<optimized out>, zero=<optimized out>, commit=<optimized out>, growing_retained=<optimized out>,
    guarded=<optimized out>) at src/extent.c:606
#9  0x0000559748cb20ea in extent_alloc_retained (guarded=false, commit=0x14ac283ad365, zero=<optimized out>, alignment=<optimized out>, size=22729641880280, expand_edata=0x0,
    ehooks=<optimized out>, pac=0x14ac8e4039f0, tsdn=0x14ac283aead8) at src/extent.c:782
#10 je_ecache_alloc_grow (tsdn=tsdn@entry=0x14ac283aead8, pac=pac@entry=0x14ac8e4039f0, ehooks=<optimized out>, ecache=ecache@entry=0x14ac8e40d208, expand_edata=expand_edata@entry=0x0,
    size=size@entry=4294971392, alignment=<optimized out>, zero=<optimized out>, guarded=<optimized out>) at src/extent.c:104
#11 0x0000559748cbc79e in pac_alloc_real (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
tsdn=tsdn@entry=0x14ac283aead8, pac=pac@entry=0x14ac8e4039f0, ehooks=ehooks@entry=0x14ac8e4000c0, size=size@entry=4294971392, Python Exception <class 'NameError'> Installation error: gdb._e
xecute_unwinders function is missing:

    alignment=alignment@entry=64, zero=zero@entry=false, guarded=false) at src/pac.c:124
#12 0x0000559748cbc8e0 in pac_alloc_impl (tsdn=0x14ac283aead8, self=0x14ac8e4039f0, size=4294971392, alignment=64, zero=<optimized out>, guarded=<optimized out>, frequent_reuse=false,
    deferred_work_generated=0x14ac283ad537) at src/pac.c:178
#13 0x0000559748cbb92d in pai_alloc (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
deferred_work_generated=0x14ac283ad537, frequent_reuse=false, guarded=false, zero=false, alignment=<optimized out>, size=4294971392,
    self=0x14ac8e4039f0, tsdn=0x14ac283aead8) at include/jemalloc/internal/pai.h:43
#14 je_pa_alloc (tsdn=tsdn@entry=0x14ac283aead8, shard=shard@entry=0x14ac8e4039d8, size=size@entry=4294971392, alignment=alignment@entry=64, slab=slab@entry=false, szind=108, zero=false,
    guarded=false, deferred_work_generated=0x14ac283ad537) at src/pa.c:139
#15 0x0000559748c6547f in je_arena_extent_alloc_large (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
tsdn=tsdn@entry=0x14ac283aead8, arena=arena@entry=0x14ac8e401040, usize=usize@entry=4294967296, alignment=alignment@entry=64,
    zero=<optimized out>) at src/arena.c:338
#16 0x0000559748cb98eb in je_large_palloc (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
tsdn=tsdn@entry=0x14ac283aead8, arena=0x14ac8e401040, usize=4294967296, alignment=alignment@entry=64, zero=zero@entry=64) at src/large.c:37
#17 0x0000559748cb9d8e in je_large_malloc (tsdn=tsdn@entry=0x14ac283aead8, arena=<optimized out>, usize=<optimized out>, zero=zero@entry=64) at src/large.c:17
#18 0x0000559748c688ce in je_arena_malloc_hard (tsdn=tsdn@entry=0x14ac283aead8, arena=<optimized out>, arena@entry=0x0, size=size@entry=4294967273, ind=5292, ind@entry=108,
    zero=zero@entry=false) at src/arena.c:1205
#19 0x0000559748c5bfa5 in arena_malloc (slow_path=<optimized out>, tcache=0x14ac283aee30, zero=false, ind=108, size=4294967273, arena=0x0, tsdn=<optimized out>)
    at include/jemalloc/internal/arena_inlines_b.h:162
#20 iallocztm (slow_path=<optimized out>, arena=0x0, is_internal=false, tcache=0x14ac283aee30, zero=false, ind=108, size=4294967273, tsdn=<optimized out>)
    at include/jemalloc/internal/jemalloc_internal_inlines_c.h:55

#21 imalloc_no_sample (ind=108, usize=4294967296, size=4294967273, tsd=<optimized out>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2398
#22 imalloc_body (tsd=<optimized out>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2573
#23 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2687
#24 je_malloc_default (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
size=size@entry=4294967273) at src/jemalloc.c:2722
#25 0x0000559748ccd859 in fallback_impl<false> (Python Exception <class 'NameError'> Installation error: gdb._execute_unwinders function is missing:
size=4294967273) at src/jemalloc_cpp.cpp:98

**Comment by interwq** [comment]
When heap corruption happens, it can easily corrupt allocator internals which leads to all kinds of strange behavior, e.g. a corrupted lock state can cause deadlock / livelock.

In this case, the internal pairing heap is corrupted, e.g. from double frees etc.
