### ISSUE TITLE
`operator delete` bypasses debug logging

### ISSUE THREAD

**Issue by DanShaders** [jemalloc/jemalloc#2576]
In `jemalloc_cpp.cpp`, global C++ new/delete operators are calling `free_impl` function directly. This bypasses debug logging for `operator delete`. I think this is a totally unexpected (especially considering that `operator new` is properly logged) and, IMO, worth fixing.

(I just spent 4 hours because of that)

**Comment by interwq** [comment]
Thanks for catching this @DanShaders . Fixed in #2578.
