### ISSUE TITLE
How to set opt.narenas  in code?

### ISSUE THREAD

**Issue by muween** [jemalloc/jemalloc#2584]
xcept of the ways of `ln -s 'narenas:xxx' /etc/malloc.conf` and `export MALLOC_CONF=narenas:xxx`, I want to set narenas in my code. I use mallcnt like this:

```
unsigned new_arena_num = 64;
size_t sz = sizeof(new_arena_num);
int res = mallctl("arenas.narenas", NULL, NULL, &new_arena_num, sz);
```

However, res != 0 and failed. What's wrong ?

`mallctl("opt.narenas", NULL, NULL, &new_narenas, sizeof(sz))` also not work.

**Comment by ericm1024** [comment]
opt.narenas and arenas.narenas are read-only mallctls.

You can check the read-write status by referring to the man page: https://jemalloc.net/jemalloc.3.html (notice the `r-` after both of these names in the documentation)

From the man page, it seems like everything in the `opt.*` namespace can be set in the following ways
> The string specified via --with-malloc-conf, the string pointed to by the global variable malloc_conf, the “name” of the file referenced by the symbolic link named /etc/malloc.conf, and the value of the environment variable MALLOC_CONF, will be interpreted, in that order, from left to right as options. 

The closest closest thing to setting the value in your code is probably the `malloc_conf` variable.

Try defining a global variable like so
```
const char *malloc_conf = "narenas:64";
```
I think the value of this variable has to be fixed, so I don't believe you can do any sort of configuration that isn't just a static number here.
