### ISSUE TITLE
puzzle about cache_bin_alloc_easy

### ISSUE THREAD

**Issue by uvletter** [jemalloc/jemalloc#2588]
I find the code for `cache_bin_alloc_easy` and `cache_bin_alloc` has little difference, and the calculation for adjust_low_water is eliminated, just a pointer comparison now, so if we can drop the `cache_bin_alloc_easy`  in `imalloc_fastpath`

**Comment by interwq** [comment]
`cache_bin_alloc_easy` is designed to minimize the "context" on fastpath, i.e. to limit the # of CPU registers involved on the fastpath, because low_water is not changed on the fastpath. Also note that these paths are heavily inlined which eliminates some of the branches and logic on the fastpath.

**Comment by uvletter** [comment]
To verify the registers difference between the two versions, I generate the assembles in https://godbolt.org/z/f9qvfMcea, but it seems with `cache_bin_alloc_easy` and without `cache_bin_alloc_easy` are almost the same,  without `cache_bin_alloc_easy` even saves a register for `movzx   edx, WORD PTR [rdi+8]`, so I don't think `cache_bin_alloc_easy` limits the # of CPU registers.
