### ISSUE TITLE
Trying to use jeprof to get text wrt leak but getting "first profile should be a remote form"

### ISSUE THREAD

**Issue by jturnergresham** [jemalloc/jemalloc#2590]
I am trying to use jeprof on a jemalloc profile output file (as per https://github.com/jemalloc/jemalloc/wiki/Use-Case:-Leak-Checking) but getting error message:

$ jeprof --show_bytes `which w` jeprof.14332.86.i86.heap
Using local file jeprof.14332.86.i86.heap.
The first profile should be a remote form to use /pprof/symbol

I have tried on a few files, so don't think is the particular file. Had a quick look at the Perl but not seen obvious cause.

Found few others with similar problem but they were trying to generate GIFs and no real resolution offered.

**Comment by jturnergresham** [comment]
User error

**Comment by wisped001** [comment]
halo，I also met this problem, but I had tried series of accounts even the root account, it still over there !!! Could you tell me more about the "User Error", plz..
