### ISSUE TITLE
question about configuration options

### ISSUE THREAD

**Issue by diehard2** [jemalloc/jemalloc#2597]
I'm building jemalloc from source, and I'm seeing the following 

``` 
install_suffix     :
malloc_conf        :
documentation      : 0
shared libs        : 0
static libs        : 1
autogen            : 1
debug              : 0
stats              : 1
experimental_smallocx : 0
prof               : 0
prof-libunwind     : 0
prof-libgcc        : 0
prof-gcc           : 0
fill               : 1
utrace             : 0
xmalloc            : 1
log                : 0
lazy_lock          : 0
cache-oblivious    : 1
cxx                : 1
```
with these options

--disable-shared --enable-static --prefix=$/home/mashter/.conan/data/jemalloc/5.3.0/build/prod/build/03c1c1a761434a9372ad894a65312e161889d8a5/build-release --disable-debug --enable-cxx --disable-doc --enable-fill --enable-xmalloc --disable-readlinkat --enable-syscall --disable-lazy-lock --disable-log --enable-initial-exec-tls --enable-libdl --disable-prof --enable-autogen

and I'm compiling with Clang

I was under the impression that profiling was enabled by default for jemalloc builds, but other than that, what are

prof-libunwind, 
prof-libgcc
prof-gcc

Thanks for the help.

**Comment by interwq** [comment]
These are the backtracing options. See details in https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md?plain=1#L134
