### ISSUE TITLE
Skip purge in some cases involving opt_junk_free

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#260]
In `src/huge.c`, there is this snippet in `huge_ralloc_no_move_similar`:
```c
zeroed = !chunk_purge_wrapper(arena, &chunk_hooks, ptr,
    CHUNK_CEILING(usize), usize, sdiff);
if (config_fill && unlikely(opt_junk_free)) {
        memset((void *)((uintptr_t)ptr + usize), 0x5a, sdiff);
        zeroed = false;
}
```

A similar one is in `huge_ralloc_no_move_shrink`
It seems to me the purge here is not useful considering the memset. Or maybe there shouldn't be a memset and purge should be kept here, I'm not sure what happens to those pages afterwards.
Thoughts?

**Comment by jasone** [comment]
The ```memset()``` only occurs if junk filling is enabled.  The code be restructured as ```if (...) {...} else {...}``` to avoid the extra work in the slow path, but it's a bit simpler to scan the code and understand how the fast path works as-is.

**Comment by glandium** [comment]
The point is that the purge is not unconditional, and is not useful if memset happens after.
