### ISSUE TITLE
Provide a way to decommit instead of purge

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#261]
There are reasons one may want to decommit (which currently does nothing). You can implement commit/decommit with chunk_hooks currently, but the thing is that that has a non negligible performance impact. I found a way to achieve a decent equivalent with less performance impact by making purge not purge but actually decommit (and keeping chunk_hooks_t.decommit doing nothing). In fact, it looks like it even improves(!) performance on some of our Firefox benchmars (which would mean that in some cases we're better off with MEM_DECOMMIT than MEM_RESET).

But that fails because chunks marked as purged are not committed before they are used. (then, there's also huge alloc shrinkage that will try to memset without committing, too)

I kind of worked around the issue by changing the flags set in arena_purge_stashed to use CHUNK_MAP_DECOMMITTED instead of CHUNK_MAP_UNZEROED. That's kind of gross and obviously doesn't solve the problem with memset for huge alloc shrinkage.

Now the question is how can we properly hook this?

Kind of relatedly, I'd like for arena_purge_all to be able to go through all previously purged chunks again, and it seems this could be achieved by setting the flags to something other than  CHUNK_MAP_UNZEROED too. Seems there's an opportunity to kill two birds with one stone.

**Comment by jasone** [comment]
I don't understand the issue you're running into.  The idea for the hooks is that there is a dalloc-->decommit-->purge cascade, i.e. if you decommit, then no purge happens.  What you're describing sounds like using the purge hook rather than the decommit hook, then wishing that the commit hook would later be called.  If you use the decommit hook, then you *do* get a commit hook call before the memory is reused.

**Comment by glandium** [comment]
As mentioned, enabling decommit/commit is slow. However, doing decommit during purge has less of a performance impact (and in some cases improves performance! This is all on Windows, BTW)

**Comment by glandium** [comment]
The last paragraph, however, is about mac, where I'd like another pass of purge to happen on all chunks that have already been purged, but with an implementation that does something else than MADV_FREE..

**Comment by glandium** [comment]
> As mentioned, enabling decommit/commit is slow. However, doing decommit during purge has less of a performance impact (and in some cases improves performance! This is all on Windows, BTW)

because purge doesn't happen as often as decommit.

**Comment by jasone** [comment]
Okay, what I don't understand is how enabling decommit/commit is slow.  If you merely "enable" them as functions that do nothing more than guarantee zeroed memory on commit, is it slow?  ```madvise(...MADV_DONTNEED...)``` suffices for this, as does ```memset(...0...)```.

**Comment by glandium** [comment]
Again, this is Windows. If I implement decommit/commit with MEM_DECOMMIT/MEM_COMMIT, the result is performance regression across the board in Firefox. If I do MEM_DECOMMIT in purge and arrange for MEM_COMMIT to be called before chunks are used, I don't (and as mentioned, in some cases, it's even faster than with no decommit/commit and with MEM_RESET in purge).

**Comment by jasone** [comment]
Ah, I get it.  You want ```arena_dalloc_bin_run()``` to call ```arena_run_dalloc()``` instead of ```arena_run_dalloc_decommit()```.  If you find that works well, I'm game.

**Comment by glandium** [comment]
Let me try that and come back to you in a couple hours. What about the double purge use-case?

**Comment by glandium** [comment]
> What about the double purge use-case?

Mmmm actually, I might be able to do what I want with that change in `arena_dalloc_bin_run`

**Comment by jasone** [comment]
I can't think of a currently supported approach to double purging except to use the decommit/commit hooks for purge, and maintain your own metadata to track which memory ranges have been purged using ```MADV_FREE```, so that you can do the second round of purging completely out-of-band, making sure of course that concurrent no calls into your commit hooks occur.  That's a bit of a pain though, because you'll have to zero the memory in the commit hook if it didn't get double-purged.

**Comment by glandium** [comment]
How about a flag that can be passed to arena.i.purge to do a purge of e.g. UNZEROED pages?

**Comment by glandium** [comment]
Mmmm: how about I do this, assuming it doesn't have performance side effects: do MADV_FREE in decommit, disable purge with lg_dirty_mult, and make the purge hook function do the second purge pass, which will be triggered by arena.i.purge.

**Comment by jasone** [comment]
Heh, I think that will work.

**Comment by glandium** [comment]
> Ah, I get it. You want arena_dalloc_bin_run() to call arena_run_dalloc() instead of arena_run_dalloc_decommit(). If you find that works well, I'm game.

That performs about as badly as without changes to `arena_dalloc_bin_run()`.

**Comment by jasone** [comment]
What other sources of extra decommits (as compared to purges) are there?  That's the only one that jumped out at me.

**Comment by glandium** [comment]
chunk_alloc_mmap ?

**Comment by glandium** [comment]
Interestingly, those are using pages_decommit directly, instead of using hooks, so I was inflicting myself pain by testing page_decommit modifications instead of actually using hooks.

**Comment by glandium** [comment]
Looks like the remainder was `arena_dalloc_large_locked_impl`, so essentially, I'm entirely removing `arena_run_dalloc_decommit` at this point. With that, it looks like I ends up more or less with the same performance as with the `MAP_DECOMMIT` in purge thing, but that's not entirely surprising, since it looks like decommit then only happens right before purge (presumably, from `arena_purge_stashed`)
Note the `pages_decommit` business in chunk_*.c is suspect. The if is weird, and mapping pages to then decommit them almost unconditionally seems funny. And on Windows it's completely inefficient, since you can VirtualAlloc non committed pages directly, instead of committing and decommitting them immediately.
As for double purge, I haven't gotten to a setup that doesn't crash yet.

**Comment by glandium** [comment]
> Mmmm: how about I do this, assuming it doesn't have performance side effects: do MADV_FREE in decommit, disable purge with lg_dirty_mult, and make the purge hook function do the second purge pass, which will be triggered by arena.i.purge.

Well, with `arena_run_dalloc_decommit` not doing anything, decommit is never called if purge is disabled with `lg_dirty_mult`, so that wouldn't work. What might, though is to make decommit `MADV_FREE` and return false, and change the decommit hook to a function that returns true before calling `arena.i.purge`

**Comment by glandium** [comment]
There appears to be no heuristic I can use in the decommit/purge hooks to guess whether they were called from `arena_run_dalloc_decommit` or somewhere else. How do you propose we go forward? Remove `arena_run_dalloc_decommit`? Make it optional?

**Comment by jasone** [comment]
Hmm, what are the ambiguous cases?  Also, are you converging on setup that performs satisfactorily?  That might help inform the decision.

**Comment by glandium** [comment]
> Hmm, what are the ambiguous cases?

I can't seem to distinguish between e.g. `arena_run_dalloc_decommit` triggered decommits from the ones from other code paths from the values passed to the decommit function.

>  Also, are you converging on setup that performs satisfactorily? That might help inform the decision.

I'm converging on the following, that does not perform worse than without this setup, while decommitting memory as wanted:
- Make `arena_run_dalloc_decommit` not call `arena_run_decommit` (in practice, that's equivalent to removing `arena_run_dalloc_decommit` entirely
- On Windows, do `MEM_COMMIT` in the commit hook, and `MEM_DECOMMIT` in the decommit hook.
- On Mac, do `mmap(..., PROT_READ | PROT_WRITE, MAP_FIXED | MAP_PRIVATE | MAP_ANON, -1, 0)` in the purge hook. That actually performs well enough that I don't need double purge anymore.
- On other platforms, keep the default hooks

Note I have a "fun" issue with setting up the hooks on Windows (#269)

**Comment by jasone** [comment]
@glandium, are we all done with this issue?

**Comment by jasone** [comment]
Assumed complete.
