### ISSUE TITLE
Not able to get runtime stats

### ISSUE THREAD

**Issue by benstadin** [jemalloc/jemalloc#2614]
I'm confused about how to get the correct runtime statistics using mallctl. My app always reports the very same and too low numbers. I'm linking the application with LD_PRELOAD, and the stats output when the app exits looks actually correct. I'm running the app inside a Ubuntu 22.04 docker container with jemalloc installed via apt.

Am I missing something obvious?

My config:
`    export MALLOC_CONF="narenas:1,background_thread:true,tcache_max:1024,dirty_decay_ms:0,muzzy_decay_ms:0,retain:false,stats_print:true"`

The numbers below never change during the lifetime of my application, regardless whether I allocate 1GB of memory:

Allocated: 2599864
Active: 2768896
Metadata: 2423800
Resident: 5111808
Mapped: 9060352
Retained: 0

The stats method which prints numbers above:

```
#ifdef __APPLE__
#define mctl je_mallctl
#else
#define mctl mallctl
#endif

int64_t printStats() const {
    size_t sz;

       // Variables to hold statistics
       uint64_t allocated, active, metadata, resident, mapped, retained;

       // Getting the value of allocated memory
       sz = sizeof(allocated);
    mctl("stats.allocated", &allocated, &sz, NULL, 0);

       // Getting the value of active memory
       sz = sizeof(active);
    mctl("stats.active", &active, &sz, NULL, 0);

       // Getting the value of metadata
       sz = sizeof(metadata);
    mctl("stats.metadata", &metadata, &sz, NULL, 0);

       // Getting the value of resident memory
       sz = sizeof(resident);
    mctl("stats.resident", &resident, &sz, NULL, 0);

       // Getting the value of mapped memory
       sz = sizeof(mapped);
    mctl("stats.mapped", &mapped, &sz, NULL, 0);

       // Getting the value of retained memory
       sz = sizeof(retained);
    mctl("stats.retained", &retained, &sz, NULL, 0);

       // Printing the statistics
       std::cout << "Allocated: " << allocated << std::endl;
       std::cout << "Active: " << active << std::endl;
       std::cout << "Metadata: " << metadata << std::endl;
       std::cout << "Resident: " << resident << std::endl;
       std::cout << "Mapped: " << mapped << std::endl;
       std::cout << "Retained: " << retained << std::endl;
    
    return mapped;
}
```

The correct looking stats when the app exits (after allocating and freeing ~1GB):

```
ctive:                    1006673920
mapped:                    1008771072
retained:                           0
base:                           43088
internal:                           0
metadata_thp:                       0
tcache_bytes:                       0
resident:                  1006718976
abandoned_vm:                       0
extent_avail:                       0
```

**Comment by interwq** [comment]
You likely need the epoch call to refresh the stats:
https://jemalloc.net/jemalloc.3.html#epoch

**Comment by benstadin** [comment]
The call to epoch fails. I used the same code as in stats.c below. Does it matter from which thread this method is called?

    uint64_t epoch = 1;
    // Update the statistics cached by mallctl.
    int err;
    size_t sz = sizeof(uint64_t);
        err = mctl("epoch", (void *)&epoch, &sz, (void *)&epoch,
            sizeof(uint64_t));
    if (err != 0) {
        std::cout << "Failed to get jemalloc stats..." << std::endl;
        return -1;
    }
