### ISSUE TITLE
Looks like crititcal sections are leaked

### ISSUE THREAD

**Issue by Dmitry-Me** [jemalloc/jemalloc#262]
`malloc_mutex_init()` calls `InitializeCriticalSectionAndSpinCount()` which must be paired with `DeleteCriticalSection()` *at some later point* but I don't see any `DeleteCriticalSection()` calls anywhere.

**Comment by jasone** [comment]
Mutexes are initialized, and then remain valid (and in use) until process termination.

**Comment by Dmitry-Me** [comment]
@jasone What would happen if this code is linked into a Windows DLL which is repeatedly loaded and unloaded?
