### ISSUE TITLE
Download github source code and. /autogen.sh then make: make: *** [src/jemalloc.sym.o] Error 1 

### ISSUE THREAD

**Issue by shreepo** [jemalloc/jemalloc#2627]
When I downloaded the source code from GitHub, ran ./autogen.sh, and then make, I encountered the following error, and there were many others above it.

include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3245:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3245 | JEMALLOC_ALWAYS_INLINE unsigned
      | ^~~~~~~~~~~~~~~~~~~~~~
include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3256:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3256 | JEMALLOC_ALWAYS_INLINE unsigned
      | ^~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3326:1: error: unknown type name ‘JEMALLOC_EXPORT’
 3326 | JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3326:36: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_RESTRICT_RETURN’
 3326 | JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3365:22: error: expected declaration specifiers or ‘...’ before ‘tsdn_t’
 3365 | irallocx_prof_sample(tsdn_t *tsdn, void *old_ptr, size_t old_usize,
      |                      ^~~~~~
src/jemalloc.c:3367:24: error: expected declaration specifiers or ‘...’ before ‘hook_ralloc_args_t’
 3367 |     prof_tctx_t *tctx, hook_ralloc_args_t *hook_args) {
      |                        ^~~~~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_preamble.h:40,
                 from src/jemalloc.c:1:
include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3399:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3399 | JEMALLOC_ALWAYS_INLINE void *
      | ^~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3429:64: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 3429 | do_rallocx(void *ptr, size_t size, int flags, bool is_realloc) {
      |                                                                ^
src/jemalloc.c:3506:1: error: unknown type name ‘JEMALLOC_EXPORT’
 3506 | JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3506:36: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_RESTRICT_RETURN’
 3506 | JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3518:36: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 3518 | do_realloc_nonnull_zero(void *ptr) {
      |                                    ^
src/jemalloc.c:3556:1: error: unknown type name ‘JEMALLOC_EXPORT’
 3556 | JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3556:36: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_RESTRICT_RETURN’
 3556 | JEMALLOC_EXPORT JEMALLOC_ALLOCATOR JEMALLOC_RESTRICT_RETURN
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_preamble.h:40,
                 from src/jemalloc.c:1:
include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3600:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3600 | JEMALLOC_ALWAYS_INLINE size_t
      | ^~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3614:22: error: expected declaration specifiers or ‘...’ before ‘tsdn_t’
 3614 | ixallocx_prof_sample(tsdn_t *tsdn, void *ptr, size_t old_usize, size_t size,
      |                      ^~~~~~
In file included from include/jemalloc/internal/jemalloc_preamble.h:40,
                 from src/jemalloc.c:1:
include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3625:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3625 | JEMALLOC_ALWAYS_INLINE size_t
      | ^~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3688:1: error: unknown type name ‘JEMALLOC_EXPORT’
 3688 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3688:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_NOTHROW’
 3688 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      |                        ^~~~~~~~~~~~~~~~
src/jemalloc.c:3777:1: error: unknown type name ‘JEMALLOC_EXPORT’
 3777 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3777:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_NOTHROW’
 3777 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      |                        ^~~~~~~~~~~~~~~~
src/jemalloc.c:3804:1: error: expected declaration specifiers before ‘JEMALLOC_EXPORT’
 3804 | JEMALLOC_EXPORT void JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_preamble.h:40,
                 from src/jemalloc.c:1:
include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3833:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3833 | JEMALLOC_ALWAYS_INLINE size_t
      | ^~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:3843:1: error: expected declaration specifiers before ‘JEMALLOC_NOINLINE’
 3843 | JEMALLOC_NOINLINE void
      | ^~~~~~~~~~~~~~~~~
src/jemalloc.c:3869:1: error: expected declaration specifiers before ‘JEMALLOC_EXPORT’
 3869 | JEMALLOC_EXPORT void JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3879:1: error: unknown type name ‘JEMALLOC_EXPORT’
 3879 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3879:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_NOTHROW’
 3879 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      |                        ^~~~~~~~~~~~~~~~
src/jemalloc.c:3906:1: error: expected declaration specifiers before ‘JEMALLOC_EXPORT’
 3906 | JEMALLOC_EXPORT int JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3928:1: error: expected declaration specifiers before ‘JEMALLOC_EXPORT’
 3928 | JEMALLOC_EXPORT int JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3948:1: error: expected declaration specifiers before ‘JEMALLOC_EXPORT’
 3948 | JEMALLOC_EXPORT int JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:3970:1: error: expected declaration specifiers before ‘JEMALLOC_EXPORT’
 3970 | JEMALLOC_EXPORT void JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_preamble.h:40,
                 from src/jemalloc.c:1:
include/jemalloc/internal/jemalloc_internal_macros.h:10:36: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
   10 | #    define JEMALLOC_ALWAYS_INLINE JEMALLOC_ATTR(always_inline) static inline
      |                                    ^~~~~~~~~~~~~
src/jemalloc.c:3995:1: note: in expansion of macro ‘JEMALLOC_ALWAYS_INLINE’
 3995 | JEMALLOC_ALWAYS_INLINE size_t
      | ^~~~~~~~~~~~~~~~~~~~~~
src/jemalloc.c:4018:1: error: unknown type name ‘JEMALLOC_EXPORT’
 4018 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      | ^~~~~~~~~~~~~~~
src/jemalloc.c:4018:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘JEMALLOC_NOTHROW’
 4018 | JEMALLOC_EXPORT size_t JEMALLOC_NOTHROW
      |                        ^~~~~~~~~~~~~~~~
src/jemalloc.c:4041:32: error: expected declaration specifiers or ‘...’ before ‘tsd_t’
 4041 | batch_alloc_prof_sample_assert(tsd_t *tsd, size_t batch, size_t usize) {
      |                                ^~~~~
src/jemalloc.c:4054:62: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 4054 | batch_alloc(void **ptrs, size_t num, size_t size, int flags) {
      |                                                              ^
src/jemalloc.c:4241:1: error: expected declaration specifiers before ‘JEMALLOC_ATTR’
 4241 | JEMALLOC_ATTR(constructor)
      | ^~~~~~~~~~~~~
src/jemalloc.c:4255:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 4255 | {
      | ^
src/jemalloc.c:4334:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 4334 | {
      | ^
src/jemalloc.c:4369:31: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 4369 | jemalloc_postfork_child(void) {
      |                               ^
In file included from include/jemalloc/internal/assert.h:2,
                 from include/jemalloc/internal/tsd_internals.h:9,
                 from include/jemalloc/internal/tsd_tls.h:7,
                 from include/jemalloc/internal/tsd.h:13,
                 from include/jemalloc/internal/ckh.h:5,
                 from include/jemalloc/internal/prof_structs.h:5,
                 from include/jemalloc/internal/jemalloc_internal_includes.h:51,
                 from src/jemalloc.c:2:
include/jemalloc/internal/malloc_io.h:58:8: error: old-style parameter declarations in prototyped function definition
   58 | size_t malloc_snprintf(char *str, size_t size, const char *format, ...)
      |        ^~~~~~~~~~~~~~~
src/jemalloc.c:4397: error: expected ‘{’ at end of input
 4397 | 
      | 
src/jemalloc.c:4396:1: warning: control reaches end of non-void function [-Wreturn-type]
 4396 | }
      | ^
make: *** [src/jemalloc.sym.o] Error 1

**Comment by interwq** [comment]
Check the output from `autogen`. Something is missing there.
