### ISSUE TITLE
calloc() doesn't address possible overflow in multiplication

### ISSUE THREAD

**Issue by Dmitry-Me** [jemalloc/jemalloc#263]
`bootstrap_calloc()` blindly multiplies `size*num` and completely ignores possible overflow which is bad idea (tm) - see http://kqueue.org/blog/2012/03/05/memory-allocator-security-revisited/

**Comment by glandium** [comment]
Having looked at this recently, what matters is that calloc does handle overflow. bootstrap_calloc is only used with _pthread_mutex_init_calloc_cb, and will, in practice, never be called with num > 1.

This is where _pthread_mutex_init_calloc_cb is defined:
https://github.com/freebsd/freebsd/blob/e79c62ff68fc74d88cb6f479859f6fae9baa5101/lib/libthr/thread/thr_mutex.c#L219
and where it calls mutex_init:
https://github.com/freebsd/freebsd/blob/e79c62ff68fc74d88cb6f479859f6fae9baa5101/lib/libthr/thread/thr_mutex.c#L229

This is where mutex_init is defined:
https://github.com/freebsd/freebsd/blob/e79c62ff68fc74d88cb6f479859f6fae9baa5101/lib/libthr/thread/thr_mutex.c#L126
and where it calls the given calloc_cb:
https://github.com/freebsd/freebsd/blob/e79c62ff68fc74d88cb6f479859f6fae9baa5101/lib/libthr/thread/thr_mutex.c#L145

Considering the functionality there, there is no way this will ever change to possibly overflow.

**Comment by jasone** [comment]
Yep, @glandium summed it up well.

**Comment by Dmitry-Me** [comment]
@glandium Then where's the actual `alloca()` which is callable by users?

**Comment by Dmitry-Me** [comment]
I found it - it's `je_calloc()` and there's some reasonably looking code for handling overflows
