### ISSUE TITLE
DeadLock while allocating the memory(Version: 5.2.0)

### ISSUE THREAD

**Issue by manjunathcs405** [jemalloc/jemalloc#2635]
While allocating the memory there is some exception , to Handle the exception __cxa_allocate_exception requested the memory allocation again so deadlock, process got stuck.

Below is the StackTrace for the same:

Pstack:

Thread 8 (Thread 0x7fc71be37700 (LWP 23552)):
#0  0x00007fcb754d354d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fcb754cee9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fcb754ced68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fcb761c1a01 in malloc_mutex_lock_final (mutex=0x7fca13c02558) at include/jemalloc/internal/mutex.h:155
#4  je_malloc_mutex_lock_slow (mutex=0x7fca13c02558) at src/mutex.c:85
#5  0x00007fcb761b9ae8 in malloc_mutex_lock (mutex=0x7fca13c02558, tsdn=0x7fc71be35eb8) at include/jemalloc/internal/mutex.h:221
#6  extent_recycle_extract (growing_retained=<optimized out>, slab=<optimized out>, alignment=4096, pad=0, size=20480, new_addr=0x0, extents=0x7fca13c02558, rtree_ctx=0x7fc71be35ee8, r_extent_hooks=0x7fc71be2f5a0, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8) at src/extent.c:922
#7  extent_recycle (tsdn=0x7fc71be35eb8, arena=0x7fca13c008c0, r_extent_hooks=0x7fc71be2f5a0, extents=0x7fca13c02558, new_addr=0x0, size=20480, pad=0, alignment=4096, slab=true, szind=29, zero=0x7fc71be2f5af, commit=0x7fc71be2f5ae, growing_retained=false) at src/extent.c:1135
#8  0x00007fcb761bb0b9 in je_extents_alloc (tsdn=<optimized out>, arena=<optimized out>, r_extent_hooks=<optimized out>, extents=<optimized out>, new_addr=<optimized out>, size=<optimized out>, pad=0, alignment=4096, slab=true, szind=29, zero=0x7fc71be2f5af, commit=0x7fc71be2f5ae) at src/extent.c:558
#9  0x00007fcb7619348f in arena_slab_alloc (bin_info=0x7fcb763fe128 <je_bin_infos+1160>, binshard=0, binind=29, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8) at src/arena.c:1219
#10 arena_bin_nonfull_slab_get (binshard=0, binind=29, bin=0x7fca13c08e78, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8) at src/arena.c:1264
#11 arena_bin_malloc_hard (tsdn=0x7fc71be35eb8, arena=0x7fca13c008c0, bin=0x7fca13c08e78, binind=29, binshard=0) at src/arena.c:1300
#12 0x00007fcb76193c31 in je_arena_tcache_fill_small (tsdn=0x7fc71be35eb8, arena=0x7fca13c008c0, tcache=<optimized out>, tbin=0x7fc71be36370, binind=29, prof_accumbytes=<optimized out>) at src/arena.c:1388
#13 0x00007fcb761df7f4 in je_tcache_alloc_small_hard (tsdn=<optimized out>, arena=<optimized out>, tcache=<optimized out>, tbin=0x7fc71be36370, binind=<optimized out>, tcache_success=0x7fc71be2f6ff) at src/tcache.c:93
#14 0x00007fcb7618c743 in tcache_alloc_small (slow_path=false, zero=false, arena=<optimized out>, binind=29, size=<optimized out>, tcache=0x7fc71be360a8, tsd=0x7fc71be35eb8) at include/jemalloc/internal/tcache_inlines.h:60
#15 arena_malloc (slow_path=false, zero=false, ind=29, size=<optimized out>, tsdn=0x7fc71be35eb8, tcache=0x7fc71be360a8, arena=0x0) at include/jemalloc/internal/arena_inlines_b.h:165
#16 iallocztm (slow_path=false, zero=false, arena=0x0, is_internal=false, tcache=0x7fc71be360a8, ind=29, size=<optimized out>, tsdn=0x7fc71be35eb8) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#17 imalloc_no_sample (size=<optimized out>, ind=29, usize=5120, tsd=0x7fc71be35eb8, dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:1875
#18 imalloc_body (tsd=0x7fc71be35eb8, dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:2071
#19 imalloc (dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:2180
#20 **je_malloc_default** (size=<optimized out>) at src/jemalloc.c:2211
#21 0x00007fcb749885a3 in **__cxa_allocate_exception ()** from /lib64/libstdc++.so.6
#22 0x00007fcb75ebede1 in HighgateEnvironment::LogStackAndThrow(char const*) () from /opt/AS/share/libwlx.so
#23 0x00007fcb75eff7df in wlSignalHandler () from /opt/AS/share/libwlx.so
#24 <signal handler called>
#25 0x00007fcb761b2613 in je_extent_heap_remove (ph=0x7fca13c02608, phn=0x7fca13c09700) at src/extent.c:289
#26 0x00007fcb761b9783 in extents_remove_locked (extent=<optimized out>, extents=0x7fca13c02558, tsdn=0x7fc71be35eb8) at src/extent.c:384
#27 extent_activate_locked (extents=0x7fca13c02558, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8, extent=<optimized out>) at src/extent.c:700
#28 extent_recycle_extract (growing_retained=<optimized out>, slab=<optimized out>, alignment=4096, pad=0, size=<optimized out>, new_addr=<optimized out>, extents=0x7fca13c02558, rtree_ctx=0x7fc71be35ee8, r_extent_hooks=0x7fc71be34850, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8) at src/extent.c:952
#29 extent_recycle (tsdn=0x7fc71be35eb8, arena=0x7fca13c008c0, r_extent_hooks=0x7fc71be34850, extents=0x7fca13c02558, new_addr=<optimized out>, size=<optimized out>, pad=0, alignment=4096, slab=true, szind=7, zero=0x7fc71be3485f, commit=0x7fc71be3485e, growing_retained=false) at src/extent.c:1135
#30 0x00007fcb761bb0b9 in je_extents_alloc (tsdn=<optimized out>, arena=<optimized out>, r_extent_hooks=<optimized out>, extents=<optimized out>, new_addr=<optimized out>, size=<optimized out>, pad=0, alignment=4096, slab=true, szind=7, zero=0x7fc71be3485f, commit=0x7fc71be3485e) at src/extent.c:558
#31 0x00007fcb7619348f in arena_slab_alloc (bin_info=0x7fcb763fddb8 <je_bin_infos+280>, binshard=0, binind=7, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8) at src/arena.c:1219
#32 arena_bin_nonfull_slab_get (binshard=0, binind=7, bin=0x7fca13c07718, arena=0x7fca13c008c0, tsdn=0x7fc71be35eb8) at src/arena.c:1264
#33 arena_bin_malloc_hard (tsdn=0x7fc71be35eb8, arena=0x7fca13c008c0, bin=0x7fca13c07718, binind=7, binshard=0) at src/arena.c:1300
#34 0x00007fcb76193c31 in je_arena_tcache_fill_small (tsdn=0x7fc71be35eb8, arena=0x7fca13c008c0, tcache=<optimized out>, tbin=0x7fc71be36160, binind=7, prof_accumbytes=<optimized out>) at src/arena.c:1388
#35 0x00007fcb761df7f4 in je_tcache_alloc_small_hard (tsdn=<optimized out>, arena=<optimized out>, tcache=<optimized out>, tbin=0x7fc71be36160, binind=<optimized out>, tcache_success=0x7fc71be349af) at src/tcache.c:93
#36 0x00007fcb7618c743 in tcache_alloc_small (slow_path=false, zero=false, arena=<optimized out>, binind=7, size=<optimized out>, tcache=0x7fc71be360a8, tsd=0x7fc71be35eb8) at include/jemalloc/internal/tcache_inlines.h:60
#37 arena_malloc (slow_path=false, zero=false, ind=7, size=<optimized out>, tsdn=0x7fc71be35eb8, tcache=0x7fc71be360a8, arena=0x0) at include/jemalloc/internal/arena_inlines_b.h:165
#38 iallocztm (slow_path=false, zero=false, arena=0x0, is_internal=false, tcache=0x7fc71be360a8, ind=7, size=<optimized out>, tsdn=0x7fc71be35eb8) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#39 imalloc_no_sample (size=<optimized out>, ind=7, usize=112, tsd=0x7fc71be35eb8, dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:1875
#40 imalloc_body (tsd=0x7fc71be35eb8, dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:2071
#41 imalloc (dopts=<optimized out>, sopts=<optimized out>) at src/jemalloc.c:2180
#42 **je_malloc_default** (size=<optimized out>) at src/jemalloc.c:2211
#43 0x00007fcb75eb2c7d in operator new(unsigned long) () from /opt/AS/share/libwlx.so
..

**Comment by interwq** [comment]
The crash at frame 25:
```
0x00007fcb761b2613 in je_extent_heap_remove (ph=0x7fca13c02608, phn=0x7fca13c09700) at src/extent.c:289
```

This is a common crash site caused by heap corruption from the application (e.g. invalid pointers, double frees).

You will want to debug your application to find the root cause. ASAN is usually the most effective.
