### ISSUE TITLE
Provide way to toggle THP at runtime before first allocation

### ISSUE THREAD

**Issue by michaeleisel** [jemalloc/jemalloc#2645]
My particular use case is that I'd like to only turn on `thp` for Linux kernels that are 4.6+. I can't do this with environment variables because this is for a binary to be run by third parties who shouldn't have to set MALLOC_CONF, and I don't want to use a shim binary + execve to set the variables. If I could, say, run `setenv("MALLOC_CONF", "...", 1);` or `mallctl` before the first allocation to set the `thp` variable, this would solve things. However, when I tried running `setenv` before the first allocation, it didn't work. Perhaps it's because the variable is already read in a constructor function? Could we maybe delay reading more variables until first allocation, or better yet, delay setup as a whole and at least have an option to not run it all in a constructor function?

**Comment by interwq** [comment]
There are a few ways to set the malloc settings:

> The string specified via --with-malloc-conf, the string pointed to by the global variable malloc_conf, the “name” of the file referenced by the symbolic link named /etc/malloc.conf, and the value of the environment variable MALLOC_CONF

See the TUNING section in https://jemalloc.net/jemalloc.3.html

**Comment by michaeleisel** [comment]
None of these are sufficient for this use case. The first is a compile-time change, the second requires changing a file used by other processes, and the last one doesn't work for runtime because it gets read too early.
