### ISSUE TITLE
Microbenchmark uses wrong timebase on some Darwin systems

### ISSUE THREAD

**Issue by jorisgeer** [jemalloc/jemalloc#2653]
On an M2 Apple silicon macbook, microbenchmark reports 0.1-0.2 ns per iteration.

Source code in nstime.c shows mach_absolute_time() is used. This function does not return nanoseconds but 'ticks'.
Developer doc advises to use the equivalent clock_gettime_nsec_np(CLOCK_UPTIME_RAW))

With abovementioned change, iterations now show around 5-8 ns, a figure that seems sensible to me and matches wall-clock times.

See https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time

**Comment by interwq** [comment]
Thanks @jorisgeer. Switching to clock_gettime_nsec_np() in #2733.
