### ISSUE TITLE
cannot build on Mac Yosemite with any compiler (linker error)

### ISSUE THREAD

**Issue by jeffhammond** [jemalloc/jemalloc#266]
I attempted to build the latest version of jemalloc on my Mac.  It fails with GCC 5.2.0, Clang 3.6, and Intel 15.

This is how I configured with GCC 5:
```
jrhammon-mac01:build jrhammon$ ../configure CC=gcc-5 --prefix=/Users/jrhammon/Work/MEMORY/MEMKIND/install-jemalloc-gcc5 && make -j4
```

The error with GCC 5.2 is:
```
jrhammon-mac01:build jrhammon$ make
gcc-5 -shared -Wl,-install_name,/Users/jrhammon/Work/MEMORY/MEMKIND/install-jemalloc-gcc5/lib/libjemalloc.2.dylib  -o lib/libjemalloc.2.dylib src/jemalloc.pic.o src/arena.pic.o src/atomic.pic.o src/base.pic.o src/bitmap.pic.o src/chunk.pic.o src/chunk_dss.pic.o src/chunk_mmap.pic.o src/ckh.pic.o src/ctl.pic.o src/extent.pic.o src/hash.pic.o src/huge.pic.o src/mb.pic.o src/mutex.pic.o src/pages.pic.o src/prof.pic.o src/quarantine.pic.o src/rtree.pic.o src/stats.pic.o src/tcache.pic.o src/util.pic.o src/tsd.pic.o src/valgrind.pic.o src/zone.pic.o  -lpthread 
0  0x10b974a44  __assert_rtn + 144
1  0x10b99c5d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x10b97ff81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
0  0x10b974a44  __assert_rtn + 144
3  0x10b9c2bf8  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 796
1  0x10b99c5d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x10b97ff81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
3  0x10b9c2bf8  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 796
4  0x10b9c4a80  ld::tool::InputFiles::parseWorkerThread() + 472
5  0x7fff87b47268  _pthread_body + 131
6  0x7fff87b471e5  _pthread_body + 0
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2015-07-30-141144.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /SourceCache/ld64/ld64-242.2/src/ld/parsers/macho_relocatable_file.cpp, line 1748.
collect2: error: ld returned 1 exit status
make: *** [lib/libjemalloc.2.dylib] Error 1
```

With Clang 3.6, the error is:
```
jrhammon-mac01:build jrhammon$ make
clang-3.6 -shared -Wl,-install_name,/Users/jrhammon/Work/MEMORY/MEMKIND/install-jemalloc-clang36/lib/libjemalloc.2.dylib  -o lib/libjemalloc.2.dylib src/jemalloc.pic.o src/arena.pic.o src/atomic.pic.o src/base.pic.o src/bitmap.pic.o src/chunk.pic.o src/chunk_dss.pic.o src/chunk_mmap.pic.o src/ckh.pic.o src/ctl.pic.o src/extent.pic.o src/hash.pic.o src/huge.pic.o src/mb.pic.o src/mutex.pic.o src/pages.pic.o src/prof.pic.o src/quarantine.pic.o src/rtree.pic.o src/stats.pic.o src/tcache.pic.o src/util.pic.o src/tsd.pic.o src/valgrind.pic.o src/zone.pic.o  -lpthread 
0  0x10d0cca44  __assert_rtn + 144
1  0x10d0f45d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x10d0d7f81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
3  0x10d11abf8  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 796
4  0x10d11ca80  ld::tool::InputFiles::parseWorkerThread() + 472
5  0x7fff87b47268  _pthread_body + 131
6  0x7fff87b471e5  _pthread_body + 0
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2015-07-30-141548.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /SourceCache/ld64/ld64-242.2/src/ld/parsers/macho_relocatable_file.cpp, line 1748.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libjemalloc.2.dylib] Error 1
```

With Intel 15, the error is:
```
jrhammon-mac01:build jrhammon$ make
icc -shared -Wl,-install_name,/Users/jrhammon/Work/MEMORY/MEMKIND/install-jemalloc-intel15/lib/libjemalloc.2.dylib  -o lib/libjemalloc.2.dylib src/jemalloc.pic.o src/arena.pic.o src/atomic.pic.o src/base.pic.o src/bitmap.pic.o src/chunk.pic.o src/chunk_dss.pic.o src/chunk_mmap.pic.o src/ckh.pic.o src/ctl.pic.o src/extent.pic.o src/hash.pic.o src/huge.pic.o src/mb.pic.o src/mutex.pic.o src/pages.pic.o src/prof.pic.o src/quarantine.pic.o src/rtree.pic.o src/stats.pic.o src/tcache.pic.o src/util.pic.o src/tsd.pic.o src/valgrind.pic.o src/zone.pic.o  -lpthread 
0  0x10c51ca44  __assert_rtn + 144
1  0x10c5445d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x10c527f81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
0  0x10c51ca44  __assert_rtn + 144
1  0x10c5445d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
3  0x10c56abf8  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 796
2  0x10c527f81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
4  0x10c56ca80  ld::tool::InputFiles::parseWorkerThread() + 472
3  0x10c56abf8  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 796
5  0x7fff87b47268  _pthread_body + 131
4  0x10c56ca80  ld::tool::InputFiles::parseWorkerThread() + 472
5  0x7fff87b47268  _pthread_body + 131
6  0x7fff87b471e5  _pthread_body + 0
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2015-07-30-141738.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /SourceCache/ld64/ld64-242.2/src/ld/parsers/macho_relocatable_file.cpp, line 1748.
6  0x7fff87b471e5  _pthread_body + 0
make: *** [lib/libjemalloc.2.dylib] Error 1
```

This is where I am on the jemalloc master:
```
jrhammon-mac01:build jrhammon$ git info | grep Recent -A6
## Most Recent Commit:

commit 6e98caf8f064482b9ab292ef3638dea67420bbc2
Merge: 46c0af6 9b68f67
Author: Jason Evans <jasone@canonware.com>

    Merge branch 'dev'
```

These are the compilers:
```
jrhammon-mac01:build jrhammon$ gcc-5 -v
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.2.0/libexec/gcc/x86_64-apple-darwin14.4.0/5.2.0/lto-wrapper
Target: x86_64-apple-darwin14.4.0
Configured with: ../configure --build=x86_64-apple-darwin14.4.0 --prefix=/usr/local/Cellar/gcc/5.2.0 --libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.2.0 --without-multilib' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --disable-multilib
Thread model: posix
gcc version 5.2.0 (Homebrew gcc 5.2.0 --without-multilib) 

jrhammon-mac01:build jrhammon$ clang-3.6 -v
clang version 3.6.1 (tags/RELEASE_361/final)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

jrhammon-mac01:build jrhammon$ icc --version
icc (ICC) 15.0.3 20150408
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.
```

I am using Mac Yosemite (10.10.4):
```
jrhammon-mac01:build jrhammon$ uname -a
Darwin jrhammon-mac01.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

**Comment by jasone** [comment]
There's something wrong with the toolchain on your system.  I routinely build on OS X 10.10.5 with no issues.

**Comment by jeffhammond** [comment]
My toolchain is more than sufficient to build jemalloc 3.6.0 (http://www.canonware.com/download/jemalloc/jemalloc-3.6.0.tar.bz2).

It seems the build is fine if I do it in-place (`./configure && make`) and remains fine after I do that.  Thus, I would argue that there is nothing wrong my toolchain but something strange in the autotools setup you have that is brittle for out-of-place builds in some circumstances, in particular, the one where someone updates your repo and does `mkdir build && cd build && ../configure CC=gcc-5 && make`.  I guess I will rely upon release tarballs from now on.

In any case, "It works on my Mac, so if it doesn't work on yours, your Mac must be broken" is a logical fallacy.

**Comment by jasone** [comment]
Your ld is asserting, and you're using a non-standard compiler.  That looks very much like your problem.  If you can narrow the scope of this issue to universal problems with objdir build issues, I'll take a look, but I'm not going to install other compilers so I can make ld crash too. ;-)

**Comment by thejkane** [comment]
Hi Jasone,

I am facing the same problem. The assertion is triggered during link time. The error i got is in [1].
My gcc version is as follows;

jemalloc]>gcc --version
gcc (MacPorts gcc48 4.8.4_0) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

In a comment above you mentioned, you routinely build on OS X 10.10.5 without an issue. Could you kindly tell me the gcc version you are using ?

Thank you
Regards
-Thejaka

[1]
gcc -shared -Wl,-dylib_install_name,@rpath/libjemalloc.2.dylib  -o lib/libjemalloc.2.dylib src/jemalloc.pic.o src/arena.pic.o src/atomic.pic.o src/base.pic.o src/bitmap.pic.o src/chunk.pic.o src/chunk_dss.pic.o src/chunk_mmap.pic.o src/ckh.pic.o src/ctl.pic.o src/extent.pic.o src/hash.pic.o src/huge.pic.o src/mb.pic.o src/mutex.pic.o src/pages.pic.o src/prof.pic.o src/quarantine.pic.o src/rtree.pic.o src/stats.pic.o src/tcache.pic.o src/util.pic.o src/tsd.pic.o src/zone.pic.o  -lpthread 
collect2: error: ld terminated with signal 11 [Segmentation fault: 11], core dumped
0  0x10c244f5a  __assert_rtn + 144
1  0x10c2ea5fa  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3076
2  0x10c2cfddc  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 374
0  0x10c244f5a  __assert_rtn + 144
1  0x10c2ea5fa  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3076
3  0x10c247b3f  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 635
0  0x10c244f5a  __assert_rtn + 144
4  0x10c2497c5  ld::tool::InputFiles::parseWorkerThread() + 251
2  0x10c2cfddc  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 374
1  0x10c2ea5fa  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3076
2  0x10c2cfddc  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 374
5  0x7fff8494705a  _pthread_body + 131
3  0x10c247b3f  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 635
6  0x7fff84946fd7  _pthread_body + 0
3  0x10c247b3f  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 635
4  0x10c2497c5  ld::tool::InputFiles::parseWorkerThread() + 251
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2015-08-18-114424.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file src/ld/parsers/macho_relocatable_file.cpp, line 1685.
4  0x10c2497c5  ld::tool::InputFiles::parseWorkerThread() + 251
5  0x7fff8494705a  _pthread_body + 131
6  0x7fff84946fd7  _pthread_body + 0
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2015-08-18-114424.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file src/ld/parsers/macho_relocatable_file.cpp, line 1685.
5  0x7fff8494705a  _pthread_body + 131
make: *** [lib/libjemalloc.2.dylib] Error 1

**Comment by jasone** [comment]
I typically build with the XCode-bundled clang on OS X, but the bundled gcc front end works as well.
```
je@lyken:~/jemalloc [dev]> type -a gcc
gcc is /usr/bin/gcc
je@lyken:~/jemalloc [dev]> gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
je@lyken:~/jemalloc [dev]> clang --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by thejkane** [comment]
Hi Jasone,

Thank you for the response.
I am able to build jemalloc after switching to clang.

I have macport installed gcc and I have been building jemalloc with that without 
any issue. Seems Yosemite update is causing linker to hit the assertion failure. Not sure exactly the cause for the issue. According to [1], the assertion failure is active if we have profiler enabled. I believe
jemalloc does not enable such features by default.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=60893

Thanks
-Thejaka

**Comment by jeffhammond** [comment]
The reason I need a compiler other than the default is because I am going to be using jemalloc with memkind, which requires OpenMP at configure time (I haven't yet figured out why this is, but I will at some point).  I prefer to build with the same compiler toolchain end-to-end, even though I know that the C ABI allows me to do otherwise.

I won't object if you re-close this, but I think it is good that the issue has been discussed so other users understand this limitation on Mac, which I find to be unique to jemalloc among all the libraries I build for Mac.

I also recognize that memkind issues on my Mac are really my problem and should probably just suck it up and fix them myself.  After all, I know where to find the folks who can approve my pull requests to that project :-)

**Comment by jasone** [comment]
I have only one guess as to why ld is crashing: ```JEMALLOC_TLS_MODEL``` is set to ```initial-exec``` if the compiler supports it.  You can try disabling that by editing configure.ac and see if the problem goes away.  If that's the problem, it might be possible to extend the configure test to also verify that linking succeeds.  Ultimately though, this looks still looks to me like a toolchain bug, and even if we end up with a workaround, we should be reporting the bug upstream.

**Comment by jasone** [comment]
@jeffhammond, did you ever find a solution or workaround for this issue?

**Comment by jeffhammond** [comment]
Unfortunately not.  I tried disabling `JEMALLOC_TLS_MODEL` in `configure.ac` but that did not solve it.  I will just use the default toolchain.  This is hardly the first time that Mac has broken my linker user experience.

**Comment by ronawho** [comment]
I think this is caused by a [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57438
) resulting from the use of `__builtin_unreachable()`

https://github.com/jemalloc/jemalloc/pull/409 should resolve it by making the check for `__builtin_unreachable` a configure time check

**Comment by jeffhammond** [comment]
@ronawho I saw issues with GCC 5.2, Clang 3.6 and Intel 15.  I am confused as to how Clang and Intel are affected by a GCC bug, but perhaps I am not thinking hard enough.

**Comment by ronawho** [comment]
@jeffhammond Maybe `__builtin_unreachable` also results in zero-sized functions for Intel and Clang?

Do you still have Clang 3.6 and Intel installed on you mac to be able to see if this works around the issue for them too? Should be easy to test by replacing the `__builtin_unreachable` in [util.h] (https://github.com/jemalloc/jemalloc/blob/dev/include/jemalloc/internal/util.h#L78) with `abort`

**Comment by jeffhammond** [comment]
I tried to reproduce my original bug report with Clang 3.6 (same git hash) but cannot.  I upgraded to El Capitan a while back, so it's fair to say that my platform is not the same now.

**Comment by jeffhammond** [comment]
Fortunately, I can reproduce with GCC 6, so I'll try your fix now.
```
mrene-ivm:build jrhammon$ make
gcc-6 -shared -Wl,-install_name,/Users/jrhammon/Work/MEMORY/MEMKIND/install-jemalloc-gcc6/lib/libjemalloc.2.dylib  -o lib/libjemalloc.2.dylib src/jemalloc.pic.o src/arena.pic.o src/atomic.pic.o src/base.pic.o src/bitmap.pic.o src/chunk.pic.o src/chunk_dss.pic.o src/chunk_mmap.pic.o src/ckh.pic.o src/ctl.pic.o src/extent.pic.o src/hash.pic.o src/huge.pic.o src/mb.pic.o src/mutex.pic.o src/pages.pic.o src/prof.pic.o src/quarantine.pic.o src/rtree.pic.o src/stats.pic.o src/tcache.pic.o src/util.pic.o src/tsd.pic.o src/valgrind.pic.o src/zone.pic.o  -lpthread 
0  0x106f2b99e  __assert_rtn + 144
1  0x106f3f2f3  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3195
2  0x106f37206  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 342
3  0x106f72fa5  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 815
4  0x106f75189  ld::tool::InputFiles::parseWorkerThread() + 495
5  0x7fff9c66b99d  _pthread_body + 131
6  0x7fff9c66b91a  _pthread_body + 0
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2016-05-17-142530.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-264.3.102/src/ld/parsers/macho_relocatable_file.cpp, line 1840.
collect2: error: ld returned 1 exit status
make: *** [lib/libjemalloc.2.dylib] Error 1
```

**Comment by jeffhammond** [comment]
@ronawho Indeed, defining `unreachable()` to `abort()` in all three cases (in `util.h`) fixes this in https://github.com/jemalloc/jemalloc/commit/6e98caf8f064482b9ab292ef3638dea67420bbc2 as well as https://github.com/jemalloc/jemalloc/commit/3de035335255d553bdb344c32ffdb603816195d8.

**Comment by ronawho** [comment]
Cool, let me know if you get a chance to try it out with the Intel compiler as well.

And FYI I can't repro the failure with clang 3.5 or 3.6 on Yosemite with 6e98caf8f064482b9ab292ef3638dea67420bbc2, or 3de035335255d553bdb344c32ffdb603816195d8

**Comment by jeffhammond** [comment]
Like Clang 3.6, Intel 16 (details below) no longer shows this error.
```
$ icc -v
icc version 16.0.2 (gcc version 4.9.0 compatibility)
```
