### ISSUE TITLE
build and install the latest 5.3.0 version, the version displayed may be wrong

### ISSUE THREAD

**Issue by Angelia-Wang** [jemalloc/jemalloc#2671]
After downloading and installing the latest 5.3.0 version of the source code, the version displayed is strange：
```shell
$ wget https://github.com/jemalloc/jemalloc/archive/refs/tags/5.3.0.tar.gz
$ tar -xzvf 5.3.0.tar.gz
$ cd jemalloc-5.3.0
$ ./autogen.sh
$ make
$ sudo make install

$ jemalloc-config --version
0.0.0-0-g000000missing_version_try_git_fetch_tags
```

**Comment by interwq** [comment]
Only the official release package contains the pre-generated VERSION file, which is located at:
https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2

If you want to build from source, follow the hint in the message, by having it in a git repo and do git fetch tags (which are needed to generate the proper version number).
