### ISSUE TITLE
Excessive extent requests when using extent alloc hook (wasting memory)

### ISSUE THREAD

**Issue by VinayBanakar** [jemalloc/jemalloc#2673]
Hi, I am writing a simple custom extent allocator that returns extents from a pre mapped area (this way I can explicitly control the mapped area -- and the allocations in it). I am using the dev branch. Here is a simple test file where we perform 100 allocations of 1024 bytes (the allocation size doesn't matter) and set a custom alloc hook.

```c++
#include <iostream>
#include <sys/mman.h>
#include "/home/vin/jemalloc/include/jemalloc/jemalloc.h"
#include <cstring>
/*
  To run this test:
  1. clone jemalloc: git clone https://github.com/jemalloc/jemalloc.git
  2. configure jemalloc with --with-jemalloc-prefix=jem_
  3. build test:
    g++ -std=c++17 -I/home/user/jemalloc/include -L/home/user/jemalloc/lib test.cc -o test -ljemalloc
*/
const size_t INITIAL_MMAP_SIZE = 1ULL * 1024 * 1024 * 1024; // 1 GiB

struct ArenaInfo
{
    uintptr_t base_pointer;
    uintptr_t pre_alloc;
} info;

void *extent_alloc_hook_dram(extent_hooks_t *extent_hooks, void *new_addr, size_t size,
                             size_t alignment, bool *zero, bool *commit, unsigned arena_ind)
{
    uintptr_t ret = (info.pre_alloc + alignment - 1) & ~(alignment - 1);
    if (ret + size > info.base_pointer + INITIAL_MMAP_SIZE)
        return nullptr;
    info.pre_alloc = ret + size;
    if (*zero)
        memset(reinterpret_cast<void *>(ret), 0, size);
    printf(">>> extent request: size %lu ret %p alignment %lu\n", size, (void *)ret, alignment);
    return reinterpret_cast<void *>(ret);
}

int main()
{
    extent_hooks_t *hooks = new extent_hooks_s();
    memset(hooks, 0, sizeof(extent_hooks_s));
    hooks->alloc = extent_alloc_hook_dram;
    info.base_pointer = reinterpret_cast<uintptr_t>(mmap(NULL, INITIAL_MMAP_SIZE,
                                            PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0));
    if (reinterpret_cast<void *>(info.base_pointer) == MAP_FAILED)
    {
        std::cerr << "mmap failed" << std::endl;
        return 1;
    }
    info.pre_alloc = info.base_pointer;
    unsigned arena_id;
    size_t sz = sizeof(arena_id);
    if (jem_mallctl("arenas.create", &arena_id, &sz, (void *)&hooks, sizeof(extent_hooks_t *)))
    {
        throw std::runtime_error("Failed to create new arena with new hooks");
    }
    int flags = MALLOCX_ARENA(arena_id) | MALLOCX_TCACHE_NONE;
    for (int i = 0; i < 100; i++)
    {
        void *p = jem_mallocx(1024, flags);
        std::cout << "1024" << " " << p << std::endl;
    }
    jem_malloc_stats_print(NULL, NULL, NULL);

    return 0;
}
```
The sample output from the above code is 
```
>>> extent request: size 2097152 ret 0x7fffb6e00000 alignment 2097152
>>> extent request: size 2097152 ret 0x7fffb7000000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7200000 alignment 4096
1024 0x7fffb7200000
1024 0x7fffb7200400
1024 0x7fffb7200800
1024 0x7fffb7200c00
>>> extent request: size 2097152 ret 0x7fffb7201000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7401000 alignment 4096
1024 0x7fffb7401000
1024 0x7fffb7401400
1024 0x7fffb7401800
1024 0x7fffb7401c00
>>> extent request: size 2097152 ret 0x7fffb7402000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7602000 alignment 4096
1024 0x7fffb7602000
1024 0x7fffb7602400
1024 0x7fffb7602800
1024 0x7fffb7602c00
>>> extent request: size 2097152 ret 0x7fffb7603000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7803000 alignment 4096
1024 0x7fffb7803000
1024 0x7fffb7803400
1024 0x7fffb7803800
1024 0x7fffb7803c00
```
jemalloc requests 2 MiB extents periodically. After each 2 MiB extent, it requests a 4 KiB extent. 

I expected all the 1024 allocations (belonging to the same size class) must be in a contiguous slab. After every 4 1024 allocations, a 2 MiB extent is requested which is presumably used for metadata and consequently a 4096 B extent is requested to store our allocations. So you can now see how simple sequential allocations (of the same size class) is placing the allocations 2 MiB apart for no reason. I call the metadata usage "high and wasteful"  because we don't need 2 MiB of metadata extent to manage a single 4 KiB extent. Ideally I would not expect a request for 2 MiB extents until a large number of pages are filled.

**Comment by VinayBanakar** [comment]
I see a similar issue (#1468) but it is closed to have been resolved.
I have tried without the `MALLOCX_TCACHE_NONE` flag but it doesn't seem to make a difference in number of extents requests but it does change the order in which they are requested.
```
>>> extent request: size 2097152 ret 0x7fffb6e00000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7000000 alignment 4096
>>> extent request: size 2097152 ret 0x7fffb7001000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7201000 alignment 4096
>>> extent request: size 2097152 ret 0x7fffb7202000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7402000 alignment 4096
1024 0x7fffb7000000
1024 0x7fffb7000400
1024 0x7fffb7000800
1024 0x7fffb7000c00
1024 0x7fffb7201000
1024 0x7fffb7201400
1024 0x7fffb7201800
1024 0x7fffb7201c00
1024 0x7fffb7402000
1024 0x7fffb7402400
>>> extent request: size 2097152 ret 0x7fffb7403000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7603000 alignment 4096
>>> extent request: size 2097152 ret 0x7fffb7604000 alignment 4096
>>> extent request: size 4096 ret 0x7fffb7804000 alignment 4096
1024 0x7fffb7402800
1024 0x7fffb7402c00
1024 0x7fffb7603000
1024 0x7fffb7603400
1024 0x7fffb7603800
1024 0x7fffb7603c00
1024 0x7fffb7804000
1024 0x7fffb7804400
1024 0x7fffb7804800
1024 0x7fffb7804c00
```

**Comment by guangli-dai** [comment]
Some things to check: 
1. the malloc stats, it should include some information that could affect the behavior of fitting requests into existing extents, i.e., `lg_extent_max_active_fit`. Also the purging of extents are not followed, some extents may get purged based on different settings of `dirty_decay_ms`;
2. To understand why extents are requested, adding a breakpoint to the hook function should give you a full backtrace and more information regarding how that extent is used;

Some other context FYI. Sometimes jemalloc may over reserve, but those untouched area is only virtual memory. Virtual memory is viewed as a much cheaper resource compared to the physical memory.

**Comment by user8555** [comment]
Is it correct to ignore the `new_addr` value in the code above? As per the documentation, if new_addr is not NULL then the return value must be `new_addr`. I'm trying to write a similar solution, however, it's unclear to me how to maintain the contract to return new_addr. 

Are there any constraints on what the possible range of new_addr might be? can it be any arbitrary address? Arbitrary address would mean that the hook implementation will need to keep a page table and implement yet another virtual memory management system.

**Comment by VinayBanakar** [comment]
@guangli-dai thanks for your response. I experimented with different `lg_extent_max_active_fit` (2, 6, 11, 63, etc) but it did not have any effect on reusing the 2MiB extent reserved for metadata for our 1024 allocations. The `dirty_decay_ms`is set to default (10s) and our test program does not take that long to run. I wondered if it was a size class specific behavior but l observe it doesn't seem to be. I understand that jemalloc might over reserve VM but requesting a new 2 MiB extent to hold metadata for each consecutive 4 KiB extent (which holds user allocations) seem very unreasonable. 

Here is the stats file when lg_extent_max_active_fit is set to 11: [jem_malloc_stats.txt](https://github.com/user-attachments/files/16401518/jem_malloc_stats.txt)

**Comment by VinayBanakar** [comment]
I did some more debugging and here is a part of the relevant call graph: 
```
pac_alloc_impl()
|--- pac_alloc_real() (tries various ecaches)
|    |--- ecache_alloc()
|    |    |--- extent_recycle()
|    |    |    |--- extent_recycle_extract()
|    |    |    |    |--- eset_fit()
|    |    |    |         |--- eset_first_fit() 
                              # always returns NULL in the custom extent case
|    |    |    |--- extent_recycle_split()
|    |    |         |--- extent_split_interior()
|    |    |              |--- extent_split_impl()
                              # returns NULL if custom alloc 
                              set but no custom split provided
|    |    |                   |--- ehooks_split() (splits existing extents)
|    |--- ecache_alloc_grow()
|    |    |--- extent_alloc_retained()
|    |         |--- extent_recycle() (see above)
|    |         |--- extent_grow_retained()        
|    |              if no cached extents:
|    |              |--- extent_alloc_wrapper() (allocates new extent)
|    |                   |--- ehooks_alloc() (maps/allocates new pages)
|    |                        |--- extent_alloc_mmap() (system call)
|    |                        |--- extent_alloc_t (user provided)
```
There seems to be two reasons why the initial 2 MiB allocated is not being reused for the 1024 allocations and we are forced to allocate 2MiB + 4 KiB extents after every 4 1024 allocations. 
1. `extent_recycle_extract()` (`eset_first_fit()`) is not able to find a fit (the bitmap is empty, not sure why) and thus is not requesting for the extent split. Because the existing extent is not split, we request a new 2 MiB extent from `extent_grow_retained()`.
2. In `extent_split_impl()` when a custom extent alloc is set but no custom extent split is defined, the `ehooks_split_will_fail` returns true thus detering from any extent splitting.

@interwq @guangli-dai @jasone I would really appreciate your help understand this behavior and updating the docs accordingly. When no custom split/merge hook is provided, can we expect the default hooks to kick in? Also, will the `extent_recycle_extract`/`eset_first_fit` work on extents returned from custom extent alloc?

Here is an output file that reports relevant functions entered and their parameters during the above allocations: [verbose_output.txt](https://github.com/user-attachments/files/16405159/verbose_output.txt)

**Comment by VinayBanakar** [comment]
I found a fix. First, looks like either we should mark the extent as committed in alloc hook or provide an explicit commit hook that returns false. Furthermore, we also seem to require setting a split hook explicitly. What the split hook does doesn't seem to matter but just that it shouldn't be null.

**Comment by interwq** [comment]
As you already observed, null hooks mean it's not allowed or failure. There will be no default hooks that can fit all scenarios. You must indicate if a operation is allowed / succeed or not in the hook.
