### ISSUE TITLE
huge expansion may waste system calls on Windows

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#268]
It doesn't directly matter to me, but since I was looking at the code to figure out how chunks were handled on Windows (since VirtualAlloc and VirtualFree must match 1:1 when mapping/unmapping), I found out that `arena_chunk_ralloc_huge_expand_hard` is wastefully trying to expand the zone when chunk merging won't work.

So what jemalloc ends up doing when expanding a huge allocation is:
- (try to) allocate chunks following the old allocation
- when that succeeds, it calls the merge hook, which returns true (at least for the default merge hook)
- then those chunks are deallocated
- to add insult to injury, it may retry all the above with a different size (cf. `huge_ralloc` doing two `huge_ralloc_no_move_expand` passes)
- only then a totally new set of chunks is allocated.

**Comment by jasone** [comment]
In order to solve this we may have to introduce a way for the extent hooks to specify whether merging and coalescing can possibly succeed.  For example, we could allow those hook function pointers to be ```NULL```, in which case it would be possible to short-circuit all the pointless steps.
