### ISSUE TITLE
Error jemalloc telegram-desktop snap/flatpak arm64

### ISSUE THREAD

**Issue by tigernero79** [jemalloc/jemalloc#2680]
for a few days telegram desktop snap arm64 stops and does not start on pios arm64 system generating this error output:

```
pi@RaspyPi5v4:~ $ sudo snap run telegram-desktop
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /root/snap/telegram-desktop/common/.cache/gio-modules/libgiolibproxy.so
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
../../../glib/gprintf.c:350: failed to allocate memory
```

```
pi@RaspyPi5v4:~ $ flatpak run org.telegram.desktop
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
../glib/gprintf.c:349: failed to allocate memory
```

Is this a known issue? Is there a way to fix it?

**Comment by popey** [comment]
For the snap, there is a workaround. I publish a fork, built on an M1 machine. https://snapcraft.io/telegram-asahi

**Comment by tigernero79** [comment]
it's curious that telegram with its official build didn't notice the bug. or didn't promptly correct it. having to force those with arm64 cpu to use unofficial snap. it makes you understand how snaps are not regularly followed. I'm very sorry

**Comment by popey** [comment]
@tigernero79, they're well aware. There are a few bugs about it. From their perspective, it's Jemalloc that needs fixing, not Telegram. Do a few more searches, and you'll find numerous conversations about it.

**Comment by tigernero79** [comment]
@popey 

that's the problem. they can't say the problem isn't ours but jemalloc's. and close it here because in any case you make a bad impression. regardless if you rely on third parties then try not to rely on anyone else and do the work yourself. because it will always be your application that doesn't work. saying it's not our fault doesn't make you look good or help you in our application. like saying my Ferrari won't start but we can't do anything about it because we don't make the defective part. and that means take care of it yourself otherwise you will fail as a brand. do you understand?
