### ISSUE TITLE
[Deadlock] deadlock happens in pac_dalloc_impl when concurrent calls to std::vector.reserve() & push.back()

### ISSUE THREAD

**Issue by zzk777x** [jemalloc/jemalloc#2683]
<img width="577" alt="image" src="https://github.com/user-attachments/assets/458eeceb-cdd8-407e-b291-c31c6e6cbd58">
jemalloc version：5.3.0

**Comment by zzk777x** [comment]
The deadlock seems to occur here:
https://github.com/jemalloc/jemalloc/blob/b66f689764e05084f5b995bf2f8d277b70e084fd/src/extent.c#L926

**Comment by guangli-dai** [comment]
Can you share the minimal repro you have?

**Comment by interwq** [comment]
> concurrent calls to std::vector.reserve() & push.back()

If there's no synchronization, the internals of the vector will be corrupted and result in invalid operations such as double free and corrupted pointers etc. These will be passed down to the allocator which then corrupts allocator internal metadata. Not an allocator issue.
