### ISSUE TITLE
Initialization order issue when trying to set chunk hooks

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#269]
This happened to me on Windows, but this might as well happen anywhere the compiler creates a global initialization function to fill the `init_lock` with its initial value, although that's rather unlikely.

The problem at hand is that I setup a constructor function in order to set up my custom chunk hooks, and that function ended up running before the `init_lock` initializer, so when I called `mallctl`, which calls `malloc_init`, `malloc_init` crashed while trying to lock the uninitialized `init_lock`.

The problem is that nothing guarantees in which order initializers in the same binary are going to be executing.

For now, I worked around this by forcing the `init_lock` initializer to be executed earlier by adjusting the CRT$XC* section name, but it only works on MSVC (so it would still be broken for TorBrowser, who build with mingw).

**Comment by jasone** [comment]
Thanks!
