### ISSUE TITLE
ASLR: FreeBSD 13.2 Jemalloc causes RES memory to keep on increasing even after setting retain:false

### ISSUE THREAD

**Issue by RupeshPilania** [jemalloc/jemalloc#2711]
Hi Team,

I noticed Jemalloc doesn't bring down RES memory to original one even after calling free and setting these flags.
MALLOC_CONF="xmalloc:true,dirty_decay_ms:0,retain:false" 
The only way to make it work is to disable aslr at kernel level along with MALLOC_CONF="xmalloc:true,dirty_decay_ms:0,retain:false" 

Test Results:

ASLR Enabled:

cat /etc/sysctl.conf | grep aslr
kern.elf32.aslr.enable=1
kern.elf32.aslr.pie_enable=1
kern.elf64.aslr.enable=1
kern.elf64.aslr.pie_enable=1
13.2-RELEASE-p12 FreeBSD 13.2-RELEASE-p12 MESSAGING_GATEWAY amd64

C600V-DUT018:rtestuser 16] ./mem-fragment
Hello!  This program will fragment its process heap.  Run top -p 5364 to follow along!
Press Enter to continue...

 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
 5364 root          1  20    0    10M  2280K ttyin    6   0:00   0.00% mem-frag

500k 5KB chunks were just provisioned
Press Enter to continue...

  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
 5364 root          1  52    0  4898M  3034M ttyin    6   0:02   0.00% mem-frag

500k 5KB chunks were just provisioned
Press Enter to continue...

 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
 5364 root          1  48    0  9816M  6064M ttyin    6   0:04   0.00% mem-frag

The first allocations were just free()'d.
Press Enter to continue...

  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
 5364 root          1  27    0  7266M  3541M ttyin    6   0:05   0.00% mem-frag

The 2nd allocations were just free()'d.
Press Enter to continue...

  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
 5364 root          1  28    0  4716M  1018M ttyin    6   0:05   0.00% mem-frag

ASLR Disabled:
cat /etc/sysctl.conf | grep aslr
kern.elf32.aslr.enable=0
kern.elf32.aslr.pie_enable=0
kern.elf64.aslr.enable=0
kern.elf64.aslr.pie_enable=0

C600V-DUT018:rtestuser 8] setenv MALLOC_CONF "xmalloc:true,dirty_decay_ms:0,retain:false"

C600V-DUT018:rtestuser 10] ./mem-fragment
Hello!  This program will fragment its process heap.  Run top -p 3884 to follow along!
Press Enter to continue...
 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
 3884 root          1  20    0    16M  2152K ttyin    5   0:00   0.00% mem-frag
500k 5KB chunks were just provisioned
Press Enter to continue...
  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COM
 3884 root          1  44    0  2592M  2072M ttyin    5   0:02   0.00% mem
500k 5KB chunks were just provisioned
Press Enter to continue...
 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COM
 3884 root          1  45    0  5168M  4142M ttyin    5   0:03   0.00% mem
The first allocations were just free()'d.
Press Enter to continue...
 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COM
 3884 root          1  25    0  2618M  2097M ttyin    5   0:04   0.00% mem
The 2nd allocations were just free()'d.
Press Enter to continue...
 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COM
 3884 root          1  26    0    68M    52M ttyin    5   0:04   0.00% mem

**Comment by RupeshPilania** [comment]
Raised bug on FreeBSD as well https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281471
mem-fragment program reference was taken from https://engineering.linkedin.com/blog/2021/taming-memory-fragmentation-in-venice-with-jemalloc#:~:text=Jemalloc

#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
 
 
// Define constants to make sure strings are not allocated at the top of the heap
#define HIT_ENTER  "Press Enter to continue...\n"
#define ALLOCATED  "500k 5KB chunks were just provisioned\n"
#define FREED      "The first allocations were just free()'d.\n"
#define FREED_NEXT "The 2nd allocations were just free()'d.\n"
 
 
void press_enter_to_continue(void) {
   printf(HIT_ENTER);
   getchar();
   return;
}
 
int main() {
    printf("Hello!  This program will fragment its process heap.  Run top -p %d to follow along!\n", getpid());
    press_enter_to_continue();
 
    int i;
    // Arbitrary value
    int ARRAY_SIZE = 5*1024*102;
 
    // Because we're asking for a large size at the get-go, the backing memory for these arrays will be mmap'd.  But the pointers stored here will be for
    // small allocations that we expect to be brk()'d.  We keep the mapping so we can free them later.
    char *p1[ARRAY_SIZE];
    char *p2[ARRAY_SIZE];
 
    int mallocSize = 5 * 1024;
 
    for(i=0; i < ARRAY_SIZE; i++){
        // malloc in small chunks such that we are always below the mmap threshold for these allocations.
        p1[i] = malloc(mallocSize);
        // Write something to make sure the page is backed by physical RAM
        *p1[i] = 'a';
    }
 
    printf(ALLOCATED);
    press_enter_to_continue();
 
    for(i=0; i < ARRAY_SIZE; i++){
        // Again, malloc in small chunks such that we are always below the mmap threshold for these allocations
        p2[i] = malloc(mallocSize);
       *p2[i] = 'a'; 
    }
 
    printf(ALLOCATED);
    press_enter_to_continue();
 
    // Free the allocations
    for(i=0; i < ARRAY_SIZE; i++){
        free(p1[i]);
    }
 
    printf(FREED);
    press_enter_to_continue();
 
    // Free the allocations
    for(i=0; i < ARRAY_SIZE; i++){
        free(p2[i]);
    }
 
    printf(FREED_NEXT);
    press_enter_to_continue();
 
    return 0;

**Comment by interwq** [comment]
From the discussion in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281471, it looks to be fixed in FreeBSD 14. Closing but feel free to ping if anything.
