### ISSUE TITLE
Allow to control the junk bytes

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#272]
Currently, enabling junk will use 0xa5 for allocations and 0x5a for deallocations. It can be preferred to use other values in order to control the destination of hypothetical pointers with those byte patterns, or hypothetical instructions, which can depend on the OS and architecture.

Now, the question is how to expose this. I was thinking going through `malloc_conf`. Another possibility would be to hardcode at build time, through configure options. For the former, one thing to weigh is that the config for junk is currently in the form `junk:(true|false|alloc|free)`, with `junk:free` meaning both alloc and free. I waas thinking about something like `junk:alloc=a5` which would be the same as `junk:alloc`, `junk:free=5a` which would be the same as `junk:free` and `junk:alloc=a5;free=5a` which would be the same as `junk:true`. Then one could change the values. The simple equivalents would still work. But maybe I'm being too fancy.

I was also wondering if there was interest in having a full pointer-sized value for junk.

@thestinger might have something to say here.

**Comment by thestinger** [comment]
Perhaps the default could just guarantee a crash in that scenario by using a byte pattern that will cause any pointers to point into the kernel's portion of the memory. It could pick a good default per-platform.

**Comment by jasone** [comment]
I've considered this in the past but never taken any action because I've never seen a situation where ```0xa5/0x5a``` fails to cause crashes.  Have you run into such a case?

If we do make this configurable, I'd prefer not to extend the configuration string syntax, and instead add e.g. ```opt.junk_{alloc,free}```.  Re: supporting pointer-size junk values, that would require a bit of internal refactoring, and IMO loses one of the great things about byte-size junk values: they're really easy to spot in crashes.

**Comment by glandium** [comment]
> Perhaps the default could just guarantee a crash in that scenario by using a byte pattern that will cause any pointers to point into the kernel's portion of the memory

Even if that is possible for 32-bits processes on 32-bits kernels, that doesn't work for 32-bits on 64-bits kernels, does it? That could work for 64-bits processes on 64-bits kernels, assuming the current state where no address space is using the full 64 bits.

> I've considered this in the past but never taken any action because I've never seen a situation where 0xa5/0x5a fails to cause crashes.

0xa5a5a5a5 will cause a crash in 32-bits processes on 32-bits kernels, and 0xa5a5a5a5a5a5a5a5/0x5a5a5a5a5a5a5a5a will cause a crash in 64-bits processes on 64-bits kernels, but:
- 0xa5a5a5a5 is not guaranteed to cause a crash in a 32-bits process on a 64-bits kernel because nothing is guaranteeing the address is not mapped and writable
- 0x5a5a5a5a is in the same situation as 0xa5a5a5a5 (lack of guarantee it's not mapped and writable) for 32-bits processes on both 32-bits and 64-bits kernels

**Comment by jasone** [comment]
This is centralized now into ```JEMALLOC_{ALLOC,FREE}_JUNK``` (a82070ef5fc3aa81fda43086cdcc22bfa826b894), which makes it easy to modify the specific values (though not at run time).
