### ISSUE TITLE
Crash happening:  INVALID_POINTER_READ_c0000005_jemalloc.dll!tcache_bin_flush_stashed

### ISSUE THREAD

**Issue by gugavaro** [jemalloc/jemalloc#2721]
callstack:

`
00 00000088`377fd2a8 00007ffd`c06533a3     ntdll!ZwWaitForMultipleObjects+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 964] 01 00000088`377fd2b0 00007ffd`c0653271     KERNELBASE!WaitForMultipleObjectsEx+0x123 [minkernel\kernelbase\synch.c @ 1551] 02 00000088`377fd5a0 00007ffd`c1c60e20     KERNELBASE!WaitForMultipleObjects+0x11 [minkernel\kernelbase\synch.c @ 1403] 03 00000088`377fd5e0 00007ffd`c1c889cd     kernel32!WerpReportFaultInternal+0x62c [onecore\windows\feedback\core\faultrep\lib\faultrep.cpp @ 1073] 04 00000088`377fd760 00007ffd`c071eabc     kernel32!WerpReportFault+0xc5 [onecore\windows\feedback\core\faultrep\lib\faultrep.cpp @ 1384] 05 00000088`377fd7b0 00007ffd`c31a7e4a     KERNELBASE!UnhandledExceptionFilter+0x34c [minkernel\kernelbase\xcpt.c @ 701] 06 (Inline Function) --------`--------     ntdll!RtlpThreadExceptionFilter+0x2e [minkernel\ldr\rtlstrt.c @ 958] 07 00000088`377fd8a0 00007ffd`c3163ef3     ntdll!RtlUserThreadStart$filt$0+0x3f [minkernel\ldr\rtlstrt.c @ 1185] 08 00000088`377fd8d0 00007ffd`c31a353f     ntdll!__C_specific_handler+0x93 [minkernel\crts\crtw32\misc\riscchandler.c @ 446] 09 00000088`377fd940 00007ffd`c305f358     ntdll!RtlpExecuteHandlerForException+0xf [minkernel\ntos\rtl\amd64\xcptmisc.asm @ 132] 0a 00000088`377fd970 00007ffd`c31a2e7e     ntdll!RtlDispatchException+0x2c8 [minkernel\ntos\rtl\amd64\exdsptch.c @ 680] 0b 00000088`377fe0c0 00007ffc`e7c3e467     ntdll!KiUserExceptionDispatch+0x2e [minkernel\ntos\rtl\amd64\trampoln.asm @ 771] 0c 00000088`377fe7f0 00007ffc`e7c42d46     jemalloc!tcache_bin_flush_stashed+0x57 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 557] 0d 00000088`377fe890 00007ffc`e7c3e3af     jemalloc!tcache_bin_flush_bottom+0x66 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 510] 0e 00000088`377fe920 00007ffc`e7c435e6     jemalloc!tcache_bin_flush_small+0x3f [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 529] 0f 00000088`377fe960 00007ffc`e7c436a0     jemalloc!tcache_flush_cache+0xc6 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 790] 10 00000088`377fe9c0 00007ffc`e7c3ea0b     jemalloc!tcache_destroy+0x30 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 810] 11 00000088`377fea20 00007ffc`e7c4d552     jemalloc!tcache_cleanup+0x18b [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 853] 12 00000088`377fea60 00007ffc`e7c4acbb     jemalloc!tsd_do_data_cleanup+0x32 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tsd.c @ 383] 13 00000088`377fea90 00007ffc`e7c4bb1a     jemalloc!tsd_cleanup+0x5b [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tsd.c @ 409] 14 00000088`377fead0 00007ffc`e7c4ac3b     jemalloc!tsd_boot1+0x6a [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\tsd_win.h @ 92] 15 00000088`377ff5a0 00007ffc`e7b127f3     jemalloc!malloc_tsd_boot1+0xb [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tsd.c @ 453] 16 00000088`377ff5e0 00007ffc`e7b128d7     jemalloc!malloc_init_hard+0x1b3 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2167] 17 00000088`377ff620 00007ffc`e7b1c940     jemalloc!malloc_init+0x17 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 298] 18 00000088`377ff650 00007ffc`e7b1c9ca     jemalloc!imalloc_init_check+0x20 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2658] 19 00000088`377ff680 00007ffc`e7b07b70     jemalloc!imalloc+0x2a [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2676] 1a 00000088`377ff6c0 00007ffc`e7b11216     jemalloc!malloc_default+0xa0 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2727] 1b 00000088`377ff7e0 00007ffc`e7b02b9b     jemalloc!imalloc_fastpath+0xf6 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\jemalloc_internal_inlines_c.h @ 261] 1c 00000088`377ff8d0 00007ff6`9ae88bf1     jemalloc!je_malloc+0x1b [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2747] 1d 00000088`377ff900 00007ffd`c1c3dbe7     test_try!AllocFreeThreadProc_JeMallocHeapFree+0x111 [C:\Developer\mchisholm\test_try\test_try\test_try.cpp @ 415] 1e 00000088`377ffdb0 00007ffd`c30c5a6c     kernel32!BaseThreadInitThunk+0x17 [clientcore\base\win32\client\thread.c @ 77] 1f 00000088`377ffde0 00000000`00000000     ntdll!RtlUserThreadStart+0x2c [minkernel\ldr\rtlstrt.c @ 1184]`

**Comment by gugavaro** [comment]
let me know what details you need and i will add here

**Comment by interwq** [comment]
Crashes along these path are most certainly caused by application level heap corruptions, e.g. double frees, corrupted pointers etc. Best way to debug is ASAN.

Another thing to check is whether there's mixed allocator usage (e.g. allocate from the system allocator but free to jemalloc).

**Comment by gugavaro** [comment]
@interwq even during allocation i am getting crashes

![image](https://github.com/user-attachments/assets/429aa184-cf3e-41a1-991a-e3098e3aaaa9)

![image](https://github.com/user-attachments/assets/27bf2917-d543-4bbb-92a0-7b104cd7967a)

![image](https://github.com/user-attachments/assets/5e9685f4-09ff-473a-8a85-71463f081f5e)

![image](https://github.com/user-attachments/assets/7e6cc977-a5cb-4c2d-b79e-f6f8656931f0)
