### ISSUE TITLE
Crash hapenning: FAILURE_BUCKET_ID:  INVALID_POINTER_WRITE_c0000005_jemalloc.dll!ehooks_default_zero_impl  

### ISSUE THREAD

**Issue by gugavaro** [jemalloc/jemalloc#2722]
callstack:

`# Child-SP          RetAddr               Call Site00 000000eb`51cfd768 00007ffd`c06533a3     ntdll!ZwWaitForMultipleObjects+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 964] 01 000000eb`51cfd770 00007ffd`c0653271     KERNELBASE!WaitForMultipleObjectsEx+0x123 [minkernel\kernelbase\synch.c @ 1551] 02 000000eb`51cfda60 00007ffd`c1c60e20     KERNELBASE!WaitForMultipleObjects+0x11 [minkernel\kernelbase\synch.c @ 1403] 03 000000eb`51cfdaa0 00007ffd`c1c889cd     kernel32!WerpReportFaultInternal+0x62c [onecore\windows\feedback\core\faultrep\lib\faultrep.cpp @ 1073] 04 000000eb`51cfdc20 00007ffd`c071eabc     kernel32!WerpReportFault+0xc5 [onecore\windows\feedback\core\faultrep\lib\faultrep.cpp @ 1384] 05 000000eb`51cfdc70 00007ffd`c31a7e4a     KERNELBASE!UnhandledExceptionFilter+0x34c [minkernel\kernelbase\xcpt.c @ 701] 06 (Inline Function) --------`--------     ntdll!RtlpThreadExceptionFilter+0x2e [minkernel\ldr\rtlstrt.c @ 958] 07 000000eb`51cfdd60 00007ffd`c3163ef3     ntdll!RtlUserThreadStart$filt$0+0x3f [minkernel\ldr\rtlstrt.c @ 1185] 08 000000eb`51cfdd90 00007ffd`c31a353f     ntdll!__C_specific_handler+0x93 [minkernel\crts\crtw32\misc\riscchandler.c @ 446] 09 000000eb`51cfde00 00007ffd`c305f358     ntdll!RtlpExecuteHandlerForException+0xf [minkernel\ntos\rtl\amd64\xcptmisc.asm @ 132] 0a 000000eb`51cfde30 00007ffd`c31a2e7e     ntdll!RtlDispatchException+0x2c8 [minkernel\ntos\rtl\amd64\exdsptch.c @ 680] 0b 000000eb`51cfe580 00007ffc`f11b03e0     ntdll!KiUserExceptionDispatch+0x2e [minkernel\ntos\rtl\amd64\trampoln.asm @ 771] 0c 000000eb`51cfeca8 00007ffc`e7f92e4a     VCRUNTIME140D!memset+0x130 [D:\a\_work\1\s\src\vctools\crt\vcruntime\src\string\amd64\memset.asm @ 270] 0d 000000eb`51cfecb0 00007ffc`e7fa1555     jemalloc!ehooks_default_zero_impl+0x4a [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\ehooks.c @ 243] 0e 000000eb`51cfecf0 00007ffc`e7fa40fe     jemalloc!ehooks_zero+0x45 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\ehooks.h @ 370] 0f 000000eb`51cfed30 00007ffc`e7fa50ab     jemalloc!extent_commit_zero+0xfe [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\extent.c @ 1312] 10 000000eb`51cfed90 00007ffc`e7fa2960     jemalloc!extent_recycle+0x28b [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\extent.c @ 621] 11 000000eb`51cfee00 00007ffc`e7fd5e59     jemalloc!ecache_alloc+0x150 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\extent.c @ 87] 12 000000eb`51cfee90 00007ffc`e7fd56c4     jemalloc!pac_alloc_real+0xc9 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\pac.c @ 116] 13 000000eb`51cfef00 00007ffc`e7fcf56f     jemalloc!pac_alloc_impl+0x94 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\pac.c @ 178] 14 000000eb`51cfef70 00007ffc`e7fcfcd3     jemalloc!pai_alloc+0x5f [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\pai.h @ 45] 15 000000eb`51cfefc0 00007ffc`e7f2d98a     jemalloc!pa_alloc+0x153 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\pa.c @ 139] 16 000000eb`51cff020 00007ffc`e7fc3822     jemalloc!arena_extent_alloc_large+0xea [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\arena.c @ 338] 17 000000eb`51cff0b0 00007ffc`e7f2ebc2     jemalloc!large_palloc+0x102 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\large.c @ 37] 18 000000eb`51cff110 00007ffc`e8041719     jemalloc!arena_palloc+0x152 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\arena.c @ 1230] 19 000000eb`51cff170 00007ffc`e803f4b8     jemalloc!ipallocztm+0x199 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\jemalloc_internal_inlines_c.h @ 80] 1a 000000eb`51cff1c0 00007ffc`e803f62a     jemalloc!tsd_tcache_data_init+0xf8 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 717] 1b 000000eb`51cff250 00007ffc`e804d1a4     jemalloc!tsd_tcache_enabled_data_init+0x3a [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tcache.c @ 644] 1c 000000eb`51cff280 00007ffc`e804ae20     jemalloc!tsd_data_init+0x44 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tsd.c @ 245] 1d 000000eb`51cff2b0 00007ffc`e804c730     jemalloc!tsd_fetch_slow+0xe0 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tsd.c @ 297] 1e 000000eb`51cff2f0 00007ffc`e804c7af     jemalloc!tsd_fetch_impl+0xa0 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\tsd.h @ 422] 1f 000000eb`51cff330 00007ffc`e804ac40     jemalloc!tsd_fetch+0xf [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\tsd.h @ 449] 20 000000eb`51cff360 00007ffc`e7f127f3     jemalloc!malloc_tsd_boot1+0x10 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\tsd.c @ 453] 21 000000eb`51cff3a0 00007ffc`e7f128d7     jemalloc!malloc_init_hard+0x1b3 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2167] 22 000000eb`51cff3e0 00007ffc`e7f1c940     jemalloc!malloc_init+0x17 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 298] 23 000000eb`51cff410 00007ffc`e7f1c9ca     jemalloc!imalloc_init_check+0x20 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2658] 24 000000eb`51cff440 00007ffc`e7f07b70     jemalloc!imalloc+0x2a [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2676] 25 000000eb`51cff480 00007ffc`e7f11216     jemalloc!malloc_default+0xa0 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2727] 26 000000eb`51cff5a0 00007ffc`e7f02b9b     jemalloc!imalloc_fastpath+0xf6 [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\include\jemalloc\internal\jemalloc_internal_inlines_c.h @ 261] 27 000000eb`51cff690 00007ff6`9ae88bf1     jemalloc!je_malloc+0x1b [C:\Users\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\jemalloc.c @ 2747] 28 000000eb`51cff6c0 00007ffd`c1c3dbe7     test_try!AllocFreeThreadProc_JeMallocHeapFree+0x111 [C:\Developer\mchisholm\test_try\test_try\test_try.cpp @ 415] 29 000000eb`51cffb70 00007ffd`c30c5a6c     kernel32!BaseThreadInitThunk+0x17 [clientcore\base\win32\client\thread.c @ 77] 2a 000000eb`51cffba0 00000000`00000000     ntdll!RtlUserThreadStart+0x2c [minkernel\ldr\rtlstrt.c @ 1184]`

**Comment by interwq** [comment]
See reply in #2721.
