### ISSUE TITLE
Crashing during allocation

### ISSUE THREAD

**Issue by gugavaro** [jemalloc/jemalloc#2724]
Info from Crash Dump

ExceptionAddress: 00007ffd87aa03e0 (VCRUNTIME140D!memset+0x0000000000000130)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000001
   Parameter[1]: 00000240cad80020
Attempt to write to address 00000240cad80020

WRITE_ADDRESS:  00000240cad80020 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000001

EXCEPTION_PARAMETER2:  00000240cad80020

STACK_TEXT:  
000000f1`d44fec48 00007ffc`e5782e4a     : 00000240`cad80000 00000000`00008000 00000240`cb0000c8 00007ffc`00000001 : VCRUNTIME140D!memset+0x130
000000f1`d44fec50 00007ffc`e5791555     : 00000240`cad80000 00000000`00008000 000000f1`d44fee20 00007ffc`e578f7a8 : jemalloc!ehooks_default_zero_impl+0x4a
000000f1`d44fec90 00007ffc`e57940fe     : 00000240`cad60c08 00000240`cb0000c0 00000240`cad80000 00000000`00008000 : jemalloc!ehooks_zero+0x45
000000f1`d44fecd0 00007ffc`e57950ab     : 00000240`cad60c08 00000240`cb0000c0 00000240`cb016080 00000240`cb003a01 : jemalloc!extent_commit_zero+0xfe
000000f1`d44fed30 00007ffc`e5792960     : 00000240`cad60c08 00000240`cb0039f0 00000240`cb0000c0 00000240`cb003a28 : jemalloc!extent_recycle+0x28b
000000f1`d44feda0 00007ffc`e57c5e59     : 00000240`cad60c08 00000240`cb0039f0 00000240`cb0000c0 00000240`cb003a28 : jemalloc!ecache_alloc+0x150
000000f1`d44fee30 00007ffc`e57c56c4     : 00000240`cad60c08 00000240`cb0039f0 00000240`cb0000c0 00000000`00008000 : jemalloc!pac_alloc_real+0xc9
000000f1`d44feea0 00007ffc`e57bf56f     : 00000240`cad60c08 00000240`cb0039f0 00000000`00008000 00000000`00001000 : jemalloc!pac_alloc_impl+0x94
000000f1`d44fef10 00007ffc`e57bfcd3     : 00000240`cad60c08 00000240`cb0039f0 00000000`00008000 00000000`00001000 : jemalloc!pai_alloc+0x5f
000000f1`d44fef60 00007ffc`e571d98a     : 00000240`cad60c08 00000240`cb0039d8 00000000`00008000 00000000`00001000 : jemalloc!pa_alloc+0x153
000000f1`d44fefc0 00007ffc`e57b3822     : 00000240`cad60c08 00000240`cb001080 00000000`00007000 00000000`00001000 : jemalloc!arena_extent_alloc_large+0xea
000000f1`d44ff050 00007ffc`e571ebc2     : 00000240`cad60c08 00000240`cb001080 00000000`00007000 00000000`00001000 : jemalloc!large_palloc+0x102
000000f1`d44ff0b0 00007ffc`e5831719     : 00000240`cad60c08 00000240`cb001080 00000000`00007000 00000000`00001000 : jemalloc!arena_palloc+0x152
000000f1`d44ff110 00007ffc`e582f4b8     : 00000240`cad60c08 00000000`00007000 00000000`00001000 00000240`cad60c01 : jemalloc!ipallocztm+0x199
000000f1`d44ff160 00007ffc`e582f62a     : 00000240`cad60c08 00000240`cad60e01 00000240`cad60c08 00000240`cad60f28 : jemalloc!tsd_tcache_data_init+0xf8
000000f1`d44ff1f0 00007ffc`e583d1a4     : 00000240`cad60c08 cccccccc`cccccccc cccccccc`cccc0100 000000f1`d44ff530 : jemalloc!tsd_tcache_enabled_data_init+0x3a
000000f1`d44ff220 00007ffc`e583ae20     : 00000240`cad60c08 00000000`00000000 00000000`00000000 00000000`00000000 : jemalloc!tsd_data_init+0x44
000000f1`d44ff250 00007ffc`e583c730     : 00000240`cad60c08 00000000`00000000 00000000`00000000 00000000`00000000 : jemalloc!tsd_fetch_slow+0xe0
000000f1`d44ff290 00007ffc`e583c7af     : 0000ef64`3ab96701 cccccccc`cccccc00 cccccccc`cccccccc 000000f1`d44ff530 : jemalloc!tsd_fetch_impl+0xa0
000000f1`d44ff2d0 00007ffc`e583ac40     : 000000f1`d44ff530 00007ffc`e56f9296 00007ffc`e592ba10 00000000`00000000 : jemalloc!tsd_fetch+0xf
000000f1`d44ff300 00007ffc`e57027f3     : 00007ffc`e592ba10 00007ffc`e59360d0 00007ffc`e6a1a300 00000240`cabb8bc0 : jemalloc!malloc_tsd_boot1+0x10
000000f1`d44ff340 00007ffc`e57028d7     : 00007ff6`9c138071 000000f1`d44ff5e5 00000000`00000000 00007ff6`9c1229f8 : jemalloc!malloc_init_hard+0x1b3
000000f1`d44ff380 00007ffc`e570c940     : 00000000`00002800 000000f1`6c078965 00000000`00000000 cccccccc`00000000 : jemalloc!malloc_init+0x17
000000f1`d44ff3b0 00007ffc`e570c9ca     : 000000f1`d44ff468 000000f1`d44ff4a8 cccccccc`cccccccc 00007ffc`e68a037f : jemalloc!imalloc_init_check+0x20
000000f1`d44ff3e0 00007ffc`e56f7b70     : 000000f1`d44ff468 000000f1`d44ff4a8 00000000`00000004 cccccccc`00000001 : jemalloc!imalloc+0x2a
000000f1`d44ff420 00007ffc`e5701216     : 00000000`000022d7 cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc : jemalloc!malloc_default+0xa0
000000f1`d44ff540 00007ffc`e56f2b9b     : 00000000`000022d7 00007ffc`e56f1b22 00007ff6`9c1380df 000000f1`d44ff858 : jemalloc!imalloc_fastpath+0xf6
000000f1`d44ff630 00007ff6`9c1260a5     : 00000000`000022d7 000000f1`d44ff948 0000c10d`00000330 000000f1`d44ff690 : jemalloc!je_malloc+0x1b
000000f1`d44ff660 00007ff6`9c1248ac     : 00007ff6`00001450 00007ff6`0012d687 00007ff6`00000400 00000000`00002800 : martinc_try!AllocFreeThreadProc_JeMallocHeapFree+0xb5
000000f1`d44ff930 00007ff6`9c123b43     : 00000240`caba0950 00000240`caba094c 00000240`caba0948 00000240`caba0944 : martinc_try!std::invoke<unsigned long (__cdecl*)(int,int,int,int),unsigned long,unsigned long,unsigned long,unsigned long>+0x6c
000000f1`d44ffa40 00007ffc`e68c3010     : 00000240`caba0940 00000000`00000000 00000000`00000000 00000000`00000000 : martinc_try!std::thread::_Invoke<std::tuple<unsigned long (__cdecl*)(int,int,int,int),unsigned long,unsigned long,unsigned long,unsigned long>,0,1,2,3,4>+0xf3
000000f1`d44ffbe0 00007ffd`c1c3dbe7     : 00000240`caba5a60 00000000`00000000 00000000`00000000 00000000`00000000 : ucrtbased!thread_start<unsigned int (__cdecl*)(void *),1>+0xb0
000000f1`d44ffc40 00007ffd`c30c5a6c     : 00000000`00000000 00000000`00000000 000004f0`fffffb30 000004d0`fffffb30 : kernel32!BaseThreadInitThunk+0x17
000000f1`d44ffc70 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x2c

STACK_COMMAND:  ~4s; .ecxr ; kb

FAULTING_SOURCE_LINE:  C:\Users\gustavovaro\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\ehooks.c

FAULTING_SOURCE_FILE:  C:\Users\gustavovaro\source\repos\vcpkg\buildtrees\jemalloc\src\59c56fa90c-b7343129b8.clean\src\ehooks.c

FAULTING_SOURCE_LINE_NUMBER:  243

FAULTING_SOURCE_CODE:  
   239: 	if (opt_thp != thp_mode_always) {
   240: 		needs_memset = pages_purge_forced(addr, size);
   241: 	}
   242: 	if (needs_memset) {
>  243: 		memset(addr, 0, size);
   244: 	}
   245: }
   246: 
   247: void
   248: ehooks_default_guard_impl(void *guard1, void *guard2) {

SYMBOL_NAME:  jemalloc!ehooks_default_zero_impl+4a

MODULE_NAME: jemalloc

IMAGE_NAME:  jemalloc.dll

FAILURE_BUCKET_ID:  INVALID_POINTER_WRITE_c0000005_jemalloc.dll!ehooks_default_zero_impl

OS_VERSION:  10.0.26100.1

BUILDLAB_STR:  ge_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {020b7ab7-9369-94f0-3b73-b65fae62b724}

let me know if you need any other info.

**Comment by interwq** [comment]
Please don't create multiple new issues. The suggestion in #2721 still applies. Try ASAN first for any heap corruption bugs, and then your config and setup.

**Comment by gugavaro** [comment]
@interwq I already enable ASAN and nothing that would help us.
