### ISSUE TITLE
jemalloc is thread un-safe on the first call.

### ISSUE THREAD

**Issue by gugavaro** [jemalloc/jemalloc#2725]
The first allocation must happen in a thread-safe manner.

I am able to repro the issue running this code on windows.

`#include < jemalloc/jemalloc.h>
#include < iostream>
#include < vector>
#include < thread>
#include < chrono>
#include < list>
#include < random>

const size_t INITIAL_SIZE = 5200;
const size_t BUFFER_COUNT = 1234567;
const int THREAD_COUNT = 6;
const size_t MIN_ALLOC = 1024;
const size_t MAX_ALLOC = 10240;

int MyRand(const int& min, const int& max)
{
    static thread_local std::mt19937* generator = nullptr;
    if (!generator)
        generator = new std::mt19937(
            clock() + static_cast<int>(std::hash<std::thread::id>{}(std::this_thread::get_id())));
    std::uniform_int_distribution<int> distribution(min, max);
    return distribution(*generator);
}

int main() {
    //void* initial = je_malloc(INITIAL_SIZE);

    std::vector<std::thread> threads;
    for (int i = 0; i < THREAD_COUNT; ++i) {
        threads.emplace_back([]() {
            std::list<unsigned char*> listBuffers;

            for (int i = 0; i < INITIAL_SIZE; ++i)
            {
                const size_t nBytes = MyRand(MIN_ALLOC, MAX_ALLOC);
                auto pointer = static_cast<unsigned char*>(je_malloc(nBytes));

                listBuffers.push_back(pointer);
            }

            for (size_t i = 0; i < BUFFER_COUNT; ++i)
            {
                if (i % 2 == 0)
                {
                    const size_t nBytes = MyRand(MIN_ALLOC, MAX_ALLOC);
                    auto pointer = static_cast<unsigned char*>(je_malloc(nBytes));
                    listBuffers.push_back(pointer);
                }
                else
                {
                    auto pointer = listBuffers.front();
                    je_free(pointer);
                    listBuffers.pop_front();
                }
            }

            for (auto pointer : listBuffers)
            {
                je_free(pointer);
            }
        });
    }

    for (auto& t : threads) {
        t.join();
    }

    //je_free(initial);
    std::cout << "Test complete!" << std::endl;
    return 0;
}

if I uncomment the lines:
void* initial = je_malloc(INITIAL_SIZE);
je_free(initial);

it works great!

`

**Comment by interwq** [comment]
> if I uncomment the lines:
void* initial = je_malloc(INITIAL_SIZE);
je_free(initial);
it works great!

How does this pointing to a thread unsafe of first call issue? Correlation does not mean causation. The first call is covered by the malloc_init lock which isn't hard to discover: https://github.com/jemalloc/jemalloc/blob/4f4fd424477142ee9962fcf4e4cd0349d4e6e4d3/src/jemalloc.c#L2210

@gugavaro the issues you created are not helping either side. Please do your due diligence before assuming it's a memory allocator problem.

**Comment by gugavaro** [comment]
it is a very simple program. and works one way vs don't the other way.
The usage of jemalloc should just works, like I said it is a very simple program. I should not need to spend a lot of time to have it working.

@interwq keep I don't understand why you are so eager to close the issues right away. Perhaps someone else should be working with the community to triage the issues as it seems you are not willing to even take a look on the issues.

**Comment by gugavaro** [comment]
@jasone , @davidtgoldblatt is there anyone who could take a look on this piece of code and could give a better explanation how a simple piece of code is crashing if first allocation is thread-unsafe?
