### ISSUE TITLE
Q: How to reduce overhead costs when using jemalloc with profiling enabled

### ISSUE THREAD

**Issue by angelskieglazki** [jemalloc/jemalloc#2734]
Hi,
I'm trying to debug a logical memory leak on my server. Somewhere some container is not being cleaned up or something like that. I configured the jemalloc with this flags:

`./configure --enable-prof --enable-prof-libunwind --with-install-suffix="-prof"`

and run my application:

`MALLOC_CONF=prof:true,prof_leak:true,lg_prof_sample:0,prof_final:true,prof_prefix:jeprog-server ./server`

I noticed that the memory usage has increased quite a bit. When the app is built with the system allocator(malloc) or with jemallock without profiling enabled it uses about 300mb of ram at startup, but when I build it with jemallock with profiling enabled it starts using about 2gb.

I want to try to run the server with profiling enabled in a production environment, but I have limited memory there. I'm probably doing something wrong, tell me how to fix it

regards, max

**Comment by interwq** [comment]
> lg_prof_sample:0

This will force jemalloc to record every single allocations, and for sure will introduce high CPU & memory overhead. Heap profiling is designed to be sample based. The default rate is one record every 2^19=512K (lg_prof_sample:19) of allocations.

Closing but feel free to ask questions.

**Comment by angelskieglazki** [comment]
> > lg_prof_sample:0
> 
> This will force jemalloc to record every single allocations, and for sure will introduce high CPU & memory overhead. Heap profiling is designed to be sample based. The default rate is one record every 2^19=512K (lg_prof_sample:19) of allocations.
> 
> Closing but feel free to ask questions.

thank you!
