### ISSUE TITLE
Issue under "old" Linux distros due to gettid() not being implemented in glibc before v2.30

### ISSUE THREAD

**Issue by vldevel** [jemalloc/jemalloc#2740]
I encountered an issue when linking jemalloc to a program built under an "old" Linux distro (I use 4-5 years old build systems so that my program can run under all current distros in use).

The problem stems from the use of the gettid() function introduced by commit edc1576f03d15a22b968828b68a074d9be6e5cc0

This function is not available in glibc versions prior to v2.30 and the corresponding code therefore needs to be amended or disabled when built on system with older glibc versions.

As a quick workaround for this issue, and seeing as this new code only affects profiling, I simply patched src/prof_stack_range.c at line 7 to read:
`#if defined (__linux__) && (__GLIBC_MAJOR__ > 2 || __GLIBC_MINOR__ >= 30)`
However, you might want to implement a better fix...

**Comment by sharkcz** [comment]
for example RHEL-8 which is supported until 2029 is affected
