### ISSUE TITLE
Could prof.dump be told to dump only a particular arena?

### ISSUE THREAD

**Issue by rohansuri** [jemalloc/jemalloc#2744]
Hello,
Thank you for the wonderful allocator. Also appreciate how easy jemalloc makes it to get a heap profile using the prof.dump option. 
I wanted to know if there's a way to dump the heap profile only for a particular arena?

**Comment by guangli-dai** [comment]
No. Profiling can be enabled but inactive at the beginning and toggled on during the execution. In that way, the profile dumped can be for certain time period. It can also be used with new threads: https://jemalloc.net/jemalloc.3.html#:~:text=enable%2Dprof%5D-,Initial,-setting%20for%20thread. Hope that helps.

**Comment by rohansuri** [comment]
Thanks!
