### ISSUE TITLE
malloc(3) manpage is illegible on 11-CURRENT in the section describing chunk allocation functions, etc

### ISSUE THREAD

**Issue by yaneurabeya** [jemalloc/jemalloc#276]
The following is a direct copy of malloc(3) on my FreeBSD 11-CURRENT box (the last time I installed was late May/early June, but this should still hold true today)

<pre>
           A chunk allocation function conforms to the chunk_alloc_t type and
                                                                              upon
                                                                              success
                                                                              returns
                                                                              a
                                                                              pointer
                                                                              to
                                                                              size
                                                                              bytes
                                                                              of
                                                                              mapped
                                                                              memory
...
</pre>

The mandoc markup's pretty messed up :(.

**Comment by jasone** [comment]
This has something to do with how ```man``` is configured on FreeBSD, but I haven't had time to dig into it.  If you run this command, formatting works as expected:

  ```zcat /usr/share/man/man3/jemalloc.3.gz |nroff -man -t |less```

**Comment by jasone** [comment]
I spent several hours trying to get to the bottom of this, but I found no perfect solution.  One thing I tried was to preprocess the man page by running it through the tbl macro processor, but that introduced other undesirable artifacts.  This is something that a FreeBSD docs expert needs to look at.

**Comment by jasone** [comment]
This issue no longer exists, presumably due to some docs infrastructure changes in FreeBSD.
