### ISSUE TITLE
not_reached() code reached in some corner case

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#283]
This is happening while running Firefox unit tests with debug enabled in jemalloc, where `not_reached()` would crash. The `not_reached()` code that is being reached is the one from `tsd_cleanup` in `src/tsd.c`.

What is happening is the following:
- Some thread has allocated memory, so its associated tsd is initialized.
- At the end of the thread execution, `tsd_cleanup` is called a certain number of times, along with `pthread_setspecific`, which triggers other `tsd_cleanup` calls, which is the expected behavior.
- NPTL finishes all the cleanup from tsd data in `__nptl_deallocate_tsd`. By the end of that function, the `pthread` struct for the current thread has `specific_used` set to `false` and `specific_1stblock`, which contains the tsd data (the jemalloc tsd data is initialized early enough that its data ends up stored there) is also emptied out.
- After all the above, free() ends up being called from `__free_tcb` through `__deallocate_stack`, `__free_stacks` and `dl_deallocate_tls`.
- `free`, in turn, calls `tsd_set`, which calls `pthread_setspecific` again, so the `pthread` struct for the current thread now has tsd data again, but tsd_cleanup is never going to be called for that.
- The thread is destroyed.
- Another thread starts, and happens to get the memory address of the `pthread` struct from that previous thread, and thus starts out with a `pthread` struct with `specific_used` and `specific_1stblock` initialized because of that last `pthread_setspecific` (NPTL assumes its cleanup from `__nptl_deallocate_tsd` was enough, which is fair enough). Fortunately, the value is a pointer to the jemalloc tsd thread local address, which happens to be correct, but the data there is reinitialized, so we have an inconsistent state where the jemalloc tsd itself is marked uninitialized, but NPTL thinks it is initialized. That is not a problem is most cases but...
- This new thread ends without doing any allocation, so tsd_get is never called, and the tsd is never initialized.
- `tsd_cleanup` ends up being called because NPTL thinks it is initialized, and since the content of the jemalloc tsd says it is uninitialized, we end up in the branch that says `not_reached`.

The safe workaround, I'd say, would be add a dummy case for `tsd_state_uninitialized`.

**Comment by jasone** [comment]
Wow.  Ow.
