### ISSUE TITLE
jemalloc_constructor blocks in OpenBSD when linking pthread before jemalloc

### ISSUE THREAD

**Issue by equalsraf** [jemalloc/jemalloc#289]
While using jemalloc in OpenBSD(-current amd64) I came across a binary that blocks on start in the jemalloc initialization code, in calls to `sched_yield()` - but this only happens when if against pthread before jemalloc. I have not digged in deep enough to figure out the full issue behind it, and maybe I just tripped into unexpected behaviour, but its probably worth documenting.

First seen in neovim/neovim#3434, a minimal example to reproduce is
```C
/** 
 * This will generate a program that locks
 *    cc -L/home/raf/Code/neovim/.deps/usr/lib -lpthread -ljemalloc test_jemalloc.c
 * But either one of these is fine
 *    cc -L/home/raf/Code/neovim/.deps/usr/lib -ljemalloc -lpthread test_jemalloc.c
 *    cc -L/home/raf/Code/neovim/.deps/usr/lib -pthread -ljemalloc test_jemalloc.c
*/
int main(void)
{
    return 0;
}
```

Here is a gdb trace. I also have a full [ktrace](https://gist.github.com/anonymous/dd2a6c2252ead21f4c50) from my first test, it seems to be in a loop calling `sched_yield()`.

```gdb
#0  0x00001efa611309da in sched_yield () at <stdin>:2
#1  0x00001efa7d0caa45 in _spinlock (lock=0x1efa7d4d28d4) at /usr/src/lib/librthread/rthread.c:82
#2  0x00001efa7d0ce06e in _rthread_mutex_lock (mutexp=0x1ef820acb468, trywait=0, abstime=0x0)
    at /usr/src/lib/librthread/rthread_sync.c:98
#3  0x00001ef8205ffc40 in malloc_init_hard () at mutex.h:85
#4  0x00001ef82060726f in calloc (num=1, size=48) at src/jemalloc.c:285
#5  0x00001efa7d0cdf4b in pthread_mutex_init (mutexp=0x1ef820acb468, attr=0x0) at /usr/src/lib/librthread/rthread_sync.c:44
#6  0x00001efa7d0ce083 in _rthread_mutex_lock (mutexp=0x1ef820acb468, trywait=0, abstime=0x0)
    at /usr/src/lib/librthread/rthread_sync.c:100
#7  0x00001ef8205ffc40 in malloc_init_hard () at mutex.h:85
#8  0x00001ef820600cb7 in jemalloc_constructor () at src/jemalloc.c:285
#9  0x00001ef8204340ce in __register_frame_info () from /home/raf/neovim/build/bin/nvim
#10 0x00001ef8204341b6 in atexit () from /home/raf/neovim/build/bin/nvim
#11 0x00001ef820432ea9 in __init () from /home/raf/neovim/build/bin/nvim
#12 0x0000000000000000 in ?? ()
```

Some extra info

- I was linking against a static libjemalloc.a (built by Neovim) but I can reproduce with a dynamic .so too
- Tested with versions 4.0.2 and 4.0.3
- Both with  gcc and clang.
- Using [-pthread](http://marc.info/?t=123479154600001&r=1&w=2) is likely the same as moving `-lpthread` to last. This seems to be the "right" way to link against pthread in OpenBSD
- There was a similar [bug in openbsd](http://openbsd-archive.7691.n7.nabble.com/process-stuck-in-a-sched-yield-loop-td270329.html) from a while back, but it seems unrelated and I believe it was already [fixed](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/librthread/rthread_fork.c.diff?r1=1.11&r2=1.12&f=h)

**Comment by jasone** [comment]
This is due to recursive allocation during bootstrapping, specifically due to mutex initialization.  See FreeBSD's libc for a way to resolve this issue.
