### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [jemalloc/jemalloc#292]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/jemalloc/jemalloc/blob/345c1b0eeeac333c3da8baa46e9b96c3b2aca443/configure.ac#L1180 "Configuration checks")?

**Comment by jasone** [comment]
I don't want to depend on a third-party autoconf macro, because it's unlikely that such macros perfectly fit.  In this case, a quick search indicates others have had to fork ```AX_PTHREAD```, which isn't a good sign that such a change would be net positive in the context of jemalloc.
