### ISSUE TITLE
sized realloc

### ISSUE THREAD

**Issue by stepancheg** [jemalloc/jemalloc#298]
AFAIU, there are no
* sized realloc function
* realloc function which accepts a parameter with amount of used data to memcpy (when 2M allocated, and only 1M is used, and reallocating to 3M, no need to copy whole 2M inside jemalloc).

So, requesting a function like:

```
void* je_srallocx(void *ptr, size_t old_size, size_t used_size, size_t size, int flags);
```

* `old_size` parameter can be used to avoid call to `isalloc`
* `used_size` is a parameter to be passed to `memcpy` (in the most cases it will be equal to `old_size`)

**Comment by jasone** [comment]
Reallocation is complicated/expensive enough that the internal size lookup is inconsequential; in fact the metadata have to be updated anyway if in-place reallocation succeeds, so there's no cache miss benefit except in the slow path.

Re: ```used_size```, we already have ```xallocx()``` to support its intended purpose.  Yes, this requires two calls instead of just one, but if the over-copying is so expensive that we care about this optimization, then ```xallocx()``` followed by either (in practice) ```rallocx()``` or (rarely due to ```xallocx()``` failure) ```mallocx(); [copy]; dallocx()``` is an acceptable approximation of ```srallocx()```.

**Comment by stepancheg** [comment]
`realloc` must not be much more expensive than `free`. It so, why having sized `free` is profitable, and having sized `realloc` is not?

**Comment by jasone** [comment]
```realloc()``` is in the fastest case a no-op, but for more practical uses it requires either a move (similar cost to ```malloc(); memcpy(); free();```) for small size classes or a page run expansion/contraction for large size classes.  Only the in-place large and huge size class cases are particularly compelling for ```realloc()```, and these compelling cases necessitate modifying the metadata that ```sdallocx()``` avoids reading.  In other words, ```srallocx()``` would only speed up slow paths.

**Comment by stepancheg** [comment]
I did naive perf test. `srallocx` works about 5% faster than `rallocx`. The test is:

```
#include <stdio.h>
#include <sys/time.h>
#include <errno.h>
#include <jemalloc/jemalloc.h>

long long microseconds() {
    struct timeval tv;
    if (gettimeofday(&tv, NULL) < 0) {
        perror("gettimeofday");
        exit(1);
    }
    return tv.tv_sec * 1000000LL + tv.tv_usec;
}

int main(void) {
    long long start = microseconds();
    for (int i = 0; i < 100000000; ++i) {
        size_t old_size = 100 + i % 100;
        size_t new_size = 200 + i % 200;
        size_t used_size = old_size / 2;
        void* m = je_mallocx(old_size, 0);
        //m = je_rallocx(m, new_size, 0);
        m = je_srallocx(m, old_size, old_size, new_size, 0);
        //m = je_srallocx(m, old_size, used_size, new_size, 0);
        je_dallocx(m, 0);
    }
    long long d = microseconds() - start;
    printf("%lld\n", d);
    return 0;
}

// vim: set ts=4 sw=4 et:
```

Do you think 5% is not large enough? Or did I measure wrong?

**Comment by stepancheg** [comment]
Actually, 5% is a speedup of a whole test. Speedup of realloc should be about 10%.

**Comment by jasone** [comment]
I remain of the opinion that the extra complexity/maintenance/size cost this change incurs is not worthwhile, because reallocation is not as performance-critical as allocation/deallocation.  Closing.
