### ISSUE TITLE
jemalloc and java application

### ISSUE THREAD

**Issue by sith** [jemalloc/jemalloc#304]
Hi

I am trying to do native profiling on my java application and I faced multiple problems.

The documentation for this tool says I have to set LD_PRELOAD env variable - LD_PRELOAD=${JEMALLOC_PATH}/lib/libjemalloc.so.1 app

What is 'app' here? Is it the full path to my app? Something like /usr/bin/java ? Or is it just label?
Do you have rpm package for the latest build? Is it possible to create one?

We tried to install tool from source but it needs ./configure executable and we didn't find it.  We also tried to use autoconfig option but it requires installation of other packages that is not easy in our case.

Where can we find jeprof tool?
How do I specify path to jeprof.19678.0.f.heap file?

Alex Fedorov

**Comment by evanj** [comment]
App in this case is /usr/bin/java

jeprof should come with jemalloc. If it doesn't come installed with the version on your operating system, you should grab the jemalloc source, run ./configure and make, then use the "jeprof" script that is created by that process. Good luck and hope this helps!
