### ISSUE TITLE
configure script sets version to 0.0.0-0 if within git tree

### ISSUE THREAD

**Issue by strtok** [jemalloc/jemalloc#305]
jemalloc's configure script includes logic to override the VERSION file shipped in the distribution with a version derived from the git working tree if jemalloc's configure script detects that it's within a working tree.

Here's the code in question:
```
if test "x`test ! \"${srcroot}\" && cd \"${srcroot}\"; git rev-parse --is-inside-work-tree 2>/dev/null`" = "xtrue" ; then
        rm -f "${objroot}VERSION"
  for pattern in '[0-9].[0-9].[0-9]' '[0-9].[0-9].[0-9][0-9]' \
                 '[0-9].[0-9][0-9].[0-9]' '[0-9].[0-9][0-9].[0-9][0-9]' \
                 '[0-9][0-9].[0-9].[0-9]' '[0-9][0-9].[0-9].[0-9][0-9]' \
                 '[0-9][0-9].[0-9][0-9].[0-9]' \
                 '[0-9][0-9].[0-9][0-9].[0-9][0-9]'; do
    if test ! -e "${objroot}VERSION" ; then
      (test ! "${srcroot}" && cd "${srcroot}"; git describe --long --abbrev=40 --match="${pattern}") > "${objroot}VERSION.tmp" 2>/dev/null
      if test $? -eq 0 ; then
        mv "${objroot}VERSION.tmp" "${objroot}VERSION"
        break
      fi
    fi
  done
fi
```
This will set the version to 0.0.0-0-g0000000000000000000000000000000000000000, or to something else (given the right pattern) if the pattern match above fails.

It seems like it's common that projects may want to include jemalloc's source within another git repo. Maybe this could be documented better? Or maybe a configure override to force using the version defined in the VERSION file?

**Comment by jasone** [comment]
Would this do the right thing if we simply removed the following?

  ```rm -f "${objroot}VERSION"```

**Comment by jasone** [comment]
See http://www.canonware.com/pipermail/jemalloc-discuss/2015-October/001174.html for an earlier report of this issue.

**Comment by ronawho** [comment]
Is someting like `--with-version=$(cat ${JEMALLOC_DIR}/VERSION)` the recommended way to use the VERSION file when jemalloc is inside another repo, or is there a better/cleaner way?
