### ISSUE TITLE
chunk cache in default allocation hook

### ISSUE THREAD

**Issue by buchgr** [jemalloc/jemalloc#307]
I noticed that the default allocation chunk hook calls `chunk_alloc_core`, which tries to reuse a decommited/purged chunk by calling `chunk_recycle` from  `arena_t.chunks_(sz)ad_retained`, before delegating to `mmap` or `VirtualPageAlloc` or similar. 

When a chunk is decommited/purged it's also inserted into `arena_t.chunks_(sz)ad_retained` using `chunk_record`. However, this is not part of the default decommit or purge chunk hooks.

This is a problem when I want to overwrite the allocation chunk hook. As it basically means that with purging enabled, the virtual memory cached in `arena_t.chunks_(sz)ad_retained` is lost. Purged chunks will be stored there, but I have no means of reusing them.

So I guess I am kindly asking for clarification on two things
* Why was the chunk caching not integrated into jemalloc, but made part of the default allocation chunk hook or phrased differently: why is the default allocation chunk hook not a simple delegate for `page_map`?
* What's the reason for having both `arena_t.chunks_(sz)ad_retained` and ``arena_t.chunks_(sz)ad_cached`? 

Thanks.

**Comment by buchgr** [comment]
Below is a program to demonstrate this. 

We first alloc two 1GB chunks with the default chunk hooks, with a free in between and see that the address gets reused between allocations. We then overwrite the default chunk hooks with a simple call to mmap and see that on two consecutive calls we get two different addresses. We then switch back to the default chunk hooks and get the address of the previous mmap call. This essentially shows that we are leaking virtual memory when not using the default allocation chunk hook.

```C++
#include <iostream>
#include <jemalloc/jemalloc.h>
#include <sys/mman.h>

chunk_hooks_t old_hooks;

void *alloc_default(void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit, unsigned arena_ind);
void *alloc_mmap(void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit, unsigned arena_ind);

int main(int argc, char** argv) {
    size_t size;
    size_t mib[3];
    size_t hooks_len;
    chunk_hooks_t new_hooks;

    size = sizeof(mib) / sizeof(mib[0]);
    mallctlnametomib("arena.0.chunk_hooks", mib, &size);
    mib[1] = 0;
    hooks_len = sizeof(chunk_hooks_t);
    mallctlbymib(mib, size, &old_hooks, &hooks_len, nullptr, 0);

    new_hooks = old_hooks;

    new_hooks.alloc = alloc_default;
    mallctlbymib(mib, size, nullptr, nullptr, &new_hooks, hooks_len);

    void *p;

    std::cout << "default alloc hook" << std::endl;
    p = mallocx(1 << 30, MALLOCX_ARENA(0));
    free(p);
    
    p = mallocx(1 << 30, MALLOCX_ARENA(0));
    free(p);

    std::cout << "overwrite alloc hook" << std::endl;

    new_hooks.alloc = alloc_mmap;
    mallctlbymib(mib, size, nullptr, nullptr, &new_hooks, hooks_len);

    p = mallocx(1 << 30, MALLOCX_ARENA(0));
    free(p);
    
    p = mallocx(1 << 30, MALLOCX_ARENA(0));
    free(p);

    std::cout << "switch back to default alloc hook" << std::endl;
    new_hooks.alloc = alloc_default;
    mallctlbymib(mib, size, nullptr, nullptr, &new_hooks, hooks_len);

    p = mallocx(1 << 30, MALLOCX_ARENA(0));
    free(p);
    
  return 0;
}

void *alloc_default(void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit, unsigned arena_ind) {
  void *p = old_hooks.alloc(new_addr, size, alignment, zero, commit, arena_ind);
  std::cout << p << std::endl;
  return p;
}

void *alloc_mmap(void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit, unsigned arena_ind) {
  void *p = mmap(nullptr, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0); 
  std::cout << p << std::endl;
  return p;
}
```

Example output:
```
default alloc hook
0x7f5137000000
0x7f5137000000
overwrite alloc hook
0x7f50f7000000
0x7f50b7000000
switch back to default alloc hook
0x7f50b7000000
```

Expected output:
```
default alloc hook
0x7f5137000000
0x7f5137000000
overwrite alloc hook
0x7f5137000000
0x7f5137000000
switch back to default alloc hook
0x7f5137000000
```

**Comment by buchgr** [comment]
There is no hurry with this issue, as I have moved on to other stuff, but I just accidentally came across my patch to fix this issue. Just wanted to post it here, it might help someone: https://github.com/buchgr/jemalloc/commit/74891766a92c4aec4634de05a80b45057ebd9f47

**Comment by jasone** [comment]
@buchgr, I just took a look at your patch, and it helped me better understand the issue.  I'll make sure to resolve this before the 4.1.0 release.

**Comment by buchgr** [comment]
@jasone thanks, appreciate it!
