### ISSUE TITLE
Lazy lock may be broken on Windows?

### ISSUE THREAD

**Issue by alexcrichton** [jemalloc/jemalloc#310]
Currently the default for MinGW builds is to enable lazy locking (e.g. `--enable-lazy-lock` to the configure script), but it seems problematic for Windows. The `isthreaded` global variable indicates whether threads are active and locks should be used, but this is only set to `true` on a `DLL_THREAD_ATTACH` event on Windows (unlike on Unix where `pthread_create` is hooked). 

[According to Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682583%28v=vs.85%29.aspx), however, "the call is made in the context of the new thread", and I believe this means that problems can later arise. For example, if thread A uses jemalloc, spawns thread B, then uses jemalloc some more, it could be the case that thread A enters a jemalloc critical section before thread B has used jemalloc, meaning it _doesn't grab a lock_. Later on thread B uses jemalloc, enabling future calls to locking functions. If thread A then exits the critical section, it will attempt to unlock a not-locked mutex, causing the process to abort.

I _think_ this means that lazy locking isn't possible on Windows to do reliably, and perhaps the default for MinGW should be switched back? The default was enabled after #83 was filed in   13473c7 but #83 didn't look like it ever came up with concrete evidence to why lazy locking was at fault, and it looks like a number of initialization changes to mutexes in jemalloc has changed in the meantime, so it's likely that this has been fixed under the hood.

We discovered this when updating Rust to use jemalloc 4.0.0 after a [few](https://github.com/rust-lang/rust/pull/28173) [failed](https://github.com/rust-lang/rust/pull/28304) [attempts](https://github.com/rust-lang/rust/pull/29214) which all seemed to bounce for spurious reasons.
---

Unfortunately I haven't been able to come up with a nice succinct test case to reproduce this. My current threshold is "checkout Rust, update jemalloc, build, run one test 100 times and it'll die at least once". I can try to reduce this down, however, if it would help! I figured I'd try to run the idea of lazy locking by here first though.

**Comment by jasone** [comment]
Enabling lazy locking by default was a workaround, so I support disabling it again, even forcibly disabling it assuming that it cannot work.

**Comment by alexcrichton** [comment]
For us we managed to update to 4.0.x by disabling lazy locking on Windows, and everything since has appeared to be going swimmingly on Windows!

**Comment by rustyx** [comment]
Solving an issue by forcibly enabling a configuration setting (like lazy-lock) is never a good solution.

Lazy-locking should be disabled by default, and #83 should be investigated and fixed properly.

**Comment by strrchr** [comment]
When will this issue be fixed?

**Comment by jasone** [comment]
eee1ca655e348b0602c96b702332c28d53869fff / 07ee4c5ff4c60e8e04eb452e2ef154c47fa118a4 force no lazy-lock on Windows;  583c32c3056bff7606570e7836d33bf8fd18d299 / 1eb801bcad74f4b7eb4d5ab3ce2d67935c10ac58 removed forcing lazy-lock on Windows.
