### ISSUE TITLE
jemalloc crashes on Windows 8 & 10

### ISSUE THREAD

**Issue by xqrzd** [jemalloc/jemalloc#314]
I'm not sure if this a jemalloc, gcc, or Windows bug, but here goes. If I compile jemalloc x64 with the default options (./configure) using MingGW (gcc version 5.3.0 (Rev1, Built by MSYS2 project)), the resulting dll works fine on Windows 7, but causes a segfault on 8 & 10.

Running make check gives this:
```
=== test/unit/atomic ===
test/test.sh: line 22:  1788 Segmentation fault      ${t}.exe /c/jemalloc-4.0.4/ /c/jemalloc-4.0.4/
Test harness error
Makefile:363: recipe for target 'check' failed
make: *** [check] Error 1
```

The problem seems to be related to gcc optimization; if I remove the -O3 flag jemalloc works fine on Windows 8 and 10, and adding -O1 causes it to fail.

The problem seems to be somewhere in initialization; simply calling LoadLibrary("jemalloc.dll") causes the crash.
```
Exception thrown at 0x0000000070E414EA (jemalloc.dll) in Win32Project1.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

Should I be using a different compiler? It seems strange no one else has ran into this, as I've only used the defaults.

**Comment by dimatr** [comment]
The crash during initialization sounds similar to this MinGW [bug](https://sourceforge.net/p/mingw-w64/bugs/395/)   .  jemalloc v 4.0.4 has the mentioned lazy_lock in the [MinGW configure](https://github.com/jemalloc/jemalloc/commit/13473c7c66a81a4dc1cf11a97e9c8b1dbb785b64). Do you see the crash when using the v4.0.4?

**Comment by xqrzd** [comment]
It definitely seems similar to that bug. I am using the latest jemalloc, and the result is the same with/without lazy locking.

I tried rustyx's windows branch and it worked great, so I'll probably just use that. This issue can probably be closed, seeing as the problem only happens with optimization enabled makes me think it's a MingGW bug.

**Comment by jasone** [comment]
Closing under the assumption this is a MinGW bug.  Please reopen if that's not the case.
