### ISSUE TITLE
jemalloc on Windows leaks TSD's

### ISSUE THREAD

**Issue by rustyx** [jemalloc/jemalloc#318]
When built with MSVC 2015 on Windows, jemalloc is leaking TSD's, no matter if I link it statically or as a DLL.

Further analysis shows that the MSC-specific `_tls_callback` is never invoked in Release mode (however is working fine in Debug mode):

```
static BOOL WINAPI
_tls_callback(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{

	switch (fdwReason) {
#ifdef JEMALLOC_LAZY_LOCK
	case DLL_THREAD_ATTACH:
		isthreaded = true;
		break;
#endif
	case DLL_THREAD_DETACH:
		_malloc_thread_cleanup();
		break;
	default:
		break;
	}
	return (true);
}
#ifdef _MSC_VER
#  ifdef _M_IX86
#    pragma comment(linker, "/INCLUDE:__tls_used")
#  else
#    pragma comment(linker, "/INCLUDE:_tls_used")
#  endif
#  pragma section(".CRT$XLY",long,read)
#endif
JEMALLOC_SECTION(".CRT$XLY") JEMALLOC_ATTR(used)
static BOOL	(WINAPI *const tls_callback)(HINSTANCE hinstDLL,
    DWORD fdwReason, LPVOID lpvReserved) = _tls_callback;
#endif
```

My guess is that the `.CRT$XLY` hack isn't working in MSVC 2015.

The only way I could work around this problem was to invoke it manually:

```
#include <jemalloc/jemalloc.h>
#include <jemalloc/internal/jemalloc_internal_defs.h>
extern "C" {
	void _malloc_thread_cleanup(void);
	extern bool je_isthreaded;
}
static thread_local struct JeMallocThreadHelper {
#ifdef JEMALLOC_LAZY_LOCK
	JeMallocThreadHelper() {
		je_isthreaded = true;
	}
#endif
	~JeMallocThreadHelper() {
		_malloc_thread_cleanup();
	}
} tls_jemallocThreadHelper;
```

Note this works only for C++ threads, but was sufficient for me.

Obviously, this is ugly and a better solution is needed.

**Comment by jasone** [comment]
@rustyx, I suggest proactively pulling other people who have shown an interest into Windows portability in to this conversation, so that it doesn't languish.

**Comment by yuslepukhin** [comment]
@jasone @rustyx  This one is fairly easy to fix by fixing the linker directives (both 32 and 64). I can now see it work in a debugger.  Will PR it.

I just discovered another bug in TSD while building jemalloc from a CMake file (I can PR it if there is an interest) on windows and that is the reason why tsd test does not work.

tsd test installs a cleanup handler for its test data structure. Then invokes a test(...) it in turns invokes p_test/jet_nallocs and comes to malloc_init(). That one clears the index ncleanups back to zero and the malloc_tsd_boot then overwrites the data cleanup handler with malloc_tsd_cleanup().

Right now I do not see a way to fix it but I am new to Jemalloc

**Comment by rustyx** [comment]
Pls see above, this is already fixed.
