### ISSUE TITLE
make install Error 71 : /doc/jemalloc.html not exist

### ISSUE THREAD

**Issue by linjunjie** [jemalloc/jemalloc#319]
when I run the "make install", I got this:

```
install: doc/jemalloc.html: No such file or directory
make: *** [install_doc_html] Error 71
```

and I go to the ./doc/ to check , there's no file called jemalloc.html

`html.xsl         html.xsl.in      jemalloc.xml     jemalloc.xml.in  manpages.xsl     manpages.xsl.in  stylesheet.xsl`

**Comment by jasone** [comment]
This happens if you're building from a git checkout rather than from a release tarball.  You need to ```make dist``` before installing.
