### ISSUE TITLE
make dist error too

### ISSUE THREAD

**Issue by linjunjie** [jemalloc/jemalloc#320]
When I run the cmd "make dist", I got below:

```
/usr/bin/xsltproc -o doc/jemalloc.html doc/html.xsl doc/jemalloc.xml
warning: failed to load external entity "/html/docbook.xsl"
compilation error: file doc/html.xsl line 2 element import
xsl:import : unable to load /html/docbook.xsl
make: *** [doc/jemalloc.html] Error 5
```

Am I do something wrong with the make dist?

**Comment by jasone** [comment]
You need to tell the build system where to find xsltroot (or install the appropriate XSL software if it's missing).  Here are the flags I usually pass to ```configure```:

- FreeBSD: ```--with-xslroot=/usr/local/share/xsl/docbook```
- OS X: ```--with-xslroot=/opt/local/share/xsl/docbook-xsl```

**Comment by Napoleon-BlownApart** [comment]
You may need to install:  

    apt-get install libxslt-dev xsltproc docbook-xsl

**Comment by kaixulucky** [comment]
In centos 6.8 I was so solved
[root@localhost jemalloc-4.1.1]# make dist
/usr/bin/xsltproc -o doc/jemalloc.html doc/html.xsl doc/jemalloc.xml
warning: failed to load external entity "/html/docbook.xsl"
compilation error: file doc/html.xsl line 2 element import
xsl:import : unable to load /html/docbook.xsl
make: *** [doc/jemalloc.html] 错误 5
解决方法1：yum -y install docbook-style-xsl
         ./autogen.sh --with-xslroot=/usr/share/sgml/docbook/xsl-stylesheets-1.75.2/
         make dist
         make -j&&make install
