### ISSUE TITLE
Package jemalloc 4.x to Ubuntu/Debian

### ISSUE THREAD

**Issue by thedrow** [jemalloc/jemalloc#326]
So far the latest jemalloc in the Ubuntu repositories is 3.6.x.
Can it be because some dependencies rely on that version?
We can release 4.x with a new package named jemalloc4 if that's the case.
Are you guys responsible for packaging this software? If not, I'll take this issue to where it's relevant.

**Comment by jasone** [comment]
Linux distro packaging is handled by people working on the distros, rather than by the jemalloc project.

**Comment by thedrow** [comment]
:+1: I'll file an issue there.
