### ISSUE TITLE
Performance regression when moving to 4.0.4

### ISSUE THREAD

**Issue by jimwwalker** [jemalloc/jemalloc#332]
Hi,

We (Couchbase) updated our jemalloc library to the 4.0.4 release recently, a later system test has indicated a performance regression with part of our code. I've identified that the cause of the regression was our upgrade of jemalloc.

Previously we were building a library from c002a5c and we updated to 4.0.4 (we've not shipped this to customers yet, it's currently a blocker defect sitting in my queue).

I've tracked down the regression (there's actually a couple of slowdowns) and would like to raise this is an issue to find out if this is expected and to get some guidance on the best course of action (tuning/build options).

The regressions appear to have been triggered from the addition of cache-index randomization but also from changes to the chunk-size.

In my research I can see these 2 commits introduce a speed-bump. Linux perf(1) high-lighted that the lost time was going into page-fault handling (I can share data on that if needed)

- commit 5bd879646cdb303045096fc2b9d75f565313afa8
- commit 8a03cf039cd06f9fa6972711195055d865673966

I've pushed a C++ program that models the part of software which regressed and a script which I used to churn through each jemalloc commit between our release points. Our regression is in some code which is allocating an increasingly sized buffer. There are 4 threads doing the same workload (on their own buffers).

I have a spreadsheet of data-points to share that show some analysis and clearly show the speed bumps. Two sheets are shown:

1. "github test" shows performance data for my simplified test case and one regression point.
2. "couchbase test" shows performance data (95 percentile) from a Couchbase unit test (which is more involved to run, but actually shows the two commits regressing performance).
3. The "couchbase test" also shows what happens when I change chunk size and build with --disable-cache-oblivousness.

Note all tests have "narenas:1" (as does our shipping code).

What's interesting is that "--disable-cache-obliviousness" recovered our performance, however I don't know jemalloc well enough to know that will have some negative impact elsewhere? 

- Spreadsheet https://docs.google.com/spreadsheets/d/1EZpW2JBnRKVh-wRYpR3v_cNtd0Hn7Ecwz-qQa13jUgs/edit?usp=sharing
- Code https://github.com/jimwwalker/jemalloc/commit/e7a213653c3948fdac0c035653056d6b78093cba

Any assistance would be greatly appreciated!

**Comment by jasone** [comment]
Just a few days ago @djwatson noticed that run quantization (part of 8a03cf039cd06f9fa6972711195055d865673966) is a non-trivial overhead for some workloads (see #330).  Whether we use that patch or something similar, we'll reduce run quantization overhead soon.  Meanwhile I suggest building with ```--disable-cache-oblivious``` since it causes a measurable slowdown for you.

Regarding chunk size, note that the default was 4 MiB until 4.0.0, so the change from 256 KiB to 2 MiB on the dev branch was essentially a switch from 4 MiB to 2 MiB between releases.  You may want to experiment more with chunk sizes to see what works best for you.

**Comment by jasone** [comment]
Feel free to reopen if you have further related comments/questions.
