### ISSUE TITLE
In place reallocation not happening for huge reallocs

### ISSUE THREAD

**Issue by AlisdairO** [jemalloc/jemalloc#335]
Hi,

I noticed a while ago that huge reallocs on a short-lived program seemed to be quite a bit slower using jemalloc than the system allocator.  I've recently been informed that this is not expected, so I thought I'd post some code/results here.  I'm using jemalloc 4.0.4 for everything, and have tried on a linux VM and and OSX laptop.

The following program takes ~100ms on system, ~250ms on jemalloc.

```
#include <string.h>
#include <stdio.h>
#include <stdlib.h>


int main() {

    size_t buflen = 1024, oldlen = 0;
    char *buf = malloc(1024);
    for (int i = 0; i < 18; i++) {
        printf("Reallocing\n");
        buf = realloc(buf, buflen *= 2);
        printf("%zu\n", buflen);
        memset(buf, 1, buflen - oldlen);
        oldlen = buflen;
    }
    free(buf);

    return 0;
}
```

I made a jemalloc-specific version using xallocx to try to show when jemalloc was unable to realloc in-place:

```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <jemalloc/jemalloc.h>

int main() {

    size_t buflen = 1024, oldlen = 0;
    char *buf = malloc(1024);
    for (int i = 0; i < 18; i++) {

        size_t newbuflen = xallocx(buf, buflen*2, 0, 0);

        if (newbuflen == buflen) {
            printf("xallocx failed: realloc\n");
            buf = realloc(buf, buflen *= 2);
        } else {
            printf("xallocx succeeded\n");
            buflen = newbuflen;
        }
        printf("%zu\n", buflen);
        memset(buf, 1, buflen - oldlen);
        oldlen = buflen;
    }   
    free(buf);
         
    return 0;
}  
```

Output:

```
xallocx failed: realloc
2048
xallocx failed: realloc
4096
xallocx failed: realloc
8192
xallocx failed: realloc
16384
xallocx succeeded
32768
xallocx succeeded
65536
xallocx succeeded
131072
xallocx succeeded
262144
xallocx succeeded
524288
xallocx succeeded
1048576
xallocx failed: realloc
2097152
xallocx failed: realloc
4194304
xallocx failed: realloc
8388608
xallocx failed: realloc
16777216
xallocx failed: realloc
33554432
xallocx failed: realloc
67108864
xallocx failed: realloc
134217728
xallocx failed: realloc
268435456
```

I ran a slightly less cut down variant of this program through a profiler on OSX, and found that the system allocator was taking virtually no time, while jemalloc was eating quite a bit for moving on huge reallocs:

<img width="367" alt="jemalloc_basic" src="https://cloud.githubusercontent.com/assets/6296622/13230923/518cdc6c-d99f-11e5-9e12-ce11998b8e6e.png">

**Comment by jasone** [comment]
All the ```xallocx()``` failures for small size classes (< 16 KiB) are expected, and the successes for large size classes are expected as well (likely, but not guaranteed).  The huge size class failures can happen in principle, but they're surprising for a simple test program, and indeed they likely indicate a bug.

**Comment by jasone** [comment]
Thanks for reporting this and providing a test program.  I'm still scratching my head over why I didn't notice the opportunity to optimize this a long time ago.  Nearly all the necessary code was already there.

**Comment by AlisdairO** [comment]
No worries at all - thanks a lot for taking a look at it so quickly :-).
