### ISSUE TITLE
Invalid and inconsistent errorno definitions in Windows builds alter runtime behavior

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#343]
The content of `msvc_compat/windows_extra.h` causes
 invalid and inconsistent `errno` definitions in some compilation units
 apparently because `errno.h` does not always get to be included
 on windows and alters its runtime behavior.
 
 This is how I repro it in my build (native build no MinGW)
  
1) Build with `disable-stats` and run allocated.exe test.
 
 Because stats are disabled mallctl returns `ENOENT` with value 2.
 But the test compares it with value 3 as `ENOENT` is defined in
 windows_extra.h as `ERROR_PATH_NOT_FOUND` with value of 3.
 
 In general, errno C-runtime codes is not the same thing as Windows
 system errors.
 
 The test fails and it passes its value to strerror() which results
 the following output and then crash.

c:\dev\oss\repo.jemalloc\build>debug\allocated.exe
thd_start(): Error in mallctl(): No such process
thd_start(): Error in mallctl(): No such process

It is apparent in the debugger.

2) Prepend (or replace alltogether) the content of windows_extra.h
 with `#include <errno.h>`
 
 This results on the same definitions of errno everywhere. The test
 now exhibits the correct behavior

c:\dev\oss\repo.jemalloc\build>Debug\allocated.exe
"thread.allocated" mallctl not available
test_main_thread: skip
"thread.allocated" mallctl not available
test_subthread: skip
"thread.allocated" mallctl not available
test_main_thread: skip
"thread.allocated" mallctl not available
test_subthread: skip
"thread.allocated" mallctl not available
test_main_thread: skip
--- pass: 0/5, skip: 5/5, fail: 0/5 ---

The same happens with `fill` and `cache` related tests, they start
behaving correctly and enable to test and fix issues.

3) Now rebuild stats:

c:\dev\oss\repo.jemalloc\build>debug\allocated.exe
test_main_thread: pass
test_subthread: pass
test_main_thread: pass
test_subthread: pass
test_main_thread: pass
--- pass: 5/5, skip: 0/5, fail: 0/5 ---

it is possible that the same issue exists in compilation units other than tests.
I have not looked up the history as to why header came into existence the
way it is.

**Comment by jasone** [comment]
Integrated; thanks!
