### ISSUE TITLE
compile error under mingw 4.8.1

### ISSUE THREAD

**Issue by denzelii** [jemalloc/jemalloc#35]
jemalloc 3.4.1 is not compiling under mingw32 4.8.1:
 -ffs() is not defined
 -ffsl() is not defined
 -printf("%z", size_t) is incorrect
 - in malloc_init_hard() missing InitializeCriticalSection(&init_lock); call before malloc_mutex_lock(&init_lock);

**Comment by jasone** [comment]
These issues have all been fixed now, via the addition of ```jemalloc_ffs()``` and ```PRIzu```/```PRIzd```/```PRIzx```.
