### ISSUE TITLE
Unaligned accesses in hash.h can cause crash on arm architecture

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#351]
The code in include/jemalloc/internal/hash.h for hash_get_block_32 and hash_get_block_64 doesn't quite handle unaligned accesses properly. The code still references the p variable as if it were a uint32_t* or a uint64_t*.

Here is a proposed fix implemented on Android aosp master source code:

https://android-review.googlesource.com/#/c/206322/

It yields the same values but avoids the possible unaligned accesses.

**Comment by jasone** [comment]
Resolved by ca18f2834e17f31551f871cf4ca487aa9249614e.
