### ISSUE TITLE
NULL ptr behavior for {r,x,s,d,sd}allocx() functions is not documented

### ISSUE THREAD

**Issue by ronawho** [jemalloc/jemalloc#352]
Sorry if I just missed some documentation, but I'm not seeing anything that
mentions the behavior of the extended API functions when their `ptr` argument
is `NULL`. I'm guessing the behavior is undefined because that would line up
with behavior for `size==0`, and because the example below segfaults, but I
wasn't sure.

```c
#include <jemalloc/jemalloc.h>

int main() {
  void* p = NULL;
  je_dallocx(p, 0);
}
```

**Comment by jasone** [comment]
Yes, passing addresses to ```dallocx()``` that do not correspond to live allocations results in undefined behavior.
