### ISSUE TITLE
warning "undefined behavior" in MALLOCX_ALIGN 

### ISSUE THREAD

**Issue by nicolaichuk** [jemalloc/jemalloc#354]
in file jemalloc.h
```
#    define MALLOCX_ALIGN(a)						\
       ((int)(((a) < (size_t)INT_MAX) ? ffs((int)(a))-1 :		\
       ffs((int)((a)>>32))+31))
```

warning:

'>>': shift count negative or too big, undefined behavior

**Comment by jasone** [comment]
We need yet more casts in order to make this macro do the right thing with integer constants.  The root cause is likely that you're passing an integer rather than ```size_t``` to the macro.  Until the fix is in place you can work around the issue by changing e.g. ```MALLOCX_ALIGN(64)``` to ```MALLOCX_ALIGN((size_t)64)```.
