### ISSUE TITLE
jemalloc 3.6 crash in arena_avail_insert

### ISSUE THREAD

**Issue by gao1738** [jemalloc/jemalloc#359]
the core info as follow:

Program terminated with signal 11, Segmentation fault.
#0  0x00007fded39b63e2 in arena_avail_insert (maybe_adjac_succ=false, maybe_adjac_pred=false, npages=1018, pageind=6, chunk=0x0, arena=0x7fde65c3e540) at src/arena.c:225
225	src/arena.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-78.el7.x86_64
(gdb) bt
#0  0x00007fded39b63e2 in arena_avail_insert (maybe_adjac_succ=false, maybe_adjac_pred=false, npages=1018, pageind=6, chunk=0x0, arena=0x7fde65c3e540) at src/arena.c:225
#1  arena_chunk_alloc (arena=0x7fde65c3e540) at src/arena.c:621
#2  0x00007fded39b70dc in arena_run_alloc_large (arena=0x7fde65c3e540, size=<optimized out>, zero=false) at src/arena.c:699
#3  0x00007fded39b7bac in je_arena_malloc_large (arena=0x7fde65c3e540, size=1048576, zero=false) at src/arena.c:1663
#4  0x00007fded39adf64 in je_arena_malloc (try_tcache=true, zero=false, size=1048576, arena=0x0) at include/jemalloc/internal/arena.h:971
#5  je_imalloct (arena=0x0, try_tcache=true, size=1048576) at include/jemalloc/internal/jemalloc_internal.h:771
#6  je_imalloc (size=1048576) at include/jemalloc/internal/jemalloc_internal.h:780
#7  malloc (size=1048576) at src/jemalloc.c:929
#8  0x00007fded3700cfa in dbscale::assign_mem_from_mem_node(dbscale::memory_node**, unsigned long) () from /home/gao/dbscale/libs/libdbscale_core.so
#9  0x00007fded31bb82f in yylex_init_extra(void*, void**) () from /home/gao/dbscale/libs/libmysql_driver.so
#10 0x00007fded31e8845 in dbscale::do_parse(char const*, unsigned long, dbscale::stmt_node*, dbscale::MemoryAllocater*) () from /home/gao/dbscale/libs/libmysql_driver.so
#11 0x00007fded3107be8 in dbscale::mysql::MySQLParser::parse(char const*, bool, dbscale::MemoryAllocater*, dbscale::sql::Statement*, dbscale::MemoryAllocater*) ()
   from /home/gao/dbscale/libs/libmysql_driver.so
#12 0x00007fded30defdd in dbscale::mysql::MySQLHandler::handle_query_command(dbscale::Packet*) () from /home/gao/dbscale/libs/libmysql_driver.so
#13 0x00007fded30e393b in dbscale::mysql::MySQLHandler::do_handle_request() () from /home/gao/dbscale/libs/libmysql_driver.so
#14 0x00007fded35da0d6 in dbscale::Handler::svc() () from /home/gao/dbscale/libs/libdbscale_core.so
#15 0x00007fded2d7b25c in ACE_Task_Base::svc_run(void*) () from /home/gao/dbscale/libs/libACE.so.6.3.2
#16 0x00007fded2d7cbe5 in ACE_Thread_Adapter::invoke_i() () from /home/gao/dbscale/libs/libACE.so.6.3.2
#17 0x00007fded2d7cc9d in ACE_Thread_Adapter::invoke() () from /home/gao/dbscale/libs/libACE.so.6.3.2
#18 0x00007fded29fcdf5 in start_thread () from /home/gao/dbscale/libs/libpthread.so.0
#19 0x00007fded04921ad in clone () from /home/gao/dbscale/libs/libc.so.6

The jemalloc is installed from rpm:
jemalloc-devel-3.6.0-1.el7.x86_64
jemalloc-3.6.0-1.el7.x86_64

Is it a fixed bug? If yes, which version I should upgraded to?

best regards!

dennis

**Comment by jasone** [comment]
This is most likely due to an application bug corrupting allocator metadata, typically either a double free or write-after-free.  If you disable thread caching (e.g. ```MALLOC_CONF=tcache:false```) and use a debug build of jemalloc, assertions will likely catch double frees.
