### ISSUE TITLE
Make Wiki Editable

### ISSUE THREAD

**Issue by njwhite** [jemalloc/jemalloc#366]
I can't seem to edit the wiki, and can't find the repo backing it. [The leak-checking example](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Leak-Checking) could use a description of what the columns in the "top" output mean :)

**Comment by jasone** [comment]
The wiki is intentionally not world-writable.  Note that there is a [link](https://github.com/jemalloc/jemalloc.wiki.git) on the wiki page.
