### ISSUE TITLE
Remove Valgrind/quarantine/redzone support

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#369]
Rationale:

- The [```arena.<i>.reset```](146) feature would at a minimum have to assure that quarantine wasn't enabled.
- Quarantine doesn't interact well with thread caches, which means that applications which use explicit thread caches cannot in general use quarantine safely.
- Redzone support complicates memory layout in ways that make it impossible to compute various tables at compile time (small run sizes vary, which impacts quantized run sizes).  This can be mitigated, but at considerable engineering complexity cost.

**Comment by milasudril** [comment]
What is the new way of debugging memory issues when using jemalloc?

**Comment by jasone** [comment]
@milasudril, various facilities remain, including assertions (see ```--enable-debug```), run-time-optional junk filling (built in by default; see ```--disable-fill```) and heap profiling (see ```--enable-prof```).  Note that jemalloc is designed primarily to be efficient (speed and memory usage), rather than to be a debugging facility.  Other projects such as AddressSanitizer and Valgrind remain good (jemalloc-incompatible) options for investigating memory corruption.

**Comment by milasudril** [comment]
The reason I use jemalloc is the presence of SSE friendlier API:s

    void *mallocx(void *ptr, int flags);
    void *rallocx(void *ptr, size_t size, int flags);
    void dallocx(void *ptr,int flags)

In particular, the second one has no corresponding function on POSIX (there is on Windows). This means that I have do one of the following, if aligned realloc is desired:

 * Disable AVX. On 32-bit platform, also disable SSE, basically removing the need for this API.
 * Emulate `rallocx` by
   - `posix_memalign`
   - check the result,
   - `memcpy` to the new block
   - `free` the old block
   - return pointer to new block
  Notice that this will *always* move data to a new block, even if the old block had sufficient space (this is the reason for the existence `realloc`).
 * Roll my own wrappers, or use the functions found in WINE/ReactOS.
