### ISSUE TITLE
MSVC 2015 bustage with jemalloc tip

### ISSUE THREAD

**Issue by rvandermeulen** [jemalloc/jemalloc#374]
On rev a15841c, I'm getting the following compilation failure:
mutex.h(46): error C2061: syntax error: identifier 'witness_t'

Followed by a cascade of other build failures after that.

**Comment by rvandermeulen** [comment]
Nevermind, I was being dumb.

**Comment by jasone** [comment]
I'm guessing you ran into issues because I didn't add witness.[ch] to the MSVC build system files.

**Comment by rvandermeulen** [comment]
Correct, witness.c was missing.
