### ISSUE TITLE
MSVC 2015 bustage with jemalloc tip

### ISSUE THREAD

**Issue by rvandermeulen** [jemalloc/jemalloc#375]
jemalloc\src\include\jemalloc/internal/mb.h(107): error C2065: 'MALLOC_MUTEX_RANK_OMIT': undeclared identifier

AFAICT, that's the only use of MALLOC_MUTEX_RANK_OMIT in the repo.

**Comment by jasone** [comment]
Oops, that's a refactoring artifact.

**Comment by rvandermeulen** [comment]
This is still broken for me. Now I'm getting
jemalloc\src\include\jemalloc/internal/mb.h(107): error C2198: 'je_malloc_mutex_init': too few arguments for call

**Comment by rvandermeulen** [comment]
Confirmed fixed by rev 71d9482, thanks!
