### ISSUE TITLE
Is there any way to know the version of jemalloc on my device?

### ISSUE THREAD

**Issue by Delostik** [jemalloc/jemalloc#376]
Is there any way to know the version of jemalloc on my device? For example, on android devices, jemalloc was prebuilt.

thx

**Comment by jasone** [comment]
The version string is printed by ```malloc_stats_print()```, which you can either call directly or cause to be called at shutdown by setting ```MALLOC_CONF=stats_print:true``` in the enclosing shell environment.

**Comment by Delostik** [comment]
I call this function directly but received a segment fault

**Comment by jasone** [comment]
Read the [manual](http://www.canonware.com/download/jemalloc/jemalloc-latest/doc/jemalloc.html) and make sure you're passing valid arguments, and if you are, then you're hitting something outside my experience and need to investigate e.g. using a debugger.
