### ISSUE TITLE
OS X Static Lib

### ISSUE THREAD

**Issue by godrays** [jemalloc/jemalloc#381]
Hi,

I tried to build static lib and use with XCode but I wasn't able to link static lib.

Here how I build the lib:

./configure --with-jemalloc-prefix="" --prefix=$PWD/build/xcode
make clean
make build_lib_static
make install_lib_static

When I link, I just put '-ljemalloc' linker flag and am able to build simple console app. Unfortunately jemalloc does not hook.

When I use shared lib, it works perfectly fine. I can see malloc calls are being replaced by jemalloc.

I can't see why it does not work with static lib.

I'm using Yosemite, Xcode 7

**Comment by jasone** [comment]
My guess is that the constructor attribute on the ```register_zone()``` function in jemalloc isn't being called, due to the dynamic loader not being involved.  You could try to manually call that function in your application during startup, or you could use e.g. ```je_malloc()``` directly (with care not to mix allocators).
