### ISSUE TITLE
Implement arena.<i>.destroy

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#382]
Now that all internal metadata are allocated via auto arenas (see 66cd953514a18477eb49732e40d5c2ab5f1b12c5, which was a prerequisite for `arena.<i>.reset`), it is feasible to also completely destroy arenas that were created via `arenas.extend`.  The primary motivation is to make ephemeral arenas simple for applications to manage; right now the application has to manage its own pool of arenas if it wants to make short-term use of arenas.

It's not clear what to do about stats for destroyed arenas.  One possibility would be to keep an extra set of arena stats into which to merge during arena destruction, and show those stats independently and/or as part of the merged arena stats.

**Comment by yuslepukhin** [comment]
@jasone How this would be different from arena.<i>.reset currently documented?

**Comment by jasone** [comment]
```arena.<i>.destroy``` would perform a reset, and then completely destroy the arena, so a subsequent ```arenas.extend``` operation could reuse the arena index.

**Comment by yuslepukhin** [comment]
@jasone This apparently means that memory will be unmapped. I am looking forward to this as we'd like to use this feature in a multi-tenancy environment.

**Comment by jasone** [comment]
I'm partway through implementing this, and have a design that seems pretty reasonable with regard to destroyed arena stats.  It will become possible to access merged stats, e.g. ```stats.arenas.<i>.mapped``` at index ```MALLCTL_STATS_ARENAS_MERGED```, whereas currently it is at index ```arenas.narenas``` (which has to be queried for every mallctl epoch).  As a side note I'm going to maintain deprecated compatibility with the latter so that transitioning apps between versions won't be unnecessarily disruptive.

In addition to ```MALLCTL_STATS_ARENAS_MERGED``` there will be ```MALLCTL_STATS_ARENAS_DESTROYED```, which will contain the merger of destroyed arenas' stats, updated during each arena destruction.  I considered keeping per-arena-index destroyed arena stats, but that would be only marginally more informative and much less wieldy.

**Comment by jasone** [comment]
Note that #463 ended up being instrumental to ```arena.<i>.destroy```, because without it a destroyed arena's base allocations would have been leaked.  The ```arenas.extend``` mallctl (which will be renamed to ```arenas.create``` as part of #382) had to be modified to take an argument so that application-specified extent hooks could be used for *all* base allocations.  The API feels clunky because it's the first mallctl to return a different type than its input type, but I couldn't think of a cleaner solution within the confines of mallctl.
