### ISSUE TITLE
imx6ul run jemalloc come out Alignment trap: not handling instruction e1b24f9f at [<76f015c8>] Unhandled fault: alignment exception (0x001) at 0x76f2564

### ISSUE THREAD

**Issue by macherie** [jemalloc/jemalloc#384]
Alignment trap: not handling instruction e1b24f9f at [<76f015c8>]
Unhandled fault: alignment exception (0x001) at 0x76f2564

**Comment by jasone** [comment]
What version of jemalloc is this for?  If it's 4.1.1, then I cannot make any progress without symbols for the reported hex addresses.  If it's for 4.1.0, then b40253a93ec4eb79c536403491f326bb56f72c02 probably fixes the issue you're seeing.

**Comment by macherie** [comment]
Hi:
http://comments.gmane.org/gmane.comp.lib.jemalloc/1256
Please read the above article.my jemalloc version is 4.1.1,the problem I have encountered is exactly the same as it is.

**Comment by jasone** [comment]
Did you try my suggestion at the end of that email thread?

**Comment by macherie** [comment]
Is to change a 32 bit system for the computer to compile it? I am not too clear, can you speak clearly? thank you！

**Comment by macherie** [comment]
4  include/jemalloc/internal/hash.h
 @@ -53,7 +53,7 @@ hash_get_block_32(const uint32_t *p, int i)
  	if (unlikely((uintptr_t)p & (sizeof(uint32_t)-1)) != 0) {
  		uint32_t ret;
  
 -		memcpy(&ret, &p[i], sizeof(uint32_t));
 +		memcpy(&ret, (uint8_t *)(p + i), sizeof(uint32_t));
  		return (ret);
  	}
  
 @@ -68,7 +68,7 @@ hash_get_block_64(const uint64_t *p, int i)
  	if (unlikely((uintptr_t)p & (sizeof(uint64_t)-1)) != 0) {
  		uint64_t ret;
  
 -		memcpy(&ret, &p[i], sizeof(uint64_t));
 +		memcpy(&ret, (uint8_t *)(p + i), sizeof(uint64_t));
  		return (ret);
  	}
  
Is this the right thing to do?
