### ISSUE TITLE
Fix tautological-constant-out-of-range-compare clang warning in arena.c

### ISSUE THREAD

**Issue by liutikas** [jemalloc/jemalloc#386]
jemalloc/src/arena.c:1355:41: warning: comparison of constant 18446744072 with expression of type 'ssize_t' (aka 'int') is always true [-Wtautological-constant-out-of-range-compare]
        return (decay_time >= -1 && decay_time <= NSTIME_SEC_MAX);
                                    ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~

**Comment by jasone** [comment]
This appears to be relative to the 4.1.0 release, and was resolved by 022f6891faf1fffa435f2bc613c25e8482a32702, as part of the 4.2.0 release.
