### ISSUE TITLE
Verify jemalloc in use at runtime?

### ISSUE THREAD

**Issue by mlin** [jemalloc/jemalloc#388]
I was wondering if there's a suggested precise way to test at runtime that jemalloc is in use as `malloc()` regardless of how the program was linked. This would be a great addition to https://github.com/jemalloc/jemalloc/wiki/Getting-Started

Context: I recently ran into an issue where I thought my program was using jemalloc, but due to some very subtle misconfiguration, was actually using the system malloc at runtime. I think this is now fixed, but I'd like to put in some kind of countermeasure against a future regression. In particular I'd like to make the program print a warning if jemalloc isn't in use, since the performance difference is really substantial.

**Comment by jasone** [comment]
A quick and dirty method is to see if a warning prints from: ```MALLOC_CONF=invalid_flag:foo <program>```

A more detailed sanity check is to look for reasonable stats during shutdown from: ```MALLOC_CONF=stats_print:true <program>```

A programmatic approach is to define ```mallctl``` as a weak symbol in your application, and check at run time whether your weak symbol is replaced by jemalloc's definition.

The best approach depends on a lot of circumstances, so I don't think there's a canned best practice.

**Comment by mlin** [comment]
Thanks @jasone! cc @orodeh

**Comment by fwyzard** [comment]
@jasone
> A programmatic approach is to define `mallctl` as a weak symbol in your application, and check at run time whether your weak symbol is replaced by jemalloc's definition.

How would you do that, e.g. using GCC on Linux ?

Here is my approach, using `dlsym` to check if `mallctl` is available or not:
```c++
#include <dlfcn.h>

extern "C" {
  typedef
  int (*mallctl_t)(const char *name, void *oldp, size_t *oldlenp, void *newp, size_t newlen);
}

bool check_jemalloc() {
  mallctl_t mallctl = (mallctl_t) ::dlsym(RTLD_DEFAULT, "mallctl");
  return (mallctl != nullptr);
}
```

**Comment by jasone** [comment]
The ```dlsym()``` approach is reasonable AFAIK.  You may be able to do the check a bit cheaper if you create a weak symbol that is set to ```NULL```, and then just do a null pointer check without the ```dlsym()``` call.

**Comment by fwyzard** [comment]
Yes, this works most of the time:
```c++
extern "C"
{
  // weak symbol: resolved at runtime by the linker if we are using jemalloc, nullptr otherwise
  int mallctl(const char *name, void *oldp, size_t *oldlenp, void *newp, size_t newlen) __attribute__((weak));
}

bool check_jemalloc() {
  return (mallctl != nullptr);
}
```

However I did not manage to generate a weak symbol when using `clang -lfto` .

**Comment by ChasenYang** [comment]
you can use sleep in your code like this
    void *p = malloc(1024*1024);
    sleep(100);
    free(p);
during sleeping time, 
get the process id and run this command
cat  /proc/13173/smaps | grep jemalloc
you can see that you program is using the jemalloc

**Comment by SergejIsbrecht** [comment]
What about pmap -X <pid> and look for libjemalloc.so.1?

**Comment by limjinsun** [comment]
```
MALLOC_CONF=stats_print:true ruby -e "exit"
```
_**If this command show stats, then it's all set. I found this on internet.**_

**Comment by easimon** [comment]
Old issue, but maybe also useful:

```
MALLOC_CONF=abort_conf:true,invalid_option:foo java -version
```

This command
- *fails* when jemalloc is used
- succeeds (prints results of java -version) when jemalloc is not used, because glibc malloc ignores MALLOC_CONF

This "fail to succeed" inversion may be counter-intuitive, but I use this in a ci pipeline in a step that is expected to fail. And checking for return codes is easier / more stable than grepping the output.

**Comment by atstockland** [comment]
> ```
> MALLOC_CONF=stats_print:true ruby -e "exit"
> ```
> 
> _**If this command show stats, then it's all set. I found this on internet.**_

How would I run this?

**Comment by DimmKirr** [comment]
> MALLOC_CONF=stats_print:true ruby -e "exit"



> > ```
> > MALLOC_CONF=stats_print:true ruby -e "exit"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _**If this command show stats, then it's all set. I found this on internet.**_
> 
> How would I run this?

Copy the command and run it on the server/in a container that is supposed to run ruby.
