### ISSUE TITLE
Don't attempt to use /proc/<pid>/maps on Darwin

### ISSUE THREAD

**Issue by mberhault** [jemalloc/jemalloc#394]
Darwin builds always return `EFAULT` on dumps due to the lack of `procfs`.
This makes error checking impossible (I'd like to know when there's a real error. eg: permission denied, full disk etc... and log it).

It would be nice to either remove the `proc` check entirely, or use something else.

**Comment by jasone** [comment]
This is a variation on #26, which is to say that heap profiling simply doesn't work on OS X.

**Comment by mberhault** [comment]
Got it, thanks @jasone.
