### ISSUE TITLE
jemalloc not detecting invalid read

### ISSUE THREAD

**Issue by royamitabha** [jemalloc/jemalloc#395]
I have the following code:

int main(int argc, char **argv)
{
  int * n = new int(5);
  delete n;
  *n += 1;
  std::cerr << *n << std::endl;
}

With jemalloc configured with --enable-debug,  I cannot get any assertions to fire (valgrind works fine
for this).  Why is this the case?

**Comment by jasone** [comment]
This is a write after free, and the only mechanism in jemalloc that can possibly detect it is [quarantine](http://www.canonware.com/download/jemalloc/jemalloc-latest/doc/jemalloc.html#opt.quarantine).
