### ISSUE TITLE
file descriptor opened but not closed in os_overcommits_proc()

### ISSUE THREAD

**Issue by vsarunas** [jemalloc/jemalloc#399]
After #193, each process under Linux using jemalloc 4.2 opens /proc/sys/vm/overcommit_memory, but the descriptor is [never closed](https://github.com/jemalloc/jemalloc/blob/dev/src/pages.c#L217).

**Comment by cferris1000** [comment]
Any chance this can make it into 4.2.2?

**Comment by jasone** [comment]
Yes, I will make sure this is fixed in the next release.

**Comment by jasone** [comment]
Fixed in dev by 3c8c3e9e9b59b6e34a222816a05f0a01a68919b3, and cherry-picked into rel-4.3.0 as 79647fe4650ddd5325ce2cedf0fced772eed3f71.  Thanks!
