### ISSUE TITLE
prng.h uses atomic_*_uint64 on all platforms, but it's only declared in 64-bits platforms

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#402]
in atomic.h, atomic_*_uint64 functions are behind a

```
#if (LG_SIZEOF_PTR == 3 || LG_SIZEOF_INT == 3)
```

but prng.h uses them unconditionally.

**Comment by jasone** [comment]
This is roughly the third time I've made this mistake.  I wish there were a way to catch this on 64-bit systems.

**Comment by jasone** [comment]
Partial fix integrated as c2942e2c0e097e7c75a3addd0b9c87758f91692e.

**Comment by jasone** [comment]
In practice, c2942e2c0e097e7c75a3addd0b9c87758f91692e appears to be sufficiently general.  We have a multiplicity of implementations based on C11, gcc intrinsics, and Windows APIs that cover pretty much all hypothetically supported systems going back ~10 years.

I cherry-picked the fix to rel-4.3.0 as af33e9a59735a2ee72132d3dd6e23fae6d296e34.
