### ISSUE TITLE
jemalloc to manage DMA memory

### ISSUE THREAD

**Issue by bhjLarson** [jemalloc/jemalloc#410]
I am interested in using jemalloc as the memory manager for direct memory access (DMA) memory.  Can the jemalloc chunk header and run header  be stored separately from the application memory?  The DMA read and write must only contain the actual data being transferred, not the jemalloc headers.  It appears that others have succeeded with this (http://www.canonware.com/pipermail/jemalloc-discuss/2015-October/001179.html) but it is unclear if this was accomplished without modifying  jemalloc.

**Comment by jasone** [comment]
The dev brach recently migrated to extent-based metadata, which means all the allocator metadata now come from the base allocator.  This provides the full separation between application data and allocator metadata you're looking for.
