### ISSUE TITLE
Please merge jemalloc 4.2.x branch in jemalloc-cmake

### ISSUE THREAD

**Issue by nicolaichuk** [jemalloc/jemalloc#411]

**Comment by yuslepukhin** [comment]
@nicolaichuk Will do today.

**Comment by yuslepukhin** [comment]
@nicolaichuk https://github.com/jemalloc/jemalloc-cmake/commit/a84e5083d11de84bda298020961fb9966d50ed9a done

**Comment by nicolaichuk** [comment]
thanks
