### ISSUE TITLE
Long spinning in rtree_node_init under heavy contention

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#415]
Currently in rtree_node_init, threads encountered CAS failure will spin and wait for the initialize thread to finish. However if the thread that's doing initialization is preempted, many other threads will be spinning and waiting for a long time. Observed in t-test1 with 128 threads on 32 cores. Practically the test is in a live lock like situation that never finishes. Perf shows > 99% CPU time spinning in rtree_node_init.

A simple spin a number of times then block (e.g. like below) fixed the issue. However we can probably avoid the sleep by fixing this differently (and better), e.g. initialize multiple nodes in rtree at once, different node size, etc.

```
unsigned n_spin = 16;
do {
  CPU_SPINWAIT;
  node = atomic_read_p((void **)elmp);
  if (n_spin-- == 0) {
    usleep(1000);
    u_spin = 16;
  }
} while (node == RTREE_NODE_INITIALIZING);
```

**Comment by djwatson** [comment]
I also noticed this on the new dev branch.  atomic helper-complete would also fix this.

**Comment by jasone** [comment]
Interesting; given that initialization only happens once per node I overlooked scenarios that could cause contention to be an issue.  Long ago jemalloc used custom adaptive spinlocks (which was the origin of the ```CPU_SPINWAIT``` macro).  If possible I'd like to avoid sleep syscalls; I'll dredge that code up see if it makes sense in this context.

@djwatson, what is atomic helper-complete?  Is it something related to earlier hotpatching discussion?

**Comment by djwatson** [comment]
if rtree_node_init sees someone else is trying to init the node, it probably means the other thread initing the node has been scheduled off and is sleeping.   Not sure it makes sense in this case vs. adaptive spinning, but you could do something like:

                node = rtree_node_alloc(tsdn, rtree, ZU(1) << rtree->levels[level].bits);
                if (node == NULL)
                        return (NULL);
                if(!atomic_cas_p((void **)elmp, node) {
                     free_node(node); // or purge/leak
               }

**Comment by interwq** [comment]
That would work if we can free the allocated node. Currently I think it
cannot be freed (memory from base_alloc)?

**Comment by jasone** [comment]
We have adaptive spinning as of e5effef428b5bf941e1697f6000c97f1ce734756, so this may be resolved, but further analysis is necessary before declaring victory.

**Comment by interwq** [comment]
It looks the issue still exists under heave contention. Perf now reports je_rtree_child_read_hard (i.e. rtree_node_init) takes 99% of CPU w/ t-test1, all time spent in spinning:
       │            for (i = 0; i < (KQU(1) << spin->iteration); i++)  
 30.37 │      mov    0x8(%rsp),%r8                                                                                                       ▒
 37.47 │      add    $0x1,%r8                                                                                                            ▒
  1.24 │      mov    %r8,0x8(%rsp)                                                                                                       ▒
 12.18 │      mov    0x8(%rsp),%r9                                                                                                       ▒
 17.15 │      cmp    %rsi,%r9                                                                                                            ▒
       │    - jb     50                                                                                                                  ▒
       │                    CPU_SPINWAIT;         

I think we are missing "spin a while and then eventually block". Since if there are many threads, if the thread doing the work gets preempted, other threads spinning won't help.

**Comment by interwq** [comment]
One possible solution if we want to avoid the blocking, and cannot free the already allocated node: if we allocated a node and then CAS failed, we can use the node to initialize the next region in the rtree (and retry if still fails). This should only happen under heavy contention, in which case initialize multiple nodes probably makes sense.

**Comment by interwq** [comment]
@djwatson fixed this.
