### ISSUE TITLE
Dead links in wiki documentation (google code)

### ISSUE THREAD

**Issue by uniqueid001** [jemalloc/jemalloc#421]
The wiki documentation contains links to gperftools, however since google code was shut down that project moved to github.  The patch in the attached zip file corrects this.  (github wouldn't allow me to upload the patch file itself)

[0001-Updated-links-to-gperftools.patch.zip](https://github.com/jemalloc/jemalloc/files/350407/0001-Updated-links-to-gperftools.patch.zip)

**Comment by jasone** [comment]
Patch manually applied.  Thanks!
