### ISSUE TITLE
Deadlock in tcache_destroy (4.2.1)

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#425]
There is a path through jemalloc that can lead to a deadlock because the arena lock is already being held, and then an attempt is made to acquire it again.

Here's the stack trace from the jemalloc 4.2.1. I annotated the two places that the arena lock has been acquired.

  The arena lock is being acquired again.
#01 arena_bin_nonfull_run_get() at src/arena.c:2292
#02 arena_bin_malloc_hard() at src/arena.c:2334
#03 arena_malloc_small() at src/arena.c:2550
#04 arena_malloc() at include/jemalloc/internal/arena.h:1344
#05 a0malloc() at src/jemalloc.c:336
#06 malloc_tsd_malloc() at src/tsd.c:18
#07 malloc_tsd_funcs() at include/jemalloc/internal/tsd.h:658
#08 chunk_merge_default() at src/chunk.c:738
#09 chunk_record() at src/chunk.c:526
#10 chunk_dalloc_wrapper() at src/chunk.c:660
#11 arena_unstash_purged() at src/arena.c:1752
#12 arena_purge_to_limit() at src/arena.c:1810
#13 arena_maybe_purge_decay() at src/arena.c:1495
#14 arena_maybe_purge() at src/arena.c:1509
#15 arena_run_dalloc() at src/arena.c:2162
#16 arena_dalloc_bin_run() at src/arena.c:2854
  The arena lock is acquired at line src/arena.c:2853 in arena_dalloc_bin_run
#17 arena_dalloc_bin_locked_impl() at src/arena.c:2906
#18 arena_dalloc_bin_junked_locked() at src/arena.c:2921
#19 tcache_bin_flush_small() at src/tcache.c:134
#20 tcache_destroy() at src/tcache.c:368
#21 tcache_cleanup() at src/tcache.c:407
#22 tsd_cleanup() at src/tsd.c:82

My config has decay purge enabled instead of ratio enabled, to make this happen more often, I set the DECAY_TIME_DEFAULT to zero. My config also has JEMALLOC_TLS enabled.

I tried to come up with a small test that demonstrates this, but I was unable to get the right set of circumstances to make this occur. If necessary, I can try again if the stack doesn't make sense.

**Comment by jasone** [comment]
This is one of a long-lived class of bugs, and quite serious for affected applications.  It's tempting to delay purging during thread cleanup, but so far it hasn't quite been necessary.
