### ISSUE TITLE
runs_avail : deallocate/insert and allocate/first-best-fit not match for large run

### ISSUE THREAD

**Issue by leebaok** [jemalloc/jemalloc#445]
I am reading code of jemalloc-4.2.1. And I think arena_run_first_best_fit of large run maybe much larger than the request (two level up than request). 

For runs_avail, arena_avail_insert use size2index(run_quantize_floor(size)) to locate the index. And runs_avail[i] stores the runs that larger than index2size(i). This means runs_avail[i] could fit the request of all size in index i.  For arena_run_first_best_fit, use size2index(run_quantize_ceil(size)) to locate index. And this fits well for large run. 

But for large run allocation, size is updated for three times:
* arena_malloc_large : usize=index2size(binind), size=usize+large_pad
* arena_run_alloc_large_helper : size=s2u(size)
* arena_run_first_best_fit : ind=size2index(run_quantize_ceil(size))

If large_pad is PAGE, the index of size will become one level up in the first two steps. And in the third step, the size will become one more level up than the original size. And the found run is too large than request. And maybe the first two steps are not necessary.

Is it designed in this method or I got the wrong idea of the allocation of large run with large_pad ?

**Comment by jasone** [comment]
I made some quantization simplifications this spring (prior to moving quantization from runs to extents) that hopefully clear up the situation:

  3aea827f5e7d07ce156476bba8a843640969de51

This was a precursor for removing some sizes:

  7bb00ae9d656b3d3ea9a01777cf1a13ab97f2430

I don't remember all the details of this conversion, but there are some relevant notes in #370, and I find no indications in my notes nor the git history of having uncovered bugs that would have caused correctness issues.  Can you please take a look at the newer implementation and see if your concerns are addressed?  It was difficult for me to wrap my head around the old implementation, so if possible I'd rather discuss this in the context of the new version.

**Comment by leebaok** [comment]
jemalloc is in hot developing process. According to the changes, I think this issue not exists in the newer version. 

I will move to the the newest implementation of jemalloc. 

Thanks !
