### ISSUE TITLE
why no frame in the heap file?

### ISSUE THREAD

**Issue by wutheringwind** [jemalloc/jemalloc#447]
My programe:
void test()
{
        int i = 30;
        while(i)
        {
                printf("loop\n") ;
                void * p = malloc(200000);
                sleep(1);
                --i;
        }
}

void test2()
{
        int i = 20;
        while(i)
        {
                printf("loop\n") ;
                void * p = malloc(200000);
                sleep(1);
                --i;
        }
}

void main()
{
        test();
        test2();
}

the content of a heap file as below, no frame info:
heap_v2/32
  t*: 40: 9175040 [0: 0]
  t0: 40: 9175040 [0: 0]
@
  t*: 40: 9175040 [0: 0]
  t0: 40: 9175040 [0: 0]

MAPPED_LIBRARIES:
00008000-00009000 r-xp 00000000 b3:06 1027       /usr/bin/test_go/go
00010000-00011000 rw-p 00000000 b3:06 1027       /usr/bin/test_go/go
...

**Comment by mckellyln** [comment]
I think you should touch the memory.

**Comment by djwatson** [comment]
> the content of a heap file as below, no frame info:

This is the kernel's view of memory usage?  mckellyln is correct, you need to touch the memory.  Unlike most allocators, jemalloc never touches the allocated memory itself, and therefore the pages are not faulted in until you actually use the memory.
