### ISSUE TITLE
Question: Is there any reliable way to track double free with jemalloc?

### ISSUE THREAD

**Issue by grotesque** [jemalloc/jemalloc#451]
[Here](https://github.com/jemalloc/jemalloc/issues/111) it was mentioned that to tackle double free 

> force immediate failure due to double freeing by using a debug build of jemalloc with thread caching disabled

But even after doing that we cannot zero in on the issue if the offending free is the first free. The only way to track this is have stack traces recorded for every free (if possible with parameter info). Windows does this with pageheap and linux with valgrind. But these are too heavy and my application doesn't run well with them.

Can jemalloc help or do I have to implement some instrumentation myself?

**Comment by jasone** [comment]
From the allocator's perspective, the first call to ```free()``` is valid, so there's no reasonable way to flag it.  Your idea of tracing deallocations is probably your best bet.  If you can limit tracing to, say, allocations of a known size, you may be able to zero in on the culprit with reasonable effort.
