### ISSUE TITLE
Jemalloc library is hitting Segmentation fault on CentOS-7

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#455]
Context: http://jemalloc.net/mailman/jemalloc-discuss/2016-August/001317.html

**Comment by RoelVdP** [comment]
Thank you @jasone

**Comment by jasone** [comment]
Long story short, my attempt to install CentOS 7 on a development machine failed, so I'm going to set up a VMware guest image when I get back to this.

**Comment by jasone** [comment]
I'm working on setting up a CentOS 7 x86_64 VMware guest today, at the same time as setting up a CentOS 6 i686 guest for #448.

**Comment by jasone** [comment]
The ```ls``` crash isn't reproducing for me with jemalloc 3.6.0, 4.2.1, nor dev.  Please provide detailed reproduction steps.  You may also want to try a more modern jemalloc package; you appear to be something no newer than 3.6.0.
