### ISSUE TITLE
Need help with jemalloc cores

### ISSUE THREAD

**Issue by ajopensrc** [jemalloc/jemalloc#457]
Hi Jason,

This is with reference to recent thread:
http://jemalloc.net/mailman/jemalloc-discuss/2016-September/001326.html

I have compiled the jemalloc library using the --enable-fill and --enable-debug options and I guess these stacks are assertion failures in libejemalloc code and I am trying to understand what these mean. Please confirm if any other options are needed for debug jemalloc.

We did find another stack with double free as the memory contents are all Zs and working on fixing that.

Regards,
Asmita

**Comment by interwq** [comment]
This looks like to be the dev branch. From the stack trace it seems related
to https://github.com/jemalloc/jemalloc/issues/437

Can you please try release 4.2.1 instead? You can find the code here:
https://github.com/jemalloc/jemalloc/tree/4.2.1/

**Comment by ajopensrc** [comment]
Ah ok. Will give it a shot.. is it ok to use --enable-debug and --enable-fill for verifying this with 4.2.1 or you want me to stick to release (assuming that means no options to ./configure script)

Thanks for taking a look.

**Comment by interwq** [comment]
Sure. Please feel free to enable debug options for investigation.

**Comment by ajopensrc** [comment]
Ok. Meanwhile, there was another core (with same dev libjemalloc) which I assumed to be a double free in the application code since the ptr being freed has all Zs in the corefile. Could you please confirm this is correct or could the below stack also be due to jemalloc dev branch?

(gdb) bt
#0  0x00007f1a8e4d0ab3 in large_dalloc_impl (tsdn=0x7f197311c580, extent=0x7f14ac0360c0, junked_locked=true) at src/large.c:292
#1  0x00007f1a8e4d0bc3 in je_large_dalloc_junked_locked (tsdn=0x7f197311c580, extent=0x7f14ac0360c0) at src/large.c:309
#2  0x00007f1a8e4e48b0 in je_tcache_bin_flush_large (tsd=0x7f197311c580, tbin=0x7f1455e9c448, binind=39, rem=10, tcache=0x7f1455e9bf40)
    at src/tcache.c:210
#3  0x00007f1a8e4e3cfe in je_tcache_dalloc_large (tsd=0x7f197311c580, tcache=0x7f1455e9bf40, ptr=0x7f14a687fa00, size=28672, slow_path=true)
    at include/jemalloc/internal/tcache.h:436
#4  0x00007f1a8e4b4085 in je_arena_dalloc (tsdn=0x7f197311c580, extent=0x7f14a6a35300, ptr=0x7f14a687fa00, tcache=0x7f1455e9bf40, slow_path=true)
    at include/jemalloc/internal/arena.h:601
#5  0x00007f1a8e4abd71 in je_idalloctm (tsdn=0x7f197311c580, extent=0x7f14a6a35300, ptr=0x7f14a687fa00, tcache=0x7f1455e9bf40, is_metadata=false,
    slow_path=true) at include/jemalloc/internal/jemalloc_internal.h:1093
#6  0x00007f1a8e4b047c in ifree (tsd=0x7f197311c580, ptr=0x7f14a687fa00, tcache=0x7f1455e9bf40, slow_path=true) at src/jemalloc.c:1730
#7  0x00007f1a8e4b0b41 in free (ptr=0x7f14a687fa00) at src/jemalloc.c:1841

**Comment by interwq** [comment]
I'm not sure about this one. The stack trace is related to both cases. I'd
still say try on the stable release and you should be able to confirm if
it's double free or not.

**Comment by ajopensrc** [comment]
Ok. I will update on the outcome with stable release. Thanks.

**Comment by ajopensrc** [comment]
Not seeing the cores with 4.2.1 branch. Closing the issue.

**Comment by jasone** [comment]
The bugs fixed by f6d01ff4b7322eeed56c61a11e3e3397765d3f22 and e3187ec6b6a349b3add5c27c470ff7f7f040c1d5 could easily have caused the crashes reported here.
