### ISSUE TITLE
Managing arenas

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#460]
Jason,

I am currently working on multi tenancy problems and memory is a hot topic.
I am experimenting with allocating extended arenas and switching thread association
once a specific piece of code id executed.

This works well, particularity when it comes to resetting arenas, this unmaps memory and Private bytes drop as expected ready for reuse.

However, control calls that switch current thread association prove to be costly and contentious.

Caching as a thread local helps.

However, invoking malloc/free calls with an arena argument may be a better deal.

Would using mallocx/dallocx with MALLOCX_ARENA(a) fit the bill?

**Comment by interwq** [comment]
The cost from thread-arena rebinding is probably from mutex contention. It involves 3 mutexs: control, source arena and dest arena. We can probably do something to get rid of the control lock (I suspect it's the main contributor).  

I think mallocx w/ MALLOCX_ARENA(a) does what you want, however at a small cost on the fast path (decoding the flags).

For dallocx, no need to control the arena -- it will be returned to the original arena.

Jason can probably share more insights.

**Comment by jasone** [comment]
@interwq is probably right re: high mutex contention on ```ctl_mtx```.  I just created a small diff that may help the situation: 
```diff
diff --git a/src/ctl.c b/src/ctl.c
index 535f1ea..87fd8c7 100644
--- a/src/ctl.c
+++ b/src/ctl.c
@@ -1186,14 +1186,13 @@ thread_arena_ctl(tsd_t *tsd, const size_t *mib, size_t miblen, void *oldp,
        if (oldarena == NULL)
                return (EAGAIN);

-       malloc_mutex_lock(tsd_tsdn(tsd), &ctl_mtx);
        newind = oldind = oldarena->ind;
        WRITE(newind, unsigned);
        READ(oldind, unsigned);
        if (newind != oldind) {
                arena_t *newarena;

-               if (newind >= ctl_stats.narenas) {
+               if (newind >= narenas_total_get()) {
                        /* New arena index is out of range. */
                        ret = EFAULT;
                        goto label_return;
@@ -1218,7 +1217,6 @@ thread_arena_ctl(tsd_t *tsd, const size_t *mib, size_t miblen, void *oldp,

        ret = 0;
 label_return:
-       malloc_mutex_unlock(tsd_tsdn(tsd), &ctl_mtx);
        return (ret);
 }
```

In general I prefer ```mallocx(..., MALLOCX_ARENA(a))``` because fine grained control of which allocations happen with specific arenas is otherwise difficult, or it requires lots of thread-->arena binding changes as in your case.

**Comment by yuslepukhin** [comment]
Thanks a lot to both of you. On a related note, how does tcache fares in this situation? Does it make sense to build with it or just disable it?

**Comment by interwq** [comment]
I'd imagine the benefit from tcache is too large to leave out. Even with
explicit arena control, allocations will still be satisfied from tcache
first. That means memory from previous arena will be reused for a while
(until the next GC / flush event).

It's possible to also control tcache behavior with mallocx. You can
check MALLOCX_TCACHE_*. However external synchronization is probably
needed, e.g. to determine which tcache is safe to use.

**Comment by interwq** [comment]
A bit of more thoughts: if you think some allocations can really benefit
from arena locality, and reusing memory from other arenas may hurt much, it
makes sense to mark those allocations as MALLOCX_TCACHE_NONE so that it's
always from the specified arena (bypasses tcache in that case).

**Comment by yuslepukhin** [comment]
I am more concerned at this point about memory separation. 

Meaning when an entity is unloaded within the process then the entire memory that was used by it must be made available to the process. 

For that reason I make use of reset feature for extended arenas.

This means that the application must not have any outstanding allocations for that specific arena because the memory would be yanked off from under it.

Thus I am concerned about what would happen to tcache when arena is reset because that can happen at any time.

**Comment by jasone** [comment]
You definitely need to flush any tcaches that were used with your arena prior to reset.  The three main options are:
- As suggested by @interwq, use ```MALLOCX_TCACHE_NONE``` to bypass tcache entirely.
- Manually manage (and assure no concurrent access of) tcaches via the ```tcache.{create,flush,destroy}``` mallctls, and explicitly use an appropriate tcache via ```MALLOCX_TCACHE(tc)``` wherever the arena is accessed.  This helps control which tcaches actually need reset, and prevents unrelated allocation requests from receiving regions from your arena.  This option is more work than ```MALLOCX_TCACHE_NONE```, but it provides a safe mechanism for tcache-based speedup.
- Use the ```thread.tcache.flush``` mallctl on all relevant threads prior to resetting the arena.  This is fragile, because you have to be sure that no remaining allocations made via the tcache are accessed after the reset.

**Comment by yuslepukhin** [comment]
@jasone @interwq 

- My  understanding that ` MALLOCX_TCACHE_NONE` is something to be ORed with `MALLOCX_ARENA(a)`
- Would the above be the same as a build switch --disable-tcache?

**Comment by jasone** [comment]
```--disable-tcache``` is a big hammer, and it will negatively effect performance for all allocation.  If you don't use jemalloc for anything except your arena, then it is a reasonable approach.
