### ISSUE TITLE
Implement further rtree optimizations

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#465]
The rtree code implements multiple optimizations to speed up common case lookups, especially skipping the leading 16 bits and path caching, but it could be further specialized to encode differing numbers of bits at each tree level.  Currently (assuming 4 KiB pages) we encode 64-bit addresses as {[16],16,16,4}, and 32-bit addresses as {16,4}.  We would be better served by {[16],18,18} on x64, and {10,10} or perhaps even {20} (4 MiB) on 32-bit systems.

On a related note, although `rtree_elm_lookup()` is explicitly unrolled, we dynamically initialize `rtree_t`, which forces the compiler to load run-time constants rather than encode them as compile-time immediates.  The only purpose of the current generality is testing; surely it is still possible to adequately test the code absent this pessimization.

See #360 for context.

**Comment by djwatson** [comment]
Some initial experiments with this:

* For 64bit, {[16], 16, 20} seemed to work quite well, slightly better than {[16], 18, 18}. 
* If I'm following the second comment, I didn't notice any difference trying a static rtree_t in rtree_elm_lookup.
* For a two-level tree, the path cache seemed to be slightly *worse* than no path cache.

Some microbench numbers:
master: 1.22
dev: 2.02
two-level tree, no cache: 1.89

**Comment by jasone** [comment]
Any idea why {[16], 16, 20} was faster than {[16], 18, 18}?  I'd expect them to be essentially the same speed, with only a minor difference in memory usage, depending on the application.

**Comment by djwatson** [comment]
Sorry hit enter too early and updated the comment - probably because level[1] fits in cache better.  Might just be an artifact of the microbench.

**Comment by interwq** [comment]
A couple years ago one optimization we had on a customized rtree
implementation was to mark all non-valid nodes point to a special node that
indicates lookup returns nothing (and that special node points to itself).
This can get rid of the branches when travel down though the rtree (we
always jump N times where N is the depth). The idea should also be
applicable on the rtree here?

**Comment by djwatson** [comment]
@interwq - The fast path is dalloc, where the rtree nodes must exist (or free() was passed an invalid pointer), so I don't think that would help here.

**Comment by djwatson** [comment]
Oh nevermind, I understand now - perf shows the cache misses as the expensive part, but it's worth trying removing some branches.

**Comment by interwq** [comment]
Yep. For the hot cache case, we would be able to lookup w/o any branches.

**Comment by jasone** [comment]
@interwq, that would require us to initialize the nodes rather than using sparsely backed virtual memory, so we'd potentially need to use more levels (e.g. {[16], 9, 9, 9, 9}) to keep memory usage reasonable.  Any thoughts on whether more dependent loads would outweigh the benefits of fewer branches?

**Comment by interwq** [comment]
@jasone, yes initialization would be required. However if we use hugepage
for the rtree, the memory consumption should be roughly the same even if we
don't use more levels.

IIRC the workload we had was more hot cache type, so less branches matters
much. My feeling is the more cache-miss we have, the less the branches
matter.

The other thing is, the hardware I tried the optimization on was
ivy-bridge. Not sure if newer hardware will benefit more or less from this.

**Comment by djwatson** [comment]
Experimented with a couple different caching options.  

page -> binind cache: https://gist.github.com/djwatson/88cef40ab6915ecf7cef700087d95859

page -> extent_t* cache: https://gist.github.com/djwatson/7d433985f20c45640490b08adede06de

Both reduce the time difference between master/dev by about half.  Microbench:
master: 1.22
dev: 2.02
dev+ either cache: 1.75

extent cache does better for large extents, since they don't use binind.   Interestingly, making the cache thread-local gives back almost all the difference, but I'm unsure how to flush threadlocal caches in a safe way (the test didn't do any cross-thread frees, so was safe).

dev + threadlocal cache: 1.32

 I'll give them both a test in prod and see how it goes.

**Comment by jasone** [comment]
A page -> rtree_elm_t* cache would work correctly in the absence of flushing, so you could try that thread-local.  There would be one extra dereference as compared to the page -> extent_t* cache, but otherwise it should be the same, right?

**Comment by djwatson** [comment]
Yea that would work.  Could also store the binind in the rtree leaves directly to avoid the dereference for small allocations.  Also this probably doesn't need to be threadlocal, only arena-local, since it is the arenas that share small slabs.

**Comment by bmaurer** [comment]
I was talking a bit with @djwatson about this over breakfast. in tcmalloc the radix tree (and the cache used to optimize it) was a constant source of pain.

One thing I had experimented with on tcmalloc was the idea of switching to a scheme more like the current bit masking one that jemalloc uses. unlike jemalloc my approach was to use very big "chunks" -- I think something like a GB. Any allocations that were larger than this chunk size (or any memalign requests that could not be satisfied) were given a chunked-aligned block of memory.
