### ISSUE TITLE
Signal SIGSEGV happened, use jemalloc version 4.1.0 on Android

### ISSUE THREAD

**Issue by tonyjansan** [jemalloc/jemalloc#469]
I import jemalloc version 4.1.0 to my android-platform(Kernel 3.10.84).

when executing jemalloc() in threads, the process generates fatal signals like:

```

Revision: '0'
ABI: 'arm'
pid: 754, tid: 14124
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8e0129c
    r0 e8e01298  r1 f72c89b4  r2 00000001  r3 ffffffe1
AM write failed: Broken pipe
    r4 07ffffff  r5 e8e012a0  r6 00000001  r7 00000002
    r8 40000000  r9 c09bbc08  sl 00000004  fp 00000003
    ip f72c89d0  sp e5c01d80  lr f72917d9  pc f728f9f8  cpsr 000f0030

backtrace:
pc 000499f8  /system/lib/libc.so (arena_run_reg_alloc+87)
pc 0004b7d5  /system/lib/libc.so (je_arena_tcache_fill_small+100)
pc 0005caa3  /system/lib/libc.so (je_tcache_alloc_small_hard+18)
pc 00056eb7  /system/lib/libc.so (je_malloc+574)
pc 0000ebe3  /system/lib/libutils.so
pc 0003faeb  /system/lib/libc.so (_ZL15__pthread_startPv+30)
pc 0001a095  /system/lib/libc.so (__start_thread+6)
```

if it's a known issue, and what I would do to get more details and avoid the signal.

**Comment by jasone** [comment]
There isn't enough information here to determine whether the problem is a bug in jemalloc, or an application bug.  This sort of crash is typically due to the application corrupting allocator metadata.  Do all applications crash, every time, or is it just some applications, some of the time?
