### ISSUE TITLE
Valgrind errors

### ISSUE THREAD

**Issue by spectrec** [jemalloc/jemalloc#470]
OS: CentOS 6
Arch: i386
Jemalloc version: 4.2.1 (3de035335255d553bdb344c32ffdb603816195d8)

Valgrind output ([valgrind.txt](https://github.com/jemalloc/jemalloc/files/520063/valgrind.txt)):
==2512== Invalid read of size 1
==2512==    at 0x404D7E3: arena_redzones_validate (arena.c:2485)
==2512==    by 0x404D7E3: je_arena_dalloc_junk_small (arena.c:2508)
==2512==    by 0x404DBD5: arena_dalloc_bin_locked_impl (arena.c:2901)
==2512==    by 0x404FFC5: je_arena_dalloc_bin (arena.c:2936)
==2512==    by 0x404FFC5: je_arena_dalloc_small (arena.c:2952)
==2512==    by 0x40748A2: je_arena_dalloc (arena.h:1431)
==2512==    by 0x40748A2: je_idalloctm (jemalloc_internal.h:1070)
==2512==    by 0x40748A2: quarantine_drain_one (quarantine.c:101)
==2512==    by 0x40748A2: quarantine_drain (quarantine.c:113)
==2512==    by 0x40748A2: je_quarantine (quarantine.c:136)
==2512==    by 0x403C298: je_iqalloc (jemalloc_internal.h:1085)
==2512==    by 0x403C298: ifree (jemalloc.c:1815)
==2512==    by 0x403C298: free (jemalloc.c:1933)
==2512==    by 0x808B86D: main (main.c:14859)
==2512==  Address 0x4615807 is 7 bytes after a block of size 2,048 free'd
==2512==    at 0x407EE67: je_valgrind_freelike_block (valgrind.c:33)
==2512==    by 0x403F84F: ifree (jemalloc.c:1816)
==2512==    by 0x403F84F: realloc (jemalloc.c:1858)
==2512==    by 0x80485E2: main (main.c:9)
==2512==  Block was alloc'd at
==2512==    at 0x403FA4E: realloc (jemalloc.c:1916)
==2512==    by 0x80485BD: main (main.c:7)
==2512== 
==2512== Invalid write of size 4
==2512==    at 0x402C023: memset (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==2512==    by 0x404D855: je_arena_dalloc_junk_small (arena.c:2509)
==2512==    by 0x404DBD5: arena_dalloc_bin_locked_impl (arena.c:2901)
==2512==    by 0x404FFC5: je_arena_dalloc_bin (arena.c:2936)
==2512==    by 0x404FFC5: je_arena_dalloc_small (arena.c:2952)
==2512==    by 0x40748A2: je_arena_dalloc (arena.h:1431)
==2512==    by 0x40748A2: je_idalloctm (jemalloc_internal.h:1070)
==2512==    by 0x40748A2: quarantine_drain_one (quarantine.c:101)
==2512==    by 0x40748A2: quarantine_drain (quarantine.c:113)
==2512==    by 0x40748A2: je_quarantine (quarantine.c:136)
==2512==    by 0x403C298: je_iqalloc (jemalloc_internal.h:1085)
==2512==    by 0x403C298: ifree (jemalloc.c:1815)
==2512==    by 0x403C298: free (jemalloc.c:1933)
==2512==    by 0x808B86D: main (main.c:14859)
==2512==  Address 0x4614c00 is in a rw- anonymous segment

How to reproduce:
- jemalloc: ./autogen.sh && make -j && make install
- test: gcc -ggdb3 [main.c](https://github.com/jemalloc/jemalloc/files/520000/main.txt) -o main -ljemalloc && valgrind ./main

I can't reproduce this on CentOS 6 x86_64 (even when ./configure CFLAGS=-m32 LDFLAGS=-m32).

If I run command `./configure --disable-valgrind' then valgrind says nothing, so tell me please, is this a real bug or just an invalid use of valgrind macros?

**Comment by jasone** [comment]
There is a Valgrind-related fix that will go out in 4.3.0: a6a8e40f7d24ee9f4f6abf1c03e1e0d7e3763084.  You may want to cherry-pick that fix and see if it addresses the issue you're seeing.  If not, then you've either hit an application error or an otherwise unreported jemalloc bug, in which case I will need a reproducible test case to investigate and fix it.

**Comment by spectrec** [comment]
Thanks, I cherry-pick this commit, but valgrind output wasn't changed. I have stored all allocations of my application (now it contains only malloc/realloc/free/calloc). The code is available via 
[this link](https://github.com/jemalloc/jemalloc/files/521081/main.txt).

**Comment by jasone** [comment]
This issue doesn't reproduce for me on 32-bit CentOS 6.8.  Is it possible that you're actually using a different copy of libjemalloc at run time?  Here's how I'm invoking the test program:

  ```LD_LIBRARY_PATH=$HOME/jemalloc/lib MALLOC_CONF=stats_print:true valgrind ./main```

**Comment by spectrec** [comment]
I have found the option which triggers the problem: `junk:true', now I can reproduce it on both x86 and x86_64 architectures. Here's how I'm invoking the test program:

LD_LIBRARY_PATH=lib MALLOC_CONF=junk:true valgrind ./main

**Comment by jasone** [comment]
Deallocation-time junk filling shouldn't be allowed when running inside Valgrind.  jemalloc already prohibited enabling tcache when running in Valgrind; a2539fab95008bee7fc1e4651d24b6a0427b88ce does the same for ```junk:true``` and ```junk:free```.

Thanks for digging into this and figuring out the cause.
