### ISSUE TITLE
Add an Android specific section to configure

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#471]
Even though android is close to linux, it's different enough that it would be nice to have it's own section.

I would like to suggest adding this to configure.ac:

case "${host}" in
  _linux-android_)
        CFLAGS="$CFLAGS"
        CPPFLAGS="$CPPFLAGS -D_GNU_SOURCE"
        abi="elf"
        force_tls="0"
        AC_DEFINE([JEMALLOC_HAS_ALLOCA_H])
        AC_DEFINE([JEMALLOC_PROC_SYS_VM_OVERCOMMIT_MEMORY], [ ])
        AC_DEFINE([JEMALLOC_PURGE_MADVISE_DONTNEED], [ ])
        AC_DEFINE([JEMALLOC_THREADED_INIT], [ ])
        AC_DEFINE([JEMALLOC_C11ATOMICS])
        default_munmap="0"
        ;;

**Comment by jasone** [comment]
It looks like the pattern was munged during markdown translation.  After some very confusing spelunking in config.{guess,sub}, I'm of the impression that the correct pattern is ```*-*-linux-android```.
