### ISSUE TITLE
Abysmal fork performance on Linux with transparent huge pages enabled

### ISSUE THREAD

**Issue by Shnatsel** [jemalloc/jemalloc#473]
On Linux with `/sys/kernel/mm/transparent_hugepage/enabled` set to `always` a fork-heavy program written in Rust (specifically https://github.com/mmstick/parallel) executes 80 times slower when compiled with jemalloc than it is with default libc allocator. Profiling shows 70% of the time being spent in the kernel in `copy_page` routine. 

This has been originally reported against Rust as https://github.com/rust-lang/rust/issues/36705; you can find more details there.

May be related to #467

**Comment by jasone** [comment]
This is related to #243.  Closing as a duplicate, but with a note in #243 to look here for additional context.
