### ISSUE TITLE
Can not build rel-4.3.0 on Windows

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#475]
This is due to chk protos differ in tsd vs tsdn types. This is fixed on the tip of the dev.

When building dev with my traditional with-malloc-conf=purge:decay

Tests start complaining that this is no longer an acceptab;e configuration. Could not find a good doc on the acceptable MALLOC_CONF

**Comment by jasone** [comment]
Re: ckh and tsd/tsdn, I don't see a problem (```tsdn_t``` isn't part of any ckh function prototype).  Is it possible you have a partially updated tree?

Re: purging, I removed ratio-based purging in 63b5657aa566ceab270ff6e9d4f366233d2d0b79, so the "purge" option no longer exists on the dev branch (decay is the only purge implementation).

**Comment by yuslepukhin** [comment]
@jasone Thanks,
