### ISSUE TITLE
je_witness_lock_error() assert fires

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#480]
This crashes practically non-stop so I will have to rollback but here is some data:
# First argument to the je_witness_lock_error()

0:676> dx -r1 (((Store!witness_list_t *)0x1a52f51c98))
(((RocksDBStore!witness_list_t *)0x1a52f51c98)) [Type: witness_list_t]
[+0x000] qlh_first : 0x1a52f51ca8 [Type: witness_s *]
# qlh_first from abo

0:676> dx -r1 (((RocksDBStore!witness_s *)0x1a52f51ca8))
(((RocksDBStore!witness_s *)0x1a52f51ca8)) [Type: witness_s]
[+0x000] name : 0x7ffac171a560 : "rtree_elm" [Type: char *]
[+0x008] rank : 0xb [Type: unsigned int]
[+0x010] comp : 0x7ffac18b7d60 [Type: int (__cdecl*)(witness_s *,void *,witness_s *,void *)]
[+0x018] opaque : 0x3ccf4c0000 [Type: void *]
[+0x020] link [Type: ]
# Second argument to the je_witness_lock_error()

0:676> dx -r1 (((Store!witness_s *)0x1dae952d58))
(((RocksDBStore!witness_s *)0x1dae952d58)) [Type: witness_s]
[+0x000] name : 0x7ffac171a3d8 : "arena_extent_cache" [Type: char *]
[+0x008] rank : 0xa [Type: unsigned int]
[+0x010] comp : 0x0 [Type: int (__cdecl*)(witness_s *,void *,witness_s *,void *)]
[+0x018] opaque : 0x0 [Type: void *]
[+0x020] link [Type: ]

0:676> kp~15
# Child-SP RetAddr Call Site

00 0000001db718edc0 00007ffac18aa08a ucrtbase!abort(void)+0x4e [d:\th\minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 77]
01 0000001db718edf0 00007ffac18aa481 Store!je_witness_lock_error(struct witness_list_t \* witnesses = 0x0000001a52f51c98, struct witness_s \* witness = 0x0000001dae952d58)+0x6a [c:\dev\oss\repo.jemalloc\src\witness.c @ 29]
02 0000001db718ee20 00007ffac18ac919 Store!je_witness_lock(struct tsdn_s \* tsdn = , struct witness_s \* witness = 0x0000001dae952d58)+0xb1 [c:\dev\oss\repo.jemalloc\include\jemalloc\internal\witness.h @ 227] 03 0000001db718ee50 00007ffac18aadeb Store!je_extent_dalloc(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, struct extent_s \* extent = 0x0000001c12ca0840)+0x29 [c:\dev\oss\repo.jemalloc\src\extent.c @ 74]
04 (Inline Function) ---------------- Store!extent_leak+0xe 05 0000001db718ee80 00007ffac18ac703 Store!extent_alloc_wrapper_hard(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, struct extent_hooks_s *\* r_extent_hooks = <Value unavailable error>, void \* new_addr = 0x0000000000000000, unsigned int64 usize = 0x1c000, unsigned int64 pad = 0x1000, unsigned int64 alignment = 0x40, bool \* zero = 0x0000001db718f090, bool \* commit = 0x0000001db718efc0, bool slab = false)+0x16b [c:\dev\oss\repo.jemalloc\src\extent.c @ 717]
06 0000001db718eef0 00007ffac18b1ed0 Store!je_extent_alloc_wrapper(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, struct extent_hooks_s *\* r_extent_hooks = 0x0000001db718f068, void \* new_addr = 0x0000000000000000, unsigned int64 usize = 0x1c000, unsigned int64 pad = 0x1000, unsigned int64 alignment = 0x40, bool \* zero = 0x0000001db718f090, bool \* commit = 0x0000001db718efc0, bool slab = false)+0xe3 [c:\dev\oss\repo.jemalloc\src\extent.c @ 740]
07 0000001db718ef70 00007ffac18b30ff Store!arena_extent_alloc_large_hard(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, struct extent_hooks_s *\* r_extent_hooks = , unsigned int64 usize = 0x1c000, unsigned int64 alignment = 0x40, bool \* zero = 0x0000001db718f090)+0x60 [c:\dev\oss\repo.jemalloc\src\arena.c @ 314] 08 0000001db718efe0 00007ffac18b8ae9 Store!je_arena_extent_alloc_large(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, unsigned int64 usize = 0x1c000, unsigned int64 alignment = 0x40, bool \* zero = 0x0000001db718f090)+0xff [c:\dev\oss\repo.jemalloc\src\arena.c @ 350]
09 0000001db718f060 00007ffac18b89fe Store!je_large_palloc(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, unsigned int64 usize = 0x1c000, unsigned int64 alignment = 0x40, bool zero = false)+0xc9 [c:\dev\oss\repo.jemalloc\src\large.c @ 37]
0a 0000001db718f0b0 00007ffac18b359a Store!je_large_malloc(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, unsigned int64 usize = 0x1c000, bool zero = false)+0x6e [c:\dev\oss\repo.jemalloc\src\large.c @ 13]
0b 0000001db718f0f0 00007ffac18b34b5 Store!je_arena_malloc_hard(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, unsigned int64 size = 0x1c000, unsigned int ind = 0x2f, bool zero = false)+0xba [c:\dev\oss\repo.jemalloc\src\arena.c @ 1221]
0c 0000001db718f120 00007ffac189ece2 Store!je_arena_malloc(struct tsdn_s \* tsdn = 0x0000001a52f51c08, struct arena_s \* arena = 0x0000001dae950000, unsigned int64 size = 0x1c000, unsigned int ind = 0x2f, bool zero = false, struct tcache_s \* tcache = 0x0000000000000000, bool slow_path = true)+0x125 [c:\dev\oss\repo.jemalloc\include\jemalloc\internal\arena.h @ 523] 0d 0000001db718f170 00007ffac189ea8c Store!imallocx_no_prof(struct tsd_s \* tsd = 0x0000001a52f51c08, unsigned int64 size = , int flags = 0n136, unsigned int64 \* usize = 0x0000001db718f270, bool slow_path = true)+0x142 [c:\dev\oss\repo.jemalloc\src\jemalloc.c @ 2009] 0e 0000001db718f1d0 00007ffac18a0253 Store!imallocx_body(unsigned int64 size = 0x1bc87, int flags = 0n142606336, struct tsdn_s *\* tsdn = 0x0000001db718f278, unsigned int64 \* usize = 0x0000001db718f270, bool slow_path = true)+0x13c [c:\dev\oss\repo.jemalloc\src\jemalloc.c @ 2049] 0f 0000001db718f220 00007ffa`c1829795 Store!je_mallocx(unsigned int64 size = , int flags = )+0x63 [c:\dev\oss\repo.jemalloc\src\jemalloc.c @ 2068]

**Comment by jasone** [comment]
b93f63b3ebab068efdcfa2ea3e19055bfc2e7f82 fixes the locking error reported by witness, but it may be that you were hitting this code path due to another issue, so you may encounter a different failure mode with this fix in place.
