### ISSUE TITLE
4.2.1: sdallocx asserting usize is not == isalloc()

### ISSUE THREAD

**Issue by madscientist** [jemalloc/jemalloc#483]
I've been looking into supporting sized delete in my C++ codebase (using GCC 6.2.0) and jemalloc.  I create inlined global operator delete() for sized deletions which invokes sdallocx() with a flags argument of 0 (I don't use arenas or anything).  Without using sized delete everything works perfectly.  Much of the time when I do use sized delete things work OK.

But I have reproducible cases where the assert() at jemalloc.c:2546 is firing:

```
    usize = inallocx(tsd_tsdn(tsd), size, flags);
>   assert(usize == isalloc(tsd_tsdn(tsd), ptr, config_prof));
```

There's nothing too magical about this situation; the C++ code that is running is just:

```
    delete node->object;
```

and the size being passed in is 56:

```
#3  0x00000000005619a7 in operator delete (ptr=0x7ffff2921330, size=56)
```

The value of usize computed by inallocx() is 64, but the value computed by isalloc() is 80 (I modified the jemalloc code to store that value to make it easier to get):

```
#2  0x0000000000f8654c in sdallocx (ptr=0x7ffff2921330, size=56, flags=0)
(gdb) p usize
$3 = 64
(gdb) p ia
$4 = 80
```

Is this an instance of a known issue?  Maybe something I'm doing isn't valid, or there's a known issue with sdallocx() in 4.2.1?  If this is a new issue I can try to dig into it further and maybe test against a newer Git branch version.

**Comment by madscientist** [comment]
Well, the size of the object is 56 bytes, according to GDB:

    (gdb) p sizeof(*node->object)
    $6 = 56

I don't know for sure what size was asked of operator new, but as far as I can see nothing subclasses this class so I have no reason to believe it was anything other than 56 bytes.  OK, given that this is not something you're familiar with I'll dig deeper.

**Comment by djwatson** [comment]
I posted jemalloc patches for sized delete in #476 .   If you provide your repro I'd be happy to take a look.

**Comment by madscientist** [comment]
I'll have to put this aside for a day or so due to another emergency.

I found a different core (same assert in jemalloc).  I looked at that one and what happened there was that we had a non-virtual dtor in a parent class.  In the child, there was NO dtor (or ctor) defined.  In neither class was there any virtual function; the child just added a bit more data (POD) and a few more methods, but no overloaded methods.  Common wisdom in some C++ circles is "if you have any virtual functions then your dtor must be virtual", which implies that if you have no virtual functions then your dtor doesn't need to be virtual.  But in the face of sized delete that wisdom is clearly wrong; even if the subclass dtors aren't needed, the delete itself will do the wrong thing.  Changing the dtor here to be virtual fixed that crash.  Sutter's Virtuality Guideline #4 is obviously correct and important, if you want to use sized delete operators.

I haven't been able to get back to the original (which I didn't think was inherited from, but I'll have to look more carefully).  It's possible this is all down to errors in the code, which were not evident with a normal delete operator.

**Comment by madscientist** [comment]
Sure enough, I found 2 instances of dtors which should have been virtual but weren't, and two instances of `delete foo` that should have been `delete [] foo`.  Now my tests all pass with no problems.

Sorry for the noise when it was our own bad code :(

**Comment by jasone** [comment]
Thanks for digging in and reporting back.  This will be useful background info when others hit the same problem.
