### ISSUE TITLE
Segmantation fault during mallocx test on Linux i586

### ISSUE THREAD

**Issue by ismail** [jemalloc/jemalloc#492]
This is on openSUSE Tumbleweed i586 on a real machine:

```
abuild@seferogullari:/home/abuild/rpmbuild/BUILD/jemalloc-4.3.0> make check_integration_decay
MALLOC_CONF="purge:decay,decay_time:-1" /bin/sh test/test.sh test/integration/aligned_alloc test/integration/allocated test/integration/sdallocx test/integration/mallocx test/integration/MALLOCX_ARENA test/integration/overflow test/integration/posix_memalign test/integration/rallocx test/integration/thread_arena test/integration/thread_tcache_enabled test/integration/xallocx test/integration/chunk
=== test/integration/aligned_alloc ===
test_alignment_errors: pass
test_oom_errors: pass
test_alignment_and_size: pass
--- pass: 3/3, skip: 0/3, fail: 0/3 ---

=== test/integration/allocated ===
test_main_thread: pass
test_subthread: pass
test_main_thread: pass
test_subthread: pass
test_main_thread: pass
--- pass: 5/5, skip: 0/5, fail: 0/5 ---

=== test/integration/sdallocx ===
test_basic: pass
test_alignment_and_size: pass
--- pass: 2/2, skip: 0/2, fail: 0/2 ---

=== test/integration/mallocx ===
test_overflow: pass
test/test.sh: line 22: 21566 Segmentation fault      (core dumped) ${t} /home/abuild/rpmbuild/BUILD/jemalloc-4.3.0/ /home/abuild/rpmbuild/BUILD/jemalloc-4.3.0/
Test harness error
make: *** [Makefile:404: check_integration_decay] Error 1
````

**Comment by jasone** [comment]
This is probably due to an integer overflow for maximal or over-sized allocation requests, but I've fixed multiple related issues over the past month, and this doesn't currently reproduce on the 32-bit systems I've tested on (CentOS 6, Ubuntu 14.04).  Can you try a build with ```--enable-debug``` specified to see if we get an assertion failure that helps narrow down the problem?  Also, what  compiler (and version) are you using?

**Comment by ismail** [comment]
Indeed;

```
=== test/integration/mallocx ===
test_overflow: pass
<jemalloc>: include/jemalloc/internal/stats.h:184: Failed assertion: "cactive - size < cactive"
```

Using ```gcc version 6.2.1 20160830 [gcc-6-branch revision 239856] (SUSE Linux)```

**Comment by jasone** [comment]
Thanks @ismail.  I don't have gcc 6 set up anywhere, so I'm just setting up an i586 Tumbleweed system to make sure I can reproduce this.

**Comment by jasone** [comment]
This does not reproduce on the i586 Tumbleweed system I set up today.  The compiler matches that of the original problem report.  I tried both a direct git checkout, and the 4.3.0 release tarball, both with the same result.  This is as close to matching the environment as is feasible, with the possible exception of RAM (I tried 2 GiB and 512 MiB).

Any other info you can provide?  I'm planning roll the 4.3.1 release within the hour, so this is going to get punted unless I can make some progress on it within the hour.

**Comment by jasone** [comment]
@ismail, it looks like there's a real bug here, so please do follow up if you can with info that allows us to reproduce and fix this.  Thanks!

**Comment by ismail** [comment]
One thing you can try setting

```
export MALLOC_CHECK_=2
export MALLOC_PERTURB_=63
```

before running tests, which is the default in our build systems, there might be a memory corruption somewhere

**Comment by jasone** [comment]
Marking this as a duplicate of #497 and closing.
