### ISSUE TITLE
4.3.0 build failure with Xcode 8.1 and macOS 10.11

### ISSUE THREAD

**Issue by ilovezfs** [jemalloc/jemalloc#494]
Full build log
https://gist.github.com/ilovezfs/20d854eb604f17181e0089b28ed2470c
(original is here but the link will die at some point https://bot.brew.sh/job/Homebrew%20Core/10770/version=el_capitan/consoleText)

The error is
```
 dyld: lazy symbol binding failed: Symbol not found: _os_unfair_lock_lock
```

The problem is that `os_unfair_lock_lock` is defined in the Xcode 8.1 SDK headers, but is only actually available on Sierra (10.12). I've worked around the problem by setting `je_cv_os_unfair_lock` equal to `"no"` in the environment, but it should be fixed properly in configure.

```
    #  dyld: lazy symbol binding failed: Symbol not found: _os_unfair_lock_lock
    if MacOS.version == :el_capitan && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
      ENV["je_cv_os_unfair_lock"] = "no"
    end
```

See https://github.com/Homebrew/homebrew-core/pull/6625.

**Comment by jasone** [comment]
Somehow this slipped past me for the 4.3.1 release.  I recall seeing a report with less information, and I thought I responded that it didn't make sense to me, but cannot find an audit trail.  I will be sure to develop a fix before upgrading my other Apple dev machine.

**Comment by ilovezfs** [comment]
@jasone Thanks!

**Comment by jasone** [comment]
```JE_RUNNABLE()``` causes general cross-compilation portability issues.  I'm going to revert those diffs and document in the INSTALL file how to use autoconf's ```--cache``` option to work around broken environments.
