### ISSUE TITLE
realloc'd memory misreported as leak

### ISSUE THREAD

**Issue by chenguo** [jemalloc/jemalloc#499]
I had a doozy with this one, Valgrind didn't see anything but jemalloc found a leak in a function that calls `realloc()`. Finally I tried out the master branch and realized maybe dev has a bug.

Reduced sample program:

```C
#include <stdlib.h>

int main(int argc, char** argv) {
  void *a = malloc(8);
  a = realloc(a, 16);
  free(a);
}
```
compiled simply with `g++ main.cc`. `jemalloc` was configured with `--enable-prof` before compiling.

Output linking against master `libjemalloc.so`
```
heap_v2/1
  t*: 0: 0 [0: 0]
  t0: 0: 0 [0: 0]

MAPPED_LIBRARIES:
00400000-00401000 r-xp 00000000 00:64 1627323                            /home/chen/code/place-attachment/deps/tile-querier/common/test/mem-dbg/a.out
00600000-00601000 r--p 00000000 00:64 1627323                            /home/chen/code/place-attachment/deps/tile-querier/common/test/mem-dbg/a.out
00601000-00602000 rw-p 00001000 00:64 1627323                            /home/chen/code/place-attachment/deps/tile-querier/common/test/mem-dbg/a.out
```

Output linking against dev `libjemalloc.so`:
```
heap_v2/1
  t*: 1: 8 [0: 0]
  t0: 1: 8 [0: 0]
@ 0x7f1ccdc4e8ff 0x7f1ccdc244ac 0x4005d6 0x7f1ccd874f45 0x4004f9
  t*: 1: 8 [0: 0]
  t0: 1: 8 [0: 0]

MAPPED_LIBRARIES:
00400000-00401000 r-xp 00000000 00:64 1627873                            /home/chen/code/place-attachment/deps/tile-querier/common/test/mem-dbg/a.out
00600000-00601000 r--p 00000000 00:64 1627873                            /home/chen/code/place-attachment/deps/tile-querier/common/test/mem-dbg/a.out
00601000-00602000 rw-p 00001000 00:64 1627873                            /home/chen/code/place-attachment/deps/tile-querier/common/test/mem-dbg/a.out
```

**Comment by jasone** [comment]
Thank you for the clear report.  This should be straightforward to find and fix.

**Comment by guilt** [comment]
Can this be fixed earlier? I require to instrument many libraries with jemalloc, and I rely on this profiling data from jemalloc.

**Comment by jasone** [comment]
Do I understand correctly that this bug only applies to the dev branch?  The 5.0.0 is the next release that will be based on that branch, so we're already planning on a fix before next release.  If you mean that you want a fix right away, I personally have other issues that are higher priority for me at the moment; if you are able to diagnose the issue and develop a patch I'll be happy to review and integrate it.
