### ISSUE TITLE
Rev 45f83a2 broke cross-compiles

### ISSUE THREAD

**Issue by rvandermeulen** [jemalloc/jemalloc#502]
While testing the rc-4.4.0 branch with Firefox, I found that our Android and OSX builds are currently broken.

It's the same failure for both:
https://treeherder.mozilla.org/logviewer.html#?job_id=31170068&repo=try

memory/jemalloc/src> checking whether Darwin os_unfair_lock_*() is runnable... configure: error: in `/builds/slave/try-and-api-15-000000000000000/build/src/obj-firefox/memory/jemalloc/src':
memory/jemalloc/src> configure: error: cannot run test program while cross compiling
memory/jemalloc/src> See `config.log' for more details
DEBUG: <truncated - see config.log for full output>
DEBUG: #define posix_fallocate innocuous_posix_fallocate
DEBUG: #include <assert.h>
DEBUG: #undef posix_fallocate
DEBUG: /* Override any gcc2 internal prototype to avoid an error.  */
DEBUG: /* We use char because int might match the return type of a gcc2
DEBUG:     builtin and then its argument prototype would still apply.  */
DEBUG: char posix_fallocate();
DEBUG:
DEBUG: int main() {
DEBUG:
DEBUG: /* The GNU C library defines this for functions which it implements
DEBUG:     to always fail with ENOSYS.  Some functions are actually named
DEBUG:     something starting with __ and the normal name is an alias.  */
DEBUG: #if defined (__stub_posix_fallocate) || defined (__stub___posix_fallocate)
DEBUG: choke me
DEBUG: #else
DEBUG: posix_fallocate();
DEBUG: #endif
DEBUG:
DEBUG: ; return 0; }
ERROR: old-configure failed

**Comment by jasone** [comment]
The ```JE_RUNNABLE()``` macro uses ```AC_CACHE_CHECK()```, which AFAIK should make it possible to specify a cache file with the result that you want for the target machine.

**Comment by glandium** [comment]
That adds burden on the people doing cross-builds, even when what they're doing has nothing to do with Darwin (which is the case of the android builds).

More generally, 45f83a2ac6a9cd3b21675766127ee85910e54156 doesn't look like the right thing to do. Except if Apple screw up backwards compatibility, if using os_unfair_lock_* compiles, it means the osx target for the SDK/compiler is such that os_unfair_lock_* is available. If someone building on OSX 10.12 and/or with a recent SDK wants to produce a binary that can run on older OSX versions, they need to set the `MACOSX_DEPLOYMENT_TARGET` environment variable or the -mmacosx-version-min.

http://stackoverflow.com/questions/6591988/best-practice-for-osx-10-x-backwards-compatability

(There are some cases where they however declare weak symbols, which you'd need to `if ()` before using, and without access to the corresponding headers, I can't tell whether that's the case here, but I doubt it)

What I'm saying is that, to me, the previous code, using JE_COMPILABLE was just fine, and the build environment of the user reporting #494 probably needs fixing.

**Comment by jasone** [comment]
Thanks @glandium, your explanation convinced me.  I'll revert the ```JE_RUNNABLE()``` diffs and document in how to use ```--cache``` to work around broken build environment issues.

**Comment by jasone** [comment]
dev: 4066b4ef57c3b14bb57696539455809ce4a714c3, 9b94c015af7fe7f86b19c71059be8758afd06fe3
rc-4.4.0: 2a24dc24761b9b5b8f9af30618d2f4fb17d59a59, 8e3fb7f4172b6b98d68ae605d0cc69cde3937d94

**Comment by glandium** [comment]
So, I upgraded Xcode on my mac to see what it was all about, and it turns out `os_unfair_lock_*` is defined as `__attribute__((availability(macosx,introduced=10.12)))` which has the effect of making it available... as a weak symbol whatever version of macosx is targeted.

So, in fact, the JE_COMPILABLE test will always pass, whatever `MACOSX_DEPLOYMENT_TARGET` is.

Now, it appears there is also an alternative to running an executable to know whether that it's actually available or not, depending on the `MACOSX_DEPLOYMENT_TARGET`: Linking with `-Wl,-no_weak_imports`, which is a OSX-only ld flag, that is not available until Xcode 8, but fails the linkage when `MACOSX_DEPLOYMENT_TARGET` is below the `availability` version.

**Comment by jasone** [comment]
I just experimented a bit with ```JE_CFLAGS_APPEND([-Wl,-no_weak_imports])```, and found that on Ubuntu 16.04 it "succeeds", then causes later configure tests to fail with

```/usr/bin/ld: cannot find -lgcc_s```

Unfortunately, I was forced to update my last OS X 10.11 system to 10.12 last night, so I can't test whether this would do the right thing if limited to OS X.
