### ISSUE TITLE
Allocating in Lower 32-bit Address Space Only?

### ISSUE THREAD

**Issue by sprinkle131313** [jemalloc/jemalloc#506]
Is there a way to allocate memory in the lower 32-bit address space on a 64-bit system?

**Comment by jasone** [comment]
Yes, you can change the precedence of [dss](http://jemalloc.net/jemalloc.3.html#opt.dss) on systems that support the ```sbrk(2)``` system call.  The simplest way to try this without modifying the application is to set ```MALLOC_CONF=dss:primary``` in the environment prior to program invocation.
