### ISSUE TITLE
A question about malloc_usable_size returned value meaning.

### ISSUE THREAD

**Issue by freak82** [jemalloc/jemalloc#510]
Hi,

I would like to ask about the exact meaning of the value returned by malloc_usable_size.
For example, if I do malloc(4120) which is 4KB + 24 and then pass the returned pointer to malloc_usable_size it returns 8192 according to my simple test.
Does that mean that the actual allocation is 8KB and the remaining bytes (8192 - 4120) are going to be unused/wasted in case of such allocation?
My case is that I'll need to allocate a lot of objects/blocks of 4 or 8KB with some header (24 bytes) in them and I'm not sure if this won't provoke a lot of unused (allocated but inaccessible) memory, if the above is true.

Thanks,
Pavel.

**Comment by jasone** [comment]
Your interpretation of the ```malloc_usable_size()``` output is correct.  However, the result suggests that you are using a rather old version of jemalloc.  Since 4.0.0 jemalloc returns 5 KiB rather than 8 KiB in that case (see [size classes](http://jemalloc.net/jemalloc.3.html#size_classes)).
