### ISSUE TITLE
4.3.1 assertion failure arena.c:311

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#511]
While trying to verify https://github.com/jemalloc/jemalloc/issues/508 the below brought down processes on the pack of the machines. I may still have dumps and can dig at it deeper.

Child-SP          RetAddr           Call Site
000000ae`317ce080 00007ffb`f57a5cbd ucrtbase!abort(void)+0x58 [d:\rs2\minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 77]
000000ae`317ce0b0 00007ffb`f57a688f Store!arena_run_page_validate_zeroed(struct arena_chunk_s * chunk = <Value unavailable error>, unsigned int64 run_ind = <Value unavailable error>)+0x4d [c:\dev\oss\pool.jemalloc\src\arena.c @ 311]
000000ae`317ce0e0 00007ffb`f57a382b Store!arena_run_split_small(struct arena_s * arena = <Value unavailable error>, struct arena_run_s * run = <Value unavailable error>, unsigned int64 size = 0x3000, unsigned int binind = 0xe)+0x1ef [c:\dev\oss\pool.jemalloc\src\arena.c @ 495]
000000ae`317ce140 00007ffb`f57a3776 Store!arena_run_alloc_small_helper(struct arena_s * arena = 0x0000021d`c71c0080, unsigned int64 size = 0x3000, unsigned int binind = 0xe)+0x3b [c:\dev\oss\pool.jemalloc\src\arena.c @ 1112]
000000ae`317ce170 00007ffb`f57a0bd4 Store!arena_run_alloc_small(struct tsdn_s * tsdn = 0x00000229`7529e188, struct arena_s * arena = 0x0000021d`c71c0080, unsigned int64 size = 0x3000, unsigned int binind = 0xe)+0xc6 [c:\dev\oss\pool.jemalloc\src\arena.c @ 1130]
000000ae`317ce1a0 00007ffb`f57a0a20 Store!arena_bin_nonfull_run_get(struct tsdn_s * tsdn = 0x00000229`7529e188, struct arena_s * arena = 0x0000021d`c71c0080, struct arena_bin_s * bin = 0x0000021d`c71c10e0)+0xd4 [c:\dev\oss\pool.jemalloc\src\arena.c @ 2252]
000000ae`317ce1e0 00007ffb`f57a2456 Store!arena_bin_malloc_`hard(struct tsdn_s * tsdn = 0x00000229`7529e188, struct arena_s * arena = 0x0000021d`c71c0080, struct arena_bin_s * bin = 0x0000021d`c71c10e0)+0x90 [c:\dev\oss\pool.jemalloc\src\arena.c @ 2294]
000000ae`317ce230 00007ffb`f57a946d Store!arena_malloc_small(struct tsdn_s * tsdn = 0x00000229`7529e188, struct arena_s * arena = 0x0000021d`c71c0080, unsigned int binind = <Value unavailable error>, bool zero = false)+0xb6 [c:\dev\oss\pool.jemalloc\src\arena.c @ 2509]
000000ae`317ce280 00007ffb`f57a93a5 Store!je_arena_malloc_hard(struct tsdn_s * tsdn = 0x00000229`7529e188, struct arena_s * arena = 0x0000021d`c71c0080, unsigned int64 size = 0x180, unsigned int ind = 0xe, bool zero = false)+0x9d [c:\dev\oss\pool.jemalloc\src\arena.c @ 2624]
000000ae`317ce2b0 00007ffb`f5790f42 Store!je_arena_malloc(struct tsdn_s * tsdn = 0x00000229`7529e188, struct arena_s * arena = 0x0000021d`c71c0080, unsigned int64 size = 0x180, unsigned int ind = 0xe, bool zero = false, struct tcache_s * tcache = 0x00000000`00000000, bool slow_path = true)+0x125 [c:\dev\oss\pool.jemalloc\include\jemalloc\internal\arena.h @ 1346]
000000ae`317ce300 00007ffb`f5790ceb Store!imallocx_no_prof(struct tsd_s * tsd = 0x00000229`7529e188, unsigned int64 size = <Value unavailable error>, int flags = 0n131, unsigned int64 * usize = 0x000000ae`317ce408, bool slow_path = true)+0x142 [c:\dev\oss\pool.jemalloc\src\jemalloc.c @ 2205]
000000ae`317ce360 00007ffb`f579276a Store!imallocx_body(unsigned int64 size = 0x178, int flags = 0n137363456, struct tsdn_s ** tsdn = 0x000000ae`317ce400, unsigned int64 * usize = 0x000000ae`317ce408, bool slow_path = true)+0x14b [c:\dev\oss\pool.jemalloc\src\jemalloc.c @ 2246]
000000ae`317ce3b0 00007ffb`f571c113 Store!je_mallocx(unsigned int64 size = <Value unavailable error>, int flags = <Value unavailable error>)+0xfa [c:\dev\oss\pool.jemalloc\src\jemalloc.c @ 2265]

**Comment by yuslepukhin** [comment]
Looks like the assert fails when attempting to verify that a piece of memory is zeroed out. But the the value of zero is false and consistently propagated up the stack.

**Comment by jasone** [comment]
Are custom chunk hooks in use?  At a glance this looks like it could be caused by the same thing as for #512.  Is the operating environment is similar between the two issues?

**Comment by yuslepukhin** [comment]
@jasone The operating env and the binaries are the same. But no custom hooks.

**Comment by yuslepukhin** [comment]
After some fixes are in place on our end this no longer reproes
