### ISSUE TITLE
Crashes while attempting to fill newly allocated memory

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#512]
This happens regularly with 4.2.1 and exhibits the same behavior with 4.3.1. The stacks below are from 4.3.1 and demonstrate the problem with small and large allocations.

[Alloc_small_memset.txt](https://github.com/jemalloc/jemalloc/files/608060/Alloc_small_memset.txt)
[Alloc_large_memset.txt](https://github.com/jemalloc/jemalloc/files/608061/Alloc_large_memset.txt)

**Comment by yuslepukhin** [comment]
This happens only when allocations are performed via je_mallox and not when with je_malloc

**Comment by jasone** [comment]
Can you please provide a repro program for this?  I can guess from the backtraces that custom arenas are involved, and that ```MALLOC_CONF=zero:true``` is set, but that leaves a lot of possible explanations.

**Comment by yuslepukhin** [comment]
@jasone Will try providing a program. MALLOC_CONF is not set. The dump shows the same. Filling with junk is set.

Build settings --malloc-conf=purge:decay --disable-tcache --enable-debug

**Comment by yuslepukhin** [comment]
No longer reproes. WIll close for now.
