### ISSUE TITLE
Create specific way to disable syscall calls.

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#517]
For security purposes, syscall might be modified to filter out any but a few whitelisted system calls. The 4.3.1 codebase uses syscall if it has been defined, so might trigger some syscalls that we don't want to allow.

It's possible to disable this by undefining the JEMALLOC_HAVE_SYSCALL. However, that's set by the configure script itself, and it's not as clear what will happen if it's not defined. It would be nice if there was a configure option, or define that could be used to specifically disable the use of syscalls.

**Comment by jasone** [comment]
For the time being, the cleanest workaround is to do something like:

```echo "je_cv_syscall=no" > config.cache && ./configure -C```

A ```--disable-syscall``` option seems reasonable though.
