### ISSUE TITLE
Chromium crashes with "LD_PRELOAD=/usr/lib/libjemalloc.so"

### ISSUE THREAD

**Issue by enihcam** [jemalloc/jemalloc#520]
Description:
Chromium crashes with "LD_PRELOAD=/usr/lib/libjemalloc.so".

Additional info:
Archlinux

Steps to reproduce:
pacman -S jemalloc
set 'LD_PRELOAD=/usr/lib/libjemalloc.so'
Start chromium

**Comment by jasone** [comment]
I've never worked on Chromium, but I'm guessing that it has a version of tcmalloc built in.  If so, then this is most likely due to mixed allocator use, i.e. not a jemalloc bug.

**Comment by jasone** [comment]
Closing under the assumption that this is not due to a jemalloc bug.  If you determine otherwise, please reopen with additional information.
