### ISSUE TITLE
Please update jemalloc/jemalloc-cmake for 4.4.0

### ISSUE THREAD

**Issue by nicolaichuk** [jemalloc/jemalloc#527]
Please update https://github.com/jemalloc/jemalloc-cmake for 4.4.0

**Comment by yuslepukhin** [comment]
I can updated it to 4.3.0. I have not seen 4.4.0 release nor do I have it ready.

**Comment by nicolaichuk** [comment]
On this page https://github.com/jemalloc/jemalloc/releases says that latest release is 4.4.0. (4 dec 2016)

**Comment by yuslepukhin** [comment]
@nicolaichuk Pushed 4.3.1 integration. Do not have 4.4.0 yet.

**Comment by nicolaichuk** [comment]
@yuslepukhin, thanks for the update to version 4.3.1.

But I can not understand why you do not have 4.4.0 yet?
This issue #498 "4.4.0 release" was been close  12 days ago.
And was been create tag 4.4.0 https://github.com/jemalloc/jemalloc/tags

**Comment by yuslepukhin** [comment]
@nicolaichuk Well, mostly because I have to do my day job and it does not require 4.4.0 :) jemalloc-cmake is an experiment with hopes that some day it will be on par with the mainline. You are welcome to contribute on your spare time.

**Comment by nicolaichuk** [comment]
@yuslepukhin, thanks for answer.

**Comment by nicolaichuk** [comment]
@yuslepukhin 

please create tag "jemalloc-cmake.4.3.1" https://github.com/jemalloc/jemalloc-cmake/tags
because jemalloc_version incorect parse old "jemalloc-cmake.4.2.1" version.

and apply PR https://github.com/jemalloc/jemalloc-cmake/pull/1

**Comment by yuslepukhin** [comment]
@nicolaichuk The tag has been created.

**Comment by yuslepukhin** [comment]
@nicolaichuk The tag has been created.

**Comment by nicolaichuk** [comment]
Please update https://github.com/jemalloc/jemalloc-cmake for 5.0.1
