### ISSUE TITLE
jemalloc opens /proc/sys/vm/overcommit_memory without O_CLOEXEC

### ISSUE THREAD

**Issue by nickkral** [jemalloc/jemalloc#528]
src/pages.c has the following lines:

```
  #if defined(JEMALLOC_HAVE_SYSCALL) && defined(SYS_open)
          fd = (int)syscall(SYS_open, "/proc/sys/vm/overcommit_memory", O_RDONLY);
  #else
          fd = open("/proc/sys/vm/overcommit_memory", O_RDONLY);
  #endif
          if (fd == -1)
                  return (false); /* Error. */
```
To avoid file descriptor leakage within multithreaded programs, it's recommended that all open calls also include the O_CLOEXEC flag, eg:

`  fd = open("/proc/sys/vm/overcommit_memory", O_RDONLY | O_CLOEXEC);
`

Even if jemalloc doesn't have this particular threading issue, O_CLOEXEC is still recommended from a code cleanliness point of view.

**Comment by jasone** [comment]
This is related to #501, since we'll be creating wrappers for all syscalls.
