### ISSUE TITLE
Atomics cleanup

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#532]
The atomics implementation should be made to be closer to the C11 API. The should let us pick up some simple wins (example: currently an atomic load does a fetch-add of 0; only a plain load is necessary in most cases).

**Comment by jasone** [comment]
Will we get 64-bit atomic ops on all platforms as part of this?  See #621 for context.

**Comment by davidtgoldblatt** [comment]
I think in general not all 32-bit platforms have 64-bit atomic ops.

**Comment by davidtgoldblatt** [comment]
Completed in #664.
