### ISSUE TITLE
Drop requirement for parentheses around return arguments

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#540]
Allow e.g.
```C
return (x);
```
to be just
```C
return x;
```
This removes a style constraint inherited from [FreeBSD's style(9)](https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9) that probably dates back to early C compilers with weakly defined operator precedence.

**Comment by IndolentPangolin** [comment]
style(9) has that rule to allow for debugging information, e.g.:

#define return(x) do { printf("return %d at %s:%d\n", (x), __FILE__, __LINE__); return (x); } while (0)

It's not a great motivation, but that's what it's in the style guide.

**Comment by jasone** [comment]
Ah, good to know!
