### ISSUE TITLE
Wiki links broken

### ISSUE THREAD

**Issue by Rufflewind** [jemalloc/jemalloc#553]
Lots of links point to `http://www.canonware.com/download/jemalloc/jemalloc-latest/doc/jemalloc.html` but that doesn't exist anymore.

See for example: [Use Case: Heap Profiling](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling).

**Comment by jasone** [comment]
Thanks for reporting this.  I just went through the wiki and converted all the links to http://jemalloc.net/jemalloc.3.html .

**Comment by Rufflewind** [comment]
Thanks for the quick fix!
