### ISSUE TITLE
build jemalloc for Windows Failed,Can't Generate header files

### ISSUE THREAD

**Issue by denniszong** [jemalloc/jemalloc#556]
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>sh -c "CC=cl /jemalloc-dev/autogen.sh"
autoconf
autoconf-2.69: error: no input file
Error 0 in autoconf

D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>

and how to do it? i'm a newer for cygwin or shell command!
use the follow command
sh -c "/jemalloc-dev/autogen.sh CC=cl --enable-lazy-lock=no"

i got the same result

**Comment by rustyx** [comment]
First `cd` to the directory where your jemalloc is located

For example, if you have it in `D:\jemalloc-dev`

```
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>cd \jemalloc-dev
D:\jemalloc-dev>
```
Then run:
```
D:\jemalloc-dev>sh ./autogen.sh CC=cl --enable-lazy-lock=no
```

Note you can add more parameters to this command, for example `--with-malloc-conf=lg_chunk:20` sets the chunk to 1MB for better performance (default on Windows is 64KB).

**Comment by mike07026** [comment]
I follow the guide and try to build jemalloc 5.0.1 on Windows 10

```
sh ./autogen.sh CC=cl --enable-lazy-lock=no
autoconf
autoconf: configure.in: No such file or directory
Error 0 in autoconf
```

I found "configure.ac" in the directory, but not "configure.in". Is it missing the "configure.in" file in release source package ?

**Comment by rustyx** [comment]
Your autoconf is probably too old. Upgrade to version 2.69 or later.

To debug the autoconf process you can try `sh autoconf -i -v`

**Comment by mike07026** [comment]
Yes, it works .Thank you.

**Comment by gregruthenbeck** [comment]
I'm on Win10 and have trouble getting `sh ./autogen.sh CC=cl` to work (fails with `checking whether the C compiler works... no`). 
I'm trying with `bash ./autogen.sh CC=cl` instead. The cmd window I'm using I prime with `vcvarsall.bat x86` so that cl.exe is visible. Can anyone see/suggest why this fails? Should I use 'sh', not 'bash'?

**Comment by kgybels** [comment]
It seems you need `CC=cl.exe` (extension included).

Source: https://github.com/jemalloc/jemalloc/issues/1151#issuecomment-376459923

**Comment by Assembly87** [comment]
I am getting a different error

```
autoconf
./autogen.sh: line 5: autoconf: command not found
Error 0 in autoconf
```

I already have autoconf and the other packages mentioned here [](https://github.com/jemalloc/jemalloc/tree/dev/msvc) installed.
How to solve this error?

**Comment by gregruthenbeck** [comment]
Looks like you're missing a dependency: https://www.gnu.org/software/autoconf/autoconf.html
