### ISSUE TITLE
Mutex contention profiling

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#574]
Currently we don't have insights regarding mutex contention in jemalloc. At arena / bin level, it will be useful to add tracking for information like 
- how often a mutex is contended
- when contended, how long it takes to get the lock
- thread / CPU, e.g. # of threads / CPU contending on this lock

Should keep overhead minimal on fast path.

**Comment by interwq** [comment]
Goals of mutex profiling:
1. Minimal impact on fast path (i.e. when there is no contention)
2. Minimal memory cost. We probably don't want to spend too much memory on this. A few counters per lock should be reasonable. Going histogram is probably too far.
3. Gather information to help us understand lock behavior, and guide design / performance tuning.

Current plan:
1. Instead of calling mutex_lock directly, use trylock first, enter slow path if lock is taken already;
2. on slow path, do appropriate accounting and customized adaptive spin. The customized spinning isn't required, but since we are gathering a bunch of information anyway, we can try making some better spin decisions.
3. High level output in malloc_stats, and new mallctl for control and detailed data.

Looks like all platforms / locking mechanisms we support have trylock:
``pthread_mutex_trylock``
MacOS:
``os_unfair_lock_trylock``
``OSSpinLockTry``
Windows:
``TryAcquireSRWLockExclusive``
``TryEnterCriticalSection``

Locks that we want to profile:
1. bin locks
2. extents lock
3. prof related locks (bt2gctx_mtx)
*time granularity when recording time -- ideally we want nano second granularity. Will need to check whether we have such support on each platform.

Candidate counters / events to profile --
1. average lock waiting time, when there is contention
On average how long do we have to wait (either spin or block) before we can acquire the lock.

2. longest lock waiting time, when there is contention
Max waiting time, during the last time period (likely need a mallctl to reset this). This should give information about lock related latency spikes.

3. % of locking w/ contention
i.e. (# of contention) / (total # of locking). This one adds tax on the fast path as we'll need to increment a counter after we grab the lock. It does offer quite valuable information though, and the cost should be acceptable (write to the same cacheline, and no atomic required) so should be worth doing.

4. % of locking acquired through spinning
To help us understand how effective our spinning policy is. Cost: one counter change on slow path.

5. % of lock holder different from last
i.e. track how often a lock is taken by the same thread as last time. This adds a branch and non atomic write  to the fast path (if current thread is different from the last lock holder). This can help us understand if the lock (and the protected resource) is passed around between threads often. Ideally we want to track CPU instead of thread, but before we have a very fast way of getting CPU id (e.g. from rseq support), track thread should be good enough.

6. max # of threads waiting
i.e. inc / dec an atomic pointer when we enter / leave the slow path. However this may actually slows down fast path and other parts as well, as more cacheline traffic is generated. This should give us insights about the worst case or p99 latency spikes caused by lock contention, e.g. triggered by a burst of requests. However this information is pretty similar to (2), and with the high cost we might consider to skip this one.

**Comment by jasone** [comment]
Re: time granularity, Windows only has 100ns resolution.  See the [nstime](https://github.com/jemalloc/jemalloc/blob/dev/src/nstime.c) code for portable time management.

**Comment by interwq** [comment]
A prototype here: https://github.com/interwq/jemalloc/commit/c8e0d3735cb3335050127598a508fdab9c6d3224

Feedback / comments? @jasone @davidtgoldblatt @djwatson

**Comment by jasone** [comment]
Looks reasonable overall.  What do you have in mind for how we gather/report the profiling data?

**Comment by interwq** [comment]
I'm thinking about integrating the key counters to malloc_stats (as much as possible), and having separate mallctls to retrieve detailed info and reset max_* counters. 

How about I add the counters to malloc_stats first, and see how much can be fit there?

**Comment by interwq** [comment]
Took me a while to get the stats mallctl straight. A draft here adding two of the counters to malloc_stats:
https://github.com/interwq/jemalloc/commits/prof_mutex

I'm thinking about --

/*************************/
In malloc_stats output:
Per small bins: add two counters to : contention rate and max_wait_time;
Per arena: In the summary section, either 
a) output the lock with highest contention rate, or 
b) output all locks that might cause issues. Same two counters above, or more if can fit.

/*************************/
For mallctl (per lock):
(1) mallctl to return the entire prof struct (that contains all counters)
(2) mallctls for each individual counters
(3) mallctl to reset the entire struct, probably share API with (1)
(4) mallctl to reset individual counters, probably share API with (2)

If we want (1) / (3), we'll need to expose a profiling data struct in the public header. Any downside / concerns of doing so?

@jasone : what do you think? (a) or (b), and which ones to have for (1) to (4)? Or suggest a different approach?

**Comment by jasone** [comment]
I made a few comments on [your diff](https://github.com/interwq/jemalloc/commit/87a8e46caf7ab5d7e209d3bfd37e52780126157a#diff-8b84f05184e9cc8cb5a7f6e9bea88dc7), but since it's ephemeral, I'll put the main comments here.  (Pull requests may be a better option for collaboratively iterating on prototypes, even if we don't intend to commit them.)

If we split the mallctl interface in two (```stats.arenas.<i>.bins.<j>.lock.{contention,max_wait}```), we avoid having to provide lock_prof_data_t as part of the jemalloc API (option (2)), which I have  a pretty strong preference for due to simplified API compatibility concerns.  I suspect in practice we'd rather do a global reset of all lock stats (option (5) :wink:) rather than per lock (options (3)/(4)), but this API does provide a natural place for per lock stats reset should there be a good reason to provide that.

Regarding lock stats output, I'l prefer to output all the stats, even in the human-readable ```malloc_stats_print()``` output format, and leave it up to the reader to scan through them and make judgements on which indicate performance concerns.

**Comment by interwq** [comment]
Yeah will create a pull request next time I update the branch.

I agree that a global lock reset API is probably sufficient. So if I understand everything correctly, we want to provide an API for:
1) read each individual counters, and
2) reset all lock stats

 For (1), actually I want to expose all meaningful counters, not just the 2 in malloc_stats, i.e. 
 +	/* Total time spent waiting on this lock. */
 +	nstime_t		tot_wait_time;
 +	/* Max time spent on a single lock operation. */
 +	nstime_t		max_wait_time;
 +	/* # of times have to wait for this lock (after spinning). */
 +	uint64_t		n_wait_times;
 +	/* # of times acquired the lock through local spinning. */
 +	uint64_t		n_spin_acquired;
 +	/* Max # of threads waiting for the lock at the same time. */
 +	uint32_t		max_n_thds;
 +
 +	/* # of times the new lock holder is different from the previous one. */
 +	uint64_t		n_owner_switches;
 +	/* # of lock() operations in total. */
 +	uint64_t		n_lock_ops;

So that the reader can compute the stats they want. Do you think it's too much (7 counters)?

**Comment by jasone** [comment]
Seems reasonable to me.  Let's publish ```nstime_t``` as ```uint64_t``` though, and document it as nanoseconds.  We may want slightly more descriptive mallctl interface names, but use your own judgement on that.

**Comment by interwq** [comment]
A couple of more things we need to decide: 
1) do we want a non-prof mutex type? I think for the majority of locks, we do want to have profiling ability. Does it justify to add a mutex type without profiling?
2) do we a config switch for mutex profiling? On one hand it would be nice to control it, on the other hand that means we can not rely on the profiling counters, e.g. to make spin decisions.

**Comment by interwq** [comment]
@jasone : I replied a bit in the diff here: https://github.com/interwq/jemalloc/commit/87a8e46caf7ab5d7e209d3bfd37e52780126157a#diff-8b84f05184e9cc8cb5a7f6e9bea88dc7
Yeah it's bad for conversation. Let's move the discussion to a pull request.

**Comment by jasone** [comment]
Re: (1), let's try to just have profiling mutexes for now, to keep things simple.

Re: (2), how about a run-time option, e.g. ```--lock-prof-mode``` (please come up with at better name :wink:), with e.g. {"disabled", "count", "time"} as options.

**Comment by interwq** [comment]
@jasone : if I add one more level to the bin stats, e.g. stats.arenas.0.bins.0.lock.num_ops, it means the max level becomes 7 instead of 6 here https://github.com/jemalloc/jemalloc/blob/dev/src/ctl.c#L177. Do you think it's okay to do so? Or there are side effects from that?

**Comment by jasone** [comment]
Increasing the max ctl depth is totally fine.

**Comment by interwq** [comment]
@jasone: Does this look good to you? I have the proper mallctl added. For arena locks, I have large, extent, decay and tcache_ql. I'm not sure how to deal with prof locks as they are global. What do you think about adding them to this struct: https://github.com/jemalloc/jemalloc/blob/dev/include/jemalloc/internal/ctl_structs.h#L37

```
Merged arenas stats:
assigned threads: 129
dss allocation precedence: N/A
decay time: N/A
purging: dirty: 1229101, sweeps: 26, madvises: 859, purged: 13013
                            allocated      nmalloc      ndalloc    nrequests
small:                      234064752       343636       202651       401574
large:                      250720256       272633       262458       272633
total:                      484785008       616269       465109       674207
active:                     685785088
mapped:                    5829234688
retained:                  1225060352
base:                        60456144
internal:                     4163360
tcache:                     480517200
resident:                  5780742144
Lock stats:          n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns max_n_wait_thds
large_mutex:             393999            2043            1549          116278        74000281        15000058               5
extent_mutex:            241972               0               0           16246               0               0               0
decay_mutex:                395               0               0             321               0               0               0
tcache_mutex:              5401              21              14            5089         2000008         1000004               1
bins: .....................
```

**Comment by interwq** [comment]
Code is in this pull request #697.

**Comment by jasone** [comment]
Adding global lock stats to ```ctl_stats_t``` sounds reasonable to me.

Re: the human-readable stats output, I have some suggestions for making it more consistent with existing output.
```
Merged arenas stats:
assigned threads: 129
dss allocation precedence: N/A
decay time: N/A
purging: dirty: 1229101, sweeps: 26, madvises: 859, purged: 13013
                            allocated      nmalloc      ndalloc    nrequests
small:                      234064752       343636       202651       401574
large:                      250720256       272633       262458       272633
total:                      484785008       616269       465109       674207
active:                     685785088
mapped:                    5829234688
retained:                  1225060352
base:                        60456144
internal:                     4163360
tcache:                     480517200
resident:                  5780742144
                     n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns max_n_wait_thds
large:                   393999            2043            1549          116278        74000281        15000058               5
extents_cached:          241972               0               0           16246               0               0               0
decay:                      395               0               0             321               0               0               0
tcaches:                   5401              21              14            5089         2000008         1000004               1
bins: .....................
```
I am confused by some of the names.  Does ```extent_mutex``` refer to the mutex protecting ```extents_cached```, or ```extents_freelist```?  In order to clarify some of this, we may want to rename some of the structure fields, e.g. s/tcache_ql/tcache_list/, so that the code and the stats have clear relationships.

What about stats for ```extents_retained```, ```extent_freelist```, and ```base```?

Incidentally, #691 will result in a transition to the following mutex-protected fields, so our naming scheme should support such changes:
- ```tcache_ql```
- ```large```
- ```extents_dirty```
- ```extents_muzzy```
- ```extents_retained```
- ```decay_dirty```
- ```decay_muzzy```
- ```extent_freelist```
- ```bins```...
- ```base```

One final note: This is going to be a good bit of output, and I think we should consider adding an option to ```malloc_stats_print()``` ("x"?) to disable printing them.  I've been contemplating adding an ```opt.malloc_stats_print_opts``` mallctl to go along with ```opt.malloc_stats_print``` so that we can control what is printed, which would make this even more useful (#698).

**Comment by interwq** [comment]
@jasone: this sounds good to me. Would you like me to rebase pass #691 and add all the lock stats together? Or you want to land this before #691 with the current locks (and add the new ones separately) -- I'm adding the global ones (prof and base), and also the other extent ones as you pointed out.

**Comment by interwq** [comment]
Also which prof mutexes we'd like to track?  On prof_enter and prof_exit we take bt2gctx_mtx. Will that be enough?

**Comment by jasone** [comment]
#691 is ready for review, so let's get that one in first and rebase this one.

```bt2gctx_mtx``` is the only global mutex that certainly deserves profiling.  ```ctl_mtx``` is tempting to profile as well.

**Comment by interwq** [comment]
Sounds good. I know David already started reviewing on #691. So I'll finish adding JSON here first and then switch to review as well.
