### ISSUE TITLE
allow manually disabling JEMALLOC_HAVE_SECURE_GETENV, JEMALLOC_HAVE_ISSETUGID

### ISSUE THREAD

**Issue by tamird** [jemalloc/jemalloc#584]
This is needed to support both glibc and musl in the same `configure` result; such support is necessary for CockroachDB, which uses jemalloc via https://github.com/cockroachdb/c-jemalloc.

Unfortunately, the `go` toolchain does not allow us to `configure` per-target, so we are forced to commit `jemalloc_internal_defs.h`. Currently, we are doing this per-platform, and using build tags to switch on them: https://github.com/cockroachdb/c-jemalloc/blob/master/cgo_flags.go#L9:L11.

We could introduce a build tag and check in glibc and musl configurations, but would prefer to just disable `JEMALLOC_HAVE_SECURE_GETENV` and `JEMALLOC_HAVE_ISSETUGID` so that a single `jemalloc_internal_defs.h` can support both libcs.

**Comment by jasone** [comment]
Can you use a [cache file](https://github.com/jemalloc/jemalloc/blob/4.4.0/INSTALL#L335) to override the ```configure``` tests?  For your use case, a ```config.cache``` file with the following contents should do the job:

```
ac_cv_func_secure_getenv=no
ac_cv_func_issetugid=no
```

**Comment by tamird** [comment]
Those cache file entries are not respected, unfortunately. That's what this issue is about. See https://github.com/jemalloc/jemalloc/blob/4.4.0/configure.ac#L1428:L1444 (this code is the same on `dev`).

**Comment by jasone** [comment]
I tried the cache file on my system (master branch), and it appeared to successfully override the configure tests.  Are you sure you're running ```configure``` correctly?  With ```config.cache``` in the top directory, run ```./configure -C```, and you should see output lines like:

```
checking for secure_getenv... (cached) no
checking for issetugid... (cached) no
```

In ```include/jemalloc/internal/jemalloc_internal_defs.h```, you should see
```C
/*
 * Defined if secure_getenv(3) is available.
 */
/* #undef JEMALLOC_HAVE_SECURE_GETENV */

/*
 * Defined if issetugid(2) is available.
 */
/* #undef JEMALLOC_HAVE_ISSETUGID */
```

**Comment by tamird** [comment]
Ah, right you are. Thanks!

**Comment by tamird** [comment]
Ah, turns out that disabling `JEMALLOC_HAVE_SECURE_GETENV` on a system which actually does have `secure_getenv` results in:
```
./jemalloc.c:795:1: error: static declaration of 'secure_getenv' follows non-static declaration
/usr/include/stdlib.h:570:14: note: previous declaration is here
```
I'll see about submitting a PR to fix that.

**Comment by tamird** [comment]
https://github.com/jemalloc/jemalloc/pull/586 should do it.
