### ISSUE TITLE
jemalloc.pc: wrong includedir

### ISSUE THREAD

**Issue by hexum** [jemalloc/jemalloc#589]
Right after installation pkg-config returns `/usr/include` as dir with jemalloc.h
```bash
# pkg-config --variable=includedir jemalloc
/usr/include
```
But actually jemalloc.h sits in /usr/include/jemalloc/
Also `jemalloc-config` show wrong string.
```
# jemalloc-config --includedir
/usr/include
```

Wrong includedir in jemalloc.pc breaks some [CMake builded programs](https://bugs.gentoo.org/show_bug.cgi?id=607128).

**Comment by hexum** [comment]
Gentoo linux
=dev-libs/jemalloc-4.4.0
Manually master build is affected too.

**Comment by jasone** [comment]
The correct way to include the jemalloc header is:

```C
#include <jemalloc/jemalloc.h>
```

Therefore this is not a bug.
