### ISSUE TITLE
Assert "assert(milli <= 1000)" in stats_arena_bins_print

### ISSUE THREAD

**Issue by gnurizen** [jemalloc/jemalloc#591]
We occasionally see this assert:

#7  0x000000000104ab7f in stats_arena_bins_print (write_cb=0x558de1, cbopaque=0x7fc3b7ffec60, json=false, large=true, huge=true, i=32) at jemalloc/src/stats.c:140
(gdb) info locals
availregs = 97
milli = 1020
util = "0.450"
reg_size = 4096
nregs = 1
nrequests = 3577
curruns = 97
nmalloc = 6298
ndalloc = 6199
nfills = 1303
nflushes = 1834
nruns = 6298
run_size = 4096
curregs = 99
nreruns = 0
page = 4096
config_tcache = true
in_gap = false
in_gap_prev = false
nbins = 36
j = 28

VERSION:
4.3.1-0-g0110fa8451af905affd77c3bea0d545fee2251b2

Our program periodically calls malloc_stats_print and records the data for debugging purposes.    I don't understand the code but the assertion seems to imply that 'curregs' should be equal to or less than 'availregs'.    We never see any problems in Release builds related to this code so maybe its an overzealous assert?   Thanks for your help!

**Comment by interwq** [comment]
Thanks for the reporting the issue and the details! I believe the assertion is necessary, and I'm not aware of any issue that should cause this. A couple of reasons I can think of:
1) multiple threads calling malloc_stats at the same time? After a quick look, I didn't find locking on arena / stats around this. @jasone 
2) corruption caused by double free etc.

**Comment by jasone** [comment]
@interwq has a reasonable fix in #592.  However, you should consider modifying your application to avoid concurrent ```malloc_stats_print()``` calls (and concurrent epoch updates in general).

**Comment by interwq** [comment]
@jasone: it looks even if only 1 thread is doing malloc_stats_print(), this could still happen: the counters are read separately without locking the arena (I believe only ctl_mtx is involved), so anything could happen in between?

**Comment by jasone** [comment]
That was my initial thought too,  but each bin's stats are updated in a self-consistent fashion because the appropriate bin lock is held in ```arena_stats_merge()``` at the time the ctl stats cache is refreshed.

**Comment by gnurizen** [comment]
Just to be sure I'm following, our application only calls malloc_stats_print from one dedicated thread but because we also trigger epochs concurrently we're causing this assert?   So its recommended to serialize malloc_stats_print and "epoch" mallctl calls?

**Comment by jasone** [comment]
Correct, assuming you care about reasonable stats consistency from ```malloc_stats_print()```.
