### ISSUE TITLE
Assert "assert(nstime_compare(&arena->decay.epoch, &time) <= 0);"

### ISSUE THREAD

**Issue by denniszong** [jemalloc/jemalloc#594]
when i set system time to backwards.it will Assert in function "arena_maybe_purge_helper()" at line
/* Verify that time does not go backwards. */
assert(nstime_compare(&arena->decay.epoch, &time) <= 0);

when i use jemalloc,i can't set time to backwards?I must to set time backwards to do some tests.

**Comment by jasone** [comment]
As far as I know, this was fixed in 4.2.1.  Are you using 4.1.0 or 4.2.0?

**Comment by denniszong** [comment]
Thank you very much! I upgrade it to  4.4.0,It work well now.
