### ISSUE TITLE
Consider memoizing iealloc() results in tcache_bin_flush_small() / _large()

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#598]
```tcache_bin_flush_large()``` potentially performs multiple passes over allocations when deallocating them, and looking up their corresponding extents via ```iealloc()``` is a somewhat costly operation.  Consider memoizing the extent lookup results for use in later passes.

**Comment by interwq** [comment]
I believe this also applies to ```tcache_bin_flush_small```:
https://github.com/jasone/jemalloc/blob/9f0ae0b2ff0efc50706d81823d3246227ae7cf10/src/tcache.c#L131
