### ISSUE TITLE
./configure: error: the invalid value in --with-ld-opt="/usr/local/lib/libjemalloc.so.2"

### ISSUE THREAD

**Issue by kaixulucky** [jemalloc/jemalloc#626]
In centos6.8 system jemalloc-4.1.1 and jemalloc-4.1.0 environment, install nginx1.10.3, in 4.2,4.3,4.4 no problem
[root@localhost nginx-1.10.3]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost nginx-1.10.3]# uname -r
2.6.32-642.el6.x86_64
[root@localhost nginx-1.10.3]# ./configure \
> --with-http_stub_status_module \
> --with-http_gzip_static_module \
> --with-ld-opt=/usr/local/lib/libjemalloc.so.2 \
> --with-http_realip_module \
> --with-http_addition_module \
> --with-pcre=/root/nginx/pcre-8.40 \
> --with-zlib=/root/nginx/zlib-1.2.11 \
> --with-openssl=/root/nginx/openssl-1.0.2k \
> --with-pcre-jit \
> --add-module=/root/nginx/ngx_pagespeed-1.12.34.2-beta \
> --with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc \
> --with-http_ssl_module \
> --with-http_v2_module
checking for OS
 + Linux 2.6.32-642.el6.x86_64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
checking for gcc -pipe switch ... found
checking for --with-ld-opt="/usr/local/lib/libjemalloc.so.2" ... not found
./configure: error: the invalid value in --with-ld-opt="/usr/local/lib/libjemalloc.so.2"
[root@localhost nginx-1.10.3]# ll /usr/local/lib/libjemalloc.so.2
-rwxr-xr-x 1 root root 7038728 2月  17 09:42 /usr/local/lib/libjemalloc.so.2

**Comment by jasone** [comment]
[Odd, my previous message appears to have been lost; here's something similar.]

This does not appear to be a jemalloc issue.  It is specific to nginx and/or CentOS.

**Comment by kaixulucky** [comment]
OK, thanks!
