### ISSUE TITLE
How to complie jemalloc as 32-bit on x86_64 machine?

### ISSUE THREAD

**Issue by WentaoCai** [jemalloc/jemalloc#638]
I tried to make and make install jemalloc directly and then make my own program with libjemalloc.a in -m32, but it shows that :
`i386:x86-64 architecture of input file '.../libjemalloc.a' is incompatible with i386 output`

Then I tried to modify Makefile of jemalloc, adding -m32 to CPPFLAG, CFLAG, and even CXXFLAG. When I make again, it shows errors:
```
include/jemalloc/internal/atomic_inlines.h:110:11: error: ‘atomic_uint_least64_t’ does not name a type
  volatile atomic_uint_least64_t *a = (volatile atomic_uint_least64_t *)p;
```

Is there any way to solve this issue?

**Comment by jasone** [comment]
[scripts/gen_run_tests](https://github.com/jemalloc/jemalloc/blob/8ac7937eb5ce011945188ef3553dbc2bcc294a25/scripts/gen_run_tests.py) does 32-bit testing as something essentially like:
```
./configure CC="gcc -m32" CXX="g++ -m32"
make check
```
Given the necessary system libraries this works well.
