### ISSUE TITLE
Simplify using private_namespace.txt

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#677]
Right now, we use private_namespace.txt to mangle any symbols that need to be used outside of the object file in which they're defined. This works, but is brittle and error-prone.

We could generate private_namespace.txt automatically by compiling, finding all the exported symbols, and then subtracting out those symbols we intend to export.

At that point we could recompile with the updated private_namespace.txt.

Some other random notes:
- On sufficiently friendly platforms, I think we can get by with `--redefine-sym` or `--localize-symbol` from `objcopy`, or linker renaming trickery.
- We should be able to lazily re-compute private_symbols.txt: only recompile if we see a newly exported function that's not on the whitelist.
- The MSVC equivalent to `nm` is `dumpbin`, to which we can pass the `/EXPORTS` flag.

I'm assigning to @jasone as part of my master plan to die never having learned autotools.

**Comment by jasone** [comment]
This may be worth doing at roughly the same time as #303.
