### ISSUE TITLE
Integrate tdata (ticker) into tsd

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#684]
Currently tdata is a separate array which holds per arena tickers. However this adds some complexity in order to avoid synchronization (besides atomics), e.g. alloc / expand tdata array. In addition, from memory layout perspective, the separate page adds a potential TLB access (and miss) on the fast path.

Integrating ticker into tsd should be a way to improve the cases. The other would be using the async worker thread, which replaces the ticker mechanism.

**Comment by interwq** [comment]
@jasone : looking through "optimization" labels this one seems to have potential of a measurable win. Do you think I should tackle on this soon (maybe after finishing background threads)?

**Comment by jasone** [comment]
We have background purging now (see #149).

Regarding embedding the contents of ```arenas_tdata``` into the tsd, I don't think the metadata size overhead (~4096*8 --> ~32 KiB per thread on 64-bit systems) is acceptable.  However, we could potentially co-allocate an array just past the tsd that is big enough for common use cases (enough entries for all auto arenas, or current range of arenas, whichever is greater), and then allocate separate space if the array ends up being too small.

**Comment by interwq** [comment]
I was also thinking maybe only one ticker per tsd, and use that ticker for the associated arena?

Alternatively, should we consider making one ticker per arena?

**Comment by jasone** [comment]
One ticker per tsd would make it difficult to associate ticks with particular arenas; we'd probably have to give up on ticking during deallocation (maybe okay?).

One ticker per arena would force us to synchronize.

**Comment by interwq** [comment]
Not ticking during free doesn't sound right. In the case where we have tons of free at once (like in a cleanup thread), we need ticking to trigger decay there.

How about we have 1 ticker per tsd, for the associated arena, while for other arenas we still keep the current tdata array? It should improve the TLB, but won't help complexity. 

Either way, let's move this to 5.1?

**Comment by interwq** [comment]
Some prod data regarding this, it looks ticker causes ~13% of LLC load misses on the free() fast path, which seems to be far too high. To compare, loading metadata from rtree contributes ~20% (which is expected). I'll take a look at this soon.

       │     tcache_dalloc_small():                                                                                                                                                               ▒
       │ af:   mov    jemalloc_je_tcache_bin_info,%r15                                                                                                                                            ▒
  0.13 │       lea    (%rcx,%rcx,2),%r10                                                                                                                                                          ▒
  0.34 │       shl    $0x3,%r10                                                                                                                                                                   ▒
  2.63 │       lea    (%rbx,%r10,1),%r13                                                                                                                                                          ▒
  0.03 │       mov    0x1d4(%r13),%r8d                                                                                                                                                            ▒
  1.78 │       cmp    (%r15,%r14,4),%r8d                                                                                                                                                          ▒
  0.04 │     . je     3c4                                                                                                                                                                         ▒
  4.83 │ d3:   add    $0x1,%r8d                                                                                                                                                                   ▒
  0.01 │       lea    (%rcx,%rcx,2),%r9                                                                                                                                                           ▒
  0.07 │       lea    (%rbx,%r9,8),%rdi                                                                                                                                                           ▒
  0.32 │       mov    0x1e0(%rdi),%rdx                                                                                                                                                            ▒
  2.39 │       mov    %r8d,0x1d4(%rdi)                                                                                                                                                            ▒
  0.25 │       movslq %r8d,%r8                                                                                                                                                                    ▒
  0.14 │       shl    $0x3,%r8                                                                                                                                                                    ▒
  0.68 │       sub    %r8,%rdx                                                                                                                                                                    ▒
  2.86 │       mov    %r12,(%rdx)                                                                                                                                                                 ▒
       │     ticker_ticks():                                                                                                                                                                      ▒
 13.57 │       subl   $0x1,0x1c8(%rbx)                                                                                                                                                            ▒
  0.92 │     . js     393                                                                                                                                                                         ▒
       │     free():                                                                                                                                                                              ▒
  0.59 │107:   add    $0x28,%rsp                                                                                                                                                                  ▒
  0.96 │       pop    %rbx                                                                                                                                                                        ▒
  0.03 │       pop    %r12                                                                                                                                                                        ▒
  0.09 │       pop    %r13                                                                                                                                                                        ▒
  0.57 │       pop    %r14                                                                                                                                                                        ▒
  1.23 │       pop    %r15                                                                                                                                                                        ▒
  0.02 │       pop    %rbp                                                                                                                                                                        ▒
  0.29 │115: , retq

**Comment by davidtgoldblatt** [comment]
This is probably me just not understanding how the counters got named, but how's that a *load* miss?

**Comment by interwq** [comment]
@davidtgoldblatt : we do check the value after the increment, e.g. `if (unlikely(ticker->tick-- < 0)) {    // slow path `, so it was counted as load miss.

**Comment by interwq** [comment]
Achieved by https://github.com/jemalloc/jemalloc/commit/c259323ab3082324100c708109dbfff660d0f4b8
