### ISSUE TITLE
Higher cache miss rate with extents

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#721]
In a prod benchmark w/ dev, I'm observing higher LLC miss rate, with a fair contribution from tcache_bin_flush_small. It's the 4th LLC miss source within jemalloc (and ~10th of the entire application), ranking follows:
1) free
2) malloc 
3) extent_heap_remove_first (or the arena_run_heap_remove_first) on dev
4) tcache_bin_flush_small

When comparing LLC miss to 4.5, first 2 had no change (fast path), while the 3rd one regressed about ~30%, and the 4th regressed >100%. Both related to larger cache footprint from extent I believe. #716 should help this, but if we still experience high miss rate, we may want to push it further, e.g. limit it to 128 bytes and cacheline aligned.

**Comment by jasone** [comment]
Related: #461.

**Comment by interwq** [comment]
#728 improved the situation quite a bit. We observed improvements from production benchmarks. Keep this open a bit longer to make sure no major regression.

**Comment by jasone** [comment]
The LLC miss rate is no longer a significant issue.  Closing.
