### ISSUE TITLE
jemalloc crash in je_size2index_lookup

### ISSUE THREAD

**Issue by ajopensrc** [jemalloc/jemalloc#722]
Hi,

We are seeing this crash intermittently with libjemalloc 4.2.1 version while allocating a 128k size buffer: 

(gdb) bt
#0 0x00007f06916dbce1 in je_size2index_lookup (size=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:603
#1 je_size2index (size=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:615
#2 arena_avail_remove (npages=0, pageind=<optimized out>, chunk=0x7f0642c00000, arena=0x7f068fd6f600) at src/arena.c:229
#3 arena_run_split_remove (arena=0x7f068fd6f600, chunk=<optimized out>, run_ind=388, flag_dirty=0, flag_decommitted=0, need_pages=33) at src/arena.c:420
#4 0x00007f06916dc2d1 in arena_run_split_large_helper (arena=0x7f068fd6f600, run=<optimized out>, size=135168, remove=<optimized out>, zero=<optimized out>) at src/arena.c:469
#5 0x00007f06916dc6f3 in arena_run_split_large (zero=false, size=135168, run=<optimized out>, arena=0x7f068fd6f600) at src/arena.c:524
#6 arena_run_alloc_large_helper (arena=0x7f068fd6f600, size=135168, zero=false) at src/arena.c:1130
#7 0x00007f06916df5e5 in arena_run_alloc_large (zero=<optimized out>, size=135168, arena=0x7f068fd6f600, tsdn=0x7f0653fff698) at src/arena.c:1146
#8 je_arena_malloc_large (tsdn=0x7f0653fff698, arena=0x7f068fd6f600, binind=48, zero=false) at src/arena.c:2613
#9 0x00007f06916e096f in je_arena_malloc (slow_path=true, tcache=0x7f065494b000, zero=<optimized out>, ind=48, size=131072, arena=0x0, tsdn=0x7f0653fff698)
at include/jemalloc/internal/arena.h:1344
#10 je_arena_palloc (tsdn=0x7f0653fff698, arena=0x0, usize=131072, alignment=<optimized out>, zero=false, tcache=0x7f065494b000) at src/arena.c:2776
#11 0x00007f06916d21b5 in je_ipallocztm (arena=0x0, is_metadata=false, tcache=0x7f065494b000, zero=false, alignment=512, tsdn=<optimized out>, usize=131072)
at include/jemalloc/internal/jemalloc_internal.h:994
#12 je_ipalloc (zero=false, alignment=512, usize=131072, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1015
#13 imemalign (memptr=0x7f0653fee810, alignment=512, size=<optimized out>, min_alignment=<optimized out>) at src/jemalloc.c:1654

**Comment by interwq** [comment]
Hello,

From the stack trace this looks to be memory corruption related to application, e.g. caused by double free, etc. I'd suggest trying jemalloc debug mode, or ASAN to see if they catch anything. Also please feel free to let us know if you still find this to be caused by jemalloc.

**Comment by interwq** [comment]
Closing assuming not caused by malloc.

**Comment by ajopensrc** [comment]
Ok. Will try with debug mode and looks for double free possibility in the code, but since it isn't hitting often might be hard to confirm. Will update if we see this again.
