### ISSUE TITLE
Can't get jemalloc working on OS X

### ISSUE THREAD

**Issue by jeff303** [jemalloc/jemalloc#731]
Apologies if I've missed something, but I can't get jemalloc to work on OS X 10.12.3.  Specifically, I am trying to use it with Oracle Java to debug a native memory leak.

jemalloc (commit 07f4f93434b) was configured using:
`./configure --enable-prof --enable-stats --enable-debug --enable-fill`

and installed to the default location (`/usr/local/lib`).  Compiler/libc provided by Apple XCode command line tools package.

```
which java
/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java

DYLD_PRINT_LIBRARIES=1 DYLD_INSERT_LIBRARIES=/usr/local/lib/libjemalloc.dylib MALLOC_CONF="prof_final:true,prof_prefix:jeprof.out" java -version
# snipped dyld output
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

ls jeprof*
jeprof*: No such file or directory
```

The dyld output from `DYLD_PRINT_LIBRARIES=1` shows the first two lines as being

```
dyld: loaded: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java
dyld: loaded: /usr/local/lib/libjemalloc.dylib
```

But no prof files get generated, nor do I see any kind of output indicating jeprof has done anything.  Any suggestions on what I might be missing?  Much appreciated.

**Comment by jasone** [comment]
Heap profiling is not implemented on OS X, though doing so would probably be reasonably straightforward.  See #26.
