### ISSUE TITLE
include/msvc_compat/stdbool.h

### ISSUE THREAD

**Issue by lcizzle** [jemalloc/jemalloc#76]
Throws errors in Visual Studio 2013.

/* MSVC doesn't define _Bool or bool in C, but does have BOOL */
/* Note this doesn't pass autoconf's test because (bool) 0.5 != true */
//typedef BOOL _Bool;
//#define bool _Bool
typedef int bool;
#define true 1
#define false 0

This modification fixes it.

**Comment by glandium** [comment]
This should have been fixed by ff2e999667cbd06e5e80c243277c1f3c72d6d263

**Comment by jasone** [comment]
Cool, closing.
