### ISSUE TITLE
test/unit/SFMT fails on ppc64le (POWER8), default system configuration

### ISSUE THREAD

**Issue by davidlt** [jemalloc/jemalloc#761]
701daa5298b3befe2aff05ce590533165abb9ba4 from dev branch.
Environment CentOS 7.3, kernel 3.10.0-514.10.2.el7.ppc64le, glibc 2.17, GCC 4.8.5, binutils 2.25.1-22.base.el7

The output is very long.

```
[..]
=== test/unit/SFMT ===
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 2409195644 != 3440181298: Output mismatch for i=0
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 723582512 != 1564997079: Output mismatch for i=1
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3024894813 != 1510669302: Output mismatch for i=2
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 1781879280 != 2930277156: Output mismatch for i=3
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 1067356262 != 1452439940: Output mismatch for i=4
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3639479974 != 3796268453: Output mismatch for i=5
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 592726212 != 423124208: Output mismatch for i=6
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 1298498744 != 2143818589: Output mismatch for i=7
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 2452768176 != 3827219408: Output mismatch for i=8
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3824828382 != 2987036003: Output mismatch for i=9
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3706840695 != 2674978610: Output mismatch for i=10
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 2896181029 != 1536842514: Output mismatch for i=11
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 56987722 != 2027035537: Output mismatch for i=12
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3107113493 != 2534897563: Output mismatch for i=13
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 571033558 != 1686527725: Output mismatch for i=14
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3546233604 != 545368292: Output mismatch for i=15
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 356067907 != 1489013321: Output mismatch for i=16
test_gen_rand_32:test/unit/SFMT.c:1470: Failed assertion: (array32[i]) == (init_gen_rand_32_expected[i]) --> 3083877846 != 1370534252: Output mismatch for i=17
[..]
test_gen_rand_64:test/unit/SFMT.c:1539: Failed assertion: (array64[i]) == (init_gen_rand_64_expected[i]) --> 5913104268441886684 != 17911176066536804411: Output mismatch for i=320
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 15011377014086013184 != 5913104268441886684: Mismatch at array64[320]=520f9100d0531fdc, gen=d0531fdc520f9100
test_gen_rand_64:test/unit/SFMT.c:1539: Failed assertion: (array64[i]) == (init_gen_rand_64_expected[i]) --> 6489211395007107642 != 9435590428600085274: Output mismatch for i=321
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 16704082165977993057 != 6489211395007107642: Mismatch at array64[321]=5a0e4f61e7d0d23a, gen=e7d0d23a5a0e4f61
test_gen_rand_64:test/unit/SFMT.c:1539: Failed assertion: (array64[i]) == (init_gen_rand_64_expected[i]) --> 18394792964016838654 != 294488509967864007: Output mismatch for i=322
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 12759850028219461309 != 18394792964016838654: Mismatch at array64[322]=ff476ebdb11417fe, gen=b11417feff476ebd
test_gen_rand_64:test/unit/SFMT.c:1539: Failed assertion: (array64[i]) == (init_gen_rand_64_expected[i]) --> 10557335078815870876 != 8890111397567922046: Output mismatch for i=323
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 12364403651488460881 != 10557335078815870876: Mismatch at array64[323]=92833051ab972f9c, gen=ab972f9c92833051
test_gen_rand_64:test/unit/SFMT.c:1539: Failed assertion: (array64[i]) == (init_gen_rand_64_expected[i]) --> 16055781649477978126 != 7987823476034328778: Output mismatch for i=324
[..]
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 1754619880594255701 != 3073899525695973756: Mismatch at array64[2179]=2aa8af551859a97c, gen=1859a97c2aa8af55
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 15597606917057861703 != 17683621739956131033: Mismatch at array64[2180]=f568d847d875d4d9, gen=d875d4d9f568d847
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 18168880899653445029 != 6213038555764413674: Mismatch at array64[2181]=563925a5fc24d4ea, gen=fc24d4ea563925a5
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 5538982302595934999 != 12927559740696718094: Mismatch at array64[2182]=b367eb174cde6b0e, gen=4cde6b0eb367eb17
test_gen_rand_64:test/unit/SFMT.c:1544: Failed assertion: (r) == (array64[i]) --> 5350760337346429364 != 7046024228361058349: Mismatch at array64[2183]=61c881b44a41b82d, gen=4a41b82d61c881b4
[..]
test_gen_rand_64:test/unit/SFMT.c:1550: Failed assertion: (r) == (array64_2[i]) --> 15901047961728968207 != 12920235861796970207: Mismatch at array64_2[140]=b34de60fdcabdedf gen=dcabdedfb34de60f
test_gen_rand_64:test/unit/SFMT.c:1550: Failed assertion: (r) == (array64_2[i]) --> 16056892601259235855 != 7973511058236476095: Mismatch at array64_2[141]=6ea79a0fded58abf gen=ded58abf6ea79a0f
test_gen_rand_64:test/unit/SFMT.c:1550: Failed assertion: (r) == (array64_2[i]) --> 6741727410782203639 != 7219251473892207964: Mismatch at array64_2[142]=642feef75d8f6d5c gen=5d8f6d5c642feef7
test_gen_rand_64:test/unit/SFMT.c:1550: Failed assertion: (r) == (array64_2[i]) --> 5304134062951985163 != 16667100989749989843: Mismatch at array64_2[143]=e74d700b499c11d3 gen=499c11d3e74d700b
test_gen_rand_64:test/unit/SFMT.c:1550: Failed assertion: (r) == (array64_2[i]) --> 16714931991172784667 != 2497987184069926422: Mismatch at array64_2[144]=22aaa21be7f75e16 gen=e7f75e1622aaa21b
[..]
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 16217721885120513390 != 2067087833999404065: Mismatch at array64_2[692]=1cafc56ee110ec21 gen=e110ec211cafc56e
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 9274943656950834061 != 9246210600625190941: Mismatch at array64_2[693]=8051238d80b7381d gen=80b7381d8051238d
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 8735624157386078780 != 5211080643994921955: Mismatch at array64_2[694]=48517a3c793b2be3 gen=793b2be348517a3c
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 17969465669581198025 != 17795642742515195345: Mismatch at array64_2[695]=f6f6d2c9f9605dd1 gen=f9605dd1f6f6d2c9
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 6906580627730542245 != 34109759994534525: Mismatch at array64_2[696]=792ea55fd91a7d gen=5fd91a7d00792ea5
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 15744512752759354527 != 4455243792546512622: Mismatch at array64_2[697]=3dd4349fda7fbeee gen=da7fbeee3dd4349f
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 11502447904695190185 != 4524713178174646125: Mismatch at array64_2[698]=3ecb02a99fa0e76d gen=9fa0e76d3ecb02a9
test_by_array_64:test/unit/SFMT.c:1586: Failed assertion: (r) == (array64_2[i]) --> 3509278514095987961 != 3646258704899339831: Mismatch at array64_2[699]=329a1cf930b37637 gen=30b37637329a1cf9
test_by_array_64 (arena_new-reentrant): fail
--- pass: 0/12, skip: 0/12, fail: 12/12 ---
```
```
% grep ': fail' b.log
test_gen_rand_32 (non-reentrant): fail
test_gen_rand_32 (libc-reentrant): fail
test_gen_rand_32 (arena_new-reentrant): fail
test_by_array_32 (non-reentrant): fail
test_by_array_32 (libc-reentrant): fail
test_by_array_32 (arena_new-reentrant): fail
test_gen_rand_64 (non-reentrant): fail
test_gen_rand_64 (libc-reentrant): fail
test_gen_rand_64 (arena_new-reentrant): fail
test_by_array_64 (non-reentrant): fail
test_by_array_64 (libc-reentrant): fail
test_by_array_64 (arena_new-reentrant): fail
```

**Comment by jasone** [comment]
Perhaps an endianness issue.

**Comment by davidlt** [comment]
The system is little endian (same as x86_64 and aarch64)

**Comment by jasone** [comment]
Well, it's switchable on powerpc, but you're surely correct that endianness isn't the issue.  I don't have the ability to test on powerpc, but I'm pretty sure that this test has passed on powerpc in times past.  Do you have any idea what is going wrong?

FWIW, we don't use the SFMT code at all, so this failure is harmless.  Maybe we should just remove the code.

**Comment by paravoid** [comment]
This happened while building 5.0.1 for Debian too. Full build log can be found [from Debian's build network](https://buildd.debian.org/status/fetch.php?pkg=jemalloc&arch=ppc64el&ver=5.0.1-1&stamp=1503718442&raw=0).

I bisect'ed this and commit 701daa5298b3befe2aff05ce590533165abb9ba4 seems to be the culprit. Reverting this on top of master makes the test suite failure go away and finish successfully.

**Comment by marxin** [comment]
I've just reached the same problem. I think the current implementation is incomplete, please take a look:
https://github.com/gcc-mirror/gcc/blob/master/gcc/config/rs6000/xmmintrin.h#L1764
That will support _mm_pause for GCC 8.0.

Anyway using both versions provided in xmmintrin.h for POWER8 is still not sufficient to have it working and SFMT.c test still fails. Do I understand it correctly that implementation without CPU_SPINWAIT is more conservative (and probably slower)?

**Comment by paravoid** [comment]
@davidtgoldblatt, any insights here?

**Comment by davidtgoldblatt** [comment]
I can't come up with a plausible theory for why the added spinwait mechanism has observable behavior in the test, but reading the Power ISA documentation[1], the assembly in the bisected-to diff isn't correct anyway (as @marxin points out): the setting of the program-priority register is "sticky", and we never undo the lowering. (I also think that GCC's version is incorrect w.r.t. signals because of related issues).

We could do something similar, but given that we don't have testing here in the first place, I'm inclined to simply not try. I'll put something up reverting the problematic commit tomorrow.

[1] Book II, chapter 3 of the 2.07B or 3.0B ISA documents.

**Comment by davidtgoldblatt** [comment]
Oh I see, it was the altivec define in that commit that broke SFMT, by causing that code to trigger its big-endian paths. In the long run we should probably try to kill the SFMT code in favor of the lcg prng we use and understand outside of testing, but in the short term just killing that definition should work I think.

@paravoid -- I believe that #1043 should fix things for Power (or at least, this particular failure). Could you verify?

**Comment by paravoid** [comment]
Yup, confirmed! Thanks! Is that something that you would apply to the master branch as well?

**Comment by marxin** [comment]
> I can't come up with a plausible theory for why the added spinwait mechanism has observable behavior in the test, but reading the Power ISA documentation[1], the assembly in the bisected-to diff isn't correct anyway (as @marxin points out): the setting of the program-priority register is "sticky", and we never undo the lowering. (I also think that GCC's version is incorrect w.r.t. signals because of related issues).

Can you please explain why GCC's version is incorrect. I can file a bug, PPC maintainers can explain and help ;)

**Comment by marxin** [comment]
Thank you for working on that. Just a small nit: one can't apply the patch on top of 5.0.1 (some refactoring has happened in meantime in spin.h).
Are you planning to backport that (or creating 5.0.2 release)?

**Comment by davidtgoldblatt** [comment]
The reason I think the GCC version is incorrect w.r.t. signals is, I think the following pattern is pretty reasonable:

```
signal(SIGALRM, &set_myself_to_high_priority);
set_priority(low);
ualarm(10000, 0);
// ...
// Many lines of code later, maybe in some other function, maybe in a function written by someone else.
#if CONFIGURE_SCRIPT_DETECTED_MM_PAUSE
_mm_pause();
#else
spin_for_a_little_bit();
#endif
// ...
// We expect the signal to have fired here
high_priority_work();
```

I.e. you know that you're going to be doing unimportant work for the next 10ms or so, but want to be treated regularly afterwards.

After that GCC change, the configure script will pick up a working `_mm_pause()`, and we encounter the risk of the following execution:

```
signal(SIGALRM, &set_myself_to_high_priority);
set_priority(low);
ualarm(10000, 0);
// ...
_mm_pause():
    cur_priority = get_priority();
    set_priority(low);
    // Alarm triggers; signal handler is called.
        set_myself_to_high_priority():
            set_priority(medium);
    set_priority(cur_priority /* == low */);
// ...
// We expect the signal to have fired here
high_priority_work(); // Executes with low priority.
```

Basically, I think it's pretty reasonable for callers to assume that _mm_pause() does not affect execution after it has completed, and that it's also reasonable to change hyperthread priority from a signal handler. The GCC _mm_pause implementation makes it so that these two beliefs are not safe when held at the same time. (Maybe "incorrect" was too strong a word, but it's certainly error-prone in this instance).

**Comment by davidtgoldblatt** [comment]
With respect to master / a 5.0.2 release. Our CI has improved over the past year, to the point where every commit gets testing close to what we'd do for a release. We haven't totally figured out what, if anything, we want a release to mean under those circumstances. I'll try to have a firmer answer in a few days.

Could you clarify why you want a master commit / point release? (E.g. would you take that as a statement that that particular commit would be particularly stable, or better tested, or have better support?).

**Comment by paravoid** [comment]
Not sure which of the two of us you were asking, but speaking from the Debian side: we tend to stick to releases, rather than git snapshots, as these are usually a well-defined point in the history of a project where upstream feels like their code is stable and ready to be deployed to a wider audience. Debian has been stuck to 3.6.0(!) for years and I'm trying to push 5.0.1 to it right now. We can (and often do) backport individual patches on top of a release, which I've already done for 5.0.1 for the two patches I already sent to you, and we could do the same for this bug/patch, but I think to @marxin's point above, this patch doesn't apply to master as-is.

More generally speaking, are you saying that you're contemplating not making releases and just dropping master altogether in the future? In that case, what would you recommend us to include e.g. in a Debian stable release, which goes through a multi-month freeze period, followed by a "released" period that gets no updates except security patches for 3+ years? Are there commits that you may consider appropriate or "more" stable, e.g. before a large refactor or something?

**Comment by munroesj** [comment]
Don't use xmmintrin.h ON POWER in BE

**Comment by munroesj** [comment]
There is a reason of the warning in the header:
/* This header is distributed to simplify porting x86_64 code that
   makes explicit use of Intel intrinsics to powerpc64le.
   It is the user's responsibility to determine if the results are
   acceptable and make additional changes as necessary.
   Note that much code that uses Intel intrinsics can be rewritten in
   standard C or GNU C extensions, which are more portable and better
   optimized across multiple targets.

**Comment by davidtgoldblatt** [comment]
The underlying POWER issue seems to be resolved. I opened #1049 to move the release discussion to.
