### ISSUE TITLE
Intermittent failure:  src/arena.c:351: Failed assertion: "p[i] == 0"

### ISSUE THREAD

**Issue by WesleyHartTX** [jemalloc/jemalloc#766]
b973ec7 on rc-4.5.0. Also  confirmed as failing on 4.4.0.

Environment is Ubuntu 16.04 LTS, kernel 4.4.0-57-generic, glibc 2.23-0ubuntu7, binutils 2.26.1-1ubuntu1~16.04.3.

--with-jemalloc-prefix=je_ --with-malloc-conf=lg_chunk:20 --enable-stats --enable-debug

The asserts only seem to occur when doing aligned allocations in an arena with custom chunk_hooks. Passing MALLOCX_TCACHE_NONE to je_mallocx (our default) makes the failures intermittent, omitting it seems to make them much more likely.

[aligntest.c.txt](https://github.com/jemalloc/jemalloc/files/921085/aligntest.c.txt)

**Comment by jasone** [comment]
The ```mprotect()``` call in ```my_chunk_commit()``` does not zero memory, but the commit hook is required to provide zeroed memory.  From the [manual](http://jemalloc.net/jemalloc.3.html#arena.i.chunk_hooks):

> A chunk commit function conforms to the chunk_commit_t type and commits zeroed physical memory to back pages within a chunk of given size at offset bytes, extending for length on behalf of arena arena_ind, returning false upon success.

I added ```memset(addr, 0, length);``` just before the ```my_chunk_commit()``` return, and it resolves the issue.

**Comment by WesleyHartTX** [comment]
Jason,

Thanks for the quick response!

I've actually toyed with putting that memset() call in our production code; but I neglected to include it when I was assembling the reproducer test. Apologies.

With the memset() in place, I see a (probably) separate problem where the chunk that's allocated for the first je_mallocx() call isn't always re-used after the allocation in it is free'd. The result is that after a few 100,000 alloc/free pairs, I exhaust my limited memory pool. The perplexing things is that on some runs, I get perfect reuse and all allocations fit in that initial chunk, and on some runs I don't.

Do you want full details here, or shall I open a separate issue?

**Comment by jasone** [comment]
We can use this issue to track the exhaustion symptom.  Incidentally, you're probably better off using ```mmap()``` than ```memset()``` to zero the newly committed memory.

Please capture the output of ```malloc_stats_print()``` at the time memory is exhausted, to get some visibility into memory usage, fragmentation, and retained virtual memory.

**Comment by WesleyHartTX** [comment]
Memory exhaustion reproducer:

[exhaust.c.txt](https://github.com/jemalloc/jemalloc/files/922685/exhaust.c.txt)

It may take multiple runs to trigger the out of memory issue.

Output of malloc_stats_print():

[stats.txt](https://github.com/jemalloc/jemalloc/files/922701/stats.txt)

**Comment by jasone** [comment]
#775 fixes this for the master branch.  I'll try to fix it on the dev branch tomorrow.

**Comment by jasone** [comment]
Actually, #775 breaks both macOS and Windows, so I'll have to dig into that first tomorrow.
