### ISSUE TITLE
SEGV + sys hang in jemalloc

### ISSUE THREAD

**Issue by jahunter-m** [jemalloc/jemalloc#815]
Hello, I am trying to drop jemalloc in as the allocator for my project; however, I am seeing (intermittently, but with high probability) a SEGV in one thread and a hang in other threads, where the hanging threads take 100% CPU time in "sys," and apparently can't be attached to or killed. Running "strace", which produces output (attached) before the hang (but can't be detached or killed after the hang!), shows "[????????????????] +++ killed by SIGSEGV +++" in thread 3.

I am attaching the test case that reproduces the issue, on my machine:
  1. (Succeeds): g++ repro.cc -g -o repro -lpthread ; ./repro
  2. (Fails/hangs): g++ repro.cc -g -o repro -lpthread -ljemalloc ; ./repro

I am having trouble debugging the issue, because once the SEGV occurs, the hanging threads can't be attached to, pstacked, or killed. Also, running the repro inside gdb doesn't help, because the failure is just a hang--the debugger doesn't break at the SEGV, and after the SEGV the program doesn't respond to "break" signals from the debugger.

Would someone be able to see if the issue reproduces on their machine, or suggest some further steps I could use to track down the issue on mine?

Versions:
  - Ubuntu 17.04
  - g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
  - Linux 4.10-0-20 generic
  - jemalloc 4.5.0-1-g807a9a3e1751ea0f350a1484a70d86b257d69f62

[repro.zip](https://github.com/jemalloc/jemalloc/files/973860/repro.zip)
[strace_logs.zip](https://github.com/jemalloc/jemalloc/files/973877/strace_logs.zip)

**Comment by jahunter-m** [comment]
The repro is a stress test: the main thread spawns 8 workers, and waits for them to finish. Each worker allocates a block of random size and immediately adds it to the garbage list. If there's already a block at that position on the garbage list, it frees it. Using the default Linux/gcc malloc(), which is slow, the program exits successfully after around 30 seconds. Using jemalloc, which is fast, the program hangs within a few seconds--sometimes before some threads complete their work, sometimes not.

**Comment by jahunter-m** [comment]
The repro fails in branches stable-4, master, and dev; it succeeds in branch stable-3.

**Comment by jahunter-m** [comment]
Git bisect blames commit 62f2d84e7aebaa25df32a0ae882cc856e5218687 , Nov 17, 2016, "Refactor madvise(2) configuration."

**Comment by jahunter-m** [comment]
And, turning off MADV_FREE in the master head (version 4.5.0) (using echo "je_cv_madv_free=no" > config.cache && ./configure -C) causes the repro to succeed.

**Comment by jasone** [comment]
This doesn't reproduce for me.  I'm using Ubuntu 16.04 with g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, the 4.8.0-41-generic kernel, and I hacked jemalloc to ```#define MADV_FREE 8```, since the installed headers don't expose the functionality.  Furthermore, we use ```MADV_FREE``` on FreeBSD, and I wasn't able to reproduce the problem there either.

I looked at the test program pretty closely, and I don't see any issues with it, but I could have missed something regarding memory ordering semantics.

**Comment by jahunter-m** [comment]
Thanks for looking into this. It is possible that this is a regression introduced in Ubuntu 17.04, as I do not recall running into any issues before I upgraded from 16.x--although I can't remember if I stressed the code as much before I upgraded.
