### ISSUE TITLE
Infinite spin when used in parallel with malloc

### ISSUE THREAD

**Issue by DesbyP** [jemalloc/jemalloc#827]
Hi,

I got a big program divided in modules. I wanna use _jemalloc_ in one of my modules but keep the others running with a classic _malloc_.

In this situation an infinite spin occurs in `chunk_dss_max_update` ([see code](https://github.com/jemalloc/jemalloc/blob/master/src/chunk_dss.c#L83))
It is due to an external call to `malloc` and `sbrk` that modifies the location of current program break.

I am using version 4.5.0 on the master branch.

Is jemalloc designed to be the unique allocator of a program or is it a bug?

The module using _jemalloc_ is monothread, in this case can I just remove the `if` condition [line 78](https://github.com/jemalloc/jemalloc/blob/master/src/chunk_dss.c#L78)?

Thanks

**Comment by jasone** [comment]
This sounds similar to the issue described in #802.  Do you know whether the other thread(s) calling ```sbrk()``` decrease the break?  If not, we have multiple issues to fix in that code.

**Comment by DesbyP** [comment]
Yes, a call to `free` leads to a `sbrk` with a negative increment.

Same issue as #802 indeed.

**Comment by jasone** [comment]
I'm going to close this issue as a duplicate; watch #802 for updates.  It's near the top of my todo list, so a fix should be available soon on the stable-4 and dev branches.
