### ISSUE TITLE
Try to cut down on mangling-induced recompilation

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#838]
Changing any source file means that the name-mangling header has changed, which means that the input to every source file has changed, which triggers recompilation. The end result is that changing any source file causes recompilation of every source file.

Instead, we could detect if the name-mangling header has changed before updating it. Since most code changes don't change the set of public symbols, we can cut down on code/compile/test iteration time.

**Comment by jasone** [comment]
The simple way to resolve this is to use file checksums rather than timestamps for dependency tracking, but GNU make doesn't support that AFAIK.  We can simulate such a mechanism, but it's gonna be a bit ugly.

**Comment by davidtgoldblatt** [comment]
I was thinking of just having two name-mangling headers, private_namespace_gen.h and private_namespace.h, and having the rule for the latter copy the former into the latter, but only if they're not equal. Will that do it?
