### ISSUE TITLE
Make witness_assert_lockless calls in error paths reentrancy-safe

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#847]
I happened to touch some of these incidentally, and realized that we still assert locklessness if we fail a reentrant allocation (say, due to ooming).

Instead, we should do checks similar to those on the success paths.

**Comment by jasone** [comment]
This is resolved by fa35463d56be52a3a6e6b513fbb6cc6e63d9bcc7.
