### ISSUE TITLE
Unrealistic stats on dev branch

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#857]
2 stats counters look totally wrong with the current dev branch, e.g. in one of the application we have:
mapped: 412032556869, retained: 75392458752
and on 4.5 they were:
mapped: 102005473280, retained: 1342177280

**Comment by interwq** [comment]
Mapped is fixed in #856. Still looking for retained.

**Comment by interwq** [comment]
Looked through retained stats and didn't see anything wrong. @jasone : it looks to me that retained stats is directly retrieved from extents_npages_get(&arena->extents_retained) (https://github.com/jemalloc/jemalloc/blob/eeefdf3ce89e09ce7cc5c58d2a3730b83045eec1/src/arena.c#L235), so unlikely to get it wrong. I checked astats->retained is always 0 before the arena_stats_accum. Do you think it's simply that we are using way more virtual address space than 4.5? That is ~75G (vs ~1G on 4.5) retained w/ ~100G mapped.

**Comment by interwq** [comment]
Or the other way around, the retained stats was incorrectly low somehow before.

**Comment by jasone** [comment]
We use an exponential series in ```extent_grow_retained()```, so I could imagine retained memory causing total virtual memory being ~2.25X higher in extreme cases for dev versions, relative to 4.x.  It looks like we have a >50X difference here though, so there's probably another explanation.

**Comment by interwq** [comment]
I believe we never move retained extents between arenas. Can a different arena re-use freed chunks with 4.x?

**Comment by jasone** [comment]
No, all the 4.x versions have completely independent arenas, so there's no migration of chunks between them.

**Comment by interwq** [comment]
After a few more debugging sessions, I still see nothing wrong with the retained stats on dev. The big difference in retained between 4.x and dev remains to be explained, but probably no need to delay 5.0 release. On 64 bit I imagine this is less of an issue if at all, but on 32-bit we may reach VAS exhaustion. I'm going to close this and create a separate issue to track that.
