### ISSUE TITLE
Unit Tests fail when configured with --with-lg-page=22

### ISSUE THREAD

**Issue by ghaidinyak** [jemalloc/jemalloc#883]
When I do the following, the unit tests fail. They pass with --with-lg-page=13

./configure --with-lg-page=22
make
make check

**Comment by interwq** [comment]
I believe it's because the pagesize defined is greater than HUGEPAGE. Do we want to support this @jasone ? Or limit the range of lg-page?

**Comment by ghaidinyak** [comment]
Where is HUGEPAGE defined and how do I modify it for cross compiling?

**Comment by jasone** [comment]
Such a large page size is almost certain to work poorly due to external fragmentation.  We don't want to do anything special to enable such large pages, though we might consider forcefully limiting it to be no larger than ```HUGEPAGE```.

**Comment by ghaidinyak** [comment]
Two points, first how is HUGEPAGE defined? X86_64 supports 4K, 2M & 1G huge pages. Powerpc supports 64K, 16M & 16GB pages and ARM supports 64K, 1M & 16M pages.

Second, I tried configuring using --with-lg-page=20 (Hopefully a 2M page) and the unit tests failed. Is a 2MB (typical hugepage on x86_64) supported?

**Comment by jasone** [comment]
This works:
```sh
./configure --with-lg-page=22 --with-lg-hugepage=22 && make all tests && make check
```
We just need to enforce ```PAGE <= HUGEPAGE``` in the configure script.
