### ISSUE TITLE
Question on jemalloc stats.resident and reason of physical memory growth beyond that

### ISSUE THREAD

**Issue by yliu198** [jemalloc/jemalloc#892]
Hi, 

I am trying to use jemalloc and its stats/profiling capability to investigate my application's memory growth issue. 

In my testing, jemalloc usually works well in terms of keeping physical memory footprint low and releasing deallocated memory back to the OS (i.e. freeing physical memory). (So thanks for the great work!)

However, sometimes my application's physical memory started to linearly grow for unknown reason by a few Giga-bytes in an hour or two, which is puzzling me. 

During such a period, I collected jemalloc stats as follows:
---Before the growth:
05/18 23:04:51
Allocated:	459652176	active:	568348672	metadata:	120945664	resident:	814112768	mapped:	4487905280	retained:	3695181824			8183087104
---After the growth:
05/19 02:04:52
Allocated:	459689248	active:	568401920	metadata:	120945664	resident:	814153728	mapped:	4487905280	retained:	3695181824			8183087104
---
Basically, "Allocated" increased 37072, "active" increased 53248, "resident" increased 40960 and rest unchanged. However, meanwhile the OS reported resident memory of the process increased from ~1GBytes to ~4.4GBytes. Btw, I enabled jemalloc profiler in the test and it did not report large amount of malloc activities during the period.

Here are my questions: 
(1) Can jemalloc's stats underestimate the "resident" memory amount used by an application at all, if so can it be so much? 
(2) Otherwise, what could be the possible causes for my applications' strange physical memory growth? I suspect it is some bug that accessed free'ed memory during the period, thus caused the OS to re-map physical pages for large amount of free virtual memory, but unfortunately have not found such bug yet. Is this a possible cause? 
(3) Unlikely, but could there be some logic in my application that caused memory fragmentation?

My application runs on x86_64 linux with kernel version 2.6.32. 

Any suggestion will be appreciated!

-Yong

**Comment by jasone** [comment]
Are there any mapped files that could explain the growth?  If not, the only other idea I have is that transparent huge pages are causing physical memory usage to be much higher than jemalloc's estimate, which is based on 4 KiB pages rather than 2 MiB pages.

**Comment by interwq** [comment]
In addition to what @jasone mentioned, does your program have much memory managed outside of jemalloc e.g. through mmap explicitly? Probably useful to strace and see if large chunk of memory is mmaped by other parts.

**Comment by yliu198** [comment]
Thanks for your quick responses, Jason and interwq!
I collected /proc/$pid/maps file in one of my testing and found no changes at all before and after the physical memory growth. The process should not open/mmap any files during the period too.

**Comment by interwq** [comment]
@yliu198 : You are welcome! re- opened file could be mapped in on demand, during the memory increase, if the program accesses the part of files wasn't accessed before, it could still result in new memory being mapped in.

**Comment by yliu198** [comment]
@interwq ; my application's main job is to process streams of data in memory, it opens only a few small files besides its own log files and it is not mmapping them I think, otherwise I guess I will see the file names in proc//maps, right?

**Comment by davidtgoldblatt** [comment]
Yeah -- if there are *no* large mappings in memory other than code and the heap, then it's probably not delayed page-in.

Does your behavior have any unusual allocation patterns that might trigger an edge case on our end?

**Comment by davidtgoldblatt** [comment]
*your program's behavior

**Comment by yliu198** [comment]
@davidtgoldblatt The application is supposed to be idling during the time, mostly doing heartbeat with remote services. The memory growth happens sporadically. The application may run a night without having the issue, but with about 50% chance it will happen.
Btw the same memory growth happens with tcmalloc as well.

**Comment by yliu198** [comment]
@jasone My system is using huge pages:
grep AnonHugePages /proc/meminfo 
AnonHugePages:  127766528 kB
Does it mean that some 4k size pages could not be returned to the OS even though jemalloc calls madvise, unless the whole huge page of 2M is completely returned?

**Comment by interwq** [comment]
@yliu198 : that is correct. You can try disabling transparent huge pages (assuming that's what you are using) and see if it changes.

**Comment by yliu198** [comment]
@interwq Will try that. Thanks.

**Comment by yliu198** [comment]
Just to let everyone know that disabling transparent huge pages indeed solved my issue. 
Thanks a lot to the jemalloc team!
