### ISSUE TITLE
TSD leak during thread death if the thread never allocates

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#896]
It looks like glibc might free() after invoking all of its pthread destructors, through _dl_deallocate_tls. If the thread never allocates, then we won't be able to get our pthread destructor invoked, so we run the risk of leaking the allocation.

This doesn't matter for threads that allocate or free during their lifetimes, but it's something we should ideally be able to protect against.

**Comment by interwq** [comment]
This was resolved by #911.
