### ISSUE TITLE
Maybe return 0 for nallocx(0, 0) ?

### ISSUE THREAD

**Issue by aidermoi** [jemalloc/jemalloc#898]
I was trying to integrate a piece of software with jemalloc, which calls nallocx(0, 0) at some point.
it crashed with the following stacktrace:
#0  je_s2u_lookup (size=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:794
#1  je_s2u (size=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:810
#2  inallocx (flags=<optimized out>, size=<optimized out>, tsdn=<optimized out>) at src/jemalloc.c:2636
#3  nallocx (size=<optimized out>, flags=<optimized out>) at src/jemalloc.c:2688
#4  0x000000000040064e in main () at main.cpp:4

I found the assert(size != 0) in nallocx() was only triggered only if jemalloc was configured with --enable-debug. Otherwise, it assertion statement will be somehow ignored, which results segmentation fault later on.

Is there a specific reason that we don't allow nallocx with size of 0?
If malloc(0) is legal, can we at least make nallocx not crash? thx!

**Comment by interwq** [comment]
@aidermoi: Thanks for the input. However ```nallocx``` is a non-standard API w/ undefined behavior if input size is 0. The return value 0 in this case means ```exceed the maximum supported size class and/or alignment``` as specified in http://jemalloc.net/jemalloc.3.html.

As for assertions, they are disabled unless in debug mode to avoid runtime overhead (small but matters for core lib like malloc).

**Comment by aidermoi** [comment]
Thanks for the explanation.
