### ISSUE TITLE
Segmentation fault on X86 android 

### ISSUE THREAD

**Issue by seanlee1001** [jemalloc/jemalloc#904]
It reported a SIGSEGV error when running one program on Android 6.0.1 (X86), could you help to check, Thanks.

strdup() calls the malloc() with length strlen()+1, it is a very small size(must be 8).

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004cfdb3 in arena_run_reg_dalloc (ptr=0x7f7dc0844280, run=0x7f7dc0840148) at external/jemalloc/src/arena.c:290
290	external/jemalloc/src/arena.c: No such file or directory.
(gdb) bt
#0  0x00000000004cfdb3 in arena_run_reg_dalloc (ptr=0x7f7dc0844280, run=0x7f7dc0840148) at external/jemalloc/src/arena.c:290
#1  arena_dalloc_bin_locked_impl (junked=true, bitselm=<optimized out>, ptr=0x7f7dc0844280, chunk=0x7f7dc0840000, arena=0x7f7dc0fc0180) at external/jemalloc/src/arena.c:2291
#2  je_arena_dalloc_bin_junked_locked (arena=arena@entry=0x7f7dc0fc0180, chunk=0x7f7dc0840000, ptr=0x7f7dc0844280, bitselm=<optimized out>)
    at external/jemalloc/src/arena.c:2309
#3  0x00000000004bfa79 in je_tcache_bin_flush_small (rem=4, binind=<optimized out>, tbin=<optimized out>, tcache=0x7f7dc0f82000, tsd=0x0) at external/jemalloc/src/tcache.c:133
#4  je_tcache_event_hard (tsd=tsd@entry=0x7f7dc0f8f008, tcache=tcache@entry=0x7f7dc0f82000) at external/jemalloc/src/tcache.c:44
#5  0x00000000004b530f in je_tcache_event (tcache=<optimized out>, tsd=<optimized out>) at external/jemalloc/include/jemalloc/internal/tcache.h:258
#6  je_tcache_alloc_large (zero=<optimized out>, size=<optimized out>, tcache=<optimized out>, arena=<optimized out>, tsd=<optimized out>)
    at external/jemalloc/include/jemalloc/internal/tcache.h:370
#7  je_arena_malloc (tcache=0x7f7dc0f82000, zero=false, size=<optimized out>, arena=<optimized out>, tsd=0x7f7dc0f8f008)
    at external/jemalloc/include/jemalloc/internal/arena.h:1084
#8  je_iallocztm (arena=0x0, is_metadata=false, tcache=0x7f7dc0f82000, zero=false, size=<optimized out>, tsd=0x7f7dc0f8f008)
    at external/jemalloc/include/jemalloc/internal/jemalloc_internal.h:879
#9  je_imalloc (size=<optimized out>, tsd=0x7f7dc0f8f008) at external/jemalloc/include/jemalloc/internal/jemalloc_internal.h:898
#10 imalloc_body (usize=<synthetic pointer>, tsd=<synthetic pointer>, size=<optimized out>) at external/jemalloc/src/jemalloc.c:1410
#11 je_malloc (size=<optimized out>) at external/jemalloc/src/jemalloc.c:1423
#12 0x0000000000499a3b in strdup (str=0x7f7dc0f89c1a "debugfs") at bionic/libc/upstream-openbsd/lib/libc/string/strdup.c:45

**Comment by jasone** [comment]
This is likely due to pre-existing memory corruption, such as a double free.  When the thread cache is flushed, it can cause earlier deallocation errors to trigger crashes like this one.  You can narrow down the origin of the problem by using a debug build of jemalloc so that assertions are enabled, and disabling tcache (set ```MALLOC_CONF=tcache:false``` in the environment prior to launch).

**Comment by interwq** [comment]
Closing assuming not a jemalloc bug. Please feel free to let us know if otherwise.
