### ISSUE TITLE
Deadlock when using dlsym to hook function ?

### ISSUE THREAD

**Issue by spch2008** [jemalloc/jemalloc#916]
#0  0x0000003ee2c0e334 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003ee2c0960e in _L_lock_995 () from /lib64/libpthread.so.0
#2  0x0000003ee2c09576 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000035af405ccc in je_malloc_mutex_lock () at include/jemalloc/internal/mutex.h:101
#4  malloc_init_hard () at src/jemalloc.c:1463
#5  0x00000035af40b065 in malloc_init (num=<value optimized out>, size=<value optimized out>) at src/jemalloc.c:317
#6  ialloc_body (num=<value optimized out>, size=<value optimized out>) at src/jemalloc.c:1560
#7  calloc (num=<value optimized out>, size=<value optimized out>) at src/jemalloc.c:1801
#8  0x0000003ee2401310 in _dlerror_run () from /lib64/libdl.so.2
#9  0x0000003ee240107a in dlsym () from /lib64/libdl.so.2
#10 0x000000000064172b in getenv () at common/libco/co_hook_sys_call.cpp:840
#11 0x00000035af404662 in secure_getenv () at src/jemalloc.c:802
#12 malloc_conf_init () at src/jemalloc.c:1021
#13 0x00000035af405bb5 in malloc_init_hard_a0_locked () at src/jemalloc.c:1333
#14 0x00000035af405dac in malloc_init_hard () at src/jemalloc.c:1469
#15 0x00000035af40b8ce in malloc_init (size=568) at src/jemalloc.c:317
#16 ialloc_body (size=568) at src/jemalloc.c:1560
#17 malloc (size=568) at src/jemalloc.c:1624
#18 0x0000003ee2866e8b in __fopen_internal () from /lib64/libc.so.6
#19 0x0000003ee3c0cd2d in ?? () from /lib64/libselinux.so.1
#20 0x0000003ee3c15c66 in ?? () from /lib64/libselinux.so.1
#21 0x00007fffffffe588 in ?? ()
#22 0x0000000000000002 in ?? () at /root/gcc-4.8.2-with-all-requires/gcc-4.8.2/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:708
#23 0x00007fffffffe588 in ?? ()
#24 0x0000003ee3c04fa3 in _init () from /lib64/libselinux.so.1
#25 0x00007ffff63f34c8 in ?? ()
#26 0x0000003ee200e705 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#27 0x0000003ee2000b3a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#28 0x0000000000000002 in ?? () at /root/gcc-4.8.2-with-all-requires/gcc-4.8.2/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:708
#29 0x00007fffffffe7de in ?? ()
#30 0x00007fffffffe808 in ?? ()
#31 0x0000000000000000 in ?? ()

**Comment by jasone** [comment]
See https://gitter.im/jemalloc/jemalloc?at=594d63994bcd78af563b1286 and the following discussion.  In summary, the ```getenv()``` override at frame 10 triggers allocation, and this breaks jemalloc bootstrapping.   jemalloc has limited reentrancy tolerance, but ```getenv()``` is fundamental to bootstrapping, and the only general workaround would be to provide a mechanism to completely disable ```MALLOC_CONF``` processing.
