### ISSUE TITLE
Make the Git repo better

### ISSUE THREAD

**Issue by notorand-it** [jemalloc/jemalloc#920]
If I go to the Git repo, the ["code" tab](https://github.com/jemalloc/jemalloc), I cannot find any link to the [Release page](https://github.com/jemalloc/jemalloc/releases).
This makes the access to the list of released tarballs rather difficult: I know where it is because I have bookmarked it. But what about the occasional visitor?

**Comment by jasone** [comment]
There is a row of links toward the top of the "code tab" page, currently:
- [2003 commits](https://github.com/jemalloc/jemalloc/commits/dev)
- [4 branches](https://github.com/jemalloc/jemalloc/branches)
- **[41 releases](https://github.com/jemalloc/jemalloc/releases)**
- [67 contributors](https://github.com/jemalloc/jemalloc/graphs/contributors)

Note that there is a link, and that this is a standard GitHub project that we do not have (nor want) direct control over layout.  For a human-created custom entry into jemalloc resources, see [jemalloc.net](http://jemalloc.net/).
