### ISSUE TITLE
MySQL jemalloc5.0 start FAILED

### ISSUE THREAD

**Issue by lj2007331** [jemalloc/jemalloc#921]
CentOS Linux release 7.3.1611 (Core) 
mysql-5.6.36-linux-glibc2.5-x86_64.tar.gz
jemalloc-5.0.0
mysql error log:
terribly wrong...
stack_bottom = 0 thread_stack 0x40000
/usr/local/mysql/bin/mysqld(my_print_stacktrace+0x35)[0x9133a5]
/usr/local/mysql/bin/mysqld(handle_fatal_signal+0x3d8)[0x676458]
/lib64/libpthread.so.0(+0xf370)[0x7feb0d895370]
/usr/local/lib/libjemalloc.so(+0x49c9c)[0x7feb0daebc9c]
/usr/local/lib/libjemalloc.so(+0x4afb6)[0x7feb0daecfb6]
/usr/local/lib/libjemalloc.so(+0x4b174)[0x7feb0daed174]
/usr/local/lib/libjemalloc.so(+0x4c962)[0x7feb0daee962]
/usr/local/lib/libjemalloc.so(free+0x109)[0x7feb0daa91e9]
/lib64/ld-linux-x86-64.so.2(_dl_deallocate_tls+0x58)[0x7feb0df24118]
/lib64/libpthread.so.0(+0x6e07)[0x7feb0d88ce07]
/lib64/libpthread.so.0(+0x6f1f)[0x7feb0d88cf1f]
/lib64/libpthread.so.0(+0x7ea5)[0x7feb0d88dea5]
/lib64/libc.so.6(clone+0x6d)[0x7feb0c55676d]

**Comment by interwq** [comment]
There is no symbol for the jemalloc functions. My best guess would be this is related to some of the fixes we had recently. Can you please the the most recent dev branch and see if it still happens? (if so getting jemalloc symbols would help us identify the issue).

**Comment by jasone** [comment]
Feel free to re-open with additional info that would allow us to investigate.
