### ISSUE TITLE
configure in v5 does not work on Linux

### ISSUE THREAD

**Issue by jaideepmukherjee** [jemalloc/jemalloc#926]
Hi

I made the following changes in configure.ac to fix the build issues.
Note I needed muldefs due to inline in OS headers. I am building on RH55 with gcc 4.8.3.

Thanks
Jaideep

496d495
< LDFLAGS='-Wl,-zmuldefs'
1459c1458
<   AC_CHECK_HEADERS([dlfcn.h], [
---
>   AC_CHECK_HEADERS([dlfcn.h],
1461c1460
<       [AC_CHECK_LIB([dl], [dlsym], [LIBS="$LIBS -ldl"], [have_dlsym="0"])])],
---
>       [AC_CHECK_LIB([dl], [dlsym], [LIBS="$LIBS -ldl"], [have_dlsym="0"])]),

**Comment by jasone** [comment]
See #912 for the initial report of this problem.
