### ISSUE TITLE
Test failure: sdallocx

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#931]
ubuntu(--enable-debug)

=== test/integration/sdallocx ===
test_basic (non-reentrant): pass
test_basic (libc-reentrant): pass
test_basic (arena_new-reentrant): pass
test_alignment_and_size (non-reentrant): pass
test_alignment_and_size (libc-reentrant): pass
Killed
Test harness error: test/integration/sdallocx w/ MALLOC_CONF=""
Use prefix to debug, e.g. JEMALLOC_TEST_PREFIX="gdb --args" sh test/test.sh test/integration/sdallocx
Makefile:490: recipe for target 'check_integration' failed
make: *** [check_integration] Error 1
program finished with exit code 2
elapsedTime=33.494877

**Comment by davidtgoldblatt** [comment]
It's probably just getting OOMed? Those machines aren't that powerful.

**Comment by interwq** [comment]
Hmm. That's plausible however this particular test has happened a number of times (I have seen ~3, @jasone also reported once). If it's really OOMing, we'll need to tweak the sdallocx test.
