### ISSUE TITLE
how can I confirm that new/delete operation are actually replaced by jemalloc lib

### ISSUE THREAD

**Issue by youzp** [jemalloc/jemalloc#934]
I would like to use two c++ source files to generate a dynamic link library, and i want to replace new/delete operations in test01.cpp and test02.cpp with jemalloc, how can I confirm that they are actually replaced?

g++ -O2 -Wall -c -fPIC test01.cpp -std=c++11 -I./
g++ -O2 -Wall -c -fPIC test02.cpp -std=c++11 -I./
g++ -O2 -Wall -shared -o libMytest.so test01.o test02.o -std=c++11 -lpthread -lpcrecpp lib/libjemalloc.a

I use the way of dynamic linking but not found libjemalloc.so
g++ -O2 -Wall -Wl,--as-needed -shared -o libMytest.so test01.o test02.o -std=c++11 -lpthread -lpcrecpp -ljemalloc
$ ldd libCacheAlgo.so 
	linux-vdso.so.1 =>  (0x00007fff75ba5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f157a8ee000)
	libpcrecpp.so.0 => /lib64/libpcrecpp.so.0 (0x00007f157a6e4000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f157a3dc000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f157a1c6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1579e04000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f157ad3c000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f1579ba3000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f15798a1000)

Remove "-Wl,--as-needed"
g++ -O2 -Wall -shared -o libMytest.so test01.o test02.o -std=c++11 -lpthread -lpcrecpp -ljemalloc
$ ldd libCacheAlgo.so 
	linux-vdso.so.1 =>  (0x00007fff109f7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd03b44f000)
	libpcrecpp.so.0 => /lib64/libpcrecpp.so.0 (0x00007fd03b245000)
	**libjemalloc.so.2 => /usr/local/lib/libjemalloc.so.2 (0x00007fd03add6000)**
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd03aace000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd03a7cb000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd03a5b5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd03a1f4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd03b89d000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fd039f92000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd039d8e000)

**Comment by jasone** [comment]
You can print out jemalloc stats to verify that jemalloc is being utilized for the new/delete calls.  The simplest way to test this would be to call ```malloc_stats_print()``` before and after test code, and verify that the allocation request counters match your expectation.  See the [jemalloc(3) manual](http://jemalloc.net/jemalloc.3.html) for API details.

**Comment by youzp** [comment]
thank you!
