### ISSUE TITLE
rocksdb from python, static TLS block

### ISSUE THREAD

**Issue by KenMacD** [jemalloc/jemalloc#955]
Trying to `import rocksdb` in Python results in `cannot
allocate memory in static TLS block` after upgrading to `jemalloc >= 5`

I'm running Arch Linux and `rocksdb` installs the library:

     /usr/lib/librocksdb.so

This library is dynamically linked to `libjemalloc.so..2`, which comes from version `5.0.1`.

Using the `rocksdb` shared library directly seems fine, as `jemalloc` will load on start. For example:

    #include <stdio.h>
    #include "rocksdb/db.h"

    int main(int argc, char **argv) {
        rocksdb::DB* db;
        rocksdb::Options options;
        options.create_if_missing = true;
        rocksdb::Status status = rocksdb::DB::Open(options, "/tmp/testdb", &db);
        printf("%d", status.ok());
    }

Unfortunately when trying to use `rocksdb` through https://github.com/twmht/python-rocksdb it does not work unless `jemalloc` is also setup through `LD_PRELOAD`.

As another workaround I tried to compile `rocksdb` without `jemalloc` support, but although it has a `DISABLE_JEMALLOC` environment variable, it doesn't actually prevent it from linking to `jemalloc` if it can find the library during the build.

(Possibly related to #937 )

**Comment by davidtgoldblatt** [comment]
Yeah, this is the same as #937. I put up a sample fix that works for python (but breaks programs that depend on jemalloc the "right" way) in https://github.com/davidtgoldblatt/jemalloc/commit/dbd61d6a19bce00e3e460852c5b8cf5b30ca76f7 , which might work for you.

Another option would be to LD_PRELOAD libjemalloc.so for python as well, which should fix the issue.

I'll close this for now in favor of #937, but feel free to reopen if there's something unique about this usage in particular.

**Comment by bajrachar** [comment]
@KenMacD - Were you able to fix this issue?

**Comment by KenMacD** [comment]
Hi @bajrachar, I linked to a commit in #937 (https://github.com/KenMacD/jemalloc/commit/7036e64d36b54e75c6428a3c2aa62db0471f1047) that is working for me. I think the official fix is still 'in progress'.
