### ISSUE TITLE
Witness and custom hook

### ISSUE THREAD

**Issue by superjet008** [jemalloc/jemalloc#978]
I use 'arenas.create' to create a new arena,
then set custom extent hooks, 
and finally 'thread.arena' to assign calling thread to the newly created arena, 
but get '<jemalloc>: Should own 0 locks of rank >= 11: extent_grow(13) Aborted'.

If I don't use custom hooks, this won't happen.
Any ideas?

Another question is if I'm setting custom hooks for arena 0, I would get
'<jemalloc>: jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_a.h:151: Failed assertion: "arena != arena_get(tsd_tsdn(tsd), 0, false)"
Aborted'

Thanks in advance.

**Comment by superjet008** [comment]
A gdb session shows the witness depth assertion failure is related to the custom hooks.
There's kind of circular behavior.
A comment on how the witness works would be appreciated.

**Comment by davidtgoldblatt** [comment]
The witness code is there to help us catch lock-ordering issues in debug mode; it makes sure that each mutex has a "rank", and you acquire those mutexes in increasing order of rank.

This assert triggering probably means that you're mallocing from within your extent hooks, and those extent hooks are being invoked from arena 0 (this is not supported). Are you sure you've correctly set your extent hooks to the newly created arena, and not the auto arenas?

**Comment by superjet008** [comment]
I set "narenas:1" in conf and  use the following code to set custom hooks when creating arenas and assert return is 0.
int ret = mallctl("arenas.create", &arena_id, &size, &hooks_ptr, sizeof(extent_hooks_t *));
I'm still not sure how using custom hooks can change the order of acquiring mutexes.

So I cannot use custom hooks with arena 0?

**Comment by davidtgoldblatt** [comment]
To clarify, are you using 'ret' in the code sample above as your custom arena? That's the mallctl error code, not the arena you should be using (which will be stored into arena_id).

arenas.create shouldn't ever tell you it gave you arena 0.

Custom extent hooks are allowed on the automatically created arenas, but they're not allowed to to allocator operations. For custom arenas, allocating within the hooks is somewhat supported (we added functionality to allow it, and internally we rely on that functionality, but I don't want to promise that it will continue to work forever).

**Comment by superjet008** [comment]
Yes, I'm asserting the ret is 0 and get arena id from arena_id.

Since custom created arena doesn't work , I tried 'thread.arena' to get auto created arenas for the threads and set extent hooks on them. There I got arena 0.

Can you elaborate more on 'allocating within the hooks is somewhat supported'?
Like what should be there and what shouldn't?
Thanks.

**Comment by davidtgoldblatt** [comment]
I don't want to commit to anything; to be safely forward-compatible, you shouldn't allocate from within the extent hooks at all.

For now though, allocating from within an extent hook on a manually-created arena works. Even though I can't guarantee that will be the case forever, it's not something we have any plans to change.
