### ISSUE TITLE
Abort during malloc call

### ISSUE THREAD

**Issue by lasarojc** [jemalloc/jemalloc#981]
Hi all.
I am using jemalloc as the allocator for a Java application. While running some native code, the application received an abort signal and cored. The top of the stack is below and, at frame #17 I see an allocation for 16 bytes, exactly what the application is supposed to be doing. I know this is not a lot of information, but I was hoping your trained eyes might be able to relate this stack to one of the bugs fixed since version 3.6.0, which we are running on Centos6.5. I am making the case with my manager to upgrade to the latest stable, and any confirmation from your side would be very helpful. I've only seen this error once over several days of intensive testing, which is to say that I don't know how to consistently repro it, making a pretty lame case for a bug, but, any info/help will be greatly appreciated.

#0  0x000000339ba325e5 in raise () from /lib64/libc.so.6
#1  0x000000339ba33dc5 in abort () from /lib64/libc.so.6
#2  0x00007fcce3d757c5 in ?? () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-1.b13.el6.x86_64/jre/lib/amd64/server/libjvm.so
#3  0x00007fcce3f06a33 in ?? () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-1.b13.el6.x86_64/jre/lib/amd64/server/libjvm.so
#4  0x00007fcce3d7b492 in JVM_handle_linux_signal () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-1.b13.el6.x86_64/jre/lib/amd64/server/libjvm.so
#5  0x00007fcce3d71183 in ?? () from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-1.b13.el6.x86_64/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x000000339be09470 in pthread_mutex_lock () from /lib64/libpthread.so.0
#8  0x00007fcce4bf3f20 in je_malloc_mutex_lock (tsdn=<optimized out>, mutex=0xf578f590b95d90f9) at include/jemalloc/internal/mutex.h:94
#9  je_tcache_bin_flush_small (tsd=0x7fcc877ff690, tcache=<optimized out>, tbin=0x7fcc9a05d3a8, binind=<optimized out>, rem=1) at src/tcache.c:116
#10 0x00007fcce4bf4aeb in je_tcache_event_hard (tsd=<optimized out>, tcache=tcache@entry=0x7fcc9a05d000) at src/tcache.c:45
#11 0x00007fcce4bc12ef in je_tcache_event (tcache=0x7fcc9a05d000, tsd=<optimized out>) at include/jemalloc/internal/tcache.h:249
#12 je_tcache_alloc_small (size=<optimized out>, slow_path=false, zero=false, binind=1, tcache=0x7fcc9a05d000, arena=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/tcache.h:334
#13 je_arena_malloc (slow_path=false, tcache=0x7fcc9a05d000, zero=false, ind=1, size=<optimized out>, arena=0x0, tsdn=<optimized out>) at include/jemalloc/internal/arena.h:1333
#14 je_iallocztm (slow_path=false, arena=0x0, is_metadata=false, tcache=0x7fcc9a05d000, zero=false, ind=1, size=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:967
#15 je_ialloc (slow_path=false, zero=false, ind=1, size=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:979
#16 ialloc_body (slow_path=false, usize=<synthetic pointer>, tsdn=<synthetic pointer>, zero=false, size=<optimized out>) at src/jemalloc.c:1520
#17 malloc (size=<optimized out>) at src/jemalloc.c:1559

(gdb) info registers
rax            0xf578f590b95d90f9       -758586535277915911
rbx            0x10     16
rcx            0x7fcc877ff690   140516423366288
rdx            0x7fccb97d1d58   140517262040408
rsi            0x288    648
rdi            0xf578f590b95d90f9       -758586535277915911
rbp            0x7fcc9a05d000   0x7fcc9a05d000
rsp            0x7fcc877fdc30   0x7fcc877fdc30
r8             0x7fcc9f3f9900   140516821801216
r9             0x7fcc9a062e88   140516734152328
r10            0x7fcc14c00000   140514498183168
r11            0x1bd0   7120
r12            0x7fcca3834dc0   140516893347264
r13            0x10     16
r14            0x1      1
r15            0x7fcc9a05d048   140516734128200
rip            0x7fcce4bc12ef   0x7fcce4bc12ef <malloc+639>
eflags         0x206    [ PF IF ]
...

**Comment by interwq** [comment]
Hi, this type of fault is often from application induced heap corruption (e.g. double free). Usually sanitizers like ASAN are very helpful in figuring out what's going on, however for java it might not have much information.

You can also try running debug build of jemalloc, which does additional sanity checks and catches corruptions earlier.

**Comment by lasarojc** [comment]
Thanks for the suggestions. I will start by running the debug build in a stress test. Will close the issue until I am sure it is not an application problem.
