### ISSUE TITLE
Total memory allocated stats 

### ISSUE THREAD

**Issue by RajeevRastogi** [jemalloc/jemalloc#988]
I have one application (say A1), which uses jemalloc for memory allocation. This application (A2) gets integrated with customer application and they use malloc for memory allocation.
We want to give two interfaces to customer in order to get total memory allocated by application A1 (i.e. total memory allocated by jemalloc).
At the same time, we want to restrict memory allocated by jemalloc.

So is there any way 
1. To get total memory allocated by jemalloc?
2. To restrict amount of memory to be allocated by jemalloc. If demand for memory goes beyond set memory, we can return error.

If there is no existing way, then is it possible to slightly modify source code to get same?

Thanks and Regards,
Kumar Rajeev Rastogi

**Comment by RajeevRastogi** [comment]
Hello community, this is my first mail to this community. So I am not sure if I have sent mail in right format. Excuse me for any  of my mistake.
Please reply my query or let me know if I need to post this query somewhere else?
I want below information:
1. How to get total memory allocated by jemalloc?
2. How to restrict amount of memory to be allocated by jemalloc. If demand for memory goes beyond threshold, we can return error.

**Comment by interwq** [comment]
@RajeevRastogi : please see answers below. Also, jemalloc developers are usually around here as well: https://gitter.im/jemalloc/jemalloc
1) to get memory allocated, see http://jemalloc.net/jemalloc.3.html#stats.allocated, and http://jemalloc.net/jemalloc.3.html#stats.resident. Note that this needs to be compiled with stats, which is enabled by default.
2) To limit RSS accurately might not be trivial in this case, you can check [extent hooks](http://jemalloc.net/jemalloc.3.html#arena.i.extent_hooks) which can be customized to do so.

**Comment by RajeevRastogi** [comment]
On Aug 15, 2017 12:23 AM, "Qi Wang" <notifications@github.com> wrote:

Thanks Qi Wang for your response.

> @RajeevRastogi : please see answers below. Also, jemalloc developers are
usually around here as well: https://gitter.im/jemalloc/jemalloc
>
> to get memory allocated, see
http://jemalloc.net/jemalloc.3.html#stats.allocated, and
http://jemalloc.net/jemalloc.3.html#stats.resident. Note that this needs to
be compiled with stats, which is enabled by default.

Yes I could get these using mallctl API. One question in order to find
exact memory allocated, is it sufficient to get only stat.alllcated? I see
there are so many other similar parameters including stat.resident.

> To limit RSS accurately might not be trivial in this case, you can check
extent hooks which can be customized to do so.

Sorry I couldn't get this. Can you please give some examples.

**Comment by davidtgoldblatt** [comment]
"Memory allocated" is something of a fuzzy concept; stats.allocated is (more or less) the sum of allocations that have not been freed; stats.resident is (more or less) the pages that we act as if are backed by physical pages.

> Sorry I couldn't get this. Can you please give some examples.

You might want to check the test cases in the extent code to see how extent hooks are used. There's also a couple open-source projects that use them (hhvm is one).

**Comment by RajeevRastogi** [comment]
On Aug 16, 2017 1:53 AM, "David Goldblatt" <notifications@github.com> wrote:
>
> "Memory allocated" is something of a fuzzy concept; stats.allocated is
(more or less) the sum of allocations that have not been freed;
stats.resident is (more or less) the pages that we act as if are backed by
physical pages.
>>
>> Sorry I couldn't get this. Can you please give some examples.
>
> You might want to check the test cases in the extent code to see how
extent hooks are used. There's also a couple open-source projects that use
them (hhvm is one).

Still I am confused.
Do you mean we need to change jemalloc related source code for this?
Currently we have been just linking only jemalloc library to use it.
Any direct pointer regarding this will be really helpful.

**Comment by davidtgoldblatt** [comment]
> Sorry I couldn't get this. Can you please give some examples.

You may want to Google around on terms like"resident set size", "virtual memory", and "allocator fragmentation". The memory we get from the OS (which is more or less what stats.resident) is not necessarily equal to the sum of the memory that your program has allocated but not freed (which is more or less what stats.allocated means).

> Still I am confused.
> Do you mean we need to change jemalloc related source code for this?
> Currently we have been just linking only jemalloc library to use it.
> Any direct pointer regarding this will be really helpful.

You don't need to change the jemalloc source code for this. You might want to take a look at the folly library's JemallocNodumpAllocator: https://github.com/facebook/folly/blob/master/folly/experimental/JemallocNodumpAllocator.h and https://github.com/facebook/folly/blob/master/folly/experimental/JemallocNodumpAllocator.cpp . The extent hooks can replace OS system calls (so, instead of getting raw memory directly from the OS by calling `sbrk` or `mmap`, we get it from calling the extent hook you specify). In your case, you would change the allocation hook to start refusing to allocate more memory when you're about to hit your application limit.

I would recommend reading the jemalloc man page at http://jemalloc.net/jemalloc.3.html . It does a good job of covering a lot of this stuff. If you have more specific questions about the meaning of the documentation or API semantics, we're happy to help.

**Comment by RajeevRastogi** [comment]
On Aug 16, 2017 9:49 AM, "David Goldblatt" <notifications@github.com> wrote:
>  The memory we get from the OS (which is more or less what
stats.resident) is not necessarily equal to the sum of the memory that your
program has allocated but not freed (which is more or less what
stats.allocated means).

I got these stat using mallctl API. But in order to always get recent stat,
I had to use below calls:
mallctl("thread.tcache.flush",NULL,NULL,NULL,0)
mallctl("epoch", NULL,NULL,&epoch,&Len)

I am worried that these will degrade performance because thread cache will
be flushed. Am I correct? If yes, is there any way to avoid this?

> The extent hooks can replace OS system calls (so, instead of getting raw
memory directly from the OS by calling sbrk or mmap, we get it from calling
the extent hook you specify). In your case, you would change the allocation
hook to start refusing to allocate more memory when you're about to hit
your application limit

So in this case we will have to maintain our self how much memory was
allocated and then take decision to discard? Am I correct?

**Comment by interwq** [comment]
Flushing thread cache will incur some overhead, so it's not recommended to do so very frequently. For the use case of getting accurate stats, it shouldn't be an issue in practice.

For customized extent hooks, you can track memory usage in the user defined hooks, e.g. accounting when map new pages, or purging unused pages.

**Comment by amosbird** [comment]
> I got these stat using mallctl API. But in order to always get recent stat, I had to use below calls: mallctl("thread.tcache.flush",NULL,NULL,NULL,0) mallctl("epoch", NULL,NULL,&epoch,&Len)

hmm, after using these calls I still cannot get recent stats.

```
#include <iostream>
#include <jemalloc/jemalloc.h>
#include <malloc.h>
#include <string.h>
#include <sys/mman.h>

int main() {
    int epoch = 1;
    for (auto i = 0ul; i < 100000; ++i) {
        void* ptr = 0;
        int ret = posix_memalign(&ptr, 16, 100000);
        size_t sz, allocated, active, metadata, resident, mapped;
        sz = sizeof(size_t);
        mallctl("thread.tcache.flush", NULL, NULL, NULL, 0);
        mallctl("epoch", NULL, NULL, &epoch, sizeof(epoch));
        if (mallctl("stats.allocated", &allocated, &sz, NULL, 0) == 0
            && mallctl("stats.active", &active, &sz, NULL, 0) == 0
            && mallctl("stats.metadata", &metadata, &sz, NULL, 0) == 0
            && mallctl("stats.resident", &resident, &sz, NULL, 0) == 0
            && mallctl("stats.mapped", &mapped, &sz, NULL, 0) == 0) {
            fprintf(stderr,
                "Current allocated/active/metadata/resident/mapped: %zu/%zu/%zu/%zu/%zu\n",
                allocated, active, metadata, resident, mapped);
        }
    }
}
```

**Comment by stoperro** [comment]
@amosbird I copied you code and was getting same result. Turns out `mallctl("epoch", ...` was failing on my system (checked result code) as epoch needs to be  `size_t` and on 64-bit system `int` was just too small. After changing to `size_t epoch = 1` values started to change.
