### ISSUE TITLE
jemalloc 5.0.1  multiple definition of `je_spin_adaptive'

### ISSUE THREAD

**Issue by anysql** [jemalloc/jemalloc#991]
src/extent_dss.pic.o: In function `je_spin_adaptive':
/data/jemalloc-5.0.1/include/jemalloc/internal/spin.h:20: multiple definition of `je_spin_adaptive'
src/jemalloc.pic.o:/data/jemalloc-5.0.1/include/jemalloc/internal/spin.h:20: first defined here
collect2: ld returned 1 exit status
make: *** [lib/libjemalloc.so.2] Error 1
make: *** Waiting for unfinished jobs....

get the above error under gcc 4.1.2 on CentOS 5

#ifndef JEMALLOC_INTERNAL_SPIN_H
#define JEMALLOC_INTERNAL_SPIN_H

#ifdef JEMALLOC_SPIN_C_
#  define SPIN_INLINE extern inline
#else
#  define SPIN_INLINE inline
#endif

#define SPIN_INITIALIZER {0U}

typedef struct {
        unsigned iteration;
} spin_t;

SPIN_INLINE void
spin_adaptive(spin_t *spin) {
        volatile uint32_t i;

        if (spin->iteration < 5) {
                for (i = 0; i < (1U << spin->iteration); i++) {
                        CPU_SPINWAIT;
                }
                spin->iteration++;
        } else {
#ifdef _WIN32
                SwitchToThread();
#else
                sched_yield();
#endif
        }
}

#undef SPIN_INLINE

#endif /* JEMALLOC_INTERNAL_SPIN_H */

change spin_adaptive to be static to avoid compile error

**Comment by anysql** [comment]
spin.h was included in multiple files : extent_dss.c , jemalloc.c

**Comment by davidtgoldblatt** [comment]
Should be fixed by #980.
