### ISSUE TITLE
can't find  jemalloc.h

### ISSUE THREAD

**Issue by stonedreamforest** [jemalloc/jemalloc#996]
have any release version for windows ?

**Comment by davidtgoldblatt** [comment]
I don't totally understand the question; we test on Windows as part of our continuous integration process. All our recent releases should work on Windows.

**Comment by stonedreamforest** [comment]
i download this:
[https://github.com/jemalloc/jemalloc/releases/download/5.0.1/jemalloc-5.0.1.tar.bz2](https://github.com/jemalloc/jemalloc/releases/download/5.0.1/jemalloc-5.0.1.tar.bz2)

and  i can't find ``` jemalloc.h``` in the ```jemalloc-5.0.1\include\jemalloc```directory

**Comment by davidtgoldblatt** [comment]
jemalloc.h is a generated file. To generate it, you'll need to follow the instructions in INSTALL.md (note that you'll also need a mingw/msys2 installation for the unix-y parts, since you're on Windows).

**Comment by stonedreamforest** [comment]
I don't know how to build from windows，but I build it successfully on MAC.
thanks;)

**Comment by work-krishna** [comment]
for Ubuntu 24.04, I followd this and it worked for me,

```
sudo apt-get -y install autoconf libxslt-dev xsltproc docbook-xsl
git clone https://github.com/jemalloc/jemalloc.git
cd jemalloc
autoconf
./configure
make dist
sudo make install
```
